!$RDBIH
      SUBROUTINE RDBIH
!********1*********2*********3*********4*********5*********6*********7**
! RDBIH            ??/??/83            0000.0    PGMR - BILL EDDY
!                  02/01/84            0000.0    PGMR - BILL EDDY
!
! FUNCTION:        READ HEADER RECORD ON BIH TABLES FILE AND DETERMINE:
!                   . START AND END DATES FOR TABLE DATA FOR THIS RUN
!                   . CORE REQUIREMENTS FOR TABLE DATA FOR THIS RUN
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL(L)
      SAVE
!
      CHARACTER*4 KGDYN,KTBLE,CBUF
      CHARACTER*4 KIONI,KND
!
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/BIHTBL/IA1UTC,JA1UTC,IPOLA1,JPOLA1,IFLUXS,JFLUXS,IFLXAP,   &
     &              JFLXAP,IFLXKP,JFLXKP,IIONO,JIONO,                   &
     &              NVR(6),NUTC  ,IBIH  ,JBIH  ,                        &
     &              IFLUX ,JFLUX ,IBHSYS,IBHDAT,IBHTIM,IFLXSF,          &
     &              IBIHTL(2),IBIHHR,JBIHHR,NXBIHT
      COMMON/DTMTIM/ISTDRG,IENDRG
      COMMON/COREQ /NCHRLY,MAXUTC,MAXUT1,MAXFLX,MAXDSC,KORSUM(3),       &
     &              KORSM2(3),NXCORQ
      COMMON/ION2EL/LIONC,LFRQOP,lFRQOF,NXIONL
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/LICASE/LINT(2),LCASE(18),NXLCAS
      COMMON/TIMDAT/KYMD,KHMS,ICPU,IO,IRUNB,IRUNE,ITBLB,ITBLE,IARCT1,   &
     &              IARCT2,IDATAB,IDATAE,NXTIME
      COMMON/UNITS /IUNT01,IUNT02,IUNT03,IUNT05,IUNT06,IUNT07,IUNT11,   &
     &              IUNT12,IUNT15,IUNT16,                               &
     &              IUNT30,IUNT31,IUNT39,IUNT40,IUNT41,IUNT42,IUNT43,   &
     &              IUNT50,IUNT52,IUNT53,IUNT60,IUNT90,IUNT91,IUNT99,   &
     &              ILINE(2),IPAGE(2),MLINEP(2),MAXCOL(2),IUNT17,       &
     &              IUNT70,IUNT71,                                      &
     &              IUNT88,NXUNIT
!
      DIMENSION IBUF(48),IDATES(12),ISFAVG(5),CBUF(2)
      INTEGER*4 IBUF_B32(48)
!
      DATA KGDYN,KTBLE/'GDYN','TBLE'/
      DATA KIONI,KND/'IONI','ND  '/
      DATA ISFAVG/55,161,161,81,81/
      DATA TSTBIH/0.1250D0/
!
      EQUIVALENCE(IDATES(1),IA1UTC)
!     EQUIVALENCE(IBUF(1),CBUF(1))
      EQUIVALENCE(IBUF_B32(1),CBUF(1))
!
!**********************************************************************
! START OF EXECUTABLE CODE
!**********************************************************************
      LTBION=.FALSE.
! READ TABLES FIlE TO DETERMINE WHETHER  NEW TABLES WITH IONOSPHERIC DAT
! OLD TABLES IS BEING USED. IF NEW TABLES IS BEING USED SET LTBION TO TR
  100 CONTINUE
!     READ(IUNT02,ERR=105,END=200)IBUF(1),IBUF(2)
      READ(IUNT02,ERR=105,END=200)IBUF_B32(1),IBUF_B32(2)
      IBUF(1) = IBUF_B32(1)
      IBUF(2) = IBUF_B32(2)
!        print*,ibuf_b32(1),ibuf_b32(2)
!        print*,ibuf(1),ibuf(2)
      IF(CBUF(1).EQ.KIONI.AND. CBUF(2).EQ.KND) THEN
        LTBION=.TRUE.
        GO TO 200
      ELSE
        GOTO 100
      ENDIF
  105 STOP
  200 CONTINUE
      REWIND IUNT02
! IF OLD TABLES IS BEING USED AND IONOSPHERIC OPTION IS SELECED WRITE
! ERROR MESSAGE AND STOP.
      IF(.NOT.LTBION.AND.LIONC)GOTO 60400
! FOR LARGE RUNS AND DTM APPLICATION LDRG CONTROLS
! THE REDUCTION OF 3-HOURLY KP VALUES STORAGE TIMES DOWN TO TIMES
! SPECIFIED ON THE INTCOM CARD
!
      LDRG=.FALSE.
      IF(LINT(1).AND.LCASE(15))LDRG=.TRUE.
      IF(LINT(1).AND.LCASE(16))LDRG=.TRUE.
! READ HEADER RECORD FROM TABLE FILE
!
!     READ(IUNT02,END=60000) IBUF
      READ(IUNT02,END=60000) IBUF_B32
      DO KKK=1,48
          IBUF(KKK) = IBUF_B32(KKK)
      ENDDO
!     print*, ibuf_b32
!     print*, ibuf

      IF(CBUF(1).NE.KGDYN .AND. CBUF(2).NE.KTBLE) GO TO 60100
! IF NEW TABLES CONTAINING IONOSPHERIC DATA IS BEING READ NEW HEADER REC
! FORMAT ELSE READ OLD HEADER RECORD FORMAT.
      IF(LTBION)THEN
! LOAD START AND END TIMES FOR TABLES INTO COMMON BIHTBL
        DO 210 I=1,12
        IDATES(I)=IBUF(I+2)
  210   CONTINUE
! LOAD NUMBER OF VARIABLES PER RECORD INTO COMMON BIHTBL
        DO 220 I=1,6
        NVR(I)=IBUF(I+14)
  220   CONTINUE
! SAVE NUMBER OF A1-UTC VALUES ON FILE
        NUTC=IBUF(21)
!
        IBHSYS=IBUF(23)
        IBHDAT=IBUF(24)
        IBHTIM=IBUF(25)
! LOAD TITLE INFORMATION INTO COMMON/BIHTBL/
        IBIHTL(1)=IBUF(29)
        IBIHTL(2)=IBUF(30)
! LOAD THE INVERSE DATA RATE (DAYS/VALUE) FOR POLE, A1UT1, AND OTHER
! EARTH ORIENTATION PARAMETERS.
        IBHINT=IBUF(31)
      ELSE
! LOAD START AND END TIMES FOR TABLES INTO COMMON BIHTBL
        DO 230 I=1,10
        IDATES(I)=IBUF(I+2)
  230   CONTINUE
! LOAD NUMBER OF VARIABLES PER RECORD INTO COMMON BIHTBL
        DO 240 I=1,6
        NVR(I)=IBUF(I+12)
  240   CONTINUE
! SAVE NUMBER OF A1-UTC VALUES ON FILE
        NUTC=IBUF(19)
!
        IBHSYS=IBUF(21)
        IBHDAT=IBUF(22)
        IBHTIM=IBUF(23)
! LOAD TITLE INFORMATION INTO COMMON/BIHTBL/
        IBIHTL(1)=IBUF(27)
        IBIHTL(2)=IBUF(28)
! LOAD THE INVERSE DATA RATE (DAYS/VALUE) FOR POLE, A1UT1, AND OTHER
! EARTH ORIENTATION PARAMETERS.
        IBHINT=IBUF(29)
      ENDIF
      IF(IBHINT.LT.3) GOTO 60200
!
!
! DETERMINE START DATE FOR POLE/A1UT1 DATA THAT IS AT LEAST 32 DAYS
! AND 3 INTERVALS PRIOR TO THE RUN AND THAT ALSO LANDS ON A BIH INTERVAL
! (32 DAYS PLUS 3 INTERVALS IS USED TO SPAN 32 DAY EPHEMERIS RECORDS AND
! TO ALLOW INTERPOLATION AT FIRST POINT). THIS ALSO DETERMINES DATES
! FOR OTHER EARTH ORIENTATION PARAMETERS: EOPDEP, EOPDPS.
!
! * NOTE ALL CALCULATIONS FOR A1UT1 AND POLE AND EOP'S WILL BE DONE
!        IN HOURS.
!
      IPOLD=IPOLA1/100
      IPOLH=IPOLA1-IPOLD*100
      CALL DIFF(IPOLD,0,IRUNB,0,NDAYS,NSEC)
      ISUBH1=(768/IBHINT +1)
      ISUBHR=ISUBH1*IBHINT + 2*IBHINT
      NHOUR1=(NDAYS*24 - IPOLH)/IBHINT
      NHOURS=NHOUR1*IBHINT - ISUBHR
! TEST TO SEE IF START OF POLE DATA REQUESTED IS BEFORE ACTUAL POLE DATA
      IF(NHOURS.LT.0) GOTO 60300
!
      IHOURS=IPOLH + NHOURS
      NDAYS=IHOURS/24
      IBIHHR=MOD(IHOURS,24)
      ITBLBD=IPOLD
      CALL ADDYMD(ITBLBD,NDAYS)
      IBIH=ITBLBD
      ITBLB=ITBLBD*100 + IBIHHR
! DETERMINE END DATE FOR POLE A1UT1 DATA FOR THIS RUN
      CALL DIFF(IPOLD,0,IRUNE,0,NDAYS,NSEC)
      NHOUR1=(NDAYS*24 -IPOLH)/IBHINT
      NHOURS=(NHOUR1+1)*IBHINT + ISUBHR
      IHOURS=IPOLH + NHOURS
      NDAYS=IHOURS/24
      JBIHHR=MOD(IHOURS,24)
      ITBLED=IPOLD
      CALL ADDYMD(ITBLED,NDAYS)
      JBIH=ITBLED
      ITBLE=ITBLED*100 + JBIHHR
!
! DETERMINE START AND END DATES FOR FLUX DATA THAT INCLUDES SPACE FOR
! COMPUTING SOLAR FLUX AVERAGES
!
      IFLUX=IRUNB
      IF(LDRG) IFLUX=ISTDRG
! IATDEN IS PASSED FROM RD50A1 IT IS ONE OF THE FOLLOWING:10,20,30,40,50
! IT MUST BE MADE TO BE 1,2,3,4,OR 5 TO ACCESS THE ARRAY ISFAVG
      IF(IATDEN.EQ.42.OR.IATDEN.EQ.52.OR.IATDEN.EQ.62) THEN
! CALCULATE FLUX NEEDED FOR DTM END OF INTERVAL AVERAGE
        NDAYS=80
        CALL ADDYMD(IFLUX,-NDAYS)
        JFLUX=IRUNE
        IF(LDRG) JFLUX=IENDRG
        CALL ADDYMD(JFLUX,40)
      ELSE
        IATDN=IATDEN/10
        NDAYS=ISFAVG(IATDN)/2
        CALL ADDYMD(IFLUX,-NDAYS)
        JFLUX=IRUNE
        IF(LDRG) JFLUX=IENDRG
        CALL ADDYMD(JFLUX,NDAYS)
      ENDIF
!
! DETERMINE DYNAMIC ALLOCATION REQUIREMENTS FOR TABLES
!
! A1-UTC
      MAXUTC=(JBIH/10000-IBIH/10000+1)*2+3
! PRIOR TO 1972 THERE COULD BE MORE THAN 2 A1-UTC CHANGES PER YEAR SO
! EXTRA SPACE IS ALLOCATED
      IF(IBIH.LT.720000) MAXUTC=MAXUTC+50
      MAXUTC= MIN(MAXUTC,NUTC)
! A1-UT1 AND POLAR MOTION
      CALL DIFF(IBIH,0,JBIH,0,NDAYS,NSEC)
      NHOUR1=NDAYS*24
      NHOURS=NHOUR1+(JBIHHR-IBIHHR)
      MAXUT1=NHOURS/IBHINT  + 1
! FLUX DATA
      CALL DIFF(IFLUX,0,JFLUX,0,NDAYS,NSEC)
      MAXFLX=NDAYS+1
      RETURN
! END OF FILE ENCOUNTERED
60000 WRITE(IUNT06,80100)
      STOP
! INCORRECT HEADER ON BIH TABLES
60100 WRITE(IUNT06,80200) IBUF(1),IBUF(2)
      STOP
! BIH POLE, A1UT1, EOPDEP, AND EOPDPS INTERVAL IS TO SMALL
60200 WRITE(IUNT06,80300) IBHINT,TSTBIH
      WRITE(IUNT06,80400)
      STOP
! START OF REQUESTED POLE DATA IS BEFORE AVAILABLE POLE DATA
60300 WRITE(IUNT06,80500)
      STOP
! IONOSPHERIC OPTION SELECTED BUT TABLES INPUT DOES NOT CONTAIN
! IONOSPHERIC INDICES
60400 WRITE(IUNT06,80600)
      STOP
! FORMATS
80100 FORMAT(5X,'UNEXPECTED END OF FILE ENCOUNTERED WHILE TRYING TO ', &
     &'READ BIH TABLES FILE' )
80200 FORMAT(5X,'INCORRECT HEADER ENCOUNTERED ON BIH TABLES FILE ',2A4)
80300 FORMAT(5X,'RDBIH: BIH A1UT1-POLE INTERVAL IS TOO SMALL ',2D24.16)
80400 FORMAT(5X,' THE MINIMUM INTERVAL IS 3 HOURS ')
80500 FORMAT(1X,'***** ABNORMAL TERMINATION IN SUBROUTINE RDBIH **',    &
     &     '***',/,' REQUESTED START DATE OF POLE VALUES IS BEFORE',    &
     &     ' START DATE OF ACTUAL POLE VALUES AVAILABLE FROM THE ',     &
     &     ' GEODYN TABLES FILE')
80600 FORMAT(1X,'THE IONOSPHERIC OPTION WAS SELECTED BUT BIH TABLES ', &
     &'USED DOES NOT CONTAIN',/,' IONOSPHERIC INDICES. EXECUTION ', &
     &' TERMINARING IN RDBIH.')
      END
