!$RDFLUX
      SUBROUTINE RDFLUX(FLUX,IHEADR)
!********1*********2*********3*********4*********5*********6*********7**
! RDFLUX           01/15/79            7902      PGMR - BILL EDDY
!
! FUNCTION:     READ SOLAR FLUX AND MAGNETIC FLUX FROM DISK FILE
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   FLUX    I/O        DUMMY ARRAY AS INPUT/
!                      ARRAY CONTAINING FLUX DATA AS OUTPUT
!   NFLUX    I         DIMENSION OF FLUX ARRAY
!   IHEADR   I         INDICATOR FOR TYPE OF FLUX TO BE READ
!                        1 = SOLAR FLUX
!                        2 = MAGNETIC FLUX(AP)
!                        3 = MAGNETIC FLUX(KP)
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL(L)
      SAVE
!
      INTEGER IBUF2
!
      CHARACTER*8 HEADR,HEADER
!
      DIMENSION FLUX(1)
      DIMENSION IBUF2(96),HEADR(3),NDAYM(12)
!
      INTEGER*4 NREC_B32, NREM_B32, NFLUXS_B32
      INTEGER*4 IDUM_B32, IBUF2_B32(96)
!
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/BIHTBL/IA1UTC,JA1UTC,IPOLA1,JPOLA1,IFLUXS,JFLUXS,IFLXAP,   &
     &              JFLXAP,IFLXKP,JFLXKP,IIONO,JIONO,                   &
     &              NVR(6),NUTC  ,IBIH  ,JBIH  ,                        &
     &              IFLUX ,JFLUX ,IBHSYS,IBHDAT,IBHTIM,IFLXSF,          &
     &              IBIHTL(2),IBIHHR,JBIHHR,NXBIHT
      COMMON/COREQ /NCHRLY,MAXUTC,MAXUT1,MAXFLX,MAXDSC,KORSUM(3),       &
     &              KORSM2(3),NXCORQ
      COMMON/TIMDAT/KYMD,KHMS,ICPU,IO,IRUNB,IRUNE,ITBLB,ITBLE,IARCT1,   &
     &              IARCT2,IDATAB,IDATAE,NXTIME
      COMMON/UNITS /IUNT01,IUNT02,IUNT03,IUNT05,IUNT06,IUNT07,IUNT11,   &
     &              IUNT12,IUNT15,IUNT16,                               &
     &              IUNT30,IUNT31,IUNT39,IUNT40,IUNT41,IUNT42,IUNT43,   &
     &              IUNT50,IUNT52,IUNT53,IUNT60,IUNT90,IUNT91,IUNT99,   &
     &              ILINE(2),IPAGE(2),MLINEP(2),MAXCOL(2),IUNT17,       &
     &              IUNT70,IUNT71,                                      &
     &              IUNT88,NXUNIT
!
      DATA HEADR/'FLUXS   ','FLUXAP  ','FLUXKP  '/
      DATA NDAYM/31,28,31,30,31,30,31,31,30,31,30,31/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!
      IF (IHEADR.LT.3) GO TO 40
!
! SKIP FLUXAP DATA IF FLUXKP REQUESTED
!
      READ(IUNT02,END=60100) HEADER,NREC_B32,NREM_B32,NFLUXS_B32
      NREC = NREC_B32
      NREM = NREM_B32
      NFLUXS = NFLUXS_B32
!     print*, nrec_b32, nrem_b32, nfluxs_b32
!     print*, nrec, nrem, nfluxs

      IF(HEADER.NE.HEADR(2)) GO TO 60000
      DO 20 I=1,NREC
!     READ(IUNT02,END=60100)IBUF2
      READ(IUNT02,END=60100)IBUF2_B32
      DO KKK=1,96
          IBUF2(KKK) = IBUF2_B32(KKK)
      ENDDO
   20 END DO
   40 CONTINUE
!
! READ FLUX HEADER
!
       READ(IUNT02,END=60100) HEADER,NREC_B32,NREM_B32,NFLUXS_B32
      NREC = NREC_B32
      NREM = NREM_B32
      NFLUXS = NFLUXS_B32
!     print*, nrec_b32, nrem_b32, nfluxs_b32
!     print*, nrec, nrem_b32, nfluxs
      IF(HEADER.NE.HEADR(IHEADR)) GO TO 60000
      NVREC=NVR(IHEADR+3)/32
      IND=0
      IYMB=IFLUX/100
      IYME=JFLUX/100
! READ FLUX DATA
      DO 200 I=1,NREC
!     READ(IUNT02,END=60100) IBUF2
      READ(IUNT02,END=60100) IBUF2_B32
      DO KKK=1,96
          IBUF2(KKK) = IBUF2_B32(KKK)
      ENDDO
!     print*, ibuf2
!     print*, ibuf2_b32
      IF(I.EQ.NREC) NVREC=NREM/32
      K1=-31
      K2=0
      DO 100 J=1,NVREC
      K1=K1+32
      IYYMM=IBUF2(J*32)
      IF(IYYMM.LE.4912)IYYMM=IYYMM+10000
      IF(IYYMM.LT.IYMB) GO TO 100
      IF(IYYMM.GT.IYME) GO TO 100
      IYY=IYYMM/100
      IMM=IYYMM-IYY*100
      NDAYS=NDAYM(IMM)
      IF(NDAYS.GT.31 .OR. NDAYS .LE. 0) GO TO 60300
      IF(IMM.NE.2) GO TO 50
      NDAYS=29- MIN(IYY-IYY/4*4,1)
   50 CONTINUE
      K2=K1+NDAYS-1
      KB=K1
      KE=K2
! FOR START OF TABLES SET KB TO START DAY OF TABLES
      IF(IYYMM.EQ.IYMB) KB=K1+MOD(IFLUX,100)-1
! FOR END OF TABLES SET KE TO END DAY OF TABLES
      IF(IYYMM.EQ.IYME) KE= MIN(K2,K1+MOD(JFLUX,100)-1)
! IF DTM MODEL IS PICKED USE DAILY VALUES SO FILL ARRAY WITH 8
! OF EVERY VALUE
      IF ( (IATDEN.EQ.41 .AND. IHEADR.EQ.3) .OR.                        &
     &   (IATDEN.EQ.51 .AND. IHEADR.EQ.3)   .OR.                        &
     &   (IATDEN.EQ.61 .AND. IHEADR.EQ.3) ) THEN
      DO 80 K=KB,KE
      DO 78 J1=1,8
      IND=IND+1
      FLUX(IND)=IBUF2(K)
   78 END DO
   80 END DO
      GOTO 100
      ENDIF
      DO 95 K=KB,KE
      IND=IND+1
      FLUX(IND)=IBUF2(K)
   95 END DO
  100 END DO
  200 END DO
! TEST IF NUMBER OF FLUX VALUES EXCEEDS ALLOCATED SPACE
      MXFLX=MAXFLX
      IF((IATDEN.EQ.41).AND.(IHEADR.EQ.3)) MXFLX=MAXFLX*8
      IF((IATDEN.EQ.51).AND.(IHEADR.EQ.3)) MXFLX=MAXFLX*8
      IF((IATDEN.EQ.61).AND.(IHEADR.EQ.3)) MXFLX=MAXFLX*8
      IF(IND.GT.MXFLX) GO TO 60200
      IF(IND.EQ.MXFLX) GO TO 400
! IF REQUESTED DATE EXCEEDS TABLE END DATE SET THE REST OF ARRAY
! TO THE AVERAGE FLUX VALUE FOR THE LAST MONTH IN THE TABLES
      IYY=IYYMM/100
      IMM=IYYMM-IYY*100
      NDAYS=NDAYM(IMM)
      IF(NDAYS.GT.31 .OR. NDAYS .LE. 0) GO TO 60300
      IF(IMM.NE.2) GO TO 255
      NDAYS=29- MIN(IYY-IYY/4*4,1)
  255 CONTINUE
      K2=K1+NDAYS-1
      KB=K1
      KE=K2
! IF REQUESTED DATE EXCEEDS TABLE END CALCULATE THE AVERAGE VALUE
! OF THE LAST MONTH AND SET THE REST OF FLUX TO THIS AVERAGE VALUE
      FLXSM=0.0D0
      DO 295 K=KB,KE
      FLXSM=FLXSM+IBUF2(K)
  295 END DO
      DIFF=(KE-KB)+1.0D0
      AVGFLX=FLXSM/DIFF
      IND1=IND+1
      DO 300 J=IND1,MXFLX
      FLUX(J)=AVGFLX
  300 END DO
  400 CONTINUE
      RETURN
! INCORRECT HEADER
60000 WRITE(IUNT06,80000) HEADER,HEADR(IHEADR)
      STOP 16
! END OF FILE ON UNIT 2
60100 WRITE(IUNT06,80100)IUNT02
      STOP 16
! TOO MANY FLUX VALUES
60200 WRITE(IUNT06,80200) IND,MAXFLX
      STOP 16
! YYMM AT END OF FLUX RECORD IS INCORRECT
60300 WRITE(IUNT06,80300) IYYMM,I
      STOP 16
80000 FORMAT(5X,'INCORRECT HEADER(',A8,')ENCOUNTERED IN SUBROUTINE',    &
     &   ' RDFLUX WHILE SEARCHING FOR (',A8,').  EXECUTION TERMINATING')
80100 FORMAT(5X,'UNEXPECTED END OF FILE ON UNIT',I3,                    &
     &    'EXECUTION TERMINATING')
80200 FORMAT(5X,'NUMBER OF FLUXES(',I5,') EXCEEDS ALLOCATED SPACE (',I5,&
     & ') IN RDFLUX')
80300 FORMAT(1X,'YYMM =',I5,' IS AN INVALID YEAR AND MONTH FOR FLUX ON',&
     &'RECORD',I6,' EXECUTION TERMINATING IN SUBROUTINE RDFLUX')
      END
