!$EPHMRD
      SUBROUTINE EPHMRD(AA1,BUF,NDIM,IENDP,INTRVL)
!********1*********2*********3*********4*********5*********6*********7**
! EPHMRD           00/00/00            0000.0    PGMR - BILL EDDY
!                  03/04/91                      PGMR - SBL
!                  04/06/92                      PGMR - LUCIA TSAOUSSI
!
!
! FUNCTION          READ AND SELECT EPHEMERIS DATA FOR THIS RUN.
!                   PRINT BIH AND FLUX DATA
!                   SELECT TWO RECORDS OF EPHEMERIS DATA TO BE USED
!                   FOR CALCULATIONS ON THE EPHEMERIS CORRECTION EPOCH
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA1      I         DYNAMIC ARRAY FOR REAL VARIABLES. SEE
!                      COMMON CORA FOR POINTERS TO AA1
!   BUF      I         VARIABLE DIMENSIONED ARRAY USED TO READ
!   (NDIM)             EPHEMERIS DATA
!   NDIM     I         DIMENSION OF BUF ARRAY FOR READING EPHEM
!                      DATA RECORDS
!   INTRPL   I         NUMBER OF SETS OF COEFFICIENTS PER
!   (12)               SPECIFIED INTERVAL(32 DAYS).
!   INTRPO   I         ORDER OF CHEBYCHEV INTERPOLATION FOR EACH
!   (12)               OF THE INTERPOLATED QUANTITIES
!   INTRVL   I         LENGTH OF EPHEMERIS DATA RECORDS IN DAYS
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL(L)
      SAVE
!
      CHARACTER*8 CBUF
      CHARACTER*8 HA1UTC
      CHARACTER*8 TITLE
!
      DIMENSION MJDDIN(261)
      DIMENSION XP(261),YP(261),A1(261),EP(261),EC(261)
      DIMENSION AA1(1),AFLX(5)
      DIMENSION BUF(NDIM)
      DIMENSION FLXS(36),FLXM(8,36),FLXAV(36)
      DIMENSION IDAYS(5)
      DIMENSION AMODL(4),CB(6),TB(6)
      INTEGER*4 NPHM_B32
!
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/BIHTBL/IA1UTC,JA1UTC,IPOLA1,JPOLA1,IFLUXS,JFLUXS,IFLXAP,   &
     &              JFLXAP,IFLXKP,JFLXKP,IIONO,JIONO,                   &
     &              NVR(6),NUTC  ,IBIH  ,JBIH  ,                        &
     &              IFLUX ,JFLUX ,IBHSYS,IBHDAT,IBHTIM,IFLXSF,          &
     &              IBIHTL(2),IBIHHR,JBIHHR,NXBIHT
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CEPHEP/FSCEPC(1),EPHBFC(1016),                             &
     &              FSCEPT(1),EPHBFT(1016),                             &
     &              SEPBFC(75),SEPBFT(75),XEPHEP
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY,XCONST
      COMMON/CORA  /KA1UTC,KA1UT1,KXP   ,KYP   ,KEOPDP,KEOPDS,KFLXS ,   &
     &              KFLXM ,KFLXAV,KBIN  ,KBOUT ,KOBDR ,KDAT1 ,KDAT2 ,   &
     &              KDAT3 ,KSCOB ,KB1   ,KB2   ,KB3   ,KBSIGM,KBBIAS,   &
     &              JDSCRP,JDPSR ,JPOLIN,JPUTBH,JXNMOL,JEAQFB,JEAQFE,   &
     &              JEAEFB,JEAEFE,JEAINT,JEASTP,JEAVER,JATPER,JTACCL,   &
     &              JTIMES,JTDYNS,JTIMED,JEXACT,JXACIN,JCTBTI,JCTBWE,   &
     &              JCTCTM,JRTMTB,JVLOPT,JSIGSP,JSSDST,JSSDSR,JSSDDG,   &
     &              JXCGST,JXCGDT,JTACFB,JTACFE,JTAVER,JTAEFB,JTAEFE,   &
     &              JTAINT,JTASTP,JNUTIN,JNUTMD,JDWNWT,NXCORA
      COMMON/COREPH/EMJDS0(2),EFSEC0(2),EMODE(2),ECORR(2),              &
     &              PSTAE0(12),DEBC(12),SGMEBC(12),BODYID(2),XCOEPH
      COMMON/COREQ /NCHRLY,MAXUTC,MAXUT1,MAXFLX,MAXDSC,KORSUM(3),       &
     &              KORSM2(3),NXCORQ
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &              FSDINP(4),XEPHST
      COMMON/EPOCTM/IEPSTP,NXEPOC
      COMMON/GLBPAR/NARCS,NDPOLE,NDCSA,MXDEGG,MXORDG,NSRA,              &
     &              NDUMMY,MAXPAS,NXGLBP
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999)      ,  &
     &              IBDPF(999),ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,      &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988),  &
     &              NXEPH2
      COMMON/LSWTCH/LFLXPR,LMALL,LPGRAV,LST50,LST50I,LTERMV,LST17,      &
     &              NXLSWT
      COMMON/POLINF/NPOLE,NPOLEA,NUTA,MXUTC,NMODEL,NXPOLI
      COMMON/POLRAT/XPD(15000),YPD(15000),A1D(15000),TIMEPR(15000),XPOLR
      COMMON/TIMDAT/KYMD,KHMS,ICPU,IO,IRUNB,IRUNE,ITBLB,ITBLE,IARCT1,   &
     &              IARCT2,IDATAB,IDATAE,NXTIME
      COMMON/UNITS /IUNT01,IUNT02,IUNT03,IUNT05,IUNT06,IUNT07,IUNT11,   &
     &              IUNT12,IUNT15,IUNT16,                               &
     &              IUNT30,IUNT31,IUNT39,IUNT40,IUNT41,IUNT42,IUNT43,   &
     &              IUNT50,IUNT52,IUNT53,IUNT60,IUNT90,IUNT91,IUNT99,   &
     &              ILINE(2),IPAGE(2),MLINEP(2),MAXCOL(2),IUNT17,       &
     &              IUNT70,IUNT71,                                      &
     &              IUNT88,NXUNIT
!
      CHARACTER*8      AFLX
      DATA AFLX/'  AP  ','  KP  ','  KP  ','KP 3HR','KP 3HR'/
      DATA C1000/1000.0D0/,C0/0.0D0/
      DATA C1D6/1.0D6/,C1D10/1.0D10/
      DATA CMJD/2400000.0D0/,CMILLI/1.0D-3/
      DATA CMJD2/2400000.5D0/
      DATA CJPL/2.99792458D8/
      DATA TITLE/'GDYNTBLE'/
      CHARACTER*8      EPHEM
      DATA EPHEM/'EPHEM  '/
      DATA IDAYS/55,161,161,81,81/
      CHARACTER*8      AMODL
      DATA AMODL/'J65','J71','J77','DTM'/
      DATA LFIRST/.TRUE./,LONECB,LONETB/.FALSE.,.FALSE./
      DATA HA1UTC/' a1-utc '/
!
      EQUIVALENCE(CBUF,IBIHTL(1))
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!     IF(.NOT.LPEPHM) GO TO 700
!     CALL PEPWRT(IBLK,A1UT1,FLXPRN)
!     GO TO 500
!700  CONTINUE
!
!   **** INITIALIZE XPD YPD A1D MJDD

      DO I=1,5000
      TIMEPR(I)=0
      XPD(I)=0.D0
      YPD(I)=0.D0
      A1D(I)=0.D0
      ENDDO
      DO I=1,261
      MJDDIN(I)=0
      ENDDO
!
!   ****  HANDLE THE GEODYN INTERNAL REFERENCE TIME
!
      ITMGN2=INT(TMGDN2+0.1)
!
!   ****  HANDLE EPOCH FOR PLANETARY EPHEMERIS CORRECTION
!
      IF (ECORR(1).EQ.C0.OR.ICBDGM.GT.11) GO TO 100
      IF (EMJDS0(1).EQ.C0) THEN
      IDATCB=IRUNB
      CALL MJDYMD(MJDCB,IDATCB,IDUM,2)
      DJDCB=MJDCB+CMJD2
      EMJDS0(1)=(MJDCB-ITMGN2)*86400
      ELSE
      MODJD=EMJDS0(1)
      CALL MJDYMD(MODJD,IDATCB,IHMS,4)
      CALL MJDYMD(MJDCB,IDATCB,IDUM,2)
      DJDCB=MJDCB+CMJD2
      END IF
  100 IF (ECORR(2).EQ.C0.OR.ITBDGM.GT.11) GO TO 200
      IF (EMJDS0(2).EQ.C0) THEN
      IDATTB=IRUNB
      CALL MJDYMD(MJDTB,IDATTB,IDUM,2)
      DJDTB=MJDTB+CMJD2
      EMJDS0(2)=(MJDTB-ITMGN2)*86400
      ELSE
      MODJD=EMJDS0(2)
      CALL MJDYMD(MODJD,IDATTB,IHMS,4)
      CALL MJDYMD(MJDTB,IDATTB,IDUM,2)
      DJDTB=MJDTB+CMJD2
      END IF
!
! READ FIRST DATA RECORD ON EPHEMERIS FILE TO DETERMINE START TIME
! OF CURRENT EPHEMERIS FILE
!
! 200 READ(IUNT01,END=60000) NPHM,DJ1,DJ2,BUF
  200 READ(IUNT01,END=60000) NPHM_B32,DJ1,DJ2,BUF
      NPHM = NPHM_B32
      MJD=DJ1-CMJD
      IBASE=MJD
!
! FIND EPHEMERIS START TIME THAT PRECEDES RUN START TIME
! BY AT LEAST 2 DAYS
!
      CALL MJDYMD(MTIME,IRUNB,IDUM,2)
      MEPHMB=(MTIME-IBASE)/INTRVL*INTRVL+IBASE
      IF(MEPHMB+ 2 .GE. MTIME) MEPHMB=MEPHMB-INTRVL
      IF(MEPHMB.LT.MJD) GO TO 60500
! CALCULATE EPHEMERIS START TIME IN MJD SECONDS FOR IIE
      FSC1EN=(MEPHMB-ITMGN2)*86400
!
! FIND EPHEMERIS STOP TIME THAT IS BEYOND END OF RUN
!
      IF(MREFSY.EQ.1)THEN
         CALL MJDYMD(MTIME,IEPSTP,IDUM,2)
         MEPHME=((MTIME-IBASE)/INTRVL+1)*INTRVL+IBASE
      ELSE
         CALL MJDYMD(MTIME,IRUNE,IDUM,2)
         MEPHME=((MTIME-IBASE)/INTRVL+1)*INTRVL+IBASE
      ENDIF
! PRINT OUT PLANETARY EPHEMRIS INFORMATION IN THE FORM OF YYMMDD,HHMMSS
      CALL MJDYMD(MJD,IYMDEM,IHMSEM,1)
      WRITE(IUNT06,80050) IYMDEM
      CALL MJDYMD(MEPHMB,IYMDBG,IHMSBG,1)
      WRITE(IUNT06,80060) IYMDBG
      CALL MJDYMD(MEPHME,IYMDED,IHMSED,1)
      WRITE(IUNT06,80070) IYMDED
!
! SET LOGICAL FLAGS FOR POSITIONING THE EPOCH FOR THE EPHEMERIS CORR.
! PROPERLY WITHIN THE TIME SPAN OF THE SELECTED RUN TIME
! PLUS,
! CHECK WHETHER THE EPOCH FOR REQUESTED PLANETARY EPHEM. CORRECTION
! IS EARLIER THAN THE BEGINNING OF THE CURRENT EPHEMERIS FILE
!
      IF (ECORR(1).EQ.C0.OR.ICBDGM.GT.11) GO TO 250
      IF (DJDCB.LT.DJ1) GO TO 60600
      LSKCB=MJDCB.LT.MEPHMB
      LSELCB=MJDCB.GE.MEPHMB.AND.MJDCB.LE.MEPHME
      LASTCB=MJDCB.GT.MEPHME
  250 IF (ECORR(2).EQ.C0.OR.ITBDGM.GT.11) GO TO 300
      IF (DJDTB.LT.DJ1) GO TO 60700
      LSKTB=MJDTB.LT.MEPHMB
      LSELTB=MJDTB.GE.MEPHMB.AND.MJDTB.LE.MEPHME
      LASTTB=MJDTB.GT.MEPHME
  300 CONTINUE
!
! SKIP EPHEMERIS RECORDS FOR TIMES PRIOR TO START OF RUN
!
      NOSKIP=(MEPHMB-IBASE)/INTRVL-1
      IF(NOSKIP .LT. 1) GO TO 500
      DO 440 I=1,NOSKIP
!     READ(IUNT01,END=60000) NPHM,DDJ1,DDJ2,BUF
      READ(IUNT01,END=60000) NPHM_B32,DDJ1,DDJ2,BUF
      NPHM = NPHM_B32
!  GET EPOCH AND BUFFER FOR CENTRAL BODY
      IF (LSKCB.AND.ICBDGM.LT.12) THEN
         IF (DJDCB.GE.DDJ1.AND.DJDCB.LE.DDJ2) THEN
         DJEPC=DDJ1
         DO 441 IC=1,NDIM
         EPHBFC(IC)=BUF(IC)
  441    CONTINUE
         LONECB=.TRUE.
         ELSE
           IF (LONECB) THEN
           DJEPC2=DDJ1
           DO 442 IC=1,NDIM
!          BUF2TC(IC+1)=BUF(IC)
  442      CONTINUE
           LONECB=.FALSE.
           END IF
         END IF
      END IF
!  GET EPOCH AND BUFFER FOR TRACKING BODY
      IF (LSKTB.AND.ITBDGM.LT.12) THEN
         IF (DJDTB.GE.DDJ1.AND.DJDTB.LE.DDJ2) THEN
         DJEPT=DDJ1
         DO 451 IC=1,NDIM
         EPHBFT(IC)=BUF(IC)
  451    CONTINUE
         LONETB=.TRUE.
         ELSE
           IF (LONETB) THEN
           DJEPT2=DDJ1
           DO 452 IC=1,NDIM
!          BUF2TT(IC+1)=BUF(IC)
  452      CONTINUE
           LONETB=.FALSE.
           END IF
         END IF
      END IF
  440 END DO
  500 CONTINUE
      NRECS=(MEPHME-MEPHMB)/INTRVL+1
      NEPHMR=NRECS
      MJDEXP=MEPHMB
      MAXPRN=1
      IF(LFLXPR) MAXPRN=999999
!
! COMPUTE FLUX SOLAR FLUX AVERAGE FOR ATMOSPHERIC DENSITY MODEL
!
      INDX=IATDEN/10
      INDXA=INDX
      IF(IATDEN.EQ.41) INDXA=2
      CALL FLXAVG(AA1(KFLXS),IDAYS(INDX),MAXFLX,AA1(KFLXAV))
!
! COMPUTE AND OUTPUT EPHEMERIS INTERFACE FILE HEADER INFORMATION
!
      MEPHME=MEPHMB+NRECS*INTRVL-1
! IRECL CONTAINS ROOM FOR FSECXY,XP(261),YP(261),A1(261),EP(261),
! EC(261),FSECFL,FLXS(36),FLXAV(36),FLXM(8,36),FSECEP,BUF(NDIM)
      IRECL= NDIM+1668
      ITOTSE=IRECL*NRECS
      WRITE(IUNT30) EPHEM,IRECL,NRECS,MEPHMB,MEPHME
!
! LOOP FOR EACH EPHEMERIS RECORD TO BE OUTPUT
!
      WRITE(IUNT06,82000) TITLE,IBHDAT,IBHTIM
      IBIHH=IBIH*100 + IBIHHR
      JBIHH=JBIH*100 + JBIHHR
!      write(6,*)'EPHMRD: IBIH,IBIHH,IBIHHR ',IBIH,IBIHH, IBIHHR
      JPA1UT=JA1UTC
      JPPLA1=JPOLA1
      JPFLXS=JFLUXS
      JPFXAP=JFLXAP
      JPFXKP=JFLXKP
      IPFLUX=IFLUX
      JPFLUX=JFLUX
      IPBIHH=IBIHH
      IPBIH=IBIH
      JPBIH=JBIH
      IPRUNB=IRUNB
      IPRUNE=IRUNE
      IF(JA1UTC-1000000.GT.0)JPA1UT=JA1UTC-1000000
      IF(JPOLA1-100000000.GT.0)JPPLA1=JPOLA1-100000000
      IF(JFLUXS-1000000.GT.0)JPFLXS=JFLUXS-1000000
      IF(JFLXAP-1000000.GT.0)JPFXAP=JPFXAP-1000000
      IF(JFLXKP-1000000.GT.0)JPFXKP=JFLXKP-1000000
      IF(IFLUX-1000000.GT.0)IPFLUX=IFLUX-1000000
      IF(JFLUX-1000000.GT.0)JPFLUX=JFLUX-1000000
      IF(JBIH-1000000.GT.0)JPBIH=JBIH-1000000
      IF(IBIH-1000000.GT.0)IPBIH=IBIH-1000000
      IF(IBIHH-100000000.GT.0)IPBIHH=IBIHH-100000000
      IF(IRUNB-1000000.GT.0)IPRUNB=IRUNB-1000000
      IF(IRUNE-1000000.GT.0)IPRUNE=IRUNE-1000000
      WRITE(IUNT06,82100) IA1UTC,JPA1UT,IPOLA1,JPPLA1,IFLUXS,JPFLXS,    &
     &     IFLXAP,JPFXAP,IFLXKP,JPFXKP,IPRUNB,IPRUNE,IPBIHH,JPBIH,      &
     &     IPFLUX,JPFLUX
      WRITE(IUNT06,81000)
!   ******* debug this loop further *********
      DO 2500 I=1,NRECS
!     READ(IUNT01,END=60000) NPHM,DJ1,DJ2,BUF
      READ(IUNT01,END=60000) NPHM_B32,DJ1,DJ2,BUF
      NPHM = NPHM_B32
! TEST TO SEE IF EPHEMERIS FILE IS POSITIONED PROPERLY
      MJD=DJ1-CMJD

      IF(MJD .NE. MJDEXP) GO TO 60100
!  GET EPOCH AND BUFFER FOR CENTRAL BODY
      IF (LSELCB.AND.ICBDGM.LT.12) THEN
         IF (DJDCB.GE.DJ1.AND.DJDCB.LE.DJ2) THEN
         DJEPC=DJ1
         DO 541 IC=1,NDIM
         EPHBFC(IC)=BUF(IC)
  541    CONTINUE
         LONECB=.TRUE.
         ELSE
           IF (LONECB) THEN
           DJEPC2=DJ1
           DO 542 IC=1,NDIM
!          BUF2TC(IC+1)=BUF(IC)
  542      CONTINUE
           LONECB=.FALSE.
           END IF
         END IF
      END IF
!  GET EPOCH AND BUFFER FOR TRACKING BODY
      IF (LSELTB.AND.ITBDGM.LT.12) THEN
         IF (DJDTB.GE.DJ1.AND.DJDTB.LE.DJ2) THEN
         DJEPT=DJ1
         DO 551 IC=1,NDIM
         EPHBFT(IC)=BUF(IC)
  551    CONTINUE
         LONETB=.TRUE.
         ELSE
           IF (LONETB) THEN
           DJEPT2=DJ1
           DO 552 IC=1,NDIM
!          BUF2TT(IC+1)=BUF(IC)
  552      CONTINUE
           LONETB=.FALSE.
           END IF
         END IF
      END IF
      MJDEXP=MJDEXP+INTRVL
      MJDXY=MJD
      MJDFLX=MJD
      IHOUR=0

      CALL POLDAT(MJDXY,IHOUR,AA1(KXP),AA1(KYP),AA1(KA1UT1),            &
     & AA1(KEOPDP),AA1(KEOPDS),XP,YP,A1,EP,EC)




      CALL FLXDAT(MJDFLX,AA1(KFLXS),AA1(KFLXAV),AA1(KFLXM),             &
     &            FLXS,FLXAV,FLXM)
!     IF(I .GT. MAXPRN ) GO TO 1600
! PRINT FLUX,A1-UTC VALUES
      IF(I .GT. MAXPRN ) GOTO 1200
      WRITE(IUNT06,81100) AFLX(INDXA),AFLX(INDXA),IDAYS(INDX),          &
     &                   AMODL(INDX),IDAYS(INDX),AMODL(INDX)
 1200 CONTINUE
      MJD1=MJDFLX-1
      DO 1500 IXL=1,18
      MJD1=MJD1+1
      CALL MJDYMD(MJD1,IYMD1,IDUM,1)
      MJDP18=MJD1+18
      CALL MJDYMD(MJDP18,IYMD2,IDUM,1)
      IXL1=IXL+18
      IF(IXL.GT.1) GO TO 1250
! CALCULATE A1-UTC AT START OF POLE VALUES
      IDAYHR=IHOUR/24
      MJDP1=MJDXY+IDAYHR
      IHR1=MOD(IHOUR,24)
      CALL MJDYMD(MJDP1,IYMDP,IDUM,1)
      IYMDHP=IYMDP*100 + IHR1
      IHMS=IHR1*10000
      T1=TDIF(4,3,IYMDP,IHMS,AA1(KA1UTC))
 1250 CONTINUE
      IF(I .GT. MAXPRN ) GOTO 1251
      WRITE(IUNT06,81200) IYMD1,FLXM(1,IXL),FLXS(IXL),FLXAV(IXL),       &
     & IYMD2,FLXM(1,IXL1),FLXS(IXL1),FLXAV(IXL1)
 1251 CONTINUE
      IF(IXL.GT.4) GO TO 1500
      GO TO (1350,1500,1400,1450),IXL
 1350 CONTINUE
! WRITE A1-UTC HEADER
      IF(I .GT. MAXPRN ) GOTO 1351
      WRITE(IUNT06,81300)
 1351 CONTINUE
!>>>  TOPEX POE A1-UTC FILE
      if( LFIRST ) then
        IF(I .GT. MAXPRN ) GOTO 1361
        WRITE(89 ) HA1UTC
 1361 CONTINUE
         LFIRST = .false.
      endif
      GO TO 1500
 1400 CONTINUE
! WRITE FIRST A1-UTC VALUE
      IF(I .GT. MAXPRN ) GOTO 1401
      WRITE(IUNT06,81500) IYMDHP,T1
 1401 CONTINUE
!>>>  TOPEX POE A1-UTC FILE
      HYMDHP =  IYMDHP + 0.5D0
      IF(I .GT. MAXPRN ) GOTO 1411
      WRITE(89          ) HYMDHP,T1
 1411 CONTINUE
      GO TO 1500
 1450 CONTINUE
! WRITE LAST A1-UTC VALUE
      IHRS=(NINTBH-1)*IBHINT
      IHRS=IHR1+IHRS
      IDYS=IHRS/24
      MJDP2=MJDXY+IDYS
      IHR2=MOD(IHRS,24)
      CALL MJDYMD(MJDP2,IYMDP,IDUM,1)
      IYMDHP=IYMDP*100 + IHR2
      IHMS=IHR2*10000
      T1=TDIF(4,3,IYMDP,IHMS,AA1(KA1UTC))
      IF(I .GT. MAXPRN ) GOTO 1451
      WRITE(IUNT06,81500) IYMDHP,T1
 1451 CONTINUE
!>>>  TOPEX POE A1-UTC FILE
      HYMDHP =  IYMDHP + 0.5D0
      IF(I .GT. MAXPRN ) GOTO 1461
      WRITE(89          ) HYMDHP,T1
 1461 CONTINUE
 1500 END DO
! WRITE POLAR MOTION AND OTHER EARTH ORIENTATION PARAMETERS
      IF(I .GT. MAXPRN ) GOTO 1501
      WRITE(IUNT06,81510)
      WRITE(IUNT06,81520)
 1501 CONTINUE
      NINTHF=NINTBH/2
      NINTHR=NINTHF*IBHINT
      DO 1540 INDX1=1,NINTHF
      CALL MJDYMD(MJDP1,IYMD1,IDUM,1)
      IYMDH1=IYMD1*100+IHR1
      INDX2=INDX1+NINTHF
      IHRTP2=IHR1+NINTHR
      IDHR2=IHRTP2/24
      IHR2=MOD(IHRTP2,24)
      MJDP2=MJDP1+IDHR2
      CALL MJDYMD(MJDP2,IYMD2,IDUM,1)
      IYMDH2=IYMD2*100+IHR2
      XSEC1=XP(INDX1)/(SECRAD*CMILLI)
      XSEC2=XP(INDX2)/(SECRAD*CMILLI)
      YSEC1=YP(INDX1)/(SECRAD*CMILLI)
      YSEC2=YP(INDX2)/(SECRAD*CMILLI)
      CALL YMDTIS(IYMD1,0,ISEC1)
      CALL YMDTIS(IYMD2,0,ISEC2)
      MJDDIN(INDX1)=ISEC1
      MJDDIN(INDX2)=ISEC2
      IF(I .GT. MAXPRN ) GOTO 1511
      WRITE(IUNT06,81540) IYMDH1,XSEC1,YSEC1,A1(INDX1),EP(INDX1),       &
     &EC(INDX1),IYMDH2,XSEC2,YSEC2,A1(INDX2),EP(INDX2),EC(INDX2)
 1511 CONTINUE
      IHRTP1=IHR1+IBHINT
      IDHR1=IHRTP1/24
      IHR1=MOD(IHRTP1,24)
      MJDP1=MJDP1+IDHR1
 1540 END DO
      IF(INDX2.LT.NINTBH) THEN
      IHRTP2=IHR2+IBHINT
      IDHR2=IHRTP2/24
      IHR2=MOD(IHRTP2,24)
      MJDP2=MJDP2+IDHR2
      CALL MJDYMD(MJDP2,IYMD2,IDUM,1)
      IYMDH1=IYMD2*100+IHR2
      INDX1=NINTBH
      CALL YMDTIS(IYMD2,0,ISEC2)
      MJDDIN(INDX1)=ISEC2
      XSEC1=XP(INDX1)/(SECRAD*CMILLI)
      YSEC1=YP(INDX1)/(SECRAD*CMILLI)
      IF(I .GT. MAXPRN ) GOTO 1541
      WRITE(IUNT06,81550) IYMDH1,XSEC1,YSEC1,A1(INDX1),EP(INDX1),       &
     &EC(INDX1)
 1541 CONTINUE
      ENDIF
!
! WRITE 3 HOURLY KP IF USING FRENCH DRAG MODEL OR MSIS MODEL
      IF((IATDEN.EQ.41).OR.(IATDEN.EQ.42).OR.(IATDEN.EQ.43).OR.         &
     &    (IATDEN.EQ.51).OR.(IATDEN.EQ.52).OR.(IATDEN.EQ.53).OR.        &
     &    (IATDEN.EQ.61).OR.(IATDEN.EQ.62).OR.(IATDEN.EQ.63)) THEN
      IF(I .GT. MAXPRN ) GOTO 1546
         WRITE(IUNT06,83500)
 1546 CONTINUE
         MJD2=MJDFLX-1
         DO 1550 JXL=1,18
            MJD2=MJD2+1
            CALL MJDYMD(MJD2,JYMD1,IDUM,1)
            MJD18=MJD2+18
            CALL MJDYMD(MJD18,JYMD2,IDUM,1)
            JXL1=JXL+18
      IF(I .GT. MAXPRN ) GOTO 1550
            WRITE(IUNT06,84000) JYMD1,(FLXM(II,JXL),II=1,8),JYMD2,      &
     &                                (FLXM(II,JXL1),II=1,8)
 1550    CONTINUE
      ENDIF
 1600 CONTINUE
      SCALE=VLIGHT/CJPL
      KM1=1
      KM2=IENDP
      DO 1800 KM=KM1,KM2
 1800 BUF(KM)=C1000*SCALE*BUF(KM)
! CONVERT DATES TO SECONDS FROM GEODYN REFERENCE TIME
      FSECXY=((MJDXY -ITMGN2)*86400) + (IHOUR*3600)
      FSECFL=(MJDFLX-ITMGN2)*86400
      FSECEP=(MJD   -ITMGN2)*86400
! OUTPUT EPHEMERIS DATA RECORDS TO SCRATCH FILE
!     write(6,*)XP
!     write(6,*)YP
!     write(6,*)A1
      WRITE(IUNT30) FSECXY,XP,YP,A1,EP,EC,FSECFL,FLXS,FLXAV,FLXM,FSECEP,&
     &BUF
! CALL POLDOT TO COMPUTE RATES
      IF(NMODEL.EQ.1) THEN
      IPT=1+(I-1)*NINTBH
      CALL POLDOT(MJDDIN,TIMEPR(IPT),XP,YP,A1,XPD(IPT),YPD(IPT),        &
     &A1D(IPT),NINTBH)
      IF(IPT.GT.1) THEN
      DO N=1,NINTBH-3
      XPD(IPT-3+N)=XPD(IPT+2+N)
      YPD(IPT-3+N)=YPD(IPT+2+N)
      A1D(IPT-3+N)=A1D(IPT+2+N)
      TIMEPR(IPT-3+N)=TIMEPR(IPT+2+N)
      ENDDO
      ENDIF
      ENDIF
 2500 END DO
      IF(NMODEL.EQ.1) THEN
      NREM=NRECS*NINTBH-4
      DO N=NREM,NREM+5
      XPD(N)=0.D0
      YPD(N)=0.D0
      A1D(N)=0.D0
      TIMEPR(N)=0
      ENDDO
      ENDIF
!     write(6,*)'DBG EPHEM DOTS '
!     do n=1,1000
!     write(6,*)XPD(N),YPD(N),A1D(N),TIMEPR(N),n
!     enddo
!
      LDONCB=.NOT.LASTCB
      LDONTB=.NOT.LASTTB
!2510 READ(IUNT01,END=60000) NPHM,DDJ1,DDJ2,BUF
 2510 READ(IUNT01,END=60000) NPHM_B32,DDJ1,DDJ2,BUF
      NPHM = NPHM_B32
!  GET EPOCH AND BUFFER FOR CENTRAL BODY
      IF (LASTCB.AND.ICBDGM.LT.12) THEN
         IF (DJDCB.GE.DDJ1.AND.DJDCB.LE.DDJ2) THEN
         DJEPC=DDJ1
         DO 2541 IC=1,NDIM
         EPHBFC(IC)=BUF(IC)
 2541    CONTINUE
         LONECB=.TRUE.
         ELSE
           IF (LONECB) THEN
           DJEPC2=DDJ1
           DO 2542 IC=1,NDIM
!          BUF2TC(IC+1)=BUF(IC)
 2542      CONTINUE
           LONECB=.FALSE.
           LDONCB=.TRUE.
           END IF
         END IF
      END IF
!  GET EPOCH AND BUFFER FOR TRACKING BODY
      IF (LASTTB.AND.ITBDGM.LT.12) THEN
         IF (DJDTB.GE.DDJ1.AND.DJDTB.LE.DDJ2) THEN
         DJEPT=DDJ1
         DO 2551 IC=1,NDIM
         EPHBFT(IC)=BUF(IC)
 2551    CONTINUE
         LONETB=.TRUE.
         ELSE
           IF (LONETB) THEN
           DJEPT2=DDJ1
           DO 2552 IC=1,NDIM
!          BUF2TT(IC+1)=BUF(IC)
 2552      CONTINUE
           LONETB=.FALSE.
           LDONTB=.TRUE.
           END IF
         END IF
      END IF
      IF (.NOT.LDONCB.OR..NOT.LDONTB) GO TO 2510
!
!   FILL EPHEM. START TIMES IN COMMON /CEPHEP/
!
      IF (ECORR(1).EQ.C0.OR.ICBDGM.GT.11)  GO TO 2560
      FSCEPC(1)=(DJEPC-CMJD2-3.0D4)*864.0D2
!     BUF2TC(1)=(DJEPC2-CMJD2-3.0D4)*864.0D2
 2560 IF (ECORR(2).EQ.C0.OR.ITBDGM.GT.11)  GO TO 2600
      FSCEPT(1)=(DJEPT-CMJD2-3.0D4)*864.0D2
!     BUF2TT(1)=(DJEPT2-CMJD2-3.0D4)*864.0D2
 2600 CONTINUE
! OUTPUT INFORMATION ABOUT SOURCE OF TABLES DATA
      WRITE(IUNT06,83000)
      REWIND IUNT01
      REWIND IUNT30
      ENDFILE 89
      RETURN
!
! ERROR MESSAGES
!
! UNEXPECTED END OF FILE ON EPHEMERIS UNIT
60000 WRITE(IUNT06,80000) MJD
      STOP 16
! EPHEMERIS POSITIONING PROBLEM
60100 WRITE(IUNT06,80100) MJD,MJDEXP
      STOP 16
! REQUESTED DATE PRECEDES START OF EPHEMERIS FILE
60500 WRITE(IUNT06,80500) MEPHMB,MJD
      STOP 16
! REQUESTED DATE ON CARD PLNEPH PRECEDES START OF EPHEMERIS FILE
60600 WRITE(IUNT06,80600) IDATCB,IYMDEM
      STOP 16
60700 WRITE(IUNT06,80700) IDATTB,IYMDEM
      STOP 16
80000 FORMAT(1X,'UNEXPECTED END OF FILE ENCOUNTERED WHILE READING',     &
     & ' EPHEMERIS FILE IN EPHMRD. MJD =',I10/                          &
     & 1X, 'EXECUTION TERMINATING')
80050 FORMAT(1X,'START TIME OF THE FIRST 32 DAY EPHEMERIS RECORD ',     &
     &       ' ON UNIT 1:             ',I6)
80060 FORMAT(1X,'START TIME OF THE FIRST 32 DAY EPHEMERIS RECORD ',     &
     &       'SELECTED FOR THIS RUN:  ',I6)
80070 FORMAT(1X,'START TIME OF THE LAST  32 DAY EPHEMERIS RECORD ',     &
     &       'SELECTED FOR THIS RUN:  ',I6)
80100 FORMAT(1X,'EPHEMERIS POSITIONING PROBLEM. MJD OF LAST RECORD',    &
     & 'READ WAS',I7,' MJD OF NEXT RECORD IS',I10,'EXECUTION',          &
     & 'TERMINATING')
80300 FORMAT(5X,'NEPHEM EQUALS ONE')
80500 FORMAT(1X,'REQUESTED DATE (',I6,                                  &
     &  ') PRECEDES START OF EPHEMERIS FILE (',I6,')' )
80600 FORMAT(1X,'REQUESTED DATE FOR CENTRAL BODY EPHEM CORR',I6,        &
     & 'PRECEDES START OF EPHEMERIS FILE',I6 )
80700 FORMAT(1X,'REQUESTED DATE FOR TRACKING BODY EPHEM CORR',I6,       &
     & 'PRECEDES START OF EPHEMERIS FILE' ,I6 )
81000 FORMAT(/                                                          &
     &  27X,'TABLE VALUES FOR MAGNETIC FLUX,SOLAR FLUX,POLAR MOTION,',  &
     &  'A1-UT1 AND A1-UTC DATA')
81100 FORMAT(/2( 9X,'MAGNETIC FLUX',5X,'SOLAR FLUX',10X)/               &
     & 2( 1X,'YYMMDD',5X,A6,8X,'S',5X,'AVERAGE', 8X)/                   &
     &  28X,'(',I3,' DAYS(',A3,'))',32X,'(',I3,' DAYS(',A3,'))',/)
81200 FORMAT(  1X,I6,3X,F8.4,6X,F5.1,3X,F7.2, 8X ,                      &
     &         1X,I6,3X,F8.4,6X,F5.1,3X,F7.2, 8X ,                      &
     &         I6,2F7.0,2X,F8.4)
81300 FORMAT('+',111X,'A1-UTC')
81500 FORMAT('+', 99X,I8,1X,F11.7)
81510 FORMAT(/2(11X,'POLAR MOTION',4X,'EARTH ORIENTATION PARAMETERS',   &
     &21X))
81520 FORMAT(2(1X,'YYMMDDHH',4X,'X',6X,'Y',7X,'A1-UT1',4X,'DEPSI ',     &
     &5X,'DPSI',23X))
81540 FORMAT(2(1X,I8,2F7.0,4X,3(F8.4,2X),19X))
81550 FORMAT(77X,I8,2F7.0,4X,3(F8.4,2X),19X)
82000 FORMAT(/ 10X,'BIH TABLES FILE *** ',A8,' *** CREATED ',I6,' AT ', &
     &       I6)
82100 FORMAT(/ 4X,4X,'A1-UTC',6X,'POLE/A1-UT1/EOP',7X,'FLUXS',9X,       &
     &  'FLUXAP',9X,'FLUXKP',11X,'RUN',14X,'BIH',13X,'FLUX'/            &
     &  4X, 2(' START  END      '),4(' START  END    '),                &
     &  2X,1(' START  END    '),2X,1(' START  END'),                    &
     &  /4X,1(I6,1X,I6,1X),1(I8,1X,I8,1X),                              &
     &  4(I6,1X,I6,1X),2(I8,1X,I8,1X),// )
                                                              !125
                                                      ! 130
                                            ! 128
!     &  /4X,1(I6,1X,I6,1X),1(I8,1X,I8,1X),
!     &  4(I6,1X,I6,1X),2(I8,1X,I8,1X)//)

83000 FORMAT(1X/5X,'TABLE VALUES ARE FROM THE FOLLOWING SOURCES',       &
     &      ' UNLESS OVERRIDDEN BY INPUT FROM THE USER.'/1X,            &
     & 'A1-UTC        -',1X,                                            &
     & 'VALUES PUBLISHED BY THE U. S. NAVAL OBSERVATORY.'/1X,           &
     & 'A1-UT1        -',1X,                                            &
     & 'DIFFERENCES BETWEEN A1-UTC AND UT1-UTC WHERE UT1-UTC ARE THE',  &
     &  1X,'SMOOTHED 5 DAY VALUES FROM THE BIH CIRCULAR D.'/1X,         &
     & 'POLAR MOTION  -',1X,                                            &
     & 'SMOOTHED 5 DAY VALUES FROM THE BIH CIRCULAR D BULLETINS.'/1X,   &
     & 'SOLAR FLUX    -',1X,                                            &
     & 'THE OTTAWA 2800MHZ VALUES ADJUSTED TO 1 AU FOUND IN THE TABLES',&
     &  1X,'OF DAILY SOLAR INDICES IN THE SOLAR-GEOPHYSICAL DATA'/      &
     &  18X,'PROMPT REPORTS ISSUED BY NOAA. THE VALUES PRINTED ARE',1X, &
     &  'SCALED BY GEODYN TO THE EARTHS ACTUAL DISTANCE FROM THE SUN.'/ &
     &  1X,'MAGNETIC FLUX -',1X,                                        &
     &  'AP VALUES ARE FROM THE TABLE OF GEOMAGNETIC ACTIVITY INDICES', &
     &  1X,'IN THE NOAA SOLAR-GEOPHYSICAL DATA PROMPT REPORTS'/         &
     &  18X,'KP VALUES ARE OBTAINED BY CUBIC INTERPOLATION OF THE AP',  &
     &  1X,'TO KP TABLES.'/)
83500 FORMAT(1X,' YYMMDD  KP-0   KP-3   KP-6   KP-9   KP-12  KP-15 ',   &
     &       ' KP-18  KP-21  YYMMDD  KP-0   KP-3   KP-6   KP-9  ',      &
     &       ' KP-12  KP-15  KP-18  KP-21 '/)
84000 FORMAT(1X,I7,8F7.3,1X,I7,8F7.3)
      END
