!$ACCSEL
      SUBROUTINE ACCSEL(AA,II,LL,FSEC,INDSAT,INDSET,INPSAT,LELEVS,      &
     &                  LHRFON,IXDDNC,IORDER,IORDRV,NH,NSTEPS,N3,       &
     &                  IDXDDN,IPXDDA,H,ISATID)
!********1*********2*********3*********4*********5*********6*********7**
! ACCSEL           00/00/00            0000.0    PGMR - D. E. Pavlis
!
! FUNCTION:  ACCELEROMETER DATA SELECTION AND MODELING INTERFACE
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL VARIABLES.
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER VARIABLES
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL VARIABLES
!   INDSAT   I    A    FOR A GIVEN INTERNAL SAT NO (1,2,3) INDSAT
!                      GIVES THE ACTUAL LOCATION IN THE SATELLITE
!                      RELATED ARRAYS FOR THIS SATELLITE.
!                      (EG.   SAT ID=ISATNO(INDSAT(1,2,OR 3))
!   INDSET   I    A    FOR A GIVEN INTERNAL SATELLITE NUMBER INDSET TELL
!                      WHICH SAT SET THAT THE GIVEN SAT BELONGS TO.
!   INPSAT   I    A    POINTER ARRAY THAT RELATES THE INTERNAL SATELLITE
!                      NUMBER (1,2,3) TO THE SATELLITES DEFINED IN THE
!                      DATA HEADER RECORDS (N=1,2,3). (EG.
!                      ISATP=INPSAT(1) WOULD TELL WHICH OF THE THREE
!                      POSSIBLE SATELLITES DEFINED IN THE DATA HEADER
!                      RECORDS PERTAINED TO INTERNAL SATELLITE NO. 1)
!   LHRFON  I     A    FLAGS FOR HIGH RATE INTEGRATION FORCES
!   IXDDNC  O     A    POINTERS TO THE ARRAY OF THE COWELL ACCELERATIONS
!                      FOR SEPARATELY INTEGRATED FORCES OR ACCELEROMTER
!                      FORCES
!   IORDER   I    A    ORDER OF COWELL INTEGRATION FOR ORBIT
!   IORDRV   I    A    ORDER OF COWELL INTEGRATION FOR VAR. EQ.
!   NH       I    A    MAXIMUM NUMBER OF ORBIT BACK VALUES PLUS ONE
!   NSTEPS   I    A    NH+IORDER-2
!   N3       O    A    NSAT*3
!   IDXDDN   O    A    NUMBER OF STEPS COVERED BY XDDTNC ARRAY (ARRAY OF
!                      SEPARATELY INTEGRATED ACCELS)
!   H        I    A    INTEGRATION STEP SIZE IN SECONDS FOR ORBIT
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/ACCLRM/MDYNPD,MBAPPD,MACOBS,IDYNSC(200),MDYNST,IACCSC(200),&
     &              MACCSC,NACPRM(200),NATPRM(200),NXCLRM
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/NHINPT/NH1VOC,NXNHIN
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)

      DIMENSION AA(1),II(1),LL(1),INDSAT(3),INDSET(3),INDSTA(3),        &
     &   INPSAT(3),FSEC(1)
      DIMENSION LELEVS(3,4)
! BELOW MAKE NM (MINTIM)
      DIMENSION NSELCT(500)
      DIMENSION LHRFON(MSETA,MXFMG)
      DIMENSION IXDDNC(NSETA), IORDER(NSETA), IORDRV(NSETA), NH(NSETA)
      DIMENSION NSTEPS(NSETA), N3(NSETA), IDXDDN(NSETA), IPXDDA(NSETA)
      DIMENSION H(NSETA),DUM(3),DUMAR(3,3)
      DIMENSION FSECIN(1),FSECOT(1)
      DIMENSION IYMD(1),IHM(1),SEC(1)

!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
      IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
      ENDIF

!     write(6,*)' dbg calling ORBSET from ACCSEL '
! OBTAIN SATELLITE POSITIONS AT CORRECT SATELLITE TIMES
      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),INDSAT(1),            &
     &   NEQNI,II(KSGMNT-1+IRET),                                       &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),IRET,MJDSBL,FSEC(1),       &
     &   FSEC(NM),NM,AA,II)
!     write(6,*)' dbg calling ORBIT fr ACCSEL '

      IF(NINTOT.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      ENDIF

      CALL ORBIT(MJDSBL,FSEC,AA(KS),NM,II(KINDH),II(KNMH),II(KMJDSC),   &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM,AA(KPXPFM),              &
     &   LNADJ,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),                &
     &   AA(KTPMES+2*MINTIM),LL(KLTPMS+3*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)
! GET THE SATELLITE ID
! THE ARRAY LL(KLSETS) WILL HAVE ONE TRUE FLAG FOR ONE SATELLITE IN THE
! II(KMJDSC) and AA(KFSEC) IS THE TIME OF THE LAST VALUE IN PXHDDT OR AN
! SMALL STEPSIZE ARRAY
! NOW THE ARRAY AA(KPXHDT) HAS BEEN FILLED UP FOR THIS BLOCK.
! GET THE INFORMATION FOR PMPA

! GET THE SET
      JXDDNC=KXDDNC
      JPXDDA=KPXHDT
      K=1
      DO ISET=1,NSETA
      IF( LL(KLSETS+ISET-1) ) K=ISET
      ENDDO
!
! FOR EACH SET, THE XDDAO ARRAY IS DIMENSIONED (3,NFSCAC,NSAT,NSTEP)
! WHERE NSAT IS THE NUMBER OF SATELLITES IN THE SET OF INTEREST.
! IF THERE IS MORE THAN ONE SATELLITE IN A SET THAT HAS ACCELEROMETRY,
! THEN SUBROUTINE GETFRC WILL NEED TO BE PASSED MORE INFORMATION (LIKE
! THE SAT # WITHIN THE SET AND THE NUMBER OF SATELLITES IN THE SET).
! FOR NOW TERMINATE IF THE NUMBER OF SATELLITES IN A SET WITH
! ACCELEROMETRY IS GREATER THAN 1
!
      IF(N3(K).GT.3) THEN
        NSATPR=N3(K)/3
        WRITE(6,60000)
        WRITE(6,60001)
        WRITE(6,60002)
        WRITE(6,60003) K,NSATPR
        WRITE(6,60004)
        WRITE(6,60005)
        STOP
      ENDIF
!
!
! RATIO FOR THIS SET
      NRAT=II(KNRAT-1+K)
! NUMBER OF EQUATIONS FOR HIGH RATE FORCES
      NEQNH=II(KNEQNH-1+K)
      NEQN=II(KNEQN-1+K)
      HS=H(K)/NRAT
!
! POINTER TO AA(KXDDAO) IXDDAC (ARRAY AA(KXDDAO) IS XDDTAC(N3,IDXDDN(K))
!       IF(K.GT.1) THEN
!      DO J=1,K-1
!      NSTEPS(J)=(MAX0(IORDER(J),IORDRV(J))-1)*2
!      NH(J)=NSTEPS(J)-(IORDER(J)-1)+1
!      NHD=(NH1VOC+1)-NH(J)
!      NHD=MAX0(NHD,0)
!      NHD0=NHD
!      JXDDNC=JXDDNC+N3(J)*(1+II(KNRAT-1+J)*((2*IORDER(J)-3)+NHDO))
!      IDXDDN(J)=(1+II(KNRAT-1+J)*((2*IORDER(J)-3)+NHDO))
!      JPXDDA=JPXDDA+IDXDDN(J)*II(KNEQNH-1+J)*N3(J)
!      ENDDO
!       ENDIF
!      IXDDNC(K)=JXDDNC
      IXDDAC=(IXDDNC(K)-KXDDNC)*NFSCAC + KXDDAO
! AND LAST DIMENSION OF AA(KXDDAO)
!      IDXDDN(K)=(1+NRAT*((2*IORDER(K)-3)+NHDO))
!
! POINTER TO AA(KPXHDT) IPXDDA (ARRAY AA(KPXHDT) IS PXDDAC(NEQNH,N3,IDXD
!      IPXDDA(K)=JPXDDA


!  LAST NSTEPB INTEGRATION STEP VALUES. PXHDDT( , ,ILAST), TIME OF LAST
!  STEP MJDLST,FLAST
! This ILAST below might not be correct maybe we need to work with the f
! for NSTEPB above.
      IOL1=IORDER(K)-1
!     write(6,*)' dbg ii(kibckn) ',ii(kibckn),iol1
      ILAST=II(KIBCKN-1+K)+IOL1
      MJDLST=II(KMJDSC-1+K)
      FLAST =AA(KFSEC-1+K)
!     write(6,*)'               '
!     write(6,*)' dbg time of last integration ',ILAST,MJDLST,FLAST
!     write(6,*)'               '


! EVALUATE THE LOCATION FOR THE FIRST OBSERVATION (FOR THE 3rd DIMENSION
! OF THE PARTIALS ARRAY
! TLAST THE LAST TIME OF INTEGRATION
      TLAST=DBLE(MJDLST)+FLAST
! TFIRST THE TIME OF THE FIRST OBSERVATION IN THE BLOCK
      TFIRST=DBLE(MJDSBL)+FSEC(1)
      TL=DBLE(MJDSBL)+FSEC(NM)
!     write(6,*)'               '
!     write(6,*)' last integration: ',TLAST
!     write(6,*)' first observation: ',TFIRST,TL
!     write(6,*)'               '
! HOW MANY STEPS WE GO BACK FOR THE FIRST OBSERVATION
      IBACK=(TLAST-TFIRST)/HS
!     write(6,*)' dbg need to go back steps: ',IBACK
! ADDRESS OF THE FIRST OBSERVATION
      IADDR=ILAST-IBACK
      TINT=TLAST-HS*IBACK
!     write(6,*)' dbg TINT ',TINT
!     write(6,*)' dbg IADDR ',IADDR

      CALL GETNM(NM,LL(KLEDIT),NSELCT,MJDSBL,FSEC,HS,TINT)
!
      DO IQP=1,NM
         ITEST=IADDR-1+NSELCT(IQP)
         IF(ITEST.LT.1) THEN
            FSECIN(1)=FSEC(IQP)
            CALL UTCET(.FALSE.,1,MJDSBL,FSECIN,FSECOT,AA(KA1UT))
            CALL YMDHMS(MJDSBL,FSECOT,IYMD,IHM,SEC,1)
            IF(IYMD(1).GT.1000000)IYMD(1)=IYMD(1)-1000000
            WRITE(6,60010)
            WRITE(6,60011)
            WRITE(6,60012)
            WRITE(6,60013) MTYPE
            WRITE(6,60014) IYMD(1),IHM(1),SEC(1)
            STOP
         ENDIF
      ENDDO
!
!
      IF(LSTINR) THEN
         TP1=DBLE(MJDSBL)+FSEC(1)
         WRITE(91) MTYPE,NM,TP1
         DO IQP=1,NM
           TP1=DBLE(MJDSBL)+FSEC(IQP)
           WRITE(91) TP1
         ENDDO
      ENDIF
!
      CALL GETFRC(AA(KPMPA),AA(IXDDAC),AA(IPXDDA(K)),AA(KOBSC),         &
     &            LL(KLAVOI),LNPNM,HS,NEQNH,N3(K),IDXDDN(K),            &
     &            II(KHRFRC+MXHRG*(K-1)),II(KPTFBS+(K-1)*MXFMG),        &
     &            IADDR,LL(KLEDIT),NSELCT,LHRFON(K,1),                  &
     &            II(KPTFSB+(K-1)*MXHRG),AA(KACCDT),INDSAT(1),          &
     &            II(KIPTFM),II(KILNFM),II(KNFMG))
!     write(6,*)' dbg calling ACCELR from ACCSEL '


! Out of GETFRC the PMPA array will be filled with partials for all the
! force morel partials that apply. Now in ACCELR we will add the partial
! the accelerometer biases.

      JACCBT=KACCBT+(K-1)*MBAPPD*2
      JACPER=KACPER+(K-1)*MBAPPD
      JACCPE=KACCPE+(K-1)
      CALL ACCELR(AA,II,LL,MJDSBL,FSEC,INDSAT(1),INDSET(1),INPSAT(1),   &
     &             INDSTA(1),LELEVS,AA(JACCBT),AA(JACPER),II(JACCPE),   &
     &             AA(KPRMVC),AA(KPRSG0),AA(KPMPA),LNPNM,LL(KLAVOI),    &
     &             AA(KOBSC),AA(KOBS),AA(KACCDT),MTYPE,NM,.FALSE.,NDIM1,&
     &             NDIM2,DUM,0,DUM,DUM,DUMAR,II(KISATN),ISATID)

      RETURN
60000 FORMAT(' EXECUTION TERMINATING IN SUBROUTINE ACCSEL')
60001 FORMAT(' ATTEMPT TO USE ACCELEROMETRY WITH MORE THAN')
60002 FORMAT(' ONE SATELLITE IN A SET.')
60003 FORMAT(' SET # ',I3,' HAS ',I3,' SATELLITES.')
60004 FORMAT(' SUBROUTINES ACCSEL AND GETFRC NEED UPGRADES')
60005 FORMAT(' BEFORE THIS CAN WORK.')
60010 FORMAT(' EXECUTION TERMINATING IN ACCSEL')
60011 FORMAT(' NEGATIVE INDEX TO ACCELERATION ARRAYS')
60012 FORMAT(' PROBABLY CAUSED BY OBSERVATIONS BEFORE STARTING EPOCH')
60013 FORMAT(' OFFENDING OBSERVATION IS MTYPE ',I4)
60014 FORMAT(' AT TIME ',I8,2X,I4,2X,F10.3)
      END
