!$ADJFIT
       SUBROUTINE ADJFIT(IBETA,X,ADJUST)
!*******************************************************************
!  ROUTINE NAME:   ADJFIT   DATE: 01/24/97      PGMR: A. MARSHALL
!
!   FUNCTION -  Apply the fits to the GFO yaw angle error curves
!               generated by Doug Wiemer of Ball Aerospace.
!               SEPARATE CURVE FITS APPLY FOR 80-92 deg
!               and 92-104 deg.
!
!              MODIFIED CODE ORIGINALLY WRITTEN FOR GIPSY BY
!              YOAZ BAR-SEVER (JPL:  yeb@cobra.jpl.nasa.gov)
!
!  I/O PARAMETERS:
!
!   NAME    A/S    I/O   DESCRIPTION OF I/O PARAMETERS IN ARGUMENT LIST
!   -----  ------ -----  -----------------------------------------------
!   IBETA    S      I    BETA' Angle
!   X        S      I    Orbit Angle
!   ADJUST   S      O    Yaw Angle
!*******************************************************************
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
!
!********1*********2*********3*********4*********5*********6*********7**
! START OF EXECUTABLE CODE
!********1*********2*********3*********4*********5*********6*********7**
!
!
!
       goto(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15) ibeta
    1  continue
    2  continue
    4  continue
    5  continue
    7  continue
    8  continue
    9  continue
   11  continue
   12  continue
   13  continue
   14  continue
       write(6,*) ' '
       write(6,*) 'Error is subroutine adjust_fit!'
       write(6,*) 'Beta angle is',ibeta
       write(6,*) 'It must be either 3, 6, 10 or 15 degrees.'
       write(6,*) 'Program stopped.'
       stop
!
!** the adjustments
    3  if(x .lt. 92) then
         adjust=1.0609136389D7 -6.2464144351D5*x + 1.4701423038D4*x**2  &
     &         - 1.7288822997D2*x**3 + 1.0158684593D0*x**4              &
     &         - 2.3859026165D-3*x**5
       else
         adjust=-3.2217447904D6 + 1.5766298541D5*x - 3.0808687109D3*x**2&
     &         + 3.0051295924D1*x**3 - 1.4632779249D-1*x**4             &
     &         + 2.8456199053D-4*x**5
       endif
       return
!
    6  if(x .lt. 92) then
         adjust=5.6391133622D5 -3.4213592002D4*x + 8.2957483078D2*x**2  &
     &         - 1.0047564151D1*x**3 + 6.0782291639D-2*x**4             &
     &         - 1.4690906456D-4*x**5
       else
         adjust=3.3701795866D4 - 3.9785733597D3*x + 1.2597879407D2*x**2 &
     &         - 1.7269620096D0*x**3 + 1.0976121399D-2*x**4             &
     &         - 2.6627944718D-5*x**5
       endif
       return
!
   10  if(x .lt. 92) then
         adjust=-5.6311241293D4 + 3.1365823694D3*x - 6.9353058283D1*x**2&
     &         + 7.5993959736D-1*x**3 - 4.1202223864D-3*x**4            &
     &         + 8.8259599581D-6*x**5
       else
         adjust=1.7144441992D5 - 9.1589422413D3*x + 1.9479755544D2*x**2 &
     &         - 2.0623824143D0*x**3 + 1.0872576982D-2*x**4             &
     &         - 2.2839849588D-5*x**5
       endif
       return
!
   15  if(x .lt. 92) then
         adjust=-1.8454956519D4 + 1.0766778232D3*x - 2.5042424166D1*x**2&
     &         + 2.9014131881D-1*x**3 - 1.6737720228D-3*x**4            &
     &         + 3.8448825110D-6*x**5
       else
         adjust=3.8096974272D4 - 1.9978532184D3*x + 4.1744876078D1*x**2 &
     &         - 4.3446470296D-1*x**3 + 2.2526805177D-3*x**4            &
     &         - 4.6562003076D-6*x**5
       endif
       return
!
      END
