!$ALBFLX
      SUBROUTINE ALBFLX(SVECT,SFLUX,COSTHG,SINTHG,AMJD,RSUN,NSEG,ACS,   &
     &ECS,SOLNA,SOLNE,NPOINT,AA,SFLUXSW,SFLUXLW)
!********1*********2*********3*********4*********5*********6*********7**
! ALBFLX           89/05/23            0000.0    PGMR: SBL
!
! FUNCTION: CALCULATE TOTAL CONTRIBUTION OF LONG WAVE AND SHORT
!           WAVE RADIANCE FOR EACH OF THE EARTH AREA SPOTS FOR ALBEDO
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   SVECT    I    A    CARTESIAN ECF VECTORS OF THE AREA SPOTS
!   SFLUX    O    A    SUMMATION OF LONG WAVE AND SHORT WAVE RADIANCE
!                      FOR THE AREA SPOTS
!   COSTHG   I    S    COSINE OF THE GREENWICH HOUR ANGLE
!   SINTHG   I    S    SINE OF THE GREENWICH HOUR ANGLE
!   AMJD     I    S    MODIFIED JULIAN DATE IN DAYS
!   RSUN     O    S    EARTH - SUN DISTANCE
!   NSEG     I    A    VARIABLE NUMBER OF SEGMENTS AS RINGS INCREASE
!   ACS      I    A    ALBEDO MODEL COEFFICIENTS
!   ECS      I    A    EMMISIVITY MODEL COEFFICIENTS
!   SOLNA    I    A    SOLAR LONGITUDE  FOR THE ALBEDO MODEL
!   SOLNE    I    A    SOLAR LONGITUDE  FOR THE EMISSIVITY MODEL
!
! COMMENTS:
!
! REFERENCES: KNOCKE, P.,AND RIES, J.,"EARTH RADIATION PRESSURE EFFECTS
!                   ON SATELLITES"; CENTER FOR SPACE RESEARCH,
!                   UNIVERSITY OF TEXAS AT AUSTIN, SEPTEMBER, 1987.
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/ALBMIS/ALBON,ALBCON,EMSCON,ALBTUM,XALBMI
      COMMON/ALBINT/IRINGS,ISPOTS,IMAXA,IMAXE,MMAXA,MMAXE,KMAXA,KMAXE,  &
     &              KALB,KEMM,KLMOD,IMODEL,NPNALB,NXALBI
      COMMON/ALBMAX/MRINGS,MSPOTS,MIMAXA,MIMAXE,MMMAXA,MMMAXE,          &
     &              MKMAXA,MKMAXE,                                      &
     &              MIMA1A,MIMA1E,MMMA1A,MMMA1E,                        &
     &              MKMA1A,MKMA1E,                                      &
     &              NXALMX
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
!           *ALBINT* MARS ALBEDO INTEGER INFORMATION
!           IRINGS - NUMBER OF RINGS SPECIFIED FOR ALBEDO MODEL
!           ISPOTS - TOTAL NUMBER OF SPOTS WITHIN THE RINGS
!                    IT WILL BE USED FOR ALLOCATIONS IN THE FUTURE
!           IMAXA  - MAXIMUM DEGREE FOR ALBEDO MODEL
!           IMAXE  - MAXIMUM DEGREE FOR EMISSIVITY MODEL
!           MMAXA  - MAXIMUM ORDER FOR ALBEDO MODEL
!           MMAXE  - MAXIMUM ORDER FOR EMISSIVITY MODEL
!           KMAXA  - MAXIMUM TIME PERIODS FOR ALBEDO
!           KMAXE  - MAXIMUM TIME PERIODS FOR EMISSIVITY
!           KALB   - COUNTER FOR ALTIME 1 CARDS SECOND READ
!           KEMM   - COUNTER FOR ALTIME 0 CARDS SECOND READ
!           KLMOD  - MODEL INDICATOR =1 ALBEDO
!                                    =0 EMISSIVITY
!           IMODEL - MODEL INDICATOR =1 EARTH DEFAULT MODEL
!                                    =0 NEW PLANET MODEL
!           NXALBI - NO. OF WORDS IN COMMON BLOCK ALBINT
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CBDTRU/BDTRUE(7,999)
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
!
      DIMENSION AA(1)
      DIMENSION NSEG(1)
      DIMENSION SVECT(NPOINT,3),SFLUX(1),SUNECF(3)
      DIMENSION ACS(MIMAXA+1,MMMAXA+1,2,MKMAXA)
      DIMENSION ECS(MIMAXE+1,MMMAXE+1,2,MKMAXE)
      DIMENSION SOLNA(MKMAXA,2),SOLNE(MKMAXE,2)
      DIMENSION SFLUXSW(ISPOTS),SFLUXLW(ISPOTS)
!
      DATA TWO/2.0D0/,ONE/1.0D0/,C360D0/360.0D0/,C180D0/180.0D0/
      DATA C90D0/90.0D0/,C365P/365.25D0/,ZERO/0.0D0/,THREE/3.0D0/
      DATA CP5/0.5D0/,FOUR/4.0D0/
      DATA C1/0.1D0/,A0/0.34D0/,A2/0.29D0/,CK1/0.07D0/
!CC   DATA T0/14960.0D0/,C1/0.1D0/,A0/0.34D0/,A2/0.29D0/,CK1/0.07D0/
      DATA E0/0.68D0/,E2/0.18D0/
!
!   T0 - THE EPOCH DAY FOR HARMONIC COEFFICIENTS (FROM GEDYN REF.TIME)
!   T0= 2444960.5 (Dec.21 0.0h 1981) - GEODYN REF. TIME
!   A0,A2,C1,CK1,E0,E2  - ARE THE HARMONIC COEFFICIENTS
!
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      T0=2444960.5D0-TMGDN1
!
      MXD=MAX(MIMAXE,MIMAXA)
      MXO=MAX(MMMAXE,MMMAXA)
!
! CALCULATE SUN'S POSITION IN ECF
       SUNECF(1)=BDTRUE(1,8)*COSTHG+BDTRUE(2,8)*SINTHG
       SUNECF(2)=-BDTRUE(1,8)*SINTHG+BDTRUE(2,8)*COSTHG
       SUNECF(3)=BDTRUE(3,8)
!      THE BODY-FIXED LONGITUDE OF THE SUN IS REQUIRED
       SNLON = ATAN2(SUNECF(2),SUNECF(1))
! CALCULATE DISTANCE TO SUN
      RSUN=SQRT(SUNECF(1)**2+SUNECF(2)**2+SUNECF(3)**2)
! CALCULATE ARGUMENT OF FIRST PERIODIC TERM : AFPT
      DIFF=AMJD-T0
      AFPT=(MOD(DIFF,C365P)*TWOPI)/C365P
      DO 200 I=1,NSEG(IRINGS+1)
! CALCULATE THE SINE OF THE LATITUDE OF EACH SPOT
      SLAT=SVECT(I,3)/AE
!
!
!
      IF(IMODEL.EQ.1) THEN
! THE LATITUDE AND LONGITUDE OF EACH SURFACE SPOT IS NEEDED
        DIFF=SLAT-1.D0
        IF(SLAT.GT.1.D0.AND.DIFF.LT.0.000000005D0) THEN
        SLAT=1.D0
        ENDIF
        DIFF=1.D0-SLAT
        IF(SLAT.LT.-1.D0.AND.DIFF.GT.-0.000000005D0) THEN
        SLAT=-1.D0
        ENDIF
        SPLAT = ASIN(SLAT)
        SPLON = ATAN2(SVECT(I,2),SVECT(I,1))
        SPLAT = ASIN(SLAT)
        SPLON = ATAN2(SVECT(I,2),SVECT(I,1))
! COMPUTE LOCAL SOLAR TIME OF SURFACE SPOT (RADIANS SINCE MIDNIGHT
! THIS IS NEEDED FOR THE MARS EMMISSIVITY MODEL
        IF(ICBDGM.EQ.3) THEN
           SUNTIM = SPLON
        ELSE
           SUNTIM = SPLON - SNLON + PI
        ENDIF
        IF(SUNTIM.LT.0)SUNTIM=SUNTIM+TWOPI
        IF(SUNTIM.GE.TWOPI)SUNTIM=SUNTIM-TWOPI
      ENDIF
!
!
!
! TEST TO SEE IF AREA ELEMENT IS IN SUNLIGHT
! .....FIND COSINE OF ANGLE BETWEEN AREA NORMAL AND SUN VECTOR
      CSN=SUNECF(1)*SVECT(I,1)+SUNECF(2)*SVECT(I,2)+SUNECF(3)*SVECT(I,3)
      CSN=CSN/RSUN/AE
! IF THE ANGLE BETWEEN THE SUN'S VECTOR AND THE SPOT NORMAL IS GREATER
! THEN 90 DEGREES THEN THE SPOT IS IN DARKNESS SO DO NOT CALCULATE A
! SHORT WAVE CONTRIBUTION TO THE RADIANCE
      SWRAD=ZERO
      IF(CSN.LT.ZERO) GOTO 100
! ALBCON CONTAINS THE USER INPUT VALUE OF ALBEDO
      IF(ALBCON.GT.ZERO) THEN
      ALBEDO=ALBCON
      ELSE
!
         IF(IMODEL.EQ.0) THEN
! APPLY DEFAULT MODEL
         A1=C1*COS(AFPT)
         ALBEDO=A0+A1*SLAT+A2*CP5*                                      &
     &   (THREE*(SLAT**2)-ONE)
!
         ELSE
! APPLY INPUT MODEL
! RECALL THAT THE MARS ALBEDO MODEL IS DEFINED W.R.T.
! BODY-FIXED GEOGRAPHIC LATITUDE AND LONGITUDE
! MUST CHECK HERE THE LONGITUDE AND CALL THE APPROPRIATE MODEL
      DO 50 JJ=1,KMAXA
      SOLN1=SOLNA(JJ,1)*DEGRAD
      SOLN2=SOLNA(JJ,2)*DEGRAD
!     IF(SPLON.GE.SOLN1.AND.SPLON.LE.SOLN2) THEN
      K=JJ
          DUMALB = 0.0D0
          CALL GETALB(AA(KPALB),ACS(1,1,1,1),MIMAXA,MMMAXA,             &
     &               MKMAXA,K,IMAXA,MMAXA,SPLAT,                        &
     &    SPLON,DUMALB,MXD,MXO)
          ALBEDO = DUMALB
!     ENDIF
   50 END DO
      ENDIF
      ENDIF
! CALCULATE SHORT WAVE RADIANCE
      SWRAD=ALBEDO*CSN
! CALCULATION OF THE EMISSIVITY OF THE SPOT AREA
  100 CONTINUE
! EMSCON CONTAINS THE USER INPUT VALUE OF ALBEDO
      IF(EMSCON.GT.ZERO) THEN
      EMISSI=EMSCON
      ELSE
!
         IF(IMODEL.EQ.0) THEN
! APPLY DEFAULT MODEL
      E1=-CK1*COS(AFPT)
      EMISSI=E0+E1*SLAT-E2*CP5*                                         &
     &   (THREE*(SLAT**2)-ONE)
         ELSE
!
! APPLY INPUT MODEL
! MUST CHECK HERE THE LONGITUDE AND CALL THE APPROPRIATE MODEL
      DO 150 JJ=1,KMAXE
      SOLN1=SOLNE(JJ,1)*DEGRAD
      SOLN2=SOLNE(JJ,2)*DEGRAD
!     IF(SUNTIM.GE.SOLN1.AND.SUNTIM.LE.SOLN2) THEN
      K=JJ
           DUMEMM = 0.0D0
           CALL GETALB(AA(KPALB),ECS(1,1,1,1),MIMAXE,MMMAXE,            &
     &                 MKMAXE,K,IMAXE,MMAXE,SPLAT,                      &
     &     SUNTIM,DUMEMM,MXD,MXO)
           EMISSI = DUMEMM
!     ENDIF
  150 END DO
      ENDIF
      ENDIF
! CALCULATION OF LONGWAVE RADIANCE
      ALWRAD=EMISSI/FOUR
      DEG = 360.0D0/TWOPI
!     IF(I.EQ.NSEG(IRINGS+1).AND.IMODEL.EQ.1)THEN
!        WRITE(6,201)I,SPLAT*DEG,SPLON*DEG,SUNTIM*DEG,DUMEMM
!     ENDIF
!201    FORMAT(1X,I3,3F13.2,2D15.6)
! SUM OF LONG WAVE AND SHORT WAVE RADIANCE FOR THIS PARTICULAR SPOT
      SFLUX(I)=SWRAD+ALWRAD
      SFLUXSW(I)=SWRAD
      SFLUXLW(I)=ALWRAD
  200 END DO
      RETURN
      END
