!$ARCLOD
      SUBROUTINE ARCLOD(AA,II,LL,IARC,LOAD,LCOMBK,LDYNAM)
!********1*********2*********3*********4*********5*********6*********7**
! ARCLOD           84/03/29            0000.0    PGMR - EDDY
!
! FUNCTION:         CONTROL LOADING OF ARC INFORMATION FROM EXTENDED
!                   VIRTUAL MEMORY TO DYNAMIC MEMORY AND UNLOADING
!                   OF ARC INFORMATION FROM DYNAMIC MEMORY TO
!                   EXTENDED VIRTUAL MEMORY.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   IARC     I    S    CURRENT ARC NUMBER
!   LOAD     I    S    LOGICAL FLAG CONTROLLING DIRECTION OF LOAD
!                   .TRUE. LOAD FROM EXTENDED V.M. TO DYNAMIC ARRAYS
!                   .FALSE. UNLOAD FROM DYNAMIC ARRAYS TO EXTENDED VM
!   LCOMBK   I    S    LOGICAL FLAG CONTROLLING COMMON BLOCK INFO.
!                   .TRUE. ARC COMMON BLOCK INFORMATION WILL BE
!                      LOADED OR UNLOADED AS INDICATED BY LOAD
!                   .FALSE. ARC COMMON BLOCKS WILL BE LEFT ALONE
!   LDYNAM   I    S    LOGICAL FLAG CONTROLLING DYNAMIC ARRAY INFO
!                   .TRUE. ARC DYNAMIC ARRAYS WILL BE LOADED OR
!                      UNLOADED AS INDICATED BY LOAD
!                   .FALSE. ARC DYNAMIC ARRAYS WILL BE LEFT ALONE
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      DIMENSION AA(1),II(1),LL(1)
!
      DATA LRDIFF/.FALSE./
!
!***********************************************************************
! START OF EXECUTABLE CODE
!***********************************************************************
!
      IF(.NOT. LCOMBK) GO TO 500
!
! LOAD/UNLOAD ARC COMMON BLOCKS FROM/TO EXTENDED VIRTUAL MEMORY
!
      CALL IFRACB(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,IDUM,DUM)
!
! LOAD/UNLOAD ARC DYNAMIC ARRAYS FROM/TO EXTENDED VIRTUAL MEMORY
!
  500 IF(.NOT.LDYNAM) GO TO 1000
!
      CALL IFRAD1(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,DUM)
      CALL IFRAD2(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,DUM)
      CALL IFRAD4(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,DUM)
      CALL IFRAD6(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,DUM)
      CALL IFRAD7(AA,II,LL,IARC,LRDIFF,LOAD,IDUM,DUM)
!
 1000 RETURN
      END
