!$BARYC
      SUBROUTINE BARYC(MJDSEC,FSEC,XPC,VPC,NDXVPC,                      &
     &                 IGRPX,IOR,IORMOX,IORSNX,IOREMX,                  &
     &                 COEF,COEFMO,COEFS,COEFEM,                        &
     &                 NM,NDIM1,NDIM2,LVEL,LTBODY,LSUNV,                &
     &                 PARCBD,PARTBD,PSTAT,PSUN,PMOON,                  &
     &                 CHEB,CHEBV,CHEBS,CHEBSV,CHEBMO,CHBVMO,           &
     &                 TTTMO,TTT,TWOT,AA,II)
!********1*********2*********3*********4*********5*********6*********7**
! BARYC            88/09/08            8901.0    PGMR - A. MARSHALL
!                  03.11.92            9201.0       LUCIA TSAOUSSI
!
!
!  FUNCTION:              PUT PLANET CENTERED (TRUE OF SAT REF)
!                         COORDINATES INTO BARYCENTRIC (TRUE SAT REF)
!                         MODEL CORRECTIONS TO THE PLANETARY EPHEMERIS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I         INTEGER SECONDS SINCE GEODYN REFERENCE TIME
!   FSEC     I         FRACTIONAL REMAINING SECONDS (COORDINATE ET)
!   XPC     I\O        PLANET CENTERD TRUE OF SAT REF SYTEM POS INPUT
!                      BARYCENTERD TRUE OF SAT REF SYTEM POS OUTPUT
!   VPC     I\O        PLANET CENTERD TRUE OF SAT REF SYTEM VEL INPUT
!                      BARYCENTERD TRUE OF SAT REF SYTEM VEL OUTPUT
!   NDXVPC   I         FIRST DIMENSION OF XPC &VPC
!   IGRP     I         CENTRAL BODY GROUP (MERCURY=3, OTHERWISE=1)
!   IOR      I         ORDER OF CHEBYSHEV POLYNOMIALS
!   IORMO    I         ORDER OF CHEBYSHEV POLYNOMIALS (MOON)
!   IORSUN   I         ORDER OF CHEBYSHEV POLYNOMIALS (SUN)
!   COEF     I         CHEBYSHEV POLYNOMIAL COEFFICIENTS
!   COEFMO   I         CHEBYSHEV POLYNOMIAL COEFFICIENTS (MOON)
!   COEFS    I         CHEBYSHEV POLYNOMIAL COEFFICIENTS (SUN)
!   NM       I         NUMBER OF TIMES
!   LVEL     I         TRUE IF VELOCITY CALCULATIOONS REQUIRED
!   LTBODY   I         TRUE IF PLANET IS TRACKING BODY
!   LSUNV    I         TRUE IF VECTOR FROM XPC TO SUN SHOULD BE CALC.
!   PSTAT    O         PLANET STATE IN BARYCENTRIC TRUE SAT REF SYSTEM
!   PSUN     O         SUN    STATE IN BARYCENTRIC TRUE SAT REF SYSTEM
!   PMOON    O         MOON   STATE IN BARYCENTRIC TRUE SAT REF SYSTEM
!   CHEB     O         CHEBYSHEV POLYNOMIALS
!   CHEBV    O         CHEBYSHEV VELOCITY POLYNOMIALS
!   CHEBS    O         CHEBYSHEV POLYNOMIAL (SUN)
!   CHEBSV   O         CHEBYSHEV VELOCITY POLYNOMIAL (SUN)
!   CHEBMO   O         CHEBYSHEV POLYNOMIAL (MOON)
!   CHBVMO   O         CHEBYSHEV VELOCITY POLYNOMIAL (MOON)
!   TTTMO         A    NORMALIZED MOON TIME
!   TTT           A    NORMALIZED TIME (FSEC)
!   TWOT          A    SCRATCH ARRAY
!
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBARYC/CBODY(6),TBODY(6),SUNRF(6)
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/COREPH/EMJDS0(2),EFSEC0(2),EMODE(2),ECORR(2),              &
     &              PSTAE0(12),DEBC(12),SGMEBC(12),BODYID(2),XCOEPH
      COMMON/EPHM/FSECXY(1),XP(261),YP(261),A1UT(261),EP(261),EC(261),  &
     &            FSCFLX(1),FLUXS(36),AVGFLX(36),FLUXM(288),FSECEP(1),  &
     &            EPHP(816),EPHN(96),ELIB(120),BUFT(2700),FSECNP(4)
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      DIMENSION FSEC(NM),COEF(3,IOR),COEFMO(3,IORMO),COEFS(3,IORSUN)
      DIMENSION COEFEM(3,IOREM),DXDEBC(6,6),PSTATC(6),CB(6),TB(6)
      DIMENSION CHEB(NM,IOR),CHEBV(NM,IOR),                             &
     &          CHEBS(NM,IORSUN),CHEBSV(NM,IORSUN),                     &
     &          CHEBMO(NM,IORMO),CHBVMO(NM,IORMO),                      &
     &          PSTAT(NM,6),PMOON(NM,6),PSUN(NM,3),                     &
     &          XPC(NDXVPC,3),VPC(NDXVPC,3),PARCBD(NM,36),PARTBD(NM,36)
      DIMENSION TTT(NM),TTTMO(NM),FNSEC(4),TWOT(NM),VSEC(4)
      DIMENSION AA(1),II(1)
      DATA ZERO/0.0D0/,ONE/1.0D0/,TWO/2.0D0/
      DATA FNSEC/2764800.D0,1382400.D0,691200.D0,345600.D0/
      DATA LEPOCT,LEPOCC/.TRUE.,.TRUE./
      DATA ONETH/1.0D3/
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! INITIALIZE
      NM3 = NM*3
      NM6 = NM*6
      VSEC(1)=TWO/FNSEC(1)
      VSEC(2)=TWO/FNSEC(2)
      VSEC(3)=TWO/FNSEC(3)
      VSEC(4)=TWO/FNSEC(4)
!  SET FLAGS FOR CORRECTING THE EPHEMERIS STATE VECTOR
      LCNVEL=ECORR(1).EQ.1.D0
      LTRVEL=ECORR(2).EQ.1.D0
      DO 100 I=1,NM
      CHEB(I,1) = ONE
      CHEBV(I,1)= ZERO
      CHEBV(I,2)= ONE
  100 END DO
!
      IF(.NOT.LTBODY) GOTO 1300
      DO 200 I=1,NM
      DO 200 J=1,3
      PSTAT(I,J) = ZERO
      PMOON(I,J) = ZERO
  200 CONTINUE
      IF (LVEL.OR.LTRVEL) THEN
      DO 250 I=1,NM
      DO 250 J=4,6
      PSTAT(I,J) = ZERO
      PMOON(I,J) = ZERO
  250 CONTINUE
      ENDIF
!
! CALCULATE TRACKING BODY COORDINATES (ASSUME EARTH)
!
! MAP MJDSEC,FSEC INTO INTERVAL  -1,1  FOR EACH PERIOD GROUP
! FIGURE POINTER WHITHIN 32 DAY RECORD FOR EACH PERIOD GROUP
      FSECC1=FSECNP(ICHBOG(2,3))
      RNSEC=ONE/FNSEC(ICHBOG(2,3))
      DO 400 I=1,NM
      TTT(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTT(I)=TTT(I)*TWO-ONE
  400 END DO
!
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
      LCHEBV=LVEL.OR.LTRVEL
!     WRITE(6,*) ' BARYC : LCHEBV FLAG ',LCHEBV,LVEL,LTRVEL
      CALL CHEBPV(CHEB,CHEBV,TTT,IOR,NM,TWOT,LCHEBV)
!
! COMPUTE POSITION
      DO 500 I=1,3
      DO 500 J=1,IOR
      DO 500 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+COEF(I,J)*CHEB(K,J)
  500 CONTINUE
!
      IF(LVEL.OR.LTRVEL) THEN
!     WRITE(6,*) ' BARYC : COMPUTE  VELOCITY ARRAY'
! COMPUTE VELOCITY
      DO 600 I=1,IOR
      DO 600 J=1,NM
      CHEBV(J,I)=CHEBV(J,I)*VSEC(ICHBOG(2,3))
  600 CONTINUE
      DO 700 I=4,6
      DO 700 J=1,IOR
      DO 700 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+COEF(I-3,J)*CHEBV(K,J)
  700 CONTINUE
      ENDIF
!
!     IGRPT1=TMT1/FNSEC(4)
!     FSECC1=FSECEP(1+ITOTTT)+IGRPT1*FNSEC(4)
      FSECC1=FSECNP(ICHBOG(2,10))
      RNSEC=ONE/FNSEC(ICHBOG(2,10))
      DO 800 I=1,NM
      TTTMO(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTTMO(I)=TTTMO(I)*TWO-ONE
  800 END DO
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
      DO 850 I=1,NM
      CHEBMO(I,1) = ONE
      CHBVMO(I,1) = ZERO
      CHBVMO(I,2) = ONE
  850 END DO
!
      CALL CHEBPV(CHEBMO,CHBVMO,TTTMO,IORMO,NM,TWOT,LCHEBV)
!
! COMPUTE POSITION
      DO 900 I=1,3
      DO 900 J=1,IORMO
      DO 900 K=1,NM
      PMOON(K,I) = PMOON(K,I)+COEFMO(I,J)*CHEBMO(K,J)
  900 CONTINUE
!
      IF(LVEL.OR.LTRVEL) THEN
! COMPUTE VELOCITY
      DO 1000 I=1,IORMO
      DO 1000 J=1,NM
      CHBVMO(J,I) = CHBVMO(J,I)*VSEC(ICHBOG(2,10))
 1000 CONTINUE
      DO 1100 I=4,6
      DO 1100 J=1,IORMO
      DO 1100 K=1,NM
      PMOON(K,I) = PMOON(K,I)+COEFMO(I-3,J)*CHBVMO(K,J)
 1100 CONTINUE
      ENDIF
!
      DO 1200 I=1,3
      DO 1200 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)-PMOON(K,I)
 1200 CONTINUE
      IF(LVEL.OR.LTRVEL) THEN
      DO 1250 I=4,6
      DO 1250 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)-PMOON(K,I)
 1250 CONTINUE
      ENDIF
!
!  CORRECT THE PLANET EPHEMERIS / HERE EARTH'S POSITION
!  -----------------------------------------------------
!
      IF (ECORR(2).EQ.0.D0) GO TO 1815
!
      IF (LEPOCT) THEN
      MJDS=EMJDS0(2)
      CALL PLANPT(MJDS,EFSEC0(2),.TRUE.,.TRUE.,CB,TB)
!     WRITE(6,*) ' TEST PLANPT CALCULATIONS'
!     WRITE(6,*) 'BARYC : CBODY  ', CB
!     WRITE(6,*) 'BARYC : TBODY  ', TB
          DO 1251 I=1,6
          PSTAE0(6+I)=TB(I)*ONETH
!     WRITE(6,*) ' BARYC : I , EPOCH   PSTAE0  ', PSTAE0(6+I)
 1251    CONTINUE
      END IF
      IXTB=IPLNIN(ITBDGM)
!     WRITE(6,*) ' BARYC : IXTB , IS IT 9 ??  ',IXTB
        DO 1810 IE=1,NM
          DO 1805 IP=1,6
          PSTATC(IP)=PSTAT(IE,IP)
 1805   CONTINUE
      DELT=DBLE(MJDSEC)+FSEC(IE)-EMJDS0(2)-EFSEC0(2)
      CALL EPHCOR(PSTAE0(7),PSTATC,DELT,BDSTAT(7,8),                    &
     &            BDSTAT(7,IXTB),DXDEBC)
!     WRITE(6,*) ' BARYC : LEPOCH  TR BD ',LEPOCT
      DO 1808 J=1,6
      DO 1808 K=1,6
      PSTAT(IE,J)=PSTAT(IE,J)+DXDEBC(J,K)*DEBC(6+K)
!     WRITE(6,*) ' UPDATED PSTAT(IE,J)  ',IE, J, PSTAT(IE,J)
      M=(J-1)*6+K
!     WRITE(6,*) ' BARYC : M INDEX =  ',M
      PARTBD(IE,M)=DXDEBC(J,K)
 1808 CONTINUE
 1810 END DO
!
!  CONTINUE HERE WHEN NOT CORRECTING THE TRACKING BODY POSITION ***
!  _________________________________________________________________
!
 1815 CONTINUE
!
      GOTO 1900
!
 1300 CONTINUE
      IF(.NOT.LMOON) GOTO 1349
!
! ******************************************************************
!
! IF MOON IS CENTRAL BODY THEN EVALUATE THE EARTH SS BARYC VECTOR AND
! ADD THAT TO THE EARTH CENTERED MOON VECTOR TO GET THE SS BARYC MOON
! VECTOR.
!
! CALCULATE EARTH-MOON BARYC VECTOR
! NOTE: SINCE IOREM=IORSUN THEN THE ARRAYS FOR THE SUN WILL
!       TEMPORARILY BE USED HERE.
!
! MAP MJDSEC,FSEC INTO INTERVAL  -1,1  FOR EACH PERIOD GROUP
! FIGURE POINTER WHITHIN 32 DAY RECORD FOR EACH PERIOD GROUP
      FSECC1=FSECNP(ICHBOG(2,3))
      RNSEC=ONE/FNSEC(ICHBOG(2,3))
      DO 1310 I=1,NM
      TTT(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTT(I)=TTT(I)*TWO-ONE
 1310 END DO
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
! CHEBS AND CHEBSV ARE TEMPORARILY USED HERE FOR THE EARTH BECAUSE
! THE SUN AND THE EARTH HAVE THE SAME ORDER
      DO 1311 I=1,NM
      CHEBS(I,1) = ONE
      CHEBSV(I,1)= ZERO
      CHEBSV(I,2)= ONE
 1311 END DO
!
      LCHEBV=LVEL.OR.LCNVEL
      CALL CHEBPV(CHEBS,CHEBSV,TTT,IOREM,NM,TWOT,LCHEBV)
!
      DO 1312 I=1,NM
      DO 1312 J=1,3
      PSTAT(I,J) = ZERO
 1312 CONTINUE
      IF (LVEL.OR.LCNVEL) THEN
      DO 1314 I=1,NM
      DO 1314 J=4,6
      PSTAT(I,J) = ZERO
 1314 CONTINUE
      ENDIF
!
! COMPUTE POSITION
      DO 1315 I=1,3
      DO 1315 J=1,IOREM
      DO 1315 K=1,NM
      IF(K.EQ.1) THEN
      ENDIF
      PSTAT(K,I) = PSTAT(K,I)+COEFEM(I,J)*CHEBS(K,J)
 1315 CONTINUE
!
      IF(LVEL.OR.LCNVEL) THEN
! COMPUTE VELOCITY
      DO 1316 I=1,IOREM
      DO 1316 J=1,NM
      CHEBSV(J,I)=CHEBSV(J,I)*VSEC(ICHBOG(2,3))
 1316 CONTINUE
      DO 1317 I=4,6
      DO 1317 J=1,IOREM
      DO 1317 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+COEFEM(I-3,J)*CHEBSV(K,J)
 1317 CONTINUE
      ENDIF
!
! EVALUATE THE EARTH-MOON BARYC EARTH VECTOR
!
      FSECC1=FSECNP(ICHBOG(2,10))
      RNSEC=ONE/FNSEC(ICHBOG(2,10))
      DO 1318 I=1,NM
      TTTMO(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTTMO(I)=TTTMO(I)*TWO-ONE
 1318 END DO
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
      DO 1319 I=1,NM
      CHEBMO(I,1) = ONE
      CHBVMO(I,1) = ZERO
      CHBVMO(I,2) = ONE
 1319 END DO
      CALL CHEBPV(CHEBMO,CHBVMO,TTTMO,IORMO,NM,TWOT,LCHEBV)
      DO 1320 I=1,NM
      DO 1320 J=1,3
      PMOON(I,J) = ZERO
 1320 CONTINUE
      IF (LVEL.OR.LCNVEL) THEN
      DO 1321 I=1,NM
      DO 1321 J=4,6
      PMOON(I,J) = ZERO
 1321 CONTINUE
      ENDIF
!
! COMPUTE POSITION
      DO 1322 I=1,3
      DO 1322 J=1,IORMO
      DO 1322 K=1,NM
      PMOON(K,I) = PMOON(K,I)+COEFMO(I,J)*CHEBMO(K,J)
 1322 CONTINUE
!
      IF(LVEL.OR.LCNVEL) THEN
! COMPUTE VELOCITY
      DO 1330 I=1,IORMO
      DO 1330 J=1,NM
      CHBVMO(J,I) = CHBVMO(J,I)*VSEC(ICHBOG(2,10))
 1330 CONTINUE
      DO 1331 I=4,6
      DO 1331 J=1,IORMO
      DO 1331 K=1,NM
      PMOON(K,I) = PMOON(K,I)+COEFMO(I-3,J)*CHBVMO(K,J)
 1331 CONTINUE
      ENDIF
!
! EVALUATE SS BARYC EARTH VECTOR
!
      DO 1332 I=1,3
      DO 1332 K=1,NM
      PMOON(K,I) = PSTAT(K,I)-PMOON(K,I)
 1332 CONTINUE
      IF(LVEL.OR.LCNVEL) THEN
      DO 1334 I=4,6
      DO 1334 K=1,NM
      PMOON(K,I) = PSTAT(K,I)-PMOON(K,I)
 1334 CONTINUE
      ENDIF
! ******************************************************************
!
 1349 CONTINUE
      DO 1350 I=1,NM
      DO 1350 J=1,3
      PSTAT(I,J) = ZERO
 1350 CONTINUE
      IF(LVEL.OR.LCNVEL) THEN
      DO 1375 I=1,NM
      DO 1375 J=4,6
      PSTAT(I,J) = ZERO
 1375 CONTINUE
      ENDIF
! CALCULATE CENTER  OF INTEGRATION COORDINATES
!
! MAP MJDSEC,FSEC INTO INTERVAL  -1,1  FOR EACH PERIOD GROUP
! FIGURE POINTER WHITHIN 32 DAY RECORD FOR EACH PERIOD GROUP
! CENTRAL BODY
      FSECC1=FSECNP(IGRP)
      RNSEC=ONE/FNSEC(IGRP)
      DO 1500 I=1,NM
      TTT(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTT(I)=TTT(I)*TWO-ONE
 1500 END DO
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
      LCHEBV=LVEL.OR.LCNVEL
!     WRITE(6,*) ' BARYC : LCHEBV FLAG ',LCHEBV,LVEL,LCNVEL
      CALL CHEBPV(CHEB,CHEBV,TTT,IOR,NM,TWOT,LCHEBV)
!
! COMPUTE POSITION
      DO 1600 I=1,3
      DO 1600 J=1,IOR
      DO 1600 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+COEF(I,J)*CHEB(K,J)
 1600 CONTINUE
!
! COMPUTE VELOCITY
      IF(LVEL.OR.LCNVEL) THEN
      DO 1700 I=1,IOR
      DO 1700 J=1,NM
      CHEBV(J,I) = CHEBV(J,I)*VSEC(IGRP)
 1700 CONTINUE
      DO 1800 I=4,6
      DO 1800 J=1,IOR
      DO 1800 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+COEF(I-3,J)*CHEBV(K,J)
 1800 CONTINUE
      ENDIF
!
      IF(LMOON) THEN
      DO 1820 I=1,3
      DO 1820 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+PMOON(K,I)
 1820 CONTINUE
        IF(LVEL.OR.LCNVEL) THEN
      DO 1870 I=4,6
      DO 1870 K=1,NM
      PSTAT(K,I) = PSTAT(K,I)+PMOON(K,I)
 1870 CONTINUE
        ENDIF
!
      ENDIF
!
!  CORRECT THE PLANET EPHEMERIS / HERE CENTRAL BODY STATE VECTOR
!  --------------------------------------------------------------
!
      IF (ECORR(1).EQ.0.D0) GO TO 1818
!
      IF (LEPOCC) THEN
      MJDS=EMJDS0(1)
      CALL PLANPC(MJDS,EFSEC0(1),.TRUE.,.TRUE.,II,CB,TB)
!     WRITE(6,*) ' TEST PLANPC CALCULATIONS'
!     WRITE(6,*) ' BARYC: CBODY  ', CB
!     WRITE(6,*) ' BARYC: TBODY  ', TB
          DO 1801 I=1,6
          PSTAE0(I)=CB(I)*ONETH
!     WRITE(6,*) ' BARYC : I , EPOCH   PSTAE0  ', PSTAE0(I)
 1801    CONTINUE
!     WRITE(6,*) ' BARYC : INIT. EPOCH  EMJDS0 ', EMJDS0(1),EFSEC0(1)
      END IF
      IXCB=IPLNIN(ICBDGM)
!     WRITE(6,*) ' BARYC : IXCB  IS IT 2???  ', IXCB
      DO 1811 IE=1,NM
        DO 1802 IP=1,6
          PSTATC(IP)=PSTAT(IE,IP)
 1802   CONTINUE
      DELT=DBLE(MJDSEC)+FSEC(IE)-EMJDS0(1)-EFSEC0(1)
      CALL EPHCOR(PSTAE0,PSTATC,DELT,BDSTAT(7,8),                       &
     &            BDSTAT(7,IXCB),DXDEBC)
!     WRITE(6,*) ' BARYC : LEPOCH CNT BD   ', LEPOCC
      DO 1809 J=1,6
      DO 1809 K=1,6
      PSTAT(IE,J)=PSTAT(IE,J)+DXDEBC(J,K)*DEBC(K)
!     WRITE(6,*) ' UPDATED PSTAT(IE,J)  ',IE, J, PSTAT(IE,J)
      M=(J-1)*6+K
!     WRITE(6,*) ' BARYC : M INDEX =  ',M
      PARCBD(IE,M)=DXDEBC(J,K)
 1809 CONTINUE
 1811 END DO
!
!  CONTINUE HERE WHEN NOT CORRECTING THE CENTRAL BODY POSITION ***
!  _________________________________________________________________
!
 1818 CONTINUE
!
!
 1900 CONTINUE
! CALCULATE SUN COORDINATES
      IF(LSUNV) THEN
      DO 2000 I=1,NM
      CHEBS(I,1)  = ONE
      DO 2000 J=1,3
      PSUN(I,J)  = ZERO
 2000 CONTINUE
!     IGRPT1=TMS1/FNSEC(1)
!     FSECC1=FSECEP(1+ITOTTT)+IGRPT1*FNSEC(1)
      FSECC1=FSECNP(ICHBOG(2,11))
      RNSEC=ONE/FNSEC(ICHBOG(2,11))
      DO 2100 I=1,NM
      TTT(I)=((MJDSEC-FSECC1)+FSEC(I))*RNSEC
      TTT(I)=TTT(I)*TWO-ONE
 2100 END DO
!
! COMPUTE CHEBYSHEV POLYNOMIALS AT APPROPRIATE TIMES
      CALL CHEBPV(CHEBS,CHEBSV,TTT,IORSUN,NM,TWOT,.FALSE.)
!
! COMPUTE POSITION
      DO 2200 I=1,3
      DO 2200 J=1,IORSUN
      DO 2200 K=1,NM
      PSUN(K,I) = PSUN(K,I)+COEFS(I,J)*CHEBS(K,J)
 2200 CONTINUE
      ENDIF
!
      DO 2300 I=1,NM
      XPC(I,1)=XPC(I,1)+PSTAT(I,1)
      XPC(I,2)=XPC(I,2)+PSTAT(I,2)
      XPC(I,3)=XPC(I,3)+PSTAT(I,3)
 2300 END DO
      IF(.NOT.LVEL) GO TO 2500
      DO 2400 I=1,NM
      VPC(I,1)=VPC(I,1)+PSTAT(I,4)
      VPC(I,2)=VPC(I,2)+PSTAT(I,5)
      VPC(I,3)=VPC(I,3)+PSTAT(I,6)
 2400 END DO
 2500 CONTINUE
!
      IF(.NOT.LSUNV) RETURN
      DO 2600 I=1,NM
      PSUN(I,1)=PSUN(I,1)-XPC(I,1)
      PSUN(I,2)=PSUN(I,2)-XPC(I,2)
      PSUN(I,3)=PSUN(I,3)-XPC(I,3)
 2600 END DO
      RETURN
      END
