!$BIASES
      SUBROUTINE BIASES(PMPA  ,RESID ,RESIDU,EDTSIG,RATIO ,OBSSIG,      &
     &    EDFLAG,LEDIT ,NDIM1 ,NDIM2 ,NM    ,NTYPE ,ISTATS,LBEDIT,      &
     &    LNEDIT,RESCAL,LSCALE,AA    ,II    ,LL    )
!********1*********2*********3*********4*********5*********6*********7**
! BIASES           00/00/00            0000.0    PGMR - T. MARTIN
!
! FUNCTION:       CONTROLS REMOVING MEASUREMENT BIASES, EDITING OF
!                 DATA (REGULAR AND LOCAL EDITING) AND COMPUTATION
!                 OF ELECTRONIC BIASES
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PMPA          A    PARTIALS OF MEASUREMENTS WRT PARAMETERS
!   RESID         A    MEASUREMENT RESIDUALS
!   RESIDU        A    MEASUREMENT RESIDUALS SCALED FOR PRINTOUT
!   EDTSIG        S    EDITING SIGMA
!   RATIO         A    RATIO OF RESIDUAL TO MEASUREMENT SIGMA
!   OBSSIG        A    MEASUREMENT SIGMA
!   EDFLAG  I/O   A    ARRAY FOR EDITING FLAGS FOR RESIDUAL PRINTOUT
!   LEDIT   I/O   A    ARRAY OF EDITING SWITCHES FOR EACH POINT
!   NDIM1    I    S    FIRST DIMENSION OF PMPA
!   NDIM2    I    S    SECOND DIMENSION OF PMPA
!                      IF LNPNM = .TRUE. -  NDIM1 = NO. OF PARAMETERS
!                      IF LNPNM = .TRUE. -  NDIM2 = NO. OF MEASUREMENTS
!                      IF LNPNM = .FALSE.-  NDIM1 = NO. OF MEASUREMENTS
!                      IF LNPNM = .FALSE.-  NDIM2 = NO. OF PARAMETERS
!
!   NM       I    S    NUMBER OF MEASUREMENTS IN CURRENT BLOCK
!   NTYPE    I    S    MEASUREMENT TYPE
!   ISTATS   I    S    NUMBER OF UNIQUE TRACKING/MTYPE CONFIGURATIONS
!   LBEDIT
!   LNEDIT   I    S    LOCAL EDITING SWITCH (DO LOCAL EDIT IF .FALSE.)
!   RESCAL   I    A    SCALE FACTOR FOR RESIDUAL OUTPUT UNITS
!   LSCALE
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL VARIABLES.
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER VARIABLES
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL VARIABLES
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/ANTID/ISATAN(3),ISTAN1(3),ISATN1(3),ISTAN2(3),ISATN2(3),   &
     &             IANNB1(3),IANNB2(3)
      COMMON/CEDIT /EDITX ,EDTRMS,EDLEVL,CONVRG,GLBCNV,EBLEVL,EDITSW,   &
     &              ENPX  ,ENPRMS,ENPCNV,EDBOUN,FREEZI,FREEZG,FREEZA,   &
     &              XCEDIT
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/RAMPS/TRINT(1000,2,2),FRINT(1000,2,2),TRAMP(1000,2),       &
     &             FRAMP(1000),FDRAMP(1000),RSCALX(1000),SCALX(1000),   &
     &             XINTS(1000),XINTB(1000),XINTS2(1000),RSCALY(1000)
!
      DIMENSION PMPA(NDIM1,NDIM2),RESID (NM),OBSSIG(NM),RATIO (NM),     &
     &          EDFLAG(NM),LEDIT(NM),RESIDU(NM),EDTSIG(NM)
      DIMENSION AA(1),II(1),LL(1)
!
! INDEXX IS DIMENS. BY THE MAXIMUM NO. OF BIAS PARAMETERS APPLICABLE
!        TO A SINGLE MEASUREMENT (MINDEX).
      DIMENSION INDEXX(26)
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!
! SUBTRACT SIMPLE MEASUREMENT BIAS FROM OBSERVATION RESIDUALS
      CALL BSUB  (PMPA,NDIM1,NDIM2,RESID,NM,NTYPE,INDEXX,NINDEX,LNPNM, &
     &  AA(KPRMVC),AA(KOBSC))
!
! ON FIRST ITERATION EDIT RESIDUAL RATIOS AGAINST E-BIAS EDIT LEVEL
!    TO ELIMINATE GROSS RESIDUALS AFTER REMOVING BIAS VALUES
      IF(LITER1) CALL RESEDT(EBLEVL,RESID,RESIDU,EDTSIG,RATIO,LEDIT,NM)
!
! REMOVE MOST UP-TO-DATE VALUE OF ELECTRONIC BIASES FROM RESIDUALS
      JF=KFSECS(1,1)
      CALL EBIASE(AA(KPMPE),AA(JF),RESID ,EDTSIG,RATIO ,OBSSIG,         &
     &            EDFLAG   ,LEDIT ,NTYPE ,LBEDIT,LNEDIT,AA(KOBSC),AA)
!
!
!     ....SKIP LOCAL EDITING IF LNEDIT = .TRUE.
      IF(LNEDIT) GO TO 6000
!
! IF NO BIAS PARAMETERS FOR THIS OBSERVATION BLOCK, BYPASS LOCAL EDITING
      IF(NINDEX.LE.0) GO TO 6000
! BYPASS LOCAL EDIT FOR GPS
      IF(NTYPE.GT.80) GO TO 6000
      LBEDIT=.TRUE.
      CALL BSEDIT(PMPA  ,RESID ,EDTSIG,RATIO ,OBSSIG,EDFLAG,LEDIT ,     &
     &   NM    ,INDEXX,NINDEX)
!
 6000 CONTINUE
!
! RESOLVE ELECTRONIC BIASES
!
      CALL EBIAS (PMPA  ,AA(KPMPE) ,RESID ,RESIDU,EDTSIG,RATIO ,OBSSIG, &
     &    LEDIT ,NTYPE ,ISTATS,AA(KBTWB),AA(KTBTWA),AA(KBTWD),          &
     &    RESCAL, LSCALE, EDFLAG, AA    ,II    ,LL    )
!
! APPLY ANTENNA SPECIFIC TRANSPONDER DELAYS FOR RANGE DATA
!
      IF(NTYPE.NE.53) RETURN
      IF(IANNB1(1).LE.0.OR.IANNB1(1).GT.4) RETURN
      IF(NPVAL(IXANTD).LE.0) RETURN
      NUMD=NPVAL(IXANTD)
!
      DO 6100 I=1,NUMD
! IN THIS LOOP USE AUXARRAYS FOR SATID AND ANT # TO FIGURE WHICH
! (IF ANY) TRANSPONDER DELAY APPLIES
! DELAY IS IN METERS
!
      IPT=IPVAL(IXANTD)+I-1
      IF(ISATAN(1).NE.II(KTDSAT-1+I)) GO TO 6100
      IF(IANNB1(1).NE.II(KTDANT-1+I)) GO TO 6100
      GO TO 6200
 6100 CONTINUE
      RETURN
 6200 CONTINUE
      DO N=1,NM
        RESID (N)=RESID (N)-AA(KPRMV+IPT-1)*RSCALX(N)
      ENDDO
      IPT0=II(KPTRUA-1+IPT)
      IF(IPT0.LE.0) RETURN
      IF(.NOT.LSTINR) RETURN
      LL(KLAVOI-1+IPT0)=.FALSE.
      IF(LNPNM) THEN
        DO N=1,NM
          PMPA(IPT0,N)=RSCALX(N)
        ENDDO
      ELSE
        DO N=1,NM
          PMPA(N,IPT0)=RSCALX(N)
        ENDDO
      ENDIF
      RETURN
      END
