!$BID
      SUBROUTINE BID(MT,MJDSBL,FSECBL,SECEND,JSTANO,JSATNO,IPAMB,IP900, &
     &               IPS51,IPS52,IP902,IPS61,IPS62,                     &
     &               IPS720,IPS721,IPS722,IPS723,IP156)
!********1*********2*********3*********4*********5*********6*********7**
!  BID             00/00/00         0000.0      PGMR - ?
!
! FUNCTION: Identify Biases for sake of punch
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MT       I    S    MEASUREMENT TYPE
!   MJDSBL   I    S    MJD  OF DATA BLOCK START
!   FSECBL   I    S    TIME OF DATA BLOCK START IN SECONDS
!   SECEND   I    S    ELAPSED TIME IN SECONDS
!                      FROM DATA BLOCK START TO DATA BLOCK END
!   JSTANO   I    A    STATION   IDS OF THE UP-TO-3 STATIONS
!   JSATNO   I    A    SATELLITE IDS OF THE UP-TO-3 SATELLITES
!   IPAMB
!   IP900
!   IPS51
!   IPS52
!   IP902
!   IPS61
!   IPS62
!   IPS720
!   IPS721
!   IPS722
!   IPS723
!   IP156
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**

      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION JSTANO(3),JSATNO(3)
      DIMENSION FSEC(1),IYMD(1),IHM(1),SEC(1)
      DIMENSION JYMD(1),JHM(1),SEJ(1)
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/XPARMB/MPARMB,NPARMB,MPOBS,JPAMB,ISKIPE,                   &
     &             ITPARM(5,28000),ISTABP(3,28000),                     &
     &             ISATBP(3,28000),IPRMBF(28000)
      COMMON/ZPARMB/MPARMZ,ITPRMZ(1000),ISTABZ(3,1000),                 &
     &             ISATBZ(3,1000),IPRMPY(1000),IPRMZ(1000),IUSECY(1000)
!
      ITM1=MJDSBL+FSECBL
      ITM2=MJDSBL+SECEND
!
      IF(IPAMB.GT.0) THEN
        IPX=IPAMB-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=MT
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        IF(I1.EQ.2147483647) ITPARM(2,IPX)=ITM1
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=JSTANO(1)
        ISTABP(2,IPX)=JSTANO(2)
        ISTABP(3,IPX)=JSTANO(3)
        ISATBP(1,IPX)=JSATNO(1)
        ISATBP(2,IPX)=JSATNO(2)
        ISATBP(3,IPX)=JSATNO(3)
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IP900.GT.0) THEN
        IPX=IP900-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=900
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        IF(MT.EQ.40) THEN
          ISTABP(1,IPX)=0
          ISTABP(2,IPX)=0
          ISTABP(3,IPX)=0
          ISATBP(1,IPX)=JSATNO(1)
          ISATBP(2,IPX)=0
          ISATBP(3,IPX)=0
        ELSE
          ISTABP(1,IPX)=JSTANO(1)
          ISTABP(2,IPX)=0
          ISTABP(3,IPX)=0
          ISATBP(1,IPX)=0
          ISATBP(2,IPX)=0
          ISATBP(3,IPX)=0
        ENDIF
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IP902.GT.0) THEN
        IPX=IP902-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=900
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        IF(MT.EQ.85) THEN
          ISTABP(1,IPX)=0
          ISTABP(2,IPX)=0
          ISTABP(3,IPX)=0
          ISATBP(1,IPX)=JSATNO(1)
          ISATBP(2,IPX)=0
          ISATBP(3,IPX)=0
        ELSE
          ISTABP(1,IPX)=JSTANO(2)
          ISTABP(2,IPX)=0
          ISTABP(3,IPX)=0
          ISATBP(1,IPX)=0
          ISATBP(2,IPX)=0
          ISATBP(3,IPX)=0
        ENDIF
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IPS51.GT.0) THEN
        IPX=IPS51-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=500
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=JSTANO(1)
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=0
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IPS52.GT.0) THEN
        IPX=IPS52-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=500
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=JSTANO(2)
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=0
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IPS61.GT.0) THEN
        IPX=IPS61-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=600
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=JSTANO(1)
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=0
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IPS62.GT.0) THEN
        IPX=IPS62-IPVAL0(IXBISA)+1
        ITPARM(1,IPX)=600
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=JSTANO(2)
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=0
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
!     IF(IPS720.GT.0) THEN
      IF(IPS720.GT.0.AND.MT.EQ.56) THEN
        IPX=IPS720-IPVAL0(IXBISA)+1
! WILL NEED SOMETHING FANCIER FOR 700 TO INDICATE ALL (APPLICABLE) MTs
! OR A PARTICULAR MT ONLY. FOR PATCH 400 WILL DO
        ITPARM(1,IPX)=700
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=0
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=JSATNO(2)
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
!     IF(IPS721.GT.0) THEN
      IF(IPS721.GT.0.AND.MT.EQ.56) THEN
        IPX=IPS721-IPVAL0(IXBISA)+1
! WILL NEED SOMETHING FANCIER FOR 700 TO INDICATE ALL (APPLICABLE) MTs
! OR A PARTICULAR MT ONLY. FOR PATCH 400 WILL DO
        ITPARM(1,IPX)=701
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=0
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=JSATNO(2)
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
!     IF(IPS722.GT.0) THEN
      IF(IPS722.GT.0.AND.MT.EQ.56) THEN
        IPX=IPS722-IPVAL0(IXBISA)+1
! WILL NEED SOMETHING FANCIER FOR 700 TO INDICATE ALL (APPLICABLE) MTs
! OR A PARTICULAR MT ONLY. FOR PATCH 400 WILL DO
        ITPARM(1,IPX)=702
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=0
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=JSATNO(2)
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
!     IF(IPS723.GT.0) THEN
      IF(IPS723.GT.0.AND.MT.EQ.56) THEN
        IPX=IPS723-IPVAL0(IXBISA)+1
! WILL NEED SOMETHING FANCIER FOR 700 TO INDICATE ALL (APPLICABLE) MTs
! OR A PARTICULAR MT ONLY. FOR PATCH 400 WILL DO
        ITPARM(1,IPX)=703
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=0
        ISTABP(2,IPX)=0
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=JSATNO(2)
        ISATBP(2,IPX)=0
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
!
      IF(IP156.GT.0.AND.MT.EQ.56) THEN
        IPX=IP156-IPVAL0(IXBISA)+1
! WILL NEED SOMETHING FANCIER FOR 700 TO INDICATE ALL (APPLICABLE) MTs
! OR A PARTICULAR MT ONLY. FOR PATCH 400 WILL DO
        ITPARM(1,IPX)=156
        I1=ITPARM(2,IPX)
        ITPARM(2,IPX)=MIN(I1,ITM1)
        I2=ITPARM(3,IPX)
        ITPARM(3,IPX)=MAX(I2,ITM2)
        ISTABP(1,IPX)=0
        ISTABP(2,IPX)=JSTANO(2)
        ISTABP(3,IPX)=0
        ISATBP(1,IPX)=JSATNO(1)
        ISATBP(2,IPX)=JSATNO(2)
        ISATBP(3,IPX)=0
        IPRMBF(IPX)=-98
      ENDIF
      IF(IP156.GT.0.AND.MT.NE.56) THEN
! FOR CYCLE SLIP REPAIR CAPABILITY
        IPX=IP156-IPVAL0(IXBISA)+1
        IPX=IPX-NAMBBH
        ISTABZ(1,IPX)=JSTANO(1)
        ISTABZ(2,IPX)=JSTANO(2)
        ISTABZ(3,IPX)=JSTANO(3)
        ISATBZ(1,IPX)=JSATNO(1)
        ISATBZ(2,IPX)=JSATNO(2)
        ISATBZ(3,IPX)=JSATNO(3)
        ITPRMZ(IPX)=MT
      ENDIF
!
!      FSEC(1)=0.E0
!      CALL YMDHMS(ITM1,FSEC,IYMD,IHM,SEC,1)
!      CALL YMDHMS(ITM2,FSEC,JYMD,JHM,SEJ,1)
!      WRITE(6,34567) IYMD,IHM,SEC
!34567 FORMAT(' BLOCK START ',I6,2X,I4,2X,F10.2)
!      WRITE(6,34568) JYMD,JHM,SEJ
!34568 FORMAT(' BLOCK END   ',I6,2X,I4,2X,F10.2)
!      WRITE(6,34569) MT
!34569 FORMAT(' MEASUREMENT TYPE ',I10)
!      WRITE(6,34570) JSTANO
!34570 FORMAT(' JSTANO ',3I12)
!      WRITE(6,34571) JSATNO
!34571 FORMAT(' JSATNO ',3I12)
!      WRITE(6,34572) IPAMB
!34572 FORMAT(' IPAMB ',I10)
!      WRITE(6,34573) IP900,IP902
!34573 FORMAT(' IP900 IP902 ',2I10)
!      WRITE(6,34574) IPS51,IPS52
34574 FORMAT(' IPS500 IPS502 ',2I10)
!      IF(MT.EQ.85.AND.IP902.GT.0) WRITE(6,34575)
!34575 FORMAT(' $$$$$$ LOOK HERE ######')
      RETURN
      END
