!$BLKOUT
      SUBROUTINE BLKOUT(OBSBUF,OBFOUT,INDBUF,OBSNRM,OBSNM2,SUMCR2,      &
     &      OBSDIF,BINSIG,NWTD  ,NPOINT)
!********1*********2*********3*********4*********5*********6*********7**
! BLKOUT           86/06/04            8606.0    PGMR - TOM MARTIN
!
! FUNCTION:  LOAD OBSERVATION RECORDS FROM INTERNAL
!            OBSERVATION BUFFER INTO OUTPUT BUFFERS.
!            DUMP ANY PREVIOUSLY FILLED OBSERVATION BLOCK.
!            OVERWRITE OBSERVATION RECORD WITH NORMAL POINT DATA.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   OBSBUF   I    A    INTERNAL OBSERVATION BUFFER.
!   OBFOUT   I    A    OUTPUT BUFFERS.
!   INDBUF   I    A    INDICES OF OPEN BUFFERS.
!   OBSNRM   I    S    OBSERVATION NORMAL POINT VALUE.
!   OBSNM2        S    SECOND WORD IN THE OBSERVATION BUFFER VARIES
!                      WITH MTYPE
!   SUMCR2        S    NORMAL POINT REDUCTION VALUE
!   OBSDIF   I    S    DIFFERENCE BETWEEN OBSERVATION NORMAL POINT
!                      AND OBSERVATION THAT IT REPLACES.
!                      "REDUCTION VALUE"
!   BINSIG   I    S    NORMAL POINT BIN STANDARD ERROR.
!   NWTD     I    S    NUMBER OF OBSERVATIONS USED TO COMPUTE THE
!                      NORMAL POINT.
!   NPOINT   I    S    INDEX WITHIN THE INTERNAL OBSERVATION BLOCK
!                      OF THE OBSERVATION BEING REPLACED BY THE
!                      NORMAL POINT.
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      PARAMETER ( ZERO = 0.0D0 )
!
! /CBLOKI/ INTEGER INFORMATION ABOUT DATA BLOCK
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
! /CNORMI/ NORMAL POINT OPTION INTEGER DATA
      COMMON/CNORMI/NRECDF,NRECDH,INDREC,MPTS  ,NPTS  ,NPLEFT
! /CNORML/ NORMAL POINT OPTION LOGICAL DATA
      COMMON/CNORML/LNORM ,LNORMP
! /CSIML/ SIMDAT OPTION LOGICAL DATA
      COMMON/CSIML/LSIMTI
! /COBBUF/ OBSERVATION BLOCK POINTERS
      COMMON/COBBUF/IOBSBF,IBUF1 ,IBUF2 ,IWORD1,NHEADR,NWORDM
! /COBGLO/ GLOBAL OBSERVATION PROCESSING LIMITS
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
! /COBLOC/ OBSERVATION BLOCK DYNAMIC ARRAY POINTERS
!          STATION INFORMATION POINTERS TO COORDINATE SYSTEM ARRAYS
!          OBSERVATION BUFFER POINTERS
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
!
      DIMENSION OBSBUF(1),OBFOUT(MSIZE,MPART,MBUF),INDBUF(MBUF)
      DIMENSION JPART(5)
      DIMENSION JOBCOR(9,8)
!
      EQUIVALENCE (KOBS,JOBCOR(1,1))
!
      DATA JPART/3,4,5,7,8/
      DATA METRIX/37/,MOPT/12/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      LOP=(MTYPE.GT.MOPT).AND.(MTYPE.LT.METRIX).AND.(MTYPE.NE.31)
!
      IF(NPTS.LT.MPTS) GO TO 1000
! OUTPUT BLOCK FULL -- DUMP TO OUTPUT DEVICE AND OPEN NEW BLOCK
      NUMOBS=NPLEFT-MPTS
      CALL BLKHDR(OBFOUT,INDBUF,OBSBUF,NUMOBS)
 1000 CONTINUE
!
      NPT1=NPOINT-KOBBUF
      NPTS=NPTS+1
! MOVE OBSERVATION RECORD INTO OUTPUT BUFFER
      ND0REC=INDREC+NRECDH
      DO 3000 IRTYPE=1,8
!.....DESTINATION RECORD AND BUFFER
      NDXREC=ND0REC+NPTS
      IBUF=(NDXREC-1)/MSIZE
      NDXREC=NDXREC-IBUF*MSIZE
      NDXBUF=INDBUF(IBUF+1)
!.....LOOP OVER PARTITION NUMBERS
      DO 2000 IPART=1,9
      IF(.NOT.LSWTCH(IPART,IRTYPE)) GO TO 2000
!.....ADDRESS WITHIN OBSERVATION BUFFER
      JOBREC=JOBCOR(IPART,IRTYPE)+NPT1
!.....MOVE DATA
      OBFOUT(NDXREC,IPART,NDXBUF)=OBSBUF(JOBREC)
      LABEL=.TRUE.
 2000 END DO
!.....INCREMENT RECORD TYPE POINTER
      ND0REC=ND0REC+MPTS
 3000 END DO
!
! GET POINTER TO TIME CORR IN OBSBUF
      JTMCOR=KTMCOR+NPT1
! GET INDICIES FOR OBS TIME IN OBFOUT
      ND0REC=INDREC+NRECDH
      NDXREC=ND0REC+NPTS
      IBUF=(NDXREC-1)/MSIZE
      NDXREC=NDXREC-IBUF*MSIZE
      NDXBUF=INDBUF(IBUF+1)
! REMOVE TIME CORRECTION FROM OBS TIME (NEGATE 8400 LOOP IN OBSRD)
      OBFOUT(NDXREC,6,NDXBUF)=OBFOUT(NDXREC,6,NDXBUF)+OBSBUF(JTMCOR)
!
! MOVE SUM OF CORRECTIONS AND OBSERVATION SIGMAS INTO OUTPUT BUFFER
      DO 4000 I=4,8
! IF SIMULATED DATA CARDS ARE PRESENT AND THE IONOSPHERIC OPTION IS
! SELECTED DO NOT OVERWRITE OBSERVATION SIGMAS.
      IF((I.EQ.7.OR.I.EQ.8).AND.LSIMDT.AND.LIONC) GO TO 4000
      IF(.NOT.LFS(I+30)) GO TO 4000
!.....PARTITION NUMBER
      IPART=JPART(I-3)
!.....ADDRESS WITHIN OBSERVATION BUFFER
      JOBREC=KOBSUM(I)+NPT1
!.....DESTINATION RECORD AND BUFFER
      NDXREC=INDREC+NRECDH+NPTS
      IBUF=(NDXREC-1)/MSIZE
      NDXREC=NDXREC-IBUF*MSIZE
      NDXBUF=INDBUF(IBUF+1)
!.....MOVE DATA
      OBFOUT(NDXREC,IPART,NDXBUF)=OBSBUF(JOBREC)
 4000 END DO
      IF(.NOT.LSIMTI) GO TO 4100
!
!.....OVERWRITE OBSERVATION WITH SIMULATED DATA
      OBFOUT(NDXREC,1,NDXBUF)=OBSNRM
      IF(.NOT.LOP) RETURN
      OBFOUT(NDXREC,2,NDXBUF)=OBSNM2
      OBFOUT(NDXREC,4,NDXBUF)=SUMCR2
      RETURN
 4100 CONTINUE
      IF(.NOT.LNORM) RETURN
      IF(MTYPE.LT.METRIX) RETURN
!
! NORMAL POINT PROCESSING OCCURS BELOW THIS POINT
!
!.....OVERWRITE OBSERVATION WITH NORMAL POINT
      OBFOUT(NDXREC,1,NDXBUF)=OBSNRM
!.....OVERWRITE OBSERVATION SIGMA WITH BIN STANDARD ERROR
      OBFOUT(NDXREC,7,NDXBUF)=BINSIG
!
      IF(MTYPE.EQ.99.OR.MTYPE.EQ.100.OR.MTYPE.EQ.199) GO TO 5000
!
! RANGE AND DOPPLER NORMAL POINTS
!
!.....LOAD NORMAL POINT REDUCTION VALUE INTO OUTPUT BUFFER
      OBFOUT(NDXREC,4,NDXBUF)=OBSDIF
!.....LOAD NUMBER OF WEIGHTED OBSERVATIONS IN BIN INTO OUTPUT BUFFER
      OBFOUT(NDXREC,8,NDXBUF)=NWTD
!
! ALTIMETER NORMAL POINTS
!
 5000 CONTINUE
!
!.....POINTERS TO OBSERVATION CORRECTIONS RECORD
      NDXREC=INDREC+NRECDH+NPTS+MPTS
      IBUF=(NDXREC-1)/MSIZE
      NDXREC=NDXREC-IBUF*MSIZE
      NDXBUF=INDBUF(IBUF+1)
!
!.....ZERO OUT THE RELATIVISTIC CORRECTION ON THE OBSERVATION
!.....CORRECTIONS RECORD IN CASE OF RANGE OR DOPPLER NORMAL POINT
!.....GENERATION
!
      IF(MTYPE.EQ.99.OR.MTYPE.EQ.199) GO TO 5010
!
      OBFOUT(NDXREC,8,NDXBUF)=ZERO
      RETURN
!
 5010 CONTINUE
!
!.....LOAD NORMAL POINT REDUCTION VALUE INTO OUTPUT BUFFER
      OBFOUT(NDXREC,9,NDXBUF)=OBSDIF
!.....POINTERS TO LOCATION DATA RECORD
      NDXREC=INDREC+NRECDH+NPTS+MPTS*3
      IBUF=(NDXREC-1)/MSIZE
      NDXREC=NDXREC-IBUF*MSIZE
      NDXBUF=INDBUF(IBUF+1)
!.....LOAD NUMBER OF WEIGHTED OBSERVATIONS IN BIN INTO OUTPUT BUFFER
      OBFOUT(NDXREC,9,NDXBUF)=NWTD
      RETURN
      END
