!$BLKTYP
      SUBROUTINE BLKTYP(OBFOUT,INDBUF,MSIZE,MPART,MBUF,MPTS,RECTYP,     &
     &    ND0REC)
!********1*********2*********3*********4*********5*********6*********7**
! BLKTYP           86/06/04            8606.0    PGMR - TOM MARTIN
!
! FUNCTION:  LOAD RECORD TYPE INDICATORS INTO OBSERVATION BLOCK
!            WITHIN OUTPUT BUFFERS.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   OBFOUT   I    A    OUTPUT BUFFERS.
!   INDBUF   I    A    INDICES OF OPEN BUFFERS.
!   MSIZE    I    S    MAXIMUM NUMBER OF LOGICAL RECORDS WITHIN
!                      EACH OUTPUT BUFFER.
!   MPART    O    S    NUMBER OF PARTITIONS WITHIN EACH OUTPUT
!                      BUFFER.
!   MBUF     I    S    BUFFER NUMBER.
!   MPTS     O    S    NUMBER OF LOGICAL RECORDS IN THIS LOGICAL
!                      BLOCK.
!   RECTYP   O    S    RECORD TYPE INDICATOR TO BE LOADED.
!   ND0REC   O    S    INDEX OF LOGICAL RECORD IMMEDIATELY
!                      PRECEDING LOGICAL RECORDS TO BE TYPED.
!   NUMOBS   O    S    MAXIMUM NUMBER OF OUTPUT BUFFERS.
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      DIMENSION OBFOUT(MSIZE,MPART,MBUF),INDBUF(MBUF)
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      ND1REC=ND0REC+1
      NBUF1=(ND1REC-1)/MSIZE
      NDNREC=ND0REC+MPTS
      NBUFN=(NDNREC-1)/MSIZE
      N1=ND1REC-NBUF1*MSIZE
      N2=NDNREC-NBUF1*MSIZE
!.....FIRST BUFFER WITH APPROPRIATELY TYPED RECORDS
      N2=MIN(N2,MSIZE)
      NDXBUF=INDBUF(NBUF1+1)
      DO 1000 N=N1,N2
      OBFOUT(N,MPART,NDXBUF)=RECTYP
 1000 END DO
      IF(NBUFN-NBUF1-1) 7000,5000,2000
!.....WHOLE BUFFERS WITH ONLY APPROPRIATELY TYPED RECORDS
 2000 CONTINUE
      ND1BUF=INDBUF(NBUF1+2)
      NDNBUF=INDBUF(NBUFN)
      NBUF2=NBUF1+2
      DO 4000 IBUF=NBUF2,NBUFN
      NDXBUF=INDBUF(IBUF)
      DO 3000 N=1,MSIZE
      OBFOUT(N,MPART,NDXBUF)=RECTYP
 3000 END DO
 4000 END DO
!.....FINAL BUFFER WITH APPROPRIATELY TYPED RECORDS
 5000 CONTINUE
      N2=NDNREC-NBUFN*MSIZE
      NDXBUF=INDBUF(NBUFN+1)
      DO 6000 N=1,N2
      OBFOUT(N,MPART,NDXBUF)=RECTYP
 6000 END DO
 7000 CONTINUE
      RETURN
      END
