!$BSUB
      SUBROUTINE BSUB  (PMPA  ,NDIM1 ,NDIM2 ,RESID ,NM    ,NTYPE ,      &
     &                  INDEXX,NINDEX,LNPNM,PARMVC,OBSC )
!********1*********2*********3*********4*********5*********6*********7**
! BSUB             86/03/25            8604.0    PGMR - TOM MARTIN
!
! FUNCTION:  REMOVE CURRENT VALUE OF BIASES FROM OBSERVATION
!            RESIDUALS.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PMPA     I    A    OBSERVATION PARTIAL DERIVATIVE MATRIX
!   NDIM1    I    S
!   NDIM2    I    S
!   RESID    I    A    OBSERVATION RESIDUALS
!   NM       I    S    NUMBER OF OBSERVATIONS
!   NTYPE    I    S    MEASUREMENT TYPE
!   INDEXX   O    A    INDICES OF BIASES THAT APPLY TO THESE
!                      OBSERVATIONS
!   NINDEX   O    S    NUMBER OF BIASES THAT APPLY TO THESE
!                      OBSERVATIONS
!   LNPNM    I    S    SWITCH FOR ORDER OF DIMENSION OF PMPA
!                      LNPNM = .T. ORDER  = NADJST,NM
!                      LNPNM = .F. ORDER = NM,NADJST
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      PARAMETER ( METRIX = 37 )
      PARAMETER( ONE    = 1.0D0 )
!
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      COMMON/IRAMPS/INDRAM,KKRAMP
      COMMON/RAMPS/TRINT(1000,2,2),FRINT(1000,2,2),TRAMP(1000,2),       &
     &             FRAMP(1000),FDRAMP(1000),RSCALX(1000),SCALX(1000),   &
     &             XINTS(1000),XINTB(1000),XINTS2(1000),RSCALY(1000)
!
      DIMENSION PMPA  (NDIM1 ,NDIM2 ),RESID (NM)
      DIMENSION OBSC(NM)
! INDEXX IS DIMENS. BY THE MAXIMUM NO. OF BIAS PARAMETERS APPLICABLE
!        TO A SINGLE MEASUREMENT (MINDEX).
      DIMENSION INDEXX(43)
      DIMENSION PARMVC(1)
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!     write(6,*)' dbg enter BSUB PMPA ',NDIM1,NDIM2
!     DO JJ=1,NDIM1
!     DO KK=1,NDIM2
!     WRITE(6,*)' dbg ',PMPA(JJ,KK)
!     ENDDO
!     ENDDO
!     DO JJ=27,42
!     write(6,*)' BSUB BIAS VALUES ',BIASM(JJ),JJ
!     ENDDO
!
! SUBTRACT SIMPLE MEASUREMENT BIAS FROM OBSERVATION RESIDUALS
      NINDEX=0
      NUMOBS=MOD(NTYPE-1,2)+1
!  *** BIASES ADDED FOR VLBI DATA PROCESSING  ***  LT  11.08.91  ***
!     IF(NTYPE.LT.13.OR.NTYPE.GE.METRIX) NUMOBS=1

      IF(LSPL85) THEN

      ICNT=0
      NUMOBS=1
  500 CONTINUE
      ICNT=ICNT+1
      IF(ICNT.GT.4) GOTO 1000
      INDEXB=IMBIAS(NUMOBS)
      IF(INDEXB.LE.0) GO TO 720
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      IF(NUMOBS.EQ.1.OR.NUMOBS.EQ.25) SCALE=ONE
      IF(NUMOBS.EQ.20.OR.NUMOBS.EQ.22) SCALE=-ONE
        DO 710 N=1,NM
         RESID (N)=RESID (N)-SCALE*BIASM (NUMOBS)
!     if(n==1) write(6,*)' dbg BSUB bias1',BIASM(NUMOBS),NUMOBS,LSPL85,
!    .SCALE
  710    CONTINUE
  720    CONTINUE
      IF(ICNT.EQ.1) NUMOBS=20
      IF(ICNT.EQ.2) NUMOBS=22
      IF(ICNT.EQ.3) NUMOBS=25
      GOTO 500

      ELSE

      IF(NTYPE.LT.13.OR.NTYPE.GE.31) NUMOBS=1
      INDEXB=IMBIAS(NUMOBS)
      IF(INDEXB.LE.0) GO TO 1000
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      IF(INDRAM.GT.0) THEN
         DO 800 N=1,NM
         RESID (N)=RESID (N)-BIASM (NUMOBS)*2.D0*RSCALX(N)
  800    CONTINUE
      ELSE

         DO 810 N=1,NM
       IF(NTYPE.NE.40) THEN
       RESID (N)=RESID (N)-BIASM (NUMOBS)
       ELSE

        IF (ABS(BIASM (NUMOBS)).GE.100.D0) THEN
        RESID (N)=RESID (N)-BIASM (NUMOBS)
        ELSE
        RESID (N)=RESID (N)-BIASM (NUMOBS)*(1.D0 - OBSC(N)/VLIGHT)
        ENDIF

       ENDIF

  810    CONTINUE
      ENDIF
      ENDIF

 1000 CONTINUE
      IBEG=2
      IF(NTYPE.LT.31) IBEG=3
      IF(LNPNM) GO TO 5000
! PARTIAL DERVIATIVE ARRAY DIMENSIONED (NM,NADJST)
!
! SUBTRACT NON-SIMPLE MEASUREMENT BIASES FROM OBSERVATION RESIDUALS
      DO 2000 I=IBEG,26
      INDEXB=IMBIAS(I)
      IF(INDEXB.LE.0) GO TO 2000
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      DO 1800 N=1,NM
      RESID(N)=RESID(N)-BIASM (I)*PMPA(N,INDEXB)
 1800 END DO
 2000 END DO

!     write(6,*)'dbgklk',KLKSTS(1,1),KLKSTS(1,2),KLKSTS(2,1),KLKSTS(2,2)
      DO 2001 I=27,42,2
      INDEXB=IMBIAS(I)
      IF(INDEXB.LE.0) GO TO 2001
!     WRITE(6,*)' IN THIS SPLINE THE VALUE OF THE PARAMETER LEFT IS: ',&
!    & BIASM(I+1)
       IF(BIASM(I+1).EQ.0.D0) GOTO 444
! FIND THE VALUE OF THE PARAMETER TO THE RIGHT
         DO JJ=1,MAPARM
       IF(BIASM(I+1).EQ.PARMVC(JJ)) THEN
       VRIGHT=PARMVC(JJ+1)
       ENDIF
       ENDDO
 444  CONTINUE
!     WRITE(6,*)' IN THIS SPLINE THE VALUE OF THE PARAMETER RIGHT IS: ',&
!    & VRIGHT

      NINDEX=NINDEX+1
      DO 1801 N=1,NM
!     WRITE(6,*)' IN THIS SPLINE THE PMPA LEFT OF THE PARAMETER IS: ',&
!    & PMPA(N,IMBIAS(I+1))
!     WRITE(6,*)' IN THIS SPLINE THE PMPA RIGHT OF THE PARAMETER IS: ',&
!    & PMPA(N,IMBIAS(I+1)+1)
      RESID(N)=RESID(N)-BIASM (I+1)*PMPA(N,IMBIAS(I+1))-   &
     &                  VRIGHT     *PMPA(N,IMBIAS(I+1)+1)
!     write(6,*)' dbg BSUB ',RESID(N),BIASM(I+1),PMPA(N,IMBIAS(I+1)),  &
!    &  VRIGHT,PMPA(N,IMBIAS(I+1)+1)
 1801 END DO
 2001 CONTINUE

      INDEXB=IMBIAS(43)
      IF(INDEXB.LE.0) GO TO 2002
      NINDEX=NINDEX+1
      DO 1802 N=1,NM
      RESID(N)=RESID(N)-BIASM (I)*PMPA(N,INDEXB)
 1802 END DO
 2002 CONTINUE

      RETURN
 5000 CONTINUE
! PARTIAL DERVIATIVE ARRAY DIMENSIONED (NADJST,NM)
!
! SUBTRACT NON-SIMPLE MEASUREMENT BIASES FROM OBSERVATION RESIDUALS
      DO 7000 I=IBEG,26
      INDEXB=IMBIAS(I)
      IF(INDEXB.LE.0) GO TO 7000
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      DO 6800 N=1,NM
      RESID(N)=RESID(N)-BIASM (I)*PMPA(INDEXB,N)
 6800 END DO
 7000 END DO

      DO 7001 I=27,42,2
      INDEXB=IMBIAS(I)
      IF(INDEXB.LE.0) GO TO 7001
!     WRITE(6,*)' IN THIS SPLINE THE VALUE OF THE PARAMETER LEFT IS: ',&
!    & BIASM(I+1)
       IF(BIASM(I+1).EQ.0.D0) GOTO 555
! FIND THE VALUE OF THE PARAMETER TO THE RIGHT
         DO JJ=1,MAPARM
       IF(BIASM(I+1).EQ.PARMVC(JJ)) THEN
       VRIGHT=PARMVC(JJ+1)
       ENDIF
       ENDDO
 555  CONTINUE
!     WRITE(6,*)' IN THIS SPLINE THE VALUE OF THE PARAMETER RIGHT IS: ',&
!    & VRIGHT
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      DO 6801 N=1,NM
      RESID(N)=RESID(N)-BIASM (I+1)*PMPA(IMBIAS(I+1),N)-   &
     &                  VRIGHT     *PMPA(IMBIAS(I+1)+1,N)
 6801 END DO
 7001 END DO

      INDEXB=IMBIAS(43)
      IF(INDEXB.LE.0) GO TO 7002
      NINDEX=NINDEX+1
      INDEXX(NINDEX)=INDEXB
      DO 6802 N=1,NM
      RESID(N)=RESID(N)-BIASM (I)*PMPA(INDEXB,N)
 6802 END DO
 7002 CONTINUE
      RETURN
      END
