!$BUFSUP
      SUBROUTINE BUFSUP(AA,MJDS1,FSEC1,MJDS2,FSEC2,ISUPE,BUFFER,ICB,IY)
!********1*********2*********3*********4*********5*********6*********7**
! BUFSUP                                         PGMR - D. PAVLIS
!
! FUNCTION:  READ AND SAVE THE SUPPLEMENTARY EPHEMERIS BUFFER FOR
!            THE INPUT TIMES
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDS1    I    S    INTEGER NUMBER OF SECONDS SINCE GEODYN REF.TIME
!                      FOR THE BEGIN TIME OF BLOCK TO BE TRANSFORMED
!   FSEC1    I    A    ELAPSED SECONDS SINCE MJDSEC FOR BEGIN TIME
!                      POINT
!   MJDS2    I    S    INTEGER NUMBER OF SECONDS SINCE GEODYN REF.TIME
!                      FOR THE END TIME OF BLOCK TO BE TRANSFORMED
!   FSEC2    I    A    ELAPSED SECONDS SINCE MJDSEC FOR END TIME
!                      POINT
! COMMENTS:  BUFSUP IS CALLED FROM SEVERAL SUBROUTINES. BUFSUP SHOULD RE
!            INITIALIZE THE ENDS OF THE EPHEMERIS BUFFER DURING THE
!            OBSERVATION MODELING. THE INDEX IY PREVENTS IT FROM RE-
!            INITIALIZING THE TIMES DURING THE CALL FROM COWELL.
!            RLTCOR REPRESENTS THE LIGHT TIME CORRECTION IS SAVED IN THE
!            COMMON BLOCK SAVLTC AnD IT IS RE-COMPUTED FOR EVERY BLOCK I
!            LITPRX CALLED FROM EXEC2E (OR SIMGEN)
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE

      COMMON/SAVLTC/RLTCOR
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/DYNPTR/KDEPHM,KDEPH2,KDAHDR(3,9),KDYNAP(3,9,2),KDNEXT(3),  &
     &NXDYNP
      COMMON/EPHMX/FSECSE(10,2)
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      DIMENSION AA(1)
      DIMENSION ISUPE(ICBODY,5),FSEC(1),BUFFER(ICBODY,MAXDEG,2)
      DATA FSEC/0.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      IADD=0
      DO I=2,ICB
        IADD=ISUPE(I-1,2)*ISUPE(I-1,1)+IADD
      ENDDO
      IPTR=KDEPH2+IADD
!
! THE ICBODY LOOP IS DONE BEFORE CALLING BUFSUP
! ITSYS=1 ET ; ITSYS=2 UTC
      ITSYS=ISUPE(ICB,4)
           JJ=0
           DO J=1,ISUPE(ICB,1)
!
      T1=AA(IPTR+JJ)
      T2=AA(IPTR+JJ+1)
      MJD=INT(T1)
      CALL MJDYMD(MJD,IYMD1,IHMS1,1)
      CALL YMDTIS(IYMD1,IHMS1,MJDB)
      MJD=INT(T2)
      CALL MJDYMD(MJD,IYMD2,IHMS2,1)
      CALL YMDTIS(IYMD2,IHMS2,MJDE)
      IF(ITSYS.EQ.2) THEN
      CALL UTCET(.TRUE.,1,MJDB,FSEC(1),FSECOT,AA(KA1UT))
      REM=FSECOT
      CALL UTCET(.TRUE.,1,MJDE,FSEC(1),FSECOT,AA(KA1UT))
      REM2=FSECOT
      ENDIF
!
!CCC
         IF(IY.EQ.2) RETURN
      M1=MJDS1+FSEC1-RLTCOR
      M2=MJDS2+FSEC2-RLTCOR
      IF(M1.GE.MJDB.AND.M2.LE.MJDE) THEN
! LOAD FSECSE(1) OF COMMON BLOCK EPHMX
! DEPDEP THIS MIGHT NOT BE OK
      FSECSE(ICB,1)=DBLE(MJDB)+REM
      FSECSE(ICB,2)=DBLE(MJDE)+REM2
        DO K=3,ISUPE(ICB,2)
      BUFFER(ICB,K-2,1)=AA(IPTR+JJ-1+K)
! LOAD NEXT BUFFER TOO
      BUFFER(ICB,K-2,2)=AA(IPTR+JJ+ISUPE(ICB,2)-1+K)
       ENDDO
      ENDIF
!CCC
!     write(6,*)' dbg BEGIN TIME ',IYMD1,IHMS1,MJDB
!     write(6,*)' dbg CURRENT TIME ',MJDS1,FSEC1
!     write(6,*)' dbg end CURRENT TIME ',MJDS2,FSEC2
!     write(6,*)' dbg END TIME ',IYMD2,IHMS2,MJDE
              JJ=JJ+ISUPE(ICB,2)
           ENDDO
      RETURN
      END
