!$BUFXTR
      SUBROUTINE BUFXTR(MJD1,FSC1,MJD2,FSC2,MSIGN,MJDR,FSECR,LRECAL,AA)
!********1******.**2*********3*********4*********5*********6*********7**
! BUFXTR           86/12/24            8701.0    PGMR - D. ROWLANDS
!
! FUNCTION:  FILL EPHEMERIS & INTERPOLATION ENPOINT COMMON BLOCKS
!            WITH PROPER INFORMATION FOR TIMES SPECIFIED IN
!            CALLING SEQUENCE FOR PLANETS OTHER THAN EARTH.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJD1     I    S    ENDPOINT TIME IN EPHEMERIS SECONDS FROM
!                      GEODYN REFERENCE TIME
!   FSC1     I    S    REMAINING SECONDS FROM MJD1
!   MJD2     I    S     ENDPOINT TIME
!   FSC2    I\O   S    REMAINING SECONDS FROM MJD2
!   MSIGN    I    S    POSITIVE # IF (MJD2+FSC2)>(MJD1+FSC1);
!                      OTHERWISE NGEATIVE
!   MJDR     O    S    OUTPUT ENPOINT TIME WHICH POSSIBLY REPLACES
!                      MJD2 IF REQUESTED INTERVAL IS TOO LARGE
!   FSECR         S
!   LRECAL   O    S    TRUE IF REQUESTED INTERVAL IS TOO LARGE.
!   AA      I/O   A    REAL DYNAMIC ARRAY
!
!  COMMENTS:  COMMON BLOCKS WILL BE FILLED WITH INFORMATION
!             ALLOWING COORDINATE SYSTEM CALLS BETWEEN ENPOINT
!             TIMES.IN THE CASE THAT THE REQUESTED INTERVAL IS
!             TOO LARGE,THE INTERVAL WILL INCLUDE TIME MJD1+FSC1
!             GOING FORWARD/BACKWARD IN THE DIRECTION OF MSIGN
!             UP TO/BACK MJDR+FSECR.
!             BUFXTR FILLS COMMON BLOCK DNUTAT WITH 12HR
!             INFORMATION THE SAME WAY BUFEAR FILLS CNUTAT.
!             HOWEVER,AT PRESENT THIS INFORMATION IS NOT USED
!             BY DXQN THE WAY DEQN USES CNUTAT. IT MAY BE NECESSARY
!             TO USE THIS INFORMATION IN THE FUTURE.
!
!***********************************************************************
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      DIMENSION HOLD(80),AA(1)
!
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/DNUTAT/RAPXTR(1),DCPXTR(1),DNUTXR(8),SMDNUT(30)
      COMMON/DYNPTR/KDEPHM,KDEPH2,KDAHDR(3,9),KDYNAP(3,9,2),KDNEXT(3),  &
     &NXDYNP
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PRXCON/PRXCON(2,2,2)
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
!
      DATA ONE/1.D0/,TWO/2.D0/,ZERO/0.D0/
      DATA MSIGNP/0/
      DATA NSDNUT/10/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      LVENUS = .FALSE.
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJD1, FSC1 ', MJD1,FSC1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJD2, FSC2 ', MJD2,FSC2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MSIGN ', MSIGN
      LRECAL=.FALSE.
!
      IF(MSIGN.GE.0) THEN
         MJDSC1=MJD1
         FSEC1=FSC1
         MJDSC2=MJD2
         FSEC2=FSC2
         MJDR=MJDSC2
         FSECR=FSEC2
      ELSE
         MJDSC1=MJD2
         FSEC1=FSC2
         MJDSC2=MJD1
         FSEC2=FSC1
         MJDR=MJDSC1
         FSECR=FSEC1
      ENDIF
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJDSC1, FSEC1 ', MJDSC1,FSEC1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJDSC2, FSEC2 ', MJDSC2,FSEC2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJDR, FSECR ', MJDR,FSECR
   20 CONTINUE
!
      INIT1=(FSEC1+(MJDSC1-FSC1EN))/DTINPD+1
      INIT4=(FSEC2+(MJDSC2-FSC1EN))/DTINPD+2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSC1EN, DTINPD ', FSC1EN, DTINPD
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: INIT1, INIT4 ', INIT1, INIT4
!CC      WRITE(6,*) 'BUFXTR: INIT1, INIT4 ', INIT1, INIT4
!
      INIT1P=(FSDINP(1)-FSC1EN)/DTINPD+1
      INIT4P=(FSDINP(4)-FSC1EN)/DTINPD+1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSDINP(1), FSDINP(4) ',FSDINP(1),
!CC  1   FSDINP(4)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: INIT1P, INIT4P ', INIT1P, INIT4P
!
      INDX1=(FSEC1+(MJDSC1-FSC1EN))/DTENPD+1
      INDX2=(FSEC2+(MJDSC2-FSC1EN))/DTENPD+1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: DTENPD, FSC1EN ', DTENPD, FSC1EN
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: INDX1, INDX2 ', INDX1, INDX2
!
      INDX1P=(FSCENP(1)-FSC1EN)/DTENPD+1
      INDX2P=(FSCENP(2)-FSC1EN)/DTENPD+1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSCENP(1), FSCENP(2) ', FSCENP(1),
!CC  1  FSCENP(2)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: INDX1P, INDX2P ', INDX1P, INDX2P
!
      ITEST1=(MSIGN-MSIGNP)**2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MSIGN, MSIGNP, ITEST1 ', MSIGN,
!CC  1   MSIGNP,ITEST1
      ITEST2=(INIT1-INIT1P)**2+(INIT4-INIT4P)**2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: ITEST2, INIT1, INIT1P,',
!CC  1  ' INIT4, INIT4P ',ITEST2, INIT1, INIT1P, INIT4, INIT4P
      ITEST3=(INDX1-INDX1P)**2+(INDX2-INDX2P)**2
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: ITEST3, INDX1, INDX1P,',
!CC  1 ' INDX2, INDX2P ',ITEST3, INDX1, INDX1P, INDX2, INDX2P
      ITEST=ITEST1+ITEST2+ITEST3
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: ITEST ', ITEST
!
      IF(ITEST.EQ.0) RETURN
      XSTART=DBLE(MJD1)+FSC1
      IF(CMARS.GT.1.9D0.AND.CMARS.LT.2.1D0) THEN
        CALL MCRCON(XSTART)
      ENDIF
      IF(ITEST3.LE.0) GO TO 100
      MENPD=INDX2-INDX1+1
      MENPD=MIN(MENPD,2)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MENPD ', MENPD
!
      IF(MSIGN.GE.0) THEN
         INDX2=INDX1+MENPD-1
      ELSE
         INDX1=INDX2-(MENPD-1)
      ENDIF
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MSIGN, INDX1, INDX2 ',
!CC  1                              MSIGN, INDX1, INDX2
!
      FSCENP(1)=FSC1EN+(INDX1-1)*DTENPD
      FSCENP(2)=FSC1EN+(INDX2-1)*DTENPD
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSC1EN, DTENPD ',FSC1EN, DTENPD
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSCENP(1), FSCENP(2) ', FSCENP(1),
!CC  1     FSCENP(2)
!
  100 IF(ITEST1.EQ.0.AND.ITEST2.EQ.0) GO TO 400
      MINEP=INIT4-INIT1+1
      MINEP=MIN(MINEP,4)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: BELOW 100 MINEP ', MINEP
!
      IF(MSIGN.GE.0) THEN
         INIT4=INIT1+(MINEP-1)
      ELSE
         INIT1=INIT4-(MINEP-1)
      ENDIF
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MSIGN, INIT1, INIT4 ',
!CC  1                              MSIGN, INIT1, INIT4
!
      NB1=MAX(0,INIT1P-INIT1)
      NB2=MAX(0,INIT4-INIT4P)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: NB1, NB2 ', NB1, NB2
      IFGN=MIN(1+NB1,MINEP+1)
      ILGN=MAX(MINEP-NB2,0)
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: IFGN, ILGN ', IFGN, ILGN
      IFGN1=IFGN-1
      NGOOD=-1
!
      IF(IFGN.LE.ILGN) THEN
!        TRANSFER GOOD INFORMATION IN DNUTAT
         NB11=MAX(0,INIT1-INIT1P)
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: NB11 ', NB11
         IFGO=1+NB11
         IFGN1=IFGN-1
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: IFGO, IFGN1 ', IFGO, IFGN1
         NGOOD=ILGN-IFGN1
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: NGOOD ', NGOOD
         NSPOT2=(IFGO-1)*NSDNUT
         NTRANS=NGOOD*NSDNUT
         NSPOT1=IFGN1*NSDNUT
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: NSDNUT, NTRANS  ', NSDNUT, NTRANS
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: NSPOT1, NSPOT2 ', NSPOT1, NSPOT2
         DO 150 I=1,NTRANS
  150       HOLD(I)=RAPXTR(I+NSPOT2)
         DO 200 I=1,NTRANS
  200       RAPXTR(I+NSPOT1)=HOLD(I)
      ENDIF
!
!   GET NEW INTERP TIMES
!
      DO 380 I=1,MINEP
  380 FSDINP(I)=FSC1EN+(INIT1+I-2)*DTINPD
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: BELOW 380 MINEP ', MINEP
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: FSDINP ', (FSDINP(KKJ), KKJ=1,MINEP)
      NLEFT=4-MINEP
      IF(NLEFT.GT.0) THEN
         DO 385 I=1,NLEFT
  385       FSDINP(I+MINEP)=FSDINP(I)
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: BELOW 380 NLEFT ', NLEFT
!CC      IF(LVENUS)WRITE(6,*) 'BUFXTR: FSDINP ',
!CC  1           (FSDINP(MINEP+KKJ), KKJ=1,NLEFT)
      ENDIF
      IF(MSIGN.GE.0) THEN
         MJDR=FSDINP(MINEP)
         FSECR=FSDINP(MINEP)-MJDR
         TQ1=MJDR+FSECR
         TQ2=MJD2+FSC2
         IF(TQ1.LT.TQ2) LRECAL=.TRUE.
      ELSE
         MJDR=FSDINP(1)
         FSECR=FSDINP(1)-MJDR
         TQ1=MJDR+FSECR
         TQ2=MJD2+FSC2
         IF(TQ1.GT.TQ2) LRECAL=.TRUE.
      ENDIF
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: MJDR, FSECR ',MJDR, FSECR
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: TQ1, TQ2, LRECAL ', TQ1, TQ2, LRECAL
!
  400 CONTINUE
      MSIGNP=MSIGN
!
!   NOW COMPUTE QUANTITIES NOT AVAILABLE FROM LAST CALL
!
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: CALL PNCXN OR NPNCXN '
      LFLAG=.FALSE.
      IF(NPVAL(IXXTRO).GT.0) THEN
      LFLAG=.FALSE.
      IF(NGLOBL.GT.1)LFLAG=.TRUE.
         IPT2=IPVAL(IXXTRO)
      ENDIF
      IDIM1=NXALLC*2+7
      IF(NEPHEM.GE.200) THEN
       IF(ICBDGM.LE.11) THEN
         CALL NPNCXN(MINEP,LFLAG,.FALSE.,IDIM1)
        ELSE
         ICB=ICBDGM-11
         CALL NPNCXX(MINEP,LFLAG,.FALSE.,IDIM1,ICB)
       ENDIF
      ELSE
         CALL PNCXN(MINEP,LFLAG,.FALSE.,AA(KPRMV-1+IPT2),AA(KPLNDX),    &
     &   AA(KPLANC),IDIM1 )
      ENDIF
!
      IERCD1=(INDX1-1)/NNPDPR+1
      IERCD2=IERCD1
      JNRCD=1+MOD((INDX1-1),NNPDPR)
      ICHK=JNRCD+MENPD-1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: NNPDPR, INDX1, IERCD1 ',
!CC  1                    NNPDPR, INDX1, IERCD1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: JNRCD, ICHK ', JNRCD, ICHK
      IF(ICHK.GT.NNPDPR) IERCD2=IERCD1+1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: IERCD2 ', IERCD2
!***** DEBUG *****
!CC   IF(LVENUS)WRITE(6,12345) KDEPHM
12345 FORMAT(' **BUFXTR**  KDEPHM=',I12)
!***** END DEBUG *
!
      CALL FILEPH(IERCD1,IERCD2,AA(KDEPHM))
!
      IF(ITEST1.EQ.0.AND.ITEST2.EQ.0) RETURN
      ILGN1=ILGN+1
      IF=0
      IF(IFGN1.LT.1) GO TO 550
      IS=1
      IF=IFGN1
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: BEFORE DO 500  IS, IF ', IS, IF
  450 DO 500 I=IS,IF
         N=(I-1)*NSDNUT+1
         COSRA=COS(RAPXTR(N))
         SINRA=SIN(RAPXTR(N))
         COSDC=COS(DCPXTR(N))
         SINDC=SIN(DCPXTR(N))
         DNUTXR(N)=SINRA
         DNUTXR(N+1)=COSRA
         DNUTXR(N+2)=SINDC
         DNUTXR(N+3)=COSDC
         DNUTXR(N+4)=SINRA*SINDC
         DNUTXR(N+5)=SINRA*COSDC
         DNUTXR(N+6)=COSRA*COSDC
         DNUTXR(N+7)=COSRA*SINDC
  500 END DO
!
  550 IF(IF.GE.MINEP) RETURN
      IF(ILGN1.GT.MINEP) RETURN
      IS=ILGN1
      IF=MINEP
!CC   IF(LVENUS)WRITE(6,*) 'BUFXTR: BELOW 550 IS, IF ', IS, IF
      GO TO 450
      END
