!$COEFF
      SUBROUTINE COEFF(MJDSEC,FSEC1,FSECNM,AA)
!********1*********2*********3*********4*********5*********6*********7**
! COEFF            88/11/09            8901.0    PGMR - A. MARSHALL
!
!  FUNCTION:  FIND CHEBYCHEV COEFFICIENTS FOR THIS BLOCK OF
!             MEASUREMENTS.  CALLED ONCE PER BLOCK FROM
!             EXEC2E.
!
!  I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    INTEGER SECONDS SINCE GEODYN REFERENCE TIME
!   FSEC1    I    S    FRACTIONAL REMAINING SECONDS UNTIL FIRST OBS
!   FSECNM   I    S    FRACTIONAL REMAINING SECONDS UNTIL LAST  OBS
!                      IN MEASUREMENT BLOCK
!   AA      I/O   A    REAL DYNAMIC ARRAY
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CHCOEF/ COEFM(3,15),COEFJ(3,15),COEFSA(3,15),COEFS(3,15),  &
     &               COEFEM(3,15),COEFMO(3,15),COEF(3,15)
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CREFMT/REFMT(9)
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EPHM/FSECXY(1),XP(261),YP(261),A1UT(261),EP(261),EC(261),  &
     &            FSCFLX(1),FLUXS(36),AVGFLX(36),FLUXM(288),FSECEP(1),  &
     &            EPHP(816),EPHN(96),ELIB(120),BUFT(2700),FSECNP(4)
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/INVRSL/LSYMSW,LMATP,NXINVR
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LEPHM2/LXEPHM
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      COMMON/XLITSD/DELULT,DDLULT,UNVLTU(3),DELDLT,DDLDLT,UNVLTD(3),    &
     &              GRELLT,TOLLTX,GRLFCT,FCTJUP,FCTSAT
!
      DIMENSION FNSEC(4),IGRPP1(4),IGRPP2(4),ITEST(4)
      DIMENSION COFF(4,3,15),SCRTCH(3,15),AA(1)
      DIMENSION IMAP(4),IMAP2(4),IMAP3(4)
      DATA ZERO/0.D0/,ONE/1.D0/,TWO/2.D0/
      DATA FNSEC/2764800.D0,1382400.D0,691200.D0,345600.D0/
      DATA ITEST/1,2,4,8/
      DATA IMAP/4,5,6,11/,IMAP2/2,3,4,8/,IMAP3/7,2,1,3/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      IDM=15
      IF(LXEPHM) IDM=25
!
! COMPUTE EARLIEST AND LATEST POSSIBLE TIME TAGS NEEDED FOR PLANET POS
! ROUNDTRIP LIGHT TIME FROM THE SUN TO PLUTO IS @ 4.E4 SECONDS
      F1    = FSEC1-4.D4
      FIRST = MJDSEC+FSEC1-4.D4
      FLAST = MJDSEC+FSECNM
!
! LOOP THROUGH EACH PLANETARY GROUP
      DO 2500 I=1,4
      FEND = FSECNP(I) + FNSEC(I)
      L2PRD= .FALSE.
! COMPARE TIMES TO PREVIOUS COEFFICIENT TIME TAGS
      IF(NPVAL0(IXXTRO).GT.0.AND.NGLOBL.GT.1) GOTO 2600
      IF(FSECNP(I) .LE. FIRST .AND. FEND .GE. FLAST) GOTO 2500
 2600 CONTINUE
!
! UPDATE COEFFICIENTS
      CALL BUFXTR(MJDSEC,F1,MJDSEC,FSECNM,+1,MJDR,FSECR,LRECAL,AA)
      IF(LRECAL) THEN
         WRITE(6,*) 'INTERVAL TOO LARGE FOR BUFXTR (CALLED FROM COEFF)'
         STOP
      ENDIF
! COMPUTE PERIOD POINTERS FOR FIRST & FLAST
      TTEST1=FIRST-FSECEP(1)
      ITOT1=0
      IF(TTEST1.LE.FNSEC(1)) GO TO 10
      ITOT1=NTOT
      TTEST1=TTEST1-FNSEC(1)
   10 CONTINUE
      TTEST2=FLAST-FSECEP(1)
      ITOT2=0
      IF(TTEST2.LE.FNSEC(1)) GO TO 20
      ITOT2=NTOT
      TTEST2=TTEST2-FNSEC(1)
      IF (I .EQ. 1) L2PRD=.TRUE.
   20 CONTINUE
      IGRPP1(I)=TTEST1/FNSEC(I)
      IF(IGRPP1(I).GE.ITEST(I)) IGRPP1(I)=ITEST(I)-1
      IGRPP2(I)=TTEST2/FNSEC(I)
      IF(IGRPP2(I).GE.ITEST(I)) IGRPP2(I)=ITEST(I)-1
!**************DEBUG***********************************
!     WRITE(6,*)' FIRST,FLAST ',FIRST,FLAST
!     WRITE(6,*)' FNSEC,FSECEP ',FNSEC(1),FSECEP(1)
!     WRITE(6,*)' TTEST ',TTEST1,TTEST2
!     WRITE(6,*)' ITEST,IGRPP ',ITEST(I),IGRPP1(I),IGRPP2(I)
!     WRITE(6,*)' ITOT1,ITOT2,NTOT ',ITOT1,ITOT2,NTOT
!*******************************************************
!
! IF FIRST & LAST POINTERS ARE IN SAME PERIOD GROUP, PULL COEFFICIENTS
! OFF KPLAN ARRAY (JPL)
      IF (IGRPP1(I) .NE. IGRPP2(I) .OR. L2PRD) GOTO 1000
!
! STORE TIME TAG FOR THIS PERIOD
      FSECNP(I) = FSECEP(1) + IGRPP1(I)*FNSEC(I)
!
! COMPUTE CENTRAL BODY COEFFICIENTS
      IF (ICBDGM .GT. 11) GOTO 175
      IF (ICHBOG(2,14) .NE. I) GOTO 175
      N=IPLNIN(ICBDGM)
      IB=ICHBOG(1,14)
      IBPT1=KPLAN(N)+3*IGRPP1(I)*IB+ITOT1
!
        DO 125 JJ=1,3
        DO 125 KK=1,IB
        J=JJ-1
        K=KK-1
        IEPT=IBPT1+K+J*IB
        SCRTCH(JJ,KK)=EPHP(IEPT)
  125   CONTINUE
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 150 J=1,IB
      DO 150 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEF(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+        &
     &          REFMT(IPT3)*SCRTCH(3,J)
  150 CONTINUE
!
  175 CONTINUE
!   COMPUTE GROUP 1 POINTERS (MARS,JUPITER,SATURN,SUN)
!     IF(I .NE. 1) GOTO 650
      DO 250 M=1,4
      IF(ICHBOG(2,IMAP(M)).NE.I) GO TO 250
      IB=ICHBOG(1,IMAP(M))
      IBPT1=KPLAN(IMAP2(M))+3*IGRPP1(I)*IB+ITOT1
!
        DO 200 JJ=1,3
        DO 200 KK=1,IB
        J=JJ-1
        K=KK-1
        IEPT=IBPT1+K+J*IB
        COFF(M,JJ,KK)=EPHP(IEPT)
  200   CONTINUE
  250 END DO
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      IF(ICHBOG(2,4).NE.I) GO TO 310
      DO 300 J=1,IORM
      DO 300 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFM(K,J)=REFMT(IPT1)*COFF(1,1,J)+REFMT(IPT2)*COFF(1,2,J)+       &
     &           REFMT(IPT3)*COFF(1,3,J)
  300 CONTINUE
  310 CONTINUE
!
      IF(ICHBOG(2,5).NE.I) GO TO 410
      DO 400 J=1,IORJ
      DO 400 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFJ(K,J)=REFMT(IPT1)*COFF(2,1,J)+REFMT(IPT2)*COFF(2,2,J)+       &
     &           REFMT(IPT3)*COFF(2,3,J)
  400 CONTINUE
  410 CONTINUE
!
      IF(ICHBOG(2,6).NE.I) GO TO 510
      DO 500 J=1,IORSA
      DO 500 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFSA(K,J)=REFMT(IPT1)*COFF(3,1,J)+REFMT(IPT2)*COFF(3,2,J)+      &
     &            REFMT(IPT3)*COFF(3,3,J)
  500 CONTINUE
  510 CONTINUE
!
      IF(ICHBOG(2,11).NE.I) GO TO 610
      DO 600 J=1,IORSUN
      DO 600 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFS(K,J)=REFMT(IPT1)*COFF(4,1,J)+REFMT(IPT2)*COFF(4,2,J)+       &
     &           REFMT(IPT3)*COFF(4,3,J)
  600 CONTINUE
  610 CONTINUE
!
  650 CONTINUE
! COMPUTE GROUP 2 (EM) POINTERS
      IF(ICHBOG(2,3).NE.I) GO TO 850
      IB=ICHBOG(1,3)
      IBPT1=KPLAN(9)+3*IGRPP1(I)*IB+ITOT1
      DO 700 JJ=1,3
      DO 700 KK=1,IB
        J=JJ-1
        K=KK-1
        IEPT=IBPT1+K+J*IB
        SCRTCH(JJ,KK)=EPHP(IEPT)
  700 CONTINUE
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 800 J=1,IOREM
      DO 800 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFEM(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+      &
     &            REFMT(IPT3)*SCRTCH(3,J)
  800 CONTINUE
!
  850 CONTINUE
! COMPUTE GROUP 4 (MO) POINTERS
      IF(ICHBOG(2,10).NE.I) GO TO 2500
      IB=ICHBOG(1,10)
      IBPT1=KPLAN(11)+3*IGRPP1(I)*IB+ITOT1
      DO 900 JJ=1,3
      DO 900 KK=1,IB
        J=JJ-1
        K=KK-1
        IEPT=IBPT1+K+J*IB
        SCRTCH(JJ,KK)=EPHP(IEPT)
  900 CONTINUE
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 950 J=1,IORMO
      DO 950 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFMO(K,J)=(REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+     &
     &             REFMT(IPT3)*SCRTCH(3,J))*EMFACT
  950 CONTINUE
      GOTO 2500
!
 1000 CONTINUE
!
! CHECK PERIOD DIFFERENCES FOR ERROR
      IGRPDF = IGRPP2(I)-IGRPP1(I)
      IF(IGRPDF .EQ. 1 .OR. IGRPDF .EQ. -(ITEST(I)-1)) GOTO 1025
!     WRITE(6,*)' IGRPP ',IGRPP2(I),IGRPP1(I),I
      WRITE(6,*)'PERIOD POINTERS DIFFER BY MORE THAN ONE IN COEFF'
      STOP
 1025 CONTINUE
!
! COMPUTE NEW SET OF COEFFIICIENTS
! STORE TIME TAG FOR THIS PERIOD
      FSECNP(I) = FSECEP(1) + IGRPP1(I)*FNSEC(I) + FNSEC(I)/TWO
!
! COMPUTE CENTRAL BODY COEFFICIENTS
      IF (ICBDGM .GT. 11) GOTO 1075
      IF (IGRP .NE. I) GOTO 1075
      N=IPLNIN(ICBDGM)
      IB=ICHBOG(1,14)
      IBPT1=KPLAN(N)+3*IGRPP1(I)*IB+ITOT1
      IBPT2=KPLAN(N)+3*IGRPP2(I)*IB+ITOT2
      CALL CHCOMP(IBPT1,IBPT2,SCRTCH,IB,I,AA(KCHB1),AA(KCHB2),          &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),6,IDM)
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 1050 J=1,IORCB
      DO 1050 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEF(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+        &
     &          REFMT(IPT3)*SCRTCH(3,J)
 1050 CONTINUE
!
 1075 CONTINUE
!   COMPUTE GROUP 1 POINTERS (MARS,JUPITER,SATURN,SUN)
!      IF(I .NE. 1) GOTO 1650
      DO 1250 M=1,4
      IF(ICHBOG(2,IMAP(M)).NE.I) GO TO 1250
      IB=ICHBOG(1,IMAP(M))
      IBPT1=KPLAN(IMAP2(M))+3*IGRPP1(I)*IB+ITOT1
      IBPT2=KPLAN(IMAP2(M))+3*IGRPP2(I)*IB+ITOT2
      CALL CHCOMP(IBPT1,IBPT2,SCRTCH,IB,I,AA(KCHB1),AA(KCHB2),          &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),IMAP3(M),IDM)
      DO 1200 J=1,3
      DO 1200 K=1,IB
      COFF(M,J,K)=SCRTCH(J,K)
 1200 CONTINUE
 1250 END DO
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      IF(ICHBOG(2,4).NE.I) GO TO 1310
      DO 1300 J=1,IORM
      DO 1300 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFM(K,J)=REFMT(IPT1)*COFF(1,1,J)+REFMT(IPT2)*COFF(1,2,J)+       &
     &           REFMT(IPT3)*COFF(1,3,J)
 1300 CONTINUE
 1310 CONTINUE
!
      IF(ICHBOG(2,5).NE.I) GO TO 1410
      DO 1400 J=1,IORJ
      DO 1400 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFJ(K,J)=REFMT(IPT1)*COFF(2,1,J)+REFMT(IPT2)*COFF(2,2,J)+       &
     &           REFMT(IPT3)*COFF(2,3,J)
 1400 CONTINUE
 1410 CONTINUE
!
      IF(ICHBOG(2,6).NE.I) GO TO 1510
      DO 1500 J=1,IORSA
      DO 1500 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFSA(K,J)=REFMT(IPT1)*COFF(3,1,J)+REFMT(IPT2)*COFF(3,2,J)+      &
     &            REFMT(IPT3)*COFF(3,3,J)
 1500 CONTINUE
 1510 CONTINUE
!
      IF(ICHBOG(2,11).NE.I) GO TO 1610
      DO 1600 J=1,IORSUN
      DO 1600 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFS(K,J)=REFMT(IPT1)*COFF(4,1,J)+REFMT(IPT2)*COFF(4,2,J)+       &
     &           REFMT(IPT3)*COFF(4,3,J)
 1600 CONTINUE
 1610 CONTINUE
!
 1650 CONTINUE
! COMPUTE GROUP 2 (EM) POINTERS
      IF(ICHBOG(2,3).NE.I) GO TO 1850
      IB=ICHBOG(1,3)
      IBPT1=KPLAN(9)+3*IGRPP1(I)*IB+ITOT1
      IBPT2=KPLAN(9)+3*IGRPP2(I)*IB+ITOT2
      CALL CHCOMP(IBPT1,IBPT2,SCRTCH,IB,I,AA(KCHB1),AA(KCHB2),          &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),4,IDM)
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 1800 J=1,IOREM
      DO 1800 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFEM(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+      &
     &            REFMT(IPT3)*SCRTCH(3,J)
 1800 CONTINUE
!
 1850 CONTINUE
! COMPUTE GROUP 4 (MO) POINTERS
      IF(ICHBOG(2,10).NE.I) GO TO 2500
      IB=ICHBOG(1,10)
      IBPT1=KPLAN(11)+3*IGRPP1(I)*IB+ITOT1
      IBPT2=KPLAN(11)+3*IGRPP2(I)*IB+ITOT2
      CALL CHCOMP(IBPT1,IBPT2,SCRTCH,IB,I,AA(KCHB1),AA(KCHB2),          &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),5,IDM)
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 1950 J=1,IORMO
      DO 1950 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFMO(K,J)=(REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+     &
     &             REFMT(IPT3)*SCRTCH(3,J))*EMFACT
 1950 CONTINUE
!
 2500 END DO
!
      RETURN
      END
