!$COEFFX
      SUBROUTINE COEFFX(MJDSEC,FSEC1,FSECNM,AA,II,ISUPE,BUFFER)
!********1*********2*********3*********4*********5*********6*********7**
! COEFFX           99/07/07            9909.0    PGMR - A. MARSHALL
!                                                       D. PAVLIS
!
!  FUNCTION:  FIND CHEBYCHEV COEFFICIENTS FOR THIS BLOCK OF
!             MEASUREMENTS IN CASE OF SUPPLEMENTARY PLANETARY EPHEMERIS.
!             CALLED ONCE PER BLOCK FROM EXEC2E (AND SIMGEN)
!
!  I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    INTEGER SECONDS SINCE GEODYN REFERENCE TIME
!   FSEC1    I    S    FRACTIONAL REMAINING SECONDS UNTIL FIRST OBS
!   FSECNM   I    S    FRACTIONAL REMAINING SECONDS UNTIL LAST  OBS
!                      IN MEASUREMENT BLOCK
!   AA      I/O   A    REAL DYNAMIC ARRAY
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/SAVLTC/RLTCOR
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CHCOFX/ COEFX(3,25),COEFXX(3,25,988),RLVAL(988)
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CREFMT/REFMT(9)
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EPHM/FSECXY(1),XP(261),YP(261),A1UT(261),EP(261),EC(261),  &
     &            FSCFLX(1),FLUXS(36),AVGFLX(36),FLUXM(288),FSECEP(1),  &
     &            EPHP(816),EPHN(96),ELIB(120),BUFT(2700),FSECNP(4)
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHMX/FSECSE(10,2)
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/INVRSL/LSYMSW,LMATP,NXINVR
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LEPHM2/LXEPHM
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      COMMON/XLITSD/DELULT,DDLULT,UNVLTU(3),DELDLT,DDLDLT,UNVLTD(3),    &
     &              GRELLT,TOLLTX,GRLFCT,FCTJUP,FCTSAT
!
      DIMENSION FNSEC(4),IGRPP1(4),IGRPP2(4),ITEST(4)
! 4 below is for MARS JUPITER SATURN and SUN
      DIMENSION COFF(10,3,25),SCRTCH(3,25),AA(1),II(1)
      DIMENSION IMAP(4),IMAP2(4),IMAP3(4)
      DIMENSION ISUPE(ICBODY,5),BUFFER(ICBODY,MAXDEG,2)
      DATA DAYSEC/86400.D0/
      DATA ZERO/0.D0/,ONE/1.D0/,TWO/2.D0/
      DATA FNSEC/2764800.D0,1382400.D0,691200.D0,345600.D0/
      DATA ITEST/1,2,4,8/
      DATA IMAP/4,5,6,11/,IMAP2/2,3,4,8/,IMAP3/7,2,1,3/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!
! COMPUTE EARLIEST AND LATEST POSSIBLE TIME TAGS NEEDED FOR PLANET POS
! ROUNDTRIP LIGHT TIME FROM THE SUN TO PLUTO IS @ 4.E4 SECONDS
      F1    = FSEC1
      F2    = FSECNM
      FIRST = MJDSEC+FSEC1-RLTCOR
      FLAST = MJDSEC+FSECNM-RLTCOR
!
! LOOP THROUGH EACH CELESTIAL BODY IN THE SUPPLEMENTARY PLANETARY EPHEME
      DO 2500 I=1,ICBODY
! UPDATE COEFFICIENTS
! FOR SUPPLEMENTARY EPHEMERIS
      CALL BUFSUP(AA,MJDSEC,F1,MJDSEC,F2,II(KISUPE),BUFFER,I,1)
      ILOV=ISUPE(I,3)
      FEND = FSECSE(I,1) + (DBLE(ILOV)*DAYSEC)
! L2PRD IS TRUE IF THE BLOCK SPANS MORE THAN TWO BUFFERS
      L2PRD= .FALSE.
! COMPARE TIMES TO PREVIOUS COEFFICIENT TIME TAGS
!     IF(NPVAL0(IXXTRO).GT.0.AND.NGLOBL.GT.1) GOTO 2600
      IF(FSECSE(I,1) .GT. FLAST .OR. FIRST .GT. FEND) GOTO 2500
!2600  CONTINUE
!
! CHECK IF THE BLOCK SPANS TWO BUFFERS
      IF(FIRST.LT.FEND.AND.FLAST.GT.FEND) L2PRD=.TRUE.
!**************DEBUG***********************************
!     MJD1=FIRST
!     MJD2=FLAST
!     MJD3=FSECSE(I,1)
!     MJD4=FEND
!     CALL MJDYMD(MJD1,IYMD1,IHMS1,4)
!     CALL MJDYMD(MJD2,IYMD2,IHMS2,4)
!     CALL MJDYMD(MJD3,IYMD3,IHMS3,4)
!     CALL MJDYMD(MJD4,IYMD4,IHMS4,4)
!     write(6,*)' 1stOBS ',IYMD1,IHMS1
!     write(6,*)' LstOBS ',IYMD2,IHMS2
!     write(6,*)' BEGEPH ',IYMD3,IHMS3
!     write(6,*)' ENDEPH ',IYMD4,IHMS4
!*******************************************************
!
! ENTIRE BLOCK LIES WITHIN ONE BUFFER PULL COEFFICIENTS
! OFF AA(KEPHMS)
      IF (L2PRD) GOTO 1000
!
! IF CENTRAL BODY IS NOT FEATURED IN THE SUPPLEMENTARY PLANETARY EPHEMER
! SKIP THE CODE BELOW
      IF(ICBDGM.LT.12) GOTO 175
            IF(ICBDGM.EQ.I+11) THEN
! COMPUTE CENTRAL BODY COEFFICIENTS
! FIND POINTERS TO THE SUPPL. EPHEMERIS BUFFER
!     CENTRAL BODY
      ICBD=ICBDGM-11
      IB=ISUPE(ICBD,2)/3
!
        DO 125 JJ=1,3
        DO 125 KK=1,IB
        J=JJ-1
        K=KK-1
        IPT=KK+J*IB
        SCRTCH(JJ,KK)=BUFFER(ICBD,IPT,1)
  125   CONTINUE
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 150 J=1,IB
      DO 150 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFX(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+       &
     &          REFMT(IPT3)*SCRTCH(3,J)
  150 CONTINUE
!     write(6,*)' dbg COEFFX 1  ',COEFX(1,1)
!
            ENDIF
  175 CONTINUE
      IF(I+11.EQ.ICBDGM) GOTO 310
!   COMPUTE OTHER CELESTIAL BODIES FROM SUPPLEMENTARY EPHEMERIS
!
      IB=ISUPE(I,2)/3
        DO 200 JJ=1,3
        DO 200 KK=1,IB
        J=JJ-1
        K=KK-1
        COFF(I,JJ,KK)=BUFFER(I,K+JJ,1)
  200   CONTINUE
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 300 J=1,IORSCB(I)
      DO 300 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFXX(K,J,I)=REFMT(IPT1)*COFF(I,1,J)+REFMT(IPT2)*COFF(I,2,J)+    &
     &           REFMT(IPT3)*COFF(I,3,J)
  300 CONTINUE
  310 CONTINUE
!
      GOTO 2500
!
 1000 CONTINUE
!
!
! COMPUTE NEW SET OF COEFFIICIENTS
! COMPUTE CENTRAL BODY COEFFICIENTS
      IF(ICBDGM.LT.12) GOTO 1075
      IB=ISUPE(I,2)/3
      VS=2.D0/RLVAL(ICBDGM-11)
      IBD=IB*3
      ICB=7+ICBODY
      CALL CHCOMX(I,SCRTCH,BUFFER,IB,IBD,AA(KCHB1),AA(KCHB2),           &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),VS,6,ICB)
!
! RESET THE BEG AND END TIME OF THE BUFFER TO REFLECT THE NEW ONE
      FSECSE(ICBDGM-11,1)=(FSECSE(ICBDGM-11,1)+FSECSE(ICBDGM-11,2))/2.D0
      FSECSE(ICBDGM-11,2)=FSECSE(ICBDGM-11,1)+RLVAL(ICBDGM-11)
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 1050 J=1,IORCB
      DO 1050 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFX(K,J)=REFMT(IPT1)*SCRTCH(1,J)+REFMT(IPT2)*SCRTCH(2,J)+       &
     &          REFMT(IPT3)*SCRTCH(3,J)
 1050 CONTINUE
!     write(6,*)' dbg COEFFX 2  ',COEFX(1,1)
!
 1075 CONTINUE
!
      IF(I+11.EQ.ICBDGM) GOTO 1310
!   COMPUTE OTHER CELESTIAL BODIES FROM SUPPLEMENTARY EPHEMERIS
!
      IB=ISUPE(I,2)/3
      IBD=IB*3
      IPT=I+7
      VS=2.D0/RLVAL(I)
      CALL CHCOMX(I,SCRTCH,BUFFER,IB,IBD,AA(KCHB1),AA(KCHB2),           &
     &            AA(KCHBV1),AA(KCHBV2),AA(KCHEB),VS,IPT,ICB)
      DO 1200 J=1,3
      DO 1200 K=1,IB
      COFF(I,J,K)=SCRTCH(J,K)
 1200 CONTINUE
 1250 CONTINUE
!
! ROTATE & STORE COEFFICIENTS IN APPROPRIATE ARRAYS
      DO 1300 J=1,IORSCB(I)
      DO 1300 K=1,3
      IPT1=3*K-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      COEFXX(K,J,I)=REFMT(IPT1)*COFF(I,1,J)+REFMT(IPT2)*COFF(I,2,J)+    &
     &           REFMT(IPT3)*COFF(I,3,J)
 1300 CONTINUE
 1310 CONTINUE
!
 2500 END DO
!
      RETURN
      END
