!$CONDNO
      SUBROUTINE CONDNO(SUM1,NDIM,ND,CONDNM,SAVE)
!********1*********2*********3*********4*********5*********6*********7**
! CONDNO           00/00/00            8804.0    PGMR - BILL EDDY/
!                                                       WEI XIA
!
! FUNCTION:  COMPUTES CONDITION NUMBERS. CODITION NUMBERS DEFINED
!            AS DIAGONAL ELEMENTS OF ATWA TIMES DIAGONAL ELEMENTS
!            OF ATWA INVERSE.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   SUM1     I    A    ATWA MATRIX(NORMAL MATRIX)
!   NDIM     I    S    DIMENSION OF THE SUM1 ARRAY
!   ND       I    S    DIMENSION OF ARC PART OF SUM1 ARRAY
!   CONDNM  I/O   A    IF SAVE=.TRUE., DIAGONAL ELEMENTS FROM SUM1 ARRAY
!                      ARE LOADED INTO CONDNM ARRAY
!                      IF SAVE=.FALSE., CONDNM CONTAINS THE DIAGONAL
!                      ELEMENTS FROM THE PREVIOUS CALL ON INPUT AND
!                      CONTAINS THE COMPUTED CONDITION NUMBERS ON OUTPUT
!   SAVE     I    L    LOGICAL FLAG USED TO CONTROL SAVING OF DIAGONAL
!                      ELEMENTS OR CALCULATION OF CONDITION NUMBERS
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      LOGICAL SAVE
!
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
!
      DIMENSION SUM1(1),CONDNM(1)
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      IF(.NOT.SAVE) GOTO 1000
! SAVE DIAGONAL ELEMENTS OF SUM1 ARRAY
      IF(NAMBB.GT.0) THEN
!        NUM=NPVAL0(IXARC)-NPVAL0(IXBISA)
        NUM=IPVAL0(IXBISA)-1
        IST=NAMBB*(NDIM-NAMBB+1)+1
        IL=NDIM-NAMBB
        DO 150 I=1,NUM
        CONDNM(I)=SUM1(IST)
        IST=IST+IL
        IL=IL-1
  150   CONTINUE
        IPT=IPVAL0(IXBISA)-1
        IST2=1
        DO 160 I=1,NAMBB
        CONDNM(I+IPT)=SUM1(IST2)
        IST2=IST2+(NDIM-NAMBB+1)
  160   CONTINUE
!        NUM=NPVAL0(IXBISA)-NAMBB
        NUM=NPVAL0(IXARC)-(IPVAL0(IXBISA)-1)-NAMBB
        IF(NUM.GT.0) THEN
          IPT=IPVAL0(IXBISA)-1+NAMBB
           DO 170 I=1,NUM
          CONDNM(I+IPT)=SUM1(IST)
          IST=IST+IL
          IL=IL-1
  170     CONTINUE
        ENDIF
      ELSE
        IST=0
        DO 200 I=1,ND
        CONDNM(I)=SUM1(IST+I)
        IST=IST+NDIM-I
  200   CONTINUE
      ENDIF
      RETURN
 1000 CONTINUE
! CALCULATE CONDITION NUMBERS
      IF(NAMBB.GT.0) THEN
!        NUM=NPVAL0(IXARC)-NPVAL0(IXBISA)
        NUM=IPVAL0(IXBISA)-1
        IST=NAMBB*(NDIM-NAMBB+1)+1
        IL=NDIM-NAMBB
        DO 1500 I=1,NUM
        CONDNM(I)=CONDNM(I)*SUM1(IST)
        IST=IST+IL
        IL=IL-1
 1500   CONTINUE
        IPT=IPVAL0(IXBISA)-1
        IST2=1
        DO 1600 I=1,NAMBB
        CONDNM(I+IPT)=CONDNM(I+IPT)*SUM1(IST2)
        IST2=IST2+(NDIM-NAMBB+1)
 1600   CONTINUE
!        NUM=NPVAL0(IXBISA)-NAMBB
        NUM=NPVAL0(IXARC)-(IPVAL0(IXBISA)-1)-NAMBB
        IF(NUM.GT.0) THEN
          IPT=IPVAL0(IXBISA)-1+NAMBB
          DO 1700 I=1,NUM
          CONDNM(I+IPT)=CONDNM(I+IPT)*SUM1(IST)
          IST=IST+IL
          IL=IL-1
 1700     CONTINUE
       ENDIF
      ELSE
        IST=0
        DO 2000 I=1,ND
        CONDNM(I)=CONDNM(I)*SUM1(IST+I)
        IST=IST+NDIM-I
 2000   CONTINUE
      ENDIF
      RETURN
      END
