!COWELL
      SUBROUTINE COWELL(LORBIT,LNDRAG,IBACK,IBACKV,                     &
     &   IORDER,IORDRV,H,HV,POSNEG,NOSTEP,NOCORR,CTOL,NSAT,             &
     &   MJDSEC,FSEC,MJDSV,FSECV,                                       &
     &   MJDS2,FSEC2,N3,NEQN,NEQN3,NH,NHV,NSTEPS,NSTEPV,                &
     &   CPP,CPV,CCP,CCV,CIP,CIV,CCPV,CCVV,VMATRX,RSQ,                  &
     &   XP,X,SUMX,XDDOT,PX,PX3,SUMPX,PXDDOT,PXDDT3,NVSTEP,XDDTMC,      &
     &   DNLT,TOPXAT,LTPXAT,AA,II,LL,ISATID,UTDT,NRAT1,LATOT,XDDTNC,    &
     &   IDXDDN,SUMXNC,IBCKNC,IDSMXN,LSAVEA,XDDOTH,PXDDTH,TOPXTH,LTPXTH,&
     &   NSTPSV,ISTPSV,XPNC,XNC,CPPNC,XLSASS,XDDTAC,LFHIRT,LSURFF,      &
     &   PXDDAC,NEQNA,IPTFBS,NPRMAC,DYNTIM,NPERDY,EXACCT,EXACIN,EXACOB, &
     &   LACCELS,ACCTIM,ACCPER,NPERAC,L4MRST,NXSTAT,TXSTAT,DELXST,      &
     &   SUMRNC,IPXST,PXR,SUMRNP,DSROT,SUMRC,XDDRC,TMOS0,TMOS,TMOSP,    &
     &   SUMPOS, SUMXOS,                                                &
     &   XDDTOS,PDDTOS,KNSTEPS,NEQNI,ISEGM,T1SEG,T2SEG,SUMPNS  )
!********1*********2*********3*********4*********5*********6*********7**
!COWELL           82/06/17            8206.0    PGMR - TOM MARTIN
!
! FUNCTION:  NUMERICAL INTEGRATION OF SPACECRAFT ORBIT AND
!            VARIATIONAL EQUATIONS USING COWELLS METHOD
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   LORBIT   I    S    LOGICAL SWITCH INDICATING ORBIT-ONLY
!                      INTEGRATION WHEN .TRUE.
!   LNDRAG   I    S    LOGICAL SWITCH INDICATING THAT THE
!                      FORCING FUNCTION IS VELOCITY INDEPENDENT
!                      WHEN .TRUE.
!   IBACK    I    S    COUNTER INDICATING HOW MANY EXTRA BACK
!                      VALUES ARE STORED FOR SUMS AND
!                      ACCELERATIONS
!   IBACKV   I    S    SAME AS IBACK EXCEPT APPLIES TO
!                      VARIATIONAL EQUATIONS
!   IORDER   I    S    ORDER OF COWELL INTEGRATION FOR ORBIT
!   IORDRV   I    S    ORDER OF COWELL INTEGRATION FOR VAR. EQ.
!   H        I    S    INTEGRATION STEP SIZE IN SECONDS FOR ORBIT
!   HV       I    S    INTEGRATION STEP SIZE IN SECONDS FOR VAR. EQ.
!   POSNEG   I    S    PLUS OR MINUS ONE;INDICATING THE DIRECTION
!   NOSTEP   I    S    ACCUMULATED TOTAL OF ORBIT INTEGRATION
!                      OF INTEGRATION:PLUS ONE-FORWARD IN TIME
!                      MINUS ONE-BACKWARD IN TIME
!                      STEPS
!   NOCORR   I    S    ACCUMULATED TOTAL OF ORBIT CORRECTION
!                      STEPS
!   CTOL     I    S    INTEGRATION LOCAL ERROR TOLERANCE GOVERNING
!                      ORBIT CORRECTOR LOOP
!   NSAT     I    S    NUMBER OF SATELLITES OF LIKE CHARACTERISTICS
!                      TO BE SIMULATANEOUSLY INTEGRATED
!   MJDSEC   I    S    CURRENT DATE AND INTEGRAL SECONDS OF TIME O
!                      ORBIT INTEGRATION
!   FSEC     I    S    CURRENT FRACTIONAL SECONDS OF ORBIT TIME
!   MJDSV    I    S    CURRENT DATE AND INTEGRAL SECONDS OF
!                      VAR. EQ. TIME
!   FSECV    I    S    CURRENT FRACTIONAL SECONDS OF VAR. EQ. TIME
!   MJDS2    I    S    LATEST DATE AND INTEGRAL SECONDS OF TIME
!                      FOR WHICH ORBIT INTERPOLATION WILL BE
!                      PERFORMED AFTER RETURN FROM THIS ROUTINE
!   FSEC2    I    S    FRACTIONAL SECONDS OF TIME ASSOCIATED WITH
!                      MJDS2
!   N3       I    S    NSAT*3
!   NEQN     I    S    NUMBER OF FORCE MODEL VARIATIONAL EQUATIONS
!   NEQN3    I    S    NEQN*N3
!   NH       I    S    MAXIMUM NUMBER OF ORBIT BACK VALUES PLUS ONE
!   NHV      I    S    MAXIMUM NUMBER OF VAR. EQ. BACK VALUES
!                      PLUS ONE
!   NSTEPS   I    S    NH+IORDER-2
!   NSTEPV   I    S    NHV+IORDRV-2
!   CPP      I    S    COWELL COEFFICIENTS FOR PREDICTING POSITION
!   CPV      I    S    COWELL COEFFICIENTS FOR PREDICTING VELOCITY
!   CCP      I    A    COWELL COEFFICIENTS FOR CORRECTING POSITION
!   CCV      I    A    COWELL COEFFICIENTS FOR CORRECTING VELOCITY
!   CIP      I    A    COWELL COEFFICIENTS FOR INTERPOLATING
!                      POSITION
!   CIV      I    A    COWELL COEFFICIENTS FOR INTERPOLATING
!                      VELOCITY
!   CCPV     I    A    COWELL COEFFICIENTS FOR CORRECTING
!                      POSITIONAL VAR. EQ.
!   CCVV     I    A    COWELL COEFFICIENTS FOR CORRECTING VELOCITY
!                      VAR. EQ. (WORKING ARRAY)
!   VMATRX   I    A    PARTIALS OF ACCELERATION W.R.T. EPOCH
!                      POS. AND VEL. (WORKING ARRAY)
!   RSQ      I    A    MAGNITUDE OF THE POSITION VECTOR (WORKING ARRAY)
!   XP       I    A    PREDICTED S/C POS. AND VEL.
!   X        O    A    CORRECTED SC POS. AND VEL.
!   SUMX     O    A    INTEGRATION SUMS FOR ORBIT
!   XDDOT    O    A    ORBIT ACCELERATIONS
!   PX,PX3   O    A    CORRECTED VARIATIONAL EQUATIONS
!   SUMPX    O    A    INTEGRATION SUMS FOR VAR. EQ.
!   PXDDOT   O    A    VARIATIONAL ACCELERATION
!   PXDDT3   O    A    VARIATIONAL ACCELERATION
!   NVSTEP   I    S    NUMBER OF VARIATIONAL INTEGRATION STEPS
!   XDDTMC   O    A    NON POINT MASS ORBIT ACCELERATIONS
!   DNLT     O    S    ACCUMULATED CHANGE IN NODE (SINCE EPOCH)
!                      DUE TO LENSE-THIRRING
!   TOPXAT   O    A    TOPEX ATT. BACK VALUES (BETAPRIME & ORBIT ANGLE)
!   LTPXAT   O    A    TOPEX ATT. BACK VALUES (RAMPING LOGICALS)
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   ISATID        A    SAT ID ARRAY
!   NRAT1    I    S    NRAT-1 WHERE NRAT=RATIO OF LARGE STEP SIZE TO
!                      SMALL STEP SZ (NRAT=1 => SINGLE RATE INTEGRATION)
!   LATOT    I    S    IF TRUE, THEN CALLS TO SUBROUTINE F WILL
!                      LOAD THE ENTIRE ACCELERATION (NOT JUST
!                      THE LARGE STEP ACCELERATION) INTO XDDOT
!   XDDTNC   O    A    SMALL STEP ACCELERATIONS
!   IDXDDN   I    S    NUMBER OF STEPS COVERED BY (LAST DIMENSION OF)
!                      THE XDDTNC ARRAY
!   SUMXNC   O    A    SMALL STEP INTEGRATION SUMS
!   IDSMXN   I    S    NUMBER OF STEPS COVERED BY (LAST DIMENSION OF)
!                      THE SUMXNC ARRAY
!   IBCKNC  I/O   S    COUNTER INDICATING HOW MANY EXTRA BACK
!                      VALUES HAVE BEEN COMPUTED FOR XDDTNC AND SUMXNC
!   LSAVEA   I    S    IF TRUE, THEN AT CERTAIN INTEGRATION STEPS
!                      VALUES OF THE XDDOT ARRAY WILL BE SAVED IN
!                      THE XDDOTH ARRAY AND PXDDOT IN PXDDTH
!   XDDOTH   O    A    ARRAY IN WHICH CERTAIN VALUES OF XDDOT SAVED
!   PXDDTH   O    A    ARRAY IN WHICH CERTAIN VALUES OF PXDDOT SAVED
!   TOPXTH   O    A    ARRAY IN WHICH CERTAIN VALUES OF TOPXAT SAVED
!   LTPXTH   O    A    ARRAY IN WHICH CERTAIN VALUES OF LTPXAT SAVED
!   NSTPSV   I    S    NUMBER OF STEPS AT WHICH XDDOT AND PXDDOT WILL
!   ISTPSV   I    A    STEPS AT WHICH XDDOT AND PXDDOT WILL
!                      BE SAVED (IF LSAVEA TRUE)
!   XPNC     O    A    PREDICTED S/C POS. AND VEL. SMALL STEP
!   XNC      O    A    CORRECTED SC POS. AND VEL. SMALL STEP
!   CPPNC    I    A    COEFFICIENTS FOR PRDICTING LARGE STEP STATE
!                      AT SMALL STEP TIMES
!   XLSASS   O    A    LARGE STEP STATE AT HIGH RATE STEPS
!   XDDTAC   O    A    COMPUTED ACCELERATIONS CORRESPOMDING TO
!                      ACCELEROMETER
!   LFHIRT   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!   LSURFF   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!   PXDDAC   O    A    PARTIAL DERIVATIVES OF XDDTAC
!   NEQNA    I    S    NUMBER OF ADJUSTING ACCELEROMTER PARTIALS
!   IPTFBS   I    A    MAPPING ARRAY ; EXPLICIT PARTIAL ARRAY TO
!                      COMPUTED ACCELERATION PARTIAL ARRAY
!   NPRMAC   I    A    NUMBER OF PARMETERS IN EACH FORCE MODEL
!                      GROUP CATEGORY YO BE MAPPED BY IPTFBS
!   DYNTIM   I    A    USER REQUESTED START AND STOP TIMES FOR
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
!   NPERDY   I    A    NUMBER OF USER REQUESTED
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
!
! COMMENTS:  THIS SUBROUTINE IS BASED UPON THE COWELL
!            SUBROUTINE FROM THE GEODYN 8202.0 PROGRAM. THE
!            SUBROUTINE HAS BEEN COMPLETELY REWRITTEN TO
!            COLLECT VECTORS FOR OPTIMAL EXECUTION ON THE
!            CDC CYBER 205. ALL LOOPS BASED ON NEQN,NEQN3,
!            NMOVES, OR NMOVEA SHOULD BE REPLACED BY Q8 CALLS
!            ON THE CYBER 205 COMPUTER. IF THE NUMBER OF
!            LIKE SATELLITES TO BE SIMULTANEOUSLY
!            INTEGRATED IS EXPECTED TO EXCEED THREE
!            ADDITIONAL CHANGES TO THE SOURCE SHOULD
!            BE MADE AS INDICATED BY IN-LINE COMMENTS
!            AND Q8 CALLS SHOULD BE PERFORMED ON ALL
!            LOOPS BASED ON N3.
!
! RESTRICTIONS:  THE REGULARIZED INTEGRATION CAPABILITY
!                HAS BEEN DISCARDED.
!                VARY-STEP INTEGRATION HAS NOT BEEN
!                IMPLEMENTED AT PRESENT, BUT WILL BE
!                ADDED LATER.
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      CHARACTER*33 FILNAM
      DIMENSION XP(N3,2),X(N3,2),SUMX(N3,2,NH),                         &
     &   XDDOT(N3,NSTEPS),PX(NEQN3,2),PX3(NEQN,N3,2),                   &
     &   SUMPX(NEQN3,2,NHV),PXDDOT(NEQN3,NSTEPV),                       &
     &   PXDDT3(NEQN,N3,NSTEPV),RSQ(NSAT),VMATRX(3,6,NSAT)
      DIMENSION  SUMRC(NSAT,2,NH),XDDRC(NSAT,NSTEPS)
      DIMENSION DNLT(NSAT)
!      DIMENSION AEI(6),PKPX(6,6)
      DIMENSION XDDTMC(N3,2)
      DIMENSION CPP(IORDER),CPV(IORDER),                                &
     &    CCP(IORDER),CCV(IORDER),CIP(IORDER),                          &
     &   CIV(IORDER),CCPV(IORDRV),CCVV(IORDRV)
      DIMENSION SMAT(6,6),VMATS(3,2,3)
      DIMENSION TOPXAT(2*NSAT,NSTEPS),LTPXAT(3*NSAT,NSTEPS)
      DIMENSION TOPXTH(2*NSAT,IORDER),LTPXTH(3*NSAT,IORDER)
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION ISATID(NSAT)
      DIMENSION UTDT(MINTPL,4)
      DIMENSION XDDTNC(N3,IDXDDN),SUMXNC(N3,2,IDSMXN)
      DIMENSION XDDTAC(3,NFSCAC,NSAT,IDXDDN),PXDDAC(NEQNA,N3,IDXDDN)
      DIMENSION XDDOTH(N3,IORDER),PXDDTH(NEQN3,IORDER)
      DIMENSION XPNC(N3,2),XNC(N3,2)
      DIMENSION CPPNC(NRAT1,IORDER,2),XLSASS(N3,2,NRAT1)
      DIMENSION ISTPSV(30)
      DIMENSION LFHIRT(NHRATE),LSURFF(NHRATE),IPTFBS(MXFMG)
      DIMENSION NPRMAC(MXHRG)
      DIMENSION DYNTIM(MDYNPD,2,NSAT),NPERDY(NSAT)
      DIMENSION EXACCT(2,NSAT),EXACIN(NSAT),EXACOB(MACOBS,NSAT)
      DIMENSION ACCTIM(MBAPPD,2,NSAT),ACCPER(MBAPPD,NSAT),NPERAC(NSAT)
      DIMENSION SUMRNC(N3,2)
      DIMENSION PXR(6,3,NSAT,2),SUMRNP(6,3,NSAT,2)
      DIMENSION TXSTAT(MXSTAT),DELXST(6,MXSTAT,NSAT)
      DIMENSION DSROT(3,3,NSAT)
      DIMENSION TMOS0(1),TMOS(1),TMOSP(1)
      DIMENSION SUMXOS(3,2,1)
      DIMENSION SUMPOS(NEQNI,3,2,1)
      DIMENSION XDDTOS(3,KNSTEPS,1)
      DIMENSION PDDTOS(NEQNI,3,KNSTEPS,1)
      DIMENSION SUMXNS(3,2),SUMPNS(NEQNIM,3,2)
      DIMENSION T1SEG(10),T2SEG(10)
      DIMENSION DUM(3),DUM1(3,2,1)
      DIMENSION XDDBRS(3),XDDBRF(3),XDDBRN(3)
!*************** DEBUG
      DIMENSION XTEMP(6)
!*************** DEBUG

      COMMON/ACCLRM/MDYNPD,MBAPPD,MACOBS,IDYNSC(200),MDYNST,IACCSC(200),&
     &              MACCSC,NACPRM(200),NATPRM(200),NXCLRM
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CRDDIM/NDCRD2,NDCRD3,NDCRD4,NDCRD5,NDCRD6,NDCRD7,          &
     &              NDCRD8,NDCRD9,NXCRDM
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/INTSAV/ILSTEP,NSEG,NSCHED(2,50,10)
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/LEPHM2/LXEPHM
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/RAPIDI/LINTF,LBUFOP
      COMMON/IDELTX/MXSTAT,NEVENTS,NDSTAT,IDSYST,NDELTX
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
      DATA IOUT/64/
      DATA ZERO/0.0D0/,ONE/1.0D0/
      DATA EPSLON/1.0D-12/
      DATA kentry/0/

      INTEGER, dimension(100) :: scratch_array
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! LBUF WILL BE TRUE WHEN THE BUFFER IS FILLED.
      LBUF=.FALSE.
! LBUFOP TRUE MEANS THAT WE STILL NEED TO OPEN A NEW BUFFER, INTEGRATION
! IS STIL ON
!  FIGURE OUT IF THIS SATELLITE NEEDS TO SAVE INTEGRATION INFORMATION
      IF(NINTOT.GT.0.AND..NOT.LINTF) THEN
!  ZERO OUT SUMXNS
      DO I=1,3
      DO J=1,2
      SUMXNS(I,J)=0.D0
      DO K=1,NEQNIM
      SUMPNS(K,I,J)=0.D0
      ENDDO
      ENDDO
      ENDDO
! AND START COUNTING SEGMENTS:
      ENDIF    ! .NOT.LINTF

!  INITIALIZE THE DSROT MATRIX

      DO 300 I=1,NSAT

      DO 200 J=1,3
      DO 100 K=1,3
      DSROT(J,K,I)=0.D0
      DSROT(J,J,I)=1.D0
  100 END DO
  200 END DO


  300 END DO

      JPXST=0
      LXSTAT=.FALSE.
      EPSQ=.25D0*ABS(H)
      LSVSTP=.FALSE.
      N2=2*N3/3
      NRAT=NRAT1+1
      NSVCT=(IORDER-1)-NSTPSV
      NSVCK=1
      IOL2=IORDER-2
      IOL1=IOL2+1
      IOVL2=IORDRV-2
      IOVL1=IOVL2+1
      N6=N3*2
      NEQN6=NEQN3*2
      NH1=NH-1
      NHV1=NHV-1
      ISH=H
      FSH=H-ISH
      ISHV=HV
      FSHV=HV-ISHV
      H2=H*H
      HS=H
      IF(NRAT1.GT.0) HS=H/DBLE(NRAT)
      HS2=HS*HS
      HV2=HV*HV
      IF(.NOT.LORBIT) H2C=-CCPV(1)*HV2
      IF(.NOT.LORBIT) H1C=-CCVV(1)*HV
      NPV=2
      IF(LNDRAG)NPV=1
      NPV3=NPV*3
      ISN0=0
      ISN=POSNEG
      L1900=.FALSE.
      KF=KCFSC-1
!   SET UP FOR COORDINATE SYSTEMS
  800 CONTINUE
      XNSTP=(DBLE(MJDS2-MJDSEC)+(FSEC2-FSEC))/H
      NSTP=XNSTP+ONE+EPSLON
      NSTP=MIN(NSTP,NINTIM-1)
      IF(NRAT1.GT.0) NSTP=MAX(NSTP,2)
      FSECNS=FSEC+NSTP*FSH
      ISEC=FSECNS
      MJDSNS=MJDSEC+NSTP*ISH+ISEC
      FSECNS=FSECNS-ISEC
!
      IF(ICBDGM.EQ.3) THEN
      CALL BUFEAR(MJDSEC,FSEC,MJDSNS,FSECNS,ISN,MJDR,FSECR,LRECAL,AA,   &
     &            II)
      ELSE
      CALL BUFXTR(MJDSEC,FSEC,MJDSNS,FSECNS,ISN,MJDR,FSECR,LRECAL,AA)
!
       IF(LXEPHM) THEN
       DO IJ=1,ICBODY
       CALL BUFSUP(AA,MJDSEC,FSEC,MJDSNS,FSECNS,II(KISUPE),             &
     & AA(KEPHMS),IJ,2)
       ENDDO
       ENDIF
      ENDIF
!
      IF(.NOT.LRECAL) GO TO 810
      XNSTP=(DBLE(MJDR-MJDSEC)+(FSECR-FSEC))/H
      NSTP=XNSTP+EPSLON
  810 CONTINUE
      IF(ISN.LT.0) ISN0=NSTP+1
      IF(NRAT1.LE.0) THEN
         DO 820 I=1,NSTP
         AA(KF+ISN0+ISN*I)=FSEC+H*I
  820    CONTINUE
      ELSE
! WHEN MULTIRATE INTEGRATION IS BEING USED NEED THE
! PREVIOUS VALUE FOR INTERPOLATION
         DO 825 I=1,NSTP
         AA(KF+ISN0+ISN*I)=FSEC+H*(I-1)
  825    CONTINUE
      ENDIF
!   MAKE OTHER NECCESARY CALLS
!
      IF(ICBDGM.EQ.3) THEN
      CALL PRECSS(MJDSEC,AA(KCFSC),AA(KETA),AA(KZTA),AA(KTHTA),         &
     &            AA(KSRTCH),NSTP)
      CALL NUVECT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            NSTP,AA(KSRTCH))
      CALL NPVECT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NSTP,AA(KSRTCH),          &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.,                   &
     &            AA(KPDPSI),AA(KPEPST),AA(KNUTIN),AA(KNUTMD),.FALSE.,  &
     &            AA(KDXDNU),AA(KDPSIE),AA(KEPSTE),DUM,DUM1)
      CALL GRHRAN(MJDSEC,AA(KCFSC),.FALSE.,.FALSE.,AA(KEQN),AA(KSRTCH), &
     &            AA(KTHG),AA(KCOSTG),AA(KSINTG),NSTP,AA,II,UTDT(1,1),  &
     &            .FALSE.,DUM,DUM1)
      ELSE
!  NEW MARS ONLY NUTATION SUBROUTINE
          IF(LMARS.AND.IMRNUT.EQ.1) THEN
      CALL PRMCSS(MJDSEC,AA(KCFSC),AA(KETA),AA(KZTA),AA(KTHTA),         &
     &            AA(KSRTCH),NSTP)
      CALL NUVMCT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            NSTP,AA(KSRTCH))
      CALL NPVMCT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NSTP,AA(KSRTCH),          &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.)
      CALL MM2EJ2(MJDSEC,AA(KCFSC),AA(KROTMT),NDCRD2,AA(KSRTCH),        &
     & .FALSE.)
!
      CALL ROTMTR(MJDSEC,AA(KCFSC),.FALSE.,AA(KEQN),AA(KSRTCH),         &
     &            AA(KTHG),AA(KCOSTG),AA(KSINTG),NSTP,AA,II)
          ELSE
      CALL PRXCSS(MJDSEC,AA(KCFSC),AA(KETA),AA(KZTA),AA(KTHTA),         &
     &            AA(KSRTCH),NSTP,AA(KDPSI),AA(KEPST),AA(KEPSM),AA,1)
      CALL NUVXCT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            NSTP,AA(KSRTCH))
      CALL NPVXCT(MJDSEC,AA(KCFSC),AA(KDPSI),AA(KEPST),AA(KEPSM),       &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NSTP,AA(KSRTCH),          &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.)
      CALL ROTXTR(MJDSEC,AA(KCFSC),.FALSE.,AA(KEQN),AA(KSRTCH),         &
     &            AA(KTHG),AA(KCOSTG),AA(KSINTG),NSTP,AA,               &
     &            AA(KACOSW),AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),  &
     &            AA(KBCOFW),II,1)
      ENDIF
      ENDIF
!
      IF(NRAT1.LE.0) THEN
         NTCRD=0
      ELSE
! WHEN MULTIRATE INTEGRATION IS BEING USED ONE
! EXTRA VALUE WAS COMPUTED FOR INTERPOLATION
         NTCRD=1
      ENDIF

      !write(6,'(A,1x,I12, 1x, F10.4)') &
      !    'cowell: MJDSEC, FSEC ', MJDSEC, FSEC
      IF(L1900) GO TO 1900
      L1900=.TRUE.
      IF(LORBIT)GO TO 1500
      S=DBLE(MJDSV-MJDSEC)+(FSECV-FSEC)
 1000 CONTINUE
      LSBURN=.FALSE.
      LFBURN=.FALSE.
! DETERMINE IF DESIRED TIME HAS BEEN ACHIEVED
      TIMDFV=(DBLE(MJDSV-MJDS2)+(FSECV-FSEC2))*POSNEG
!*********************** DEBUG
      IF(L4MRST) THEN
         TDQ=ABS(TIMDFV)
         IF(TDQ.LT.EPSQ) RETURN
      ELSE
         IF(TIMDFV.GE.ZERO) RETURN
      ENDIF
!*********************** DEBUG
! DESIRED TIME HAS NOT BEEN ACHIEVED
 1100 CONTINUE
      IF(IBACKV.LT.NHV1) GO TO 1400
! SHIFT BACK VALUE ARRAYS FOR PARTIALS AND RESET POINTERS
! NSAVSV WILL BE A FUNCTION OF THE NUMBER OF
!    ADDITIONAL INTEGRATION STEPS REQUIRED
!    TO ADVANCE PAST MJDS2,FSEC
      NSAVSV=TIMDFV/HV+DBLE(NHV)
      NSAVSV=MAX(MIN(NSAVSV,NHV1),1)
      NSHFTV=NHV-NSAVSV
      NSAVAV=NSAVSV+IOVL2
      NSHFTA=NSHFTV*NEQN3
      NSHFTS=NSHFTA*2
      NMOVEA=NSAVAV*NEQN3
      NMOVES=NSAVSV*NEQN6
!
      DO 1200 I=1,NMOVES
      SUMPX(I,1,1)=SUMPX(I+NSHFTS,1,1)
 1200 END DO
!
!
      DO 1300 I=1,NMOVEA
      PXDDOT(I,1)=PXDDOT(I+NSHFTA,1)
 1300 END DO
!
!
      IBACKV=IBACKV-NSHFTV
 1400 CONTINUE
      S=S+HV
      IF(S*POSNEG.LE.ZERO) GO TO 3300
      GO TO 1600
 1500 CONTINUE
! ORBIT GENERATION ONLY
! DETERMINE IF DESIRED TIME HAS BEEN ACHIEVED
      TIMDIF=(DBLE(MJDSEC-MJDS2)+FSEC-FSEC2)*POSNEG
      IF(L4MRST) THEN
         TDQ=ABS(TIMDIF)
         IF(TDQ.LT.EPSQ) RETURN
      ELSE
         IF(TIMDIF.GE.ZERO) RETURN
      ENDIF
! DESIRED TIME HAS NOT BEEN ACHIEVED
 1600 CONTINUE
! SHIFT BACK VALUE ARRAYS FOR ORBIT AND RESET POINTERS
      IF(IBACK.LT.NH1) GO TO 1900
!  NSAVES WILL BE A FUNCTION OF THE NUMBER OF ADDITIONAL
!         INTEGRATION STEPS REQUIRED TO ADVANCE PAST MJDS2,FSEC2
      TIMDIF=(DBLE(MJDSEC-MJDS2)+(FSEC-FSEC2))*POSNEG
      NSAVES=TIMDIF/H+DBLE(NH)
      NSAVES=MAX(MIN(NSAVES,NH1),1)
      NSHIFT=NH-NSAVES
      NSAVEA=NSAVES+IOL2
      NSHFTA=NSHIFT*N3
      NSHFTS=NSHFTA*2
      NSHFTP=NSHIFT*2*NSAT
      NMOVEA=NSAVEA*N3
      NMOVES=NSAVES*N6
      NMVTPX=NSAVEA*2*NSAT
!
      DO 1700 I=1,NMOVES
      SUMX(I,1,1)=SUMX(I+NSHFTS,1,1)
 1700 END DO
!
!
      DO 1800 I=1,NMOVEA
      XDDOT(I,1)=XDDOT(I+NSHFTA,1)
      LTPXAT(I,1)=LTPXAT(I+NSHFTA,1)
 1800 END DO
      DO 1805 I=1,NMVTPX
      TOPXAT(I,1)=TOPXAT(I+NSHFTP,1)
 1805 END DO
!
      IF(LXPCLK) THEN
         NMOVEQ=NMOVES/3
         NSHFTQ=NSHFTS/3
         DO I=1,NMOVEQ
           SUMRC(I,1,1)=SUMRC(I+NSHFTQ,1,1)
         ENDDO
         NMOVEQ=NMOVEA/3
         NSHFTQ=NSHFTA/3
         DO I=1,NMOVEQ
           XDDRC(I,1)=XDDRC(I+NSHFTQ,1)
         ENDDO
      ENDIF

!
      IBACK=IBACK-NSHIFT
!
      IF(LSAVEA) GO TO 1900
! ACCELERATIONS FOR SEPARATE STEP INTEGRATION
! (WHETHER OR NOT SEPARATE STEP INTEGRATION)
!
!   THE INTVL [IBACK+2-NSAVES,IBACK+1+IOL2] IS BEING SAVED FOR REG STEP
!   FOR LARGE STEP ACCELS ; THE NUMBER OF ACCELS SAVED IS NSAVES+IOL2
!
!   WHAT IS SAME INTERVAL FOR SMALL STEP ACCELS?
!   RIGHT HAND ENDPOINT IS  [IBCKNC+1+IOL2]
!   THE NUMBER OF SMALL STEP ACCELS WHICH MUST BE SAVED IS:
!   [(NSAVES-1+IOL2)*NRAT+1]  ; SO, THE LEFT HAND ENDPOINT IS:
!   (IBCKNC+1+IOL2)-(NSAVES-1+IOL2)*NRAT
!   THE SAVED ACCEL INTERVAL IS:
!   [(IBCKNC+1+IOL2)-(NSAVES-1+IOL2)*NRAT , IBCKNC+1+IOL2]
!   AND NSHFTN=(IBCKNC+IOL2)-(NSAVES-1+IOL2)*NRAT
!   THE NUMBER OF SUM STEPS TO BE SAVED IS [(NSAVES-1+IOL2)*NRAT+1-IOL2]
!
      NSHFTN=(IBCKNC+IOL2)-(NSAVES-1+IOL2)*NRAT
!
! FIRST SOME CHECKS
!
      IF(NSHFTN.LT.1) THEN
         WRITE(6,6000)
         WRITE(6,6001)
         WRITE(6,6002) ISATID(1),MJDSEC,FSEC
         WRITE(6,6003) IBCKNC,IORDER,NSAVES,NRAT,IDXDDN
         STOP
      ENDIF
      ITEST=IBCKNC+1+IOL2
      IF(ITEST.GT.IDXDDN) THEN
      WRITE(6,6000)
      WRITE(6,6001)
      WRITE(6,6002) ISATID(1),MJDSEC,FSEC
      WRITE(6,6003) IBCKNC,IORDER,NSAVES,NRAT,IDXDDN
      STOP
      ENDIF
!CCCCCNMOVEN=NMOVEA*NRAT
      NMOVEN=((NSAVES-1+IOL2)*NRAT+1)*N3
      NSHFT=NSHFTN*N3
      DO I=1,NMOVEN
         XDDTNC(I,1)=XDDTNC(I+NSHFT,1)
      ENDDO
!
      IF(NEQNA.GT.0) THEN
         DO I=1,NMOVEN
            DO J=1,NEQNA
               PXDDAC(J,I,1)=PXDDAC(J,I+NSHFT,1)
            ENDDO
         ENDDO
      ENDIF
!
      NMOVEC=NMOVEN*NFSCAC
      NSHFTC=NSHFT*NFSCAC
      DO I=1,NMOVEC
         XDDTAC(I,1,1,1)=XDDTAC(I+NSHFTC,1,1,1)
      ENDDO
      IF(NRAT.LE.1) GO TO 1890
! INTEGRATION SUMS FOR SEPARATE STEP INTEGRATION
! ONLY IF SEPARATE INTEGRATION
!
!
!   THE SAVED SUM INTERVAL IS:
!   [(IBCKNC+1+IOL2)-(NSAVES-1+IOL2)*NRAT , IBCKNC+1]
!
! FIRST A CHECK
!
      ITEST=IBCKNC+1
      IF(ITEST.GT.IDSMXN) THEN
         WRITE(6,6000)
         WRITE(6,6011)
         WRITE(6,6002) ISATID(1),MJDSEC,FSEC
         WRITE(6,6013) IBCKNC,IORDER,NSAVES,NRAT,IDSMXN
         STOP
      ENDIF
!CCCCCNMOVEN=NMOVES*NRAT
      NMOVEN=((NSAVES-1+IOL2)*NRAT+1-IOL2)*N6
      NSHFT=NSHFTN*N6
      DO I=1,NMOVEN
         SUMXNC(I,1,1)=SUMXNC(I+NSHFT,1,1)
      ENDDO
 1890 CONTINUE
      IBCKNC=IBCKNC-NSHFTN
 1900 CONTINUE
      NTCRD=NTCRD+1
      IF(NTCRD.GT.NSTP) GO TO 800
      IBACK1=IBACK+1
      IORBAK=IORDER+IBACK
      IF(NRAT1.GT.0) THEN
         IFILL=IORDRV+IBACKV


         !write(6,'(A)')'cowell: call PSS'

         CALL PSS(NRAT1,CPPNC,IORDER,IOL1,IOL2,H,H2,SUMX(1,1,IBACK1),   &
     &            XDDOT(1,IORBAK-IOL1),NSAT,                            &
     &            N3,XLSASS,IBCKNC,XPNC,XNC,CPP,CPV,CCP,CCV,HS,HS2,     &
     &            SUMXNC,XDDTNC,MJDSEC,FSEC,IDSMXN,IDXDDN,              &
     &            ISATID,XDDTAC,LFHIRT,LSURFF,NTCRD,NEQN,               &
     &            XDDOT(1,IORBAK),PXDDT3(1,1,IFILL),XDDTMC,             &
     &            TOPXAT(1,IORBAK),LTPXAT(1,IORBAK),PXDDAC,NEQNA,IPTFBS,&
     &            NPRMAC,DYNTIM,NPERDY,EXACCT,EXACIN,EXACOB,LACCELS,    &
     &            ACCTIM,ACCPER,NPERAC,II(KIACCP),AA(KPACCL),NXSTAT,    &
     &            TXSTAT,DELXST,SUMRNC,IPXST,HREMAL,LXSTAT,JPXST,       &
     &            XPNC,XP,DSROT,XDDRC(1,IORBAK),LQ1,IPSBRN,LQ2,         &
     &            XDDBRN,AA,II,LL)
          IF(LQ1) THEN
            LSBURN=.TRUE.
            XDDBRS(1)=XDDBRN(1)
            XDDBRS(2)=XDDBRN(2)
            XDDBRS(3)=XDDBRN(3)
          ENDIF
          IF(LQ2) THEN
            LFBURN=.TRUE.
            XDDBRF(1)=XDDBRN(1)
            XDDBRF(2)=XDDBRN(2)
            XDDBRF(3)=XDDBRN(3)
          ENDIF
      ENDIF
      IORBNC=IORDER+IBCKNC
! PREDICT POSITION
! IF NSAT IS EXPECTED TO BE GREATER THAN 3; NESTING LOOP 2100
! INSIDE 2000 AND LOOP 2300 INSIDE 2200 ALONG WITH VECTORIZATION
! OF THE INNERMOST LOOPS WOULD SPEED-UP RUNNING TIME SIGNIFICANTLY.
      DO 2100 J=1,N3
      SUM=SUMX(J,1,IBACK1)
      !write(6,'(A,2(1x,I6),1x,E20.10)') &
      !'cowell: Iback1, J, sumx(j,1,iback1) ', &
      !         Iback1, J, sumx(j,1,iback1)
      DO 2000 I=1,IOL2
      K=IORBAK-I
      SUM=SUM+CPP(I)*XDDOT(J,K)
      !if( I == 1 )then
      !    write(6,'(A,4(1x,I6),2(1x,E20.10))') &
      !    'cowell: IORBAK, J, I, K, CPP(I), XDDOT(J,K) ', &
      !             IORBAK, J, I, K, CPP(I), XDDOT(J,K)
      !endif ! I == 1
 2000 END DO
      XP(J,1)=SUM*H2
 2100 END DO
      IF(LNDRAG.AND..NOT.LGRELE) GO TO 2400
! PREDICT VELOCITY
      DO 2300 J=1,N3
      SUM=SUMX(J,2,IBACK1)
      DO 2200 I=1,IOL1
      K=IORBAK-I
      SUM=SUM+CPV(I)*XDDOT(J,K)
 2200 END DO
      XP(J,2)=SUM*H
 2300 END DO
 2400 CONTINUE
! INCREMENT TIME FOR ORBIT INTEGRATION
!!!!!!!!!!!!!!!DIR$ SUPPRESS FSEC
      FSEC=FSEC+FSH
      ISEC=FSEC
      FSEC=FSEC-ISEC
      MJDSEC=MJDSEC+ISH+ISEC
      NCORR=0
! START OF CORRECTOR LOOP
 2500 CONTINUE
      NCORR=NCORR+1

! EVALUATE ACCELERATION
      IFILL=IORDRV+IBACKV
      INTCRD=ISN*NTCRD+ISN0
      IF(NRAT1.GT.0) THEN
          DO IQP=1,N6
            XP(IQP,1)=XP(IQP,1)+XPNC(IQP,1)
          ENDDO
      ENDIF
      !write(6,'(A)')'cowell: call F123 1'
      CALL F123(MJDSEC,FSEC,XP,XDDOT(1,IORBAK),PXDDT3(1,1,IFILL),NSAT,  &
     &  NEQN,                                                           &
     &  INTCRD,XDDTMC,TOPXAT(1,IORBAK),LTPXAT(1,IORBAK),AA,II,LL,ISATID,&
     &  LFHIRT,LSURFF,XDDTNC(1,IORBNC),XDDTAC(1,1,1,IORBNC),            &
     &  PXDDAC(1,1,IORBNC),NEQNA,IPTFBS,NPRMAC,.FALSE.,LATOT,ONE,       &
     &  DYNTIM,NPERDY,LACCELS,EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,&
     &  II(KIACCP),AA(KPACCL),NRAT,XDDRC(1,IORBAK),1,DUM,DUM)
      !write(6,'(A)')'cowell: call F123 2'
      CALL F123(MJDSEC,FSEC,XP,XDDOT(1,IORBAK),PXDDT3(1,1,IFILL),NSAT,  &
     &  NEQN,                                                           &
     &  INTCRD,XDDTMC,TOPXAT(1,IORBAK),LTPXAT(1,IORBAK),AA,II,LL,ISATID,&
     &  LFHIRT,LSURFF,XDDTNC(1,IORBNC),XDDTAC(1,1,1,IORBNC),            &
     &  PXDDAC(1,1,IORBNC),NEQNA,IPTFBS,NPRMAC,.FALSE.,LATOT,ONE,       &
     &  DYNTIM,NPERDY,LACCELS,EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,&
     &  II(KIACCP),AA(KPACCL),NRAT,XDDRC(1,IORBAK),2,DUM,DUM)
      !write(6,'(A)')'cowell: call F123 3'
      CALL F123(MJDSEC,FSEC,XP,XDDOT(1,IORBAK),PXDDT3(1,1,IFILL),NSAT,  &
     &  NEQN,                                                           &
     &  INTCRD,XDDTMC,TOPXAT(1,IORBAK),LTPXAT(1,IORBAK),AA,II,LL,ISATID,&
     &  LFHIRT,LSURFF,XDDTNC(1,IORBNC),XDDTAC(1,1,1,IORBNC),            &
     &  PXDDAC(1,1,IORBNC),NEQNA,IPTFBS,NPRMAC,.FALSE.,LATOT,ONE,       &
     &  DYNTIM,NPERDY,LACCELS,EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,&
     &  II(KIACCP),AA(KPACCL),NRAT,XDDRC(1,IORBAK),3,DUM,DUM)
      HQ=H
      IF(NRAT1.GT.0) HQ=HS
      CALL F(MJDSEC,FSEC,XP,XDDOT(1,IORBAK),PXDDT3(1,1,IFILL),NSAT,NEQN,&
     &  INTCRD,XDDTMC,TOPXAT(1,IORBAK),LTPXAT(1,IORBAK),AA,II,LL,ISATID,&
     &  LFHIRT,LSURFF,XDDTNC(1,IORBNC),XDDTAC(1,1,1,IORBNC),            &
     &  PXDDAC(1,1,IORBNC),NEQNA,IPTFBS,NPRMAC,.FALSE.,LATOT,ONE,       &
     &  DYNTIM,NPERDY,LACCELS,EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,&
     &  II(KIACCP),AA(KPACCL),NRAT,XDDRC(1,IORBAK),DUM,DUM,LQ1,IPSBRN,  &
     &  LQ2,XDDBRN,HQ)
        IF(LQ1) THEN
          LSBURN=.TRUE.
          XDDBRS(1)=XDDBRN(1)
          XDDBRS(2)=XDDBRN(2)
          XDDBRS(3)=XDDBRN(3)
        ENDIF
        IF(LQ2) THEN
          LFBURN=.TRUE.
          XDDBRF(1)=XDDBRN(1)
          XDDBRF(2)=XDDBRN(2)
          XDDBRF(3)=XDDBRN(3)
        ENDIF
! IF NSAT IS EXPECTED TO BE GREATER THAN 3; REPLACING LOOP 2800 WITH
! LOOPS NESTED INSIDE LOOPS 2600 AND 2700 ALONG WITH VECTORIZATION
! OF THESE INNERMOST LOOPS WOULD SPEED-UP RUNNING
! TIME SIGNIFICANTLY.
! CORRECT POSITION AND VELOCITY
      DO 2800 J=1,N3
      !write(6,'(A,2(1x,I6),1x,E20.10)') &
      !'cowell:2800 Iback1, J, sumx(j,1,iback1) ', &
      !             Iback1, J, sumx(j,1,iback1)
      SUM=SUMX(J,1,IBACK1)
      DO 2600 I=1,IOL2
      K=IORBAK-I+1
      !if( I == 1 ) then
      !    write(6,'(A,4(1x,I6),2(1x,E20.10))') &
      !    'cowell:2600 IORBAK, J, I, K, CCP(I), XDDOT(J,K) ', &
      !                 IORBAK, J, I, K, CCP(I), XDDOT(J,K)
      !endif ! I == 1
      SUM=SUM+CCP(I)*XDDOT(J,K)
 2600 END DO
      X(J,1)=SUM*H2
      SUM=SUMX(J,2,IBACK1)
      DO 2700 I=1,IOL1
      K=IORBAK-I+1
      SUM=SUM+CCV(I)*XDDOT(J,K)
 2700 END DO
      X(J,2)=SUM*H
 2800 END DO
!
! CORECTION STEP FOR HIGH RATE
      IF(NRAT1.GT.0) THEN
         !write(6,'(A)')'cowell: call PCSSS   '
         CALL PCSSS(XNC,N3,IORDER,IOL1,IOL2,CCP,CCV,HS,HS2,             &
     &              SUMRNC,XDDTNC(1,IORBNC-IOL1+1))
         DO IQP=1,N6
           X(IQP,1)=X(IQP,1)+XNC(IQP,1)
         ENDDO
      ENDIF
! COMPUTE MAGNITUDE OF DIFFERENCE BETWEEN PREVIOUS
! AND CURRENT POSITIONS AND TEST FOR CONVERGENCE
      DO 2850 ISAT=1,NSAT
      I=(ISAT-1)*3+1
      RSQ(ISAT)=X(I,1)**2+X(I+1,1)**2+X(I+2,1)**2
      DIFFSQ=(X(I,1)-XP(I,1))**2+(X(I+1,1)-XP(I+1,1))**2                &
     &      +(X(I+2,1)-XP(I+2,1))**2

      !write(6,'(A,3(1x,I6),3(1x,E20.10))')&
      !      'cowell: ncorr, isat, I, x(I,1), X(I+1,1), X(I+2,1)   ', &
      !               ncorr, isat, I, x(I,1), X(I+1,1), X(I+2,1)
      !write(6,'(A,3(1x,I6),3(1x,E20.10))')&
      !      'cowell: ncorr, isat, I, xp(I,1), Xp(I+1,1), Xp(I+2,1)', &
      !               ncorr, isat, I, xp(I,1), Xp(I+1,1), Xp(I+2,1)
      IF(DIFFSQ.GT.CTOL*RSQ(ISAT))GO TO 2875
 2850 END DO
      GO TO 3000
 2875 CONTINUE
!
!     ....NUMBER OF CORRECTIONS SHOULD NEVER BE > 1
!     ....IF NUMBER OF CORRECTIONS > 3, STOP PROGRAM
!
      IF(NCORR.GT.3) THEN
         WRITE(6,10211) NCORR
10211    FORMAT(///' COWELL: NCORR = ',I5/                              &
     &          ' TOO MANY CORRECTIONS IN COWELL INTEGRATOR.'/          &
     &          ' CHECK INTEGRATION STEP SIZE -- PROBABLY TOO LARGE.'/  &
     &          ' REDUCE STEP SIZE AND RE-SUBMIT.'///)
         CALL ERROR
      ENDIF
!
! NOT CONVERGED PERFORM ADDITIONAL CORRECTION
      DO 2900 J=1,N3
      XP(J,1)=X(J,1)
 2900 END DO
      GO TO 2500
 3000 CONTINUE
! CONVERGENCE ACHIEVED
      NOCORR=NOCORR+NCORR
      NOSTEP=NOSTEP+1
! PERFORM ACCELERATION EVALUATION*
      DO 3150 ISAT=1,NSAT
      IO=(ISAT-1)*3
      I=IO+1
      R= SQRT(RSQ(ISAT))
      XGMR3=GM/RSQ(ISAT)
      XGMR3=XGMR3/R
      DO 3100 J=1,3
!     XDDOT(IO+J,IORBAK)=XDDOT(IO+J,IORBAK)
!    1   +GM*(XP(IO+J,1)/RP3-X(IO+J,1)/R3)
      XDDOT(IO+J,IORBAK)=-X(IO+J,1)*XGMR3+XDDTMC(IO+J,1)
 3100 END DO
 3150 END DO
      LSVSTP=.FALSE.
      IF(LSAVEA.AND.NSVCT.LT.IOL1) THEN
       IF(NOSTEP.EQ.ISTPSV(NSVCK)) THEN
          LSVSTP=.TRUE.
          NSVCK=NSVCK+1
          NSVCT=NSVCT+1
          DO IQP=1,N3
             XDDOTH(IQP,NSVCT)=XDDOT(IQP,IORBAK)
             LTPXTH(IQP,NSVCT)=LTPXAT(IQP,IORBAK)
          ENDDO
          DO IQP=1,N2
             TOPXTH(IQP,NSVCT)=TOPXAT(IQP,IORBAK)
          ENDDO
         ENDIF
      ENDIF
! INCREMENT BACK VALUE POINTER
      IBACK=IBACK+1
      IBACK1=IBACK+1
      IBCKNC=IBCKNC+1
! UPDATE SUMS
      DO 3200 J=1,N3
      SUMX(J,2,IBACK1)=SUMX(J,2,IBACK)                                  &
     &                +XDDOT(J,IORBAK)
      SUMX(J,1,IBACK1)=SUMX(J,2,IBACK1)                                 &
     &                +SUMX(J,1,IBACK)
 3200 END DO

!--------DEP ------------
! IF INTEGRATION INFORMATION NEEDS TO BE SAVED

           IF(NINTOT.GT.0.AND..NOT.LINTF) THEN

!     FILL UP
      TMOS(1)=DBLE(MJDSEC)+FSEC
      TMOLD=TMOS0(1)
      XQP=.001D0+(TMOS(1)-TMOS0(1))/H
      IQP=XQP
      IQP=IOL1+IQP

      IF(IQP.LE.0) IQP=1

      DO J=1,N3
          XDDTOS(J,IQP,1)=XDDOT(J,IORBAK)
      ENDDO

! CHECK IF END OF BUFFER HAS BEEN REACHED


! we need to fill this in order to have the information ready when at the
! end of the integration.
      ISEGM=NSEG
      T1SEG(ISEGM)=TMOS0(1)
      T2SEG(ISEGM)=TMOS(1)

      ILSTEP=IQP
      LBUFOP=.TRUE.
      IF(IQP.EQ.KNSTEPS) THEN
      IQPP=IQP-NSTEPS+1
      IQPE=IQP
      ISEGM=NSEG
      T1SEG(ISEGM)=TMOS0(1)
      T2SEG(ISEGM)=TMOS(1)

!     IF(NSEG.EQ.1) THEN
      WRITE(FILNAM,FMT='(A13,I7,A4,I2,A7)')'RAPID_INT_SAT',ISATID,      &
     & '_SEG',NSEG,'.COWELL'
!     WE REACHED THE END OF THE BUFFER IN DYNAMIC MEMORY MEMORY
!     NOTE: REAL MEMORY IS LARGER THAN BUFFER MEMORY
!     DUMP
      CALL FNDNUM(ISATID,II(KISATN),NSETA,IRET)
      NSCHED(1,IRET,NSEG)=IRET
      NSCHED(2,IRET,NSEG)=ILSTEP
      OPEN(IOUT,FILE=FILNAM,STATUS='NEW',FORM='UNFORMATTED')
!     ENDIF

!     COMPUTE THE INTEGRATION SUMS FOR A NEW INTEGRATION BUFFER
!     COMPUTE NEW TMOS0(1)
      TMNEW=TMOS(1)-(NSTEPS-IOL1)*H
      CALL NSUMO(IOL1,SUMXOS,XDDTOS,KNSTEPS,H,TMOLD,TMNEW,SUMXNS)
!  THIS LOOP WORKS IF THERE IS ONLY ONE SATELLITE PER SET
!
      LBUF=.TRUE.
      ENDIF

          ENDIF     ! IF(.NOT.LINTF)

      IF(NRAT1.GT.0) THEN
         DO J=1,N3
            SUMXNC(J,2,IBCKNC+1)=SUMRNC(J,2)                            &
     &                          +XDDTNC(J,IORBNC)
            SUMXNC(J,1,IBCKNC+1)=SUMXNC(J,2,IBCKNC+1)                   &
     &                          +SUMRNC(J,1)
         ENDDO
      ENDIF
      IF(LXPCLK) THEN
         DO J=1,NSAT
            SUMRC(J,2,IBACK1)=SUMRC(J,2,IBACK)                          &
     &                         +XDDRC(J,IORBAK)
            SUMRC(J,1,IBACK1)=SUMRC(J,2,IBACK1)                         &
     &                         +SUMRC(J,1,IBACK)
         ENDDO
      ENDIF
! * THE FOLLOWING LENS-THIRRING CODE HAS BEEN COMMENTED OUT
!   BECAUSE LENS-THIRRING IS NOW BEING APPLIED TO THE EQUATIONS
!   OF MOTION IN SUBROUTINE FEAREL.
!     IF(.NOT.LGRELE) GO TO 3290
! ACCUMALTE NODE DRAG DUE TO LENSE-THIRRING
!     DO 3250 ISAT=1,NSAT
!     IO=(ISAT-1)*3
!     CALL ELEM(X(IO+1,1),X(IO+2,1),X(IO+3,1),X(IO+1,2),X(IO+2,2),
!    .          X(IO+3,2),AEI,2,PKPX,GM)
!     SLTC=DSQRT(ONE-AEI(2)**2)
!     SLTC=SLTC*AEI(1)
!     SLTC=SLTC**3
!     SLTC=POSNEG/SLTC
!     DNLT(ISAT)=DNLT(ISAT)+SLTC*CBLTC*H
!3250 CONTINUE
!3290 CONTINUE
! IF ONLY ORBIT GENERATION BYPASS INTEGRATION
! OF VARIATIONAL PARTIALS AND RETURN
! TO START OF ORBIT INTEGRATION LOOP
      IF(LORBIT)GO TO 1500
 3300 CONTINUE
! INCREMENT TIME FOR VARIATIONAL EQUATION INTEGRATION
      FSECT=FSECV+FSHV
      ISEC=FSECT
      FSECT=FSECT-ISEC
      MJDST=MJDSV+ISHV+ISEC
! DETERMINE IF ORBIT HAS BEEN ADVANCED TO TIME
!     LATER THAN OR EQUAL TO TIME OF
!     VARIATIONAL EQUATIONS
      S=DBLE(MJDST-MJDSEC)+(FSECT-FSEC)
      IF(S*POSNEG) 3400,3500,1600
! VARIATIONAL EQUATION TIME EARLIER;
!        INTERPOLATE FOR ORBIT
 3400 CONTINUE
      SV=S/H
      CALL INTRP(SV,CIP,CIV,IORDER,H,SUMX(1,1,IBACK1),                  &
     &   XDDOT(1,IBACK1),N3,IOL1,X)
! EVALUATE FORCES AT INTERPOLATION TIME
      IFILL=IORDRV+IBACKV
!   THIS CALL TO F IS BEING MADE BECAUSE ORBIT STEP TIME DOES
!   NOT COINCIDE WITH VARIATIONAL EQUATION TIME;COORDINATE SYSTEM
!   QUANTITIES ARE BEING CALCULATED WITH VECTOR LENGTH 1
!
!CC   CALL BUFPOS(MJDST,FSECT,MJDST,FSECT,ISN,MJDR,FSECR,LRECAL,AA)
!
      IF(ICBDGM.EQ.3) THEN
         CALL BUFEAR(MJDST,FSECT,MJDST,FSECT,ISN,MJDR,FSECR,LRECAL,AA,  &
     &    II)
      ELSE
         CALL BUFXTR(MJDST,FSECT,MJDST,FSECT,ISN,MJDR,FSECR,LRECAL,AA)
!
       IF(LXEPHM) THEN
       DO IJ=1,ICBODY
       CALL BUFSUP(AA,MJDST,FSECT,MJDST,FSECT,II(KISUPE),               &
     & AA(KEPHMS),IJ,2)
       ENDDO
       ENDIF
!
      ENDIF
!
      CALL PRECSS(MJDST,FSECT,ETA,ZTA,THTA,AA(KSRTCH),1)
      CALL NUVECT(MJDST,FSECT,DPSI,EPST,EPSM,1,AA(KSRTCH))
      CALL DEQN(1,.FALSE.,MJDST,FSECT,THTA,ZTA,ETA,EPST,                &
     &          EPSM,DPSI,AA(KROTMT+NDCRD2-1),AA(KROTMT+NDCRD3-1),      &
     &          AA(KROTMT+NDCRD4-1),AA(KROTMT+NDCRD5-1),                &
     &          AA(KROTMT+NDCRD6-1),AA(KROTMT+NDCRD7-1),                &
     &          AA(KROTMT+NDCRD8-1),AA(KROTMT+NDCRD9-1),                &
     &          AA(KROTMT+NDCRD9+NDCRD2-1),EQN,AA(KSRTCH),1)
      CALL GRHRAN(MJDST,FSECT,.FALSE.,.FALSE.,EQN,AA(KSRTCH),           &
     &  AA(KTHG+NDCRD2-1),AA(KCOSTG+NDCRD2-1),AA(KSINTG+NDCRD2-1),1,    &
     &  AA,II,UTDT(1,1),.FALSE.,DUM,DUM1)
!  THIS CALL CAN NOT BE IF MULTIRATE INTEGRATION IS SELECTED. IN
!  THAT CASE IORDER=IORDRV AND H=HV
      CALL F123(MJDST,FSECT,X,XP,PXDDT3(1,1,IFILL),NSAT,                &
     &       NEQN,NDCRD2,XP,TOPXAT(1,IFILL),LTPXAT(1,IFILL),AA,II,LL,   &
     &       ISATID,                                                    &
     &       LFHIRT,LSURFF,XNC,XPNC,                                    &
     &       PXDDAC(1,1,IFILL),NEQNA,IPTFBS,NPRMAC,.FALSE.,.TRUE.,ONE,  &
     &       DYNTIM,NPERDY,LACCELS,EXTACC,EXACIN,EXACOB,ACCTIM,ACCPER,  &
     &       NPERAC,II(KIACCP),AA(KPACCL),NRAT,XP,1,DUM,DUM)
      CALL F123(MJDST,FSECT,X,XP,PXDDT3(1,1,IFILL),NSAT,                &
     &       NEQN,NDCRD2,XP,TOPXAT(1,IFILL),LTPXAT(1,IFILL),AA,II,LL,   &
     &       ISATID,                                                    &
     &       LFHIRT,LSURFF,XNC,XPNC,                                    &
     &       PXDDAC(1,1,IFILL),NEQNA,IPTFBS,NPRMAC,.FALSE.,.TRUE.,ONE,  &
     &       DYNTIM,NPERDY,LACCELS,EXTACC,EXACIN,EXACOB,ACCTIM,ACCPER,  &
     &       NPERAC,II(KIACCP),AA(KPACCL),NRAT,XP,2,DUM,DUM)
      CALL F123(MJDST,FSECT,X,XP,PXDDT3(1,1,IFILL),NSAT,                &
     &       NEQN,NDCRD2,XP,TOPXAT(1,IFILL),LTPXAT(1,IFILL),AA,II,LL,   &
     &       ISATID,                                                    &
     &       LFHIRT,LSURFF,XNC,XPNC,                                    &
     &       PXDDAC(1,1,IFILL),NEQNA,IPTFBS,NPRMAC,.FALSE.,.TRUE.,ONE,  &
     &       DYNTIM,NPERDY,LACCELS,EXTACC,EXACIN,EXACOB,ACCTIM,ACCPER,  &
     &       NPERAC,II(KIACCP),AA(KPACCL),NRAT,XP,3,DUM,DUM)
      HQ=H
      CALL F(MJDST,FSECT,X,XP,PXDDT3(1,1,IFILL),NSAT,                   &
     &       NEQN,NDCRD2,XP,TOPXAT(1,IFILL),LTPXAT(1,IFILL),AA,II,LL,   &
     &       ISATID,                                                    &
     &       LFHIRT,LSURFF,XNC,XPNC,                                    &
     &       PXDDAC(1,1,IFILL),NEQNA,IPTFBS,NPRMAC,.FALSE.,.TRUE.,ONE,  &
     &       DYNTIM,NPERDY,LACCELS,EXTACC,EXACIN,EXACOB,ACCTIM,ACCPER,  &
     &       NPERAC,II(KIACCP),AA(KPACCL),NRAT,XP,DUM,DUM,LQ1,IPSBRN,   &
     &       LQ2,XDDBRN,HQ)
 3500 CONTINUE
! SAVE UPDATED VARIATIONAL EQUATION TIME
      MJDSV=MJDST
      FSECV=FSECT
      IBAKV1=IBACKV+1
      IOVBAK=IORDRV+IBAKV1
! EVALUATE FORCE MODEL PARTIAL DERIVATIVES
      CALL VEVAL(XTEMP,PX,PXDDT3(1,1,IOVBAK-1),AA,II,LL,NSAT,NEQN,      &
     &   .FALSE.,LNDRAG)
      NVSTEP=NVSTEP+1
! INTEGRATE VARIATIONAL EQUATIONS USING CORRECTOR FORMULAS
! POSITIONAL PARTIALS
!
!
      DO 3600 N=1,NEQN3
      PX(N,1)=SUMPX(N,1,IBAKV1)
 3600 END DO
!
!
      DO 3800 I=1,IOVL2
      K=IOVBAK-I
!
      DO 3700 N=1,NEQN3
      PX(N,1)=PX(N,1)+CCPV(I)*PXDDOT(N,K)
 3700 END DO
!
!
 3800 END DO
!
      DO 3900 N=1,NEQN3
      PX(N,1)=PX(N,1)*HV2
 3900 END DO
!
!
      IF(LNDRAG)GO TO 4350
! VELOCITY PARTIALS
!
      DO 4000 N=1,NEQN3
      PX(N,2)=SUMPX(N,2,IBAKV1)
 4000 END DO
!
!
      DO 4200 I=1,IOVL1
      K=IOVBAK-I
!
      DO 4100 N=1,NEQN3
      PX(N,2)=PX(N,2)+CCVV(I)*PXDDOT(N,K)
 4100 END DO
!
!
 4200 END DO
!
      DO 4300 N=1,NEQN3
      PX(N,2)=PX(N,2)*HV
 4300 END DO
!
!
 4350 CONTINUE
!
! START INTEGRATION FOR DELTA STATE PARTIALS (IF NECESSARY)
!
! ROTATE THE PARTIALS FROM TOR TO SATELLITE FRAME IF IDSYST=2
!
      IF(LXSTAT.AND.JPXST.GT.0) THEN

      IF(IDSYST.EQ.2) THEN
! CALL ORBTOR TO GET THE ROTATION MATRIX BASED ON CORRECTED FOR DSTATE P
      CALL ORBTOR(XP(1,1),XP(1,2),DSROT,NSAT)
      ENDIF

           NZERP=36*NSAT
           DO IQP=1,NZERP
             PXR(IQP,1,1,1)=0.D0
             SUMRNP(IQP,1,1,1)=0.D0
           ENDDO
           DO IQP=1,NSAT
             SUM=1.D0/HV2
              SUMRNP(1,1,IQP,1)=SUM*DSROT(1,1,IQP)
              SUMRNP(1,2,IQP,1)=SUM*DSROT(2,1,IQP)
              SUMRNP(1,3,IQP,1)=SUM*DSROT(3,1,IQP)
!
              SUMRNP(2,1,IQP,1)=SUM*DSROT(1,2,IQP)
              SUMRNP(2,2,IQP,1)=SUM*DSROT(2,2,IQP)
              SUMRNP(2,3,IQP,1)=SUM*DSROT(3,2,IQP)
!
              SUMRNP(3,1,IQP,1)=SUM*DSROT(1,3,IQP)
              SUMRNP(3,2,IQP,1)=SUM*DSROT(2,3,IQP)
              SUMRNP(3,3,IQP,1)=SUM*DSROT(3,3,IQP)
!
             SUM=1.D0/HV
              SUMRNP(4,1,IQP,2)=SUM*DSROT(1,1,IQP)
              SUMRNP(4,2,IQP,2)=SUM*DSROT(2,1,IQP)
              SUMRNP(4,3,IQP,2)=SUM*DSROT(3,1,IQP)

              SUMRNP(5,1,IQP,2)=SUM*DSROT(1,2,IQP)
              SUMRNP(5,2,IQP,2)=SUM*DSROT(2,2,IQP)
              SUMRNP(5,3,IQP,2)=SUM*DSROT(3,2,IQP)

              SUMRNP(6,1,IQP,2)=SUM*DSROT(1,3,IQP)
              SUMRNP(6,2,IQP,2)=SUM*DSROT(2,3,IQP)
              SUMRNP(6,3,IQP,2)=SUM*DSROT(3,3,IQP)
!
             SUM=HREMAL/HV2
              SUMRNP(4,1,IQP,1)=SUM*DSROT(1,1,IQP)
              SUMRNP(4,2,IQP,1)=SUM*DSROT(2,1,IQP)
              SUMRNP(4,3,IQP,1)=SUM*DSROT(3,1,IQP)

              SUMRNP(5,1,IQP,1)=SUM*DSROT(1,2,IQP)
              SUMRNP(5,2,IQP,1)=SUM*DSROT(2,2,IQP)
              SUMRNP(5,3,IQP,1)=SUM*DSROT(3,2,IQP)

              SUMRNP(6,1,IQP,1)=SUM*DSROT(1,3,IQP)
              SUMRNP(6,2,IQP,1)=SUM*DSROT(2,3,IQP)
              SUMRNP(6,3,IQP,1)=SUM*DSROT(3,3,IQP)
           ENDDO
      ENDIF
!
!
!
! COMPUTE S-MATRIX
      DO 5550 ISAT=1,NSAT
      IF(LNDRAG)GO TO 4600
      DO 4500 J=1,3
      J1=J+3
      DO 4400 I=1,3
      I1=I+3
      SMAT(I,J)=H2C*VMATRX(I,J,ISAT)
      SMAT(I,J1)=H2C*VMATRX(I,J1,ISAT)
      SMAT(I1,J)=H1C*VMATRX(I,J,ISAT)
      SMAT(I1,J1)=H1C*VMATRX(I,J1,ISAT)
 4400 END DO
      SMAT(J,J)=SMAT(J,J)+ONE
      SMAT(J1,J1)=SMAT(J1,J1)+ONE
 4500 END DO
      GO TO 4900
 4600 CONTINUE
      DO 4800 I=1,3
      DO 4700 J=1,3
      SMAT(I,J)=H2C*VMATRX(I,J,ISAT)
 4700 END DO
      SMAT(I,I)=SMAT(I,I)+ONE
 4800 END DO
 4900 CONTINUE
! INVERT S-MATRIX

      !orig CALL DNVERT(NPV3,SMAT,6,XP)
      !write(6,*) 'cowell: call dnvert NPV3 = ', NPV3

      CALL DNVERT(NPV3,SMAT,6, scratch_array )

! MULTIPLY V-MATRIX TIMES S-MATRIX INVERSE
      DO 5100 I=1,3
      DO 5100 K=1,NPV3
      SUM=ZERO
      DO 5000 J=1,NPV3
      SUM=SUM+VMATRX(I,J,ISAT)*SMAT(J,K)
 5000 END DO
      VMATS(K,1,I)=SUM
 5100 CONTINUE
! CHAIN FORCE MODEL PARTIALS TO EVALUATE VARIATIONAL EQUATIONS.
      IKO=(ISAT-1)*3
      DO 5400 J=1,NPV
      DO 5200 N=1,NEQN
      PXDDT3(N,1+IKO,IOVBAK-1)=PXDDT3(N,1+IKO,IOVBAK-1)                 &
     &  +PX3(N,1+IKO,J)*VMATS(1,J,1)                                    &
     &  +PX3(N,2+IKO,J)*VMATS(2,J,1)                                    &
     &  +PX3(N,3+IKO,J)*VMATS(3,J,1)
      PXDDT3(N,2+IKO,IOVBAK-1)=PXDDT3(N,2+IKO,IOVBAK-1)                 &
     &  +PX3(N,1+IKO,J)*VMATS(1,J,2)                                    &
     &  +PX3(N,2+IKO,J)*VMATS(2,J,2)                                    &
     &  +PX3(N,3+IKO,J)*VMATS(3,J,2)
      PXDDT3(N,3+IKO,IOVBAK-1)=PXDDT3(N,3+IKO,IOVBAK-1)                 &
     &  +PX3(N,1+IKO,J)*VMATS(1,J,3)                                    &
     &  +PX3(N,2+IKO,J)*VMATS(2,J,3)                                    &
     &  +PX3(N,3+IKO,J)*VMATS(3,J,3)
 5200 END DO
!
 5400 END DO
 5550 END DO
      IF(LSVSTP) THEN
         DO IQP=1,NEQN3
            PXDDTH(IQP,NSVCT)=PXDDOT(IQP,IOVBAK-1)
         ENDDO
         IF(IOVBAK.GT.2.AND.NRAT.GE.2) THEN
            CALL PACCSV(NEQN,NSAT,NRAT,PXDDTH(1,NSVCT),                 &
     &                  PXDDOT(1,IOVBAK-NRAT),II(KIACCP))
         ENDIF
      ENDIF
! INCREMENT VARIATIONAL BACK VALUE POINTER
      IBACKV=IBACKV+1
      IBAKV1=IBACKV+1
      IOVBAK=IOVL1+IBACKV
!
! IF A FINITE BURN HAS BEEN INITIATED ON THIS STEP, THEN INTIALIZE
! THE INTEGRATION SUM ASSOCIATED WITH T0
!
! IF A FINITE BURN HAS BEEN TERMINATED ON THIS STEP, THEN INTIALIZE
! THE INTEGRATION SUM ASSOCIATED WITH TLEN ABD INCREMENT THE SUM
! ASSOCIATED WITH T0
!
      IF(LSBURN.OR.LFBURN) THEN
         CALL SUMBRN(LSBURN,LFBURN,NEQN,NEQN3,IORDER,IOL1,IOL2,IOVBAK,  &
     &               IBACKV,PXDDT3,SUMPX,CCP,CCV,HV,HV2,VMATRX(1,1,1),  &
     &               XDDBRS,XDDBRF,IPSBRN)
      ENDIF
! UPDATE SUMS FOR VARIATIONAL EQUATIONS
!
      DO 5600 N=1,NEQN3
      SUMPX(N,2,IBAKV1)=SUMPX(N,2,IBACKV)                               &
     &                 +PXDDOT(N,IOVBAK)
      SUMPX(N,1,IBAKV1)=SUMPX(N,2,IBAKV1)                               &
     &                 +SUMPX(N,1,IBACKV)
 5600 END DO

           IF(NINTOT.GT.0.AND..NOT.LINTF) THEN
      TMOSP(1)=DBLE(MJDSV)+FSECV
      XQP=.001D0+(TMOSP(1)-TMOS0(1))/H
      IQP=XQP
      IQP=IOVL1+IQP
      IF(IQP.LE.0) IQP=1
!  THIS LOOP WORKS IF THERE IS ONLY ONE SATELLITE PER SET
!
      DO J=1,NEQN
          PDDTOS(J,1,IQP,1)=PXDDT3(J,1,IOVBAK)
          PDDTOS(J,2,IQP,1)=PXDDT3(J,2,IOVBAK)
          PDDTOS(J,3,IQP,1)=PXDDT3(J,3,IOVBAK)
      ENDDO

      IF(LBUF) THEN
      CALL NSUMP(NEQNI,IOL1,SUMPOS,PDDTOS,KNSTEPS,H,TMOLD,TMNEW,   &
     &                 SUMPNS,NEQNIM)
       WRITE(IOUT) TMOS0(1),TMOS(1),TMOSP(1),NEQNI,H
       WRITE(IOUT) (SUMXOS(IP,1,1),IP=1,6)
      DO IP=1,IQP
        WRITE(IOUT) XDDTOS(1,IP,1),XDDTOS(2,IP,1),XDDTOS(3,IP,1)
      ENDDO
      NN=NEQNI*3
      NN2=NEQNI*6
      WRITE(IOUT) (SUMPOS(IP,1,1,1),IP=1,NN2)
      DO IP=1,IQP
        WRITE(IOUT) (PDDTOS(JQP,1,IP,1),JQP=1,NN)
      ENDDO


! BEFORE CLEARING UP ARRAYS FILL UP THE FIRST NSTEPS LOCATIONS OF THE
! XDDTOS AND PDDTOS ARRAYS.. ALSO LOAD THE NEW SUMS IN SUMXOS AND SUMPOS
! FILL UP THE FIRST NSTEPS OF THE NEXT BUFFER

      DO I=1,3
      DO J=1,2
      SUMXOS(I,J,1)=SUMXNS(I,J)
      ENDDO
      ENDDO

      DO I=1,NEQNI
      DO J=1,3
      DO K=1,2
      SUMPOS(I,J,K,1)=SUMPNS(I,J,K)
      ENDDO
      ENDDO
      ENDDO

      DO I=1,3
      JJ=0
      DO J=IQPP,IQPE
      JJ=JJ+1
      XDDTOS(I,JJ,1)= XDDTOS(I,J,1)
      ENDDO
      ENDDO

      DO I=1,NEQNI
      DO J=1,3
      JJ=0
      DO K=IQPP,IQPE
      JJ=JJ+1
      PDDTOS(I,J,JJ,1)=PDDTOS(I,J,K,1)
      ENDDO
      ENDDO
      ENDDO


! CLEAR UP ARRAYS IN THE BUFFER


!     write(6,*)' dbg CLEARING UP ARRRAYS '
      DO I=1,3
      DO J=IQPE+1,KNSTEPS
      XDDTOS(I,J,1)=0.D0
      ENDDO
      ENDDO

      DO I=1,NEQNI
      DO J=1,3
      DO K=IQPE+1,KNSTEPS
      PDDTOS(I,J,K,1)=0.D0
      ENDDO
      ENDDO
      ENDDO

! FINALLY RESET TMOS0(1)
      TMOS0(1)=TMNEW

      CLOSE(IOUT)
      LBUF=.FALSE.
      NSEG=NSEG+1
      LBUFOP=.FALSE.
!     IF(NSEG.GT.1) THEN
!     WRITE(FILNAM,FMT='(A13,I7,A4,I2,A7)')'RAPID_INT_SAT',ISATID,      &
!    & '_SEG',NSEG,'.COWELL'
!     write(6,*)' dbg OPEN FILE ',IOUT,NSEG,NEQNI
!     OPEN(IOUT,FILE=FILNAM,STATUS='NEW',FORM='UNFORMATTED')
!     LBUFOP=.TRUE.
!     ENDIF

      ENDIF     !  LBUF

            ENDIF   !   .NOT.LINT
!

!
! REDO THE UPDATE FOR STARTING DELTA STATE PARAMETERS
      IF(LXSTAT.AND.JPXST.GT.0) THEN
         CALL UPDSTA(SUMPX(1,1,IBAKV1),SUMRNP,PXDDOT(1,IOVBAK),         &
     &               NEQN,NSAT,JPXST)
      ENDIF
!
!
! INTEGRATION STEP COMPLETED RETURN TO
!             START OF INTEGRATION LOOP
      GO TO 1000
!
 6000 FORMAT(' EXECUTION TERMINATING IN COWELL DURING SHIFTING')
 6001 FORMAT(' OF "NC" ACCELERATIONS')
 6002 FORMAT(' SATELLITE ID ',I10,' AT TIME ',I10,F15.3)
 6003 FORMAT(' IBCKNC, IORDER, NSAVES, NRAT,IDXDDN ',5I8)
 6011 FORMAT(' OF "NC" INTEGRATION SUMS')
 6013 FORMAT(' IBCKNC, IORDER, NSAVES, NRAT,IDSMXN ',5I8)
      END
