!$DCOMFL
      SUBROUTINE DCOMFL(AA)
!********1*********2*********3*********4*********5*********6*********7**
! DCOMFL           83/11/13            8311.0    PGMR - D. ROWLANDS
!
! FUNCTION:  FILL SOME COMMON BLOCKS WHICH SHARE INFORMATION WITH
!            DYNAMIC ARRAYS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA       I    A    DYNAMIC REAL ARRAY
!
! COMMENTS:  OUTPUT THROUGH VARIOUS COMMON BLOCKS
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      DIMENSION AA(1)
! /CGRAV / CONTAINS SOME FORCE MODEL CONSTANTS
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CCBODY/ESQ,ESQP1,OMESQ
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
! /CLIGHT/ CONSTANTS REQUIRED FOR LIGHT TIME COMPUTATIONS
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/FLUXAU/FLX1AU,XFLUXA
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      DATA ZERO/0.D0/,ONE/1.D0/,X1P5/1.5D0/
      DATA XLK2A/701021.D8/,XLK3A/701031.D8/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! UNLOAD THE PARAMETERS DIRECTLY STORED IN DYNAMIC ARRAYS
! GRAVITY COMMON BLOCK
      IGMPT=KPRMV+IPVAL(IXGM)+IBDGM(ICBDGM)-2
      GM=AA(IGMPT)
      IAEPT=KPRMV+IPVAL(IXSMA)+IBDAE(ICBDAE)-2
      AE=AA(IAEPT)
      IFEPT=KPRMV+IPVAL(IXFLTP)+IBDPF(ICBDPF)-2
      FE=AA(IFEPT)
      XK2=AA(KSTID)
      XK3=AA(KSTID+1)
      XLAM=AA(KSTID+2)
      SIGXK2=ZERO
      SIGXK3=ZERO
      SIGLAM=ZERO
      NTA=NPVAL0(IXTIDE)
      IF(NTA.LT.1) GO TO 1000
      IPTL=IPVAL0(IXTIDE)*3-3
      IPTV=IPVAL0(IXTIDE)-1
      GO TO (100,200,300),NTA
!  1 ADJUSTED TIDE
  100 CONTINUE
      IF(AA(KPRML0+IPTL).GT.XLK2A) GO TO 110
      SIGXK2=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
  110 CONTINUE
      IF(AA(KPRML0+IPTL).GT.XLK3A) GO TO 120
      SIGXK3=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
  120 CONTINUE
      SIGLAM=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
!  2 ADJUSTED TIDES
  200 CONTINUE
      IF(AA(KPRML0+IPTL).GT.XLK2A) GO TO 250
      SIGXK2=ONE/SQRT(AA(KPARVR+IPTV))
      IPTL=IPTL+3
      IPTV=IPTV+1
      IF(AA(KPRML0+IPTL).GT.XLK3A) GO TO 220
      SIGXK3=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
  220 CONTINUE
      SIGLAM=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
  250 CONTINUE
      SIGXK3=ONE/SQRT(AA(KPARVR+IPTV))
      IPTV=IPTV+1
      SIGLAM=ONE/SQRT(AA(KPARVR+IPTV))
      GO TO 1000
!  3 ADJUSTED TIDES
  300 CONTINUE
      SIGXK2=ONE/SQRT(AA(KPARVR+IPTV))
      IPTV=IPTV+1
      SIGXK3=ONE/SQRT(AA(KPARVR+IPTV))
      IPTV=IPTV+1
      SIGLAM=ONE/SQRT(AA(KPARVR+IPTV))
 1000 CONTINUE
      VLIGHT=AA(KSL)
!************DEBUG
!     PRINT 12345
!12345 FORMAT('- DCOMFL*****;GM,AE,FE,XK2,XK3,XLAM,VLIGHT')
!     PRINT 12346,GM,AE,FE,XK2,XK3,XLAM,VLIGHT
!12346 FORMAT(' ',5D25.16)
!************DEBUG END
!   CALCULATE CONSTANTS IN CGRAV
      FE=ONE/FE
      AESQ=AE*AE
      FSQ32=X1P5*AE*FE*FE
      FFSQ32=FE*AE+FSQ32
      RPRESS=FLX1AU/VLIGHT
!    CALCULATE CONSTANTS FROM CGRAV TO USE IN SUBROUTINE ELIPSE
      C1LESQ=(ONE-FE)**2
      ESQ=ONE-C1LESQ
      ESQP1=ESQ+ONE
      OMESQ=ONE-ESQ
!   UNLOAD PARAMETERS INTO  CEARTH
      IAEGPT=KPRMV+IPVAL(IXSMA)+IBDAE(ITBDAE)-2
      AEG=AA(IAEGPT)
      IFGIPT=KPRMV+IPVAL(IXFLTP)+IBDPF(ITBDPF)-2
      FGINV=AA(IFGIPT)
      XH2=AA(KH2)
      XL2=AA(KL2)
      RETURN
      END
