!$DEQN
      SUBROUTINE DEQN(IPD,LONLEQ,MJDSC,FSEC,THT1,Z1,ETA1,EPST1,         &
     &                EPSM1,DELPSI,RPN1,RPN2,RPN3,RPN4,RPN5,RPN6,       &
     &                RPN7,RPN8,RPN9,EQN,SCRTCH,NM)
!********1*********2*********3*********4*********5*********6*********7**
! DEQN             83/04/04            8303.0    PGMR - D. ROWLANDS
!
! FUNCTION:  CALCULATE EQN OF EQUINOX AND- IF LONLEQ IS FALSE,
!            THE PRECESSION NUTATION MATRIX IS CALCULATED.
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   IPD      I    S    12 HR PERIOD OF INTERPOLATION (OUT OF 3 POSSIBLE
!   LONLEQ   I    S    LOGICAL VAIABLE; IF TRUE ONLY THE EQUATION
!                      OF EQUINOX IS CALCULATED
!   MJDSC    I    S    INTEGRAL EPHEMERIS SECOND TIME
!   FSEC     I    A    FRACTIONAL REMAINING SECONDS
!   THT1     I    A    PRECESION ELEMENTS
!   Z1       I    A    PRECESION ELEMENTS
!   ETA1     I    A    PRECESION ELEMENTS
!   EPST1    I    A    NUTATION ELEMENTS
!   EPSM1    I    A    NUTATION ELEMENTS
!   DELPSI   I    A    NUTATION ELEMENTS
!   RPN1     O    A    1,1 POSITION OF NP MATRX
!   RPN2     O    A    2,1 POSITION OF NP MATRX
!   RPN3     O    A    3,1 POSITION OF NP MATRX
!   RPN4     O    A    1,2 POSITION OF NP MATRX
!   RPN5     O    A    2,2 POSITION OF NP MATRX
!   RPN6     O    A    3,2 POSITION OF NP MATRX
!   RPN7     O    A    1,3 POSITION OF NP MATRX
!   RPN8     O    A    2,3 POSITION OF NP MATRX
!   RPN9     O    A    3,3 POSITION OF NP MATRX
!   EQN      O    A    EQUATION OF EQUINOX AT TIMES REQUESTED.
!   SCRTCH        A    MUST BE 5 TIMES THE NUMBER OF OBSERVATIONS
!                      IF RPN IS REQUESTED. IF LONLEQ IS TRUE, SAME
!                      AS THE NUMBER OF OBSERVATIONS.
!   NM       I    S    NUMBER OF OBSERVATIONS
!
! COMMENTS:  NOTE -  PRECESSION-NUTATION ELEMENTS NOT CORRECT UPON
!                    RETURN
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      DOUBLE PRECISION MO2TOD
      DIMENSION FSEC(NM),THT1(NM),Z1(NM)
      DIMENSION ETA1(NM),EPST1(NM),EPSM1(NM),DELPSI(NM)
      DIMENSION EQN(NM),SCRTCH(NM,11),RPN1(NM),RPN2(NM),RPN3(NM)
      DIMENSION RPN4(NM),RPN5(NM),RPN6(NM),RPN7(NM),RPN8(NM),RPN9(NM)
      DIMENSION RTM_P1(3,3),RTM_P2(3,3),RTM_P3(3,3)
      DIMENSION RTM_N1(3,3),RTM_N2(3,3),RTM_N3(3,3)
      DIMENSION MO2TOD(3,3)
      DIMENSION THT2(10),ETA2(10),Z2(10),EPSM2(10),EPST2(10),DELPSI2(10)
      COMMON/CNUTAT/SINEM(1),COSEM(1),SINDP(1),COSDP(1),SINET(1),       &
     &   COSET(1),SINZ(1),COSZ(1),SINTH(1),COSTH(1),SINEA(1),COSEA(1),  &
     &   SDSE(1),SDCE(1),CDSE(1),CDCE(1),SESD(1),SECD(1),CESD(1),       &
     &   CECD(1),SESE(1),SECE(1),CESE(1),CECE(1),CECT(1),SEST(1),       &
     &   CEST(1),SECT(1),CECZ(1),CESZ(1),SECZ(1),SESZ(1),STSZ(1),       &
     &   CTCZ(1),STCZ(1),CTSZ(1),CTCZCE(1),STSZSE(1),CTCZSE(1),         &
     &   CTSZCE(1),STCZCE(1),STSZCE(1),STCZSE(1),CTSZSE(1),SESDSE(1),   &
     &   SESDCE(1),SECDSE(1),SECDCE(1),CESDSE(1),CESDCE(1),CECDSE(1),   &
     &   CECDCE(1),EPSM(1),EPST(1),DPSI(1),Z(1),THTA(1),ETA(1),AK1(1),  &
     &   AK2(1),AK3(1),AK4(1),AK5(1),AK6(1),AK7(1),AK8(1),SUMMY(198)
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      DO J=1,NM
      SCRTCH(J,6)=ETA1(J)
      SCRTCH(J,7)=THT1(J)
      SCRTCH(J,8)=Z1(J)
      SCRTCH(J,9)=EPSM1(J)
      SCRTCH(J,10)=EPST1(J)
      SCRTCH(J,11)=DELPSI(J)
      ENDDO
      GO TO 800
!BELOW IS THE OLD CALCULATION OF THE EQUATION OF EQUINOX
      OFFSET=FSCINP(IPD+1)-MJDSC
      DO 45 I=1,NM
      SCRTCH(I,1)=(OFFSET-FSEC(I))/DTINPD
   45 END DO
      DO 300 N=1,2
      M=1+(IPD+N-2)*66
      IF(N.EQ.1) GO TO 50
      D1=EPST(M-66)-EPST(M)
      DO 460 I=1,NM
      EPST1(I)=EPST1(I)+D1
  460 END DO
      IF(LONLEQ) GOTO 290
      D2=EPSM(M-66)-EPSM(M)
      D3=DPSI(M-66)-DPSI(M)
      D4=Z(M-66)-Z(M)
      D5=THTA(M-66)-THTA(M)
      D6=ETA(M-66)-ETA(M)
      DO 500 I=1,NM
      EPSM1(I)=EPSM1(I)+D2
      DELPSI(I)=DELPSI(I)+D3
      Z1(I)=Z1(I)+D4
      THT1(I)=THT1(I)+D5
      ETA1(I)=ETA1(I)+D6
  500 END DO
      GO TO 100
   50 CONTINUE
      DO 510 I=1,NM
      EPST1(I)=EPST1(I)-EPST(M)
  510 END DO
      IF(LONLEQ) GOTO 280
      DO 520 I=1,NM
      EPSM1(I)=EPSM1(I)-EPSM(M)
      DELPSI(I)=DELPSI(I)-DPSI(M)
      Z1(I)=Z1(I)-Z(M)
      THT1(I)=THT1(I)-THTA(M)
      ETA1(I)=ETA1(I)-ETA(M)
  520 END DO
  100 CONTINUE
! SCRTCH 2-4 IS THE FIRST ROW OF THE EXTRAPOLATED PRECESSION
!  MATRIX; RPPA11, RPPA12, RPPA13.
! SCRTCH 5 IS THE 1,1 ELEMENT OF THE EXTRAPOLATED NUTATION
!  MATRIX; RRA11 TIMES ITS INTERPOLATION FRACTION.
      DO 530 I=1,NM
      SCRTCH(I,2)=AK1(M)-Z1(I)*AK2(M)-ETA1(I)*AK3(M)-THT1(I)*           &
     &          STCZCE(M)
      SCRTCH(I,3)=-AK3(M)-ETA1(I)*AK1(M)+Z1(I)*AK4(M)+                  &
     &          THT1(I)*STCZCE(M)
      SCRTCH(I,4)=-STCZ(M)-THT1(I)*CTCZ(M)+Z1(I)*STSZ(M)
      SCRTCH(I,5)=SCRTCH(I,1)*(COSDP(M)-DELPSI(I)*SINDP(M))
  530 END DO
      IF(N.EQ.2) GO TO 200
!  IF FIRST STORE NOT SUM
      DO 540 I=1,NM
      RPN1(I)=SCRTCH(I,2)*SCRTCH(I,5)
      RPN4(I)=SCRTCH(I,3)*SCRTCH(I,5)
      RPN7(I)=SCRTCH(I,4)*SCRTCH(I,5)
  540 END DO
! SCRTCH 5 IS TEMPORARILY THE 2,1 ELEMENT OF THE EXTRAPOLATED
!  NUTATION MATRIX RPA21 TIMES ITS INTERPOLATED FRACTION.
      DO 550 I=1,NM
      SCRTCH(I,5)=(SDCE(M)+DELPSI(I)*CDCE(M)                            &
     &              -EPST1(I)*SDSE(M))*SCRTCH(I,1)
      RPN2(I)=SCRTCH(I,2)*SCRTCH(I,5)
      RPN5(I)=SCRTCH(I,3)*SCRTCH(I,5)
      RPN8(I)=SCRTCH(I,4)*SCRTCH(I,5)
  550 END DO
! SCRTCH 5 IS TEMPORARILY THE 3,1 ELEMENT OF THE FIRST EXTRAPOLATED
!  NUTATION MATRIX RPA31
      DO 560 I=1,NM
      SCRTCH(I,5)=(SDSE(M)+DELPSI(I)*CDSE(M)+EPST1(I)*                  &
     &            SDCE(M))*SCRTCH(I,1)
      RPN3(I)=SCRTCH(I,2)*SCRTCH(I,5)
      RPN6(I)=SCRTCH(I,3)*SCRTCH(I,5)
      RPN9(I)=SCRTCH(I,4)*SCRTCH(I,5)
  560 END DO
      GO TO 250
  200 CONTINUE
      DO 570 I=1,NM
      RPN1(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN1(I)
      RPN4(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN4(I)
      RPN7(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN7(I)
  570 END DO
!   SCRTCH5 IS TEMPORARILY THE 2,1 ELEMENT OF THE EXTRAPOLATED
!   NUTATION MATRIX TIMES ITS INTERPOLATION FRACTION
      DO 580 I=1,NM
      SCRTCH(I,5)=(SDCE(M)+DELPSI(I)*CDCE(M)                            &
     &   -EPST1(I)*SDSE(M))*SCRTCH(I,1)
      RPN2(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN2(I)
      RPN5(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN5(I)
      RPN8(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN8(I)
  580 END DO
!   SCRTCH5 IS TEMPORARILY THE 3,1 ELEMENT OF THE EXRAPOLATED
!   NUTATION MATRIX TIMES ITS INTERPOLATION FRACTION
      DO 590 I=1,NM
      SCRTCH(I,5)=(SDSE(M)+DELPSI(I)*CDSE(M)                            &
     &   +EPST1(I)*SDCE(M))*SCRTCH(I,1)
      RPN3(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN3(I)
      RPN6(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN6(I)
      RPN9(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN9(I)
  590 END DO
  250 CONTINUE
!   SCRTCH 2-4 ARE THE SECOND ROW OF THE EXTRAPOLATED
!   PRECESION MATRIX
      DO 600 I=1,NM
      SCRTCH(I,2)=AK2(M)+Z1(I)*AK1(M)-ETA1(I)*AK4(M)                    &
     &   -THT1(I)*STSZCE(M)
      SCRTCH(I,3)=-AK4(M)-ETA1(I)*AK2(M)-Z1(I)*AK3(M)                   &
     &   +THT1(I)*STSZSE(M)
      SCRTCH(I,4)=-STSZ(M)-THT1(I)*CTSZ(M)-Z1(I)*STCZ(M)
  600 END DO
!   SCRTCH 5 IS THE 1,2 ELEMENT OF THE EXTRAPOLATED NUTATION
!   MATRIX TIMES ITS INTERPOLATION FRACTION
      DO 610 I=1,NM
      SCRTCH(I,5)=(-CESD(M)+EPSM1(I)*SESD(M)-DELPSI(I)                  &
     &   *CECD(M))*SCRTCH(I,1)
      RPN1(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN1(I)
      RPN4(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN4(I)
      RPN7(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN7(I)
  610 END DO
!   SCRTCH 5 IS TEMPORARILY THE 2,2 ELEMENT OF THE EXTRAPOLATED
!   NUTATION MATRIX TIMES ITS INTERPOLATION FRACTION
      DO 620 I=1,NM
      SCRTCH(I,5)=(AK8(M)+EPSM1(I)*AK6(M)-EPST1(I)*AK7(M)               &
     &   -DELPSI(I)*CESDCE(M))*SCRTCH(I,1)
      RPN2(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN2(I)
      RPN5(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN5(I)
      RPN8(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN8(I)
  620 END DO
!   SCRTCH 5 IS TEMPORARILY THE 3,2 ELEMENT OF THE EXTRAPOLATED
!   NUTATION MATRX TIMES ITS INTERPOLATION FRACTION
      DO 630 I=1,NM
      SCRTCH(I,5)=(AK7(M)+EPST1(I)*AK8(M)-EPSM1(I)*AK5(M)               &
     &   -DELPSI(I)*CESDSE(M))*SCRTCH(I,1)
      RPN3(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN3(I)
      RPN6(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN6(I)
      RPN9(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN9(I)
  630 END DO
!   SCRATCH 2-4 ARE NOW THE 3RD ROW OF THE EXTRAPOLATED PRECESSION
!   MATRX RPPA31-RPPA33
      DO 640 I=1,NM
      SCRTCH(I,2)=CEST(M)+THT1(I)*CECT(M)-ETA1(I)*SEST(M)
      SCRTCH(I,3)=-SEST(M)-ETA1(I)*CEST(M)-THT1(I)*SECT(M)
      SCRTCH(I,4)=COSTH(M)-THT1(I)*SINTH(M)
  640 END DO
!   SCRTCH5 IS TEMPORARILY THE 1,3 ELEMENT OF THE EXTRAPOLATED NUTATION
!   MATRX TIMES ITS INTERPOLATION FRACTION
      DO 650 I=1,NM
      SCRTCH(I,5)=(-SESD(M)-EPSM1(I)*CESD(M)-DELPSI(I)                  &
     &   *SECD(M))*SCRTCH(I,1)
      RPN1(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN1(I)
      RPN4(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN4(I)
      RPN7(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN7(I)
  650 END DO
!   SCRATCH 5 IS TEMPORARILY THE 2,3 ELEMENT OF THE EXTRAPOLATED
!   NUTATION MATRX TIMES ITS INTERPOLATION FRACTION
      DO 660 I=1,NM
      SCRTCH(I,5)=(AK6(M)+EPSM1(I)*AK8(M)-EPST1(I)*AK5(M)               &
     &   -DELPSI(I)*SESDCE(M))*SCRTCH(I,1)
      RPN2(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN2(I)
      RPN5(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN5(I)
      RPN8(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN8(I)
  660 END DO
!   SCRTCH 5 IS TEMPORARILY THE 3,3 ELEMENT OF THE EXTRAPOLATED
!   NUTATION MATRX TIMES ITS INTERPOLATION FRACTION
      DO 670 I=1,NM
      SCRTCH(I,5)=(AK5(M)+EPST1(I)*AK6(M)+EPSM1(I)*AK7(M)               &
     &   -DELPSI(I)*SESDSE(M))*SCRTCH(I,1)
      RPN3(I)=SCRTCH(I,2)*SCRTCH(I,5)+RPN3(I)
      RPN6(I)=SCRTCH(I,3)*SCRTCH(I,5)+RPN6(I)
      RPN9(I)=SCRTCH(I,4)*SCRTCH(I,5)+RPN9(I)
  670 END DO
      IF(N.EQ.1) GO TO 280
      DO 675 I=1,NM
      DELPSI(I)=DELPSI(I)+DPSI(M)
  675 END DO
      GO TO 290
  280 CONTINUE
      DO 680 I=1,NM
      EQN(I)=SCRTCH(I,1)*(COSET(M)-EPST1(I)*SINET(M))
      SCRTCH(I,1)=1.D0-SCRTCH(I,1)
  680 END DO
      GO TO 300
  290 CONTINUE
      DO 690 I=1,NM
      EQN(I)=EQN(I)+SCRTCH(I,1)*(COSET(M)-EPST1(I)*SINET(M))
  690 END DO
  300 END DO
      DO 700 I=1,NM
      EQN(I)=EQN(I)*DELPSI(I)
  700 END DO
  800 CONTINUE
! NEW CODE
       DO J=1,NM
      ETA1(J)=SCRTCH(J,6)
      THT1(J)=SCRTCH(J,7)
      Z1(J)=  SCRTCH(J,8)
      EPSM1(J)=SCRTCH(J,9)
      EPST1(J)=SCRTCH(J,10)
      DELPSI(J)=SCRTCH(J,11)
       CALL VTD_ROTMAT ( 3,  ETA1(J),        RTM_P1   )
       CALL VTD_ROTMAT ( 2, -THT1(J),        RTM_P2   )
       CALL VTD_ROTMAT ( 3,  Z1(J),          RTM_P3   )
       CALL VTD_ROTMAT ( 1, -EPSM1(J),       RTM_N1   )
       CALL VTD_ROTMAT ( 3,  DELPSI(J),      RTM_N2   )
       CALL VTD_ROTMAT ( 1,  EPST1(J) ,      RTM_N3   )
       CALL MULTI_MUL_3 (  6, MO2TOD, RTM_P1,  RTM_P2,   RTM_P3,  &
     &                                RTM_N1,  RTM_N2,   RTM_N3)
       EQN(J)=DELPSI(J)*COS(EPSM1(J))
       RPN1(J)=MO2TOD(1,1)
       RPN2(J)=MO2TOD(1,2)
       RPN3(J)=MO2TOD(1,3)
       RPN4(J)=MO2TOD(2,1)
       RPN5(J)=MO2TOD(2,2)
       RPN6(J)=MO2TOD(2,3)
       RPN7(J)=MO2TOD(3,1)
       RPN8(J)=MO2TOD(3,2)
       RPN9(J)=MO2TOD(3,3)
       ENDDO
! NEW CODE

      RETURN
      END
