!$DRVGPSPHC
      SUBROUTINE DRVGPSPHC(AA, II, NM, ISEQ, ISATID, L1ST, &
                           UI, XSM, DR)
!********1*********2*********3*********4*********5*********6*********7**
! DRVGPSPHC        2017-12-22                    PGMR - JOSEPH NICHOLAS
!
!
! FUNCTION:  DRIVER FOR GPSPHC
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   DR      I/O        CORRECTIONS TO RANGES
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**

      !IMPLICIT REAL(A-H,O-Z), LOGICAL(L)
      IMPLICIT NONE

      ! XGPSTB, XANTSH(4)
      COMMON/PYUA  /XGPSTB,WVL3,VHIGH(3,3,4),VLOW(3,3,4),PYUSQ(5),      &
     &              VISATH(4),VISATL(4),XANTSL(4),XCUTSL(4),XANTSH(4)
      ! NANT_sat, NANT_sta, NANTPT, KANTPS, KANTPS_sat, NANTPS_sat,
      ! NANTPS_sta
      COMMON/APHASE/NANT_sat,NANTPS_sat(999),KANTPS_sat(999),           &
     &              nant_sta,NANTPS_sta(999),KANTPS_sta(999),           &
     &              NANTPT,  NANTPS(999),    KANTPS(999), NANTMT(99),   &
     &              NNUMMT, NXAPHA
      ! KANTYP
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      ! KANTBL
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04

      ! START AUTOMATIC COMMON BLOCK DECLARATIONS
      DOUBLE PRECISION XGPSTB,WVL3,VHIGH,VLOW,PYUSQ,VISATH,VISATL, &
          XANTSL,XCUTSL,XANTSH
      INTEGER NANT_sat,NANTPS_sat,KANTPS_sat,nant_sta,NANTPS_sta, &
          KANTPS_sta,NANTPT,NANTPS,KANTPS,NANTMT,NNUMMT,NXAPHA,KABIAS, &
          KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,KRNM,KRKM,KRKJ,KRIJ,KRKPM, &
          KRRNM,KRRKM,KRRKJ,KRRIJ,KRRKPM,KURNM,KURKM,KURKJ,KURIJ, &
          KURKPM,KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,KPMPXI,KPMPXE,KRA, &
          KRELV,KUHAT,KWORK,KTMPCR,KU,KS0,KS1,KXTP,KPXSXP,KPXDXP, &
          KXUTDT,KRPOLE,KPXPOL,KXDPOL,KOBBUF,KOBSC,KRESID,KSIGMA, &
          KRATIO,KELEVS,KPMPA,KPXSLV,KTPRTL,KFRQOF,KXYZOF,KFRQST, &
          KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,KEBVAL,KEBSIG,KEBNAM, &
          KBTWB,KTBTWA,KBTWD,KPMPE,KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN, &
          KOBOUT,KGRLT1,KGRLT2,KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS, &
          KCHEMR,KCHMOR,KEPOSR,KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS, &
          KSCRTM,KXSTT,KXSTR,KXSS,KRANGT,KRANGR,KCHB1,KCHB2,KCHBV1, &
          KCHBV2,KCHEB,KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI, &
          KQUINF,KBRTS,KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD, &
          KXPMPA,KXL,KXSIG,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS, &
          KDLONF,KDLONS,KPF,KPS,KXOBSV,KXOBSW,KXEDSW,KXSIGW,KPSF,KDNUM, &
          KCNUM,KFCOR,KCOSAR,KSINAR,KSABIA,KSBTM1,KSBTM2,KYAWBS,KVLOUV, &
          KACMAG,KOBSTR,KPRL1,KPRL2,KRL1,KT1SE,KTCP,KRATDR,KFQT1S, &
          KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1,KSV2,KTSLOV,KGLGR1, &
          KGLGR2,KGLFR1,KGLFR2,KARGR1,KARGR2,KARFR1,KARFR2,KRDS1L, &
          KFT1AV,KDFQP,KFREQ1,KFREQ3,KSAVD1,KSAVD2,KANTOU,KFM3CF,KF2CF, &
          KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,KALTWV,KXXBM,KX2PAR, &
          KATIME,KPMPAT,KPMATT,KX2PAT,KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF, &
          KACOF2,KACOF3,KBCOF,KBCOF2,KDDDA,KX2AUX,KX2VPR,KX2VPA,KEXTRA, &
          KVARAY,KATROT,KATPER,KLTAR,KXHOLD,KANTBL,KPHC,KOFDRV,KGNAME, &
          KGRSIZ,KGRCNT,KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV, &
          KANTOR,KW1PU,KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE, &
          KDSDP,KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS, &
          KIMTIM,KIMSAT,KM2VPA,KDCDD,KDWNWT,KDPOR,KC2PAR,KBOUNC,KBPART, &
          NXCA04,KNMP,KINDP,KNDPAR,KNPVCT,KISATN,KISET,KIANTO,KISATO, &
          KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,KMJDEB,KMJDBN, &
          KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,KSSTNA,KMBSAT,KMBSTA, &
          KXKEY,KXVKEY,KXFLAG,KIPNTF,KIPNTS,KNCON,KKF,KIDATB,KNSTLV, &
          KSLVID,KLLBIA,KTMRA1,KTMRA2,KIND1,KTARID,KATARD,KYAWID, &
          KXOBLK,KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC, &
          KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,KANTOF,KYSAT,KMBDEG, &
          KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP,KXNAVP, &
          KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY,KIMKEY,KIMBLK,KIMPRT, &
          KCN110,KCN111,KC110,KC111,NXCI04
      ! END AUTOMATIC COMMON BLOCK DECLARATIONS

      DOUBLE PRECISION, INTENT(INOUT) :: AA(*)
      INTEGER, INTENT(INOUT) :: II(*)
      INTEGER, INTENT(IN) :: NM
      INTEGER, INTENT(IN) :: ISEQ
      INTEGER, INTENT(IN) :: ISATID
      LOGICAL, INTENT(IN) :: L1ST
      DOUBLE PRECISION, INTENT(IN) :: UI(*)
      DOUBLE PRECISION, INTENT(IN) :: XSM(*)
      DOUBLE PRECISION, INTENT(INOUT) :: DR(NM)

      INTEGER :: IANTX, INDEX_SAT, INDEX_ANT, ISUM_SAT, ISUM_STA, IPOFF
      INTEGER :: NDIMA, NDIMZ
      INTEGER :: KTDANT,KTDSAT
      LOGICAL :: L_sat_phc, L_ant_phc

      ! FIND THE PHC ANTENNA FOR THIS GPS SATELLITE
      IF (ISEQ > 0) THEN
          IANTX = NINT(XANTSH(ISEQ))
      ELSE
          RETURN
      END IF

      ! IF A PHASE MAP IS NOT FOUND, THEN SKIP THIS SECTION.
      ! SO IF ONE WANTS TO APPLY THE PHASE CENTER VARIATIONS FOR GPS
      ! SATELLITES, ONE HAS TO DO IT THROUGH THE EXTERNAL PHASE TABLE
      IF (IANTX > 0) THEN
          L_sat_phc = .FALSE.
          L_ant_phc = .FALSE.
          ! THE ANTENNA NUMBER WAS IDENTIFIED IN THE EXTERNAL PHASE TABLE
          ! USE THE EXTERNAL NUMBERS FROM THE TABLE
          IF (NANT_sat > 0) THEN
              CALL GET_INDEX2(ISATID, IANTX, II(KANTYP), NANT_sat, &
                        INDEX_SAT, L_sat_phc)
          END IF
          IF (NANTPT > 0) THEN
              CALL GET_INDEX(IANTX, II(KANTYP+2*(NANT_sat+NANT_sta)), &
                        NANTPT, INDEX_ANT, L_ant_phc)
          END IF

          IF (XGPSTB > 0.0D0 .AND. (L_sat_phc .OR. L_ant_phc)) THEN
              IF (L_ant_phc) THEN
                  ISUM_SAT = SUM(NANTPS_SAT(1:NANT_sat)) + 6*NANT_sat
                  ISUM_STA = SUM(NANTPS_STA(1:NANT_sta)) + 6*NANT_sta
                  IPOFF = KANTPS(INDEX_ANT) + ISUM_SAT + ISUM_STA
                  NDIMA = NINT(AA(KANTBL+IPOFF+3-1))
                  NDIMZ = NINT(AA(KANTBL+IPOFF  -1))
              END IF

              IF (L_sat_phc) THEN
                  IPOFF = KANTPS_sat(INDEX_SAT)
                  NDIMA = NINT(AA(KANTBL+IPOFF+3-1))
                  NDIMZ = NINT(AA(KANTBL+IPOFF  -1))
              END IF

              CALL GPSPHC(NM, XSM, UI, NM, AA(KANTBL+IPOFF+6-1), &
                        NDIMA, NDIMZ, AA(KANTBL+IPOFF-1), L1ST, DR)
          END IF
      END IF

      END SUBROUTINE
