!$DSORT
      SUBROUTINE DSORT(PNAME,IPTRUA,ISATID,STDRG,LREDDR,NREDDR,RTGDRG,  &
     &                 IREDRG,ISTRTD,WTADRG,CTMDRG,IDIM2,IDIM4,IDIMT,KI)
!********1*********2*********3*********4*********5*********6*********7**
! ASORT
!
!
! FUNCTION:
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PNAME   I     A    PARAMETER NAME ARRAY
!   IPTRUA  I     A    POINTERS FROM UNADJUSTED TO ADJUSTED PARAMETERS
!   ISATID  I     A    SATELLITE ID
!   STDRG   I     A    DRAG TIME PERIODS
!   LREDDR  I     A    FLAGS FOR CONSTRAINTS APPLICATION (ISAT)
!   NREDDR  I     A    NUMBER OF CONTINUOUS TIME PERIODS (ISET,ISAT)
!   RTGDRG  O     A    ARRAY OF TIMES
!   IREDRG  0     A    ARRAY OF POINTERS TO ADJUSTED PARAMETERS
!   ISTRTD  I     A    STARTING LOCATION OF CONTINUOUS PERIODS
!   WTADRG  I     A    ARRAY OF WEIGHTS FOR DRAG CONSTRAINTS
!   CTMDRG  I     A    ARRAY OF CORRELATION TIMES FOR DRAG CONSTRAINTS
!   IDIM2   I     S    FIRST DIMENSION OF NREDRD
!   IDIM4   I     S    FOURTH  DIMENSION OF NREDDR
!   IDIMT   I     S    FIRST DIMENSION OF RTDRGG
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION  (A-H,O-Z),LOGICAL(L)
      SAVE
      CHARACTER*8 DRAG,HOLD8
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/KNTSTS/KNTACC(9,40),MKNTAC,KNTDRG,KNTSLR,MAXNGA,MAXNDR,    &
     &              MAXNSR,NXKNTS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/SETIOR/IORDRG,IORSRD,IORGA,IPDDRG,IPDSRD,IPDGA
      COMMON/STARTT/ESSTRT,FSSTRT
      COMMON/STARTV/SSTRTC(200)

      CHARACTER(8)      :: PNAME

      DIMENSION PNAME(2,1),IPTRUA(1),ISATID(1),STDRG(1)
      DIMENSION FSEC(1),IYMD(1),IHM(1),SEC(1)
      DIMENSION LREDDR(1)
      DIMENSION NREDDR(IDIM2,IDIM4)
      DIMENSION ISTRTD(IDIM2,IDIM4)
      DIMENSION RTGDRG(IDIMT,IDIM2,IDIM4)
      DIMENSION IREDRG(IDIMT,IDIM2,IDIM4)
      DIMENSION WTADRG(IDIM2,IDIM4)
      DIMENSION CTMDRG(IDIM2,IDIM4)
! ILOCSC IS LOCAL IT HOLDS THE STARTING LOCATION FOR DRAG IPTRUA FOR EAC
! S/C MAY NEED TO INCREASE IT OR MAKE IT DYNAMIC IN THE FUTURE
      DIMENSION ILOCSC(9999)
      DATA DRAG/'CD      '/
      DATA FSEC/0.D0/
      CHARACTER(8)      :: WRD2
      CHARACTER(8)      :: BLANK
      DATA BLANK/'        '/
      EQUIVALENCE (HOLD8,HOLDR)
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! INITIALIZE ILOCSC TO ZERO
!
      DO 10 I=1,9999
      ILOCSC(I)=0
   10 END DO
!
! DEBUG
!
!     write(6,*)' dbg nsata',nsata
!     do 100 i=1,3
!     do 100 j=1,3
!     do 100 k=1,nsata
!     write(6,*)' ISATID ',ISATID(k)
!     IF(LREDDR(K)) THEN
!     write(6,*)' dbg LREDDR',LREDDR(k),k
!     do 200 ij=1,mkntac
!     if(nreddr(ij,k).gt.0) then
!     write(6,*)' dbg NREDDR',NREDDR(IJ,k),ij,k
!     write(6,*)' dbg ISTRTD',ISTRTD(IJ,k),ij,k
!     write(6,*)' dbg WTADRG',wtadrg(IJ,k),ij,k
!     write(6,*)' dbg CTMDRG',CTMDRG(IJ,k),ij,k
!     endif
!200   continue
!     ENDIF
!100   CONTINUE
!
! DEBUG
!
! FIND THE STARTING LOCATION FOR EACH SATELLITE IN IPTRUA
! LOAD IN LOCAL ARRAY ILOCSC
      J=1
      IEC=IPVAL(IXBISA)
      DO 1001 I=1,IEC
      IF(J.GT.NSATA) GOTO 1001
!      HOLDR=PNAME(1,I)
      HOLD8=PNAME(1,I)
      IF(HOLD8(1:5).NE.DRAG(1:5)) GO TO 1001
!      HOLDR=PNAME(2,I)
      HOLD8=PNAME(2,I)
      IF(IPTRUA(I).LE.0) GO TO 1001
      WRD2=BLANK
      CALL NUMASC(ISATID(J),WRD2,28,.TRUE.)
      IF(PNAME(2,I).EQ.WRD2) THEN
!     WRITE(6,34567) J,INDX,I,PNAME(1,I),PNAME(2,I),IPTRUA(I)
      ILOCSC(J)=I
      J=J+1
      ENDIF
 1001 END DO
!
      WRITE(6,6000)
! LOOP 1000 FOR SATELLITE
!     DO 1000 KI=1,NSATA
      TT1=SSTRTC(KI)
      INDXS=ILOCSC(KI)
      IF(LREDDR(KI)) THEN
      IK0=1
      IK=IK0
      DO 300 JJ=1,IDIM2
      IF(NREDDR(JJ,KI).GT.0) THEN
      NALL=NREDDR(JJ,KI)
      INDXB=ISTRTD(JJ,KI)
      INDXT=INDXB
!      IL=ILOCSC(KI)+INDXB
      IL=ILOCSC(KI)+INDXB-1
      WRITE(6,34569)
      WRITE(6,34570)
      DO 350 IJ=1,NALL
      IF(INDXT.EQ.1) THEN
      T0=TT1
      ELSE
      T0=STDRG(INDXT-1)
      ENDIF
      T1=STDRG(INDXT)
      TREDDR=(T0/2.D0)+(T1/2.D0)
      IREDRG(IJ,IK,KI)=IPTRUA(IL)
      RTGDRG(IJ,IK,KI)=TREDDR
!     WRITE(6,*)' dbg IREDRG ',iredrg(ij,ik,ki),ij,ik,ki,il
!     write(6,*)' dbg times ',t0,t1
!     WRITE(6,*)' dbg RTGDRG ',rtgdrg(ij,ik,ki),ij,ik,ki,il
      ITAG=RTGDRG(IJ,IK,KI)
      CALL YMDHMS(ITAG,FSEC,IYMD,IHM,SEC,1)
      ITAG=SEC(1)
      IHMS=IHM(1)*100+ITAG
      !orig WRITE(6,*)' FOR SATELLITE ',KI,' AND DRAG PARAMETERS'
      WRITE(6,'(A,1x,I8,1x,A)')&
            'FOR SATELLITE ',KI,' AND DRAG PARAMETERS'

      WRITE(6,34571) IREDRG(IJ,IK,KI),IYMD(1),IHMS
      WRITE(6,6000)
      IL=IL+1
      INDXT=INDXT+1
  350 END DO
      IK=IK+1
      ENDIF
  300 END DO
      ENDIF
!1000  CONTINUE
!
! DEBUG
!
! DEBUG
!
      WRITE(6,6000)
      WRITE(6,6000)
      WRITE(6,6000)
      RETURN
 6000 FORMAT(' ')
34567 FORMAT('  ',3I5,3X,A8,3X,A8,I10)
34569 FORMAT('  THE FOLLOWING ADJUSTED PARAMETER NUMBERS WITH ')
34570 FORMAT('  TIME TAGS WILL BE CONSTRAINED TOGETHER:')
34571 FORMAT('  ADJUSTED PARM NUM:',I8,' TIME TAG ',I8,3X,I6)
      END
