!$EMATRX
      SUBROUTINE EMATRX(AA,II,LL,PARML0,PARMV0,PARMVC,MJDSB,FSECB,ETUTC,&
     & LPRTD,NRECS,IUNTMT,OUTARY,NDIMO,ISATID)
!********1*********2*********3*********4*********5*********6*********7**
! EMATRX           84/06/27                      PGMR - WFE
!
! FUNCTION:  CONTROL OUTPUT OF E-MATRIX FILES
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL DATA
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL DATA
!   PARML0   I    A    PARAMETER LABELS
!   PARMV0   I    A    PARAMETER A PRIORI VALUES
!   PARMVC   I    A    PARAMETER CURRENT VALUES
!   MJDSB    I    A    BEGINNING TIME FOR EMATRIX PRINTOUT IN MJDSEC
!   FSECB    I    A    REMAINING SECONDS TO MJDSB
!   ETUTC    I    A    DYNAMIC ARRAY CONTAINING ET-UTC TIME DIFFERENCES,
!                      A1-UTC RATES AND TIME AT WHICH TIME DIFFERENCE
!                      APPLIES
!   LPRTD    I    S    LOGICAL FLAG FOR EMATRIX PRINTOUT CONTROL
!   NRECS    I    S    NUMBER OF RECORDS WRITTEN TO THE EMAT FILE
!   IUNTMT   I    S    EMAT UNIT NUMBER
!   OUTARY   I    A    OUTPUT ARRY FOR TIEOUT OPTION
!   NDIMO    I    S    SECOND DIMENSION OF OUTARY
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/ARCPR /FSECRF,XARCPR
      COMMON/CGLBAR/LGDRAG,NXGLAR
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/G2SINF/G2SVER,G2SDAT,G2SRTM,G2SCOM,TDFVER,TDFRTM,SETCDS,   &
     &              GPCKSM,GPDEG ,GPORD ,XG2SIN
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PARPRO/MPIPRO
      COMMON/TIEOUT/XSCTIE,XSCTRF,YMDRRF,YMDTRF,XTIE,XTIEOU
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
!
      DOUBLE PRECISION,ALLOCATABLE:: PV0(:), PVC(:)
!
      DIMENSION AA(1)
      DIMENSION ETUTC(1),FSEC(1),FSECB(1)
      DIMENSION II(1)
      DIMENSION LL(1)
      DIMENSION MJDSB(1)
      DIMENSION PARML0(3,1),PARMV0(1),PARMVC(1)
      DIMENSION RSCRAT(120)
      DIMENSION OUTARY(6,NDIMO,NSATA),ISATID(NSATA)
      DIMENSION VP(30)
!
      DATA MSCR/60/
      DATA C1/1.0D0/,C0/0.0D0/,C1D6/1.0D6/
      DATA RESLBL/2.0D14/,C599/5.990D13/
      DATA C999/999.0D0/,C1E11/1.0D11/,C100/100.0D0/
!
!**********************************************************************
!* START OF EXECUTABLE CODE *******************************************
!**********************************************************************
!
! COMPUTE START AND END LOCATIONS FOR ARC AND GLOBAL INFORMATION
!
      IARCB =IPVAL0(IXARC)
      IARCE =IARCB +NPVAL0(IXARC)-1
      IGLBB =IPVAL0(IXGLBL)
      IGLBE =IGLBB+NPVAL0(IXGLBL)-1
      NWORDS=NPVAL0(IXARC)+NPVAL0(IXGLBL)
      WRITE(IOUT6,80200) EMTNUM
      WRITE(IOUT9,80200) EMTNUM
!
! OUTPUT DATE AND TIME INFORMATION
!
! TDF DATE/TIME
      ITDFDT=TDFRTM/C1D6
      ITDFTM=MOD(TDFRTM,C1D6)
! IIS DATE/TIME
      IISDT =G2SRTM/C1D6
      IISTM =MOD(G2SRTM,C1D6)
! ARC REFERENCE - CONVERT TIME FROM MJDS IN E.T. TO YMD IN UTC
      CALL UTCET(.FALSE.,1,MJDSRF,FSECRF,FSEC(1),ETUTC)
      CALL YMDHMS(MJDSRF,FSEC(1),IREFDT,IREFTM,REFSEC,1)
      WRITE(IOUT6,80210) ITDFDT,ITDFTM,IISDT,IISTM,IREFDT,IREFTM,REFSEC
      WRITE(IOUT9,80210) ITDFDT,ITDFTM,IISDT,IISTM,IREFDT,IREFTM,REFSEC
      DO 200 ISATNO=1,NSATA
! CONVERT EPOCH TIME FROM MJDS IN E.T. TO YMD IN UTC
      CALL UTCET(.FALSE.,1,MJDSB(ISATNO),FSECB(ISATNO),FSEC(1),ETUTC)
      CALL YMDHMS(MJDSB(ISATNO),FSEC(1),IEPYMD,IEPHM,EPSEC,1)
      WRITE(IOUT6,80212) ISATNO,IEPYMD,IEPHM,EPSEC
      WRITE(IOUT9,80212) ISATNO,IEPYMD,IEPHM,EPSEC
  200 END DO
      WRITE(IOUT6,80215)
      WRITE(IOUT9,80215)
!
! LOOP ON NUMBER OF E-MATRIX OUTPUT FILES REQUESTED
!
      NEMATS=EMTCNT
!
      DO 1000 JEMAT=1,NEMATS
      NRECS =0
      LPRT  =EMTPRT.GT.C0 .AND. JEMAT.EQ.1
      LPRTD =EMTPRT.GT.C1  .AND. LPRT
      IUNTMT=IUNT71+JEMAT-1
      IF(MPIPRO.GT.0) IUNTMT=72
!
! OUTPUT E-MATRIX HEADER RECORD
!
      NRECS=NRECS+1
      NXOT=0
      IF(ABS(XTIE).GT..25D0) NXOT=4+NSATA*(6*NDIMO+1)
      XNOT=DBLE(NXOT)
      CALL EMTHDR(IUNTMT,RSCRAT,.FALSE.,XNOT)
!
! OUTPUT E-MATRIX PARAMETER GROUP IDENTIFIER RECORDS
!
      NRECS=NRECS+2
      CALL EMTGRP(IUNTMT,RSCRAT,RSCRAT(MSCR+1),MSCR)
!
! OUTPUT E-MATRIX LABELS
!
! IF GLOBAL DRAG REQUESTED SWAP AND RENAME DRAG LABELS TO END OF ARC
! ALSO DO CURRENT AND APRIORI VALUES
      IF(LGDRAG) THEN
      IF(NPVAL0(IXDRAG).EQ.0) GOTO 400
! SET INDEX EQUAL TO THE POSITION OF THE FIRST DRAG LABEL
      INDEX=IPVAL0(IXDRAG)
      DO 300 I=1,NPVAL0(IXDRAG)
! SET DRAG LABEL TO TEMP SPACE, CHANGE THE LABEL IN THE TEMP SPACE,
! AND SHIFT OVER THE REST OF THE ARC LABELS. THIS IS DONE FOR EACH
! DRAG LABEL.
      TEMP=PARML0(1,INDEX)
      TEMP2=PARML0(2,INDEX)
      TEMP3=PARML0(3,INDEX)
      TEMPC=PARMVC(INDEX)
      TEMP0=PARMV0(INDEX)
! SAVE OFF SEQUENCE NUMBER
      IASEQ=TEMP/100000
      DMSEQ=DBLE(IASEQ*100000)
      DSEQ=TEMP-DMSEQ
      IF(DSEQ.GT.C999) STOP 56
! ISOLATE DRAG PART SSNNPTFC000
      DALABL=(DMSEQ/C100)-C1E11
! ADD ON SEQUENCE # AND AMOUNT TO GET GLOBAL DRAG
      TEMP=DALABL+DSEQ+C599
!
      DO 100 J=INDEX,NPVAL0(IXARC)-1
      PARML0(1,J)=PARML0(1,J+1)
      PARML0(2,J)=PARML0(2,J+1)
      PARML0(3,J)=PARML0(3,J+1)
      PARMVC(J)=PARMVC(J+1)
      PARMV0(J)=PARMV0(J+1)
  100 END DO
! PUT TEMP (CONVERTED DRAG LABEL) AT END OF ARC LABELS
      PARML0(1,NPVAL0(IXARC))=TEMP
      PARML0(2,NPVAL0(IXARC))=TEMP2
      PARML0(3,NPVAL0(IXARC))=TEMP3
      PARMVC(NPVAL0(IXARC))=TEMPC
      PARMV0(NPVAL0(IXARC))=TEMP0
  300 END DO
      ENDIF
  400 CONTINUE
!
      NLBLS =NWORDS*3+1
      XLBLS=DBLE(NLBLS)
      NRECS =NRECS+1
      IF(ABS(XTIE).LT..25D0) THEN
         WRITE(IUNTMT) XLBLS,                                           &
     &   (PARML0(1,J1),J1=IARCB,IARCE),(PARML0(1,K1),K1=IGLBB,IGLBE),   &
     &   (PARML0(2,J2),J2=IARCB,IARCE),(PARML0(2,K2),K2=IGLBB,IGLBE),   &
     &   (PARML0(3,J3),J3=IARCB,IARCE),(PARML0(3,K3),K3=IGLBB,IGLBE),   &
     &    RESLBL
      ELSE
       XNSATA=NSATA
       NDIMO6=NDIMO*6
         WRITE(IUNTMT) XLBLS,                                           &
     &   (PARML0(1,J1),J1=IARCB,IARCE),(PARML0(1,K1),K1=IGLBB,IGLBE),   &
     &   (PARML0(2,J2),J2=IARCB,IARCE),(PARML0(2,K2),K2=IGLBB,IGLBE),   &
     &   (PARML0(3,J3),J3=IARCB,IARCE),(PARML0(3,K3),K3=IGLBB,IGLBE),   &
     &    RESLBL,YMDTRF,XSCTIE,XNSATA,GM,                               &
     &   (DBLE(ISATID(ISAT)),(OUTARY(IQP,1,ISAT),IQP=1,NDIMO6),       &
     &    ISAT=1,NSATA)
      ENDIF
      IWORD=1
      IF(LPRT) WRITE(IOUT6,80220) IWORD
      IF(LPRT) WRITE(IOUT6,80250)                                       &
     &(PARML0(1,J1),J1=IARCB,IARCE),(PARML0(1,K1),K1=IGLBB,IGLBE)
      IWORD=IWORD+1
      IF(LPRT) WRITE(IOUT6,80220) IWORD
      IF(LPRT) WRITE(IOUT6,80250)                                       &
     &(PARML0(2,J2),J2=IARCB,IARCE),(PARML0(2,K2),K2=IGLBB,IGLBE)
      IWORD=IWORD+1
      IF(LPRT) WRITE(IOUT6,80220) IWORD
      IF(LPRT) WRITE(IOUT6,80250)                                       &
     &(PARML0(3,J3),J3=IARCB,IARCE),(PARML0(3,K3),K3=IGLBB,IGLBE)
!
! OUTPUT CURRENT VALUES FOR PARAMETERS
!
! CONVERT THE PLANOR PARAMETERS TO DEGREES AND DEG/SEC (INPUT UNITS)
      IF(NPVAL0(IXXTRO).GT.0) THEN
      IPT=IPVAL0(IXXTRO)
      NALL=NXALLC*2+7
!     DO 500 J=1,NALL
!     PARMVC(IPT-1+J)=PARMVC(IPT-1+J)/DEGRAD
!500  END DO

!     DO 600 J=1,7
!     IF(J.EQ.1) PARMV0(IPT-1+J)=PARMV0(IPT-1+J)/DEGRAD
!     IF(J.EQ.3) PARMV0(IPT-1+J)=PARMV0(IPT-1+J)/DEGRAD
!     IF(J.EQ.5) PARMV0(IPT-1+J)=PARMV0(IPT-1+J)/DEGRAD
!     IF(J.EQ.2) PARMV0(IPT-1+J)=(PARMV0(IPT-1+J)/DEGRAD)*86400.D0*&
!    &  36525.D0
!     IF(J.EQ.4) PARMV0(IPT-1+J)=(PARMV0(IPT-1+J)/DEGRAD)*86400.D0*&
!    &  36525.D0
!     IF(J.EQ.6) PARMV0(IPT-1+J)=(PARMV0(IPT-1+J)/DEGRAD)*86400.D0
!     IF(J.EQ.7) PARMV0(IPT-1+J)=(PARMV0(IPT-1+J)/DEGRAD)*&
!    &  (86400.D0**2.D0)
!600  END DO
!     K=0
!     M=0
!     DO 601 J=1,NXALLC
!     VP(1+J-1+M)=PARMVC(IPT-1+8+K)/DEGRAD
!     VP(2+J-1+M)=PARMVC(IPT-1+9+K)/DEGRAD
!     K=K+2
!     M=M+1
!601  ENDDO

!     write(6,77770)
!     write(6,77771)PARMV0(IPT-1+1)
!     write(6,77772)PARMV0(IPT-1+2)
!     write(6,77773)PARMV0(IPT-1+3)
!     write(6,77774)PARMV0(IPT-1+4)
!     write(6,77775)PARMV0(IPT-1+5)
!     write(6,77776)PARMV0(IPT-1+6)
!     write(6,77777)PARMV0(IPT-1+7)
!     K=0
!     DO JJJ=1,NXALLC
!     IF(JJJ.GT.6) K=K+6
!     write(6,77778)VP(JJJ+K)
!     write(6,77779)VP(JJJ+1+K)
!     K=K+1
!     ENDDO
      ENDIF

77770 FORMAT(//,1X,' PLANOR VALUES IN THE GEODYN INPUT',  &
     &' SYSTEM ')
77771 FORMAT(1X,' PLANOR1 : ',F20.15)
77772 FORMAT(1X,' PLANOR2 : ',F20.15)
77773 FORMAT(1X,' PLANOR3 : ',F20.15)
77774 FORMAT(1X,' PLANOR4 : ',F20.15)
77775 FORMAT(1X,' PLANOR5 : ',F20.15)
77776 FORMAT(1X,' PLANOR6 : ',F20.15)
77777 FORMAT(1X,' PLANOR7 : ',D20.10)
77778 FORMAT(1X,' PLANOR ACOEF : ',F20.15)
77779 FORMAT(1X,' PLANOR BCOEF : ',F20.15,//)

      ! CONVERT UNITS FOR PLANOR PARAMETER PRINTOUT
      IF (NPVAL0(IXXTRO).GT.0) THEN
      IPLANOR_MIN_INDEX = IPVAL0(IXXTRO)
      IPLANOR_MAX_INDEX = IPVAL0(IXXTRO)-1 + NXALLC*2 + 7
      ALLOCATE(PV0(1:IGLBE),PVC(1:IGLBE))
      DO I=IGLBB,IGLBE
          IF (I >= IPLANOR_MIN_INDEX .AND. I <= IPLANOR_MAX_INDEX) THEN
              PV0(I) = PARMV0(I) / DEGRAD
              PVC(I) = PARMVC(I) / DEGRAD
              IF (.NOT. LINTAX) THEN
                  SELECT CASE (I-IPLANOR_MIN_INDEX+1)
                      CASE (2, 4)
                          ! RA_DOT and DEC_DOT
                          PV0(I) = PV0(I) * 86400.D0 * 36525.D0
                          PVC(I) = PVC(I) * 86400.D0 * 36525.D0
                      CASE (6)
                          ! W_DOT
                          PV0(I) = PV0(I) * 86400.D0
                          PVC(I) = PVC(I) * 86400.D0
                      CASE (7)
                          ! W_DOT_DOT
                          PV0(I) = PV0(I) * 86400.D0**2
                          PVC(I) = PVC(I) * 86400.D0**2
                  END SELECT
              END IF
          ELSE
              PV0(I) = PARMV0(I)
              PVC(I) = PARMVC(I)
          END IF
      END DO
      END IF

      NRECS =NRECS+1
      XWORDS=DBLE(NWORDS)
      IF (NPVAL0(IXXTRO).GT.0) THEN
      WRITE(IUNTMT) XWORDS,                                             &
     &     (PARMVC(J1),J1=IARCB,IARCE),(PVC(K1),K1=IGLBB,IGLBE)
      IF(LPRT) WRITE(IOUT6,80280)
      IF(LPRT) WRITE(IOUT6,80300)                                       &
     &     (PARMVC(J1),J1=IARCB,IARCE),(PVC(K1),K1=IGLBB,IGLBE)
      ELSE
      WRITE(IUNTMT) XWORDS,                                             &
     &     (PARMVC(J1),J1=IARCB,IARCE),(PARMVC(K1),K1=IGLBB,IGLBE)
      IF(LPRT) WRITE(IOUT6,80280)
      IF(LPRT) WRITE(IOUT6,80300)                                       &
     &     (PARMVC(J1),J1=IARCB,IARCE),(PARMVC(K1),K1=IGLBB,IGLBE)
      END IF
!
! OUTPUT A PRIORI VALUES
!
      NRECS =NRECS+1
      XWORDS=DBLE(NWORDS)
      IF (NPVAL0(IXXTRO).GT.0) THEN
      WRITE(IUNTMT) XWORDS,                                             &
     &(PARMV0(J1),J1=IARCB,IARCE),(PV0(K1),K1=IGLBB,IGLBE)
      IF(LPRT) WRITE(IOUT6,80320)
      IF(LPRT) WRITE(IOUT6,80300)                                       &
     &     (PARMV0(J1),J1=IARCB,IARCE),(PV0(K1),K1=IGLBB,IGLBE)
      ELSE
      WRITE(IUNTMT) XWORDS,                                             &
     &(PARMV0(J1),J1=IARCB,IARCE),(PARMV0(K1),K1=IGLBB,IGLBE)
      IF(LPRT) WRITE(IOUT6,80320)
      IF(LPRT) WRITE(IOUT6,80300)                                       &
     &     (PARMV0(J1),J1=IARCB,IARCE),(PARMV0(K1),K1=IGLBB,IGLBE)
      END IF

      IF (NPVAL0(IXXTRO).GT.0)  DEALLOCATE(PV0,PVC)
!
! OUTPUT EMATRIX DATA RECORDS
!
      IF(MPIPRO.GT.0) GOTO 999
      CALL EMTDAT(AA(KSUM1),AA(KSUM2),PARML0,NRECS,IUNTMT,LPRTD)
  999 CONTINUE
      IF(LPARTI) GOTO 1000
!
! ENDFILE AND REWIND CURRENT UNIT
!
      ENDFILE IUNTMT
      REWIND IUNTMT
      WRITE(IOUT6,80100) NRECS,IUNTMT,EMTNUM
 1000 END DO
      RETURN
80100 FORMAT('0',9X,I5,' RECORDS OUTPUT ON UNIT ',I2,                   &
     &   ' FOR E-MATRIX NUMBER',F16.0)
80200 FORMAT('0',4X,33('*')/5X,'E-MATRIX NUMBER ',F16.0/5X,33('*')/1X )
!80210 FORMAT(29X,       'YYMMDD HHMMSS.SSSSSSS'/
!     &  5X, 'TDF RUN DATE/TIME ',6X,I6,1X,I6/
!     &  5X, 'IIS RUN DATE/TIME ',4X,I8,1X,I6/
!     &  5X, 'ARC REFERENCE DATE',6X,I6,1X,I4,F10.7/1X )
80210 FORMAT(29X,       'YYMMDD HHMMSS.SSSSSSS'/                        &
     &  5X, 'TDF RUN DATE/TIME ',6X,I9,1X,I6/                           &
     &  5X, 'IIS RUN DATE/TIME ',6X,I9,1X,I6/                           &
     &  5X, 'ARC REFERENCE DATE',6X,I9,1X,I6,1x,F10.7/1X )
!80212 FORMAT(5X, 'SAT',I2,' EPOCH DATE/TIME   ',I6,1X,I4,F10.7)
80212 FORMAT(5X, 'SAT',I2,' EPOCH DATE/TIME   ',I9,1X,I6,1x,F10.7)
80215 FORMAT('0'/1X )
80220 FORMAT('0'/1X,'E-MATRIX LABELS   WORD(',I1,')'/1X )
80250 FORMAT(1X,8F16.0)
80280 FORMAT('0','CURRENT VALUES FOR PARAMETERS'/1X )
80300 FORMAT(1X,1P,8D15.8)
80320 FORMAT('0','A PRIORI VALUES FOR PARAMETERS'/1X )
      END
