!$ENDITR
      SUBROUTINE ENDITR(AA,II,LL,PARMV,PARMVC,IPTRAU,LCONVG,PERCNT,     &
     &                  LSTNRO)
!********1*********2*********3*********4*********5*********6*********7**
! ENDITR           00/00/00            0000.0    PGMR - MARTIN
!                  84/04/02            0000.0    PGMR - EDDY
!
! FUNCTION:  CONTROL END OF ITERATION PROCESSING
!            . SUMMARIZE ITERATION STATISTICS
!            . COMPUTE ARC ADJUSTMENTS
!            . UPDATE PARAMETER ARRAYS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA       I    A    DYNAMIC ARRAY FOR REAL    DATA
!   II       I    A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL       I    A    DYNAMIC ARRAY FOR LOGICAL DATA
!   PARMV    O    A    ARRAY OF PARAMETER VALUES(ADJUSTED & UNADJ)
!                      PARAMETER VALUE ARRAY WITH UPDATED VALUES
!                      FOR ESTIMATED ARC PARAMETERS AS OUTPUT
!   PARMVC   O         UPDATED VALUES FOR ALL ADJUSTED PARAMETERS
!   IPTRAU        A    POINTER FROM ADJUSTED PARAMETER ARRAY
!                      (PARMVC) TO PARAMETER ARRAY (PARMV)
!   LCONVG   O         TRUE FOR CONVERGENCE OF INNER ITERATION WITHIN
!                      PERCNT %
!   PERCNT   O    S    PERCENT CHANGE OF RMS OF RESIDUALS FOR CURRENT
!                      ITERATION
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION  (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CEBARC/NEBIAS,NBIASE,NXCEBA
      COMMON/CEDIT /EDITX ,EDTRMS,EDLEVL,CONVRG,GLBCNV,EBLEVL,EDITSW,   &
     &              ENPX  ,ENPRMS,ENPCNV,EDBOUN,FREEZI,FREEZG,FREEZA,   &
     &              XCEDIT
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CITERM/MAXINR,MININR,MAXLST,IHYPSW,NXITER
      COMMON/CITERG/MARC,MGLOBL,MGLOBM,                                 &
     &              MGLOCV,NXITRG
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CGLBAR/LGDRAG,NXGLAR
      COMMON/CLVIEW/LNPRNT(18),NXCLVI
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI05/KNOBGL,KNOBWG,KNOBTY,KNOBWY,KNOBST,KNOBWT,KNEBOB,   &
     &              KJSTAT,NXCI05
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CSTATA/RMSTOT,RMSEDT,RMSGLB
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      COMMON/NEWCON/XOK0,XNOK0
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PARPRC/NPROCS,NPROCI(5,10)
      COMMON/PARPRO/MPIPRO
      COMMON/PUNCH /LPNCH ,LPNALL,LPNADJ,LPNITR,NXPUNC
      COMMON/TPARM/MTPARM,MTPRM1,IPS51,IPS52,MTOBS,IT2PRM(2,28000)
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      COMMON/XPARMB/MPARMB,NPARMB,MPOBS,JPAMB,ISKIPE,                   &
     &             ITPARM(5,28000),ISTABP(3,28000),                     &
     &             ISATBP(3,28000),IPRMBF(28000)
      COMMON/ZPARMB/MPARMZ,ITPRMZ(1000),ISTABZ(3,1000),                 &
     &             ISATBZ(3,1000),IPRMPY(1000),IPRMZ(1000),IUSECY(1000)
      COMMON/KNTSTS/KNTACC(9,40),MKNTAC,KNTDRG,KNTSLR,MAXNGA,MAXNDR,    &
     &              MAXNSR,NXKNTS
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/TRAJI/MJDSTR,NTRAJC,MTRAJC,NXTRAJ
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION PARMV(1),PARMVC(1),IPTRAU(1)
      DIMENSION RESID(1),WT(1),WTD(1)
      DIMENSION NXDST(6)
      DIMENSION FSCQE(1),FSCQU(1)
      DIMENSION IYMD(2),IHM(2),SECQ(2)
!
      DATA ZERO/0.0D0/,HUNDRD/1.0D2/
!!!!  DATA LOA/.TRUE./
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! LOKIT WILL ONLY BE TRUE ON THE LAST ITERATION FOR WHICH DATA IS BEING
! REDUCED. IN RUNS WITH TRAJECORY FILES, LSTNRO WILL BE TRUE ON THE
! LAST ITERATION FOR WHICH DATA IS BEING PROCESSED AND LSTINR WILL BE
! FALSE. FOR RUNS WITHOUT TRAJECTORY FILES LSTNRO WILL ALWAYS BE FALSE
! AND DATA WILL BE PROCESSED ON LSTINR
      LOKIT=.FALSE.
      IF(LSTINR.AND..NOT.LSTNRO) LOKIT=.TRUE.
      IF(.NOT.LSTINR.AND.LSTNRO) LOKIT=.TRUE.
!
      L38=.FALSE.
      IF(LOKIT) THEN
        DO I=1,28000
          IF(ITPARM(1,I).EQ.65) THEN
            L38=.TRUE.
!!!!        WRITE(6,78912) I,(ISATBP(J,I),J=1,3),ITPARM(2,I),ITPARM(3,I)
78912       FORMAT(' ENDITR ; I,SATS,TMS ',6I12)
            MJDQ=ITPARM(2,I)
            FSCQE(1)=0.184D0
            FSCQU(1)=0.D0
!!!!!       CALL UTCET(.FALSE.,1,MJDQ,FSCQE,FSCQU,AA(KA1UT))
            CALL YMDHMS(MJDQ,FSCQU,IYMD(1),IHM(1),SECQ(1),1)
            IYMD(1)=MOD(IYMD(1),1000000)
            MJDQ=ITPARM(3,I)
!!!!!       CALL UTCET(.FALSE.,1,MJDQ,FSCQE,FSCQU,AA(KA1UT))
            MJDQ=ITPARM(3,I)
            CALL YMDHMS(MJDQ,FSCQU,IYMD(2),IHM(2),SECQ(2),1)
            IYMD(2)=MOD(IYMD(2),1000000)
            WRITE(36,7000) I,(ISATBP(J,I),J=1,3),ITPARM(4,I),IYMD(1),     &
     &                      IHM(1),SECQ(1),IYMD(2),IHM(2),SECQ(2)
7000        FORMAT(5I10,2(2X,I6,1X,I4,1X,F10.1))
          ENDIF
        ENDDO
        IF(L38) REWIND 36
        IF(L38) REWIND 37
        IF(L38) CALL M38
      ENDIF
!
!
      PPARM=0.D0
      IF(NPVAL0(IXRSEP).GE.1) THEN
        PPARM=PARMV(IPVAL(IXRSEP))
      ENDIF
      IF(PPARM.GT.0.D0.AND.XNOK0.GT..1D0) THEN
         INOK0=XNOK0+.01D0
         WRITE(6,6000) INOK0
         WRITE(6,6001)
         WRITE(6,6002) PPARM
 6000    FORMAT(' FANTOM PARAMTER BEING USED TO STABILIZE ',I5)
 6001    FORMAT(' NEAR ZERO CROSSOVER EQUATIONS')
 6002    FORMAT(' CUTOFF IS ',F10.4,' METERS')
      ENDIF
!
!
! SUM INTO THE GLOBAL STATISTICAL SUMS ON THE LAST INNER ITERATION
      IF(LOKIT) CALL SUMARC(AA,II,LL)
! DISPLAY THE ARC STATISTICAL SUMMARY
      CALL SUMRIZ  (AA(KTYMEA),AA(KTYRMS),AA(KWTMTY),AA(KWTYRM),        &
     &   II(KNOBTY),II(KNOBWY),AA(KOBTYP),AA(KTMEAN),AA(KTRMS ),        &
     &   AA(KWMEAN),AA(KWTRMS),AA(KWTRND),II(KNOBST),II(KNOBWT),        &
     &   AA(KDSCRP),.FALSE.,LOKIT   )
! ARC CONVERGENCE TEST
      RMSDIF=ABS(RMSEDT-EDTRMS)
      if(rmsedt.le.0.D0) then
      rmschk=0.D0
      else
      RMSCHK=RMSDIF/RMSEDT
      endif
! SAVE THE EDITING RMS AND RECOMPUTE THE EDITING LEVEL
      EDTRMQ=EDTRMS
!     EDTRMS=RMSEDT
      if(rmsedt.gt.0.D0) EDTRMS=RMSEDT
      EDLEVL=EDITX *EDTRMS
      IF(NBIASE.GT.0.AND..NOT.LNPRNT(11)) CALL EBPRNT(AA(KEBVAL),       &
     &               AA(KEBSIG),AA(KEBNAM),AA(KDSCRP),II(KJSTAT),       &
     &               AA(KISATN),II(KMJDEB),AA(KFSEB1),          &
     &               AA(KFSEB2))
!  TRANSFORM PART OF NORMAL MATRIX PERTAINING TO SATELLITE ELEMENTS TO
!  REQUESTED SYSTEM OF ADJUSTMENT AND/OR ZERO OUT ROWS AND COLUMNS
!  ASSOCIATED WITH NON ADJUSTED ELEMENTS
      CALL ZROADJ(AA(KSUM1),AA(KSUM2),AA(KXEPOC),LL(KLADEL),II(KIELMT))
!
      LPROBQ=.FALSE.
      LPROBR=.FALSE.
      LPROBT=.FALSE.
      NDELP=0
      NDELT=0
!
      IF(LGPS.AND.NAMBBH.GT.0.AND.NCYCB.GT.0) THEN
         IAPARM=NPVAL0(IXARC)
         IF(NINNER.EQ.1) CALL MATCHB(AA(KPRML0),AA(KPRSG0),AA(KPARVR),  &
     &                               LPROBQ)
         CALL CONCYC(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                &
     &               AA(KSUM1),AA(KSUM2),AA(KPDLTA),AA(KPRMVC),AA,      &
     &               LL(KLAVOI))
      ENDIF
!!!!  IF(LOA) THEN
        IAPARM=NPVAL0(IXARC)
        CALL CONPT(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                  &
     &             AA(KSUM1),AA(KSUM2),AA(KPDLTA),AA(KPRMVC),AA,        &
     &             LL(KLAVOI),II(KISATN),NSATA,II(KATSAT))
!!!!    ENDIF

! DSTATE CONSTRAINTS
      INQUIRE(FILE='fort.62',EXIST=LEXIST)
      IF(LEXIST) THEN
      IF(NPVAL0(IXDXYZ).GT.0) THEN
      JNXSTA=KXSTAT
      JTXSTA=KTXSTA
      CALL RDLRDS(PARMVC,AA(JTXSTA),II(JNXSTA),NXDST,ISTRTD,NSETA,      &
     & WTD,AA)
         IAPARM=NPVAL0(IXARC)
      CALL CDCONST(AA(KPMPA),RESID,WTD,IAPARM,MAPARM,1,                 &
     &         AA(KSUM1),AA(KSUM2),AA(KPDLTA),PARMVC,LL(KLAVOI),        &
     &         NXDST,ISTRTD)
      ENDIF
      ENDIF
! DSTATE CONSTRAINTS
!
       CALL QCONS( MAPARM, AA(KSUM1), AA(KSUM2), AA(KSIGSP),     &
     &             II(KBSPLN), II(KSSPLN), AA(KQUINF),IUER   )

!
! CHECK FOR AMBIGUITY BIASES WITH LESS THAN THE MINIMUM
! NUMBER OF OBSERVATIONS
      IF(LGPS.AND.NAMBBH.GT.0) THEN
        DO IQP=1,NAMBBH
          IF(ITPARM(4,IQP).LT.MPOBS.AND.ITPARM(5,IQP).GT.0) THEN
!           LPROBR=.TRUE.
            ITPARM(5,IQP)=-1
            NDELP=NDELP+ITPARM(4,IQP)
          ENDIF
        ENDDO
      ENDIF
!
! CHECK FOR TROP BIASES WITH LESS THAN THE MINIMUM
! NUMBER OF OBSERVATIONS
      IF(MTPARM.GT.0) THEN
         DO IQP=1,MTPARM
           IF(IT2PRM(1,IQP).LT.MTOBS.AND.IT2PRM(2,IQP).GT.0) THEN
               LPROBT=.TRUE.
               IT2PRM(2,IQP)=-1
               NDELT=NDELT+IT2PRM(1,IQP)
           ENDIF
         ENDDO
      ENDIF
!
! IF AMBIGUITY BIASES HAD PROBLEMS, THEN THIS CAN LEAD
! TO PROBLEMS WITH CICLE SLIP BIASES
!
! FIRST CHECK THE FIRST CYCLE SLIP BIAS IN EACH CHAIN
      IF(NCYCB.GT.0) THEN
         DO IQP=1,NCYCB
           IF(IUSECY(IQP).GT.0.AND.IPRMPY(IQP).GT.0) THEN
              IF(ITPARM(5,IPRMPY(IQP)).LE.0) THEN
                 LPROBQ=.TRUE.
                 IUSECY(IQP)=-1
              ENDIF
           ENDIF
!
! THEN CHECK THE OTHER CYCLE SLIP BIASES IN EACH CHAIN
           IF(IUSECY(IQP).GT.0.AND.IPRMZ(IQP).GT.0) THEN
              JQP=IPRMZ(IQP)-IPVAL0(IXBISA)+1-NAMBBH
              IF(IUSECY(JQP).LE.0) THEN
                 LPROBQ=.TRUE.
                 IUSECY(IQP)=-1
              ENDIF
           ENDIF
         ENDDO
      ENDIF
      LCONVG=RMSCHK.LE.CONVRG
!!!!  LCONVG=.FALSE.
!
! IF THERE ARE PROBLEMS WITH AMBIGUITY, TROP OR CYCLE
! SLIP BIASES THEN NO AJUSTEMENT WILL BE PERFORMED
! ON THIS ITERATION (THE SAME BIASES WILL NOT CAUSE
! A PROBLEM ON THE NEXT ITERATION BECAUSE DATA WILL
! HAVE BEEN DELETED).
!
! IF THERE NOT AN ADJUSTMENT THEN DO NOT USE THE
! RMS OF THIS ITERATION AS A EDIT LEVEL FOR THE
! NEXT ITERATION; ALSO BUMP UP THE NUMBER OF
! ITERATIONS REQUESTED BY USER
!
         IF(MTYPE.EQ.31) GOTO 200
      IF(MPIPRO.GT.0) GO TO 200
      IF(LPROBQ.OR.LPROBR.OR.LPROBT) THEN
        WRITE(6,10001)
        WRITE(6,10002)
        IF(LPROBQ) WRITE(6,10003)
        IF(LPROBR) WRITE(6,10004) MPOBS
        IF(LPROBT) WRITE(6,10014) MTOBS
        IF(.NOT.LOKIT) THEN
          WRITE(6,10005)
          WRITE(6,10006)
          LADJCI=.FALSE.
          EDTRMS=EDTRMQ
          EDLEVL=EDITX *EDTRMS
          MININR=MININR+1
          MAXINR=MAXINR+1
          LCONVG=.FALSE.
        ELSE
!
!  IF THERE IS NO ADJUSTMENT ON THE LAST ITERATION SOME
!  OF THE SUMMARY COMPUTATIONS WILL FAIL. SO SKIP THEM
!  BY CALLING ENDJOB EARLY
           WRITE(6,10007)
           WRITE(6,10008)
           CALL ENDJOB(AA,II,LL)
        ENDIF
      ENDIF
  200 CONTINUE
! DO NOT ALLOW CONVERGENCE IF THERE WAS NO ADJUSTMENT
! ON THE PREVIOUS ITERATION
      IF(.NOT.LADJPI) LCONVG=.FALSE.
      PERCNT=CONVRG*HUNDRD
      IF(.NOT.LCONVG) GO TO 100
      MAXINR=MIN(MAX(MININR,NINNER+1),MAXINR)
      WRITE(IOUT6,10000) PERCNT
      WRITE(IUNT88,10000) PERCNT
      ILINE6=ILINE6+3
  100 CONTINUE
!
      IF(.NOT.LOKIT) GO TO 300
!!!
!!!   JTW NOV2014
!!!   IF EMATRIX ISNT SELECTED, SHOULD NOT CALL GA9PCN OR
!!!   DRGPCN UNTIL ESTIMA
!!!
      IF(EMTNUM.LE.ZERO) GOTO 300
      IAPARM=NPVAL0(IXARC)
      CALL CONCLK(NSATA,AA(KPRML0),AA(KPRMV0),AA(KPRMVC),AA(KSUM1),     &
&                 AA(KSUM2),AA(KPMPA),IAPARM,MAPARM,AA(KPDLTA),         &
&                 LL(KLAVOI))
!
! AT THIS POINT UPDATE THE NORMAL MATRIX FOR GENERAL ACCELERATION
! AND DRAG CONSTRAINTS
      IAPARM=NPVAL0(IXARC)
! FOR GENERAL ACCELERATION CONSTRAINT
      IDIM1=MKNTAC
!       print*,mkntac, iaparm
!       print*,(kntacc(jjj,1),jjj=1,9)
!       stop
      IF(IDIM1.GT.0) THEN
      IDIM4=NSATA
      IDIMT=MAXNGA
      DO 199 IJ=1,MSETA
        IPXQ=II(KJSPFR+(IJ-1)*9+7)
!       CALL ASORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ),LL(KLRDGA),&
!    &           II(KNRDGA),AA(KTGACC),II(KIRDGA),II(KSTRTA),AA(KWTACC),&
!    &           AA(KTMACC),IDIM1,IDIM4,IDIMT,IJ)
!       CALL GA9PCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                 &
!    &            SUM1,SUM2,PDELTA,PARMVC,II(KNRDGA),LL(KLRDGA),        &
!    &            II(KIRDGA),AA(KWTACC),AA(KTMACC),AA(KTGACC),IDIM1,    &
!    &            IDIMT,IDIM4,IJ,AA,LL(KLAVOI),II(KWEMGA))
        CALL ASORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ),LL(KLRDGA),&
     &           II(KNRDGA),AA(KTGACC),II(KIRDGA),II(KSTRTA),AA(KWTACC),&
     &           AA(KTMACC),IDIM1,IDIM4,IDIMT,IJ)
        CALL GA9PCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                 &
     &            AA(KSUM1),AA(KSUM2),AA(KPDLTA),AA(KPRMVC),II(KNRDGA), &
     &            LL(KLRDGA),II(KIRDGA),AA(KWTACC),AA(KTMACC),          &
     &            AA(KTGACC),IDIM1,IDIMT,IDIM4,IJ,AA,LL(KLAVOI),        &
     &            II(KWEMGA))
 199  ENDDO
      ENDIF
! FOR DRAG CONSTRAINTS
      IAPARM=NPVAL0(IXARC)
      IDIM4=NSATA
      IDIM2=KNTDRG
      IF(IDIM2.GT.0) THEN
      IDIMT=MAXNDR
      DO 201 IJ=1,MSETA
      IPXQ=II(KJSPFR+(IJ-1)*9+2)
      CALL DSORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ)  ,LL(KLRDDR),&
     &           II(KNRDDR),AA(KTGDRG),II(KIRDRG),II(KSTRTD),AA(KWTDRG),&
     &           AA(KTMDRG),IDIM2,IDIM4,IDIMT,IJ)
      CALL DRGPCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                   &
     &            AA(KSUM1),AA(KSUM2),AA(KPDLTA),AA(KPRMVC),II(KNRDDR), &
     &                                               LL(KLRDDR),        &
     &            II(KIRDRG),AA(KWTDRG),AA(KTMDRG),AA(KTGDRG),IDIM2,    &
     &            IDIMT,IDIM4,IJ,LL(KLAVOI),II(KWEMDR),1)
  201 ENDDO
      ENDIF
! OUTPUT E-MATRIX FILE IF REQUESTED
      IF(EMTNUM.LE.ZERO) GO TO 300
      LPRTD=.FALSE.
      NRECS=0
      NDIMO=MAPARM+1
      CALL EMATRX(AA,II,LL,AA(KPRML0),AA(KPRMV0),AA(KPRMVC),II(KMJDSB), &
     &            AA(KFSECB),AA(KA1UT),LPRTD,NRECS,IUNTMT,AA(KTIEOU),   &
     &            NDIMO,II(KISATN))
! PARTITIONED MATRIX SUMMATION MUST BE COMPLETED.
      IF(.NOT.LPARTI) GOTO 299
      IF(NBIASE.GT.0.OR.NPROCS.LE.1) THEN
      CALL SMPART(AA,AA(KPMPA),MAPARM,AA(KSUM1),AA(KPDLTA),AA(KTBTWA),  &
     & LPRTD,NRECS,IUNTMT)
      ELSE
      CALL SMPRT2(AA,AA(KPMPA),MAPARM,AA(KSUM1),AA(KPDLTA),AA(KTBTWA),  &
     & LPRTD,NRECS,IUNTMT)
      ENDIF
  299 CONTINUE
! IF GLOBAL DRAG IS REQUESTED PARAMETER VALUES ARE OUT OF ORDER
! SO TERMINATE THE PROGRAM AFTER CREATION OF EMAT.
      IF(MPIPRO.GT.0) RETURN
      IF(LGDRAG) CALL ENDJOB(AA,II,LL)

      IF(LGPS.AND.LNOARC) THEN
      IF(LPNCH .AND. (LPNITR .OR. LOKIT))                               &
     & CALL CRDPUN(AA    ,II    ,LL    ,NARC  ,NGLOBL,NINNER,           &
     &          AA(KPRMVC),AA(KPRSG0),LL(KLAFRC),II(KIPDFR),II(KIORFR), &
     &          II(KITACC),II(KISATN),II(KNSAT ),AA(KSTDRG),AA(KSTSRD), &
     &          AA(KSTACC),AA(KA1UT ),II(KPTRUA),II(KINDPI),II(KIPOLC), &
     &          AA(KPUTBH),II(KIELMT),II(KISTNO),II(KICRD ),AA(KPRML0), &
     &          II(KITACX),II(KMBSAT),II(KMBSTA),II(KICNL2),II(KICNH2), &
     &          II(KICNV),AA(KSAVST))
!dep new  output unit 9
      CALL ESTIMA(AA,II,LL,AA(KSUM1 ),AA(KSUM2 ),AA(KPDLTA),AA(KPRMV0), &
     &          AA(KPRMVP),AA(KPRMVC),AA(KPRMSG),AA(KPARVR),AA(KPNAME), &
     &          AA(KSATCV),II(KPTRAU),AA(KPRSG0),LOKIT)
      IF(NTRAJC.LE.0)   CALL ENDJOB(AA,II,LL)
      GO TO 301
      ENDIF

      IF(.NOT.LADJCI) GO TO 700

  300 CONTINUE

      IF(.NOT.LADJCI) GO TO 700

! COMPUTE THE ARC PARAMETER ADJUSTMENT
      CALL ESTIMA(AA,II,LL,AA(KSUM1 ),AA(KSUM2 ),AA(KPDLTA),AA(KPRMV0), &
     &          AA(KPRMVP),AA(KPRMVC),AA(KPRMSG),AA(KPARVR),AA(KPNAME), &
     &          AA(KSATCV),II(KPTRAU),AA(KPRSG0),LOKIT)
  301 CONTINUE
! UPDATE PARAMETER VALUE ARRAY FROM CURRENT PARAMETER VALUES ARRAY
      IF(NPVAL0(IXARC).LE.0) GO TO 700
      NPADJ=NPVAL0(IXARC)
!***** BEGIN DEBUG *****
!     PRINT 96345,NPADJ,(IPTRAU(J),J=1,NPADJ)
!96345 FORMAT(' ENDITR-NPADJ,IPTRAU',15I4)
!***** END DEBUG *****
      DO 650 J=1,NPADJ
      IF(IPTRAU(J).LE.0) GO TO 650
      PARMV(IPTRAU(J))=PARMVC(J)
  650 END DO
  700 CONTINUE
      LADJPI=LADJCI
      LADJCI=.TRUE.
! PUNCH ARC SETUP DECK
      IF(LPNCH .AND. (LPNITR .OR. LOKIT))                               &
     & CALL CRDPUN(AA    ,II    ,LL    ,NARC  ,NGLOBL,NINNER,           &
     &          AA(KPRMVC),AA(KPRSG0),LL(KLAFRC),II(KIPDFR),II(KIORFR), &
     &          II(KITACC),II(KISATN),II(KNSAT ),AA(KSTDRG),AA(KSTSRD), &
     &          AA(KSTACC),AA(KA1UT ),II(KPTRUA),II(KINDPI),II(KIPOLC), &
     &          AA(KPUTBH),II(KIELMT),II(KISTNO),II(KICRD ),AA(KPRML0), &
     &          II(KITACX),II(KMBSAT),II(KMBSTA),II(KICNL2),II(KICNH2), &
     &          II(KICNV),AA(KSAVST))
      IF(ICLINK.GT.0.AND..NOT.LOKIT) MAPARM=MAPARM+1
      RETURN
!10000 FORMAT(1H0,53X,'RMS HAS CONVERGED WITHIN',F16.4,' PERCENT'/1H )
10000 FORMAT(///3(' **********************************************',    &
     &   '**********************'/)/                                    &
     &    3X,'RMS HAS CONVERGED WITHIN',F16.4,' PERCENT'/               &
     &   3(' **********************************************',           &
     &   '**********************'/)///)
10001 FORMAT(' WARNING: THERE WILL BE NO ADJUSTMENT ON THIS ITERATION')
10002 FORMAT(' FOR THE FOLLOWING REASON(S):')
10003 FORMAT('  CYCLE SLIP BIASES COULD NOT BE LINKED TO PASSES')
10004 FORMAT('  AT LEAST 1 PASS OF DATA CONTAINED LESS THAN ',I3,' PTS')
10005 FORMAT('  THE AFFECTED DATA WILL BE DELETED ON SUBSEQUENT ')
10006 FORMAT('  ITERATIONS ')
10007 FORMAT(' SINCE THIS IS THE LAST ITERATION AND NO ADJUSTMENT')
10008 FORMAT(' IS BEING PERFORMED, NO SUMMARY OUTPUT WILL BE GIVEN')
10014 FORMAT('  AT LEAST ONE TROP PARM HAD FWERE THAN ',I3, 'PTS')
      END
