!$ENDJOB
      SUBROUTINE ENDJOB(AA,II,LL)
!********1*********2*********3*********4*********5*********6*********7**
! ENDJOB           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:  END NORMAL IIE EXECUTION (CLOSE OBSERVATION OUTPUT FILE IF
!            NORMAL POINTS HAVE BEEN GENERATED).
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA       I    A    REAL DYNAMIC ARRAY
!   II       I    A    INTEGER DYNAMIC ARRAY
!   LL       I    A    LOGICAL DYNAMIC ARRAY
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      CHARACTER*132   LINE
      COMMON/CGLBAR/LGDRAG,NXGLAR
      COMMON/CKOUNT/KNTBLK,KSEGMN,KNTOBS,KZROBS
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORBNF/MAXINF,NORBNF,INFSTA(15),INFNDX(15),INFSTR,INFSTP,  &
     &              INFRT ,NXCORB
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      DIMENSION AA(1),II(1),LL(1)
!
      DATA ZERO/0.0D0/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!
      if( maxinf.gt.0) call orbend
!
! IF GLOBAL DRAG OR PARTITIONED EMAT RUN
!
      IF(LGDRAG.AND.(EMTNUM.GT.ZERO)) THEN
         WRITE(IOUT9,16000)
      ELSE
         IF(LPART) WRITE(IOUT9,15000)
      ENDIF
!
! CLOSE OBSERVATION OUTPUT FILE IF NORMAL POINTS HAVE BEEN GENERATED.
!
      IF(MWIDTH.GT.0.OR.LSIMDT) CALL BLKHDR(AA(KOBOUT),II(KNDBUF),      &
     &    AA(KOBBUF),0)
      JLINE6=ILINE6+3
      IF(JLINE6.LE.MLINE6) GO TO 1000
      IPAGE6=IPAGE6+1
      JLINE6=4
      WRITE(IOUT6,10000) IPAGE6
 1000 CONTINUE
      IF(LGDRAG.AND.(EMTNUM.GT.ZERO)) THEN
         WRITE(IOUT6,16000)
      ELSE
         IF(LPART) WRITE(IOUT6,15000)
      ENDIF
!
! END AND REWIND UNIT 88 - ERROR MESSAGES FOR TOPEX EXPERT SYSTEM
!
      ENDFILE IUNT88
      REWIND IUNT88
!
! WRITE UNIT88 INFORMATION TO THE END OF UNIT9
!
      WRITE(IOUT9,*)'***** UNIT88 FOR TOPEX EXPERT SYSTEM ******'
 2000 READ(IUNT88,2001,END=2003)LINE
 2001 FORMAT(BZ,1X,A132)
      WRITE(IOUT9,2002)LINE
 2002 FORMAT(1X,A132)
      GO TO 2000
 2003 WRITE(IOUT9,2002)LINE
!
      WRITE(IOUT6,20000)
      ILINE6=JLINE6
!
! OUTPUT GEODYN INTERNAL REFERENCE TIME FOR THIS RUN
!
      WRITE(IOUT6,20010)TGTYMD,TMGDN1
      WRITE(IOUT6,20011)

      OPEN(UNIT=55,FILE='SATG',STATUS='NEW',FORM='FORMATTED')
      WRITE(55,*)'OK'
      CLOSE(55)
!
! DISPLAY NUMBER OF ZERO OBS IF ANY
!
      IF(KZROBS.GT.0) WRITE(IOUT6,20020) KZROBS
!
! CALL EXIT TO TERMINATE RUN NORMALLY
!
          CALL EXIT

10000 FORMAT('1',109X,'UNIT  6 PAGE NO.',I6)
15000 FORMAT('** PARTITIONED EMAT RUN - NO ARC ADJUSTMENT WAS DONE ON', &
     &' THE LAST INNER ITERATION.')
16000 FORMAT('** GLOBAL DRAG EMAT RUN - RUN IS TERMINATED AFTER ',      &
     &'CREATION OF EMAT.')
20000 FORMAT('0NORMAL END OF GEODYN II-E EXECUTION.'/1X )
20010 FORMAT('GEODYN REFERENCE TIME FOR THIS RUN IS:',F10.1,            &
     & 1X,'JD= ',F10.1)
20011 FORMAT(' THE TIME ON ALL IIE OUTPUT FILES REFER TO ',             &
     &       'THE DEFAULT REFERENCE TIME 2430000.5')
20020 FORMAT(/'** NOTE: ',I8,' ZERO OBS WERE SET TO 100 IN LTALTO **')
      END
