!$ESTIMA
      SUBROUTINE ESTIMA(AA,II,LL,SUM1,SUM2,PDELTA,PARMV0,PARMVP,        &
     &   PARMVC,PARMSG,PARVAR,PNAME ,SATCOV,IPTRAU,PRMSG0,LOKIT)
!********1*********2*********3*********4*********5*********6*********7**
! ESTIMA           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:  ESTIMATE ARC PARAMETERS USING BAYESIAN LEAST SQUARES.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   SUM1    I/O   A    NORMAL EQUATION MATRIX
!   SUM2    I/O   A    RIGHT HAND SIDE OF NORMAL EUATIONS
!   PDELTA  I/O   A    CHANGE IN PARAMETER VALUE (APRIORI - CURRENT)
!   PARMV0   I    A    APRIORI PARAMETER VALUE
!   PARMVP  I/O   A    PREVIOUS PARAMETER VALUE
!   PARMVC  I/O   A    CURRENT PARAMETER VALUE
!   PARMSG  I/O   A    STANDARD DEVIATION OF ADJUSTED PARAMETERS
!   PARVAR  I/O   A    DIAGONAL PORTION OF THE INVERTED APRIORI
!                      PARAMETER VAR. - COV. MATRIX
!   PNAME    I    A    PARAMETER NAME
!   SATCOV   I    A    SATELLITE COVARIANCE INFORMATION
!   IPTRAU   I    A    POINTER MAPPING ARRAY FROM ADJUSTED TO UNADJUSTED
!   PRMSG0  I    A    APRIORI SIGMA
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION  (A-H,O-Z),LOGICAL(L)
      SAVE
!ddr mod
      PARAMETER(NXPRM=30000)
!ddr mod
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/ARCPR /FSECRF,XARCPR
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CPARTI/MAXLP ,KORSIZ,MAXWRK,                               &
     &              IUNTP1,IUNTP2,IUNTPF,ISIZPF,IRECPF,NRECPF,          &
     &              NPDONE,NP1   ,NP2   ,NRECND,NPDIM ,NXPARI
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/KNTSTS/KNTACC(9,40),MKNTAC,KNTDRG,KNTSLR,MAXNGA,MAXNDR,    &
     &              MAXNSR,NXKNTS
      COMMON/MBIAST/MBTRAD,MBTRUN,ICONBIA,IPRCTP,IPREND,NXMBST
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/NUDITY/INUDP,INUDT,INUDF
      COMMON/SHIRTS/LNSNS,NXNSNS
!
      DIMENSION AA(1),II(1),LL(1),     SUM1  (MAXWRK),SUM2  (MAPARM),   &
     &   PDELTA(MAPARM),PARMV0(MAPARM),PARMVP(MAPARM),PARMVC(MAPARM),   &
     &   PARMSG(MAPARM),PARVAR(MAPARM),IPTRAU(MAPARM),PNAME(2,MPARM),   &
     &   SATCOV(1),PRMSG0(MAPARM)
      DIMENSION RESID(1),WT(1)
      DIMENSION DIFF(100000)
      DIMENSION LSUM(NXPRM)
      DATA ONE/1.D0/
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      IAPARM=NPVAL0(IXARC)
!

      JJJ=IAPARM
      IF(LOKIT.AND.EMTNUM.GT.0.D0) GO TO 301
      CALL CONCLK(NSATA,AA(KPRML0),AA(KPRMV0),AA(KPRMVC),AA(KSUM1),     &
&                 AA(KSUM2),AA(KPMPA),IAPARM,MAPARM,AA(KPDLTA),         &
&                 LL(KLAVOI))
! II(KJSPFR) array with start and stop times
      IDIM1=MKNTAC
      IF(IDIM1.GT.0) THEN
      IDIM4=NSATA
      IDIMT=MAXNGA
      DO 100 IJ=1,MSETA
      IPXQ=II(KJSPFR+(IJ-1)*9+7)
      CALL ASORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ)  ,LL(KLRDGA),&
     &           II(KNRDGA),AA(KTGACC),II(KIRDGA),II(KSTRTA),AA(KWTACC),&
     &           AA(KTMACC),IDIM1,IDIM4,IDIMT,IJ)
      CALL GA9PCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                   &
     &            SUM1,SUM2,PDELTA,PARMVC,II(KNRDGA),LL(KLRDGA),        &
     &            II(KIRDGA),AA(KWTACC),AA(KTMACC),AA(KTGACC),IDIM1,    &
     &            IDIMT,IDIM4,IJ,AA,LL(KLAVOI),II(KWEMGA))
  100 END DO
      ENDIF
      IDIM2=KNTDRG
      IF(IDIM2.GT.0) THEN
      IDIMT=MAXNDR
      DO 200 IJ=1,MSETA
      IPXQ=II(KJSPFR+(IJ-1)*9+2)
      CALL DSORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ)  ,LL(KLRDDR),&
     &           II(KNRDDR),AA(KTGDRG),II(KIRDRG),II(KSTRTD),AA(KWTDRG),&
     &           AA(KTMDRG),IDIM2,IDIM4,IDIMT,IJ)
      CALL DRGPCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                   &
     &            SUM1,SUM2,PDELTA,PARMVC,II(KNRDDR),LL(KLRDDR),        &
     &            II(KIRDRG),AA(KWTDRG),AA(KTMDRG),AA(KTGDRG),IDIM2,    &
     &            IDIMT,IDIM4,IJ,LL(KLAVOI),II(KWEMDR),2)
  200 END DO
      ENDIF
      IDIM3=KNTSLR
      IF(IDIM3.GT.0) THEN
      IDIMT=MAXNSR
      DO 300 IJ=1,MSETA
      IPXQ=II(KJSPFR+(IJ-1)*9+5)
      CALL SSORT(AA(KPNAME),II(KPTRUA),II(KISATN),AA(IPXQ)  ,LL(KLRDSR),&
     &           II(KNRDSR),AA(KTGSLR),II(KIRSLR),II(KSTRTS),AA(KWTSLR),&
     &           AA(KTMSLR),IDIM3,IDIM4,IDIMT,IJ)
      CALL SLRPCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                   &
     &            SUM1,SUM2,PDELTA,PARMVC,II(KNRDSR),LL(KLRDSR),        &
     &            II(KIRSLR),AA(KWTSLR),AA(KTMSLR),AA(KTGSLR),IDIM3,    &
     &            IDIMT,IDIM4,IJ,LL(KLAVOI))
  300 END DO
      ENDIF
  301 CONTINUE
!
!    CODE FOR TROP BIASES CONSTRAINTS  - BEGIN
!     WRITE(6,*)' dbg ESTIMA ICONBIA,MBTRAD ',ICONBIA,MBTRAD
      IF(ICONBIA.GT.0) THEN
      CALL TROPCN(AA(KPMPA),RESID,WT,IAPARM,MAPARM,1,                   &
     &            SUM1,SUM2,PDELTA,PARMVC,II(KSTBST),AA(KCTBTI),        &
     &            AA(KCTBWE),AA(KCTCTM),                                &
     &            LL(KLAVOI))
      ENDIF
!    CODE FOR TROP BIASES CONSTRAINTS  - END
!
      IF(LNSNS) THEN
         WRITE(6,6020)
         WRITE(6,6020)
         WRITE(6,6020)
         WRITE(6,6021) INUDT
         WRITE(6,6022)
         WRITE(6,6023) INUDP
         WRITE(6,6020)
         WRITE(6,6020)
         WRITE(6,6020)
 6020 FORMAT(' ')
 6021 FORMAT(' ',I6,' GPS OBSERVATIONS WERE DELETED DUE TO  ')
 6022 FORMAT(' NO AMBIGUITY BIAS PARAMETERS ')
 6023 FORMAT(' THESE WERE SPREAD OVER ',I4,' PASSES ')
      ENDIF
      IAPARM=NPVAL0(IXARC)

! DEBUG SUM1
!     write(6,*)' dbg DEBUG SUM1 ',maparm
!     kk=maparm
!     iend=maparm
!     jj=1
!     ij=1
!42221 continue
!     if(kk.eq.0) goto 42223
!     write(6,22222)(SUM1(I),i=jj,iend)
!     jj=iend+1
!     iend=iend+maparm-ij
!     kk=kk-1
!     ij=ij+1
!     goto 42221
!42223 continue
! DEBUG SUM1


      IF(ICLINK.GT.0)                                                   &
     &CALL REDUCE(SUM1,SUM2,PARVAR,IAPARM,MAPARM,II(KLINK),ICLINK)


! DEBUG SUM1
!     write(6,*)' dbg DEBUG SUM1 ',maparm
!     kk=maparm
!     iend=maparm
!     jj=1
!     ij=1
!2221 continue
!     if(kk.eq.0) goto 22223
!     write(6,22222)(SUM1(I),i=jj,iend)
!22222 format(12D12.4)
!     jj=iend+1
!     iend=iend+maparm-ij
!     kk=kk-1
!     ij=ij+1
!     goto 22221
!2223 continue
! DEBUG SUM1


      IF(NAMBB.GT.NXPRM) THEN
        WRITE(6,34567)
        WRITE(6,34567)
        WRITE(6,34567)
        WRITE(6,34567)
34567   FORMAT(' ')
        WRITE(6,34568)
34568   FORMAT(' EXECUTION TERMINATING IN ESTIMA. NUMBER OF AMBIGUITY')
        WRITE(6,34569) NAMBB,NXPRM
34569   FORMAT(' BIASES ',I10,' GREATER THAN LOCAL ARRAY SIZE=',I10)
        STOP
      ENDIF
!
! COMPUTE APRIORI MINUS CURRENT
      DO 1000 I=1,IAPARM
      PDELTA(I)=PARMV0(I)-PARMVC(I)
 1000 END DO
!
! IF THIS IS A PARTITIONED EMAT RUN THEN SKIP ARC SOLUTION ON LAST
! INNER ITERATION
!
      IF(LPART.AND.LSTINR) GOTO 1500
!
!  CALL WTADD TO ADD APRIORI INFORMATION TO ADJUSTED PARAMETERS
!
      IF(NAMBB.GT.0) THEN
         IPQ=IPVAL0(IXBISA)-1
         NK=NPVAL0(IXARC)-NAMBB
         I=NAMBB+1
         JPOS=1+NAMBB*(MAPARM-NAMBB+1)
         DO 1100 I=1,NAMBB
         LSUM(I)=.TRUE.
         IPOS=1+(I-1)*(MAPARM-NAMBB+1)
         IF(SUM1(IPOS).LT..001D0.AND.PARVAR(I+IPQ).LT.100.D0)           &
     &   LSUM(I)=.FALSE.
 1100    CONTINUE
         CALL WTADDX(IAPARM,NSATA,MAPARM,PDELTA,PARVAR,SATCOV,SUM1,SUM2)
!  CALL CONDNO TO SAVE DIAGONAL ELEMENTS OF SUM1 INTO ARRAY CONDNM
         CALL CONDNO(SUM1,MAPARM,IAPARM,AA(KCONDN),.TRUE.)
         NL=MAPARM-IAPARM
         DO 1200 I=1,NAMBB
         IPOS=1+(I-1)*(MAPARM-NAMBB+1)
         RECIP=ONE/SUM1(IPOS)
         SUM1(IPOS)=RECIP
         IF(.NOT.LSUM(I)) GO TO 1200
         CALL PARSUM(NK,NL,RECIP,SUM1(IPOS+1),SUM1(JPOS),               &
     &               SUM2(I),SUM2(NAMBB+1))
 1200    CONTINUE
         MAPK=MAPARM-NAMBB
         IAPK=IAPARM-NAMBB

          !write(6,'(A,3(1x,I10))')&
          !      'estima: NAMBB, IAPARM, MAPARM ', &
          !               NAMBB, IAPARM, MAPARM

!  CALL DSINV TO CALCULATE THE INVERSE OF THE ARRAY SUM1 (MAIN PART OF A

         !write(6,*)'estima: call dsinv '
         !write(6,*)'estima: JPOS, MAPK, IAPK ', &
         !                   JPOS, MAPK, IAPK
         !write(6,*)'estima: ( sum1(JPOS+I),I=0, MAPK ) ', &
         !                   ( sum1(JPOS+I),I=0, MAPK )

        !!!!!!! stop ! debug only

         CALL DSINV(SUM1(JPOS),MAPK,IAPK,PDELTA)

!  CALL CONDNO TO CALCULATE THE CONDITION NUMBERS
         CALL CONDNO(SUM1,MAPARM,IAPARM,AA(KCONDN),.FALSE.)
!  GET SOLUTION FOR MAIN ARC PARAMETRS
         CALL SOLVE(SUM1(JPOS),SUM2(NAMBB+1),IAPK,MAPK,PDELTA(NAMBB+1))
!  GET SOLUTION FOR AMBIGUITY BIASES
          CALL SOLVA(IAPARM,MAPARM,SUM1,SUM2,PDELTA)
      ELSE
!
!@             call matview_1 ( maparm, 1, parvar ) ! %%%%
!@             call matview_3 ( maparm, aa(ksum1) ) ! %%%%
!@             call matview_1 ( maparm, 1, aa(ksum2) ) ! %%%%%%%%%%%
!
         CALL WTADDA(IAPARM,NSATA,MAPARM,PDELTA,PARVAR,SATCOV,SUM1,SUM2)
!  CALL CONDNO TO SAVE DIAGONAL ELEMENTS OF SUM1 INTO ARRAY CONDNM
         CALL CONDNO(SUM1,MAPARM,IAPARM,AA(KCONDN),.TRUE.)
!  CALL DSINV TO CALCULATE THE INVERSE OF THE ARRAY SUM1
         !write(6,*)'estima:2 call dsinv '
         !write(6,*)'estima: NAMBB, IAPARM, MAPARM ', &
         !                   NAMBB, IAPARM, MAPARM
         !write(6,*)'estima: ( sum1(I),I=1, MAPARM*(MAPARM+1)/2  ) '
         !write(6,'(5(1x,E15.7))') ( sum1(I),I=1, MAPARM*(MAPARM+1)/2  )

         CALL DSINV(SUM1,MAPARM,IAPARM,PDELTA)
!  CALL CONDNO TO CALCULATE THE CONDITION NUMBERS
         CALL CONDNO(SUM1,MAPARM,IAPARM,AA(KCONDN),.FALSE.)
!  CALL SOLVE TO SOLVE FOR ARC PARAMETERS ON INNER ITERATION
         CALL SOLVE(SUM1  ,SUM2  ,IAPARM,MAPARM,PDELTA)
      ENDIF
!
! RE-MAKE DELTA IF LINKS ARE PRESENT
      IF(ICLINK.GT.0) CALL REDELT(PDELTA,MAPARM,II(KLINK),ICLINK)
!
 1500 CONTINUE
! UPDATE PREVIOUS PARAMETER VALUE ARRAY
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      DO 2000 I=1,JJJ
      PARMVP(I)=PARMVC(I)
 2000 END DO
!
! IF THIS IS A PARTITIONED EMAT RUN THEN SKIP ON LAST INNER ITERATION
!
      IF(LPART.AND.LSTINR) GOTO 3500
!
! ADD DIFFERENTIAL CORRECTION TO CURRENT PARAMETER VALUE ARRAY
      IF(NAMBB.GT.0) THEN
         IPTR=IPVAL0(IXBISA)-1
         DO 2500 I=1,NAMBB
         IPTR=IPTR+1
         PARMVC(IPTR)=PARMVP(IPTR)+PDELTA(I)
 2500    CONTINUE
          NUM=IPVAL0(IXBISA)-1
         DO 2600 I=1,NUM
         PARMVC(I)=PARMVP(I)+PDELTA(I+NAMBB)
 2600    CONTINUE
!         NUM=NPVAL0(IXBISA)-NAMBB
         NUM=NPVAL0(IXARC)-(IPVAL0(IXBISA)-1)-NAMBB
         IF(NUM.LE.0) GO TO 2800
         IPTR=IPVAL0(IXBISA)-1+NAMBB
         DO 2700 I=1,NUM
         IPTR=IPTR+1
         PARMVC(IPTR)=PARMVP(IPTR)+PDELTA(IPTR)
 2700    CONTINUE
 2800    CONTINUE
      ELSE
         IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
         DO 3000 I=1,JJJ
         PARMVC(I)=PARMVP(I)+PDELTA(I)
 3000    CONTINUE
      ENDIF
 3500 CONTINUE
! COMPUTE TOTAL ADJUSTMENT
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      DO 4000 I=1,JJJ
      DIFF  (I)=PARMVC(I)-PARMV0(I)
 4000 END DO
! COMPUTE STANDARD DEVIATION OF ADJUSTED PARAMETERS
!
! IF THIS IS A PARTITIONED EMAT RUN THEN SKIP ON LAST INNER ITERATION
!
      IF(LPART.AND.LSTINR) GOTO 5100
!
      J=1
      IF(NAMBB.GT.0) THEN
         INCR=MAPARM-NAMBB+1
         IPTR=IPVAL0(IXBISA)-1
         DO 4100 I=1,NAMBB
         IPTR=IPTR+1
         PARMSG(IPTR)=SQRT(SUM1(J))
         J=J+INCR
 4100    CONTINUE
         NUM=IPVAL0(IXBISA)-1
         INCR=MAPARM-NAMBB
         DO 4200 I=1,NUM
         PARMSG(I)=SQRT(SUM1(J))
         J=J+INCR
         INCR=INCR-1
 4200    CONTINUE
!         NUM=NPVAL0(IXBISA)-NAMBB
         NUM=NPVAL0(IXARC)-(IPVAL0(IXBISA)-1)-NAMBB
         IF(NUM.LE.0) GO TO 4400
         IPTR=IPVAL0(IXBISA)-1+NAMBB
         DO 4300 I=1,NUM
         IPTR=IPTR+1
         PARMSG(IPTR)=SQRT(SUM1(J))
         J=J+INCR
         INCR=INCR-1
 4300    CONTINUE
 4400    CONTINUE
      ELSE
         INCR=MAPARM
         DO 5000 I=1,IAPARM
         PARMSG(I)=SQRT(SUM1(J))
         J=J+INCR
         INCR=INCR-1
 5000    CONTINUE
      IF(ICLINK.GT.0) CALL REDELT(PARMSG,MAPARM,II(KLINK),ICLINK)
      ENDIF
 5100 CONTINUE
! PRINT PARAMETER ADJUSTMENT SUMMARY
      ILINE6=MLINE6
      IF(NAMBB.GT.0) THEN
!
!
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
!     NUM=JJJ-NPVAL0(IXBISA)
      NUM=JJJ-(NPVAL0(IXARC)-(IPVAL0(IXBISA)-1))
      DO 5200 I=1,NUM
      N=IPTRAU(I)
      JLINE6=ILINE6+4
      IF(JLINE6.LE.MLINE6) GO TO 5190
      IPAGE6=IPAGE6+1
      JLINE6=9
      WRITE(IOUT6,10000) NARC,NINNER,NGLOBL,IPAGE6
      WRITE(IOUT6,20000)
 5190 CONTINUE
      ILINE6=JLINE6
      WRITE(IOUT6,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),DIFF  (I),PRMSG0(I),PARMVC(I),PDELTA(I+NAMBB),       &
     &   PARMSG(I)
 5200 END DO
!
!
!
!
      NUM=NAMBB
      IK=IPVAL0(IXBISA)
      DO 5300 I=1,NUM
      N=IPTRAU(IK)
      JLINE6=ILINE6+4
      IF(JLINE6.LE.MLINE6) GO TO 5290
      IPAGE6=IPAGE6+1
      JLINE6=9
      WRITE(IOUT6,10000) NARC,NINNER,NGLOBL,IPAGE6
      WRITE(IOUT6,20000)
 5290 CONTINUE
      ILINE6=JLINE6
      WRITE(IOUT6,30000) (PNAME(J,N),J=1,2),PARMV0(IK),                 &
     &   PARMVP(IK),DIFF(IK),PRMSG0(IK),PARMVC(IK),PDELTA(I),           &
     &   PARMSG(IK)
      IK=IK+1
 5300 END DO
!
!
!
!
!     NUM=NPVAL0(IXBISA)-NAMBB
      NUM=NPVAL0(IXARC)-(IPVAL0(IXBISA)-1)-NAMBB
      IF(NUM.LE.0) GO TO 5500
      I1=IPVAL0(IXBISA)+NAMBB
!     I2=IPVAL0(IXBISA)+NPVAL0(IXBISA)-1
      I2=I1+NUM-1
      DO 5400 I=I1,I2
      N=IPTRAU(I)
      JLINE6=ILINE6+4
      IF(JLINE6.LE.MLINE6) GO TO 5390
      IPAGE6=IPAGE6+1
      JLINE6=9
      WRITE(IOUT6,10000) NARC,NINNER,NGLOBL,IPAGE6
      WRITE(IOUT6,20000)
 5390 CONTINUE
      ILINE6=JLINE6
      WRITE(IOUT6,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),DIFF  (I),PRMSG0(I),PARMVC(I),PDELTA(I),             &
     &   PARMSG(I)
 5400 END DO
!
!
 5500 CONTINUE
      ELSE
!
!
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      DO 7000 I=1,JJJ
      N=IPTRAU(I)
      JLINE6=ILINE6+4
      IF(JLINE6.LE.MLINE6) GO TO 6990
      IPAGE6=IPAGE6+1
      JLINE6=9
      WRITE(IOUT6,10000) NARC,NINNER,NGLOBL,IPAGE6
      WRITE(IOUT6,20000)
 6990 CONTINUE
      ILINE6=JLINE6
      WRITE(IOUT6,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),DIFF  (I),PRMSG0(I),PARMVC(I),PDELTA(I),             &
     &   PARMSG(I)
 7000 END DO
!
!
      ENDIF
      WRITE(IOUT6,20200) (AA(I),I=KCONDN,KCONDN+IAPARM-1)
      IF(.NOT.(L9APAR.AND.L9OUT)) GO TO 9100
! SEND PARAMETER ADJUSTMENT SUMMARY TO TERMINAL
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      ILINE9=MLINE9
      DO 9000 I=1,JJJ
      N=IPTRAU(I)
      JLINE9=ILINE9+4
      IF(JLINE9.LE.MLINE9) GO TO 8000
      IPAGE9=IPAGE9+1
      JLINE9=10
      WRITE(IOUT9,10009) NARC,IPAGE9,NINNER,NGLOBL
      WRITE(IOUT9,20000)
 8000 CONTINUE
      ILINE9=JLINE9
      WRITE(IOUT9,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),DIFF  (I),PRMSG0(I),PARMVC(I),PDELTA(I),             &
     &   PARMSG(I)
 9000 END DO
 9100 CONTINUE
!
! IF THIS IS A PARTITIONED EMAT RUN THEN SKIP PRINT OUT OF ADJUSTED
! ELEMENTS AND CORRELATION COEFFICIENTS FOR THE LAST INNER ITERATION
!
      IF(LPART.AND.LSTINR) GOTO 9200
      IF(LIONC.AND.LSIMDT) GOTO 9200
!
!  IF INTERPLANETARY SET UP PLANET POSITIONS FOR PRINT OUT IN ADJELM
      IF(ICBDGM.NE.ITBDGM) CALL LITPRX(MJDSRF,FSECRF,MJDSN,FSECN,AA,II)
      I=NAMBB+1
      JPOS=1+NAMBB*(MAPARM-NAMBB+1)
      MAPARM=MAPARM-NAMBB
      CALL ADJELM(II(KIELMT),AA(KPRMV),PARMV0,PARMVP,PARMVC,SUM1(JPOS), &
     &      II(KMJDSB),AA(KFSECB),AA(KA1UT),AA(KXEPOC),AA(KCKEP),       &
     &      AA(KCKEPN),II(KNSAT),AA(KRMSPO))
      MAPARM=MAPARM+NAMBB
!
 9200 CONTINUE
!
      RETURN
10000 FORMAT('1',   'ARC',I3,' PARAMETER ADJUSTMENT SUMMARY FOR ',      &
     &   'INNER ITERATION',I3,' OF GLOBAL ITERATION',I2,29X,            &
     &   'UNIT  6 PAGE NO.',I6)
10009 FORMAT('1','ARC',I3,' PARAMETER ADJUSTMENT SUMMARY',23X,          &
     &   'UNIT 9 PAGE NO.',I4/                                          &
     &   ' INNER ITERATION',I3,' GLOBAL ITERATION',I2)
20000 FORMAT('0 ','PARAMETER NAME',                                     &
     &    7X,'APRIORI  VALUE'/                                          &
     &   23X,'PREVIOUS VALUE', 9X,'TOTAL   DELTA', 5X,'APRIORI SIGMA'/, &
     &   23X,'CURRENT  VALUE', 9X,'CURRENT DELTA', 5X,'CURRENT SIGMA')
20200 FORMAT(//25X,'CONDITION NUMBERS FROM INVERSION OF NORMAL MATRIX', &
     &   ' FOR ADJUSTED ARC PARAMETERS'/25X,'(COND NO = DIAGONAL',      &
     &   ' ELEMENTS OF ATWA TIMES DIAGONAL ELEMENTS OF ATWA INVERSE)'/  &
     &    /(20X,1P,10D10.3))
30000 FORMAT('0',2A8,G24.16/17X,G24.16,G20.12,G16.8/                    &
     &     17X,G24.16,G20.12,G16.8/)
      END
