!$GENTHM
      SUBROUTINE GENTHM(MJDS,FSEC,TDNRM1,TDNRM2,TDNRM3,NFACE,ETATHM,    &
     &                  ITAPPP,ITANMP,ITAMJS,RTAFSS,RTAINS,AREA,IDSAT,  &
     &                  IDSATS,ACCEL,AA,II)
!***********************************************************************
!                                  10/31/2011        PGMR:  M BLACKBURN
!
!  FUNCTION:  COMPUTE THE THERMAL EMMISSION ACCELERATION ON A BOX WING
!             MODEL OF A VARIABLE NUMBER OF SATELLITES WITH VARIABLE
!             NUMBER OF PANELS
!
!     ACCEL = -2/3*STEFBL*AREA/C/MASS*EMISS*TEMP**4 * NORMVEC
!
!  I/O PARAMETERS:
!
!   NAME    A/S    I/O   DESCRIPTION OF I/O PARAMETERS IN ARGUMENT LIST
!   -----  ------ -----  -----------------------------------------------
!   MJDS     I      S    INTEGER EPHEMERIS SECONDS SINCE GEODYN REF.TIME
!   FSEC     I      S    FRACTIONAL REMAINING SECONDS
!   TDNRM1   A      I    SPACECRAFT FLAT PLATE NORMAL VECTORS IN TRUE OF
!                        DATE SYSTEM (X COMP.)
!   TDNRM2   A      I    SPACECRAFT FLAT PLATE NORMAL VECTORS IN TRUE OF
!                        DATE SYSTEM (Y COMP.)
!   TDNRM3   A      I    SPACECRAFT FLAT PLATE NORMAL VECTORS IN TRUE OF
!                        DATE SYSTEM (Z COMP.)
!   AREA     A      I    ARRAY OF BOX-WING AREAS, MUST BE ARRANGED IN
!                        THIS ORDER:   (X+,X-,Y+,Y-,Z+,Z-,SA+,SA-)(M**2)
!   ETATHM   A      I    ARRAY OF PANELTEMPERATURES AND EMISSIVITIES
!   ACCEL    A      O    TRUE OF DATE THERMAL IMBALANCE ACCELERATION
!   NFACE    S      I    NUMBER OF FLAT PLATES USED TO MODEL SATELLITE
!   MTAMEM   S      I    2*MTAMEM IS THE MAXIMUM DIMENSION OF ETATHM
!   ITAPPP   A      I    PLATE POINTER ARRAY FOR EACH SET
!   MTAPLA   S      I    2*MTAPLA IS THE MAXIMUM DIMENSION OF ITAPPP
!   SCMASS       SPACECRAFT MASS
!   STEFBL       STEFAN-BOLTZMAN CONSTANT
!
!***********************************************************************
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
!
!
      COMMON/BWREAL/SHADOW(2),SUNPCT,SCAREA,SCMASS,BWMEAN
      COMMON/CBDTRU/BDTRUE(7,999)
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/DELOFF/NOFFST,NSATDL,NSTADL,NCGMAS,NXDELO
      COMMON/EXTAGI/MTASAT,MTAFIL,MTAMEM,MTAPLA,NXTAGI
!     COMMON/LSTRT/     need?  in topex used for telem file
!
      DIMENSION AA(1),II(1)
      DIMENSION TDNRM1(NFACE),TDNRM2(NFACE),TDNRM3(NFACE)
      DIMENSION ACCEL(3)
      DIMENSION AREA(NFACE)
      DIMENSION ETATHM(MTAMEM,2)
      DIMENSION ITAPPP(MTAPLA,2),ITANMP(MTASAT)
      DIMENSION ITAMJS(MSATA),RTAFSS(MSATA),IDSAT(MSATA),RTAINS(MSATA)
!
      DATA ZERO/0.0D0/,ONE/1.0D0/,TWO/2.0D0/,THREE/3.0D0/,FOUR/4.0D0/
!***********************************************************************
!  START OF EXECUTABLE CODE
!***********************************************************************
!
! GET CURRENT SCMASS
!
      RATIO2=1.D0
      ITEST=MJDS+FSEC
      IF(NCGMAS.GT.0) THEN
        DO I=1,NCGMAS
           IF(IDSATS.EQ.II(KISATC-1+I).AND.                             &
     &      ITEST.GE.II(KMJDCG-1+I)) RATIO2=AA(KSCMRA-1+I)
        ENDDO
      ENDIF
      SXMASS=SCMASS*RATIO2
! INITIALIZE
!     STEFAN-BOLTZMANN CONSTANT IN W/M**2*K**4
      STEFBL=5.66D-08
      HALFPI=PI/TWO
      PI3ON2=THREE*HALFPI
      COEF  = -TWO/THREE*STEFBL/VLIGHT/SXMASS
! INITIALIZE ACCELERATION ARRAY
      DO 100 J=1,3
  100 ACCEL(J) = ZERO

!     ACCEL = -2/3*STEFBL*AREA/C/MASS*EMISS*TEMP**4 * NORMVEC
!           =            *AREA       *EMISS*TEMP**4 * NORMVEC

      CALL FNDNUM(IDSATS,IDSAT,MTASAT,IRET)
      IF(IRET.LE.0.OR.IRET.GT.MTASAT) RETURN
      MJDSDF=MJDS-ITAMJS(IRET)
      FSECDF=FSEC-RTAFSS(IRET)
      TADIFF=DBLE(MJDSDF)+FSECDF
! ... compute pointer to temp/emis preceding the current time
      IPNT1=INT(TADIFF/RTAINS(IRET))+2
      IPNTDF=TADIFF-INT(TADIFF/RTAINS(IRET))

      ISKIP=0
      IF(IRET.GT.1) THEN
      DO IJ=1,IRET-1
      ISKIP=ISKIP+ITANMP(IJ)
      ENDDO
      ENDIF

      DO 140 IPAN=1,ITANMP(IRET)
      IPT=ITAPPP(ISKIP+IPAN,2)+IPNT1-1

      TEMP=ETATHM(IPT,1)
      EMIS=ETATHM(IPT,2)

      TERM1=COEF*AREA(ITAPPP(ISKIP+IPAN,1))*EMIS*TEMP**4

      ACCEL(1)=ACCEL(1)+TERM1*TDNRM1(1)
      ACCEL(2)=ACCEL(2)+TERM1*TDNRM2(2)
      ACCEL(3)=ACCEL(3)+TERM1*TDNRM3(3)

 140  CONTINUE

      RETURN
!
      END
