      SUBROUTINE GETAMB(MTYPE,MJDSBL,FSECBL,JSTANO,JSATNO)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION JSTANO(3),JSATNO(3)
      DIMENSION FSEC(1),IYMD(1),IHM(1),SEC(1)
      DIMENSION JYMD(1),JHM(1),SEJ(1)
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/XPARMB/MPARMB,NPARMB,MPOBS,JPAMB,ISKIPE,                   &
     &             ITPARM(5,28000),ISTABP(3,28000),                     &
     &             ISATBP(3,28000),IPRMBF(28000)
!
      ITM=MJDSBL+FSECBL
      JPAMB=0
      ITDIF=0
      IF(MTYPE.EQ.65) ITDIF=4000
      IF(MTYPE.EQ.85) ITDIF=4000
      IF(MTYPE.EQ.87) ITDIF=36000
      DO 100 I=1,NAMBBH
      IPAMB=I
      IF(ITPARM(1,I).NE.MTYPE) GO TO 100
      JTDIF=ITM-ITPARM(3,I)
      IF(JTDIF.LT.-500) GO TO 100
      IF(JTDIF.GT.ITDIF) GO TO 100
      IF(JSTANO(1).NE.ISTABP(1,I)) GO TO 100
      IF(JSTANO(2).NE.ISTABP(2,I)) GO TO 100
      IF(JSTANO(3).NE.ISTABP(3,I)) GO TO 100
      IF(JSATNO(1).NE.ISATBP(1,I)) GO TO 100
      IF(JSATNO(2).NE.ISATBP(2,I)) GO TO 100
      IF(JSATNO(3).NE.ISATBP(3,I)) GO TO 100
      GO TO 200
  100 END DO
      RETURN
  200 CONTINUE
      JPAMB=IPAMB
      RETURN
      END
