!$GETFRC
      SUBROUTINE GETFRC(PMPA,XDDAO,PXHDDT,OBSC,LAVOID,LNPNM,HS,NEQNH,   &
     &                  NN3,NSTEPB,IHSAFR,IPTFBS,IFIRST,                &
     &                  LEDIT,NSEL,LHRFON,NPRMAC,ACCDOT,ISAT,           &
     &                  IPTFMG,ILNFMG,NFMG)
!********1*********2*********3*********4*********5*********6*********7**
! GEFFRC           00/00/00            0000.0    PGMR - D. E. Pavlis
!
! FUNCTION:  GET INFORMATION FROM NSTEPB DIMENSIONED ARRAYS  TO NM ARRAY
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!    PMPA   I/O   A    ARRAY OF MEASUREMENT PARTIALS
!    PXHDDT  I    A    ARRAY OF FORCE MODEL PARTIALS
!    XDDAO   I    A    ARRAY OF FORCES (FROM F)
!    OBSC    O    A    OBSERVED ACCELERATIONS (LOADED FROM XDAAO)
!    HS     I    S    SMALL STEPSIZE FOR THIS SET
!    NEQNH   I    S    NUMBER OF FORCE MODEL EQUATIONS FOR THIS SET
!    NN3      I    S    NUMBER OF SATS IN THIS SET
!    NSTEPB  I    S    STEPS FOR HIGH RATE INTEGRATION
!    NM      I    S    NUMBER OF OBSERVATIONS IN THIS BLOCK
!    IFIRST  I    S    ADDRESS OF THIRD DIMENSION OF PXHDDT TO GET THE
!                      FIRST OBSERVATION
!    LEDIT   I/O  A    OBSERVATION EDIUTING ARRAY
!    NSEL    I    A    POINTER ARRAY FROM NSTEPB TO NM
!    LHRFON  I    A    FLAGS FOR HIGH RATE FORCE MODEL PARAMETERS
!    ISAT    I    S    INTERNAL SAT # OF SATELLITE BEING PROCESSED
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX

      DIMENSION LAVOID(MAPARM),PMPA(NDIM1,NDIM2)
      DIMENSION PXHDDT(NEQNH,NN3,NSTEPB)
! THE 1 IN THE THIRD DIMENSION OF XDDAO ASSUMES THAT ACCELEROMETRY
! IS BEING USED WITH ONE SATELLITE IN A SET. SUBROUTINE ACCSEL
! CURRENTLY ENFORCES THIS
      DIMENSION XDDAO(3,NFSCAC,1,NSTEPB)
      DIMENSION OBSC(NM)
      DIMENSION IHSAFR(MXHRG)
      DIMENSION IPTFBS(MXFMG)
      DIMENSION NPRMAC(MXHRG)
      DIMENSION LEDIT(NM)
      DIMENSION LHRFON(MXFMG)
      DIMENSION NSEL(NM)
      DIMENSION INDEX(27),NPARAM(27)
      DIMENSION ACCDOT(MINTIM,4)
      DIMENSION IPTFMG(MAXFMG,MSATA),ILNFMG(MAXFMG,MSATA),NFMG(MSATA)
      DATA kentry/0/
      DATA ZERO/0.D0/
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
      kentry = kentry + 1
!     write(6,*)' getfrc kentry ',kentry

! INITIALIZE PMPA
       DO 100 I=1,NDIM1
       DO 100 J=1,NDIM2
       PMPA(I,J)=ZERO
  100  CONTINUE

! INITIALIZE ACCDOT
       DO 200 I=1,MINTIM
       DO 200 J=1,4
       ACCDOT(I,J)=ZERO
  200  CONTINUE

      INDEX(1)=IPVAL0(IXDRAG)-1
      INDEX(2)=IPVAL0(IXSLRD)-1
      INDEX(3)=IPVAL0(IXACCL)-1
      INDEX(16)=IPVAL0(IXATUD)-1
      NPARAM(1)=NPVAL0(IXDRAG)
      NPARAM(2)=NPVAL0(IXSLRD)
      NPARAM(3)=NPVAL0(IXACCL)
      NPARAM(16)=NPVAL0(IXATUD)

!     write(6,*)' dbg GETFRC DEBUG ',NN3,NSTEPB,NEQNH,NFSCAC
!     if(nn3.gt.0.and.nstepb.gt.0) then
!     DO 101 I=1,NEQNH
!     DO 101 J=1,nstepb
!     DO 101 IJK=1,NFSCAC
!     write(6,*)'XDDAO',XDDAO(1,IJK,1,J),XDDAO(2,IJK,1,J),
!    .XDDAO(3,IJK,1,J),J
!     write(6,*)'GFR',PXHDDT(I,1,J),PXHDDT(I,2,J),PXHDDT(I,3,J),J,I
!101  continue
!     endif
!
!
      IF(LSTINR) THEN
        DO J=1,NM
           XECF=XDDAO(1,17,1,IFIRST-1+NSEL(J))
           YECF=XDDAO(2,17,1,IFIRST-1+NSEL(J))
           ZECF=XDDAO(3,17,1,IFIRST-1+NSEL(J))
           PENUM=XDDAO(1,18,1,IFIRST-1+NSEL(J))
           WRITE(91) XECF,YECF,ZECF,PENUM
        ENDDO
      ENDIF
!
! LOAD OBSERVATIONS
      IF(MTYPE.GE.201.AND.MTYPE.LE.203) THEN

      I=MTYPE-200
      DO J=1,NM
      OBSC(J)=XDDAO(I,1,1,IFIRST-1+NSEL(J))
      IF(LSTINR) WRITE(91) OBSC(J)
      P1= XDDAO(I,1,1,IFIRST+NSEL(J)-2)
      P2= XDDAO(I,1,1,IFIRST+NSEL(J))
      DT= HS*2
      ACCDOT(J,I+1)=(P2-P1)/DT
!     write(6,*)' dbg OBSC ',OBSC(J),J,ifirst,nsel(j)
      ENDDO

      ELSE
! TOTAL ACCELLERATION MTYPE=200
      IF(MTYPE.NE.200) THEN
      WRITE(6,*)' WRONG MEASUREMENT TYPE: ',MTYPE,' STOPPED IN ACCELR '
      ENDIF
      DO J=1,NM
      TOT=0.D0
      DO I=1,3
      TOT=TOT+XDDAO(I,1,1,IFIRST-1+NSEL(J))**2
!     write(6,*)' dbg 1 ',XDDAO(I,1,1,IFIRST-1+NSEL(J)),I
      ENDDO
      OBSC(J)=SQRT(TOT)
      IF(LSTINR) WRITE(91) OBSC(J)
!     write(6,*)' dbg OBSC ',OBSC(J),J,IFIRST
      ENDDO


      ENDIF

      IJ=MOD(MTYPE,200)

!     write(6,*)' dbg IJ for MTYPE ',IJ,MTYPE


!***** PARTIALS FOR SURFACE FORCES  *****************************
      ISGLB=IPVAL0(IXBISA)
      ISGLB1=IPVAL0(IXBISA)-1
      NGRP=NFMG(ISAT)
      DO 300 IGRP=1,NGRP
      INDS=IPTFMG(IGRP,ISAT)
      IF(INDS.LT.ISGLB) THEN
         INDS=IPTFMG(IGRP,ISAT)+NAMBB
      ELSE
         GO TO 300
      ENDIF
      INDF=INDS-1+ILNFMG(IGRP,ISAT)
      DO 290 INDX=INDS,INDF
      LAVOID(INDX)=.FALSE.
  290 END DO
  300 END DO
!
      IF(IJ.EQ.0) GO TO 400
!
!   PARTIALS FOR INDIVIDUAL COMPONENTS
!
      IF(LNPNM)  GO TO 340
!
! MEASUREMENTS FIRST
!
      N=0
      DO 330 IGRP=1,NGRP
      INDS=IPTFMG(IGRP,ISAT)
      IF(INDS.LT.ISGLB) THEN
         INDS=IPTFMG(IGRP,ISAT)+NAMBB
      ELSE
         GO TO 330
      ENDIF
      INDF=INDS-1+ILNFMG(IGRP,ISAT)
      DO 320 INDX=INDS,INDF
      N=N+1
      DO 310 M=1,NM
      PMPA(M,INDX)=PMPA(M,INDX)+PXHDDT(N,IJ,IFIRST-1+NSEL(M))
  310 END DO
  320 END DO
  330 END DO
      GO TO 500
!
! PARAMTERS FIRST
!
  340 CONTINUE
      DO 370 M=1,NM
      NN=0
      DO 360 IGRP=1,NGRP
      INDS=IPTFMG(IGRP,ISAT)-1
      IF(INDS.LT.ISGLB1) THEN
         INDS=IPTFMG(IGRP,ISAT)-1+NAMBB
      ELSE
         GO TO 360
      ENDIF
      ILS=ILNFMG(IGRP,ISAT)
      DO 350 N=1,ILS
      PMPA(INDS+N,M)=PMPA(INDS+N,M)+PXHDDT(NN+N,IJ,IFIRST-1+NSEL(M))
  350 END DO
      NN=NN+ILS
  360 END DO
  370 END DO
      GO TO 500
!
!
! PARTIAL FOR TOTAL ACCELERATION
!
!
  400 CONTINUE
      IF(LNPNM)  GO TO 440
!
! MEASUREMENTS FIRST
!
      N=0
      DO 430 IGRP=1,NGRP
      INDS=IPTFMG(IGRP,ISAT)
      IF(INDS.LT.ISGLB) THEN
         INDS=IPTFMG(IGRP,ISAT)+NAMBB
      ELSE
         GO TO 430
      ENDIF
      INDF=INDS-1+ILNFMG(IGRP,ISAT)
      DO 420 INDX=INDS,INDF
      N=N+1
      DO 410 M=1,NM
      PMPA(M,INDX)=PMPA(M,INDX)                                         &
     & +(XDDAO(1,1,1,IFIRST-1+NSEL(M))*PXHDDT(N,1,IFIRST-1+NSEL(M))     &
     &  +XDDAO(2,1,1,IFIRST-1+NSEL(M))*PXHDDT(N,2,IFIRST-1+NSEL(M))     &
     &  +XDDAO(3,1,1,IFIRST-1+NSEL(M))*PXHDDT(N,3,IFIRST-1+NSEL(M)))    &
     &  /OBSC(J)
  410 END DO
  420 END DO
  430 END DO
      GO TO 500
!
! PARAMTERS FIRST
!
  440 CONTINUE
      DO 470 M=1,NM
      NN=0
      DO 460 IGRP=1,NGRP
      INDS=IPTFMG(IGRP,ISAT)-1
      IF(INDS.LT.ISGLB1) THEN
         INDS=IPTFMG(IGRP,ISAT)-1+NAMBB
      ELSE
         GO TO 460
      ENDIF
      ILS=ILNFMG(IGRP,ISAT)
      DO 450 N=1,ILS
      PMPA(INDS+N,M)=PMPA(INDS+N,M)                                     &
     & +(XDDAO(1,1,1,IFIRST-1+NSEL(M))*PXHDDT(NN+N,1,IFIRST-1+NSEL(M))  &
     &  +XDDAO(2,1,1,IFIRST-1+NSEL(M))*PXHDDT(NN+N,2,IFIRST-1+NSEL(M))  &
     &  +XDDAO(3,1,1,IFIRST-1+NSEL(M))*PXHDDT(NN+N,3,IFIRST-1+NSEL(M))) &
     &  /OBSC(J)
  450 END DO
      NN=NN+ILS
  460 END DO
  470 END DO
  500 CONTINUE
! RETRIEVE HERE THE PARTIALS FOR ATTITUDE FROM XDDAO (1-3,2-16,1,1)
!     WRITE(6,*)' dbg NPARAM(16) : ' , NPARAM(16)
!     WRITE(6,*)' dbg INDEX(16)+1 : ' ,INDEX(16)+1
      IF(NPARAM(16).GT.0)  THEN
      DO I=1,NPARAM(16)
      LAVOID(INDEX(16)+I)=.FALSE.
      ENDDO
       IF(LNPNM) THEN
        DO J=1,NM
        DO K=1,NPARAM(16)
        PMPA(INDEX(16)+K,J)=PMPA(INDEX(16)+K,J) +                       &
     &                      XDDAO(IJ,1+K,1,IFIRST-1+NSEL(J))
!       write(6,*)' dbg pmpa ',pmpa(index(16)+k,j),index(16)+K,j
!    .  ,ij,1+k,1,ifirst-1+NSEL(J)
        ENDDO
        ENDDO
       ELSE
        DO J=1,NM
        DO K=1,NPARAM(16)
        PMPA(J,INDEX(16)+K)=PMPA(J,INDEX(16)+K)+                        &
     &                      XDDAO(IJ,1+K,1,IFIRST-1+NSEL(J))
!       write(6,*)' dbg pmpa ',pmpa(j,index(16)+k),j,index(16)+K
        ENDDO
        ENDDO
               ! IF (LNPNM)
       ENDIF
               ! IF(NPARAM(16).GT.0)
      ENDIF
20000 CONTINUE

!     ENDIF ! IF(LHRFON(II))

!     ENDDO ! DO 1,MXFMG


!***** END PARTIALS TO HIGH RATE FORCES  *****************************

      RETURN
      END
