      SUBROUTINE GETOR(COSTHG,SINTHG,RA,DEC,IBODY)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/VAXINT/XAXIS(3,3,3)
      DIMENSION FSEC(1),RA(1),DEC(1),SCRTCH(4),ROTI(9)

!
      DEC(1)=ASIN(XAXIS(3,3,IBODY))
      IF(ABS(XAXIS(3,3,IBODY)).LT.1.D0) THEN
        R=SQRT(XAXIS(1,3,IBODY)*XAXIS(1,3,IBODY)                        &
     &        +XAXIS(2,3,IBODY)*XAXIS(2,3,IBODY))
        RA(1)=ATAN2(XAXIS(2,3,IBODY)/R,XAXIS(1,3,IBODY)/R)
      ELSE
        RA(1)=0.D0
      ENDIF
!
      CALL DXQN(MJDSC,FSEC,RA,DEC,ROTI(1),ROTI(2),ROTI(3),              &
     &                ROTI(4),ROTI(5),ROTI(6),ROTI(7),ROTI(8),          &
     &                ROTI(9),SCRTCH,1)
!
! INERTIAL IAU XAXIS IN J2000 1ST ROW OF ROTI
      COSTHG=XAXIS(1,1,IBODY)*ROTI(1)+XAXIS(2,1,IBODY)*ROTI(4)          &
     &      +XAXIS(3,1,IBODY)*ROTI(7)
      C1=ROTI(4)*XAXIS(3,1,IBODY)-ROTI(7)*XAXIS(2,1,IBODY)
      C2=ROTI(7)*XAXIS(1,1,IBODY)-ROTI(1)*XAXIS(3,1,IBODY)
      C3=ROTI(1)*XAXIS(2,1,IBODY)-ROTI(4)*XAXIS(1,1,IBODY)
!
! C1,C2,C3 HAS LENGTH |SINTHG|
! AND HAS SAME ORIRNTATION (UP TO DIRECTION) AS XAXIS(*,3)
      SINTHG=XAXIS(1,3,IBODY)*C1+XAXIS(2,3,IBODY)*C2+XAXIS(3,3,IBODY)*C3
      RETURN
      END
