!$GETPPC
      SUBROUTINE GETPPC(NADJST,ILASTR)
!********1*********2*********3*********4*********5*********6*********7**
! GETPPC                                         PGMR - D. ROWLANDS
!
!
! FUNCTION:  COMPUTE POINTERS AND QUANTITIES NECESSARY TO EXECUTE
!            THE PARALLEL PROCCSSING OF EMATS. THIS ROUTINE FIGURES
!            HOW TO SUBDIVIDE EACH PARTITION OF THE NORMAL MATRIX.
!            SEE GDYN2E FOR DESCRIPTION OF THE PARPRC COMMON BLOCK
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   NADJST   I    S    NUMBER OF ELEMENTS IN 1ST ROW OF CURRENT
!                      PARTITION
!   ILASTR   I    S    NUMBER OF ROWS IN THIS PSRTITION (NOT
!                      NECESSARILY = NADJST)
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/PARPRC/NPROCS,NPROCI(5,10)
!
      NPROCS=IPROCS
      LSTINR=.TRUE.
!
!
      IF(NPROCS.LE.0) NPROCS=1
      IF(NPROCS.GT.10) NPROCS=10
      IF(NPROCS.EQ.1) THEN
        WRITE(6,6000)
        WRITE(6,6000)
        WRITE(6,6000)
        WRITE(6,6010)
        WRITE(6,6011)
        WRITE(6,6000)
        WRITE(6,6000)
        RETURN
      ENDIF
!
!
!
      DO IPROC=1,NPROCS
         NPROCI(1,IPROC)=(IPROC-1)*NADJST-(IPROC-2)*(IPROC-1)/2
         NPROCI(2,IPROC)=NADJST-IPROC+1
         NPROCI(3,IPROC)=NPROCS
         NPROCI(4,IPROC)=0
         NPROCI(5,IPROC)=0
         IF(IPROC.LE.ILASTR) THEN
            DO 10 J=IPROC,ILASTR,NPROCS
            IF(J.GT.ILASTR) GO TO 20
            NPROCI(4,IPROC)=NPROCI(4,IPROC)+1
   10       CONTINUE
   20       CONTINUE
         ENDIF
      ENDDO
!
!
      IF(.NOT.LSTINR) RETURN
      WRITE(6,6000)
      WRITE(6,6000)
      WRITE(6,6000)
      WRITE(6,6020) NPROCS
      WRITE(6,6021)
      WRITE(6,6022)
      WRITE(6,6000)
      WRITE(6,6023)
      WRITE(6,6000)
      DO 30 IPROC=1,NPROCS
      IQL=IPROC+(NPROCI(4,IPROC)-1)*NPROCS
      WRITE(6,6024) IPROC,IPROC,IQL,NPROCS
   30 END DO
      WRITE(6,6000)
      WRITE(6,6000)
      DO 40 IPROC=1,NPROCS
      ILQ=NPROCI(1,IPROC)+1
      WRITE(6,6025) IPROC,ILQ,NPROCI(4,IPROC)
   40 END DO
      RETURN
 6000 FORMAT(' ')
 6010 FORMAT(' THE NORMAL MATRIX IS NOT BEING SUBDIVIDED')
 6011 FORMAT(' NOTHING TO BE GAINED FROM MULTIPROCESSING')
 6020 FORMAT(' ',I5,' PROCESSORS HAVE BEEN REQUESTED')
 6021 FORMAT(' THEY WILL BE USED TO DIVIDE THE PORTION OF THE NORMAL')
 6022 FORMAT(' MATRIX THAT DOES NOT BELONG TO AMBIGUITY BIASES')
 6023 FORMAT(' THE MATRIX WILL BE DIVIDED AS FOLLOWS:')
 6024 FORMAT(' PROCESSOR # ',I2,' HAS ROWNO ',I6,' THRU ROWNO ',I6,     &
     &       ' EVERY ',I4,'ROWS')
 6025 FORMAT(' SEGMENT ',I3,' STARTS AT ',I10,' AND HAS ',I7,' ROWS')
      END
