!$
      SUBROUTINE GMFHOP(COSEL,SINEL,EDOT,RNM,CDRY,CWET,CION,NM,         &
     &   MODELT,LNDRYT,LNWETT,LNIONO,BLKMET,OBSMET,LOBMET,LALTON,       &
     &   RLATA,COSLTA,SINLTA,HTA,MTYPE,MJDSBL,FSEC,IWPR,NSTA0)
!********1*********2*********3*********4*********5*********6*********7**
! GMFHOP           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:  TROP REFRACTION CORRECTION USING GPT/GMF/HOPFIELD MODEL
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   COSEL    I    A    COSINE OF ELEVATION
!   SINEL    I    A    SINE OF ELEVATION
!   EDOT     I    A    TIME RATE OF CHANGE OF ELEVATION
!   RNM      I    A    RANGE FROM STATION TO S/C
!   CDRY     O    A    DRY TROPOSPHERIC REFRACTION CORRECTION
!   CWET     O    A    WET TROPOSPHERIC REFRACTION CORRECTION
!   CION     O    A    IONOSPHERIC REFRACTION CORRECTION
!   NM       I    S    NUMBER OF OBSERVATION IN THIS LOGICAL BLOCK
!   MODELT   I    S    REFRACTION MODEL INDICATOR
!   LNDRYT   I    S    LOGICAL FLAG TO THE DRY TROPOSPHERIC REFRACTION
!                      CORRECTION
!   LNWETT   I    S    LOGICAL FLAG TO THE WET TROPOSPHERIC REFRACTION
!                      CORRECTION
!   LNIONO   I    S    LOGICAL FLAG TO THE IONOSHPERIC REFRACTION
!                      CORRECTION
!   BLKMET   I    S    METEOROLOGICAL DATA FROM THE BLOCK HEADER RECORDS
!   OBSMET   I    A    METEOROLOGICAL DATA FOR EACH OBSERVATION IN THE
!                      BLOCK
!   LOBMET   I    S    LOGICAL FLAG FOR METEOROLOGICAL DATA
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CMET/P0,T0,RELHUM,E0,WAVLEN
      COMMON/CMETI /MODEL(999),MWET(999),MDRY(999),MODESC(999),        &
     &              MAPWET(999),MAPDRY(999),METP(999),IRFRC,           &
     &              IRFPRT(10),NXCMTI
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CSTA/RLAT,COSLAT,SINLAT,RLON,COSLON,SINLON,HEIGHT,         &
     &   TMOUNT,DISP,WAVREC,WAVXMT,ELCUT,PLATNO,SITNOL,SDTLRA,ANTTNO
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      DIMENSION COSEL(NM),SINEL(NM),EDOT(NM),RNM(NM),CDRY(NM),CION(NM)
      DIMENSION OBSMET(NM),CWET(NM),FSEC(NM),JYMD(1),JHM(1),FSEC1(1)
      DIMENSION RLATA(NM),COSLTA(NM),SINLTA(NM),HTA(NM)
      DIMENSION HMF(2),WMF(2),IOROGRAPHY_ARRAY(91,145)
      DATA ZERO/0.0D0/,ONE/1.0D0/,HUNDRD/100.0D0/,C1500/1.5D3/
      DATA CFLAM0/0.965D0/,CFLAM2/0.0164D-12/,CFLAM4/0.228D-27/
      DATA CFPOSL/-2.6D-3/,CFPOSH/-3.1D-7/,DPDH/-1.1138D-4/
      DATA P1ATM/1013.5D0/,STDTMP/293.16D0/,VAPOR0/9.35D0/
      DATA kentry/0/

      PARAMETER( HALF = 0.5D0 )
      PARAMETER( C1D2 = 1.0D2 )
      PARAMETER( C1D6 = 1.0D6 )

      INTEGER :: IWPR
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!      write(6,*) 'jtw I am in GMFHOP'
!
      kentry = kentry + 1

      IF(LNDRYT) GO TO 5000
      IF(.NOT.LALTON) THEN
         CALL METDAT(BLKMET)
         IF(P0.GT.HUNDRD.AND.P0.LT.C1500) GO TO 1000
! DEFAULT PRESSURE, TEMPERATURE AND WATER VAPOR PRESSURE
         P0=P1ATM*(ONE+DPDH*HEIGHT)
         T0=STDTMP
         E0=VAPOR0
 1000 CONTINUE
      ENDIF

 1500 CONTINUE

      MODE=1
      IF(LASER) MODE=2
      MODELX=0

      CALL XDOY(DOY)

      RLATD=RLAT*57.295777951D0

      DO 2800 N=1,NM

      IF(LOBMET.AND..NOT.LALTON) CALL METDAT(OBSMET(N))
      IF(LALTON) THEN
        HEIGHT=HTA(N)
        IF(LOBMET) THEN
           CALL METDAT(OBSMET(N))
        ELSE
           CALL METDAT(BLKMET)
           IF(P0.LT.HUNDRD.OR.P0.GT.C1500) THEN
! DEFAULT PRESSURE, TEMPERATURE AND WATER VAPOR PRESSURE
              P0=P1ATM*(ONE+DPDH*HEIGHT)
              T0=STDTMP
              E0=VAPOR0
            ENDIF
        ENDIF
      ENDIF

! MODEL=6 OR 7, GPT+GMF REQUIRED
! USE GPT TO DETERMINE P0 AND T0.

        CALL GPT(DOY,RLAT,RLON,HEIGHT,P0,T0,DUM)

! CONVERT CELIUS TO KELVIN
          T0=T0+273.15D0

      GOTO 3000

      2800 END DO

      3000 CONTINUE


      MODELX=0
      MODE=1

!     THE GMF (GLOBAL FUNCTION MODEL) HAS BEEN SELECTED
      IF(MTYPE.EQ.40.OR.LGPS) THEN

! USE HOPFIELD TO DETERMINE WET AND DRY CORRECTIONS AND THEN USE
! MAPPING FUNCIONS TO GET VLBI/GPS MODEL
         DO N=1,NM
      TINV=ONE/T0
      CDRY(N)=TROPRF(MODELX,MODE,P0,TINV,E0,SINEL(N),COSEL(N),EDOT(N),  &
     &                RNM(N),CWET(N))
!         ENDDO

!     COMPUTE MODIFIED JULIAN DATE
!     CALL MJDYMD(MJDSBL,IYMD,IHMS,4)
!     CALL MJDYMD(MJDS,IYMD,IHMS,2)
! MJDS MODIFIED JULIAN DATE
! RLAT STATION LATITUDE IN RADIANS
! RLON STATION LONGITUDE IN RADIANS
! HEIGHT STATION HEIGHT IN METERS  (COMMON CSTA FOR ALL THE ABOVE)

!       DO N=1,NM
       TANEL=SINEL(N)/COSEL(N)
       ELEVAT=ATAN(TANEL)

! ZENITH DISTANCE IN RADIANS
       ZENDIST=(PI/2.D0)-ELEVAT
       CALL GMF(DOY,RLAT,RLON,HEIGHT,ZENDIST,GMFH,GMFW)

!       if (nm == 1) then
!
!       write(6,'(A,2(1x,E15.7)/)') 'refrac: GMFH, GMFW  ', &
!                                            GMFH, GMFW
!
!            write(6,'(A,1x,I8,2x, 2(1x,E15.7)/)')  &
!     &         'refrac: n, CDRY(n), CWET(n)'  ,  &
!     &                  n, CDRY(n), CWET(n)
!
!       endif
!
!       CWET(N)=CWET(N)*GMFW
!       CDRY(N)=CDRY(N)*GMFH

          CALL YMDHMS(MJDSBL,FSEC(N),JYMD,JHM,FSEC1,1)
          IF(JYMD(1).GE.1000000)JYMD(1)=JYMD(1)-1000000
          STRTIM=DBLE(JYMD(1))*C1D6 + DBLE(JHM(1))*C1D2+ FSEC1(1)

          IF (LITER1 .AND. IWPR==1) THEN

!           WRITE(6,*)'NSTA0, STRTIM, CDRY, CWET'
!           WRITE(6,*)NSTA0,STRTIM,CDRY(N),CWET(N)
!           WRITE(400,'(I8,1x,G24.16,1X,E,1x,E)') NSTA0,STRTIM,CDRY(N),CWET(N)
           WRITE(400,'(I8,1x,G24.16,1X,E20.10,1x,E20.10)') &
                 NSTA0,STRTIM,CDRY(N),CWET(N)

          ENDIF


       CWET(N)=CWET(N)*GMFW
       CDRY(N)=CDRY(N)*GMFH


       ENDDO

      ELSE
! THIS MODEL APPLIES ONLY TO DORIS AND GPS
      WRITE(6,*)' THE GMF MODEL (MODEL=6) APPLIES TO DORIS AND GPS '
      WRITE(6,*)' AND DORIS ONLY. PLEASE CHECK THE REFRAC OPTION   '
      WRITE(6,*)' EXECUTION STOPS IN SUBROUTINE REFRAC '
      STOP 16
      ENDIF

 5000 CONTINUE
      IF(LNIONO) RETURN
      RETURN
      END
