      SUBROUTINE GPOINT(JSAFRC,LSURFF,IPTFBS,NPARM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      DIMENSION JSAFRC(MXFMG),LSURFF(NSURF),IPTFBS(MXFMG),NPARM(MXHRG)
!
      DO I=1,MXFMG
      NPARM(I)=0
      ENDDO
!
!  ON FIRST ITERATION LOAD NPARM WITH THE NUMBER OF PARAMETERS THAT
!  ARE BEING ADJUSTED IRRESPECTIVE OF ACCELEROMETRY SURFACE FORCES
!
      DO 100 I=1,13
      NPARM(I)=JSAFRC(I+1)-JSAFRC(I)
      IPTFBS(I)=JSAFRC(I)
  100 END DO
!
!  NOW ZERO OUT ANY CATEGORIES THAT DON'T BELONG TO SURFACE FORCE
!  ACCELEROMETRY
!
      IF(.NOT.LSURFF(1)) NPARM(3)=0
      IF(.NOT.LSURFF(2)) NPARM(1)=0
      IF(.NOT.LSURFF(3)) NPARM(2)=0
      IF(.NOT.LSURFF(7)) NPARM(13)=0
      LPAN=.TRUE.
      IF(.NOT.LSURFF(2).AND..NOT.LSURFF(3)) LPAN=.FALSE.
!
      IF(.NOT.LPAN) THEN
         DO I=4,12
           NPARM(I)=0
         ENDDO
      ENDIF
!
      RETURN
      END
