!$IFRGD3
      SUBROUTINE IFRGD3(AA,II,LL,IFFHDR,IFFLEN,FFBUF)
!********1*********2*********3*********4*********5*********6*********7**
! IFRGD3           00/00/00            0000.0    PGMR - B. EDDY
!
! FUNCTION:  READ GLOBAL DYNAMIC ARRAYS FROM THE INTERFACE FILE
!            FOR ALLOCATION GROUP #3 - COORDINATE SYSTEMS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   IFFHDR   I    A    SCRATCH ARRAY USED FOR HEADER INFORMATION
!   IFFLEN   I    A    SCRATCH ARRAY USED FOR LENGTHS OF DATA
!   FFBUF    I    A    SCRATCH ARRAY USED FOR CONVERTING IBM
!                      FLOATING POINT NUMBERS TO CYBER F.P.
!
! COMMENTS:     INTERFACE FORMAT #2 USED:
!
! INTEGER  HEADER RECORD  - WITH IFFHDR(5)=0 INDICATING LENGTHS RECORDS
!                           FOLLOWS
! INTEGER LENGTHS RECORD  - CONTAINING IFFHDR(4)-1 LENGTHS
!            DATA RECORDS - IFFHDR(4)-1  DATA RECORDS. DATA RECORDS ARE
!                           OF THE TYPE INDICATED IN IFFHDR(3)
!
! COMMENTS:   TO READ ADDITIONAL RECORDS IN THIS ROUTINE
!             1. INCREMENT IRECS IN PROPER GROUP-REAL,INTEGER OR LOGICAL
!             2. ADD CALL TO BINRD2 (REAL) OR BINRD (INTEGER,LOGICAL)
!                IN PROPER GROUP
!             3. FOR FLOATING POINT DATA CALL SUBROUTINE Q9ICLA TO
!                CONVERT REAL WORDS TO THE CORRECT REPRESENTATION
!                FOR THE COMPUTER IIE IS RUNNING ON
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CIFF  /IFHEAD,IFLNTH,IFBUFL,IFBUFR,KDYNHD,KDYNLN,          &
     &              KDYNIF,KDYNFF,NXCIFF
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORL03/KLVELA,KLSTL2,KLSTH2,NXCL03
      COMMON/CTIDES/NTIDE,NSTADJ,NET,NETADJ,NETUN,NOT,NOTADJ,           &
     &   NOTUN ,NETUNU,NETADU,NOTUNU,NOTADU,NBSTEP,KTIDA(3),            &
     &   ILLMAX,NUNPLY,NNMPLY,NDOODN,MXTMRT,NRESP ,NXCTID
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
!SMCS ADDED COMMON BLOCK
      COMMON/NUTINF/NNUT,NNUTAA,NXNUTA
      COMMON/PLATE /NPLATE,MJDPLR,NPLTMS,NXPLAT
      COMMON/POLINF/NPOLE,NPOLEA,NUTA,MXUTC,NMODEL,NXPOLI
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
!
      DIMENSION AA(1)
      DIMENSION FFBUF(IFBUFR)
      DIMENSION IFFHDR(IFHEAD),IFFLEN(IFLNTH)
      DIMENSION II(1)
      DIMENSION LL(1)
!
      DATA IBLOCK/20/,IGROUP/3/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!**********************************************************************
! READ HEADER RECORD FOR REAL DATA
!**********************************************************************
      ITYPE=1
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS=NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR REAL DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE LAST WORD READ WHICH IS THE SUM OF THE LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR REAL DATA
!**********************************************************************
      IREC=0
      IWORDS=0
! KDPSR/DPSR - START TIMES FOR POLAR MOTION INTERVALS
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDPSR),NX,ISTAT)
! KSTNAM/STANAM - STATION NAMES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRDC(IUNT11,AA(KSTNAM),NX  )
! KA1UT/A1UTC  - A1-UTC TIME DIFFERENCE
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KA1UT),NX,ISTAT)
! KA1UT/A1UTC  - A1-UTC RATE
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KA1UT+MXUTC),NX,ISTAT)
! KA1UT/A1UTC  - TIME OF A1-UTC CORRECTION
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KA1UT+2*MXUTC),NX,ISTAT)
! KSTAIN/STAINF  - STATION ARRAY INFORMATION
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTAIN),NX,ISTAT)
! KPLTIN/PLTINF  - PLATE INFORMATION (ANG. VEL.,LAT,LONG)
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KPLTIN),NX,ISTAT)
! KPLTVL/PLTVEL  - PLATE VELOCITY
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KPLTVL),NX,ISTAT)
! KPUTBH/PUTBIH  - BIH VALUES FOR POLE/UT AT POLEUT TIMES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KPUTBH),NX,ISTAT)
! KSPEED/SPEED   - ANGULAR VELOCITY FOR OLOAD FREQUENCIES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSPEED),NX,ISTAT)
! KANGFC/ANGFAC  - COEFFICIENTS FOR ANGULAR ARGS FOR OLOAD FREQS
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KANGFC),NX,ISTAT)
! KSTVEL/STAV    - STATION VELOCITIES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTVEL),NX,ISTAT)
! KSTVDV/STAVD   - DERIVATIVES FOR STATION VELOCITIES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTVDV),NX,ISTAT)
! KTIMVL/STAVT   - TIMES FOR STATION VELOCITIES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KTIMVL),NX,ISTAT)
! KSTEL2/STEL2   - STATION ETIDE L2
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTEL2),NX,ISTAT)
! KSTEH2/STEH2   - STATION ETIDE H2
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTEH2),NX,ISTAT)
! KSL2DV/STL2DV  - DERIVATIVES FOR STATION ETIDE L2
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSL2DV),NX,ISTAT)
! KSH2DV/STH2DV  - DERIVATIVES FOR STATION ETIDE H2
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSH2DV),NX,ISTAT)
!
!>>>>>>>>>>>>>
! KAPRES/APRESS  - station pressure values
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KAPRES),NX,ISTAT)
!
! KASCAL/ASCALE  - station pressure scaling values
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KASCAL),NX,ISTAT)
!
! KASOFF/ASTOFF  - station height offsets
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KASOFF),NX,ISTAT)
! KANGT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KANGT),NX,ISTAT)
!
! KSPDT  -
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSPDT),NX,ISTAT)
!
! KOTSGN
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KOTSGN),NX,ISTAT)
!
! KANFSD
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KANFSD),NX,ISTAT)
!
! KSPDSD
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSPDSD),NX,ISTAT)
!
! KALCOF/ALCOEF  - atmospheric loading pressure coefficients
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KALCOF),NX,ISTAT)
!SMCS
!       write(6,*) "IFRGD3: KALCOF :", KALCOF
!
! KNUTIN/DNUTIN - interval length for nutation parms
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KNUTIN),NX,ISTAT)
!SMCS
!       write(6,*) "IFRGD3: KNUTIN :", KNUTIN
!
! KNUTMD/DNUTMD - midpoint times for nutation interval
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KNUTMD),NX,ISTAT)
!
!
!<<<<<<<<<<<<<
!
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
!**********************************************************************
! READ HEADER RECORD FOR INTEGER DATA
!**********************************************************************
      ITYPE=2
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS =NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR INTEGER DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE SUM OF RECORD LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR INTEGER DATA
!**********************************************************************
      IREC=0
      IWORDS=0
! KICRD/ICRD - STATION COORDINATE SYSTEM FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KICRD),IFFLEN(IREC) )
! KICON/ICON - STATION MASTER/CONSTRAINED FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KICON),IFFLEN(IREC) )
! KISTNO/ISTNO - STATION NUMBERS
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KISTNO),IFFLEN(IREC) )
! KINDPI/INDPI - INDEX ARRAY FOR POLAR MOTION
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KINDPI),IFFLEN(IREC) )
! KMJDPL/MJDPLT - PLATE MOTION TIMES
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KMJDPL),IFFLEN(IREC) )
! KIPOLC/IPOLCD - RELATES POLE INTERVALS TO ORIGINAL POLEUT CARDS
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIPOLC),IFFLEN(IREC) )
! KNDOLA/NDROLA - NUMBER OF ADJUSTED FREQS IN EACH DIR AT EACH SITE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KNDOLA),IFFLEN(IREC) )
! KIOLPA/IOLDPA - INTERNAL FREQ NO'S IN EAC DIR AT EACH SITE ADJ
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIOLPA),IFFLEN(IREC) )
! KKIOLA/KIOLA  - POINTER TO IOLDPA
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KKIOLA),IFFLEN(IREC) )
! KIP0OL/IPV0OL - POINTER TO PARMV0 IN EACH DIR AT EACH SITE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIP0OL),IFFLEN(IREC) )
! KNDOLM/NDROLM - NUMBER OF MODELLED FREQS IN EACH DIR AT EACH SITE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KNDOLM),IFFLEN(IREC) )
! KIOLPM/IOLDPM - INTERNAL FREQ NO'S IN EAC DIR AT EACH SITE MODELLED
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIOLPM),IFFLEN(IREC) )
! KKIOLM/KIOLM  - POINTER TO IOLDPM
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KKIOLM),IFFLEN(IREC) )
! KIPVOL/IPVOL - POINTER TO PARMV IN EACH DIR AT EACH SITE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIPVOL),IFFLEN(IREC) )
! KICNL2/ICNL2 - STATION ETIDE L2 FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KICNL2),IFFLEN(IREC) )
! KICNH2/ICNH2 - STATION ETIDE H2 FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KICNH2),IFFLEN(IREC) )
!
!>>>>>>>>>>>>>>>>
! KSTMJD/MJDST - station height offset times
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KSTMJD),IFFLEN(IREC) )
! KNUMST/NUMST - number of times/station array for station heights
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KNUMST),IFFLEN(IREC) )
! KITAST/ITAST - index array for station height offsets
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KITAST),IFFLEN(IREC) )
! KSTNRD/NSTRD - station number array for station height offsets
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KSTNRD),IFFLEN(IREC) )
!<<<<<<<<<<<<<<<<
! KICNV/ICNV - STATION VELOCITIES ICON
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KICNV),IFFLEN(IREC) )
! KTIDES/INTIDE - STANDARD TIDES DEGREE AND ORDER ARRAY
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KTIDES),IFFLEN(IREC) )
! KFODEG/IFODEG E/O TIDES FORCING DEGREE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KFODEG),IFFLEN(IREC) )
! KFOORD/IFOORD E/O TIDES FORCING ORDER
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KFOORD),IFFLEN(IREC) )
! KRDEGR/IRDEGR E/O TIDES RECEIVING DEGREE
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KRDEGR),IFFLEN(IREC) )
! KRORDR/IRORDR E/O TIDES RECEIVING ORDER
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KRORDR),IFFLEN(IREC) )
! KPHINC/IPHINC  E/O TIDES PHASE INCREMENT
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KPHINC),IFFLEN(IREC) )
! KDOODS/IDOODS  E/O TIDES DOODSON NUMBER
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KDOODS),IFFLEN(IREC) )
! KOTFLG/IOTFLG E/O TIDES FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KOTFLG),IFFLEN(IREC) )
! KJDN/  Unique DOODSON number array for RAY tides
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KJDN),IFFLEN(IREC) )
! KPTDN/  Mapping array for RAY tides
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KPTDN),IFFLEN(IREC) )
! KATIND/  Mapping array for Atmospheric tides
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KATIND),IFFLEN(IREC) )
! KSITE/ISITE - ATM LOADING SITES
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KSITE),IFFLEN(IREC) )
!
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
!**********************************************************************
! READ HEADER RECORD FOR LOGICAL DATA
!**********************************************************************
      ITYPE=3
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS =NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR LOGICAL DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE SUM OF DATA RECORD LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR LOGICAL DATA
!**********************************************************************
      IREC=0
      IWORDS=0
!
!
! LOGICAL DATA RECORDS GO HERE
! KLVELA/LVELA - STATION VELOCITY ADJUSTMENT FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRDL(IUNT11,LL(KLVELA),IFFLEN(IREC) )
! KLSTL2/LSTL2 - STATION ETIDE L2 ADJUSTMENT FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRDL(IUNT11,LL(KLSTL2),IFFLEN(IREC) )
! KLSTH2/LSTH2 - STATION ETIDE H2 ADJUSTMENT FLAG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRDL(IUNT11,LL(KLSTH2),IFFLEN(IREC) )
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
      RETURN
!**********************************************************************
! ERROR PROCESSING
!**********************************************************************
!
! RECORD SIZE EXCEEDS BUFFER SPACE
60100 WRITE(IOUT6,80100) ITYPE,NX,IFBUFR
      WRITE(IOUT6,89999)
      STOP
! NUMBER OF RECORDS READ DISAGREES WITH NUMBER OF LENGTHS EXPECTED
60200 WRITE(IOUT6,80200) ITYPE,IREC,NRECS
      WRITE(IOUT6,89999)
      STOP
! NUMBER OF WORDS SENT DISAGREES WITH NUMBER OF WORDS EXPECTED
60300 WRITE(IOUT6,80300) ITYPE,NWORDS,IWORDS
      WRITE(IOUT6,89999)
      STOP
! BLOCK NUMBER,GROUP NUMBER OR RECORD TYPE INCORRECT
60400 WRITE(IOUT6,80400) IBLOCK,IGROUP,ITYPE,IFFHDR
      WRITE(IOUT6,89999)
      STOP
80000 FORMAT(1X,'UNEXPECTED END OF FILE ON UNIT ',I2,' FOR DATA TYPE ', &
     & I2)
80100 FORMAT(1X,'RECORD SIZE EXCEEDS BUFFER SPACE AVAILABLE. ITYPE,NX,' &
     &'IFBUFR FOLLOW: '/1X,3I10)
80200 FORMAT(1X,'NUMBER OF TYPE (',I2,') RECORDS READ FROM INTERFACE ',&
     &'FILE DISAGREES WITH NUMBER OF LENGTHS EXPECTED',2I5)
80300 FORMAT(1X,'SUM OF RECORD LENGTHS FROM IFF LENGTHS RECORD DOES ',&
     &'NOT AGREE WITH SUM CALCULATED',3I6)
80400 FORMAT(1X,'BLOCK NUMBER,GROUP NO. OR DATA TYPE IS INCORRECT',2I5/ &
     &1X,20I5)
89999 FORMAT(1X,'EXECUTION TERMINATING IN SUBROUTINE IFRGD3 ')
      END
