!$IFRGCB
      SUBROUTINE IFRGCB(IFFHDR,IFFLEN,FFBUF)
!********1*********2*********3*********4*********5*********6*********7**
! IFRGCB           00/00/00            0000.0    PGMR - ?
!
! FUNCTION:  READ GLOBAL COMMON BLOCK INFORMATION FROM INTERFACE
!            FILE
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   IFFHDR   I    A    ARRAY USED TO READ HEADER INFORMATION
!                      IFFHDR(IFHEAD)
!   IFFLEN   I    A    ARRAY USED TO READ LENGTHS OF ALL
!                      DATA RECORDS IN THIS INTERFACE
!                      BLOCK. IFFLEN(IFLNTH)
!   FFBUF    I    A    SCRATCH ARRAY USED STORING REAL DATA BEFORE
!                      CONVERSION
!
! COMMENTS:
!                  WHEN ADDING COMMON BLOCKS TO THIS ROUTINE
!                    1. ADD COMMON BLOCK NAME TO PROPER GROUP
!                    2. VERIFY THAT LAST VARIABLE IN COMMON BLOCK LIST
!                       CONTAINS SIZE OF COMMON BLOCK
!                    3. DIMENSION AQXXXX(1),IQXXXX(1),OR ILXXXX(1)WHERE
!                       XXXX IS THE LAST 4 LETTERS OF THE LENGTHS
!                       VARIABLE IN THE COMMON BLOCK
!                    4. ADD EQUIVALENCE STATEMENT FOR NEW COMMON
!                    5. INCREMENT ICOM IN PROPER GROUP AND CALL BINRD
!                        TO READ DATA RECORD FROM INTERFACE FILE
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      CHARACTER*8 CBLKTY
!
! COMMON BLOCKS USED BY THIS ROUTINE BUT NOT RECEIVED FROM IFF
!
      COMMON/CIFF  /IFHEAD,IFLNTH,IFBUFL,IFBUFR,KDYNHD,KDYNLN,          &
     &              KDYNIF,KDYNFF,NXCIFF
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
!
! COMMON BLOCKS RECEIVING REAL DATA FROM THE IFF
!
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CEPHEP/FSCEPC(1),EPHBFC(1016),                             &
     &              FSCEPT(1),EPHBFT(1016),                             &
     &              SEPBFC(75),SEPBFT(75),XEPHEP
      COMMON/CGVTMR/EPGVTM,ELAPGT,XCGVTR
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/COREPH/EMJDS0(2),EFSEC0(2),EMODE(2),ECORR(2),              &
     &              PSTAE0(12),DEBC(12),SGMEBC(12),BODYID(2),XCOEPH
      COMMON/DELUT1/UTTDAM(41),XDELUT
      COMMON/DPLNOR/DXGEO1,DXGEO2,DXFRC1,DXFRC2,XPLNOR
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/DYNPOL/DPMEP ,DPMXP ,DPMYP ,DPMXDT,DPMYDT,DPMOPT,DPMXPC,   &
     &              DPMYPC,DPMKF ,DPMC21,DPMS21,DPMPD ,DPMUDK,DPMVDK,   &
     &              DPMOCP,DPMNLD,DPMERS,XDYNPL
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/FLUXAU/FLX1AU,XFLUXA
      COMMON/G2SINF/G2SVER,G2SDAT,G2SRTM,G2SCOM,TDFVER,TDFRTM,SETCDS,   &
     &              GPCKSM,GPDEG ,GPORD ,XG2SIN
      COMMON/G2SINC/GRVDES(9),XG2SIC
      COMMON/GCMMOD/GCMNPS,GCMT0,GCMPER(10),GCMAMP(30),GCMPHA(30),      &
     &              XXGCM
      COMMON/ION2ER/STEPSZ,XIONR
      COMMON/INVRSA/EPSIN1,EPSIN2,TOLRNC,XINVRS
      COMMON/MREFDT/DMESRF,RMESRF,XMREF
      COMMON/NETCON/TRANET(3,2),ROTNET(3,2),ROTQUA(3,2),XNETC
      COMMON/PARFIL/PFSW  ,PFUNT1,PFUNT2,PFNUMB,SEGSIZ,XPARFI
      COMMON/POLRAT/XPD(15000),YPD(15000),A1D(15000),TIMEPR(15000),XPOLR
      COMMON/PMARS /DTM74 ,XPMARS
      COMMON/RMODEL/PERMOD(3,12),XRMOD
      COMMON/SATCUT/CUTSAT,XSATCU
      ! FANTOM
      COMMON/SPOOKY/EPTIME(4),STFTIM(4),SPOOK1(4),SPOOK2(4),XSPOOK
      COMMON/RLOCGR/RLATLG,RLONLG,GAMMA,HANOM,XRLOC
      COMMON/ROBTYP/CONVRT(999),OBSCAL(999),RESCAL(999),                &
     &              XMTYP
      COMMON/ROTELM/ALF020,ALFR20,DEC020,DECR20,W020,WR20,X100,WRR20,  &
     &               XR100,XA100,THXTGC2S(3),XROTLM
      COMMON/ROTEL2/ALF0202,ALFR202,DEC0202,DECR202,W0202,WR202,X1002, &
     &              WRR202,  &
     &               XR1002,XA1002,THXTGC2S2(3),XROTLM2
      COMMON/ROTEL5/ALF050,ALFR50,DEC050,DECR50,W050,WR50,X1005,       &
     &               XA1005,THXTGC22S(3),XROTL5
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
      COMMON/YARSCH/YARTYP,YARMOD,AYAR,TAU,RISYEN,FSEYEN,RISYEX,FSEYEX, &
     &              SMEANM,XYARMD
!
! COMMON BLOCKS RECEIVING INTEGER DATA FROM THE IFF
!
      COMMON/AGRAV /NACSET,NADEG,NAORD,IAGCB,IAGCE,IDATB,IDATE,INTAG,   &
     &KCOUNT,KSKIP,INTC21,NXAGRA
      COMMON/APHASE/NANT_sat,NANTPS_sat(999),KANTPS_sat(999),           &
     &              nant_sta,NANTPS_sta(999),KANTPS_sta(999),           &
     &              NANTPT,  NANTPS(999),    KANTPS(999), NANTMT(99),   &
     &              NNUMMT, NXAPHA
      COMMON/BIHTBL/IA1UTC,JA1UTC,IPOLA1,JPOLA1,IFLUXS,JFLUXS,IFLXAP,   &
     &              JFLXAP,IFLXKP,JFLXKP,IIONO,JIONO,                   &
     &              NVR(6),NUTC  ,IBIH  ,JBIH  ,                        &
     &              IFLUX ,JFLUX ,IBHSYS,IBHDAT,IBHTIM,IFLXSF,          &
     &              IBIHTL(2),IBIHHR,JBIHHR,NXBIHT
      COMMON/BINBUF/NBUFIN,NLENI ,MAXBUF,MAXOBS,NBUFOT,NLENO ,NMAXOT,   &
     &              KBUFOT,MXBLEN,MAXTDD,NLENDR,MOBSBK,MXTIMB,          &
     &              MXOBSB,IIOBDR,IPSMAX,ILIMBK,NPASS ,MVERSN,NXBINB
      COMMON/CEBGLB/MEPARM,MEDIM ,MEBIAS,MBIASE,NEBGRP,IEBGRP(4),NXCEBG
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CGVTMI/NCDT,NSDT,NCPD,NSPD,NCDTA,NSDTA,NCPDA,NSPDA,NGRVTM, &
     &       KCDT,KCPDA,KCPDB,KSDT,KSPDA,KSPDB,KOMGC,KOMGS,KCOMGC,      &
     &       KSOMGC,KCOMGS,KSOMGS,NXGVTI
      COMMON/CIOCON/NUMCON(15),NESCON(15),NUMIND,NXCON
      COMMON/CIOTMD/NOTPT,NOTPRF,NODEG,NXCIOT
      COMMON/CISSTM/NSSTPT,NSSTF,NSDEG,NXCISS
      COMMON/CITERG/MARC,MGLOBL,MGLOBM,                                 &
     &              MGLOCV,NXITRG
      COMMON/CLASCI/LASCII,LIFCYB,LARECL,NXLASC
      COMMON/CSHAD/NSBDY,NSBDY1,NXSHAD
      COMMON/CMETI /MODEL(999),MWET(999),MDRY(999),MODESC(999),        &
     &              MAPWET(999),MAPDRY(999),METP(999),IRFRC,           &
     &              IRFPRT(10),NXCMTI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORE2E/KORE2E(3,7),KSCL2E(3),NGRP2E,MACH2E,KCOM2E,NXCORE
      COMMON/CORE2S/KORE2S(3,2),KSCL2S(3),NGRP2S,MACH2S,KCOM2S,MAXC2E,  &
     &              NXCORS
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI05/KNOBGL,KNOBWG,KNOBTY,KNOBWY,KNOBST,KNOBWT,KNEBOB,   &
     &              KJSTAT,NXCI05
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL03/KLVELA,KLSTL2,KLSTH2,NXCL03
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CORL05/KLGPRV,NXCL05
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CORL07/KLPTS,NXCL07
      COMMON/CORREQ/KORESM,NXRREQ
      COMMON/CPARTI/MAXLP ,KORSIZ,MAXWRK,                               &
     &              IUNTP1,IUNTP2,IUNTPF,ISIZPF,IRECPF,NRECPF,          &
     &              NPDONE,NP1   ,NP2   ,NRECND,NPDIM ,NXPARI
      COMMON/CRDDIM/NDCRD2,NDCRD3,NDCRD4,NDCRD5,NDCRD6,NDCRD7,          &
     &              NDCRD8,NDCRD9,NXCRDM
      COMMON/CSTATS/MSTATS,MTYPES,NXCSTT
      COMMON/CTIDES/NTIDE,NSTADJ,NET,NETADJ,NETUN,NOT,NOTADJ,           &
     &   NOTUN ,NETUNU,NETADU,NOTUNU,NOTADU,NBSTEP,KTIDA(3),            &
     &   ILLMAX,NUNPLY,NNMPLY,NDOODN,MXTMRT,NRESP ,NXCTID
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/DELOFF/NOFFST,NSATDL,NSTADL,NCGMAS,NXDELO
      COMMON/DYNPTR/KDEPHM,KDEPH2,KDAHDR(3,9),KDYNAP(3,9,2),KDNEXT(3),  &
     &NXDYNP
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/GEODEG/NMAX,NMAXP1,NP,NTOLD,NTOLO,NADJC,NADJS,NADJCS,      &
     &              NPMAX,NXGDEG
      COMMON/GEOMCS/MDEGEO,MORGEO,NPGEOM,NXGEOM
      COMMON/GRANI/NSUBLG,NXGRAN
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IOBTYP/NDXST(2,35),NDXSAT(2,35),                           &
     &      NDRSTA(50),NDRSAT(50),NDRST2(50),NDRSA2(50),                &
     &      ITMBIT(999),IOETR(999),MTYPED(11),NTYPES,                   &
     &      NM0112(4),NM1314(4),NM1522(4),NM2330(4),                    &
     &      NM3138(4),NM3997(4),NM4098(4),NM9900(4),NMT199(4),NMT203(4),&
     &      NS0112(4),NS1314(4),NS1522(4),NS2330(4),                    &
     &      NS3138(4),NS3997(4),NS4098(4),NS9900(4),NST199(4),NST203(4),&
     &      ITYPD(12,2),ITYPDD(7,2),ILINKF(5),ISTAFN(5,3),              &
     &      ISATFN(5,3),ILINKT(5),ISTATN(5,3),ISATTN(5,3),              &
     &      MGOTO(12),MENTER(12),MEXIT(12),                             &
     &      NDST60(3,24),NDST82(6,12),NDST92(12,7),NTDRSS,              &
     &      NDSA60(3,24),NDSA82(6,12),NDSA92(12,7),                     &
     &      MTDRSS(7),KTDRSS(7),ITDRSS(4,7),JTDRSS(4,7),                &
     &      NLLC60(5,24),NLLC82(10,12),NLLC98(20,7),NNBIA,              &
     &      NXMTYP
      COMMON/IONO2E/IONNDX(12),IONRZ(12),IONOYM(12),IONYMS,IONYME,IURSI,&
     &              INTERP,NXIONO
      COMMON/IPLMOD/NFMOD,NSMOD,NFTOT,NSTOT,IDFMOD(1000),IDSMOD(1000), &
     &             NFPARAM(1000),&
     &             NPMIND(1000),NSPARAM(1000),NPSIND(1000),NXPLMD
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/MODEL /NPRM(10,2,5),ICROSS,MJD01,ISSTMD,NXMODL
      COMMON/NGRIDS/NCTGRD,NREFER(6),NCENTR(6),NXGRID
      COMMON/NHINPT/NH1VOC,NXNHIN
      COMMON/NLIGHT/KNTLIM,NXNLIT
      COMMON/NLOCGR/INTEGG,IOPTLG,ICUTLG,MAXDO,NLOCAL,NLATLG,NLONLG,    &
     &              nlocgu, nlocga, nxlocg
      COMMON/NLRA/NLRARC,NLRAIN,NLRAD1,NLRAD2,NLRAPT,NLRAST,NSARAL, &
     &            NXNLRA
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/NUTINF/NNUT,NNUTAA,NXNUTA
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      COMMON/PLATE /NPLATE,MJDPLR,NPLTMS,NXPLAT
      COMMON/PLMONI/IMNNUM(5,2),NXPLMI
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      COMMON/PLTOPO/IBDTOP,NXPLTP
      COMMON/POLINF/NPOLE,NPOLEA,NUTA,MXUTC,NMODEL,NXPOLI
      COMMON/SATPIN/MAXDS,NGSAT1,NXSATP
      COMMON/SETDI /NSETDP,NFRSED,NFRSDI,NFRSLN,NXSETI
      COMMON/SSTCOM/NCBAR, NSBAR ,NCDOT ,NSDOT ,NCAPRD,NCBPRD,NSAPRD,   &
     &              NSBPRD,NCBARA,NSBARA,NCDOTA,NSDOTA,NCAPDA,NCBPDA,   &
     &              NSAPDA,NSBPDA,ISSTEP,NXSST
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/TPGRAV/NTPGCU,NTPGCA,NTPGSU,NTPGSA,ITPGRV,NTIMEC,NTIMES,   &
     &              NXTPGR
      COMMON/VLBI/NQUA,NADJQ,NADJQV,NQUAB,IYMDV,NVOPT,NXVLBI
      COMMON/XEPHMI/IBLKXE,IBLKXL,IBLKXP(2),IXEPRW,IXEPRD,              &
     &              IXEPB1,IXEPB2,IXBFS(2),IXBFE(2),                    &
     &              MJXEPS,IXPSAT(200),NXPSAT,MXPBFR,                   &
     &              NEPPBK,IXEPEF,IUNTXE,NXXEPH
      COMMON/EXATGI/MEASAT,MEAFIL,MEAMEM,MEAPLA,MEAANT,NXEAGI
      COMMON/EXTAGI/MTASAT,MTAFIL,MTAMEM,MTAPLA,NXTAGI

!      FANTOM
      COMMON/CASPER/NFGGLB,NFFGLB,NFGARC,NFFARC,NGGA,NGFA,NAGA,NAFA,    &
     &              NFANEP,NFDIR(4),NSATFA(2,200),NFANTM,NXCASP
      COMMON/TARGET/NLXYZ(200000),NPLTAR,NTARG,NATARG,NXTARG

      COMMON/TDGRDS/MTMG,MTMG1,MTMG2,MTMG3,MTMG4,NXTDRG
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
      COMMON/XPCNT2/NXTRAC2,NXFLAG2,NXALLC2,NCPPER2,NMINRT2,NDPOR2,     &
     &              NXXTR2
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/NALOAD/NSITES,NALFIL,NALSIT,MAXSIT,ITOTAL,MAXAPL,ITAPLB,   &
     &              ITAPLE,IAPLDT,NXLOAD
      COMMON/MULTDM/MLTDEM,MEMDEM,NXMDEM
!
! COMMON BLOCKS RECEIVING LOGICAL DATA FROM THE IFF
!
      COMMON/CALTOP/LADYNO,LAGEOO,LRGEOT,LRETDT,LROTDT,LRSSTT,LCOTRM,   &
     &              LFILOT,LATCOR,LFIRIT,LX1ALT,LX2ALT,LMSSWG,LATMOD,   &
     &              LG1BOT,LG1B,LONEG1,LXATTD,LXBEAM,NXALTO
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CGLBAR/LGDRAG,NXGLAR
      COMMON/CLGEOP/LGEOPL,LGPLOR,NXCLGP
      COMMON/CLNORM/LNRMGI,NXNORM
      COMMON/CLSSOT/LSSTMO,LOTMOD,LPRDES,NXLSST
      COMMON/CLVIEW/LNPRNT(18),NXCLVI
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/DWNWGT/LDWNWT,LDNWMT(999),NXDWNW
      COMMON/FANTOM/LFGLB,LFARC,LFTARC,LFTGLB,LENDGL,LPHNTM(4),LPHTIM(4)&
     &             ,LXTRAF,LSATFA(4,3),NXFANT
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      COMMON/GBINRL/LBINRG,NXGBIN
      COMMON/INVRSL/LSYMSW,LMATP,NXINVR
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/LASTER/LASTR(2),LBINAST,NXASTR
      COMMON/LICASE/LINT(2),LCASE(18),NXLCAS
      COMMON/LNUTAT/LSPNUT,NXLNUT
      COMMON/LOBTYP/L2WAYS(31),LODD(11),NXLTYP
      COMMON/LSWTCH/LFLXPR,LMALL,LPGRAV,LST50,LST50I,LTERMV,LST17,      &
     &             NXLSWT
      COMMON/LSFSHD/LSLFSH, NXSLFS
      COMMON/POLESW/LDNPOL,NXPOLS
      COMMON/PUNCH /LPNCH ,LPNALL,LPNADJ,LPNITR,NXPUNC
      COMMON/SHIRTS/LNSNS,NXNSNS
      COMMON/TRPOUT/LTROUT,NXLTPO
      COMMON/EXATGL/LEXATT,NXEAGL
      COMMON/EXTAGL/LEXTHC,NXTAGL
      COMMON/TIDALC/LRAY,LOLDST,NXTIDL
!
      DIMENSION CBLKTY(3)
      DIMENSION IFFHDR(IFHEAD),IFFLEN(IFLNTH)
      DIMENSION FFBUF(IFBUFR)
!
! SET UP DUMMY ARRAYS FOR EQUIVALENCING TO COMMON BLOCKS
!
! *REAL*     ALL DUMMY REAL ARRAYS START WITH AQ FOLLOWED BY
!            THE SAME FOUR LETTERS USED AFTER X IN THE LAST
!            VARIABLE NAME IN THE COMMON BLOCK
!
      DIMENSION AQBDST(1),AQGVTR(1),AQCLIT(1),AQDELU(1)
      DIMENSION AQDYNP(1),AQEPHS(1),AQG2SI(1),AQG2SC(1)
      DIMENSION AQINVR(1),AQPARF(1),AQRTYP(1),AQFLUX(1)
      DIMENSION AQLOCG(1),AQCEPH(1),AQEPHE(1),AQSATC(1)
      DIMENSION AQXTRA(1),AQSPOK(1),AQIONR(1),AQMREF(1)
      DIMENSION AQRMOD(1),AQTMGN(1),AQPOLR(1),AQYARK(1)
      DIMENSION AQNETC(1),AQPLNO(1),AQROTL(1),AQROT5(1)
      DIMENSION AQPMAR(1),AQGCMM(1),AQROTL2(1)
!
! *INTEGER*  ALL DUMMY INTEGER ARRAYS START WITH IQ FOLLOWED BY
!            THE SAME FOUR LETTERS USED AFTER NX IN THE LAST
!            VARIABLE NAME IN THE COMMON BLOCK
!
      DIMENSION IQAPHA(1)
      DIMENSION IQBIHT(1),IQCEBG(1),IQCEST(1),IQGVTI(1),IQITRG(1)
      DIMENSION IQCIOC(1),IQCIOT(1),IQCISS(1)
      DIMENSION IQBINB(1),IQAGRA(1)
      DIMENSION IQCMTI(1),IQCNIG(1),IQCOBG(1),IQSHAD(1)
      DIMENSION IQCA01(1),IQCA02(1),IQCA03(1),IQCA04(1),IQCA05(1)
      DIMENSION IQCA06(1),IQCA07(1)
      DIMENSION IQCORE(1),IQCORS(1)
      DIMENSION IQCI01(1),IQCI02(1),IQCI03(1),IQCI04(1),IQCI05(1)
      DIMENSION IQCI06(1),IQCI07(1)
      DIMENSION IQCL01(1),IQCL02(1),IQCL03(1),IQCL04(1),IQCL05(1)
      DIMENSION IQCL06(1),IQCL07(1)
      DIMENSION IQPARI(1),IQNHIN(1)
      DIMENSION IQRREQ(1),IQCRDM(1),IQCSTA(1)
      DIMENSION IQCTID(1),IQCVUE(1),IQDELO(1),IQDYNP(1)
      DIMENSION IQGEOM(1),IQBDPT(1)
      DIMENSION IQEPHP(1),IQGDEG(1),IQNLIT(1),IQNPCM(1),IQNPCX(1)
      DIMENSION IQOLMD(1)
      DIMENSION IQPLAT(1),IQPLNI(1),IQPOLI(1),IQSTAT(1),IQTPGR(1)
      DIMENSION IQRTYP(1),IQSST(1),IQVLBI(1)
      DIMENSION IQLOCG(1),IQPLMI(1),IQPLTP(1),IQNLRA(1)
      DIMENSION IQXEPH(1),IQEAGI(1),IQTAGI(1)
      DIMENSION IQCASP(1)
      DIMENSION IQIONO(1)
      DIMENSION IQIPLN(1)
      DIMENSION IQORCH(1)
      DIMENSION IQMODL(1)
      DIMENSION IQTARG(1)
      DIMENSION IQTDGR(1)
      DIMENSION IQXPCN(1)
      DIMENSION IQXPCN2(1)
      DIMENSION IQEPH2(1)
      DIMENSION IQNGRD(1)
      DIMENSION IQFORC(1)
      DIMENSION IQGRAN(1)
      DIMENSION IQSETI(1)
      DIMENSION IQAPLD(1)
      DIMENSION IQSATP(1)
!SMCS
      DIMENSION IQNUTA(1)
      DIMENSION IQMLTD(1)
!
! *LOGICAL*  ALL DUMMY LOGICAL ARRAYS START WITH IL FOLLOWED BY
!            THE SAME FOUR LETTERS USED AFTER NX IN THE LAST
!            VARIABLE NAME IN THE COMMON BLOCK
!
      DIMENSION ILCSTL(1),ILUNT9(1),ILGBIN(1),ILLSWT(1),ILPOLS(1)
      DIMENSION ILPUNC(1),ILPARL(1),ILCLVI(1),ILCLGP(1),ILINVR(1)
      DIMENSION ILALTO(1),ILNORM(1),ILEGRL(1),ILCASE(1),ILBTYP(1)
      DIMENSION IGLBAR(1),ILEAGL(1),ILTAGL(1)
      DIMENSION ILSSOT(1)
      DIMENSION ILFANT(1),ILLTPO(1),ILNSNS(1)
      DIMENSION ILIONO(1)
      DIMENSION ILNUTA(1)
      DIMENSION ILGPS(1)
      DIMENSION ILTIDE(1)
      DIMENSION ILSLFS(1)
      DIMENSION ILASTR(1)
      DIMENSION ILDWNW(1)
!
!
! EQUIVALENCES FOR COMMON BLOCKS TO BE RECEIVED
!
!  *REAL*
!                  CBDSTA                  CEPHEP
      EQUIVALENCE (AQBDST(1),BDSTAT(1,1)),(AQEPHE(1),FSCEPC(1))
!                  CGVTMR                  CLIGHT
      EQUIVALENCE (AQGVTR(1),EPGVTM     ),(AQCLIT(1),VLIGHT     )
!                  COREPH                  DELUT1
      EQUIVALENCE (AQCEPH(1),EMJDS0(1)  ),(AQDELU(1),UTTDAM(1))
!                  DYNPOL                  EPHSET
      EQUIVALENCE (AQDYNP(1),DPMEP      ),(AQEPHS(1),EMFACT)
!                  FLUXAU
      EQUIVALENCE (AQFLUX(1),FLX1AU)
!                  G2SINF                  INVRSA
      EQUIVALENCE (AQG2SI(1),G2SVER     ),(AQINVR(1),EPSIN1)
!                  G2SINC
      EQUIVALENCE (AQG2SC(1),GRVDES(1)  )
!                  PARFIL                  ROBTYP
      EQUIVALENCE (AQPARF(1),PFSW       ),(AQRTYP(1),CONVRT(1))
!                  RLOCGR                  RMODEL
      EQUIVALENCE (AQLOCG(1),RLATLG),(AQRMOD(1),PERMOD(1,1))
!                  SATCUT
      EQUIVALENCE (AQSATC(1),CUTSAT)
!                  XTRAOR                  SPOOKY (FANTOM)
      EQUIVALENCE (AQXTRA(1),T0XTRO),(AQSPOK(1),EPTIME(1))
!
      EQUIVALENCE (AQIONR(1),STEPSZ),(AQMREF(1),DMESRF)
!                                          POLRAT
      EQUIVALENCE (AQTMGN(1),TGTYMD),(AQPOLR(1),XPD(1))
!                  YARSCH                  NETCON
      EQUIVALENCE (AQYARK(1),YARTYP),(AQNETC(1),TRANET(1,1))
!                  DPLNOR
      EQUIVALENCE (AQPLNO(1),DXGEO1)
!                  ROTELM                  ROTEL5
      EQUIVALENCE (AQROTL(1),ALF020),(AQROT5(1),ALF050)
!                  ROTEL2
      EQUIVALENCE (AQROTL2(1),ALF0202)
!                  PMARS
      EQUIVALENCE (AQPMAR(1),DTM74 ),(AQGCMM(1),GCMNPS)
!
!  *INTEGER*
!                  APHASE
      EQUIVALENCE (IQAPHA(1),nant_sat)
!                  BIHTBL             CEBGLB
      EQUIVALENCE (IQBIHT(1),IA1UTC),(IQCEBG(1),MEPARM)
!                  BINBUF             ATGRAV
      EQUIVALENCE (IQBINB(1),NBUFIN),(IQAGRA(1),NACSET)
!                  CESTIM             CGVTMI
      EQUIVALENCE (IQCEST(1),MPARM), (IQGVTI(1),NCDT)
!                  CIOCON
      EQUIVALENCE (IQCIOC(1),NUMCON(1))
!                  CIOTMD             CISSTM
      EQUIVALENCE (IQCIOT(1),NOTPT), (IQCISS(1),NSSTPT)
!                  CITERG
      EQUIVALENCE (IQITRG(1),MARC)
!                  CMETI              CNIGLO
      EQUIVALENCE (IQCMTI(1),MODEL ),(IQCNIG(1),MINTIM)
!                  COBGLO
      EQUIVALENCE (IQCOBG(1),MABIAS)
!                  CORA01             CORA02
      EQUIVALENCE (IQCA01(1),KFSEC0),(IQCA02(1),KFSCTB)
!                  CORA03             CORA04
      EQUIVALENCE (IQCA03(1),KRFMT ),(IQCA04(1),KABIAS)
!                  CORA05             CORA06
      EQUIVALENCE (IQCA05(1),KOBTYP),(IQCA06(1),KPRMV )
!                  CORA07
      EQUIVALENCE (IQCA07(1),KELEVT)
!                  CORE2E
      EQUIVALENCE (IQCORE(1),KORE2E(1,1))
!                  CORE2S
      EQUIVALENCE (IQCORS(1),KORE2S(1,1))
!                  CORI01             CORI02
      EQUIVALENCE (IQCI01(1),KMJDS0),(IQCI02(1),KNTIME)
!                  CORI03             CORI04
      EQUIVALENCE (IQCI03(1),KICRD ),(IQCI04(1),KNMP  )
!                  CORI05             CORI06
      EQUIVALENCE (IQCI05(1),KNOBGL),(IQCI06(1),KPTRAU)
!                  CORI07
      EQUIVALENCE (IQCI07(1),KSMSA1)
!                  CORL01             CORL02
      EQUIVALENCE (IQCL01(1),KLORBT),(IQCL02(1),KLNDTT)
!                  CORL03
      EQUIVALENCE (IQCL03(1),KLVELA)
!                  CORL04             CORL05
      EQUIVALENCE (IQCL04(1),KLEDIT),(IQCL05(1),KLGPRV)
!                  CORL06
      EQUIVALENCE (IQCL06(1),KLBIAS)
!                  GRANI
      EQUIVALENCE (IQGRAN(1),NSUBLG)
!                  CORREQ             CRDDIM
      EQUIVALENCE (IQRREQ(1),KORESM),(IQCRDM(1),NDCRD2)
!                  CPARTI
      EQUIVALENCE (IQPARI(1),MAXLP)
!                  CSTATS             CSHAD
      EQUIVALENCE (IQCSTA(1),MSTATS),(IQSHAD(1),NSBDY)
!                  CTIDES             CVIEW
      EQUIVALENCE (IQCTID(1),NTIDE ),(IQCVUE(1),IOUT6)
!                  DELOFF             DYNPTR
      EQUIVALENCE (IQDELO(1),NOFFST),(IQDYNP(1),KDEPHM)
!                  EPHMPT
      EQUIVALENCE (IQEPHP(1),NTOT  )
!                  GEODEG
      EQUIVALENCE (IQGDEG(1),NMAX  )
!                  GEOMCS            IBODPT
      EQUIVALENCE (IQGEOM(1),MDEGEO),(IQBDPT(1),IBDCF(1))
!                  IOBTYP
      EQUIVALENCE (IQRTYP(1),NDXST(1,1))
!                  NHINPT
      EQUIVALENCE (IQNHIN(1),NH1VOC)
!                  NLIGHT             NPCOM
      EQUIVALENCE (IQNLIT(1),KNTLIM),(IQNPCM(1),NPNAME)
!                  NLOCGR
      EQUIVALENCE (IQLOCG(1),INTEGG)
!                  NLRA
      EQUIVALENCE (IQNLRA(1),NLRARC)
!                  OLDMOD
      EQUIVALENCE (IQOLMD(1),NTOLFR)
!                  NPCOMX             PLATE
      EQUIVALENCE (IQNPCX(1),IXARC ),(IQPLAT(1),NPLATE)
!                  PLMONI
      EQUIVALENCE (IQPLMI(1),IMNNUM(1,1))
!                  PLNETI
      EQUIVALENCE (IQPLNI(1),IPLNET(1))
!                  POLINF             SSTCOM
      EQUIVALENCE (IQPOLI(1),NPOLE ),(IQSST(1),NCBAR)
!                  SETDI
      EQUIVALENCE (IQSETI(1),NSETDP)
!                  STATN              TPGRAV
      EQUIVALENCE (IQSTAT(1),NSTA ),(IQTPGR(1),NTPGCU)
!                  PLTOPO
      EQUIVALENCE (IQPLTP(1),IBDTOP)
!                  VLBI               XEPHMI
      EQUIVALENCE (IQVLBI(1),NQUA ),(IQXEPH(1),IBLKXE)
!                  EXTAGI
      EQUIVALENCE (IQTAGI(1),MTASAT)
!                  EXATGI
      EQUIVALENCE (IQEAGI(1),MEASAT)
!                  CASPER (FANTOM)
      EQUIVALENCE (IQCASP(1),NFGGLB)
!                  IONO2E
      EQUIVALENCE (IQIONO(1),IONNDX(1))
!                  IPLMOD
      EQUIVALENCE (IQIPLN(1),NFMOD)
!                  IORCHB
      EQUIVALENCE (IQORCH(1),IORM)
!                  MODEL
      EQUIVALENCE (IQMODL(1),NPRM(1,1,1))
!                  TARGET
      EQUIVALENCE (IQTARG(1),NLXYZ(1))
!                  TDGRDS
      EQUIVALENCE (IQTDGR(1),MTMG)
!                  XPCNT
      EQUIVALENCE (IQXPCN(1),NXTRAC)
!                  XPCNT2
      EQUIVALENCE (IQXPCN2(1),NXTRAC2)
!                  IEPHM2
      EQUIVALENCE (IQEPH2(1),ISUPL)
!                  NGRIDS
      EQUIVALENCE (IQNGRD(1),NCTGRD)
!                  NFORCE
      EQUIVALENCE (IQFORC(1),NHRATE)
!                  NALOAD
      EQUIVALENCE (IQAPLD(1),NSITES)
!                  SATPIN
      EQUIVALENCE (IQSATP(1),MAXDS)
!SMCS              NUTINF                    MULTDM
      EQUIVALENCE (IQNUTA(1),NNUT),(IQMLTD(1),MLTDEM)
!
!
!  *LOGICAL*
!
!                 CALTOP             CLNORM
      EQUIVALENCE(ILALTO(1),LADYNO)   ,(ILNORM(1),LNRMGI)
!                 CLSSOT
      EQUIVALENCE(ILSSOT(1),LSSTMO)
!                 CESTML             CLGEOP
      EQUIVALENCE(ILCSTL(1),LNPNM )   ,(ILCLGP(1),LGEOPL)
!                 CGLBAR
      EQUIVALENCE(IGLBAR(1),LGDRAG)
!                 CLVIEW             CPARTL
      EQUIVALENCE(ILCLVI(1),LNPRNT(1)),(ILPARL(1),LPART)
!                 CUNIT9             GBINRL
      EQUIVALENCE(ILUNT9(1),L9SET ),(ILGBIN(1),LBINRG)
!                 INVRSL             LICASE
      EQUIVALENCE(ILINVR(1),LSYMSW),(ILCASE(1),LINT(1))
!                 LOBTYP
      EQUIVALENCE(ILBTYP(1),L2WAYS(1))
!                 LSWTCH             POLESW
      EQUIVALENCE(ILLSWT(1),LFLXPR),(ILPOLS(1),LDNPOL)
!                 PUNCH              CEGREL
      EQUIVALENCE(ILPUNC(1),LPNCH ),(ILEGRL(1),LGRELE)
!                  CORL07
      EQUIVALENCE (IQCL07(1),KLPTS)
!                  EXTAGL
      EQUIVALENCE (ILTAGL(1),LEXTHC)
!                  EXATGL               GPSBLK
      EQUIVALENCE (ILEAGL(1),LEXATT),(ILGPS(1),LGPS)
!                  FANTOM
      EQUIVALENCE (ILFANT(1),LFGLB)
!                  ION2EL
      EQUIVALENCE (ILIONO(1),LIONC)
!                  LNUTAT
      EQUIVALENCE (ILNUTA(1),LSPNUT)
!                  SHIRTS
      EQUIVALENCE (ILNSNS(1),LNSNS)
!                  TRPOUT
      EQUIVALENCE (ILLTPO(1),LTROUT)
!                  TIDALC
      EQUIVALENCE (ILTIDE(1),LRAY)
!                  LSLFSH
      EQUIVALENCE (ILSLFS(1),LSLFSH)
!
      EQUIVALENCE (ILASTR(1),LASTR(1))
!                  DWNWGT
      EQUIVALENCE (ILDWNW(1),LDWNWT)
!
      DATA IBLOCK/10/
      DATA CBLKTY/'   REAL ',' INTEGER',' LOGICAL'/
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!**********************************************************************
! READ HEADER RECORD FOR REAL COMMON BLOCKS
!***********************************************************************
      IOUT6=6
      ITYPE=1
      CALL BINRD(IUNT11,IFFHDR  ,IFHEAD)
! TEST FOR BLOCK NUMBER AND RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(3).NE.ITYPE) GO TO 60150
! SET NUMBER OF COMMON BLOCKS = NUMBER OF RECORDS -1
      NCOMS1=IFFHDR(4)
      NCOMS =NCOMS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR REAL COMMON BLOCKS
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN  ,NCOMS1)
!**********************************************************************
! READ DATA RECORDS FOR REAL COMMON BLOCKS
!**********************************************************************
      ICOM =0
! /CBDSTA/
      ICOM =ICOM +1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQBDST(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQBDST(NX) .NE. XBDSTA) GO TO 60100
! /CEPHEP/
      ICOM =ICOM +1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQEPHE(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQEPHE(NX) .NE. XEPHEP) GO TO 60100
! /CGVTMR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQGVTR(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQGVTR(NX) .NE. XCGVTR) GO TO 60100
! /CLIGHT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQCLIT(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQCLIT(NX) .NE. XCLITE) GO TO 60100
! /COREPH/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQCEPH(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQCEPH(NX) .NE. XCOEPH) GO TO 60100
! /DELUT1/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQDELU(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQDELU(NX) .NE. XDELUT) GO TO 60100
! /DYNPOL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQDYNP(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQDYNP(NX) .NE. XDYNPL) GO TO 60100
! /EPHSET/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQEPHS(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQEPHS(NX) .NE. XEPHST ) GO TO 60100
! /FLUXAU/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQFLUX(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQFLUX(NX) .NE. XFLUXA ) GO TO 60100
! /G2SINF/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQG2SI(1),10,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQG2SI(NX) .NE. XG2SIN ) GO TO 60100
! /G2SINC/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRCC(IUNT11,FFBUF,NX)
      CALL MOVER(FFBUF(1),AQG2SC(1),NX-1,.TRUE.)
      CALL Q9ICLA(FFBUF(NX),AQG2SC(NX),1,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQG2SC(NX) .NE. XG2SIC ) GO TO 60100
! /INVRSA/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQINVR(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQINVR(NX) .NE. XINVRS ) GO TO 60100
! /PARFIL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQPARF(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQPARF(NX) .NE. XPARFI ) GO TO 60100
! /RLOCGR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQLOCG(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQLOCG(NX) .NE. XRLOC ) GO TO 60100
! /RMODEL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQRMOD(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQRMOD(NX) .NE. XRMOD ) GO TO 60100
! /ROBTYP/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQRTYP(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQRTYP(NX) .NE. XMTYP ) GO TO 60100
! /SATCUT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQSATC(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQSATC(NX) .NE. XSATCU ) GO TO 60100
! /XTRAOR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQXTRA(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQXTRA(NX) .NE. XXTRAO ) GO TO 60100
! /SPOOKY/ (FANTOM)
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQSPOK(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQSPOK(NX) .NE. XSPOOK ) GO TO 60100
! /ION2ER/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQIONR(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQIONR(NX) .NE. XIONR ) GO TO 60100
! /MREFDT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQMREF(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQMREF(NX) .NE. XMREF ) GO TO 60100
! /DTMGDN/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQTMGN(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQTMGN(NX) .NE. XTMGN ) GO TO 60100
! /POLRAT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQPOLR(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQPOLR(NX) .NE. XPOLR ) GO TO 60100
! /YARSCH/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQYARK(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQYARK(NX) .NE. XYARMD ) GO TO 60100
! /NETCO/N
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQNETC(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQNETC(NX) .NE. XNETC ) GO TO 60100
! /DPLNOR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQPLNO(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQPLNO(NX) .NE. XPLNOR ) GO TO 60100
! /ROTELM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQROTL(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQROTL(NX) .NE. XROTLM ) GO TO 60100
! /ROTEL2/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQROTL2(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQROTL2(NX) .NE. XROTLM2 ) GO TO 60100
! /ROTEL5/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQROT5(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQROT5(NX) .NE. XROTL5 ) GO TO 60100
! /PMARS /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQPMAR(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQPMAR(NX) .NE. XPMARS ) GO TO 60100
! /GCMMOD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      IF(NX.GT.IFBUFR) GOTO 60400
      CALL BINRD2(IUNT11,FFBUF,NX)
      CALL Q9ICLA(FFBUF(1),AQGCMM(1),NX,ISTAT)
      IF(ISTAT.NE.0) GOTO 60500
      IF(AQGCMM(NX) .NE. XXGCM ) GO TO 60100
!
!  WRITE OUT THE GEODYN INTERNAL REFERENCE TIME

      WRITE(6,'(/A)')&
            'THE GEODYN INTERNAL REFERENCE TIME FOR THIS RUN : '
      WRITE(6,*)'YYMMDD= ', TGTYMD,' JD= ',TMGDN1
!
! TEST IF CORRECT NUMBER OF COMMON BLOCKS RECEIVED
!
      IF(ICOM.NE.NCOMS) GO TO 60200
!**********************************************************************
! HEADER RECORD FOR INTEGER COMMON BLOCKS
!**********************************************************************
      ITYPE=2
      CALL BINRD(IUNT11,IFFHDR  ,IFHEAD)
! TEST FOR CORRECT BLOCK NUMBER AND RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(3).NE.ITYPE) GO TO 60150
      NCOMS1=IFFHDR(4)
      NCOMS = NCOMS1-1
!**********************************************************************
! LENGTHS RECORD FOR INTEGER COMMON BLOCKS
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN  ,NCOMS1)
!**********************************************************************
! DATA RECORDS FOR INTEGER COMMON BLOCKS
!**********************************************************************
      ICOM=0
! /AGRAV/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQAGRA(1),NX)
      IF(IQAGRA(NX) .NE. NXAGRA) GO TO 60100
! /APHASE/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQAPHA(1),NX)
      IF(IQAPHA(NX) .NE. NXAPHA) GO TO 60100
! /BIHTBL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQBIHT(1),NX)
      IF(IQBIHT(NX) .NE. NXBIHT) GO TO 60100
! /BINBUF/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQBINB(1),NX)
      IF(IQBINB(NX) .NE. NXBINB) GO TO 60100
! /CEBGLB/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCEBG(1),NX)
      IF(IQCEBG(NX) .NE. NXCEBG) GO TO 60100
! /CESTIM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCEST(1),NX)
      IF(IQCEST(NX) .NE. NXCEST) GO TO 60100
! /CGVTMI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQGVTI(1),NX)
      IF(IQGVTI(NX) .NE. NXGVTI) GO TO 60100
! /CIOCON/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCIOC(1),NX)
      IF(IQCIOC(NX) .NE. NXCON) GO TO 60100
! /CIOTMD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCIOT(1),NX)
      IF(IQCIOT(NX) .NE. NXCIOT) GO TO 60100
! /CISSTM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCISS(1),NX)
      IF(IQCISS(NX) .NE. NXCISS) GO TO 60100
! /CITERG/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQITRG(1),NX)
      IF(IQITRG(NX) .NE. NXITRG) GO TO 60100
! /CMETI /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCMTI(1),NX)
      IF(IQCMTI(NX) .NE. NXCMTI) GO TO 60100
! /CNIGLO/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCNIG(1),NX)
      IF(IQCNIG(NX) .NE. NXCNIG) GO TO 60100
! /COBGLO/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCOBG(1),NX)
      IF(IQCOBG(NX) .NE. NXCOBG) GO TO 60100
! /CORA01/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA01(1),NX)
      IF(IQCA01(NX) .NE. NXCA01) GO TO 60100
! /CORA02/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA02(1),NX)
      IF(IQCA02(NX) .NE. NXCA02) GO TO 60100
! /CORA03/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA03(1),NX)
      IF(IQCA03(NX) .NE. NXCA03) GO TO 60100
! /CORA04/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA04(1),NX)
      IF(IQCA04(NX) .NE. NXCA04) GO TO 60100
! /CORA05/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA05(1),NX)
      IF(IQCA05(NX) .NE. NXCA05) GO TO 60100
! /CORA06/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA06(1),NX)
      IF(IQCA06(NX) .NE. NXCA06) GO TO 60100
! /CORA07/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCA07(1),NX)
      IF(IQCA07(NX) .NE. NXCA07) GO TO 60100
! /CORE2E/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCORE(1),NX)
      IF(IQCORE(NX) .NE. NXCORE) GO TO 60100
! /CORE2S/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCORS(1),NX)
      IF(IQCORS(NX) .NE. NXCORS) GO TO 60100
! /CORI01/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI01(1),NX)
      IF(IQCI01(NX) .NE. NXCI01) GO TO 60100
! /CORI02/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI02(1),NX)
      IF(IQCI02(NX) .NE. NXCI02) GO TO 60100
! /CORI03/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI03(1),NX)
      IF(IQCI03(NX) .NE. NXCI03) GO TO 60100
! /CORI04/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI04(1),NX)
      IF(IQCI04(NX) .NE. NXCI04) GO TO 60100
! /CORI05/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI05(1),NX)
      IF(IQCI05(NX) .NE. NXCI05) GO TO 60100
! /CORI06/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI06(1),NX)
      IF(IQCI06(NX) .NE. NXCI06) GO TO 60100
! /CORI07/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCI07(1),NX)
      IF(IQCI07(NX) .NE. NXCI07) GO TO 60100
! /CORL01/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL01(1),NX)
      IF(IQCL01(NX) .NE. NXCL01) GO TO 60100
! /CORL02/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL02(1),NX)
      IF(IQCL02(NX) .NE. NXCL02) GO TO 60100
! /CORL03/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL03(1),NX)
      IF(IQCL03(NX) .NE. NXCL03) GO TO 60100
! /CORL04/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL04(1),NX)
      IF(IQCL04(NX) .NE. NXCL04) GO TO 60100
! /CORL05/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL05(1),NX)
      IF(IQCL05(NX) .NE. NXCL05) GO TO 60100
! /CORL06/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL06(1),NX)
      IF(IQCL06(NX) .NE. NXCL06) GO TO 60100
! /CORL07/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCL07(1),NX)
      IF(IQCL07(NX) .NE. NXCL07) GO TO 60100
! /CORREQ/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQRREQ(1),NX)
      IF(IQRREQ(NX) .NE. NXRREQ) GO TO 60100
! /CPARTI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPARI(1),NX)
      IF(IQPARI(NX) .NE. NXPARI) GO TO 60100
! /CRDDIM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCRDM(1),NX)
      IF(IQCRDM(NX) .NE. NXCRDM) GO TO 60100
! /CSHAD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQSHAD(1),NX)
      IF(IQSHAD(NX) .NE. NXSHAD) GO TO 60100
! /CSTATS/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCSTA(1),NX)
      IF(IQCSTA(NX) .NE. NXCSTT) GO TO 60100
! /CTIDES/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCTID(1),NX)
      IF(IQCTID(NX) .NE. NXCTID) GO TO 60100
! /CVIEW /
      IPSAV6=IPAGE6
      IPSAV9=IPAGE9
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCVUE(1),NX)
      IF(IQCVUE(NX) .NE. NXCVUE) GO TO 60100
      IPAGE6=IPSAV6
      ILINE6=MLINE6
      IPAGE9=IPSAV9
      ILINE9=MLINE9
! /DELOFF/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQDELO(1),NX)
      IF(IQDELO(NX) .NE. NXDELO) GO TO 60100
! /DYNPTR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQDYNP(1),NX)
      IF(IQDYNP(NX) .NE. NXDYNP) GO TO 60100
! /EPHMPT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQEPHP(1),NX)
      IF(IQEPHP(NX) .NE. NXEPHP) GO TO 60100
! /GEODEG/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQGDEG(1),NX)
      IF(IQGDEG(NX) .NE. NXGDEG) GO TO 60100
! /GEOMCS/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQGEOM(1),NX)
      IF(IQGEOM(NX) .NE. NXGEOM) GO TO 60100
! /GRANI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQGRAN(1),NX)
      IF(IQGRAN(NX) .NE. NXGRAN) GO TO 60100
! /IBODPT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQBDPT(1),NX)
      IF(IQBDPT(NX) .NE. NXBDPT) GO TO 60100
! /IOBTYP/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQRTYP(1),NX)
      IF(IQRTYP(NX) .NE. NXMTYP) GO TO 60100
! /IORCHB/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQORCH(1),NX)
      IF(IQORCH(NX) .NE. NXORCH) GO TO 60100
! /IPLMOD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQIPLN(1),NX)
      IF(IQIPLN(NX) .NE. NXPLMD) GO TO 60100
! /MODEL /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQMODL(1),NX)
      IF(IQMODL(NX) .NE. NXMODL) GO TO 60100
! /MODEL /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNGRD(1),NX)
      IF(IQNGRD(NX) .NE. NXGRID) GO TO 60100
! /NHINPT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNHIN(1),NX)
      IF(IQNHIN(NX) .NE. NXNHIN) GO TO 60100
! /NLIGHT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNLIT(1),NX)
      IF(IQNLIT(NX) .NE. NXNLIT) GO TO 60100
! /NLOCGR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQLOCG(1),NX)
      IF(IQLOCG(NX) .NE. NXLOCG) GO TO 60100
! /NLRA/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNLRA(1),NX)
      IF(IQNLRA(NX) .NE. NXNLRA) GO TO 60100
! /NPCOM /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNPCM(1),NX)
      IF(IQNPCM(NX) .NE. NXNPCM) GO TO 60100
! /NPCOMX/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNPCX(1),NX)
      IF(IQNPCX(NX) .NE. NXNPCX) GO TO 60100
!CC   WRITE(6,*)' DBG IRWGCB ',IXLOCG,IPVAL(IXLOCG)
! /OLDMOD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQOLMD(1),NX)
      IF(IQOLMD(NX) .NE. NXOLMD) GO TO 60100
! /PLATE /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPLAT(1),NX)
      IF(IQPLAT(NX) .NE. NXPLAT) GO TO 60100
! /PLMONI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPLMI(1),NX)
      IF(IQPLMI(NX) .NE. NXPLMI) GO TO 60100
! /PLNETI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPLNI(1),NX)
      IF(IQPLNI(NX) .NE. NXPLNI) GO TO 60100
! /PLTOPO/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPLTP(1),NX)
      IF(IQPLTP(NX) .NE. NXPLTP) GO TO 60100
! /POLINF/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQPOLI(1),NX)
      IF(IQPOLI(NX) .NE. NXPOLI) GO TO 60100
! /SSTCOM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQSST(1),NX)
      IF(IQSST(NX) .NE. NXSST) GO TO 60100
! /STATN /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQSTAT(1),NX)
      IF(IQSTAT(NX) .NE. NXSTAT) GO TO 60100
! /TPGRAV/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQTPGR(1),NX)
      IF(IQTPGR(NX) .NE. NXTPGR) GO TO 60100
! /VLBI  /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQVLBI(1),NX)
      IF(IQVLBI(NX) .NE. NXVLBI) GO TO 60100
! /XEPHMI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQXEPH(1),NX)
      IF(IQXEPH(NX) .NE. NXXEPH) GO TO 60100
! /EXTAGI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQTAGI(1),NX)
      IF(IQTAGI(NX) .NE. NXTAGI) GO TO 60100
! /EXATGI/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQEAGI(1),NX)
      IF(IQEAGI(NX) .NE. NXEAGI) GO TO 60100
! /CASPER/ (FANTOM)
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQCASP(1),NX)
      IF(IQCASP(NX) .NE. NXCASP) GO TO 60100
! /IONO2E/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQIONO(1),NX)
      IF(IQIONO(NX) .NE. NXIONO) GO TO 60100
! /TARGET/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQTARG(1),NX)
      IF(IQTARG(NX) .NE. NXTARG) GO TO 60100
! /TDGRDS/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQTDGR(1),NX)
      IF(IQTDGR(NX) .NE. NXTDRG) GO TO 60100
! /XPCNT /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQXPCN(1),NX)
      IF(IQXPCN(NX) .NE. NXXTRA) GO TO 60100
! /XPCNT2/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQXPCN2(1),NX)
      IF(IQXPCN(NX) .NE. NXXTR2) GO TO 60100
! /IEPHM2/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQEPH2(1),NX)
      IF(IQEPH2(NX) .NE. NXEPH2) GO TO 60100
! /NFORCE/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQFORC(1),NX)
      IF(IQFORC(NX) .NE. NXFORC) GO TO 60100
! /SETDI /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQSETI(1),NX)
      IF(IQSETI(NX) .NE. NXSETI) GO TO 60100
! /NALOAD/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQAPLD(1),NX)
      IF(IQAPLD(NX) .NE. NXLOAD) GO TO 60100
! /SATPIN/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQSATP(1),NX)
      IF(IQSATP(NX) .NE. NXSATP) GO TO 60100
!SMCS /NUTINF/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQNUTA(1),NX)
      IF(IQNUTA(NX) .NE. NXNUTA) GO TO 60100
!     /MULTDM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRD(IUNT11,IQMLTD(1),NX)
      IF(IQMLTD(NX) .NE. NXMDEM) GO TO 60100

!
! TEST IF CORRECT NUMBER OF INTEGER COMMON BLOCKS RECEIVED
!
      IF(ICOM .NE. NCOMS ) GO TO 60200
!**********************************************************************
! READ HEADER RECORD FOR LOGICAL COMMON BLOCKS
!**********************************************************************
      ITYPE=3
      CALL BINRD(IUNT11,IFFHDR  ,IFHEAD)
! TEST FOR CORRECT BLOCK NUMBER AND DATA TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(3).NE.ITYPE) GO TO 60150
! SET NUMBER OF COMMON BLOCKS = NUMBER OF RECORDS -1
      NCOMS1=IFFHDR(4)
      NCOMS =NCOMS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR LOGICAL COMMON BLOCKS
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN  ,NCOMS1)
!**********************************************************************
! READ DATA RECORDS FOR LOGICAL COMMON BLOCKS
!**********************************************************************
      ICOM =0
! /CALTOP/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILALTO(1),NX)
      IF(ILALTO(NX) .NE. NXALTO) GO TO 60100
! /CEGREL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILEGRL(1),NX)
      IF(ILEGRL(NX) .NE. NXEGRL) GO TO 60100
! /CESTML/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILCSTL(1),NX)
      IF(ILCSTL(NX) .NE. NXCSTL) GO TO 60100
! /CGLBAR/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,IGLBAR(1),NX)
      IF(IGLBAR(NX) .NE. NXGLAR) GO TO 60100
! /CLGEOP/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILCLGP(1),NX)
      IF(ILCLGP(NX) .NE. NXCLGP) GO TO 60100
! /CLNORM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILNORM(1),NX)
      IF(ILNORM(NX) .NE. NXNORM) GO TO 60100
! /CLSSOT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILSSOT(1),NX)
      IF(ILSSOT(NX) .NE. NX) GO TO 60100
! /CLVIEW/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILCLVI(1),NX)
      IF(ILCLVI(NX) .NE. NXCLVI) GO TO 60100
! /CPARTL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILPARL(1),NX)
      IF(ILPARL(NX) .NE. NXPARL) GO TO 60100
! /CUNIT9/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILUNT9(1),NX)
      IF(ILUNT9(NX) .NE. NXUNT9) GO TO 60100
! /GBINRL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILGBIN(1),NX)
      IF(ILGBIN(NX) .NE. NXGBIN) GO TO 60100
! /INVRSL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILINVR(1),NX)
      IF(ILINVR(NX) .NE. NXINVR) GO TO 60100
! /LASTER/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILASTR(1),NX)
      IF(ILASTR(NX) .NE. NXASTR) GO TO 60100
! /LICASE/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILCASE(1),NX)
      IF(ILCASE(NX) .NE. NXLCAS) GO TO 60100
! /LOBTYP/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILBTYP(1),NX)
      IF(ILBTYP(NX) .NE. NXLTYP) GO TO 60100
! /LSWTCH/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILLSWT(1),NX)
      IF(ILLSWT(NX) .NE. NXLSWT) GO TO 60100
! /POLESW/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILPOLS(1),NX)
      IF(ILPOLS(NX) .NE. NXPOLS) GO TO 60100
! /PUNCH /
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILPUNC(1),NX)
      IF(ILPUNC(NX) .NE. NXPUNC) GO TO 60100
! /SHIRTS/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILNSNS(1),NX)
      IF(ILNSNS(NX) .NE. NXNSNS) GO TO 60100
! /TRPOUT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILLTPO(1),NX)
      IF(ILLTPO(NX) .NE. NXLTPO) GO TO 60100
! /EXTAGL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILTAGL(1),NX)
      IF(ILTAGL(NX) .NE. NXTAGL) GO TO 60100
! /EXATGL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILEAGL(1),NX)
      IF(ILEAGL(NX) .NE. NXEAGL) GO TO 60100
! /FANTOM/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILFANT(1),NX)
      IF(ILFANT(NX) .NE. NXFANT) GO TO 60100
! /GPSBLK/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILGPS(1),NX)
      IF(ILGPS(NX) .NE. NXGPS) GO TO 60100
! /ION2EL/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILIONO(1),NX)
      IF(ILIONO(NX) .NE. NXIONL) GO TO 60100
! /LNUTAT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILNUTA(1),NX)
      IF(ILNUTA(NX) .NE. NXLNUT) GO TO 60100
! /TIDALC/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILTIDE(1),NX)
      IF(ILTIDE(NX) .NE. NXTIDL) GO TO 60100
! /LSLFSH/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILSLFS(1),NX)
      IF(ILSLFS(NX) .NE. NXSLFS) GO TO 60100
! /DWNWGT/
      ICOM=ICOM+1
      NX=IFFLEN(ICOM)
      CALL BINRLC(IUNT11,ILDWNW(1),NX)
      IF(ILDWNW(NX) .NE. NXDWNW) GO TO 60100
!
! TEST IF CORRECT NUMBER OF LOGICAL COMMON BLOCKS RECEIVED
!
      IF(ICOM .NE. NCOMS ) GO TO 60200
      RETURN
! ERROR MESSAGES
!
60100 WRITE(IOUT6,80100)
      WRITE(IOUT6,80110) ICOM,CBLKTY(IFFHDR(3))
      WRITE(IOUT6,80130)
      STOP
60150 WRITE(IOUT6,80150) IBLOCK,ITYPE,IFFHDR
      WRITE(IOUT6,80999)
      STOP
60200 WRITE(IOUT6,80100)
      WRITE(IOUT6,80120) ICOM,NCOMS,IFFHDR(3)
      WRITE(IOUT6,80130)
      STOP
60400 WRITE(IOUT6,80400) IFBUFR,NX
      WRITE(IOUT6,80999)
      STOP
60500 WRITE(IOUT6,80500) ISTAT
      WRITE(IOUT6,80999)
      STOP
80100 FORMAT(5X,'EXECUTION TERMINATING DUE TO COMMON BLOCK PROBLEM IN', &
     &'SUBROUTINE IFRGCB.')
80110 FORMAT(5X,'LENGTH FOR COMMON BLOCK NUMBER',I3,' OF TYPE ',A8,     &
     & ' DOES NOT MATCH')
80120 FORMAT(5X,'NUMBER OF COMMON BLOCKS (',I2,') WRITTEN TO INTERFACE',&
     &'FILE FOR TYPE ',I1,' DOES NOT AGREE WITH EXPECTED NUMBER (',I2,  &
     & ')' )
80130 FORMAT(5X,'CHECK THAT 2S VERSION IS COMPATIBLE WITH 2E VERSION')
80150 FORMAT(1X,'BLOCK NUMBER OR RECORD TYPE DOES NOT MATCH ',2I5/1X,   &
     & 20I4)
80400 FORMAT(1X,'MAXIMUM REAL INPUT BUFFER LENGTH IS :',I6,' AND THE',  &
     & ' BUFFER LENGTH REQUESTED IS:',I6)
80500 FORMAT(1X,'SUBROUTINE Q9IC64 RETURNED WITH STATUS CODE:',I5)
80999 FORMAT(1X,'EXECUTION TERMINATING IN SUBROUTINE IFRGCB')
      END
