!$IFRGD4
      SUBROUTINE IFRGD4(AA,II,LL,IFFHDR,IFFLEN,FFBUF)
!********1*********2*********3*********4*********5*********6*********7**
! IFRGD4           85/03/04            0000.0    PGMR - B. EDDY/SEVITSKI
!
! FUNCTION:  READ GLOBAL DYNAMIC ARRAYS FROM THE INTERFACE FILE
!            FOR ALLOCATION GROUP #4 - MEASUREMENT MODELLING
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL DATA
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL DATA
!   IFFHDR   I    A    SCRATCH ARRAY USED FOR HEADER INFORMATION
!   IFFLEN   I    A    SCRATCH ARRAY USED FOR LENGTHS OF DATA
!   FFBUF    I    A    SCRATCH ARRAY USED FOR CONVERTING IBM
!                      FLOATING POINT NUMBERS TO CYBER F.P.
!
! COMMENTS:     INTERFACE FORMAT #2 USED:
!
! INTEGER  HEADER RECORD  - WITH IFFHDR(5)=0 INDICATING LENGTHS RECORDS
!                           FOLLOWS
! INTEGER LENGTHS RECORD  - CONTAINING IFFHDR(4)-1 LENGTHS
!            DATA RECORDS - IFFHDR(4)-1  DATA RECORDS. DATA RECORDS ARE
!                           OF THE TYPE INDICATED IN IFFHDR(3)
!
! COMMENTS:   TO READ ADDITIONAL RECORDS IN THIS ROUTINE
!             1. INCREMENT IRECS IN PROPER GROUP-REAL,INTEGER OR LOGICAL
!             2. ADD CALL TO BINRD2 (REAL) OR BINRD (INTEGER,LOGICAL)
!                IN PROPER GROUP
!             3. FOR FLOATING POINT DATA CALL SUBROUTINE Q9ICLA TO
!                CONVERT REAL WORDS TO THE CORRECT REPRESENTATION
!                FOR THE COMPUTER IIE IS RUNNING ON
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CIFF  /IFHEAD,IFLNTH,IFBUFL,IFBUFR,KDYNHD,KDYNLN,          &
     &              KDYNIF,KDYNFF,NXCIFF
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/DWNWGT/LDWNWT,LDNWMT(999),NXDWNW
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
!
      DIMENSION AA(1)
      DIMENSION FFBUF(IFBUFR)
      DIMENSION IFFHDR(IFHEAD),IFFLEN(IFLNTH)
      DIMENSION II(1)
      DIMENSION LL(1)
!
      DATA IBLOCK/20/,IGROUP/4/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!**********************************************************************
! READ HEADER RECORD FOR REAL DATA
!**********************************************************************
      ITYPE=1
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS=NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR REAL DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE LAST WORD READ WHICH IS THE SUM OF THE LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR REAL DATA
!**********************************************************************
      IREC=0
      IWORDS=0
      IGLB =IPVAL(IXGLBL)
      IGLB0=IPVAL0(IXGLBL)
! KFRQOF/FRQOFF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KFRQOF),NX,ISTAT)
! KXYZOF/XYZOFF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KXYZOF),NX,ISTAT)
! KFRQST/FRQSTA
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KFRQST),NX,ISTAT)
! KSTDLY/STADLY DELAY COORDINATES
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSTDLY),NX,ISTAT)
! KFRQSA/FRQSAT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KFRQSA),NX,ISTAT)
! KSADLY/SATDLY
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSADLY),NX,ISTAT)
! KXYZCG/XYZCG
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KXYZCG),NX,ISTAT)
! KSCMRA/SCMRAT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSCMRA),NX,ISTAT)
! KSSTFQ/SSTFRQ
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KSSTFQ),NX,ISTAT)
! KQUINF/QUAINF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KQUINF),NX,ISTAT)
! KLRARC/RNGCOR
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KLRARC),NX,ISTAT)
! KXYOF2/XYZOF2
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KXYOF2),NX,ISTAT)
! KDLATF/DLATF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDLATF),NX,ISTAT)
! KDLATS/DLATS
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDLATS),NX,ISTAT)
! KDLONF/DLONF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDLONF),NX,ISTAT)
! KDLONS/DLONS
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDLONS),NX,ISTAT)
! KPF/PF
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KPF),NX,ISTAT)
! KPS/PS
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KPS),NX,ISTAT)
! KDNUM/ DNUM
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDNUM),NX,ISTAT)
! KCNUM/ CNUM
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KCNUM),NX,ISTAT)
! KANTBL/ ANTBL
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KANTBL),NX,ISTAT)
! KGNAME/ GRNAME
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRDC(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KGNAME),NX,ISTAT)
! KGRSIZ/ GRSIZE
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KGRSIZ),NX,ISTAT)
! KGRCNT/ GRDCNT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KGRCNT),NX,ISTAT)
! KGRDAT/ GRDATA
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GO TO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KGRDAT),NX,ISTAT)
! KXYOF3 /XYZOF3
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KXYOF3),NX,ISTAT)
! KEXCST
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KEXCST),NX,ISTAT)
! KEXCDT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KEXCDT),NX,ISTAT)
! KEXCGX
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KEXCGX),NX,ISTAT)
! KEXCGY
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KEXCGY),NX,ISTAT)
! KEXCGZ
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KEXCGZ),NX,ISTAT)
! KDWNWT
      IREC=IREC+1
      NX=IFFLEN(IREC)
      IF(NX.GT.IFBUFR) GOTO 60100
      IWORDS=IWORDS+NX
      CALL BINRD2(IUNT11,FFBUF,NX  )
      IF(NX.GT.0) CALL Q9ICLA(FFBUF,AA(KDWNWT),NX,ISTAT)
!
!
!
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
!**********************************************************************
! READ HEADER RECORD FOR INTEGER DATA
!**********************************************************************
      ITYPE=2
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS =NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR INTEGER DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE SUM OF RECORD LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR INTEGER DATA
!**********************************************************************
      IREC=0
      IWORDS=0
! KIANTO/IANTOF
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIANTO),IFFLEN(IREC) )
! KISATO/ISATOF
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KISATO),IFFLEN(IREC) )
! KIANTD/IANTDL
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIANTD),IFFLEN(IREC) )
! KISATD/ISATDL
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KISATD),IFFLEN(IREC) )
! KISTAD/ISTADL
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KISTAD),IFFLEN(IREC) )
! KISATC/ISATCG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KISATC),IFFLEN(IREC) )
! KMJDCG/MJDSCG
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KMJDCG),IFFLEN(IREC) )
! KSSTNM/ISSTNM
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KSSTNM),IFFLEN(IREC) )
! KSSTNA/ISSTNA
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KSSTNA),IFFLEN(IREC) )
! KIPNTF/IPNTF
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIPNTF),IFFLEN(IREC) )
! KIPNTS/IPNTS
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KIPNTS),IFFLEN(IREC) )
! KNCON/NCON
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KNCON),IFFLEN(IREC) )
! KKF/KF
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KKF),IFFLEN(IREC) )
! KLLBIA/
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KLLBIA),IFFLEN(IREC) )
! KTARID/ITARID
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KTARID),IFFLEN(IREC) )
! KATARD/IATARI
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRD(IUNT11,II(KATARD),IFFLEN(IREC) )
!
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
!**********************************************************************
! READ HEADER RECORD FOR LOGICAL DATA
!**********************************************************************
      ITYPE=3
      CALL BINRD(IUNT11,IFFHDR,IFHEAD)
! TEST BLOCK NUMBER,GROUP NUMBER AND DATA RECORD TYPE
      IF(IFFHDR(1).NE.IBLOCK .OR. IFFHDR(2).NE.IGROUP .OR.              &
     &   IFFHDR(3).NE.ITYPE) GO TO 60400
      NRECS1=IFFHDR(4)
      NRECS =NRECS1-1
!**********************************************************************
! READ LENGTHS RECORD FOR LOGICAL DATA
!**********************************************************************
      CALL BINRD(IUNT11,IFFLEN,NRECS1)
! SAVE SUM OF DATA RECORD LENGTHS
      NWORDS=IFFLEN(NRECS1)
!**********************************************************************
! READ DATA RECORDS FOR LOGICAL DATA
!**********************************************************************
      IREC=0
      IWORDS=0
!
! LOGICAL DATA RECORDS GO HERE
!
! KNSCID/LNSCID
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRDL(IUNT11,LL(KNSCID),IFFLEN(IREC) )
! KEXTOF/LEXTOF
      IREC=IREC+1
      IWORDS=IWORDS+IFFLEN(IREC)
      CALL BINRDL(IUNT11,LL(KEXTOF),IFFLEN(IREC) )
! TEST IF CORRECT NUMBER OF DATA RECORDS READ
!
      IF(IREC.NE.NRECS) GO TO 60200
! TEST IF CORRECT NUMBER OF WORDS READ
      IF(NWORDS.NE.IWORDS) GO TO 60300
      RETURN
!**********************************************************************
! ERROR PROCESSING
!**********************************************************************
!
! RECORD SIZE EXCEEDS BUFFER SPACE
60100 WRITE(IOUT6,80100) ITYPE,NX,IFBUFR
      WRITE(IOUT6,89999)
      STOP
! NUMBER OF RECORDS READ DISAGREES WITH NUMBER OF LENGTHS EXPECTED
60200 WRITE(IOUT6,80200) ITYPE,IREC,NRECS
      WRITE(IOUT6,89999)
      STOP
! NUMBER OF WORDS SENT DISAGREES WITH NUMBER OF WORDS EXPECTED
60300 WRITE(IOUT6,80300) ITYPE,NWORDS,IWORDS
      WRITE(IOUT6,89999)
      STOP
! BLOCK NUMBER,GROUP NUMBER OR RECORD TYPE INCORRECT
60400 WRITE(IOUT6,80400) IBLOCK,IGROUP,ITYPE,IFFHDR
      WRITE(IOUT6,89999)
      STOP
80000 FORMAT(1X,'UNEXPECTED END OF FILE ON UNIT ',I2,' FOR DATA TYPE ', &
     & I2)
80100 FORMAT(1X,'RECORD SIZE EXCEEDS BUFFER SPACE AVAILABLE. ITYPE,NX,' &
     &'IFBUFR FOLLOW: '/1X,3I10)
80200 FORMAT(1X,'NUMBER OF TYPE (',I2,') RECORDS READ FROM INTERFACE ',&
     &'FILE DISAGREES WITH NUMBER OF LENGTHS EXPECTED',2I5)
80300 FORMAT(1X,'SUM OF RECORD LENGTHS FROM IFF LENGTHS RECORD DOES ',&
     &'NOT AGREE WITH SUM CALCULATED',3I6)
80400 FORMAT(1X,'BLOCK NUMBER,GROUP NO. OR DATA TYPE IS INCORRECT',2I5/ &
     &1X,20I5)
89999 FORMAT(1X,'EXECUTION TERMINATING IN SUBROUTINE IFRGD4 ')
      END
