!$IMAGER
      SUBROUTINE IMAGER(AA ,II  ,LL  ,INDSAT,INDSET, RESID ,SIGMA ,     &
     &    RATIO ,PMPA  ,OBS   ,OBSSIG, RESIDU,ISTATS,NTYPE,             &
     &    XSCR,XSM,XSMTOD,VSM,OFF,NEQN ,PXPF,                           &
     &    NDIMX1,NDIMX2,NDIMX3,N3,                                      &
     &    RMVPRT, ATPER, LEDIT,EDTSIG,THETAG,COSTHG,SINTHG,             &
     &    XTRA,WORK,HOLD,ATROT,IPTFMG,ILNFMG,NFMG,PXEPA,LINIM,OBSTIM)
!********1*********2*********3*********4*********5*********6*********7**
! PROCX            00/00/00            0000.0    PGMR -DESPINA PAVLIS
!
!
! FUNCTION: PROCESS DYNAMIC CROSSOVERS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A     REAL DYNAMIC ARRAY
!   II      I/O   A     INTEGER DYNAMIC ARRAY
!   LL      I/O   A     LOGICAL DYNAMIC ARRAY
!   RESID    O    A     RESIDUAL VECTOR
!   SIGMA    O    A     RESIDUAL/OBS SIGMA
!   RATIO    O    A     RATIO TO SIGMA
!   PMPA    I/O   A     PARTIALS MATRIX THETAOBS/THETA PARAMETERS
!   OBS      I    A     INPUT OBSERVATION ARRAY. IN THE CASE OF IMAGES
!                       THE OBS ARRAY CONTAINS ZEROES
!   OBSSIG   I    A     OBSERVATION SIGMA
!   RESIDU
!   ISTATS
!   NTYPE
!   RINDEX  I/O A  AUXILIARY INDEX ARRAY FOR PAIRED BLOCKS IDENTIFICATIO
!   XSCR    I/O A  SCRATCH ARRAY FOR BLOCL INFORMATION MANIPULATION
!   XSM     O   A  TOR  COORDINATES OF THE S/C
!   NEQN    I   A  NUMBER OF FORCE MODEL PARAMETERS
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/LIMAGE/LIMG,LIMCALL,LIMAT,LIMCAM
      COMMON/SAVEIM/RIM(3,3),SBF1(3,3),SBF2(3,3),SBF3(3,3),SBF4(3,3),   &
     &       SCF2(3,3),SCF3(3,3),SCF4(3,3),RKEY
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/CAMCCD/CKXMAT(30,6),CAMCTR(30,2),XKXCCD
      COMMON/CAMSAT/NCAM,NSCID(30),NXSCID
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CBLOKV/QUANO(3),EHAT(3),DEDA(3),DEDD(3),EFLG
      COMMON/CEDIT /EDITX ,EDTRMS,EDLEVL,CONVRG,GLBCNV,EBLEVL,EDITSW,   &
     &              ENPX  ,ENPRMS,ENPCNV,EDBOUN,FREEZI,FREEZG,FREEZA,   &
     &              XCEDIT
      COMMON/CEDITL/LNEDIT
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CKOUNT/KNTBLK,KSEGMN,KNTOBS,KZROBS
      COMMON/CLPRNR/LPR9NR(24),LPRNRM(24,3)
      COMMON/CNELVS/KNELEV(999)
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CNORML/LNORM ,LNORMP
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/COBSI /MODRES,NXCOBS
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI05/KNOBGL,KNOBWG,KNOBTY,KNOBWY,KNOBST,KNOBWT,KNEBOB,   &
     &              KJSTAT,NXCI05
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL03/KLVELA,KLSTL2,KLSTH2,NXCL03
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CORL05/KLGPRV,NXCL05
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CORL07/KLPTS,NXCL07
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/CRMI/RMI(9)
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
      COMMON/CSIML/LSIMTI
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/ELRTNX/NELVS,NELVC,IELSTA(6),IELSAT(6),IELSA2(6),          &
     &       INDXEL(5,4)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IMAG2E/KXIMG,KIMBST,KIMOBL,KIMBUP,KIMBPA
      COMMON/IMAG2S/NIMBLK,NIMTOT,NIMG2S
      COMMON/IOBTYP/NDXST(2,35),NDXSAT(2,35),                           &
     &      NDRSTA(50),NDRSAT(50),NDRST2(50),NDRSA2(50),                &
     &      ITMBIT(999),IOETR(999),MTYPED(11),NTYPES,                   &
     &      NM0112(4),NM1314(4),NM1522(4),NM2330(4),                    &
     &      NM3138(4),NM3997(4),NM4098(4),NM9900(4),NMT199(4),NMT203(4),&
     &      NS0112(4),NS1314(4),NS1522(4),NS2330(4),                    &
     &      NS3138(4),NS3997(4),NS4098(4),NS9900(4),NST199(4),NST203(4),&
     &      ITYPD(12,2),ITYPDD(7,2),ILINKF(5),ISTAFN(5,3),              &
     &      ISATFN(5,3),ILINKT(5),ISTATN(5,3),ISATTN(5,3),              &
     &      MGOTO(12),MENTER(12),MEXIT(12),                             &
     &      NDST60(3,24),NDST82(6,12),NDST92(12,7),NTDRSS,              &
     &      NDSA60(3,24),NDSA82(6,12),NDSA92(12,7),                     &
     &      MTDRSS(7),KTDRSS(7),ITDRSS(4,7),JTDRSS(4,7),                &
     &      NLLC60(5,24),NLLC82(10,12),NLLC98(20,7),NNBIA,              &
     &      NXMTYP
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
      COMMON/IRAMPS/INDRAM,KKRAMP
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NSEGSC/NSEGM(80)
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/RIMAGE/VIMAGE(6),QUCAM(4),QURSYS,TLBOD2
      COMMON/ROBTYP/CONVRT(999),OBSCAL(999),RESCAL(999),                &
     &              XMTYP
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/XOVER /KXKNT,KXBST,KXOBL,KXBUP,KXBPA,IAPLSC,IAPLL
      COMMON/XOVERR/XBTIME
      COMMON/XOVERS/NRXTOT,NXBLK,NUSIDE,NDEGX2,NDEGXX,NUCON,ITERNU,     &
     &              IPEDIT,IDEDIT,NXXOVR

      COMMON/DPLNOR/DXGEO1,DXGEO2,DXFRC1,DXFRC2,XPLNOR
      COMMON/ATTCBD/BATPER,ATTPRT
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26

!
      DIMENSION AA(*),II(*),LL(*)
      DIMENSION IPTFMG(MAXFMG,MSATA),ILNFMG(MAXFMG,MSATA),NFMG(MSATA)
      DIMENSION PXEPA(NDIM1,NDIM2)
      DIMENSION ATROT(3,3,MINTIM),SBFTOR(3,3)
      DIMENSION ATPER(1),LEDIT(1)
      DIMENSION INDSAT(3),INDSET(3)
      DIMENSION RESID (NM),SIGMA (NM),RATIO (NM),                       &
     &          PMPA(NDIM1,NDIM2),OBS   (NM),                           &
     &          OBSSIG(NM),EDTSIG(NM)
      DIMENSION RESIDU(NM)
      DIMENSION RINDEX(NIMBLK,3),XSCR(20,MINTIM)
      DIMENSION ELEVSC(1)
      DIMENSION XSM(MINTIM,3),XBF(MINTIM,3,2)
      DIMENSION V1(3),V2(3),V(3),ENHAT(3)
      DIMENSION ENHBR(3),ENHBP(3),ENHBY(3)
      DIMENSION OBSTIM(NM)

      DIMENSION VTOD(3,2)
      DIMENSION VATOD(3,2)
      DIMENSION VPBF(3,2)
      DIMENSION VRPBF(3,2),VCRPBF(3,2)
      DIMENSION VPPBF(3,2),VCPPBF(3,2)
      DIMENSION VYPBF(3,2),VCYPBF(3,2)
      DIMENSION PART(3)
      DIMENSION THETAG(NM),COSTHG(NM),SINTHG(NM)
      DIMENSION DXPDXI(3,3,2)
      DIMENSION PXEXI(3,3)
      DIMENSION OFF(MINTIM,3)

      DIMENSION X2VPA(1,3,20,2)
      DIMENSION XTD(1,3),XTPBF(1,3)
      DIMENSION XMP(1,3),XTP(1,3)
! X2VPA will save the partials for both points in a pair
      DIMENSION TOTRIM(3,3,2)
      DIMENSION TOTROL(3,3,2),TOTPIT(3,3,2),TOTYAW(3,3,2)

      DIMENSION TOCROL(3,3,2),TOCPIT(3,3,2),TOCYAW(3,3,2)
      DIMENSION TODPBF(3,3,2)
      DIMENSION NEQP(2)
      DIMENSION PBF(3,3)
! TOTRIM ID THE ARRAY HOLDING THE TOTAL ROTATION TOD TO CAMERA IN TIME
      DIMENSION PXPF(NDIMX1,NDIMX2,NDIMX3,2)
      DIMENSION RMVPRT(NDIMX1,NDIMX2,NDIMX3,2,2)
      DIMENSION X2PART(NEQNG,N3,2,1)
      DIMENSION XTRA(MINTIM,33),HOLD(MINTIM,30)
      DIMENSION DTYPE(1)
      DIMENSION TIMSYS(3),NUM(3)
      DIMENSION ONE(3,3),TWO(3,3),THREE(3,3)

      DIMENSION MJDS(2),FSECOT(2)
      DIMENSION TAT(2)
      DIMENSION IPAT1(2),IPAT2(2)
      DIMENSION TIMEA(2)

      DIMENSION XKMAT(6),CTR(2)
      DIMENSION PXV(3)
      DIMENSION CC(3)

      DIMENSION VIMG1(3),VIMG2(3), VIMG(3)
      DIMENSION TRKTOR(3,2)
      DIMENSION SBFRA(3,3,2),SBFDC(3,3,2)
      DIMENSION VVTMP(3,2), VVVTP(3)
      DIMENSION VTMP(3)
      DIMENSION DELCP(5), DISTP(5)

      DIMENSION DISTRH(4)
      DIMENSION PMPI(3)
      DIMENSION VRTOD(3,2)
      DIMENSION VPTOD(3,2)
      DIMENSION VYTOD(3,2)
      DIMENSION PBFGA(3,3)
      DIMENSION XSMTRA(3),XSMTDC(3)
      DIMENSION XBFRA(3,2),XBFDC(3,2),XBFGA(3,2)
      DIMENSION VPBRA(3,2),VPBDC(3,2),VPBGA(3,2)
      DIMENSION XSMTOD1(MINTIM,3),VSM(MINTIM,3),VSMTOD1(MINTIM,3)
      DIMENSION XSMTOD(MINTIM,3,2),VSMTOD(MINTIM,3,2)
      DIMENSION VLPBF(MINTIM,3,2)
      DIMENSION V1PBFN(3), V2PBFN(3), DP(3), XBOUNCE(3)
      DIMENSION PPOR(3,2), ENHPOR(3)
      DIMENSION PRPY(3)

      CHARACTER*8      DTYPE,OBS1
      CHARACTER*8      BLKNEW, BLKOLD
      CHARACTER(1) ::  BLANK, EDTFLG   ! jjm 20150224
      DATA DTYPE/'IMAGE   '/
      DATA KENTRY/0/
      DATA OBS1/'        '/
      DATA BLANK/' ' /,EDTFLG/'*'/,BLKNEW/'(*NEW*)'/,BLKOLD/'(CONT.)'/
      CHARACTER*1 TIMSYS
      DATA TIMSYS/'R','X','T'/
      DATA NUM/3*0/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEMP CAMERA !!!!!!!!!!!!!!!!!!!!!!!
!      DATA CTR/512.5,512.5/
!      DATA XKMAT/71.42860D0,0.00386,0.00000D0,0.00386,               &
!     &          -71.44341D0,0.00000D0/
      DATA CTR/0.0D0,0.0D0/
      DATA XKMAT/0.0D0,0.0D0,0.0D0,0.0D0,0.0D0,0.0D0/
      DATA DELCP/1.D0,4*0.1D-07/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEMP CAMERA !!!!!!!!!!!!!!!!!!!!!!!
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!**********************************************************************
! INITIALIZATIONS
!**********************************************************************
!       write(6,*)' DEBUG ENTER IMAGER '

      LPLN=LSTINR.AND.NPVAL0(IXXTRO).GT.0
      DO J=1,2
       DO I=1,3
        VPBRA(I,J)=0.D0
        VPBDC(I,J)=0.D0
        VPBGA(I,J)=0.D0
        XBFRA(I,J)=0.D0
        XBFDC(I,J)=0.D0
        XBFGA(I,J)=0.D0
       END DO
      END DO


      LPRINT=.FALSE.
      kentry=kentry+1
      write(6,*)'LINIM',LINIM
       IF(LINIM) THEN
        REWIND(55)
        DO I=1,80
          NSEGM(I)=1
        ENDDO
! RESET SATELITE INDICES
        ISTLST=0
        INTOSP=0
      ENDIF
      LINIM=.FALSE.


      READ(55,12345)ICTYPE,TIM1,FSEC1,TIM2,FSEC2
12345 FORMAT(I25,4G25.16)

      IF(ICTYPE.NE.33) THEN
      WRITE(6,*)' WRONG MEASUREMENT TYPE ON FILE 55 '
      STOP
      ENDIF

        MJDS(1)=INT(TIM1)
        MJDS(2)=INT(TIM2)
        JFSECN=KFSECS(1,1)

!       CHECK TIME OF FIRST OBSERVATION
!       CONVERT TIMES TO ET
         CALL UTCET(.TRUE.,1,MJDS(1),FSEC1,FSECOT(1),AA(KA1UT))
         CALL UTCET(.TRUE.,1,MJDS(2),FSEC2,FSECOT(2),AA(KA1UT))
!!       TIME OF CURRENT FIRST OBSERVATION IN A PAIR
         TOBS=DBLE(MJDSBL)+AA(JFSECN)
!!       TIME OF FIRST TIME IN THE RECORD
         TIME1=DBLE(MJDS(1))+FSECOT(1)

         IF(TOBS.NE.TIME1) THEN
!!    1. The current observation is the second in a pair skip it and read
!!       the next.
!!    2. The current observation is the first in another pair. Keep on reading
         RETURN
         ENDIF
!       CHECK TIME OF FIRST OBSERVATION

!  LOAD V1 V2 ORIENTATION VECTORS IN THE SBF SYSTEM

      DO J=1,3
      V1(J)=VIMAGE(J)
      V2(J)=VIMAGE(3+J)
      VIMG1(J)=V1(J)
      VIMG2(J)=V2(J)
      ENDDO
      CAMID1=V1(3)
      CAMID2=V2(3)

!   CLEAR UP COMPLETELY THE RMVPRT ARRAY
      NXDM=NDIMX1*NDIMX2*NDIMX3*2*2
      CALL CLEARA(RMVPRT,NXDM)

! DEP COMMENT This is a loop 1,2 for the two observations in a pair
      DO IL=1,2

      DO I=1,3
      V(I)=VIMAGE(I+(IL-1)*3)
      ENDDO

      ISATID=II(KISATN+INDSAT(IL)-1)
      ISET=INDSET(IL)
      ISAT=INDSAT(IL)

      MJDSP=MJDS(IL)
      FSECN=FSECOT(IL)

      IF(INTOSP.EQ.0) INTOSP=1
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET1)
      IF(IRET1.GT.0) THEN
      KNSTEPS=II(KSTEPS-1+IRET1)
      NEQNI=II(KNEQNI-1+IRET1)
      ENDIF
!
! OBTAIN SATELLITE POSITIONS AT CORRECT SATELLITE TIMES
      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),ISAT,                &
     &   KNSTEPS,NEQNI,II(KSGMNT-1+IRET1),                             &
     &   AA(KSGTM1-1+IRET1),AA(KSGTM2-1+IRET1),IRET1,MJDSP,FSECN,      &
     &   FSECN,1,AA,II)

      IF(NINTOT.GT.0) THEN
      IF(IRET1.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      ENDIF
      ENDIF
! DEBUG
! WRITE(6,*)' DBG NEQN FOR THIS SATELLITE ',NEQNI

!     INTEGRATE TO OBS TIME.
! DEP COMMENT This is done twice in the loop one for each time in the
!          pair to get  satellite position at time.

      CALL ORBIT(MJDSP,FSECN,AA(KS),1,II(KINDH),II(KNMH),II(KMJDSC),    &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM,PXPF,                    &
     &   LNADJ,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),                &
     &   AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET1),         &
     &   AA(KSGTM1-1+IRET1),AA(KSGTM2-1+IRET1),AA,II,LL)

      CALL DXEDXI(AA,II,LL,MJDSP,FSECN,NM,XTD,XTP,XMP,PXEXI)

! DEP COMMENT theta pbf /theta tod inertial (14)
       DO I=1,3
       DO J=1,3
       DXPDXI(I,J,IL)=PXEXI(I,J)
       ENDDO
       ENDDO

      JTERP=0

      CALL ALTPTI(AA,II,LL,NM,MJDSP,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &           XTRA(1,7),XSM,VSM,JTERP,ATROT,HOLD,2,FRQLNK,MTYPE, &
     &           SBFTOR)

      TRKTOR(1,IL)=XTRA(1,4)
      TRKTOR(2,IL)=XTRA(1,5)
      TRKTOR(3,IL)=XTRA(1,6)


      TAT(IL)=XBTIME
      TIMEA(IL)=FSECN-(TAT(IL)-DBLE(MJDSP))

!  INITIALIZE ATTITUDE ADJUSTMENT FLAGS
!  LIMAT TRUE IF S/C ORIENTAION IS ADJUSTED
      LIMAT  =.FALSE.
!  LIMCAM TRUE IF CAMERA  ORIENTAION IS ADJUSTED
      LIMCAM =.FALSE.
! IAPLSC = # OF S/C WITH ATTITUDE PARAMETERS
! IAPLL  = # OF LASERS BUT IN THE CASE OF IMAGES CAMERAS
      IF(IAPLSC.GT.0) LIMAT =.TRUE.
      IF(IAPLL .GT.0) LIMCAM=.TRUE.
! GET LOCATION OF PMPA FOR THE ATTITUDE PARTIALS FOR S/C AND CAMERA
      IPAT1(IL)=IAPLSC
      IPAT2(IL)=IAPLL
! DEBUG ****************************************************************
!     write(6,*)' POINT AT PMPA FOR ATT PARTIALS S/C ',IPAT1(IL)
!     write(6,*)' POINT AT PMPA FOR ATT PARTIALS LASER ',IPAT2(IL)
! DEBUG ****************************************************************

      DO I=1,NM

      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBF1(1,1),AA,1,1,     &
     &            .TRUE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBF1(1,2),AA,1,1,     &
     &            .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBF1(1,3),AA,1,1,     &
     &            .FALSE.,.FALSE.,II,0)
      ENDDO

      DO JJ=1,3
       DO KK=1,3
        TOTRIM(JJ,KK,IL)=SBF1(JJ,KK)
       END DO
      END DO

!  CONVERT SBF ORIENTATION VECTOR TO  INERTIAL TOD
      IF(LPLN) THEN
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBFRA(1,1,IL),AA,1,1,.TRUE.,&
     &           .FALSE.,II,1)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBFRA(1,2,IL),AA,1,1,.FALSE.,&
     &           .FALSE.,II,1)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBFRA(1,3,IL),AA,1,1,.FALSE.,&
     &           .FALSE.,II,1)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBFDC(1,1,IL),AA,1,1,.TRUE.,&
     &           .FALSE.,II,2)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBFDC(1,2,IL),AA,1,1,.FALSE.,&
     &           .FALSE.,II,2)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBFDC(1,3,IL),AA,1,1,.FALSE.,&
     &           .FALSE.,II,2)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),VVTMP(1,IL),AA,1,1,.TRUE.,&
     &           .FALSE.,II,0)
      ENDIF

      IF (LIMAT) THEN

!  IDENTIFY CAMERA LOCATION
      IF(IL.EQ.1) CAMID=CAMID1
      IF(IL.EQ.2) CAMID=CAMID2
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET2)

      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5)
      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values ',FLMMH,DISTRH(2)
      IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF

! load ccd information (if given on CAMERA card)

      IF (IRET2.NE.0) THEN
        DO J=1,6
          XKMAT(J)=CKXMAT(IRET2,J)
        END DO
        DO J=1,2
          CTR(J)=CAMCTR(IRET2,J)
        END DO
      END IF


      PXV(1)=V(1)
      PXV(2)=V(2)

      CALL GETVEC(PXV,XKMAT,DISTRH,FLMM,CTR,VIMG)

      IF (IL.EQ.1) THEN
         VIMG1(1)=VIMG(1)
         VIMG1(2)=VIMG(2)
         VIMG1(3)=VIMG(3)
      ELSE
         VIMG2(1)=VIMG(1)
         VIMG2(2)=VIMG(2)
         VIMG2(3)=VIMG(3)
      END IF

      INDAT=10

      DO 30401 K=1,3
      INDAT=INDAT+1
      CALL ALTPTI(AA,II,LL,NM,MJDSP,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &        XTRA(1,7),XSM,VSM,INDAT,ATROT,HOLD,2,FRQLNK,MTYPE,    &
     &        SBFTOR)

      GOTO (303,304,305),K

303   CONTINUE
      DO I=1,NM

      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBF2(1,1),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBF2(1,2),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBF2(1,3),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)

      VRTOD(1,IL)=SBF2(1,1)*VIMG(1)+SBF2(1,2)*VIMG(2)+ &
     &         SBF2(1,3)*VIMG(3)
      VRTOD(2,IL)=SBF2(2,1)*VIMG(1)+SBF2(2,2)*VIMG(2)+ &
     &         SBF2(2,3)*VIMG(3)
      VRTOD(3,IL)=SBF2(3,1)*VIMG(1)+SBF2(3,2)*VIMG(2)+ &
     &         SBF2(3,3)*VIMG(3)
      END DO
      GOTO  30401


304   CONTINUE
      DO I=1,NM

      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBF3(1,1),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBF3(1,2),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBF3(1,3),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)

      VPTOD(1,IL)=SBF3(1,1)*VIMG(1)+SBF3(1,2)*VIMG(2)+ &
     &         SBF3(1,3)*VIMG(3)
      VPTOD(2,IL)=SBF3(2,1)*VIMG(1)+SBF3(2,2)*VIMG(2)+ &
     &         SBF3(2,3)*VIMG(3)
      VPTOD(3,IL)=SBF3(3,1)*VIMG(1)+SBF3(3,2)*VIMG(2)+ &
     &         SBF3(3,3)*VIMG(3)
       END DO
      GOTO  30401


305   CONTINUE
      DO I=1,NM

      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,1),SBF4(1,1),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,2),SBF4(1,2),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,SBFTOR(1,3),SBF4(1,3),AA,1,1,   &
     &           .FALSE.,.FALSE.,II,0)

      VYTOD(1,IL)=SBF4(1,1)*VIMG(1)+SBF4(1,2)*VIMG(2)+ &
     &         SBF4(1,3)*VIMG(3)
      VYTOD(2,IL)=SBF4(2,1)*VIMG(1)+SBF4(2,2)*VIMG(2)+ &
     &         SBF4(2,3)*VIMG(3)
      VYTOD(3,IL)=SBF4(3,1)*VIMG(1)+SBF4(3,2)*VIMG(2)+ &
     &         SBF4(3,3)*VIMG(3)
       END DO
30401 CONTINUE
      ENDIF

!***************************************************************************
! CLEAR UP THE ARTOT ARRAY TO USE IT FOR THE CAMERA ROTATIONS

      DO  901 IJ1=1,3
      DO  901 IJ2=1,3
      DO  901 K=1,NM
      ATROT(IJ1,IJ2,K)=0.D0
  901 CONTINUE
      DO IJ1=1,3
      DO K=1,NM
      ATROT(IJ1,IJ1,K)=1.D0
      ENDDO
      ENDDO

!     GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF CAM ATT PARTIALS

      IF(LIMCAM)  THEN
      INDAT=13

      DO 30402 K=1,3
      INDAT=INDAT+1

      CALL ALTPTI(AA,II,LL,NM,MJDSP,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &        XTRA(1,7),XSM,VSM,INDAT,ATROT,HOLD,2,FRQLNK,MTYPE,SBFTOR)

      GOTO ( 306,307,308),K

306   CONTINUE
      DO I=1,NM
      TOCROL(1,1,IL)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+         &
     &        SBFTOR(3,1)*RMI(7)
      TOCROL(2,1,IL)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+         &
     &        SBFTOR(3,1)*RMI(8)
      TOCROL(3,1,IL)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+         &
     &        SBFTOR(3,1)*RMI(9)
      TOCROL(1,2,IL)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+         &
     &        SBFTOR(3,2)*RMI(7)
      TOCROL(2,2,IL)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+         &
     &        SBFTOR(3,2)*RMI(8)
      TOCROL(3,2,IL)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+         &
     &        SBFTOR(3,2)*RMI(9)
      TOCROL(1,3,IL)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+         &
     &        SBFTOR(3,3)*RMI(7)
      TOCROL(2,3,IL)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+         &
     &        SBFTOR(3,3)*RMI(8)
      TOCROL(3,3,IL)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+         &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO

      VATOD(1,IL)=TOCROL(1,1,IL)*V(1)+TOCROL(1,2,IL)*V(2)+ &
     &         TOCROL(1,3,IL)*V(3)
      VATOD(2,IL)=TOCROL(2,1,IL)*V(1)+TOCROL(2,2,IL)*V(2)+ &
     &         TOCROL(2,3,IL)*V(3)
      VATOD(3,IL)=TOCROL(3,1,IL)*V(1)+TOCROL(3,2,IL)*V(2)+ &
     &         TOCROL(3,3,IL)*V(3)

      VCRPBF(1,IL)=VATOD(1,IL)*TODPBF(1,1,IL)+VATOD(2,IL)*TODPBF(1,2,IL)
      VCRPBF(2,IL)=VATOD(1,IL)*TODPBF(2,1,IL)+VATOD(2,IL)*TODPBF(2,2,IL)
      VCRPBF(3,IL)=VATOD(3,IL)*TODPBF(3,3,IL)

307   CONTINUE
      DO I=1,NM
      TOCPIT(1,1,IL)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+         &
     &        SBFTOR(3,1)*RMI(7)
      TOCPIT(2,1,IL)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+         &
     &        SBFTOR(3,1)*RMI(8)
      TOCPIT(3,1,IL)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+         &
     &        SBFTOR(3,1)*RMI(9)
      TOCPIT(1,2,IL)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+         &
     &        SBFTOR(3,2)*RMI(7)
      TOCPIT(2,2,IL)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+         &
     &        SBFTOR(3,2)*RMI(8)
      TOCPIT(3,2,IL)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+         &
     &        SBFTOR(3,2)*RMI(9)
      TOCPIT(1,3,IL)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+         &
     &        SBFTOR(3,3)*RMI(7)
      TOCPIT(2,3,IL)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+         &
     &        SBFTOR(3,3)*RMI(8)
      TOCPIT(3,3,IL)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+         &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO

      VATOD(1,IL)=TOCPIT(1,1,IL)*V(1)+TOCPIT(1,2,IL)*V(2)+ &
     &         TOCPIT(1,3,IL)*V(3)
      VATOD(2,IL)=TOCPIT(2,1,IL)*V(1)+TOCPIT(2,2,IL)*V(2)+ &
     &         TOCPIT(2,3,IL)*V(3)
      VATOD(3,IL)=TOCPIT(3,1,IL)*V(1)+TOCPIT(3,2,IL)*V(2)+ &
     &         TOCPIT(3,3,IL)*V(3)

      VCPPBF(1,IL)= VATOD(1,IL)*TODPBF(1,1,IL)+VATOD(2,IL)*TODPBF(1,2,IL)
      VCPPBF(2,IL)= VATOD(1,IL)*TODPBF(2,1,IL)+VATOD(2,IL)*TODPBF(2,2,IL)
      VCPPBF(3,IL)= VATOD(3,IL)*TODPBF(3,3,IL)

308   CONTINUE
      DO I=1,NM
      TOCYAW(1,1,IL)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+         &
     &        SBFTOR(3,1)*RMI(7)
      TOCYAW(2,1,IL)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+         &
     &        SBFTOR(3,1)*RMI(8)
      TOCYAW(3,1,IL)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+         &
     &        SBFTOR(3,1)*RMI(9)
      TOCYAW(1,2,IL)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+         &
     &        SBFTOR(3,2)*RMI(7)
      TOCYAW(2,2,IL)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+         &
     &        SBFTOR(3,2)*RMI(8)
      TOCYAW(3,2,IL)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+         &
     &        SBFTOR(3,2)*RMI(9)
      TOCYAW(1,3,IL)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+         &
     &        SBFTOR(3,3)*RMI(7)
      TOCYAW(2,3,IL)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+         &
     &        SBFTOR(3,3)*RMI(8)
      TOCYAW(3,3,IL)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+         &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO

      VATOD(1,IL)=TOCYAW(1,1,IL)*V(1)+TOCYAW(1,2,IL)*V(2)+ &
     &         TOCYAW(1,3,IL)*V(3)
      VATOD(2,IL)=TOCYAW(2,1,IL)*V(1)+TOCYAW(2,2,IL)*V(2)+ &
     &         TOCYAW(2,3,IL)*V(3)
      VATOD(3,IL)=TOCYAW(3,1,IL)*V(1)+TOCYAW(3,2,IL)*V(2)+ &
     &         TOCYAW(3,3,IL)*V(3)

      VCYPBF(1,IL)= VATOD(1,IL)*TODPBF(1,1,IL)+VATOD(2,IL)*TODPBF(1,2,IL)
      VCYPBF(2,IL)= VATOD(1,IL)*TODPBF(2,1,IL)+VATOD(2,IL)*TODPBF(2,2,IL)
      VCYPBF(3,IL)= VATOD(3,IL)*TODPBF(3,3,IL)


30402 CONTINUE
      ENDIF

! END GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF ATTITUDE PARTIALS
! DEP COMMENT CODE (8)
!     CONVERT XSM FROM INERTIAL TOR TO INERTIAL TOD
!     XSM SATELLITE COORDINATES
!     FIRST ADD IN TOR TRACKING PT OFFSET

      XSM(1,1)=XSM(1,1)+TRKTOR(1,IL)
      XSM(1,2)=XSM(1,2)+TRKTOR(2,IL)
      XSM(1,3)=XSM(1,3)+TRKTOR(3,IL)


      CALL SATUPD(MJDSP,FSECN,XSM,XSMTOD1,AA,1,MINTIM,.TRUE.,        &
     &           .FALSE.,II,0)
      CALL SATUPD(MJDSP,FSECN,VSM,VSMTOD1,AA,1,MINTIM,.FALSE.,       &
     &           .FALSE.,II,0)
      DO JJ=1,3
         XSMTOD(1,JJ,IL)=XSMTOD1(1,JJ)
         VSMTOD(1,JJ,IL)=VSMTOD1(1,JJ)
      END DO

! DEP COMMENT CODE (9)
! COMPUTE THE PRIME MERIDIAN ANGLE

      IF(ICBDGM.EQ.3) THEN
      CALL GRHRAN(MJDSP,FSECN,.FALSE.,.FALSE.,AA(KEQN),AA(KSRTCH),  &
     &  THETAG,COSTHG,SINTHG,NM,AA,II,AA(KXUTDT))

      ELSE

      CALL ROTXTR(MJDSP,FSECN,.FALSE.,AA(KEQN),AA(KSRTCH),          &
     &   AA(KTHETG),COSTHG,SINTHG,NM,AA,AA(KACOSW),                  &
     &   AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),AA(KBCOFW),II)

      ENDIF
      DO N=1,NM
      PBF(1,1)=COSTHG(N)
      PBF(1,2)=SINTHG(N)
      PBF(1,3)=0.D0
      PBF(2,1)=-SINTHG(N)
      PBF(2,2)=COSTHG(N)
      PBF(2,3)=0.D0
      PBF(3,1)=0.D0
      PBF(3,2)=0.D0
      PBF(3,3)=1.D0
      ENDDO
      DO I=1,3
      DO J=1,3
      TODPBF(I,J,IL)=PBF(I,J)
      ENDDO
      ENDDO

      IF(LPLN) THEN
      VTMP(1)=XSM(1,1)
      VTMP(2)=XSM(1,2)
      VTMP(3)=XSM(1,3)
      VVVTP(1)=VVTMP(1,IL)
      VVVTP(2)=VVTMP(2,IL)
      VVVTP(3)=VVTMP(3,IL)
      CALL SATUPD(MJDSP,FSECN,VTMP,XSMTRA,AA,1,1,.TRUE.,          &
     &           .FALSE.,II,1)
      CALL SATUPD(MJDSP,FSECN,VTMP,XSMTDC,AA,1,1,.TRUE.,          &
     &           .FALSE.,II,2)
      CALL SATUPD(MJDSP,FSECN,VVVTP,XSMTDC,AA,1,1,.TRUE.,   &
     &           .FALSE.,II,0)
      THG=ATAN2(SINTHG(1),COSTHG(1))
      THG=THG+DXGEO2*DEGRAD
      COSTG=COS(THG)
      SINTG=SIN(THG)
      PBFGA(1,1)=COSTG
      PBFGA(1,2)=SINTG
      PBFGA(1,3)=0.D0
      PBFGA(2,1)=-SINTG
      PBFGA(2,2)=COSTG
      PBFGA(2,3)=0.D0
      PBFGA(3,1)=0.D0
      PBFGA(3,2)=0.D0
      PBFGA(3,3)=1.D0
      XBFRA(1,IL)= XSMTRA(1)*PBF(1,1) + XSMTRA(2)*PBF(1,2)
      XBFRA(2,IL)= XSMTRA(1)*PBF(2,1) + XSMTRA(2)*PBF(2,2)
      XBFRA(3,IL)= XSMTRA(3)*PBF(3,3)
      XBFDC(1,IL)= XSMTDC(1)*PBF(1,1) + XSMTDC(2)*PBF(1,2)
      XBFDC(2,IL)= XSMTDC(1)*PBF(2,1) + XSMTDC(2)*PBF(2,2)
      XBFDC(3,IL)= XSMTDC(3)*PBF(3,3)
      XBFGA(1,IL)= XSMTOD1(1,1)*PBFGA(1,1) + XSMTOD1(1,2)*PBFGA(1,2)
      XBFGA(2,IL)= XSMTOD1(1,1)*PBFGA(2,1) + XSMTOD1(1,2)*PBFGA(2,2)
      XBFGA(3,IL)= XSMTOD1(1,3)*PBFGA(3,3)
      VTMP(1)=SBFRA(1,1,IL)*VIMG(1)+SBFRA(1,2,IL)*VIMG(2)+             &
     &        SBFRA(1,3,IL)*VIMG(3)
      VTMP(2)=SBFRA(2,1,IL)*VIMG(1)+SBFRA(2,2,IL)*VIMG(2)+             &
     &        SBFRA(2,3,IL)*VIMG(3)
      VTMP(3)=SBFRA(3,1,IL)*VIMG(1)+SBFRA(3,2,IL)*VIMG(2)+             &
     &        SBFRA(3,3,IL)*VIMG(3)
      VPBRA(1,IL)= VTMP(1)*PBF(1,1) + VTMP(2)*PBF(1,2)
      VPBRA(2,IL)= VTMP(1)*PBF(2,1) + VTMP(2)*PBF(2,2)
      VPBRA(3,IL)= VTMP(3)*PBF(3,3)
      VTMP(1)=SBFDC(1,1,IL)*VIMG(1)+SBFDC(1,2,IL)*VIMG(2)+             &
     &        SBFDC(1,3,IL)*VIMG(3)
      VTMP(2)=SBFDC(2,1,IL)*VIMG(1)+SBFDC(2,2,IL)*VIMG(2)+             &
     &        SBFDC(2,3,IL)*VIMG(3)
      VTMP(3)=SBFDC(3,1,IL)*VIMG(1)+SBFDC(3,2,IL)*VIMG(2)+             &
     &        SBFDC(3,3,IL)*VIMG(3)
      VPBDC(1,IL)= VTMP(1)*PBF(1,1) + VTMP(2)*PBF(1,2)
      VPBDC(2,IL)= VTMP(1)*PBF(2,1) + VTMP(2)*PBF(2,2)
      VPBDC(3,IL)= VTMP(3)*PBF(3,3)
      VTMP(1)=SBF1(1,1)*VIMG(1)+SBF1(1,2)*VIMG(2)+           &
     &        SBF1(1,3)*VIMG(3)
      VTMP(2)=SBF1(2,1)*VIMG(1)+SBF1(2,2)*VIMG(2)+           &
     &        SBF1(2,3)*VIMG(3)
      VTMP(3)=SBF1(3,1)*VIMG(1)+SBF1(3,2)*VIMG(2)+           &
     &        SBF1(3,3)*VIMG(3)
      VPBGA(1,IL)= VTMP(1)*PBFGA(1,1) + VTMP(2)*PBFGA(1,2)
      VPBGA(2,IL)= VTMP(1)*PBFGA(2,1) + VTMP(2)*PBFGA(2,2)
      VPBGA(3,IL)= VTMP(3)*PBFGA(3,3)
      END IF

      VRPBF(1,IL)= VRTOD(1,IL)*TODPBF(1,1,IL)+VRTOD(2,IL)*TODPBF(1,2,IL)
      VRPBF(2,IL)= VRTOD(1,IL)*TODPBF(2,1,IL)+VRTOD(2,IL)*TODPBF(2,2,IL)
      VRPBF(3,IL)= VRTOD(3,IL)*TODPBF(3,3,IL)

      VPPBF(1,IL)= VPTOD(1,IL)*TODPBF(1,1,IL)+VPTOD(2,IL)*TODPBF(1,2,IL)
      VPPBF(2,IL)= VPTOD(1,IL)*TODPBF(2,1,IL)+VPTOD(2,IL)*TODPBF(2,2,IL)
      VPPBF(3,IL)= VPTOD(3,IL)*TODPBF(3,3,IL)

      VYPBF(1,IL)= VYTOD(1,IL)*TODPBF(1,1,IL)+VYTOD(2,IL)*TODPBF(1,2,IL)
      VYPBF(2,IL)= VYTOD(1,IL)*TODPBF(2,1,IL)+VYTOD(2,IL)*TODPBF(2,2,IL)
      VYPBF(3,IL)= VYTOD(3,IL)*TODPBF(3,3,IL)


!
! **************************************************************************
! ROTATION MATRICES FOR ATTITUDE PARTIAL COMPUTATIONS
! **************************************************************************
! HERE PERTURB ROLL PITCH YAW IF APPLIES AND GET THREE ROTATION MATRICES
! PER IL
!
!     GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF ATTITUDE PARTIALS

! DEP COMMENT VARIATIONAL PARTIALS:  (13)
      DO I=1,NM

! OBTAIN THE PARTIALS OF OBS WRT FM PARAMETERS FOR BOTH POINTS (VARIATIONAL)
      IF(LNPNM) GOTO 30304
      DO 30303 KK=1,NDIMX2
      DO 30302 K2=1,3
! PXPF POSITION
 !!!     RMVPRT(I,KK,K2,1,IL)=PXPF(I,KK,K2,1)
! PXPF VELOCITY
 !!!     RMVPRT(I,KK,K2,2,IL)=PXPF(I,KK,K2,2)

       IF (IL.EQ.1) X2PART(KK,K2,1,IL)=PXPF(I,KK,K2,1)
       IF (IL.EQ.1) X2PART(KK,K2,2,IL)=PXPF(I,KK,K2,2)

! PXPF POSITION
       IF (IL.EQ.2) RMVPRT(I,KK,K2,1,1)=X2PART(KK,K2,1,1)
       IF (IL.EQ.2) RMVPRT(I,KK,K2,1,2)=PXPF(I,KK,K2,1)

! PXPF VELOCITY
       IF (IL.EQ.2) RMVPRT(I,KK,K2,2,1)=X2PART(KK,K2,2,1)
       IF (IL.EQ.2) RMVPRT(I,KK,K2,2,2)=PXPF(I,KK,K2,2)

30302 END DO
30303 END DO
      GOTO 30307
30304 CONTINUE
      DO 30306 KK=1,NDIMX1
      DO 30305 K2=1,3
! PXPF POSITION
  !!!    RMVPRT(KK,K2,I,1,IL)=PXPF(KK,K2,I,1)
! PXPF VELOCITY
  !!!    RMVPRT(KK,K2,I,2,IL)=PXPF(KK,K2,I,2)

       IF (IL.EQ.1) X2PART(KK,K2,1,KIMBPA)=PXPF(KK,K2,I,1)
       IF (IL.EQ.1) X2PART(KK,K2,2,KIMBPA)=PXPF(KK,K2,I,2)

! PXPF POSITION
       IF (IL.EQ.2) RMVPRT(KK,K2,I,1,1)=X2PART(KK,K2,1,1)
       IF (IL.EQ.2) RMVPRT(KK,K2,I,1,2)=PXPF(KK,K2,I,1)
! PXPF VELOCITY
       IF (IL.EQ.2) RMVPRT(KK,K2,I,2,1)=X2PART(KK,K2,2,1)
       IF (IL.EQ.2) RMVPRT(KK,K2,I,2,2)=PXPF(KK,K2,I,2)

30305 END DO
30306 END DO
30307 CONTINUE
      ENDDO


      NEQP(IL)=NEQN
      ENDDO   ! DO IL=1,2

! DEBUG ****************************************************************
      write(6,*)' DDP MJDSBL    FOR BOTH BLOCKS ',MJDS(1), MJDS(2)
      write(6,*)' DDP FRAC ET SEC FOR BOTH ',FSECOT(1),FSECOT(2)
      write(6,*)'DP TOD X S/C BOTH BLOCKS',XSMTOD(1,1,1),XSMTOD(1,1,2)
      write(6,*)'DP TOD X S/C BOTH BLOCKS',XSMTOD(1,2,1),XSMTOD(1,2,2)
      write(6,*)'DP TOD X S/C BOTH BLOCKS',XSMTOD(1,3,1),XSMTOD(1,3,2)
! DEBUG ****************************************************************

! DEP COMMENT This was  a loop 1,2 for the two observations in a pair
!!!!!!!!!!!!!!!!!!!!

!***********************************************************************
! FORM OBSERVATION
!***********************************************************************
!  COMPUTE THE OBSERVATION USING THE PROVIDED DIRECTION VECTORS ON G2B
!    R1 FIRST OCC RANGE/ R2 SECOND

      DO 30311 I=1,NM

      DO 30310 IXX=1,6

!   FIRST CAMERA
      CAMID=CAMID1
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET2)

      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5)
      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values ',FLMMH,DISTRH(2)
      IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF
!
      IF(IXX.EQ.1) FLMMH=FLMMH+DELCP(1)
      IF(IXX.GT.1.AND.IXX.LT.6) DISTRH(IXX-1)=DISTRH(IXX-1)+DELCP(IXX)

      DO JJ=1,3
         VIMG1(JJ)=0.0D0
      END DO

       CALL GETVEC(V1,XKMAT,DISTRH,FLMMH,CTR,VIMG1)

!   SECOND CAMERA

!   FIRST CAMERA
      CAMID=CAMID2
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET2)

      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5)
      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET2-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET2-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values ',FLMMH,DISTRH(2)
      IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF
!
      IF(IXX.EQ.1) FLMMH=FLMMH+DELCP(1)
      IF(IXX.GT.1.AND.IXX.LT.6) DISTRH(IXX-1)=DISTRH(IXX-1)+DELCP(IXX)

      DO JJ=1,3
         VIMG2(JJ)=0.0D0
      END DO

       CALL GETVEC(V2,XKMAT,DISTRH,FLMMH,CTR,VIMG2)

      VTOD(1,1)=TOTRIM(1,1,1)*VIMG1(1)+TOTRIM(1,2,1)*VIMG1(2)+ &
     &         TOTRIM(1,3,1)*VIMG1(3)
      VTOD(2,1)=TOTRIM(2,1,1)*VIMG1(1)+TOTRIM(2,2,1)*VIMG1(2)+ &
     &         TOTRIM(2,3,1)*VIMG1(3)
      VTOD(3,1)=TOTRIM(3,1,1)*VIMG1(1)+TOTRIM(3,2,1)*VIMG1(2)+ &
     &         TOTRIM(3,3,1)*VIMG1(3)
      VTOD(1,2)=TOTRIM(1,1,2)*VIMG2(1)+TOTRIM(1,2,2)*VIMG2(2)+ &
     &         TOTRIM(1,3,2)*VIMG2(3)
      VTOD(2,2)=TOTRIM(2,1,2)*VIMG2(1)+TOTRIM(2,2,2)*VIMG2(2)+ &
     &         TOTRIM(2,3,2)*VIMG2(3)
      VTOD(3,2)=TOTRIM(3,1,2)*VIMG2(1)+TOTRIM(3,2,2)*VIMG2(2)+ &
     &         TOTRIM(3,3,2)*VIMG2(3)

       DO IL=1,2
      XBF(I,1,IL)=  XSMTOD(I,1,IL)*TODPBF(1,1,IL)+        &
     &            XSMTOD(I,2,IL)*TODPBF(1,2,IL)
      XBF(I,2,IL)=  XSMTOD(I,1,IL)*TODPBF(2,1,IL)+        &
     &            XSMTOD(I,2,IL)*TODPBF(2,2,IL)
      XBF(I,3,IL)=  XSMTOD(I,3,IL)*TODPBF(3,3,IL)

      VPBF(1,IL)= VTOD(1,IL)*TODPBF(1,1,IL) +           &
     &            VTOD(2,IL)*TODPBF(1,2,IL)
      VPBF(2,IL)= VTOD(1,IL)*TODPBF(2,1,IL) +           &
     &            VTOD(2,IL)*TODPBF(2,2,IL)
      VPBF(3,IL)= VTOD(3,IL)*TODPBF(3,3,IL)

      VLPBF(I,1,IL)= VSMTOD(I,1,IL)*TODPBF(1,1,IL)+       &
     &               VSMTOD(I,2,IL)*TODPBF(1,2,IL)
      VLPBF(I,2,IL)= VSMTOD(I,1,IL)*TODPBF(2,1,IL)+       &
     &               VSMTOD(I,2,IL)*TODPBF(2,2,IL)
      VLPBF(I,3,IL)= VSMTOD(I,3,IL)*TODPBF(3,3,IL)
          END DO

      IF(IXX.EQ.6) THEN
      write(6,*)'DDP PBF X S/C FOR BOTH BLOCKS',XBF(I,1,1),XBF(I,1,2)
      write(6,*)'DDP PBF Y S/C FOR BOTH BLOCKS',XBF(I,2,1),XBF(I,2,2)
      write(6,*)'DDP PBF Z S/C FOR BOTH BLOCKS',XBF(I,3,1),XBF(I,3,2)
        write(6,*)' DDP DIR VECTORS IN SBF ',VIMAGE(1),VIMAGE(4)
        write(6,*)' DDP DIR VECTORS IN SBF ',VIMAGE(2),VIMAGE(5)
        write(6,*)' DDP DIR VECTORS IN SBF ',VIMAGE(3),VIMAGE(6)
        write(6,*)' DDP DIR VECTORS IN TOD ',VTOD(1,1),VTOD(1,2)
        write(6,*)' DDP DIR VECTORS IN TOD ',VTOD(2,1),VTOD(2,2)
        write(6,*)' DDP DIR VECTORS IN TOD ',VTOD(3,1),VTOD(3,2)
        write(6,*)' DDP DIR VECTORS IN PBF ',VPBF(1,1),VPBF(1,2)
        write(6,*)' DDP DIR VECTORS IN PBF ',VPBF(2,1),VPBF(2,2)
        write(6,*)' DDP DIR VECTORS IN PBF ',VPBF(3,1),VPBF(3,2)
      ENDIF

! COMPUTE LANDMARK COORDINATES IN THE PBF SYSTEM
! NORMALIZE V1PBF V2PBF
      A=SQRT(VPBF(1,1)*VPBF(1,1) + VPBF(2,1)*VPBF(2,1) + &
     &             VPBF(3,1)*VPBF(3,1))
      B=SQRT(VPBF(1,2)*VPBF(1,2) + VPBF(2,2)*VPBF(2,2) + &
     &             VPBF(3,2)*VPBF(3,2))

      DO JJ=1,3
         V1PBFN(JJ)=VPBF(JJ,1)/A
         V2PBFN(JJ)=VPBF(JJ,2)/B
      END DO

      DP(1)=XBF(I,1,2)-XBF(I,1,1)
      DP(2)=XBF(I,2,2)-XBF(I,2,1)
      DP(3)=XBF(I,3,2)-XBF(I,3,1)

      CALL DOTPRD(DP,V2PBFN,DE1,3,3,1,1)
      CALL DOTPRD(V1PBFN,V2PBFN,DE2,3,3,1,1)
      CALL DOTPRD(DP,V1PBFN,DE3,3,3,1,1)

      EPS1=1.D0-DE2**2.D0
      EPS2=DE1*DE2-DE3

      EMA=EPS2/EPS1
      EMB=DE1+DE2*EMA
      IF(EMA.LT.ZERO.OR.EMB.LT.ZERO) THEN
      WRITE(6,*)' WARNING NO MEANINGFUL INTERSECTION '
      ENDIF

      DO IK=1,3
      XBOUNCE(IK)=(XBF(I,IK,1)+XBF(I,IK,2)+    &
     &             EMA*V1PBFN(IK)+EMB*V2PBFN(IK))/2.D0
      ENDDO



!  COMPUTE N HAT
       CALL SSPIMG(VPBF(1,1),VPBF(1,2),ENHAT,CC,EF)

! MINIMUM DISTANCE
      DIST= (XBF(I,1,1) - XBF(I,1,2)) * ENHAT(1)   +     &
     &      (XBF(I,2,1) - XBF(I,2,2)) * ENHAT(2)   +     &
     &      (XBF(I,3,1) - XBF(I,3,2)) * ENHAT(3)

      IF(IXX.LE.5) DISTP(IXX)=DIST
      IF(IXX.EQ.6) write(6,*)'DDP COMPUTED MINIMUM DISTANCE  ',DIST

30310 CONTINUE

      DO IX=1,5
        DISTP(IX)=(DISTP(IX)-DIST)/DELCP(IX)
      ENDDO

      IF(LIMAT) THEN

      CALL SSPIMG(VRPBF(1,1),VPBF(1,2),ENHBR,CC,EF)

       DIST1R= (XBF(I,1,1) - XBF(I,1,2)) * ENHBR(1) +   &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBR(2) +   &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBR(3)

      CALL SSPIMG(VPPBF(1,1),VPBF(1,2),ENHBP,CC,EF)
       DIST1P= (XBF(I,1,1) - XBF(I,1,2)) * ENHBP(1)  +    &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBP(2)  +    &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBP(3)

      CALL SSPIMG(VYPBF(1,1),VPBF(1,2),ENHBY,CC,EF)
       DIST1Y= (XBF(I,1,1) - XBF(I,1,2)) * ENHBY(1)  +     &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBY(2)  +     &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBY(3)

       X2VPA(1,1,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,1,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,1,3,1)=-(DIST-DIST1Y)/ATTPRT
       X2VPA(1,2,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,2,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,2,3,1)=-(DIST-DIST1Y)/ATTPRT
       X2VPA(1,3,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,3,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,3,3,1)=-(DIST-DIST1Y)/ATTPRT

! SECOND POINT
      CALL SSPIMG(VPBF(1,1),VRPBF(1,2),ENHBR,CC,EF)
       DIST2R= (XBF(I,1,1) - XBF(I,1,2)) * ENHBR(1) +     &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBR(2) +     &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBR(3)

      CALL SSPIMG(VPBF(1,1),VPPBF(1,2),ENHBP,CC,EF)
       DIST2P= (XBF(I,1,1) - XBF(I,1,2)) * ENHBP(1)    +     &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBP(2)    +     &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBP(3)

      CALL SSPIMG(VPBF(1,1),VYPBF(1,2),ENHBY,CC,EF)
       DIST2Y= (XBF(I,1,1) - XBF(I,1,2)) * ENHBY(1)   +      &
     &         (XBF(I,2,1) - XBF(I,2,2)) * ENHBY(2)   +      &
     &         (XBF(I,3,1) - XBF(I,3,2)) * ENHBY(3)

       X2VPA(1,1,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,1,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,1,3,2)=-(DIST-DIST2Y)/ATTPRT
       X2VPA(1,2,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,2,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,2,3,2)=-(DIST-DIST2Y)/ATTPRT
       X2VPA(1,3,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,3,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,3,3,2)=-(DIST-DIST2Y)/ATTPRT

      ENDIF

      IF(LPLN) THEN

         CALL SSPIMG(VPBRA(1,1),VPBF(1,2),ENHPOR,CC,EF)
         DISTRA= (XBFRA(1,1) - XBF(I,1,2)) * ENHPOR(1)  +    &
     &           (XBFRA(2,1) - XBF(I,2,2)) * ENHPOR(2)  +    &
     &           (XBFRA(3,1) - XBF(I,3,2)) * ENHPOR(3)
         CALL SSPIMG(VPBDC(1,1),VPBF(1,2),ENHPOR,CC,EF)
         DISTDC= (XBFDC(1,1) - XBF(I,1,2)) * ENHPOR(1)  +    &
     &           (XBFDC(2,1) - XBF(I,2,2)) * ENHPOR(2)  +    &
     &           (XBFDC(3,1) - XBF(I,3,2)) * ENHPOR(3)
         CALL SSPIMG(VPBGA(1,1),VPBF(1,2),ENHPOR,CC,EF)
         DISTGA= (XBFGA(1,1) - XBF(I,1,2)) * ENHPOR(1)  +    &
     &           (XBFGA(2,1) - XBF(I,2,2)) * ENHPOR(2)  +    &
     &           (XBFGA(3,1) - XBF(I,3,2)) * ENHPOR(3)
         PPOR(1,1)=(DISTRA-DIST)/DXGEO1
         PPOR(2,1)=(DISTDC-DIST)/DXGEO1
         PPOR(3,1)=(DISTGA-DIST)/DXGEO2

         CALL SSPIMG(VPBF(1,1),VPBRA(1,2),ENHPOR,CC,EF)
         DISTRA= (XBF(I,1,1) - XBFRA(1,2)) * ENHPOR(1)  +    &
     &           (XBF(I,2,1) - XBFRA(2,2)) * ENHPOR(2)  +    &
     &           (XBF(I,3,1) - XBFRA(3,2)) * ENHPOR(3)
         CALL SSPIMG(VPBF(1,1),VPBDC(1,2),ENHPOR,CC,EF)
         DISTDC= (XBF(I,1,1) - XBFDC(1,2)) * ENHPOR(1)  +    &
     &           (XBF(I,2,1) - XBFDC(2,2)) * ENHPOR(2)  +    &
     &           (XBF(I,3,1) - XBFDC(3,2)) * ENHPOR(3)
         CALL SSPIMG(VPBF(1,1),VPBGA(1,2),ENHPOR,CC,EF)
         DISTGA= (XBF(I,1,1) - XBFGA(1,2)) * ENHPOR(1)  +    &
     &           (XBF(I,2,1) - XBFGA(2,2)) * ENHPOR(2)  +    &
     &           (XBF(I,3,1) - XBFGA(3,2)) * ENHPOR(3)
         PPOR(1,2)=(DISTRA-DIST)/DXGEO1
         PPOR(2,2)=(DISTDC-DIST)/DXGEO1
         PPOR(3,2)=(DISTGA-DIST)/DXGEO2

       ENDIF



30311 CONTINUE

       PART(1)=ENHAT(1)
       PART(2)=ENHAT(2)
       PART(3)=ENHAT(3)

!***********************************************************************
! END FORM OBSERVATION
!***********************************************************************
!***********************************************************************
!     PARTIALS CHAINING
!***********************************************************************
!

      NNPM=NDIM1*NDIM2
      CALL CLEARA(PMPA,NNPM)

      JPTD=0
      IF(NPVAL0(IXCAME).GE.5) THEN
        IPTD=IPVAL0(IXCAME)-1
        JPTD=IPTD+1
        IF(LNPNM) THEN
          DO IXD=1,5
           PMPA(IXD+IPTD,1)=DISTP(IXD)
          ENDDO
        ELSE
          DO IXD=1,5
           PMPA(1,IXD+IPTD)=DISTP(IXD)
          ENDDO
        ENDIF
      ENDIF


! FOR THE TWO POINTS IN THE PAIR
        IPT1=0
        IPT2=0

       DO JJ=1,2

      IF(JJ.EQ.1) CAMID=CAMID1
      IF(JJ.EQ.2) CAMID=CAMID2
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET2)

      JPTD=0
      IF(NPVAL0(IXCAME).GE.5) THEN
        IPTD=IPVAL0(IXCAME)-1+(IRET2-1)*5
        JPTD=IPTD+1
        IF(LNPNM) THEN
          DO IXD=1,5
           PMPA(IXD+IPTD,1)=DISTP(IXD)
          ENDDO
        ELSE
          DO IXD=1,5
           PMPA(1,IXD+IPTD)=DISTP(IXD)
          ENDDO
        ENDIF
      ENDIF



       IF(JJ.EQ.1) THEN
         NEQNU=NEQP(JJ)
         NDMXU1=NM
         NDMXU2=NEQNU
         NDMXU3=3
         IF(LNPNM) THEN
           NDMXU1=NEQNU
           NDMXU2=3
           NDMXU3=NM
         ENDIF
         JSAT=INDSAT(1)
         JSET=INDSET(1)
         IP0AT1=IPAT1(1)
         IP0AT2=IPAT2(1)
         PER=ATPER(JSAT)
         TIME1=TIMEA(JJ)
      ENDIF

      IF(JJ.EQ.2) THEN
         NEQNU=NEQP(JJ)
         NDMXU1=NM
         NDMXU2=NEQNU
         NDMXU3=3
         IF(LNPNM) THEN
           NDMXU1=NEQNU
           NDMXU2=3
           NDMXU3=NM
         ENDIF
         JSAT=INDSAT(2)
         JSET=INDSET(2)
         IP0AT1=IPAT1(2)
         IP0AT2=IPAT2(2)
         PER=ATPER(JSAT)
         TIME1=TIMEA(JJ)
      ENDIF

      SIGN=1.D0
      IF(JJ.EQ.2) SIGN=-1.D0

! DEP COMMENT (22) CHAIN PARTIALS
! POSITION PARTIALS

      DO 900 IX=1,3
      PMPI(1)=SIGN*PART(IX)*DXPDXI(1,IX,JJ)
      PMPI(2)=SIGN*PART(IX)*DXPDXI(2,IX,JJ)
      PMPI(3)=SIGN*PART(IX)*DXPDXI(3,IX,JJ)

! CHAIN DXPDXI PARTIALS TO FM PARTIALS

      NCLR=NDIM1*NDIM2

      CALL CLEARA(PXEPA,NCLR)
      CALL CHAIN (PMPI,NM,3,1,RMVPRT(1,1,1,1,JJ),NDMXU1,                &
     &    NDMXU2,NDMXU3,                                                &
     &    NEQNU,N3,IPTFMG(1,JSAT),ILNFMG(1,JSAT),NFMG(JSAT),            &
     &    PXEPA,NDIM1,NDIM2,LNPNM,.FALSE.,.FALSE.,1.D0,LL(KLAVOI))

         IF(LNPNM) THEN

         DO 600 J=1,NM
         DO 500 K=1,NADJST
         IF(LL(KLAVOI-1+K)) GO TO 500
         DUMPMP = PMPA(K,J)
         PMPA(K,J)=PMPA(K,J)+ PXEPA(K,J)

  500    CONTINUE
  600    CONTINUE

         ELSE

         DO 800 J=1,NM
         DO 700 K=1,NADJST
         IF(LL(KLAVOI-1+K)) GO TO 700
         PMPA(J,K)=PMPA(J,K)+ PXEPA(J,K)


  700    CONTINUE
  800    CONTINUE

         ENDIF

 900  CONTINUE
 ! FO&CE MODEL PARTIALS COMPUTED; COMPUTE ATTITUDE PARTIALS

         IF(IP0AT1.GT.0) THEN
          PRPY(1)=X2VPA(1,1,1,JJ)
          PRPY(2)=X2VPA(1,1,2,JJ)
          PRPY(3)=X2VPA(1,1,3,JJ)

           CALL CHNAT2(PRPY,PMPA,1,NDIM1,NDIM2,LNPNM,                  &
     &           TIME1,PER,LL(KLAVOI),IP0AT1)

         ENDIF


       IF(IP0AT2.GT.0) THEN

          PRPY(1)=X2VPA(1,1,1,JJ)
          PRPY(2)=X2VPA(1,1,2,JJ)
          PRPY(3)=X2VPA(1,1,3,JJ)

           CALL CHNAT2(PRPY,PMPA,1,NDIM1,NDIM2,LNPNM,                  &
     &           TIME1,PER,LL(KLAVOI),IP0AT2)

       ENDIF

! FINALLY GET PLANOR
!
       IF(LPLN) THEN
         TQ=DBLE(MJDS(1)) +FSECOT(1)
         IF(JJ.EQ.2) TQ=DBLE(MJDS(2))  +FSECOT(2)
         CALL CHPOR(PPOR(1,JJ),PMPA,1,NDIM1,NDIM2,LNPNM,               &
     &              TQ,LL(KLAVOI),AA(KANGWT),AA(KWT),AA(KPPER))

       ENDIF

       ENDDO   ! FOR THE TWO POINTS (JJ)  IN THE PAIR (ABOVE)

      IF(NPVAL0(IXCAME).EQ.5) THEN
        DO I=1,5
         LL(KLAVOI+IPVAL0(IXCAME)-2+I)=.FALSE.
        ENDDO
      ENDIF

!***********************************************************************
! DONE WITH PARTIALS
!***********************************************************************
! DEP COMMENT MOVE HERE THE ATTITUDE PARTIAL CHAINING
!  AND ADD PLANOR CHAINING AS WELL. MAKE SURE ALL THE LAVOID IS OFF
!  FOR THE ADJUSTED PARAMETERS

      DO  N=1,NM
      LEDIT (N)=(OBSSIG(N).LE.0.D0)
      ENDDO
      RESID(1)=-DIST

      SIGMA(1)=1.D0/(OBSSIG(1)*OBSSIG(1))
      LBEDIT=.FALSE.
      LSCALE=.FALSE.
      LNEDIT=.TRUE.

! CONTRIBUTE TO THE TOTAL PARTIAL DERIVATIVE MATR
!  ACCUMULATE PARTIALS & RESIDUALS INTO THE
!  NORMAL MATRIX AND RIGHT HAND SIDE OF THE NORMAL EQ.

      CALL SUMNPF(PMPA,RESID,SIGMA,NADJST,MAPARM,1,                 &
     &            AA(KSUM1),AA(KSUM2),AA(KPDLTA),LL(KLAVOI))
      RESIDU(1)=RESID(1)
      RATIO(1)=RESID(1)/EDTSIG(1)
!
! PRINT RESIDUAL HEADERS
      INDSYS=MOD(ITSYS,10000)/100
      INDSYS=MIN(MAX(INDSYS+1,1),3)

! OUTPUT UTC CALENDAR TIMES
!
      SIGMA(1)=RESID(1)/OBSSIG(1)
      KNTOBS=KNTOBS+1
      KNTBLK=KNTBLK+1
      CALL YMDHMS(MJDSP,OBSTIM,IYMD,IHM,SEC,NM)
      IF(IYMD.GT.1000000)IYMD=IYMD-1000000

      IPAGE6=IPAGE6+1
          WRITE(6,10001,IOSTAT=IERR) NARC,NINNER,NGLOBL,IPAGE6,DTYPE(1),&
     &    BLKNEW,(NUM(I),I=1,3),                                        &
     &    TIMSYS(INDSYS)

10001 FORMAT('1',15X,'OBSERVATION RESIDUALS FOR ARC',                   &
     &   I3,' FOR INNER ITERATION',I3,' OF GLOBAL ITERATION',I2,17X,    &
     &   'UNIT  6 PAGE NO.',I6/                                         &
     &   2X,'STATION-SATELLITE CONFIGURATION ',2X,A8,12X,               &
     &   A7/23X,'STATION NUMBERS -',I8,12X,I8,12X,I8,                   &
     &   /2X,'DATE  GREENWICH TIME',6X,'OBSERVATION',9X,                &
     &   'RESIDUAL',2X,'RATIO TO SIGMA',4X, ' SIGMA ', 4X,              &
     &   'OBS NO.',2X,'BLOCK'/1X,'YYMMDD HHMM SEC-UTC-',A1)

          WRITE(6,10400,IOSTAT=IERR)                                    &
     &                IYMD,IHM,SEC,OBS1,RESID(1),                       &
     &                RATIO(1),SIGMA(1), KNTOBS,KNTBLK
10400 FORMAT(1X,I6,I5,F10.6,A8,F15.6,F12.4,1X,F12.4, 6X,                &
     &       I9,I8)


      NM=1
      NMWTD=1
!***********************************************************************
! SUM OBSERVATION AND RESIDUAL STATISTICS
!
      SIGMA(1)=RESID(1)/SQRT(OBSSIG(1))
      CALL SMSTAT  (AA(KTMEAN),AA(KTRMS ),AA(KWMEAN),AA(KWTRMS),        &
     &   AA(KWTRND),AA(KPRVRT),AA(KTYMEA),AA(KTYRMS),AA(KWTMTY),        &
     &   AA(KWTYRM),II(KNOBST),II(KNOBWT),II(KNOBTY),II(KNOBWY),        &
     &   LL(KLGPRV),RESIDU    ,NM        ,SIGMA     ,RATIO     ,        &
     &   NMWTD     ,NTYPE     ,ISTATS    )

      ELEVSC(1)=0.D0
      IF(LBINRI) CALL BINLEN(AA,II)
      IF(LLOCRI) THEN
      CALL CONHD
        WRITE(IUNT19)    ZERO,ZERO,ZERO,                                &
     &                   XBOUNCE(1),XBOUNCE(2),XBOUNCE(3),              &
     &                   ZERO,ZERO,ZERO
        WRITE(IUNT19)    OBSTIM,                                        &
     &                   XSM(1,1),XSM(1,2),XSM(1,3),                    &
     &                   VSM(1,1),VSM(1,2),VSM(1,3)
      ENDIF
      IF(LBINRI) CALL BINRDR(AA,II,MJDSP,OBSTIM,EDTSIG,RESID,          &
     &           AA(KTPRTL),AA(KTHG),ELEVSC,NELEVS,LEDIT,RESIDU,NM,     &
     &           AA(KXUTDT))
      IF(LODRI) THEN
         CALL BOD(AA,II,NM)
      ENDIF

!***********************************************************************
      KIMBST=KIMBST+1
      LIMCALL=.FALSE.
      LIMAT  =.FALSE.
      LIMCAM =.FALSE.


      RETURN
!
      END
