

!$IMAGE
      SUBROUTINE IMAGE(AA  ,II  ,LL  ,INDSAT,INDSET, RESID ,SIGMA ,     &
     &    RATIO ,PMPA  ,OBS   ,OBSSIG, RESIDU,ISTATS,                   &
     &    NTYPE ,RIMTIM, RIMOBS,RINDEX,                                 &
     &    XSCR,NOBSBL,XSM,XBF,XBF2,XSMTOD,VSM,OFF,VSMTOD,VL1PBF,VL2PBF, &
     &    SIMXSM,X2PART,                                                &
     &    NEQN ,PXPF  ,                                                 &
     &    NDIMX1,NDIMX2,NDIMX3,    N3, ILATP, ISAT,  ISET ,             &
     &    R1,X2AUX, RMVPRT, ATPER, LEDIT,EDTSIG,THETAG,COSTHG,SINTHG,   &
     &    XTRA,WORK,HOLD,ATROT,IPTFMG,ILNFMG,NFMG,PXEPA,OBSTIM)
!********1*********2*********3*********4*********5*********6*********7**
! PROCX            00/00/00            0000.0    PGMR -DESPINA PAVLIS
!
!
! FUNCTION: PROCESS DYNAMIC CROSSOVERS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A     REAL DYNAMIC ARRAY
!   II      I/O   A     INTEGER DYNAMIC ARRAY
!   LL      I/O   A     LOGICAL DYNAMIC ARRAY
!   RESID    O    A     RESIDUAL VECTOR
!   SIGMA    O    A     RESIDUAL/OBS SIGMA
!   RATIO    O    A     RATIO TO SIGMA
!   PMPA    I/O   A     PARTIALS MATRIX THETAOBS/THETA PARAMETERS
!   OBS      I    A     INPUT OBSERVATION ARRAY. IN THE CASE OF IMAGES
!                       THE OBS ARRAY CONTAINS ZEROES
!   OBSSIG   I    A     OBSERVATION SIGMA
!   RESIDU
!   ISTATS
!   NTYPE
!   RIMTIM  I/O A  IMAGE TIME ARRAY
!   RIMOBS  I/O A  IMAGE OBSERVATION ARRAY
!   RINDEX  I/O A  AUXILIARY INDEX ARRAY FOR PAIRED BLOCKS IDENTIFICATIO
!   XSCR    I/O A  SCRATCH ARRAY FOR BLOCL INFORMATION MANIPULATION
!   NOBSBL  I/O A  ARRAY KEEPING THE NUMBER OF OBSERVATIONS PER BLOCK
!   XSM     O   A  TOR  COORDINATES OF THE S/C
!   XBF     O   A  PLANET FIXED COORDINATES OF THE S/C AT  P1
!   XBF2    O   A  PLANET FIXED COORDINATES OF THE S/C AT  P2
!   SIMXSM  I/O A  AUXILIARY ARRAY FOR LOCATING PAIRED SATELLITE COORDINATES
!   NEQN    I   A  NUMBER OF FORCE MODEL PARAMETERS
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!

      COMMON/ATTCBD/BATPER,ATTPRT
      COMMON/LIMAGE/LIMG,LIMCALL,LIMAT,LIMCAM
      COMMON/SAVEIM/RIM(3,3),SBF1(3,3),SBF2(3,3),SBF3(3,3),SBF4(3,3),   &
     &       SCF2(3,3),SCF3(3,3),SCF4(3,3),RKEY
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/CAMCCD/CKXMAT(30,6),CAMCTR(30,2),XKXCCD
      COMMON/CAMSAT/NCAM,NSCID(30),NXSCID
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CBLOKV/QUANO(3),EHAT(3),DEDA(3),DEDD(3),EFLG
      COMMON/CEDIT /EDITX ,EDTRMS,EDLEVL,CONVRG,GLBCNV,EBLEVL,EDITSW,   &
     &              ENPX  ,ENPRMS,ENPCNV,EDBOUN,FREEZI,FREEZG,FREEZA,   &
     &              XCEDIT
      COMMON/CEDITL/LNEDIT
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CKOUNT/KNTBLK,KSEGMN,KNTOBS,KZROBS
      COMMON/CLPRNR/LPR9NR(24),LPRNRM(24,3)
      COMMON/CNELVS/KNELEV(999)
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CNORML/LNORM ,LNORMP
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/COBSI /MODRES,NXCOBS
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI05/KNOBGL,KNOBWG,KNOBTY,KNOBWY,KNOBST,KNOBWT,KNEBOB,   &
     &              KJSTAT,NXCI05
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL03/KLVELA,KLSTL2,KLSTH2,NXCL03
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CORL05/KLGPRV,NXCL05
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CORL07/KLPTS,NXCL07
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/CRMI/RMI(9)
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
      COMMON/CSIML/LSIMTI
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/DPLNOR/DXGEO1,DXGEO2,DXFRC1,DXFRC2,XPLNOR
      COMMON/ELRTNX/NELVS,NELVC,IELSTA(6),IELSAT(6),IELSA2(6),          &
     &       INDXEL(5,4)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IMAG2E/KXIMG,KIMBST,KIMOBL,KIMBUP,KIMBPA
      COMMON/IMAG2S/NIMBLK,NIMTOT,NIMG2S
      COMMON/IOBTYP/NDXST(2,35),NDXSAT(2,35),                           &
     &      NDRSTA(50),NDRSAT(50),NDRST2(50),NDRSA2(50),                &
     &      ITMBIT(999),IOETR(999),MTYPED(11),NTYPES,                   &
     &      NM0112(4),NM1314(4),NM1522(4),NM2330(4),                    &
     &      NM3138(4),NM3997(4),NM4098(4),NM9900(4),NMT199(4),NMT203(4),&
     &      NS0112(4),NS1314(4),NS1522(4),NS2330(4),                    &
     &      NS3138(4),NS3997(4),NS4098(4),NS9900(4),NST199(4),NST203(4),&
     &      ITYPD(12,2),ITYPDD(7,2),ILINKF(5),ISTAFN(5,3),              &
     &      ISATFN(5,3),ILINKT(5),ISTATN(5,3),ISATTN(5,3),              &
     &      MGOTO(12),MENTER(12),MEXIT(12),                             &
     &      NDST60(3,24),NDST82(6,12),NDST92(12,7),NTDRSS,              &
     &      NDSA60(3,24),NDSA82(6,12),NDSA92(12,7),                     &
     &      MTDRSS(7),KTDRSS(7),ITDRSS(4,7),JTDRSS(4,7),                &
     &      NLLC60(5,24),NLLC82(10,12),NLLC98(20,7),NNBIA,              &
     &      NXMTYP
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
      COMMON/IRAMPS/INDRAM,KKRAMP
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/RIMAGE/VIMAGE(6),QUCAM(4),QURSYS,TLBOD2
      COMMON/ROBTYP/CONVRT(999),OBSCAL(999),RESCAL(999),                &
     &              XMTYP
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      COMMON/XOVER /KXKNT,KXBST,KXOBL,KXBUP,KXBPA,IAPLSC,IAPLL
      COMMON/XOVERR/XBTIME
      COMMON/XOVERS/NRXTOT,NXBLK,NUSIDE,NDEGX2,NDEGXX,NUCON,ITERNU,     &
     &              IPEDIT,IDEDIT,NXXOVR
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA

!...Begin TJS
      COMMON/AXIS/LINTAX
! NEW NAMED COMMON BLOCK "PORINF" (found also in EXPLOR and STARTD)
! introduce new named common block for planetary orientation information in
! order to get current omega and R states (PLOR(1:12)), current partials of
! omega and R with respect to omega_0 and R_0 (PLOR(13:156)), partials of
! omega and R with respect to six independent moments of inertia
! (PLOR(157:228)), and partials of omega_0 and R_0 with respect to RA_0,
! DEC_0, W_0, RA_t_0, DEC_t_0, and W_t_0 (DO0DA0)
      COMMON/PORINF/PLOR(228,2),DO0DA0(12,6,2)
!...End TJS

      DIMENSION AA(*),II(*),LL(*)
      DIMENSION FSECN(1)
      DIMENSION IPTFMG(MAXFMG,MSATA),ILNFMG(MAXFMG,MSATA),NFMG(MSATA)
      DIMENSION PXEPA(NDIM1,NDIM2)
      DIMENSION ATROT(3,3,MINTIM),SBFTOR(3,3)
      DIMENSION ATPER(1),LEDIT(1)
      DIMENSION INDSAT(3),INDSET(3)
      DIMENSION RESID (NM),SIGMA (NM),RATIO (NM),                       &
     &          PMPA(NDIM1,NDIM2),OBS   (NM),                           &
     &          OBSSIG(NM),EDTSIG(NM)
      DIMENSION RESIDU(NM)
      DIMENSION RIMTIM(1),RINDEX(NIMBLK,3),XSCR(20,1),                  &
     &          NOBSBL(NIMBLK,5) ,RIMOBS(28,3,NIMTOT)
      DIMENSION ELEVSC(1)
      DIMENSION XSM(MINTIM,3),XBF(MINTIM,3) ,XBF2(MINTIM,3)
      DIMENSION VL1PBF(MINTIM,3),VL2PBF(MINTIM,3)
      DIMENSION XSMTOD(MINTIM,3),VSM(MINTIM,3),VSMTOD(MINTIM,3)
      DIMENSION SIMXSM(6,NIMTOT)
      DIMENSION CC(3)
      DIMENSION V1(3),V2(3),ENHAT(3)
      DIMENSION ENHBR(3),ENHBP(3),ENHBY(3)
      DIMENSION V1TDX(3),V1TDY(3),V1TDZ(3)
      DIMENSION V2TDX(3),V2TDY(3),V2TDZ(3)
      DIMENSION V1TOD(3),V2TOD(3)
      DIMENSION V1RTOD(3),V2RTOD(3)
      DIMENSION V1PTOD(3),V2PTOD(3)
      DIMENSION V1YTOD(3),V2YTOD(3)
      DIMENSION V1RPBF(3),V2RPBF(3)
      DIMENSION V1PPBF(3),V2PPBF(3)
      DIMENSION V1YPBF(3),V2YPBF(3)
      DIMENSION V1PBF(3),V2PBF(3)
      DIMENSION V1PBFN(3),V2PBFN(3)
!  INTERSECTION POINT
      DIMENSION XBOUNCE(3),DP(3)
      DIMENSION V1X1P(3),V1Y1P(3),V1Z1P(3)
      DIMENSION V2X2P(3),V2Y2P(3),V2Z2P(3)
!
      DIMENSION V1PBRA(3),V1PBDC(3),V1PBGA(3)
      DIMENSION V2PBRA(3),V2PBDC(3),V2PBGA(3)
      DIMENSION XBF1RA(3),XBF1DC(3),XBF1GA(3)
      DIMENSION XBF2RA(3),XBF2DC(3),XBF2GA(3)
      DIMENSION XSMTRA(3),XSMTDC(3)
      DIMENSION PBFGA(3,3)
      DIMENSION SBF1RA(3,3),SBF1DC(3,3)
      DIMENSION VTMP(3),VVTMP(3)
      DIMENSION PPOR(3,2)
      DIMENSION ENHPOR(3)
!
      DIMENSION PART(3)
      DIMENSION THETAG(NM),COSTHG(NM),SINTHG(NM)
      DIMENSION DXPDXI(3,3,2)
      DIMENSION PXEXI(3,3)
      DIMENSION SBFPBF(3,3,2)
      DIMENSION OFF(MINTIM,3)
      DIMENSION X2VPA(1,3,20,2)
      DIMENSION XTD(1,3),XTPBF(1,3)
      DIMENSION XMP(1,3),XTP(1,3)
! X2VPA will save the partials for both points in a pair
      DIMENSION TOTRIM(3,3,200000)
      DIMENSION TODPBF(3,3,200000)
      DIMENSION PXEPXI(3,3,200000)
      DIMENSION NEQP(200000)
      DIMENSION PBF(3,3)
! TOTRIM ID THE ARRAY HOLDING THE TOTAL ROTATION TOD TO CAMERA IN TIME
      DIMENSION PXPF(NDIMX1,NDIMX2,NDIMX3,2)
      DIMENSION RMVPRT(NDIMX1,NDIMX2,NDIMX3,2,2)
      DIMENSION X2PART(NEQNG,N3,2,1)
      DIMENSION ILATP(NIMBLK,2)
      DIMENSION GINDEX(1)
      DIMENSION XTRA(MINTIM,33),WORK(MINTIM),HOLD(MINTIM,30)
      DIMENSION DTYPE(1)
      DIMENSION TIMSYS(3),NUM(3)
      DIMENSION ONE(3,3),TWO(3,3),THREE(3,3)
      DIMENSION DUM(3),DUM1(3,2,1)
      DIMENSION XKMAT(6),CTR(2)
      DIMENSION DISTRH(4)
      DIMENSION DELCP(5)
      DIMENSION DISTP(5)
      DIMENSION PMPI(3)
      DIMENSION PRPY(3)
      DIMENSION PXV(3)
      DIMENSION VIMGH(3)
      DIMENSION TRKTOR(3)
      DIMENSION OBSTIM(NM)
      CHARACTER*8      DTYPE,OBS1
      CHARACTER*8      BLKNEW, BLKOLD
      CHARACTER(1) ::  BLANK, EDTFLG   ! jjm 20150224
!... Begin TJS...
      DIMENSION XR(NDPOR),DADA0(3,6,2),DADIC(3,6,2)
!... End TJS...

      DATA DTYPE/'IMAGE   '/
      DATA ZERO/0.D0/
      DATA KENTRY/0/
      DATA OBS1/'        '/
      DATA BLANK/' ' /,EDTFLG/'*'/,BLKNEW/'(*NEW*)'/,BLKOLD/'(CONT.)'/
      CHARACTER*1 TIMSYS
      DATA TIMSYS/'R','X','T'/
      DATA NUM/3*0/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEMP CAMERA !!!!!!!!!!!!!!!!!!!!!!!
!      DATA CTR/512.5,512.5/
!      DATA XKMAT/71.42860D0,0.00386,0.00000D0,0.00386,               &
!     &          -71.44341D0,0.00000D0/
      DATA CTR/0.0D0,0.0D0/
      DATA XKMAT/0.0D0,0.0D0,0.0D0,0.0D0,0.0D0,0.0D0/
      DATA DELCP/1.D0,4*0.1D-07/
      DATA ISTART/0/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TEMP CAMERA !!!!!!!!!!!!!!!!!!!!!!!
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!**********************************************************************
! INITIALIZATIONS
!**********************************************************************
! LOAD THE CAMERA PARAMETERS FOR THIS RUN
      IF(ISTART.EQ.0) THEN

      ISTART=1
      ENDIF

      LPLN=LSTINR.AND.NPVAL0(IXXTRO).GT.0
      DO I=1,3
        V2PBRA(I)=0.D0
        V2PBDC(I)=0.D0
        V2PBGA(I)=0.D0
        XBF2RA(I)=0.D0
        XBF2DC(I)=0.D0
        XBF2GA(I)=0.D0
      ENDDO
      kentry=kentry+1
!
!     INITIALIZE FLAGS FOR ATTITUDE PARTIALS
!  LIMCALL TRUE IF ORBIT IS CALLED FROM IMAGE
      LIMCALL=.FALSE.
!  LIMAT TRUE IF S/C ORIENTAION IS ADJUSTED
      LIMAT  =.FALSE.
!  LIMAT TRUE IF CAMERA  ORIENTAION IS ADJUSTED
! THE CODE HAS ALREADY BEEN IN GETRPY AND HAS COMPUTED
! IAPLSC = # OF S/C WITH ATTITUDE PARAMETERS
! IAPLL  = # OF LASERS BUT IN THE CASE OF IMAGES CAMERAS
      LIMCAM =.FALSE.
      IF(IAPLSC.GT.0) LIMAT =.TRUE.
      IF(IAPLL .GT.0) LIMCAM=.TRUE.


!  INITIALIZE MORE FLAGS NEEDED FOR KEEPING TRACK OF PAIRS
      IRET2=0
!
! KIMBUP= LOCATION OF BLOCK BEGIN IN THE ENTIRE STREAM OF DATA
! KIMBPA= SEQUENTIAL NUMBER OF BLOCK IN THE ENTIRE STREAM OF BLOCKS
      ISAVE=KIMBUP
      ISAVE2=KIMBPA
! POINTER TO  KEY  ARRAY FOR THIS  BLOCK
      JDIMN=KIMBST+NM-1
! INITIALIZE LFNDX=.TRUE. MEANS SECOND BLOCK FOUND
      LFNDX=.FALSE.
! INITIALIZE LODD=.TRUE. MEANS THE PRESENT BLOCK KEY IS ODD
      LODD=.FALSE.
!
!**********************************************************************
! IDENTIFY THE BLOCK IMAGE KEY
!**********************************************************************
!
! LOCATE THE KEY IN THE II(KIMKEY) ARRAY LOADED IN OBSRD
! THIS ARRAY IS 2* # OF BLOCKS AND IS FILLED AS NEW BLOCKS
! ARE READ.
!
! KIMBST IS THE LOCATION OF THE CURRENT BLOCK IN THE TOTAL STREAM
! OF BLOCKS
!
      KINDX=KIMKEY+KIMBST-1
      KEY=II(KINDX)
      RKEY=DBLE(KEY)

! CHECK IF THE KEY IS EVEN OR ODD
      CALL ODD(KEY,LODD)
! THE CODE BELOW FOR >>>> EVEN <<<< KEYS
! LOOP 1 PROCESS EVEN OR ODD
!
!**********************************************************************
! THE BLOCK KEY HAS BEEN IDENTIFIED
!**********************************************************************
!
        IF(LODD) THEN
! FIND THE EVEN KEY IN THE PAIR
        MKEY=KEY+1
        ELSE
! FIND THE ODD KEY IN THE PAIR
        MKEY=KEY-1
        ENDIF
!
!**********************************************************************
! THE FIRST KEY HAS BEEN IDENTIFIED
! HAS THE PAIRING KEY BEEN FOUND ALREADY?
!**********************************************************************
!
        CALL FNDNUM(MKEY,II(KIMKEY),JDIMN,IRET)
!
! IRET=0 NO IT HAS NOT BEEN FOUND
! IRET.NE.0 IT HAS BEEN FOUND IN LOCATION IRET IN THE FULL KEY ARRAY
!     if(iret.eq.0) then
!     write(6,*)' dbg we DO NOT HAVE a pair at ',KIMBST,MKEY
!     else
!     write(6,*)' dbg we DO HAVE a pair at ',KIMBST,MKEY-1,MKEY
!     endif
!
!**********************************************************************
! CALL ORBIT
!**********************************************************************
!
      ISATID=II(KISATN+INDSAT(1)-1)
      IRET1=1
      IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET1)
      IF(IRET1.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET1)
      NEQNI=II(KNEQNI-1+IRET1)
      ENDIF
      ENDIF
!
      FSECN(1)=AA(KFSECS(1,1))
! OBTAIN SATELLITE POSITIONS AT CORRECT SATELLITE TIMES
      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),INDSAT(1),            &
     &   KNSTEPS,NEQN,II(KSGMNT-1+IRET1),                              &
     &   AA(KSGTM1-1+IRET1),AA(KSGTM2-1+IRET1),IRET1,MJDSBL,FSECN,      &
     &   FSECN,1,AA,II)

      LIMCALL=.TRUE.

!     INTEGRATE TO OBS TIME.

      CALL ORBIT(MJDSBL,FSECN,AA(KS),1,II(KINDH),II(KNMH),II(KMJDSC),   &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM,PXPF,                    &
     &   LNADJ,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),                &
     &   AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQN,II(KSGMNT-1+IRET1),         &
     &   AA(KSGTM1-1+IRET1),AA(KSGTM2-1+IRET1),AA,II,LL)

!...Begin TJS
      IF (LINTAX) THEN
         DO J=1,NDPOR
            XR(J) = AA(KDPOR + (J-1)*MINTIM) ! AATJS(1,J)
         END DO
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!  FOR NOW DO0DA0 SET FOR FIRST ASTEROID
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         CALL GETDADA0 (XR(4),XR(13),DO0DA0,DADA0(1,1,2))
         CALL GETDADIC (XR(4),XR(157),DADIC(1,1,2))
      END IF
!...End TJS


      CALL DXEDXI(AA,II,LL,MJDSBL,FSECN,NM,XTD,XTP,XMP,PXEXI)
!     write(6,*)' dbg PXEXI ',PXEXI(1,1),PXEXI(1,2),PXEXI(1,3)
!     write(6,*)' dbg PXEXI ',PXEXI(2,1),PXEXI(2,2),PXEXI(2,3)
!     write(6,*)' dbg PXEXI ',PXEXI(3,1),PXEXI(3,2),PXEXI(3,3)

! GET RIM(3,3) OF CB SAVEIM = SBFTOD ROTATION MATRIX AT THIS TIME OF OBS.

      JTERP=0
      CALL ALTPTI(AA,II,LL,NM,MJDSBL,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &           XTRA(1,7),XSM,VSM,JTERP,ATROT,HOLD,2,FRQLNK,MTYPE, &
     &           SBFTOR,1)

      TRKTOR(1)=XTRA(1,4)
      TRKTOR(2)=XTRA(1,5)
      TRKTOR(3)=XTRA(1,6)

! SAVE  SBFTOR AT TIME T (INCLUDING EXTATT AND ROLL PITCH YAW)
      DO I=1,NM
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF1(1,1),AA,1,1,.TRUE.,  &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF1(1,2),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF1(1,3),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      ENDDO
      IF(LPLN) THEN
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF1RA(1,1),AA,1,1,.TRUE.,&
     &           .FALSE.,II,1,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF1RA(1,2),AA,1,1,.FALSE.,&
     &           .FALSE.,II,1,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF1RA(1,3),AA,1,1,.FALSE.,&
     &           .FALSE.,II,1,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF1DC(1,1),AA,1,1,.TRUE.,&
     &           .FALSE.,II,2,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF1DC(1,2),AA,1,1,.FALSE.,&
     &           .FALSE.,II,2,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF1DC(1,3),AA,1,1,.FALSE.,&
     &           .FALSE.,II,2,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),VVTMP,AA,1,1,.TRUE.,&
     &           .FALSE.,II,0,1)
      ENDIF
      DO JJ=1,3
      DO KK=1,3
!     SBFTOD BELOW
      RIM(JJ,KK)=SBF1(JJ,KK)
      ENDDO
!     write(6,*)' dbg SBFTOR I ',SBFTOR(JJ,1),SBFTOR(JJ,2),SBFTOR(JJ,3)
      ENDDO


!***************************************************************************
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!  IDENTIFY CAMERA LOCATION

      VIMGH(1)=VIMAGE(1)
      VIMGH(2)=VIMAGE(2)
      VIMGH(3)=VIMAGE(3)
      PXV(1)=VIMAGE(1)
      PXV(2)=VIMAGE(2)
      CAMID=VIMAGE(3)
!     CAMID=7777.0

      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET3)

      IF (IRET3.EQ.0.0D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' CAMERA ID NOT FOUND, CHECK UNIT 5 SETUP'
      WRITE(6,*)' FOR CAMERA', IDCAM
      STOP
      END IF

!     FLMMH=AA(KPRMV+IPVAL(IXCAME)-1)
      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET3-1)*5)
      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET3-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET3-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET3-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values ',FLMMH,DISTRH(2)
!!!!  IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      IF(FLMMH.EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF
!
! load ccd information (if given on CAMERA card)

      IF (IRET3.NE.0) THEN
        DO J=1,6
          XKMAT(J)=CKXMAT(IRET3,J)
        END DO
        DO J=1,2
          CTR(J)=CAMCTR(IRET3,J)
        END DO
      END IF

      CALL GETVEC(PXV,XKMAT,DISTRH,FLMMH,CTR,VIMAGE)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!     GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF ATTITUDE PARTIALS
      IF(LIMAT) THEN
      INDAT=10

!  PERTURB ROLL (1), PITCH (2), YAW (3)
      DO 30401 K=1,3
      INDAT=INDAT+1
      CALL ALTPTI(AA,II,LL,NM,MJDSBL,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &        XTRA(1,7),XSM,VSM,INDAT,ATROT,HOLD,2,FRQLNK,MTYPE,    &
     &        SBFTOR,1)

      GOTO (303,304,305),K

303   CONTINUE
      DO I=1,NM
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF2(1,1),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF2(1,2),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF2(1,3),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      V1RTOD(1)=SBF2(1,1)*VIMAGE(1)+SBF2(1,2)*VIMAGE(2)+             &
     &          SBF2(1,3)*VIMAGE(3)
      V1RTOD(2)=SBF2(2,1)*VIMAGE(1)+SBF2(2,2)*VIMAGE(2)+             &
     &          SBF2(2,3)*VIMAGE(3)
      V1RTOD(3)=SBF2(3,1)*VIMAGE(1)+SBF2(3,2)*VIMAGE(2)+             &
     &          SBF2(3,3)*VIMAGE(3)
      ENDDO


! SBF2 SBFTOD WITH ROLL PERTURBED
      GOTO  30401

304   CONTINUE
      DO I=1,NM

      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF3(1,1),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF3(1,2),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF3(1,3),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)

      V1PTOD(1)=SBF3(1,1)*VIMAGE(1)+SBF3(1,2)*VIMAGE(2)+             &
     &          SBF3(1,3)*VIMAGE(3)
      V1PTOD(2)=SBF3(2,1)*VIMAGE(1)+SBF3(2,2)*VIMAGE(2)+             &
     &          SBF3(2,3)*VIMAGE(3)
      V1PTOD(3)=SBF3(3,1)*VIMAGE(1)+SBF3(3,2)*VIMAGE(2)+             &
     &          SBF3(3,3)*VIMAGE(3)
      ENDDO

! SBF3 SBFTOD WITH PITCH PERTURBED
      GOTO  30401

305   CONTINUE
      DO I=1,NM
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,1),SBF4(1,1),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,2),SBF4(1,2),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,SBFTOR(1,3),SBF4(1,3),AA,1,1,.FALSE., &
     &           .FALSE.,II,0,1)


      V1YTOD(1)=SBF4(1,1)*VIMAGE(1)+SBF4(1,2)*VIMAGE(2)+             &
     &          SBF4(1,3)*VIMAGE(3)
      V1YTOD(2)=SBF4(2,1)*VIMAGE(1)+SBF4(2,2)*VIMAGE(2)+             &
     &          SBF4(2,3)*VIMAGE(3)
      V1YTOD(3)=SBF4(3,1)*VIMAGE(1)+SBF4(3,2)*VIMAGE(2)+             &
     &          SBF4(3,3)*VIMAGE(3)
      ENDDO

! SBF4 SBFTOD WITH YAW PERTURBED


30401 CONTINUE
      ENDIF

!***************************************************************************

! CLEAR UP THE ARTOT ARRAY TO USE IT FOR THE CAMERA ROTATIONS

      DO  901 IJ1=1,3
      DO  901 IJ2=1,3
      DO  901 K=1,NM
      ATROT(IJ1,IJ2,K)=0.D0
  901 CONTINUE
      DO IJ1=1,3
      DO K=1,NM
      ATROT(IJ1,IJ1,K)=1.D0
      ENDDO
      ENDDO

!***************************************************************************
!     GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF CAM ATT PARTIALS

      IF(LIMCAM)  THEN
      INDAT=13

      DO 30402 K=1,3
      INDAT=INDAT+1

      CALL ALTPTI(AA,II,LL,NM,MJDSBL,FSECN,ISAT,ISET,OFF,XTRA(1,4), &
     &     XTRA(1,7),XSM,VSM,INDAT,ATROT,HOLD,2,FRQLNK,MTYPE,SBFTOR,1)

      GOTO ( 306,307,308),K
306   CONTINUE
      DO I=1,NM
      SCF2(1,1)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+                 &
     &        SBFTOR(3,1)*RMI(7)
      SCF2(2,1)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+                 &
     &        SBFTOR(3,1)*RMI(8)
      SCF2(3,1)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+                 &
     &        SBFTOR(3,1)*RMI(9)
      SCF2(1,2)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+                 &
     &        SBFTOR(3,2)*RMI(7)
      SCF2(2,2)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+                 &
     &        SBFTOR(3,2)*RMI(8)
      SCF2(3,2)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+                 &
     &        SBFTOR(3,2)*RMI(9)
      SCF2(1,3)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+                 &
     &        SBFTOR(3,3)*RMI(7)
      SCF2(2,3)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+                 &
     &        SBFTOR(3,3)*RMI(8)
      SCF2(3,3)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+                 &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO
!     DO KK=1,3
!     write(6,*)' dbgSCF2 ',SCF2(KK,1),SCF2(KK,2),SCF2(KK,3),K
!     ENDDO
GOTO  30402
307   CONTINUE
      DO I=1,NM
      SCF3(1,1)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+                 &
     &        SBFTOR(3,1)*RMI(7)
      SCF3(2,1)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+                 &
     &        SBFTOR(3,1)*RMI(8)
      SCF3(3,1)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+                 &
     &        SBFTOR(3,1)*RMI(9)
      SCF3(1,2)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+                 &
     &        SBFTOR(3,2)*RMI(7)
      SCF3(2,2)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+                 &
     &        SBFTOR(3,2)*RMI(8)
      SCF3(3,2)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+                 &
     &        SBFTOR(3,2)*RMI(9)
      SCF3(1,3)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+                 &
     &        SBFTOR(3,3)*RMI(7)
      SCF3(2,3)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+                 &
     &        SBFTOR(3,3)*RMI(8)
      SCF3(3,3)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+                 &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO
!     DO KK=1,3
!     write(6,*)' dbgSCF3 ',SCF3(KK,1),SCF3(KK,2),SCF3(KK,3),K
!     ENDDO
GOTO  30402

308   CONTINUE
      DO I=1,NM
      SCF4(1,1)=SBFTOR(1,1)*RMI(1)+SBFTOR(2,1)*RMI(4)+                 &
     &        SBFTOR(3,1)*RMI(7)
      SCF4(2,1)=SBFTOR(1,1)*RMI(2)+SBFTOR(2,1)*RMI(5)+                 &
     &        SBFTOR(3,1)*RMI(8)
      SCF4(3,1)=SBFTOR(1,1)*RMI(3)+SBFTOR(2,1)*RMI(6)+                 &
     &        SBFTOR(3,1)*RMI(9)
      SCF4(1,2)=SBFTOR(1,2)*RMI(1)+SBFTOR(2,2)*RMI(4)+                 &
     &        SBFTOR(3,2)*RMI(7)
      SCF4(2,2)=SBFTOR(1,2)*RMI(2)+SBFTOR(2,2)*RMI(5)+                 &
     &        SBFTOR(3,2)*RMI(8)
      SCF4(3,2)=SBFTOR(1,2)*RMI(3)+SBFTOR(2,2)*RMI(6)+                 &
     &        SBFTOR(3,2)*RMI(9)
      SCF4(1,3)=SBFTOR(1,3)*RMI(1)+SBFTOR(2,3)*RMI(4)+                 &
     &        SBFTOR(3,3)*RMI(7)
      SCF4(2,3)=SBFTOR(1,3)*RMI(2)+SBFTOR(2,3)*RMI(5)+                 &
     &        SBFTOR(3,3)*RMI(8)
      SCF4(3,3)=SBFTOR(1,3)*RMI(3)+SBFTOR(2,3)*RMI(6)+                 &
     &        SBFTOR(3,3)*RMI(9)
      ENDDO
!     DO KK=1,3
!     write(6,*)' dbgSCF4 ',SCF4(KK,1),SCF4(KK,2),SCF4(KK,3),K
!     ENDDO

30402 CONTINUE

      ENDIF
!
! END GET THE MATRICES WE NEED FOR NUMERICAL EVALUATION OF ATTITUDE PARTIALS
!
!***************************************************************************


!**********************************************************************
!         write(6,22222)XSM(1,1),XSM(1,2),XSM(1,3)
!22222 format(1x,3F20.6)
!**********************************************************************


!     CONVERT XSM FROM INERTIAL TOR TO INERTIAL TOD
!     XSM SATELLITE COORDINATES
!     FIRST ADD IN TOR TRACKING PT OFFSET
      XSM(1,1)=XSM(1,1)+TRKTOR(1)
      XSM(1,2)=XSM(1,2)+TRKTOR(2)
      XSM(1,3)=XSM(1,3)+TRKTOR(3)

      CALL SATUPD(MJDSBL,FSECN,XSM,XSMTOD,AA,1,MINTIM,.TRUE.,          &
     &           .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,VSM,VSMTOD,AA,1,MINTIM,.FALSE.,         &
     &           .FALSE.,II,0,1)

! COMPUTE THE PRIME MERIDIAN ANGLE

      IF(ICBDGM.EQ.3) THEN
      CALL GRHRAN(MJDSBL,FSECN,.FALSE.,.FALSE.,AA(KEQN),AA(KSRTCH),  &
     &  THETAG,COSTHG,SINTHG,NM,AA,II,AA(KXUTDT),.FALSE.,DUM,DUM1)


      ELSE

!...Begin TJS
         IF (LINTAX) THEN
            CALL GETWCS (NM,AA(KDPOR),COSTHG,SINTHG,1)
         ELSE
!...End TJS

      CALL ROTXTR(MJDSBL,FSECN,.FALSE.,AA(KEQN),AA(KSRTCH),          &
     &   AA(KTHETG),COSTHG,SINTHG,NM,AA,AA(KACOSW),                  &
     &   AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),AA(KBCOFW),II,1)

!...Begin TJS
         END IF
!...End TJS

      ENDIF
! DEBUG *************************************************************
!     cost=dsqrt(costhg(1)*costhg(1)+sinthg(1)*sinthg(1))
!     write(6,*)' dbg called rotxtr ',AA(KTHETG),cost
!     write(6,*)'DDP COSTHG SINTHG FOR PT WITH KEY',KEY
!     write(6,*)'DDP ',costhg(1),sinthg(1)
! DEBUG *************************************************************

! GET SINTHG AND COSTHG TO FORM THE TOD->PBF MATRIX  PBF(PLANET BODY FIXED)

      DO N=1,NM
      PBF(1,1)=COSTHG(N)
      PBF(1,2)=SINTHG(N)
      PBF(1,3)=0.D0
      PBF(2,1)=-SINTHG(N)
      PBF(2,2)=COSTHG(N)
      PBF(2,3)=0.D0
      PBF(3,1)=0.D0
      PBF(3,2)=0.D0
      PBF(3,3)=1.D0
      ENDDO
!!!!!!!!!!!!!!!!! START TO COMPUTE VECTORS FOR PLANETARY ORIENTATION VECTORS !!!
      IF(LPLN) THEN
      VTMP(1)=XSM(1,1)
      VTMP(2)=XSM(1,2)
      VTMP(3)=XSM(1,3)
      CALL SATUPD(MJDSBL,FSECN,VTMP,XSMTRA,AA,1,1,.TRUE.,          &
     &           .FALSE.,II,1,1)
      CALL SATUPD(MJDSBL,FSECN,VTMP,XSMTDC,AA,1,1,.TRUE.,          &
     &           .FALSE.,II,2,1)
      CALL SATUPD(MJDSBL,FSECN,VVTMP,VVTMP,AA,1,1,.TRUE.,         &
     &           .FALSE.,II,0,1)
      THG=ATAN2(SINTHG(1),COSTHG(1))
      THG=THG+DXGEO2*DEGRAD
      COSTG=COS(THG)
      SINTG=SIN(THG)
      PBFGA(1,1)=COSTG
      PBFGA(1,2)=SINTG
      PBFGA(1,3)=0.D0
      PBFGA(2,1)=-SINTG
      PBFGA(2,2)=COSTG
      PBFGA(2,3)=0.D0
      PBFGA(3,1)=0.D0
      PBFGA(3,2)=0.D0
      PBFGA(3,3)=1.D0
      XBF2RA(1)= XSMTRA(1)*PBF(1,1) + XSMTRA(2)*PBF(1,2)
      XBF2RA(2)= XSMTRA(1)*PBF(2,1) + XSMTRA(2)*PBF(2,2)
      XBF2RA(3)= XSMTRA(3)*PBF(3,3)
      XBF2DC(1)= XSMTDC(1)*PBF(1,1) + XSMTDC(2)*PBF(1,2)
      XBF2DC(2)= XSMTDC(1)*PBF(2,1) + XSMTDC(2)*PBF(2,2)
      XBF2DC(3)= XSMTDC(3)*PBF(3,3)
      XBF2GA(1)= XSMTOD(1,1)*PBFGA(1,1) + XSMTOD(1,2)*PBFGA(1,2)
      XBF2GA(2)= XSMTOD(1,1)*PBFGA(2,1) + XSMTOD(1,2)*PBFGA(2,2)
      XBF2GA(3)= XSMTOD(1,3)*PBFGA(3,3)
      VTMP(1)=SBF1RA(1,1)*VIMAGE(1)+SBF1RA(1,2)*VIMAGE(2)+             &
     &        SBF1RA(1,3)*VIMAGE(3)
      VTMP(2)=SBF1RA(2,1)*VIMAGE(1)+SBF1RA(2,2)*VIMAGE(2)+             &
     &        SBF1RA(2,3)*VIMAGE(3)
      VTMP(3)=SBF1RA(3,1)*VIMAGE(1)+SBF1RA(3,2)*VIMAGE(2)+             &
     &        SBF1RA(3,3)*VIMAGE(3)
      V2PBRA(1)= VTMP(1)*PBF(1,1) + VTMP(2)*PBF(1,2)
      V2PBRA(2)= VTMP(1)*PBF(2,1) + VTMP(2)*PBF(2,2)
      V2PBRA(3)= VTMP(3)*PBF(3,3)
      VTMP(1)=SBF1DC(1,1)*VIMAGE(1)+SBF1DC(1,2)*VIMAGE(2)+             &
     &        SBF1DC(1,3)*VIMAGE(3)
      VTMP(2)=SBF1DC(2,1)*VIMAGE(1)+SBF1DC(2,2)*VIMAGE(2)+             &
     &        SBF1DC(2,3)*VIMAGE(3)
      VTMP(3)=SBF1DC(3,1)*VIMAGE(1)+SBF1DC(3,2)*VIMAGE(2)+             &
     &        SBF1DC(3,3)*VIMAGE(3)
      V2PBDC(1)= VTMP(1)*PBF(1,1) + VTMP(2)*PBF(1,2)
      V2PBDC(2)= VTMP(1)*PBF(2,1) + VTMP(2)*PBF(2,2)
      V2PBDC(3)= VTMP(3)*PBF(3,3)
      VTMP(1)=SBF1(1,1)*VIMAGE(1)+SBF1(1,2)*VIMAGE(2)+                 &
     &        SBF1(1,3)*VIMAGE(3)
      VTMP(2)=SBF1(2,1)*VIMAGE(1)+SBF1(2,2)*VIMAGE(2)+                 &
     &        SBF1(2,3)*VIMAGE(3)
      VTMP(3)=SBF1(3,1)*VIMAGE(1)+SBF1(3,2)*VIMAGE(2)+                 &
     &        SBF1(3,3)*VIMAGE(3)
      V2PBGA(1)= VTMP(1)*PBFGA(1,1) + VTMP(2)*PBFGA(1,2)
      V2PBGA(2)= VTMP(1)*PBFGA(2,1) + VTMP(2)*PBFGA(2,2)
      V2PBGA(3)= VTMP(3)*PBFGA(3,3)
      ENDIF
!!!!!!!!!!!!!!!!! END TO COMPUTE VECTORS FOR PLANETARY ORIENTATION VECTORS !!!!!

      V2RPBF(1)= V1RTOD(1)*PBF(1,1) + V1RTOD(2)*PBF(1,2)
      V2RPBF(2)= V1RTOD(1)*PBF(2,1) + V1RTOD(2)*PBF(2,2)
      V2RPBF(3)= V1RTOD(3)*PBF(3,3)
      V2PPBF(1)= V1PTOD(1)*PBF(1,1) + V1PTOD(2)*PBF(1,2)
      V2PPBF(2)= V1PTOD(1)*PBF(2,1) + V1PTOD(2)*PBF(2,2)
      V2PPBF(3)= V1PTOD(3)*PBF(3,3)
      V2YPBF(1)= V1YTOD(1)*PBF(1,1) + V1YTOD(2)*PBF(1,2)
      V2YPBF(2)= V1YTOD(1)*PBF(2,1) + V1YTOD(2)*PBF(2,2)
      V2YPBF(3)= V1YTOD(3)*PBF(3,3)

!*********************************************************************
! SAVE INFO FROM THE FIRST OCCURANCE HERE
!*********************************************************************

!    A IF BEGIN
          IF(IRET.EQ.0) THEN
! PUT THE KEY IN THE II(KIKEY) ARRAY  FOR FIRST ENCOUNTER
          II(KIKEY+KIMBST-1)=MKEY

!     WRITE(6,*)' THIS IS THE FIRST OCCURANCE IN THE PAIR '
!     WRITE(6,*)'  JUST SAVING INFORMATION FOR OBS w/KEY=',MKEY
!
! SAVE NUMBER OF OBS/ LOCATION OF BLOCK / SEQUENTIAL # OF BLOCK
!  DO EDITING HERE AND LOAD THE NUMBER OF WEIGHTED OBSERVATIONS
      NOBSBL(KIMBST,1)=NM
! SAVE LOCATION OF BLOCK
      NOBSBL(KIMBST,2)=ISAVE
! SAVE SEQUENTIAL # OF BLOCK
      NOBSBL(KIMBST,5)=ISAVE2
! SAVE ISAT
      NOBSBL(KIMBST,3)=ISAT
! SAVE THE BLOCK MJDSEC
      RINDEX(KIMBST,1)=DBLE(MJDSBL)
! SAVE THE BASE TIME FOR ATTITUDE
      RINDEX(KIMBST,3)= XBTIME
!     RINDEX TWO MORE SLOTS REAL AVAILABLE
! SAVE BEGINING LOCATION OF ATTITUDE PARTIALS FOR THE SPACECRAFT AND THE
      ILATP(KIMBST,1)=IAPLSC
      ILATP(KIMBST,2)=IAPLL
!     write(6,*)'dbg SAVING BEGINNING LOC OF ATT PARTIALS ',IAPLSC,IAPLL
!
      DO 1000 I=1,NM
!     THE TIMES SAVED ARE FSECN (RECEIVED TIME)
! SAVE TIMES FOR FIRST OCCURANCE
      TIMES=AA(KFSECS(1,1)+I-1)
      RIMTIM(KIMBUP)=TIMES
! SAVE OBSERVATIONS FOR FIRST OCCURANCE DIRECTION VECTORS COMMON
! LOAD IN OBSRD
      VIMAGE(1)=VIMGH(1)
      VIMAGE(2)=VIMGH(2)
      VIMAGE(3)=VIMGH(3)
      RIMOBS(1,1,KIMBUP)=VIMAGE(1)
      RIMOBS(1,2,KIMBUP)=VIMAGE(2)
      RIMOBS(1,3,KIMBUP)=VIMAGE(3)
! BODY
      RIMOBS(2,1,KIMBUP)=V2RPBF(1)
      RIMOBS(2,2,KIMBUP)=V2RPBF(2)
      RIMOBS(2,3,KIMBUP)=V2RPBF(3)
      RIMOBS(3,1,KIMBUP)=V2PPBF(1)
      RIMOBS(3,2,KIMBUP)=V2PPBF(2)
      RIMOBS(3,3,KIMBUP)=V2PPBF(3)
      RIMOBS(4,1,KIMBUP)=V2YPBF(1)
      RIMOBS(4,2,KIMBUP)=V2YPBF(2)
      RIMOBS(4,3,KIMBUP)=V2YPBF(3)
      IF(LPLN) THEN
        RIMOBS(5,1,KIMBUP)=XBF2RA(1)
        RIMOBS(5,2,KIMBUP)=XBF2RA(2)
        RIMOBS(5,3,KIMBUP)=XBF2RA(3)
        RIMOBS(6,1,KIMBUP)=XBF2DC(1)
        RIMOBS(6,2,KIMBUP)=XBF2DC(2)
        RIMOBS(6,3,KIMBUP)=XBF2DC(3)
        RIMOBS(7,1,KIMBUP)=XBF2GA(1)
        RIMOBS(7,2,KIMBUP)=XBF2GA(2)
        RIMOBS(7,3,KIMBUP)=XBF2GA(3)
        RIMOBS(8,1,KIMBUP)=V2PBRA(1)
        RIMOBS(8,2,KIMBUP)=V2PBRA(2)
        RIMOBS(8,3,KIMBUP)=V2PBRA(3)
        RIMOBS(9,1,KIMBUP)=V2PBDC(1)
        RIMOBS(9,2,KIMBUP)=V2PBDC(2)
        RIMOBS(9,3,KIMBUP)=V2PBDC(3)
        RIMOBS(10,1,KIMBUP)=V2PBGA(1)
        RIMOBS(10,2,KIMBUP)=V2PBGA(2)
        RIMOBS(10,3,KIMBUP)=V2PBGA(3)
!...Begin TJS
        IF (LINTAX) THEN
           DO IV=1,3
              DO JV=1,6
                 RIMOBS(10+JV,IV,KIMBUP)=DADA0(IV,JV,2)
                 RIMOBS(16+JV,IV,KIMBUP)=DADIC(IV,JV,2)
              END DO
           END DO
        END IF
!...End TJS

      ENDIF
! CAMERA
! SAVE SATELLITE  COORDINATES FOR FIRST OCCURANCE
      DO 30312 J=1,3
      SIMXSM(J,KIMBUP)=XSMTOD(I,J)
30312 END DO
      DO 30320 J=4,6
      SIMXSM(J,KIMBUP)=VSMTOD(I,J-3)
30320 END DO
!
! SAVE ROTATION MATRIX FROM TOD INERTIAL TO CAMERA BODY FIX
      DO JJ=1,3
      DO KK=1,3
      TOTRIM(JJ,KK,KIMBUP)=RIM(JJ,KK)
      TODPBF(JJ,KK,KIMBUP)=PBF(JJ,KK)
      PXEPXI(JJ,KK,KIMBUP)=PXEXI(JJ,KK)
!     write(6,*)' dbg IMAGE RIM ',RIM(JJ,KK)
!     write(6,*)' dbg IMAGE PBF ',PBF(JJ,KK),JJ,KK
      ENDDO
      ENDDO
! INCREASE THE NUMBER OF OBSERVATIONS BY ONE
      NEQP(KIMBUP)=NEQN

      KIMBUP=KIMBUP+1
1000   END DO

!*********************************************************************
! END SAVED INFO FROM THE FIRST OCCURANCE HERE
!*********************************************************************

      DO I=1,NM

! SAVE PARTIALS OF XYZ WRT FM PARAMETERS (PXPF) VARIATIONAL PARTIALS
      IF(LNPNM) GOTO 30315
      DO 30314 KK=1,NDIMX2
      DO 30313 JJ=1,3
      X2PART(KK,JJ,1,KIMBPA)=PXPF(I,KK,JJ,1)
      X2PART(KK,JJ,2,KIMBPA)=PXPF(I,KK,JJ,2)
! DEBUG ****************************************************************
!     write(6,*)' PARTIALS NM,NP  ',X2PART(KK,JJ,KIMBPA),KK,JJ,KIMBPA
! DEBUG ****************************************************************
30313 END DO
30314 END DO
      GOTO 30318
30315 CONTINUE
      DO 30317 KK=1,NDIMX1
      DO 30316 JJ=1,3
      X2PART(KK,JJ,1,KIMBPA)=PXPF(KK,JJ,I,1)
      X2PART(KK,JJ,2,KIMBPA)=PXPF(KK,JJ,I,2)
! DEBUG ****************************************************************
!     write(6,*)' PARTIALS NP,NM  ',X2PART(KK,JJ,KIMBPA),KK,JJ,KIMBPA
! DEBUG ****************************************************************
30316 END DO
30317 END DO
30318 CONTINUE
      KIMBPA=KIMBPA+1
      ENDDO
!**********************************************************************
!  DONE SAVING VARIATIONAL PARTIALS
!**********************************************************************
30319 CONTINUE
!
!  A ELSE FIRST POINT
          ELSE
!  A ELSE SECOND POINT
!
!**********************************************************************
! SECOND BLOCK WAS FOUND. WHERE IN II(KIKEY) IS THE PAIR?
!**********************************************************************
!
      CALL FNDNUM(KEY,II(KIKEY),NIMTOT,IRET2)
!     write(6,*)' dbg FIND where in the key array is the pair ',IRET2
      KEYP=KEY
!
!  C IF BEGIN
!
      IF(IRET2.NE.0) THEN
!
!  GET TIMES FOR BOTH ENCOUNTERS
      MJDSC1=INT(RINDEX(IRET2,1))
      MJDSC2=MJDSBL
      TAT1=RINDEX(IRET2,3)
      TAT2=XBTIME
!  GET NUMBER OF OBS PER BLOCK FOR PREVIOUS ENCOUNTER/ PRESENT=NM
      NMP=NOBSBL(IRET2,1)
!
       write(6,*)'                                               '
       write(6,*)'  DDP *********  IMAGING INFORMATION  *********  '
       write(6,*)'  DDP *********  FOR A NEW PAIR       *********  '
       write(6,*)'                                               '
!
!  GET ISAT AND ISET FOR PREVIOUS ENCOUNTER
      ISAT1=NOBSBL(IRET2,3)
      ISET1=NOBSBL(IRET2,4)
! DEBUG ****************************************************************
!     write(6,*)' ISAT  ',NOBSBL(IRET2,3),ISAT
!     write(6,*)' ISET  ',NOBSBL(IRET2,4),ISAT
! DEBUG ****************************************************************
! GET LOCATION OF PMPA FOR THE ATTITUDE PARTIALS FOR S/C AND CAMERA
      IPAT11=ILATP(IRET2,1)
      IPAT12=ILATP(IRET2,2)
      IPAT21=IAPLSC
      IPAT22=IAPLL
! DEBUG ****************************************************************
!     write(6,*)' POINT AT PMPA FOR ATT PARTIALS S/C ',IPAT11,IPAT21
!     write(6,*)' POINT AT PMPA FOR ATT PARTIALS LASER ',IPAT12,IPAT22
! DEBUG ****************************************************************
! GET NUMBER OF OF FIRST OBSERVATION OF PREVIOUS STREAM IN THE THE BIG A
      IRET3=NOBSBL(IRET2,2)
!     write(6,*)' dbg FIRST OBSERVATION OF PREVIOUS STREAM ',IRET3
! GET NUMBER OF OF FIRST PARTIAL OF PREVIOUS STREAM IN THE THE BIG ARRAY
      IRET9=NOBSBL(IRET2,5)
!     write(6,*)' dbg FIRST PARTIAL OF PREVIOUS STREAM  ',IRET9
! AT THIS POINT WE FOUND 2 BLOCKS FORMING A PAIR. EACH ONE OF THEM HAS
! ONE OBSERVATION

!
!***********************************************************************
! SAVE INFORMATION FOR BLOCKS IN THE SCRATCH ARRAY
!****************!*******************************************************
      VIMAGE(1)=PXV(1)
      VIMAGE(2)=PXV(2)
      VIMAGE(3)=0.D0
      JJ=0
      DO 30301 I=1,NM
      XSCR(1,I)=RIMTIM(IRET3+JJ)
      XSCR(2,I)=AA(KFSECS(1,1)+I-1)
      XSCR(3,I)=RIMOBS(1,1,IRET3+JJ)
      XSCR(4,I)=RIMOBS(1,2,IRET3+JJ)
      XSCR(5,I)=RIMOBS(1,3,IRET3+JJ)
      XSCR(6,I)=VIMGH(1)
      XSCR(7,I)=VIMGH(2)
      XSCR(8,I)=VIMGH(3)
! 7-8 MAY BE USED  FOR SCRATCH
      XSCR(9,I) =SIMXSM(1,IRET3+JJ)
      XSCR(10,I)=SIMXSM(2,IRET3+JJ)
      XSCR(11,I)=SIMXSM(3,IRET3+JJ)
      XSCR(12,I)=XSMTOD(I,1)
      XSCR(13,I)=XSMTOD(I,2)
      XSCR(14,I)=XSMTOD(I,3)
! 15-17 S/C VELOCITY OF THE FIRST POINT IN TOD (THE SECOND ID IN VSMTOD)
      XSCR(15,I)=SIMXSM(4,IRET3+JJ)
      XSCR(16,I)=SIMXSM(5,IRET3+JJ)
      XSCR(17,I)=SIMXSM(6,IRET3+JJ)
! DEBUG ****************************************************************
      write(6,*)' DDP  KEYS IN THIS PAIR ',MKEY,KEY
      write(6,*)' DDP MJDSBL    FOR BOTH BLOCKS ',MJDSC1, MJDSC2
      write(6,*)' DDP FRAC ET SEC FOR BOTH ',XSCR(1,I),XSCR(2,I)
      write(6,*)' DDP TOD X S/C FOR BOTH BLOCKS ',XSCR(9,I), XSCR(12,I)
      write(6,*)' DDP TOD X S/C FOR BOTH BLOCKS ',XSCR(10,I),XSCR(13,I)
      write(6,*)' DDP TOD X S/C FOR BOTH BLOCKS ',XSCR(11,I),XSCR(14,I)
! DEBUG ****************************************************************
      JJ=JJ+1
30301 continue
!
!***********************************************************************
! DONE SAVING INFORMATION
!***********************************************************************
!
!***********************************************************************
! OBTAIN PARTIALS OF  WRT. VARIOUS PARAMETERS
!***********************************************************************

!   CLEAR UP COMPLETELY THE RMVPRT ARRAY
      NXDM=NDIMX1*NDIMX2*NDIMX3*2*2
      CALL CLEARA(RMVPRT,NXDM)

      DO I=1,NM

! OBTAIN THE PARTIALS OF OBS WRT FM PARAMETERS FOR BOTH POINTS (VARIATIONAL)
      IF(LNPNM) GOTO 30304
      DO 30303 KK=1,NDIMX2
      DO 30302 K2=1,3
! PXPF POSITION
      RMVPRT(I,KK,K2,1,1)=X2PART(KK,K2,1,IRET9)
      RMVPRT(I,KK,K2,1,2)=PXPF(I,KK,K2,1)
! PXPF VELOCITY
      RMVPRT(I,KK,K2,2,1)=X2PART(KK,K2,2,IRET9)
      RMVPRT(I,KK,K2,2,2)=PXPF(I,KK,K2,2)
! DEBUG ****************************************************************
!     write(6,*)' dbg  1 part ',x2part(kk,k2,iret9),kk,k2,iret9
!     write(6,*)' dbg  2 part',pxpf(I,KK,K2,1),i,kk,k2
! DEBUG ****************************************************************
30302 END DO
30303 END DO
      GOTO 30307
30304 CONTINUE
      DO 30306 KK=1,NDIMX1
      DO 30305 K2=1,3
! PXPF POSITION
      RMVPRT(KK,K2,I,1,1)=X2PART(KK,K2,1,IRET9)
      RMVPRT(KK,K2,I,1,2)=PXPF(KK,K2,I,1)
! PXPF VELOCITY
      RMVPRT(KK,K2,I,2,1)=X2PART(KK,K2,2,IRET9)
      RMVPRT(KK,K2,I,2,2)=PXPF(KK,K2,I,2)
! DEBUG ****************************************************************
!     write(6,*)'dbg partials for 1st ',x2part(kk,k2,iret9),kk,k2,iret9
!     write(6,*)'dbg partials for 2nd ',pxpf(KK,K2,I,1)
! DEBUG ****************************************************************
30305 END DO
30306 END DO
30307 CONTINUE
      ENDDO


!
!  FORM 3X3 PARTIALS OF THETA(PBF)/THETA(TOD INERTIAL) DXPDXI(3,3)
! P1
       DXPDXI(1,1,1)=PXEPXI(1,1,IRET3)
       DXPDXI(2,1,1)=PXEPXI(2,1,IRET3)
       DXPDXI(3,1,1)=PXEPXI(3,1,IRET3)
       DXPDXI(1,2,1)=PXEPXI(1,2,IRET3)
       DXPDXI(2,2,1)=PXEPXI(2,2,IRET3)
       DXPDXI(3,2,1)=PXEPXI(3,2,IRET3)
       DXPDXI(1,3,1)=PXEPXI(1,3,IRET3)
       DXPDXI(2,3,1)=PXEPXI(2,3,IRET3)
       DXPDXI(3,3,1)=PXEPXI(3,3,IRET3)
!      write(6,*)' dbg1', DXPDXI(1,1,1),DXPDXI(1,2,1),DXPDXI(1,3,1)
!      write(6,*)' dbg1', DXPDXI(2,1,1),DXPDXI(3,2,1),DXPDXI(2,3,1)
!      write(6,*)' dbg1', DXPDXI(3,1,1),DXPDXI(3,2,1),DXPDXI(3,3,1)
! P2

       DXPDXI(1,1,2)=PXEXI(1,1)
       DXPDXI(2,1,2)=PXEXI(2,1)
       DXPDXI(3,1,2)=PXEXI(3,1)
       DXPDXI(1,2,2)=PXEXI(1,2)
       DXPDXI(2,2,2)=PXEXI(2,2)
       DXPDXI(3,2,2)=PXEXI(3,2)
       DXPDXI(1,3,2)=PXEXI(1,3)
       DXPDXI(2,3,2)=PXEXI(2,3)
       DXPDXI(3,3,2)=PXEXI(3,3)

!      write(6,*)' dbg2', DXPDXI(1,1,2),DXPDXI(1,2,2),DXPDXI(1,3,2)
!      write(6,*)' dbg2', DXPDXI(2,1,2),DXPDXI(3,2,2),DXPDXI(2,3,2)
!      write(6,*)' dbg2', DXPDXI(3,1,2),DXPDXI(3,2,2),DXPDXI(3,3,2)
!
!***********************************************************************
! FORM OBSERVATION
!***********************************************************************
! MINIMUM DISTANCE
!
!  COMPUTE THE OBSERVATION USING THE PROVIDED DIRECTION VECTORS ON G2B
!    R1 FIRST OCC RANGE/ R2 SECOND
!
      DO 30311 I=1,NM
!
      DO 30310 IXX=1,6
!
!     FIRST OCCURANCE CAMERA
      CAMID=XSCR(5,I)
!     CAMID=7777.0
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET4)
      IF (IRET4.EQ.0.0D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' CAMERA ID NOT FOUND, CHECK UNIT 5 SETUP'
      WRITE(6,*)' FOR CAMERA', IDCAM
      STOP
      END IF
!     FLMMH=AA(KPRMV+IPVAL(IXCAME)-1)
      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET4-1)*5)

      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET4-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET4-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET4-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values 2  ',FLMMH,DISTRH(2)
!!!!  IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      IF(FLMMH.EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF

!
      IF(IXX.EQ.1) FLMMH=FLMMH+DELCP(1)
      IF(IXX.GT.1.AND.IXX.LT.6) DISTRH(IXX-1)=DISTRH(IXX-1)+DELCP(IXX)

 !  V& V2 ARE GIVEN IN THE S/C BODY FIXED SYSTEM
!!!!  V1(1)=XSCR(3,I)
!!!!  V1(2)=XSCR(4,I)
!!!!  V1(3)=XSCR(5,I)
!
       CALL GETVEC(XSCR(3,I),XKMAT,DISTRH,FLMMH,CTR,V1)
!       XSCR(3,I)=V1(1)
!       XSCR(4,I)=V1(2)
!       XSCR(5,I)=V1(3)

!     SECOND OCCURANCE CAMERA
      CAMID=XSCR(8,I)
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET5)
      IF (IRET5.EQ.0.0D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' CAMERA ID NOT FOUND, CHECK UNIT 5 SETUP'
      WRITE(6,*)' FOR CAMERA', IDCAM
      STOP
      END IF
!     FLMMH=AA(KPRMV+IPVAL(IXCAME)-1)
      FLMMH=AA(KPRMV+IPVAL(IXCAME)-1+(IRET5-1)*5)
      IF(NPVAL0(IXCAME).GE.5)       &
     &          FLMMH=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET5-1)*5)
      DO IX=1,4
        DISTRH(IX)=AA(KPRMV+IPVAL(IXCAME)-1+(IRET5-1)*5+IX)
        IF(NPVAL0(IXCAME).GE.5) THEN
          DISTRH(IX)=AA(KPRMVC+IPVAL0(IXCAME)-1+(IRET5-1)*5+IX)
        ENDIF
      ENDDO
!     write(6,*)' dbg values ',FLMMH,DISTRH(2)
!!!!  IF(FLMMH.EQ.0.D0.OR.DISTRH(2).EQ.0.D0) THEN
      IF(FLMMH.EQ.0.D0) THEN
      WRITE(6,*)' EXECUTION TERMINATED IN IMAGE'
      WRITE(6,*)' SOME CAMERA PARAMETERS ARE ZERO'
      STOP
      ENDIF

!
      IF(IXX.EQ.1) FLMMH=FLMMH+DELCP(1)
      IF(IXX.GT.1.AND.IXX.LT.6) DISTRH(IXX-1)=DISTRH(IXX-1)+DELCP(IXX)

!!!!  V2(1)=XSCR(6,I)
!!!!  V2(2)=XSCR(7,I)
!!!!  V2(3)=XSCR(8,I)
!
       CALL GETVEC(XSCR(6,I),XKMAT,DISTRH,FLMMH,CTR,V2)
!       XSCR(6,I)=V2(1)
!       XSCR(7,I)=V2(2)
!       XSCR(8,I)=V2(3)

!DEBUG !
!     VV=DSQRT(V1(1)*V1(1) + V1(2)*V1(2) + V1(3)*V1(3))
!     WRITE(6,*)'dbg VECTOR 1 VERFICATION IN SBF',VV
!     VV=DSQRT(V2(1)*V2(1) + V2(2)*V2(2) + V2(3)*V2(3))
!     WRITE(6,*)'dbg VECTOR 2 VERFICATION IN SBF',VV
!DEBUG !

!  CONVERT V1 V2 to INERTIAL TOD
      V1TOD(1)=TOTRIM(1,1,IRET3)*V1(1)+TOTRIM(1,2,IRET3)*V1(2)+ &
     &         TOTRIM(1,3,IRET3)*V1(3)
      V1TOD(2)=TOTRIM(2,1,IRET3)*V1(1)+TOTRIM(2,2,IRET3)*V1(2)+ &
     &         TOTRIM(2,3,IRET3)*V1(3)
      V1TOD(3)=TOTRIM(3,1,IRET3)*V1(1)+TOTRIM(3,2,IRET3)*V1(2)+ &
     &         TOTRIM(3,3,IRET3)*V1(3)

      V2TOD(1)=RIM(1,1)*V2(1) + RIM(1,2)*V2(2) + RIM(1,3)*V2(3)
      V2TOD(2)=RIM(2,1)*V2(1) + RIM(2,2)*V2(2) + RIM(2,3)*V2(3)
      V2TOD(3)=RIM(3,1)*V2(1) + RIM(3,2)*V2(2) + RIM(3,3)*V2(3)

!DEBUG !
!     VV=DSQRT(V1TOD(1)*V1TOD(1)+V1TOD(2)*V1TOD(2)+V1TOD(3)*V1TOD(3))
!     WRITE(6,*)'dbg VECTOR 1 VERFICATION IN TOD',VV
!     VV=DSQRT(V2TOD(1)*V2TOD(1)+V2TOD(2)*V2TOD(2)+V2TOD(3)*V2TOD(3))
!     WRITE(6,*)'dbg VECTOR 2 VERFICATION IN TOD',VV
!DEBUG !

! ROTATE SATELLITE COORDINATES AND VECTORS FROM TOD TO PLANET BODY FIXED

!DEBUG !
!     write(6,*)' DDP ROTATION MATRIX S/C BODY FIXED TO TOD 1st PT '
!     DO JJ=1,3
!     write(6,*)' DDP',TOTRIM(JJ,1,IRET3),TOTRIM(JJ,2,IRET3), &
!    &                 TOTRIM(JJ,3,IRET3)
!     ENDDO

!     write(6,*)' DDP ROTATION MATRIX S/C BODY FIXED TO TOD 2st PT '
!     DO JJ=1,3
!     write(6,*)' DDP',RIM(JJ,1),RIM(JJ,2),RIM(JJ,3)
!     ENDDO

!     write(6,*)' DDP ROTATION MATRIX TOD TO PBF 1st PT '
!     DO JJ=1,3
!     write(6,*)' DDP',TODPBF(JJ,1,IRET3),TODPBF(JJ,2,IRET3), &
!    & TODPBF(JJ,3,IRET3),IRET3
!     ENDDO

!     write(6,*)' DDP ROTATION MATRIX TOD TO PBF 2st PT '
!     DO JJ=1,3
!     write(6,*)' DDP ',PBF(JJ,1),PBF(JJ,2),PBF(JJ,3)
!     ENDDO
!DEBUG !

! THE MINUS SIGN EXISTS ALREADY IN PBF AND TODPBF
! XBF PLANET BODY FIXED COORDINATES

      XBF(I,1)=  XSCR(9,I)*TODPBF(1,1,IRET3)+XSCR(10,I)*TODPBF(1,2,IRET3)
      XBF(I,2)=  XSCR(9,I)*TODPBF(2,1,IRET3)+XSCR(10,I)*TODPBF(2,2,IRET3)
      XBF(I,3)= XSCR(11,I)*TODPBF(3,3,IRET3)

      VL1PBF(I,1)=                                                     &
     &        XSCR(15,I)*TODPBF(1,1,IRET3)+XSCR(16,I)*TODPBF(1,2,IRET3)
      VL1PBF(I,2)=                                                     &
     &        XSCR(15,I)*TODPBF(2,1,IRET3)+XSCR(16,I)*TODPBF(2,2,IRET3)
      VL1PBF(I,3)= XSCR(17,I)*TODPBF(3,3,IRET3)

      V1PBF(1)= V1TOD(1)*TODPBF(1,1,IRET3) + V1TOD(2)*TODPBF(1,2,IRET3)
      V1PBF(2)= V1TOD(1)*TODPBF(2,1,IRET3) + V1TOD(2)*TODPBF(2,2,IRET3)
      V1PBF(3)= V1TOD(3)*TODPBF(3,3,IRET3)

      V1RPBF(1)=RIMOBS(2,1,IRET3)
      V1RPBF(2)=RIMOBS(2,2,IRET3)
      V1RPBF(3)=RIMOBS(2,3,IRET3)
      V1PPBF(1)=RIMOBS(3,1,IRET3)
      V1PPBF(2)=RIMOBS(3,2,IRET3)
      V1PPBF(3)=RIMOBS(3,3,IRET3)
      V1YPBF(1)=RIMOBS(4,1,IRET3)
      V1YPBF(2)=RIMOBS(4,2,IRET3)
      V1YPBF(3)=RIMOBS(4,3,IRET3)
      IF(LPLN) THEN
         XBF1RA(1)=RIMOBS(5,1,IRET3)
         XBF1RA(2)=RIMOBS(5,2,IRET3)
         XBF1RA(3)=RIMOBS(5,3,IRET3)
         XBF1DC(1)=RIMOBS(6,1,IRET3)
         XBF1DC(2)=RIMOBS(6,2,IRET3)
         XBF1DC(3)=RIMOBS(6,3,IRET3)
         XBF1GA(1)=RIMOBS(7,1,IRET3)
         XBF1GA(2)=RIMOBS(7,2,IRET3)
         XBF1GA(3)=RIMOBS(7,3,IRET3)
         V1PBRA(1)=RIMOBS(8,1,IRET3)
         V1PBRA(2)=RIMOBS(8,2,IRET3)
         V1PBRA(3)=RIMOBS(8,3,IRET3)
         V1PBDC(1)=RIMOBS(9,1,IRET3)
         V1PBDC(2)=RIMOBS(9,2,IRET3)
         V1PBDC(3)=RIMOBS(9,3,IRET3)
         V1PBGA(1)=RIMOBS(10,1,IRET3)
         V1PBGA(2)=RIMOBS(10,2,IRET3)
         V1PBGA(3)=RIMOBS(10,3,IRET3)
!...Begin TJS
         IF (LINTAX) THEN
            DO IV=1,3
               DO JV=1,6
                  DADA0(IV,JV,1)=RIMOBS(10+JV,IV,IRET3)
                  DADIC(IV,JV,1)=RIMOBS(16+JV,IV,IRET3)
               END DO
            END DO
         END IF
!...End TJS

      ENDIF
      XBF2(I,1)= XSCR(12,I)*PBF(1,1)+ XSCR(13,I)*PBF(1,2)
      XBF2(I,2)= XSCR(12,I)*PBF(2,1)+ XSCR(13,I)*PBF(2,2)
      XBF2(I,3)= XSCR(14,I)*PBF(3,3)

      VL2PBF(I,1)= VSMTOD(I,1)*PBF(1,1)+ VSMTOD(I,2)*PBF(1,2)
      VL2PBF(I,2)= VSMTOD(I,1)*PBF(2,1)+ VSMTOD(I,2)*PBF(2,2)
      VL2PBF(I,3)= VSMTOD(I,3)*PBF(3,3)

      V2PBF(1)= V2TOD(1)*PBF(1,1) + V2TOD(2)*PBF(1,2)
      V2PBF(2)= V2TOD(1)*PBF(2,1) + V2TOD(2)*PBF(2,2)
      V2PBF(3)= V2TOD(3)*PBF(3,3)

! DEBUG !
!     VV=DSQRT(V1PBF(1)*V1PBF(1)+V1PBF(2)*V1PBF(2)+V1PBF(3)*V1PBF(3))
!     WRITE(6,*)'dbg VECTOR 1 VERFICATION IN PBF',VV
!     VV=DSQRT(V2PBF(1)*V2PBF(1)+V2PBF(2)*V2PBF(2)+V2PBF(3)*V2PBF(3))
!     WRITE(6,*)'dbg VECTOR 2 VERFICATION IN PBF',VV
! DEBUG !

      IF(IXX.EQ.6) THEN
        write(6,*)' DDP PBF X S/C FOR BOTH BLOCKS ',XBF(I,1),XBF2(I,1)
        write(6,*)' DDP PBF Y S/C FOR BOTH BLOCKS ',XBF(I,2),XBF2(I,2)
        write(6,*)' DDP PBF Z S/C FOR BOTH BLOCKS ',XBF(I,3),XBF2(I,3)
        write(6,*)' DDP DIR VECTORS IN SBF ',XSCR(3,I),XSCR(6,I)
        write(6,*)' DDP DIR VECTORS IN SBF ',XSCR(4,I),XSCR(7,I)
        write(6,*)' DDP DIR VECTORS IN SBF ',XSCR(5,I),XSCR(8,I)
        write(6,*)' DDP DIR VECTORS IN TOD ',V1TOD(1),V2TOD(1)
        write(6,*)' DDP DIR VECTORS IN TOD ',V1TOD(2),V2TOD(2)
        write(6,*)' DDP DIR VECTORS IN TOD ',V1TOD(3),V2TOD(3)
        write(6,*)' DDP DIR VECTORS IN PBF ',V1PBF(1),V2PBF(1)
        write(6,*)' DDP DIR VECTORS IN PBF ',V1PBF(2),V2PBF(2)
        write(6,*)' DDP DIR VECTORS IN PBF ',V1PBF(3),V2PBF(3)
      ENDIF
! MORE VERIFICATION
!     VV=DSQRT( XSCR(9,I)*XSCR(9,I)+XSCR(10,I)*XSCR(10,I)+     &
!    &          XSCR(11,I)*XSCR(11,I))
!     write(6,*)' DDP geoc range TOD at point 1 ',VV
!     VV=DSQRT( XSCR(12,I)*XSCR(12,I)+XSCR(13,I)*XSCR(13,I)+     &
!    &          XSCR(14,I)*XSCR(14,I))
!     write(6,*)' DDP geoc range TOD at point 2 ',VV
!     VVF=DSQRT( XBF(I,1)*XBF(I,1)+XBF(I,2)*XBF(I,2)+             &
!    &          XBF(I,3)*XBF(I,3))
!     VVS=DSQRT( XBF2(I,1)*XBF2(I,1)+XBF2(I,2)*XBF2(I,2)+             &
!    &          XBF2(I,3)*XBF2(I,3))

! COMPUTE LANDMARK COORDINATES IN THE PBF SYSTEM
! NORMALIZE V1PBF V2PBF
      A=SQRT(V1PBF(1)*V1PBF(1) + V1PBF(2)*V1PBF(2) + V1PBF(3)*V1PBF(3))
      B=SQRT(V2PBF(1)*V2PBF(1) + V2PBF(2)*V2PBF(2) + V2PBF(3)*V2PBF(3))

      V1PBFN(1)=V1PBF(1)/A
      V1PBFN(2)=V1PBF(2)/A
      V1PBFN(3)=V1PBF(3)/A

      V2PBFN(1)=V2PBF(1)/B
      V2PBFN(2)=V2PBF(2)/B
      V2PBFN(3)=V2PBF(3)/B

      DP(1)=XBF2(1,1)-XBF(1,1)
      DP(2)=XBF2(1,2)-XBF(1,2)
      DP(3)=XBF2(1,3)-XBF(1,3)

      CALL DOTPRD(DP,V2PBFN,DE1,3,3,1,1)
      CALL DOTPRD(V1PBFN,V2PBFN,DE2,3,3,1,1)
      CALL DOTPRD(DP,V1PBFN,DE3,3,3,1,1)

      EPS1=1.D0-DE2**2.D0
      EPS2=DE1*DE2-DE3

      EMA=EPS2/EPS1
      EMB=DE1+DE2*EMA
      IF(EMA.LT.ZERO.OR.EMB.LT.ZERO) THEN
      WRITE(6,*)' WARNING NO MEANINGFUL INTERSECTION '
      ENDIF

      DO IK=1,3
      XBOUNCE(IK)=(XBF(1,IK)+XBF2(1,IK)+    &
     &             EMA*V1PBFN(IK)+EMB*V2PBFN(IK))/2.D0
      ENDDO

! COMPUTE LANDMARK COORDINATES IN THE PBF SYSTEM END

!  COMPUTE N HAT
      CALL SSPIMG(V1PBF,V2PBF,ENHAT,CC,EF)

      DIST= (XBF(I,1) - XBF2(I,1)) * ENHAT(1)         +               &
     &      (XBF(I,2) - XBF2(I,2)) * ENHAT(2)         +               &
     &      (XBF(I,3) - XBF2(I,3)) * ENHAT(3)
      IF(IXX.LE.5) DISTP(IXX)=DIST
      IF(IXX.EQ.6) write(6,*)'DDP COMPUTED MINIMUM DISTANCE  ',DIST
30310 CONTINUE
      DO IX=1,5
        DISTP(IX)=(DISTP(IX)-DIST)/DELCP(IX)
      ENDDO


      IF(LIMAT) THEN
! FIRST POINT
      CALL SSPIMG(V1RPBF,V2PBF,ENHBR,CC,EF)
      DIST1R= (XBF(I,1) - XBF2(I,1)) * ENHBR(1)         +               &
     &        (XBF(I,2) - XBF2(I,2)) * ENHBR(2)         +               &
     &        (XBF(I,3) - XBF2(I,3)) * ENHBR(3)

      CALL SSPIMG(V1PPBF,V2PBF,ENHBP,CC,EF)
       DIST1P= (XBF(I,1) - XBF2(I,1)) * ENHBP(1)         +            &
     &         (XBF(I,2) - XBF2(I,2)) * ENHBP(2)         +            &
     &         (XBF(I,3) - XBF2(I,3)) * ENHBP(3)


      CALL SSPIMG(V1YPBF,V2PBF,ENHBY,CC,EF)
       DIST1Y= (XBF(I,1) - XBF2(I,1)) * ENHBY(1)         +            &
     &         (XBF(I,2) - XBF2(I,2)) * ENHBY(2)         +            &
     &         (XBF(I,3) - XBF2(I,3)) * ENHBY(3)

       X2VPA(1,1,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,1,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,1,3,1)=-(DIST-DIST1Y)/ATTPRT
       X2VPA(1,2,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,2,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,2,3,1)=-(DIST-DIST1Y)/ATTPRT
       X2VPA(1,3,1,1)=-(DIST-DIST1R)/ATTPRT
       X2VPA(1,3,2,1)=-(DIST-DIST1P)/ATTPRT
       X2VPA(1,3,3,1)=-(DIST-DIST1Y)/ATTPRT


! SECOND POINT
      CALL SSPIMG(V1PBF,V2RPBF,ENHBR,CC,EF)
      DIST2R= (XBF(I,1) - XBF2(I,1)) * ENHBR(1)         +               &
     &        (XBF(I,2) - XBF2(I,2)) * ENHBR(2)         +               &
     &        (XBF(I,3) - XBF2(I,3)) * ENHBR(3)

      CALL SSPIMG(V1PBF,V2PPBF,ENHBP,CC,EF)
       DIST2P= (XBF(I,1) - XBF2(I,1)) * ENHBP(1)         +            &
     &         (XBF(I,2) - XBF2(I,2)) * ENHBP(2)         +            &
     &         (XBF(I,3) - XBF2(I,3)) * ENHBP(3)

      CALL SSPIMG(V1PBF,V2YPBF,ENHBY,CC,EF)
       DIST2Y= (XBF(I,1) - XBF2(I,1)) * ENHBY(1)         +            &
     &         (XBF(I,2) - XBF2(I,2)) * ENHBY(2)         +            &
     &         (XBF(I,3) - XBF2(I,3)) * ENHBY(3)

       X2VPA(1,1,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,1,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,1,3,2)=-(DIST-DIST2Y)/ATTPRT
       X2VPA(1,2,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,2,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,2,3,2)=-(DIST-DIST2Y)/ATTPRT
       X2VPA(1,3,1,2)=-(DIST-DIST2R)/ATTPRT
       X2VPA(1,3,2,2)=-(DIST-DIST2P)/ATTPRT
       X2VPA(1,3,3,2)=-(DIST-DIST2Y)/ATTPRT

      ENDIF
      IF(LPLN) THEN
         CALL SSPIMG(V1PBRA,V2PBF,ENHPOR,CC,EF)
         DISTRA= (XBF1RA(1) - XBF2(I,1)) * ENHPOR(1)         +    &
     &           (XBF1RA(2) - XBF2(I,2)) * ENHPOR(2)         +    &
     &           (XBF1RA(3) - XBF2(I,3)) * ENHPOR(3)
         CALL SSPIMG(V1PBDC,V2PBF,ENHPOR,CC,EF)
         DISTDC= (XBF1DC(1) - XBF2(I,1)) * ENHPOR(1)         +    &
     &           (XBF1DC(2) - XBF2(I,2)) * ENHPOR(2)         +    &
     &           (XBF1DC(3) - XBF2(I,3)) * ENHPOR(3)
         CALL SSPIMG(V1PBGA,V2PBF,ENHPOR,CC,EF)
         DISTGA= (XBF1GA(1) - XBF2(I,1)) * ENHPOR(1)         +    &
     &           (XBF1GA(2) - XBF2(I,2)) * ENHPOR(2)         +    &
     &           (XBF1GA(3) - XBF2(I,3)) * ENHPOR(3)
         PPOR(1,1)=(DISTRA-DIST)/DXGEO1
         PPOR(2,1)=(DISTDC-DIST)/DXGEO1
         PPOR(3,1)=(DISTGA-DIST)/DXGEO2
         CALL SSPIMG(V1PBF,V2PBRA,ENHPOR,CC,EF)
         DISTRA= (XBF(I,1) - XBF2RA(1)) * ENHPOR(1)         +    &
     &           (XBF(I,2) - XBF2RA(2)) * ENHPOR(2)         +    &
     &           (XBF(I,3) - XBF2RA(3)) * ENHPOR(3)
         CALL SSPIMG(V1PBF,V2PBDC,ENHPOR,CC,EF)
         DISTDC= (XBF(I,1) - XBF2DC(1)) * ENHPOR(1)         +    &
     &           (XBF(I,2) - XBF2DC(2)) * ENHPOR(2)         +    &
     &           (XBF(I,3) - XBF2DC(3)) * ENHPOR(3)
         CALL SSPIMG(V1PBF,V2PBGA,ENHPOR,CC,EF)
         DISTGA= (XBF(I,1) - XBF2GA(1)) * ENHPOR(1)         +    &
     &           (XBF(I,2) - XBF2GA(2)) * ENHPOR(2)         +    &
     &           (XBF(I,3) - XBF2GA(3)) * ENHPOR(3)
         PPOR(1,2)=(DISTRA-DIST)/DXGEO1
         PPOR(2,2)=(DISTDC-DIST)/DXGEO1
         PPOR(3,2)=(DISTGA-DIST)/DXGEO2
      ENDIF
30311 CONTINUE

! FORM THE MATRICES THAT GO FROM SBF TO PBF AT 2 IMAGE TIMES

      CALL MATPRD(TOTRIM(1,1,IRET3),TODPBF(1,1,IRET3),SBFPBF(1,1,1),  &
     &            3,3,3)
      CALL MATPRD(RIM,PBF,SBFPBF(1,1,2),3,3,3)

      write(6,*)'                                               '
      write(6,*)'                                               '
      write(6,*)'  *********  DDP IMAGING INFORMATION  *********  '
      write(6,*)'  *********  END                      *********  '
      write(6,*)'                                               '
      write(6,*)'                                               '

!  PART IS THE THETA CONSTR/THETA nhat
!  XSCR( 9-12,1) ARE THE TOD SC COORDINATES AT POINT 1
!  XSCR(12-14,1) ARE THE TOD SC COORDINATES AT POINT 2

!
       NEQN1=NEQP(IRET3)

!  THETA DIST/THETA X(PBF) etc

       PART(1)=ENHAT(1)
       PART(2)=ENHAT(2)
       PART(3)=ENHAT(3)

!***********************************************************************
! END FORM OBSERVATION
!***********************************************************************
!***********************************************************************
!     PARTIALS CHAINING
!***********************************************************************
!
!     CLEAR PARTIALS
      NNPM=NDIM1*NDIM2
      CALL CLEARA(PMPA,NNPM)
!
! FOR THE TWO POINTS IN THE PAIR
        DO JJ=1,2


      IF(JJ.EQ.1) CAMID=XSCR(5,1)
      IF(JJ.EQ.2) CAMID=XSCR(8,1)
      IDCAM=INT(CAMID)
      CALL FNDNUM(IDCAM,NSCID,30,IRET6)

      JPTD=0
      IF(NPVAL0(IXCAME).GE.5) THEN
        IPTD=IPVAL0(IXCAME)-1+(IRET6-1)*5
        JPTD=IPTD+1
        IF(LNPNM) THEN
          DO IXD=1,5
           PMPA(IXD+IPTD,1)=DISTP(IXD)
          ENDDO
        ELSE
          DO IXD=1,5
           PMPA(1,IXD+IPTD)=DISTP(IXD)
          ENDDO
        ENDIF
      ENDIF


      IF(JJ.EQ.1) THEN
         NEQNU=NEQN1
         NDMXU1=NM
         NDMXU2=NEQNU
         NDMXU3=3
         IF(LNPNM) THEN
           NDMXU1=NEQNU
           NDMXU2=3
           NDMXU3=NM
         ENDIF
         JSAT=ISAT1
         JSET=ISET1
         IP0AT1=IPAT11
         IP0AT2=IPAT12
         PER=ATPER(JSAT)
         DO 410 I=1,NM
         TIME1=XSCR(1,I)-(TAT1-DBLE(MJDSC1))
  410    CONTINUE
      ENDIF
      IF(JJ.EQ.2) THEN
         NEQNU=NEQN
         NDMXU1=NM
         NDMXU2=NEQNU
         NDMXU3=3
         IF(LNPNM) THEN
           NDMXU1=NEQNU
           NDMXU2=3
           NDMXU3=NM
         ENDIF
         JSAT=ISAT
         JSET=ISET
         IP0AT1=IPAT21
         IP0AT2=IPAT22
         PER=ATPER(JSAT)
         DO 420 I=1,NM
         TIME1=XSCR(2,I)-(TAT2-DBLE(MJDSC2))
  420    CONTINUE
      ENDIF

      SIGN=1.D0
      IF(JJ.EQ.2) SIGN=-1.D0


! POSITION PARTIALS 900 LOOP IS FOR FORCE MODEL PARTIALS
! COMPUTE THESE FIRST WHILE LAVOID IS STILL INITIALIZED

      DO 900 IX=1,3
      PMPI(1)=SIGN*PART(IX)*DXPDXI(1,IX,JJ)
      PMPI(2)=SIGN*PART(IX)*DXPDXI(2,IX,JJ)
      PMPI(3)=SIGN*PART(IX)*DXPDXI(3,IX,JJ)

! CHAIN DXPDXI PARTIALS TO FM PARTIALS

      NCLR=NDIM1*NDIM2
      CALL CLEARA(PXEPA,NCLR)
      CALL CHAIN (PMPI,NM,3,1,RMVPRT(1,1,1,1,JJ),NDMXU1,                &
     &    NDMXU2,NDMXU3,                                                &
     &    NEQNU,N3,IPTFMG(1,JSAT),ILNFMG(1,JSAT),NFMG(JSAT),            &
     &    PXEPA,NDIM1,NDIM2,LNPNM,.FALSE.,.FALSE.,1.D0,LL(KLAVOI))
! CHAIN ATTITUDE PARTIALS

         IF(LNPNM) THEN
         DO 600 J=1,NM
         DO 500 K=1,NADJST
         IF(LL(KLAVOI-1+K)) GO TO 500
         PMPA(K,J)=PMPA(K,J)+PXEPA(K,J)

  500    CONTINUE
  600    CONTINUE

      ELSE
         DO 800 J=1,NM
         DO 700 K=1,NADJST
         IF(LL(KLAVOI-1+K)) GO TO 700
          PMPA(J,K)=PMPA(J,K)+PXEPA(J,K)

  700    CONTINUE
  800    CONTINUE
      ENDIF


 900  CONTINUE
! FORCE MODEL PARTIALS COMPUTED; COMPUTE ATTITUDE PARTIALS
       IF(IP0AT1.GT.0) THEN
          PRPY(1)=X2VPA(1,1,1,JJ)
          PRPY(2)=X2VPA(1,1,2,JJ)
          PRPY(3)=X2VPA(1,1,3,JJ)
           CALL CHNAT2(PRPY,PMPA,1,NDIM1,NDIM2,LNPNM,                  &
     &           TIME1,PER,LL(KLAVOI),IP0AT1)
       ENDIF
       IF(IP0AT2.GT.0) THEN
          PRPY(1)=X2VPA(1,1,1,JJ)
          PRPY(2)=X2VPA(1,1,2,JJ)
          PRPY(3)=X2VPA(1,1,3,JJ)
           CALL CHNAT2(PRPY,PMPA,1,NDIM1,NDIM2,LNPNM,                  &
     &           TIME1,PER,LL(KLAVOI),IP0AT2)
       ENDIF
!
! FINALLY GET PLANOR
!
       IF(LPLN) THEN
         TQ=DBLE(MJDSC1)+XSCR(1,I)
         IF(JJ.EQ.2) TQ=DBLE(MJDSC2)+XSCR(2,I)
         CALL CHPOR(PPOR(1,JJ),PMPA,1,NDIM1,NDIM2,LNPNM,               &
!...Begin TJS
!... &              TQ,LL(KLAVOI),AA(KANGWT),AA(KWT),AA(KPPER))
     &              TQ,LL(KLAVOI),AA(KANGWT),AA(KWT),AA(KPPER),         &
     &              DADA0(1,1,JJ),DADIC(1,1,JJ),1)
!...End TJS

       ENDIF
! FOR THE TWO POINTS (JJ)  IN THE PAIR (BELOW)
        ENDDO
! FOR THE TWO POINTS (JJ)  IN THE PAIR (ABOVE)

! CAMERA PARTIALS HAVE ALREADY BEEN COMPUTED; ACCOUNT FOR THEM IN LAVOID
      IF(NPVAL0(IXCAME).GE.5) THEN
        DO I=1,NPVAL0(IXCAME)
         LL(KLAVOI+IPVAL0(IXCAME)-2+I)=.FALSE.
        ENDDO
      ENDIF
      ENDIF
! DEBUG HERE IS THE PMPA ARRAY
!        DO 1501 K=1,NADJST
!     write(6,*)' DEBUG PMPA ',PMPA(K),K
!1501    CONTINUE
!
!***********************************************************************
! DONE WITH PARTIALS
!***********************************************************************
!
!  C IF END
      DO  N=1,NM
      LEDIT (N)=(OBSSIG(N).LE.0.D0)
      ENDDO
      RESID(1)=-DIST
      SIGMA(1)=1.D0/(OBSSIG(1)*OBSSIG(1))
      LBEDIT=.FALSE.
      LSCALE=.FALSE.
      LNEDIT=.TRUE.

! CONTRIBUTE TO THE TOTAL PARTIAL DERIVATIVE MATR

!  ACCUMULATE PARTIALS & RESIDUALS INTO THE
!  NORMAL MATRIX AND RIGHT HAND SIDE OF THE NORMAL EQ.

      CALL SUMNPF(PMPA,RESID,SIGMA,NADJST,MAPARM,1,                 &
     &            AA(KSUM1),AA(KSUM2),AA(KPDLTA),LL(KLAVOI))
!
      RESIDU(1)=RESID(1)
      RATIO(1)=RESID(1)/EDTSIG(1)

      ENDIF
!
! A IF END

      IF(IRET2.EQ.0) GOTO 9600
!
! PRINT RESIDUAL HEADERS
      INDSYS=MOD(ITSYS,10000)/100
      INDSYS=MIN(MAX(INDSYS+1,1),3)
!
! OUTPUT UTC CALENDAR TIMES
!
      SIGMA(1)=RESID(1)/OBSSIG(1)
      KNTOBS=KNTOBS+1
      KNTBLK=KNTBLK+1
      CALL YMDHMS(MJDSBL,OBSTIM,IYMD,IHM,SEC,NM)
      IF(IYMD.GT.1000000)IYMD=IYMD-1000000

!
      IPAGE6=IPAGE6+1
          WRITE(6,10001,IOSTAT=IERR) NARC,NINNER,NGLOBL,IPAGE6,DTYPE(1),&
     &    BLKNEW,(NUM(I),I=1,3),                                        &
     &    TIMSYS(INDSYS)

10001 FORMAT('1',15X,'OBSERVATION RESIDUALS FOR ARC',                   &
     &   I3,' FOR INNER ITERATION',I3,' OF GLOBAL ITERATION',I2,17X,    &
     &   'UNIT  6 PAGE NO.',I6/                                         &
     &   2X,'STATION-SATELLITE CONFIGURATION ',2X,A8,12X,               &
     &   A7/23X,'STATION NUMBERS -',I8,12X,I8,12X,I8,                   &
     &   /2X,'DATE  GREENWICH TIME',6X,'OBSERVATION',9X,                &
     &   'RESIDUAL',2X,'RATIO TO SIGMA',4X, ' SIGMA ', 4X,              &
     &   'OBS NO.',2X,'BLOCK'/1X,'YYMMDD HHMM SEC-UTC-',A1)

          WRITE(6,10400,IOSTAT=IERR)                                    &
     &                IYMD,IHM,SEC,OBS1,RESID(1),                       &
     &                RATIO(1),SIGMA(1), KNTOBS,KNTBLK
10400 FORMAT(1X,I6,I5,F10.6,A8,F15.6,F12.4,1X,F12.4, 6X,                &
     &       I9,I8)

      NM=1
      NMWTD=1
!***********************************************************************
! SUM OBSERVATION AND RESIDUAL STATISTICS
!
      SIGMA(1)=RESID(1)/SQRT(OBSSIG(1))
      CALL SMSTAT  (AA(KTMEAN),AA(KTRMS ),AA(KWMEAN),AA(KWTRMS),        &
     &   AA(KWTRND),AA(KPRVRT),AA(KTYMEA),AA(KTYRMS),AA(KWTMTY),        &
     &   AA(KWTYRM),II(KNOBST),II(KNOBWT),II(KNOBTY),II(KNOBWY),        &
     &   LL(KLGPRV),RESIDU    ,NM        ,SIGMA     ,RATIO     ,        &
     &   NMWTD     ,NTYPE     ,ISTATS    )

      ELEVSC(1)=0.D0
      DKEY=DBLE(MKEY)

      IF(LBINRI) CALL BINLEN33(AA,II,DKEY)
      IF(LLOCRI) THEN
      CALL CONHD
        WRITE(IUNT19)    ZERO,ZERO,ZERO,                                &
     &                   XBOUNCE(1),XBOUNCE(2),XBOUNCE(3),              &
     &                   ZERO,ZERO,ZERO
        WRITE(IUNT19)    OBSTIM,                                        &
     &                   XSM(1,1),XSM(1,2),XSM(1,3),                    &
     &                   VSM(1,1),VSM(1,2),VSM(1,3)

      ENDIF
      IF(LBINRI) THEN
        CALL BINRDR(AA,II,MJDSBL,OBSTIM,EDTSIG,RESID,          &
     &           AA(KTPRTL),AA(KTHG),ELEVSC,NELEVS,LEDIT,RESIDU,NM,     &
     &           AA(KXUTDT))
      ENDIF

      IF(LODRI) THEN
         CALL BOD(AA,II,NM)
      ENDIF

!***********************************************************************
 9600 CONTINUE
      KIMBST=KIMBST+1
      LIMCALL=.FALSE.
      LIMAT  =.FALSE.
      LIMCAM =.FALSE.

      RETURN
!
      END
