!$INITG
      SUBROUTINE INITG(AA,II,LL,PARMV,PARMVC,IPTRUA,IGPC,IGPS,INDBUF,   &
     &                 LVLBI)
!********1*********2*********3*********4*********5*********6*********7**
! INITG            00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION: INITIALIZE GLOBAL PARAMETERS AT THE BEGINNING OF EACH GLOBAL
!           ITERATION
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL DATA
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL DATA
!   PARMV    I    A    PARAMETER VALUES ARRAY
!   PARMVC   O    A    CURRENT VALUES FOR ALL ADJUSTED PARAMETERS
!   IPTRUA   I    A    POINTER FROM PARAMETER ARRAY (PARMV) TO ADJUSTED
!                      PARAMETER ARRAY (PARMVC).
!   IGPC     I    A    DEGREE AND ORDER OF GLOBAL GEOPOTENTIAL C COEF.
!   IGPS     I    A    DEGREE AND ORDER OF GLOBAL GEOPOTENTIAL S COEF.
!   INDBUF   O    A    INDICES OF OPEN OBSERVATION BUFFERS.
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CGVTMI/NCDT,NSDT,NCPD,NSPD,NCDTA,NSDTA,NCPDA,NSPDA,NGRVTM, &
     &       KCDT,KCPDA,KCPDB,KSDT,KSPDA,KSPDB,KOMGC,KOMGS,KCOMGC,      &
     &       KSOMGC,KCOMGS,KSOMGS,NXGVTI
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CITERM/MAXINR,MININR,MAXLST,IHYPSW,NXITER
      COMMON/CITERG/MARC,MGLOBL,MGLOBM,                                 &
     &              MGLOCV,NXITRG
      COMMON/CLGVTM/LGVTM,LDPM,LGVTPM,LOPT,LCSDPM,L_MP_IERS2003,        &
     &              L_CS_IERS2003,L_MP_IERS2010,L_CS_IERS2010
      COMMON/CNORMI/NRECDF,NRECDH,INDREC,MPTS  ,NPTS  ,NPLEFT
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/COREPH/EMJDS0(2),EFSEC0(2),EMODE(2),ECORR(2),              &
     &              PSTAE0(12),DEBC(12),SGMEBC(12),BODYID(2),XCOEPH
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CPARFI/IUNPF1,IUNPF2,IUNPFI,ISZPFI,NBLKPF,NWRDPF,MTCALL(4)
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPARTI/MAXLP ,KORSIZ,MAXWRK,                               &
     &              IUNTP1,IUNTP2,IUNTPF,ISIZPF,IRECPF,NRECPF,          &
     &              NPDONE,NP1   ,NP2   ,NRECND,NPDIM ,NXPARI
      COMMON/CSTATA/RMSTOT,RMSEDT,RMSGLB
      COMMON/CSTATI/NOBTOT,NOBWTD,NAPTOT,NCUTOF
      COMMON/CTMGDN/LTMGDN
      COMMON/DYNPOL/DPMEP ,DPMXP ,DPMYP ,DPMXDT,DPMYDT,DPMOPT,DPMXPC,   &
     &              DPMYPC,DPMKF ,DPMC21,DPMS21,DPMPD ,DPMUDK,DPMVDK,   &
     &              DPMOCP,DPMNLD,DPMERS,XDYNPL
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/GBINRL/LBINRG,NXGBIN
      COMMON/GEODEG/NMAX,NMAXP1,NP,NTOLD,NTOLO,NADJC,NADJS,NADJCS,      &
     &              NPMAX,NXGDEG
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/LASTER/LASTR(2),LBINAST,NXASTR
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/LEPHM2/LXEPHM
      COMMON/LOLOAD/LOLMD,LOLAJ,L2FOLT,LAPLOD
      COMMON/NALOAD/NSITES,NALFIL,NALSIT,MAXSIT,ITOTAL,MAXAPL,ITAPLB,   &
     &              ITAPLE,IAPLDT,NXLOAD
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/NUTINF/NNUT,NNUTAA,NXNUTA
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      COMMON/OLOADA/LXYZCO,LEOPTO
      COMMON/PARFIL/PFSW  ,PFUNT1,PFUNT2,PFNUMB,SEGSIZ,XPARFI
      COMMON/PLATE /NPLATE,MJDPLR,NPLTMS,NXPLAT
      COMMON/POLINF/NPOLE,NPOLEA,NUTA,MXUTC,NMODEL,NXPOLI
      COMMON/ROTELM/ALF020,ALFR20,DEC020,DECR20,W020,WR20,X100,WRR20,  &
     &               XR100,XA100,THXTGC2S(3),XROTLM
      COMMON/ROTEL2/ALF0202,ALFR202,DEC0202,DECR202,W0202,WR202,X1002, &
     &              WRR202,  &
     &               XR1002,XA1002,THXTGC2S2(3),XROTLM2
      COMMON/SSTPTR/KCBAR, KSBAR ,KCDOT ,KSDOT ,KCAPRD,KCBPRD,KSAPRD,   &
     &              KSBPRD,KCBARA,KSBARA,KCDOTA,KSDOTA,KCAPDA,KCBPDA,   &
     &              KSAPDA,KSBPDA,NSSTOT,NSSTDP
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/TOPSCL/SCDIRA,SCLNDM,PSCDRA,PSCLND
      COMMON/VLBI/NQUA,NADJQ,NADJQV,NQUAB,IYMDV,NVOPT,NXVLBI
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
      COMMON/XPCNT2/NXTRAC2,NXFLAG2,NXALLC2,NCPPER2,NMINRT2,NDPOR2,     &
     &              NXXTR2
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION IGPC(2,1),IGPS(2,1),IPTRUA(1),SCRTCH(3)
      DIMENSION PARMV(1),PARMVC(1)
      DIMENSION INDBUF(1)
!
      DATA ZERO/0.D0/
      DATA ONE/1.0D0/
      DATA THREE/3.0D0/
!
!**********************************************************************
! START OF EXECUTABLE CODE
!**********************************************************************
!
!
! CLEAR THE SUPPLEMENTRY EPHEMERIS BUFFER IF APPLICABLE
      KL=MAXDEG*ICBODY*2
      IF(ISUPL.EQ.1) CALL CLEARA(AA(KEPHMS),KL)
! CLEAR ESTIMATION SUMMATION ARRAYS
      CALL CLEARA(AA(KSUM1),MAXWRK)
      CALL CLEARA(AA(KSUM2),MAPARM)
! CLEAR STATISTICAL SUMMATION ARRAYS
      CALL SUMCLR(AA,II,LL,.FALSE.)
      NAPTOT=0
      NCUTOF=0
      RMSTOT=ZERO
! INITIALIZE CENTRAL BODY FLAG
      IDXREP=ICBDGM-11
      IF(IDXREP.LE.0)IDXREP=1
      LEARTH=.FALSE.
      LEARTH=(ICBDGM.EQ.3.OR.IREPL(IDXREP).EQ.3)
      LMOON=.FALSE.
      LMOON=(ICBDGM.EQ.4.OR.IREPL(IDXREP).EQ.4)
      LMARS=.FALSE.
      LMARS=(ICBDGM.EQ.5.OR.IREPL(IDXREP).EQ.5)
! INITIALIZE PARTIAL DERIVATIVE FILE PARAMETERS
      IUNPF1=INT(PFUNT1)
      IUNPFI=IUNPF1
      IUNPF2=INT(PFUNT2)
      ISZPFI=INT(SEGSIZ)
      NBLKPF=0
      NWRDPF=0
      LPFEOF=.FALSE.
      LARCNU=.FALSE.
! INITIALIZE SUPPLEMENTARY EPHEMERIS FLAG
      LXEPHM=.FALSE.
      LXEPHM=ISUPL.EQ.1
! INITIALIZE TIME DEPENDENT GRAVITY AND DYNAMIC POLAR MOTION FLAGS
      LGVTM =NGRVTM.GT.0
      LDPM  =DPMOPT.GT.ZERO
      LGVTPM=LGVTM .OR. LDPM
      LOPT = DPMOCP .GT. 0

      ! DPMERS IS COLUMN 14 OF THE POLDYN CARD
      ! ... TRUE WHEN USING IERS2003 (LINEAR) MODEL FOR MEAN POLE
      ! ... (POLDYN COLUMN 14 = 0, 4, or 5)
      L_MP_IERS2003 = NINT(DPMERS) == 0 .OR. NINT(DPMERS) >= 4
      ! ... TRUE WHEN USING IERS2003 MODEL FOR C21/S21
      ! ... (POLDYN COLUMN 14 = 0 OR 1)
      L_CS_IERS2003 = NINT(DPMERS) <= 1
      ! ... TRUE WHEN USING IERS2010 MODEL FOR MEAN POLE
      ! ... (POLDYN COLUMN 14 = 1, 2, OR 3)
      L_MP_IERS2010 = NINT(DPMERS) >= 1 .AND. NINT(DPMERS) <= 3
      ! ... TRUE WHEN USING IERS2010 MODEL FOR C21/S21
      ! ... (POLDYN COLUMN 14 = 2, 3, 4, OR 5)
      L_CS_IERS2010 = NINT(DPMERS) >= 2

      LCSDPM = NINT(DPMERS) == 3 .OR. NINT(DPMERS) == 5

! INCREMENT GLOBAL ITERATION COUNT
      NGLOBL=NGLOBL+1
      LSTGLB=LSTGLB.OR.NGLOBL.GE.MGLOBL
      LSTARC=.FALSE.
      NARC=0
      INDREC=0
      IF(.NOT.LSTGLB) GO TO 1000
      IF(MBUF.LE.0) GO TO 1000
      DO 900 IBUF=1,MBUF
      INDBUF(IBUF)=IBUF
  900 END DO
 1000 CONTINUE
! LOAD GLOBAL PARAMETERS(PARMV) INTO CURRENT PARAMETER ARRAY(PARMVC)
      IF(NPVAL0(IXGLBL).LE.0) GO TO 1100
      IGLB =IPVAL(IXGLBL)
      IGLBE=IGLB+NPVAL(IXGLBL)-1
      DO 1050 J=IGLB,IGLBE
      IF(IPTRUA(J).LE. 0) GO TO 1050
      PARMVC(IPTRUA(J))=PARMV(J)
 1050 END DO
 1100 CONTINUE
!
! LOAD GLOBAL  PARAMETER VALUES INTO FORCE MODEL ARRAYS FOR:
!  K2,K2 PHASE AND K3 TIDES;EARTH & OCEAN TIDES
!  NOTE: GEOPOTENTIAL C,S COEFFICIENTS ARE LOADED IN INITA
!        OR IN INITI IF THE TIME DEPENDENT GRAVITY OPTION IS USED
      IBEG=IPVAL(IXTIDE)
      IEND=IPVAL(IXLOCG)-1
      IF(IEND.LT.IBEG) GO TO 1250
      JCNT=0
      DO 1200 J=IBEG,IEND
      AA(KSTID+JCNT)=PARMV(J)
      JCNT=JCNT+1
 1200 END DO
!
! LOAD GLOBAL  PARAMETER VALUES INTO FORCE MODEL ARRAYS FOR:
!  LOCAL GRAVITY;GM;AE;POLAR FLAT;EQUATORIAL FLAT;PLANETARY POS &VEL;
!  PLANETARY MOON GM VALUES
!
 1250 IBEG=IPVAL(IXLOCG)
      IEND=IPVAL(IXPMGM)-1
      IF(IEND.LT.IBEG) GO TO 1310
      JCNT=0
      DO 1300 J=IBEG,IEND
      AA(KLGRAV+JCNT)=PARMV(J)
      JCNT=JCNT+1
 1300 END DO
!
! LOAD PLANETARY MOON PARAMETERS
!
 1310 IBEG=IPVAL(IXPMGM)
      IEND=IPVAL(IXVLIT)-1
      IF(IEND.LT.IBEG) GOTO 1350
      JCNT=0
      DO 1320 J=IBEG,IEND
         AA(KPLMGM+JCNT)=PARMV(J)
         JCNT=JCNT+1
 1320 END DO
!
! LOAD GLOBAL GEOMETRIC PARAMETERS INTO PROPER ARRAYS FOR:
!  SPEED OF LIGHT; H2,L2 LOVE NO. ; X,Y POLE & UT1; BIASES;STA POS
!
! Was:
!
! 1350 IBEG=IPVAL(IXVLIT)
!      IEND=IPVAL(IXOLOD)-1
!      IF(IEND.LT.IBEG) GO TO 1450
!      JCNT=0
!      DO 1400 J=IBEG,IEND
!      AA(KSL+JCNT)=PARMV(J)
!      JCNT=JCNT+1
! 1400 CONTINUE
! Changed by LST
 1350 CONTINUE
      IF(NPVAL(IXVLIT).GT.0) AA(KSL)=PARMV(IPVAL(IXVLIT))
      IF(NPVAL(IXH2LV).GT.0) AA(KH2)=PARMV(IPVAL(IXH2LV))
      IF(NPVAL(IXL2LV).GT.0) AA(KL2)=PARMV(IPVAL(IXL2LV))
      IF(NPVAL(IXSTL2).LE.0)GO TO 1360
      IPL0= IPVAL(IXSTL2)
      KL0= KSTEL2
      DO 1354 I=1,NSTA
      IPL=IPL0 + I - 1
      KKL =KL0 + I - 1
      AA(KKL)=PARMV(IPL)
 1354 END DO
 1360 CONTINUE
      IF(NPVAL(IXSTH2).LE.0)GO TO 1390
      IPH0 = IPVAL(IXSTH2)
      KH0 = KSTEH2
      DO 1365 I=1,NSTA
      IPH=IPH0 + I - 1
      KKH =KH0 + I - 1
      AA(KKH)=PARMV(IPH)
 1365 END DO
!...................
 1390 IBEG=IPVAL(IXEPHC)
      IEND=IBEG+NPVAL(IXEPHC)-1
!
! IBEG WILL BE 1 LESS THAN END IF IXEPHC DOESN'T EXIST
!
      IF(IEND.LT.IBEG) GO TO 1410
      JCNT=1
      DO 1400 J=IBEG,IEND
      DEBC(JCNT)=PARMV(J)
      JCNT=JCNT+1
 1400 END DO
 1410 CONTINUE
      IBEG=IPVAL(IXEPHT)
      IEND=IBEG+NPVAL(IXEPHT)-1
!
! IBEG WILL BE 1 LESS THAN END IF IXEPHC DOESN'T EXIST
!
      IF(IEND.LT.IBEG) GO TO 1450
      JCNT=7
      DO 1420 J=IBEG,IEND
      DEBC(JCNT)=PARMV(J)
      JCNT=JCNT+1
 1420 END DO
 1450 CONTINUE


!  EOP PARAMETERS
      IBEG=IPVAL(IXPOLX)-1
      IBEGR=IPVAL(IXPXDT)-1
      IF(NPOLE.LE.0) GO TO 1470
      AA(KXPUT)=ZERO
      AA(KXPUT+1)=ZERO
      AA(KXPUT+2)=ZERO
      AA(KXDOTP)=ZERO
      AA(KXDOTP+1)=ZERO
      AA(KXDOTP+2)=ZERO
      IF(NPOLE.LE.1) GO TO 1470
      NPOLE1=NPOLE-1
      NP31=3*NPOLE1
      AA(KXPUT+NP31)=ZERO
      AA(KXPUT+NP31+1)=ZERO
      AA(KXPUT+NP31+2)=ZERO
      AA(KXDOTP+NP31)=ZERO
      AA(KXDOTP+NP31+1)=ZERO
      AA(KXDOTP+NP31+2)=ZERO
      NP32=NP31-3
      DO 1460 J=1,NP32
      AA(KXPUT+2+J)=PARMV(IBEG+3+J)-AA(KPUTBH+2+J)
      AA(KXDOTP+2+J)=PARMV(IBEGR+3+J)
      IF(MTYPE.EQ.31) AA(KXPUT+2+J)=0.D0
 1460 END DO
 1470 CONTINUE

! NUTATION PARAMETERS DPSI EPST
      GO TO  1472
      write(6,*)'  NUTATION PARAMETERS '
      write(6,*)'  #OF NUTATE CARDS  ',NNUT
      write(6,*)'  #OF ADJUSTED NUT  ',NNUTAA
      write(6,*)'  NPVAL  ',NPVAL(IXDPSI),NPVAL(IXEPST)
      write(6,*)'  NPVAL0 ',NPVAL0(IXDPSI),NPVAL0(IXEPST)
      write(6,*)'  IPVAL  ',IPVAL(IXDPSI),IPVAL(IXEPST)
      write(6,*)'  IPVAL0 ',IPVAL0(IXDPSI),IPVAL0(IXEPST)
      write(6,*)'  PARMV  ',PARMV(IPVAL(IXDPSI)),PARMV(IPVAL(IXEPST))
 1472 CONTINUE

      IF(NNUT.LE.0) GO TO 1495

!
      DO 1471 JJ=1,NNUT
      MJDSN= INT(AA(KNUTMD-1+JJ))
      FSECN=0.D0
      CALL BUFEAR(MJDSN,FSECN,MJDSN,FSECN,1,IDUM1,DUM1,LDUM1,AA,II)
      CALL PRECSS(MJDSN,FSECN,EF,ZF,TF,AA(KSRTCH),1)
      CALL NUVECT(MJDSN,FSECN,DPSI,EPST,EPSM,1,AA(KSRTCH))
!     write(6,*)' dbg DPSI, EPST  MID PT EPHEM ',DPSI,EPST,JJ
      AA(KDPSIE-1+JJ)=DPSI
      AA(KEPSTE-1+JJ)=EPST
1471  CONTINUE

      IBEG=IPVAL0(IXDPSI)
      IEND=IBEG+NPVAL0(IXDPSI)-1
      KK=1
      DO JJ=IBEG,IEND
      AA(KPDPSI-1+KK)=PARMVC(JJ)
!     write(6,*)' dbg DPSI ',AA(KPDPSI-1+KK),PARMVC(JJ),JJ
      KK=KK+1
      ENDDO

 1475 CONTINUE

      IBEG=IPVAL0(IXEPST)
      IEND=IBEG+NPVAL0(IXEPST)-1
      KK=1
      DO JJ=IBEG,IEND
      AA(KPEPST-1+KK)=PARMVC(JJ)
!     write(6,*)' dbg EPST ',AA(KPEPST-1+KK),PARMVC(JJ),JJ
      KK=KK+1
      ENDDO

 1485 CONTINUE
 1495 CONTINUE

! STATION POSTION
      IBEG=IPVAL(IXSTAP)
      IEND=IBEG+NPVAL(IXSTAP)-1
      IF(IEND.LE.IBEG) GO TO 1550
      JCNT=0
      DO 1500 J=IBEG,IEND
      AA(KSPCRD+JCNT)=PARMV(J)
      JCNT=JCNT+1
 1500 END DO
 1550 CONTINUE
!
!  NOTE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! BISASES NEED MORE CODE
!  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! COMPUTE DENORMALIZATION FACTORS FOR ESTIMATED GLOBAL C,S COEFFICIENTS
!
      IF(NPVAL0(IXGPC).LE. 0) GO TO 1700
      NGP=NPVAL0(IXGPC)
      INDXGP=KGPNRM-1
      DO 1650 I=1,NGP
      N=IGPC(1,I)
      M=IGPC(2,I)
      AA(INDXGP+I)=DENORM(N,M)
 1650 END DO
 1700 IF(NPVAL0(IXGPS).LE. 0) GO TO 1800
      NGP=NPVAL0(IXGPS)
      INDXGP=KGPNRM-1+NPVAL0(IXGPC)
      DO 1750 I=1,NGP
      N=IGPS(1,I)
      M=IGPS(2,I)
      AA(INDXGP+I)=DENORM(N,M)
 1750 END DO
 1800 CONTINUE
!
! INITIALIZE ARRAYS AND POINTERS FOR TIME DEPENDENT GRAVITY AND
! DYNAMIC POLAR MOTION
      IF(LGVTPM ) CALL GRVINI(II(KIGTSR),PARMV,II(KIPTC),II(KIPTS),     &
     &    AA(KCSAVE),AA(KSSAVE),AA(KCGRVT),AA(KSGRVT),II(KPTRUA),       &
     &    AA(KCN),AA(KSN))
!
! INITIALIZE ARRAYS AND POINTERS FOR TIME INDEPENDENT (MEAN)
! SEA SURFACE TOPOGRAPHY C AND S COEFFICIENTS
      IF(NSSTOT.GT.0) THEN
       CALL SSTCS1(II(KSSTNM),PARMV,AA(KSSTCC),AA(KSSTSS))
      ENDIF
!
! DEFINE CONSTANTS
!
      CALL DCOMFL(AA)
! COMPUTE DERIVED EARTH CONSTANTS
      CALL EARTHC()
! INITIALIZE LOCAL GRAVITY
!     CALL UPDLG(II(KMAPLG),PARMVC,AA(KPARLG),AA(KSINCO))
! COMPUTE DERIVED PLANETARY CONSTANTS IN CASE OF AN INTERPLANETARY RUN
      IF(ICBDGM.NE.ITBDGM) CALL BODYC(PARMV(IPVAL(IXXTRO)+5))
! COMPUTE CARTESIAN STATION LOCATIONS ON FIRST OUTER
!     IF(NGLOBL.GT.1) GO TO 1960
      IF(NGLOBL.GT.1) GO TO 1955
      IF(NMSTA.LT.1) GO TO 1950
! LOAD STATION SIGMAS
      ISTASS=IPVAL0(IXSTAP)-1
      DO 1900 I=1,NMSTA
      ISTAS=ISTASS+(I-1)*3
      ICRD=II(KICRD+I-1)/10-1
      JSTAS=KSPSIG+(I-1)*18+ICRD*6
      JKSTAS=KPARVR+ISTASS+(I-1)*3
      JJSTAS=KSTACV+(I-1)*3
      AA(JSTAS)=AA(JKSTAS)
      AA(JSTAS+1)=AA(JJSTAS)
      AA(JSTAS+2)=AA(JJSTAS+1)
      AA(JSTAS+3)=AA(JKSTAS+1)
      AA(JSTAS+4)=AA(JJSTAS+2)
      AA(JSTAS+5)=AA(JKSTAS+2)
      CALL DSINV(AA(JSTAS),3,3,SCRTCH)
 1900 END DO
 1950 CONTINUE
      CALL STACRD(II(KICRD),II(KICON),II(KISTNO),AA(KSTNAM),AA(KSPCRD), &
     &            AA(KSPSIG),AA(KSXYZ),AA(KDXSDP),AA(KDPSDP),AA(KSTAIN),&
     &            AA(KXLOCV),AA(KSPWT),AA(KPLTIN),AA(KPLTVL),AA(KPLTDV))
      IF(NPLATE.GT.0.AND.NPLTMS.GT.0) CALL PLTPRT(II(KISTNO),AA(KSTNAM),&
     &      AA(KSXYZ),AA(KPLTIN),AA(KPLTVL),II(KMJDPL))
      ISTASS=IPVAL0(IXSTAP)
!TVM  CALL BSLINE(1,II(KICRD),II(KICON),II(KISTNO),AA(KSTNAM),
!TVM .            ISTASS,MAPARM,AA(KSPSIG),AA(KSXYZ),AA(KDXSDP),
!TVM .            AA(KSUM1))
 1955 CONTINUE
      LAPLOD=ITOTAL.GT.0
      LOLMD=NPVAL(IXOLOD).GT.0
      LXYZCO=.FALSE.
      LEOPTO=.FALSE.
      IF(LOLMD) CALL OLODCF(AA(KABCOF),AA(KXLOCV),                      &
     &    II(KNDOLM),II,II(KKIOLM),II(KIPVOL),AA(KSTAIN),PARMV,         &
     &    AA(KANGFC),AA(KPNAME))
 1960 CONTINUE
      IF(LBINRG.AND.LSTGLB) CALL GLBBHD
      IF(LBINRG.AND.LSTGLB) CALL STABHD(II(KISTNO),AA(KSTNAM),          &
     &                      AA(KSXYZ),AA(KSTAIN))
      IF (LVLBI) CALL INIVLB(PARMV,AA(KQUINF))
!     IF(NGLOBL.EQ.1.AND.NPVAL(IXXTRO).GT.0) THEN
      IF(NPVAL(IXXTRO).GT.0) THEN
      LAX=.FALSE.
      IF(NPVAL0(IXXTRO).GT.0) LAX=.TRUE.
! INITIALIZE PLANDX
      INDX=KPLNDX-1
      NEND=7+NXALLC
      DO 1970 I=1,NEND
      AA(KPLNDX+I)=0.D0
 1970 END DO
      LFLAG=.FALSE.
      IF(NGLOBL.GT.1)LFLAG=.TRUE.
         IPT1=IPVAL(IXXTRO)
         IPT2=IPVAL0(IXXTRO)
         CALL LPLNOP(PARMV(IPT1),PARMVC(IPT2),AA(KPRMV0-1+IPT2),        &
     &                II(KMJDSC),LFLAG,AA(KACOFW),AA(KBCOFW),AA(KANGWT),&
     &                AA(KPLNDX),AA(KPLANC),AA(KPPER),LAX)
      ENDIF
! INITIALIZE CTMGDN
      LTMGDN=.TRUE.
! INITIALIZE SOLID EARTH TIDE WORKING PARAMETER ARRAYS
! AND COMMON BLOCKS
      CALL USETDP(PARMV,AA(KPRMFS))

      IF(NPVAL0(IXXTRO).GT.0) THEN
      ! INITIALIZE PLANOR PARAMETERS
      FSDIN0 = T0XTRO + (TMGDN2-30000.D0) * 86400.D0
      ALFR20 = PARMVC(IPVAL0(IXXTRO)-1 + 2)
      ALF020 = PARMVC(IPVAL0(IXXTRO)-1 + 1) - FSDIN0*ALFR20
      DECR20 = PARMVC(IPVAL0(IXXTRO)-1 + 4)
      DEC020 = PARMVC(IPVAL0(IXXTRO)-1 + 3) - FSDIN0*DECR20
      WR20 = PARMVC(IPVAL0(IXXTRO)-1 + 6)
      X100 = MODULO(WR20*86400.D0*100.D0, TWOPI)
      WRR20 = PARMVC(IPVAL0(IXXTRO)-1 + 7)
      XTIME = MOD(FSDIN0, 8640000.D0)
      XTM100 = FLOOR((FSDIN0 - XTIME + 1.D0) / 8640000.D0)
      XA100 = MOD(XTM100*X100, TWOPI)
      XAREST = MOD(XTIME*WR20, TWOPI)
      XRESTR = MOD((XTIME**2)*WRR20, TWOPI)
      W020 = PARMVC(IPVAL0(IXXTRO)-1 + 5) - XA100 - XAREST - XRESTR
      W020 = MODULO(W020, TWOPI)
      THXTGC2S(1) = MODULO(PARMVC(IPVAL0(IXXTRO)-1 + 5), TWOPI)
      THXTGC2S(2) = WR20
      THXTGC2S(3) = WRR20

        IF(LBINAST)  THEN
!       INITIALIZE PLANOR PARAMETERS FOR BINARY STAR
! K IS WHERE THE PARAMETERS FOR THE SECOND BODY BEGIN
        K=NXALLC*2+7
        FSDIN02 = T0XTRO2 + (TMGDN2-30000.D0) * 86400.D0
        ALFR202 = PARMVC(IPVAL0(IXXTRO)-1 + 2 + K)
        ALF0202 = PARMVC(IPVAL0(IXXTRO)-1 + 1 + K) - FSDIN02*ALFR202
        DECR202 = PARMVC(IPVAL0(IXXTRO)-1 + 4 + K )
        DEC0202 = PARMVC(IPVAL0(IXXTRO)-1 + 3 + K) - FSDIN02*DECR202
        WR202   = PARMVC(IPVAL0(IXXTRO)-1 + 6 + K)
        X1002   = MODULO(WR202*86400.D0*100.D0, TWOPI)
        WRR202  = PARMVC(IPVAL0(IXXTRO)-1 + 7+ K)
        XTIME2  = MOD(FSDIN02, 8640000.D0)
        XTM1002 = FLOOR((FSDIN0 - XTIME + 1.D0) / 8640000.D0)
        XA1002  = MOD(XTM1002*X1002, TWOPI)
        XAREST2 = MOD(XTIME2*WR202, TWOPI)
        XRESTR2 = MOD((XTIME2**2)*WRR202, TWOPI)
        W0202   = PARMVC(IPVAL0(IXXTRO)-1 + 5 + K)-XA1002-XAREST2-XRESTR2
        W0202   = MODULO(W0202, TWOPI)
        THXTGC2S2(1) = MODULO(PARMVC(IPVAL0(IXXTRO)-1 + 5 + K), TWOPI)
        THXTGC2S2(2) = WR202
        THXTGC2S2(3) = WRR202
        ENDIF
      ENDIF
!
! FIGURE OUT SCALES fOR TOPOGRAPGY IN ALTIMETRY AND LANDMARK DATA
!!!!!!!   SCDIRA,SCLNDM,PSCDRA,PSCLND
      SCDIRA=1.D0
      SCLNDM=1.D0
      PSCDRA=0.D0
      PSCLND=0.D0
!!!   IF(NPVAL(IXFGGM).EQ.1) THEN
!!!     SCDIRA=PARMV(IPVAL(IXFGGM))
!!!     SCLNDM=PARMV(IPVAL(IXFGGM))
!!!   ENDIF
!!!   IF(NPVAL0(IXFGGM).EQ.1) THEN
!!!     PSCDRA=DFLOAT(IPVAL0(IXFGGM))
!!!     PSCLND=DFLOAT(IPVAL0(IXFGGM))
!!!   ENDIF
!
      RETURN
      END
