!$INITI
      SUBROUTINE INITI(AA,II,LL,PARMV,PARMVC,IPTRUA,IGPCA,IGPSA,        &
     &   IELMTP,IPTC,IPTS,CSAVE,SSAVE,C,S,PNAME,LSTNRO)
!********1*********2*********3*********4*********5*********6*********7**
! INITI            00/00/00            0000.0    PGMR - ROWLANDS
!                  84/04/02            0000.0    PGMR - EDDY
!
! FUNCTION:  SET ITERATION FLAGS AND INITIALIZE VARIABLES AND
!            ARRAYS FOR THIS ITERATION
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL    DATA
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL DATA
!   PARMV    I    A    ARRAY OF ALL PARAMETER VALUES
!   PARMVC   O    A    CURRENT VALUES FOR ALL ADJUSTED PARAMETERS
!   IPTRUA   I    A    POINTER FROM PARAMETER ARRAY (PARMV)
!                      TO ADJUSTED PARAMETER ARRAYS (PARMVC)
!   IGPCA    I    A    DEG&ORDER FOR ARC GEOPOTENTIAL C COEF.
!   IGPSA    I    A    DEG&ORDER FOR ARC GEOPOTENTIAL S COEF.
!   IELMTP  I/O   A    INDICATOR FOR SAT ADJUSTMENT
!                        1 - CARTESIAN
!                        2 - KEPLER
!                        3 - N.S. KEPLER
!   IPTC    I/O   A    POINTERS TO ARRAY THAT CONTAINS C COEFFICIENTS.
!   IPTS    I/O   A    POINTERS TO ARRAY THAT CONTAINS S COEFFICIENTS.
!   CSAVE   I/O   A    POINTERS FOR SAVING PREVIOUS C COEFFIENTS FOR
!                      TIME DEPENDENT GRAVITY
!   SSAVE   I/O   A    POINTERS FOR SAVING PREVIOUS S COEFFICIENTS FOR
!                      TIME DEPENDENT GRAVITY
!   C       I/O   A    GEOPOTENTIAL C COEFFICIENTS.
!   S       I/O   A    GEOPOTENTIAL S COEFFICIENTS.
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      CHARACTER*8 CARDT
      SAVE
!
      COMMON/LIMAGE/LIMG,LIMCALL,LIMAT,LIMCAM
      COMMON/ADJGEO/LADATT,LADEBS,LADABS,LADGBS,LADLOV,LADPOL
      COMMON/ALBINT/IRINGS,ISPOTS,IMAXA,IMAXE,MMAXA,MMAXE,KMAXA,KMAXE,  &
     &              KALB,KEMM,KLMOD,IMODEL,NPNALB,NXALBI
      COMMON/ALTIDQ/NNAQM
      COMMON/ATTCBD/BATPER,ATTPRT
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/BSPHRE/DXMDN(3,3,2),DXBDN(3,3,2)
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/BWREAL/SHADOW(2),SUNPCT,SCAREA,SCMASS,BWMEAN
      COMMON/C12PRM/IDSATS(10,2),IP1,IP2,NXC12P
      COMMON/CHCFFX/COEFFX1(3,25,11),COEFFXX(3,25,988),TIMBCHEB
      COMMON/CALTOP/LADYNO,LAGEOO,LRGEOT,LRETDT,LROTDT,LRSSTT,LCOTRM,   &
     &              LFILOT,LATCOR,LFIRIT,LX1ALT,LX2ALT,LMSSWG,LATMOD,   &
     &              LG1BOT,LG1B,LONEG1,LXATTD,LXBEAM,NXALTO
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CEBARC/NEBIAS,NBIASE,NXCEBA
      COMMON/CEDIT /EDITX ,EDTRMS,EDLEVL,CONVRG,GLBCNV,EBLEVL,EDITSW,   &
     &              ENPX  ,ENPRMS,ENPCNV,EDBOUN,FREEZI,FREEZG,FREEZA,   &
     &              XCEDIT
      COMMON/CEDITL/LNEDIT
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CGVTMI/NCDT,NSDT,NCPD,NSPD,NCDTA,NSDTA,NCPDA,NSPDA,NGRVTM, &
     &       KCDT,KCPDA,KCPDB,KSDT,KSPDA,KSPDB,KOMGC,KOMGS,KCOMGC,      &
     &       KSOMGC,KCOMGS,KSOMGS,NXGVTI
      COMMON/CGVTMR/EPGVTM,ELAPGT,XCGVTR
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CITERM/MAXINR,MININR,MAXLST,IHYPSW,NXITER
      COMMON/CITERG/MARC,MGLOBL,MGLOBM,                                 &
     &              MGLOCV,NXITRG
      COMMON/CKOUNT/KNTBLK,KSEGMN,KNTOBS,KZROBS
      COMMON/CLGVTM/LGVTM,LDPM,LGVTPM,LOPT,LCSDPM,L_MP_IERS2003,        &
     &              L_CS_IERS2003,L_MP_IERS2010,L_CS_IERS2010
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CNORML/LNORM ,LNORMP
      COMMON/CON2E/KCNBST0,KCNBST1,KBUP110,KBUP111,KBPA110,KBPA111,KDIST&
     &            ,KDSIG
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CSIML/LSIMTI
      COMMON/CSTATI/NOBTOT,NOBWTD,NAPTOT,NCUTOF
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA05/KOBTYP,KDSCRP,KGMEAN,KGLRMS,KWGMEA,KWGRMS,KTYMEA,   &
     &       KTYRMS,KWTMTY,KWTYRM,KTMEAN,KTRMS ,KWMEAN,KWTRMS,KWTRND,   &
     &       KPRVRT,KEBSTT,KVLOPT,NXCA05
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORBNF/MAXINF,NORBNF,INFSTA(15),INFNDX(15),INFSTR,INFSTP,  &
     &              INFRT ,NXCORB
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI05/KNOBGL,KNOBWG,KNOBTY,KNOBWY,KNOBST,KNOBWT,KNEBOB,   &
     &              KJSTAT,NXCI05
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL06/KLBIAS,KLADEL,NXCL06
      COMMON/CPARFI/IUNPF1,IUNPF2,IUNPFI,ISZPFI,NBLKPF,NWRDPF,MTCALL(4)
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPARTI/MAXLP ,KORSIZ,MAXWRK,                               &
     &              IUNTP1,IUNTP2,IUNTPF,ISIZPF,IRECPF,NRECPF,          &
     &              NPDONE,NP1   ,NP2   ,NRECND,NPDIM ,NXPARI
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CREFMT/REFMT(9)
      COMMON/CRESPR/LRESPA,LRESPG,LRESPD,LRESPP,LRESPT
      COMMON/CRM5OE/RM5OE(9)
      COMMON/CTIDES/NTIDE,NSTADJ,NET,NETADJ,NETUN,NOT,NOTADJ,           &
     &   NOTUN ,NETUNU,NETADU,NOTUNU,NOTADU,NBSTEP,KTIDA(3),            &
     &   ILLMAX,NUNPLY,NNMPLY,NDOODN,MXTMRT,NRESP ,NXCTID
      COMMON/CTIMEA/FSECT
      COMMON/CTIMEI/MJDST
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/DYNPOL/DPMEP ,DPMXP ,DPMYP ,DPMXDT,DPMYDT,DPMOPT,DPMXPC,   &
     &              DPMYPC,DPMKF ,DPMC21,DPMS21,DPMPD ,DPMUDK,DPMVDK,   &
     &              DPMOCP,DPMNLD,DPMERS,XDYNPL
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/GEDIT/NGOBS
      COMMON/GEODEG/NMAX,NMAXP1,NP,NTOLD,NTOLO,NADJC,NADJS,NADJCS,      &
     &              NPMAX,NXGDEG
      COMMON/KIX/KINDXC
      COMMON/IMAG2E/KXIMG,KIMBST,KIMOBL,KIMBUP,KIMBPA
      COMMON/LBTYPE/LCLOCK
      COMMON/LDUAL/LASTSN,LSTSNX,LSTSNY
      COMMON/LOLOAD/LOLMD,LOLAJ,L2FOLT,LAPLOD
      COMMON/LTOTCR/LEDCR(100000)
      COMMON/LYARKO/LYARK,LTYP1,LTYP2,LMOD1,LMOD2,LYSHAD,LYE1,LSUN
      COMMON/NEWCON/XOK0,XNOK0
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/NQTRK/NQHOLD
      COMMON/NTOTCR/NTCR,NWCR
      COMMON/NUTINF/NNUT,NNUTAA,NXNUTA
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      COMMON/PARFIL/PFSW  ,PFUNT1,PFUNT2,PFNUMB,SEGSIZ,XPARFI
      COMMON/PLMINI/ IYMDP0(5),IHMP0(5),MJDP0(5),IMNUNT(5)
      COMMON/PLMINR/ RMNMIN(5),SECP0(5),FSECP0(5),                      &
     &               XMNCHG(5),XINT(5),XJDT1(5),XJDT2(5),               &
     &               XKEP1(6,5),XKEP2(6,5)
      COMMON/SAVEIM/RIM(3,3),SBF1(3,3),SBF2(3,3),SBF3(3,3),SBF4(3,3),   &
     &       SCF2(3,3),SCF3(3,3),SCF4(3,3),RKEY
      COMMON/POLINF/NPOLE,NPOLEA,NUTA,MXUTC,NMODEL,NXPOLI
      COMMON/RAPIDI/LINTF,LBUFOP
      COMMON/REFDRV/DREFDA(9),DREFDB(9),DR3TDW(9),RDATR(9),RDBTR(9),    &
     &              DDA(9,2,50),DDB(9,2,50),DDR(9,50)
      COMMON/RMSCR/RMSTCR,RMSWCR,RMSRCR,RMSPCR
      COMMON/SETADJ/LSADRG(4),LSASRD(4),LSAGA(4),LSAGP,LSATID,LSAGM,    &
     &              LSADPM,LSAKF,LSADNX,LSADJ2,LSAPGM
      COMMON/ SPLINC/ INDSP,INDTSP,INDTNO,INDTEA
      COMMON/STPTHG/COSSTG,SINSTG
      COMMON/THERMD/DRGSAT,DTHSC,ZETA,SPAXT,SPAXL,THRMFL,XTHERM
      COMMON/TIDTIM/FSCFR1,FSCFR2,FSCMS1,FSCMS2
      COMMON/TOPEXA/BETAP,PRVBET,SOMEGA,PRVOMG,YAWANG,SGAMMA,           &
     &              BETAMX,TDLOUV(8,3)
      COMMON/TOPEXL/LTOPX1,LRAMP,LRDOWN,LRUP,LFIX0,LFIX90,LSIN,LTXPRT
      COMMON/TPARM/MTPARM,MTPRM1,IPS51,IPS52,MTOBS,IT2PRM(2,28000)
      COMMON/TPGRAV/NTPGCU,NTPGCA,NTPGSU,NTPGSA,ITPGRV,NTIMEC,NTIMES,   &
     &              NXTPGR
      COMMON/TRAJI/MJDSTR,NTRAJC,MTRAJC,NXTRAJ
      COMMON/TRAJL/LTRAJ
      COMMON/VMATFL/LVMTF,LVMTFO
      COMMON/XOVER /KXKNT,KXBST,KXOBL,KXBUP,KXBPA,IAPLSC,IAPLL
      COMMON/XOVERS/NRXTOT,NXBLK,NUSIDE,NDEGX2,NDEGXX,NUCON,ITERNU,     &
     &              IPEDIT,IDEDIT,NXXOVR
      COMMON/XPARMB/MPARMB,NPARMB,MPOBS,JPAMB,ISKIPE,                   &
     &             ITPARM(5,28000),ISTABP(3,28000),                     &
     &             ISATBP(3,28000),IPRMBF(28000)
      COMMON/YARSCH/YARTYP,YARMOD,AYAR,TAU,RISYEN,FSEYEN,RISYEX,FSEYEX, &
     &              SMEANM,XYARMD
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION PARMV(1),PARMVC(1),PK(6)
      DIMENSION IGPCA(2,1),IGPSA(2,1),IPTRUA(1),IELMTP(1)
      DIMENSION IPTC(1),IPTS(1),CSAVE(1),SSAVE(1),C(6),S(6)
      DIMENSION R3THG(9)
      DIMENSION FMAT(9),HMAT(9)
      DIMENSION P1(6),P2(6),Q1(6),Q2(6)
      DIMENSION PNAME(2,1)
!
      EQUIVALENCE(CARD,CARDT)
!
      DATA ZERO/0.0D0/,ONE/1.0D0/
!
      INDXNO(I)=MAPARM*(I-1)-(I*(I-1))/2
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! UPON ENERING THIS ROUTINE IF LSTINR IS FALSE AND LSTNRO IS TRUE
! THEN A TRAJECTORY FILE ONLT ITERATION IS ABOUT TO BEGIN
! IN THIS CASE BOTH LSTINR AND LSTNRO WILL BE TRUE UPON EXIT
! ON TRAJECTORY ONLY ITERATIONS DO NOT ZERO NORMAL EQ
!
      LZNRM=.TRUE.
      IF(.NOT.LSTINR.AND.LSTNRO) LZNRM=.FALSE.
!
      NBURN=NPVAL(IXBURN)/25
      IF(NBURN.GT.0) THEN
        DO I=1,NBURN
         II(KBRAX3-1+I)=0
        ENDDO
      ENDIF
      DO KK=1,3
      DO JJ=1,3
      SBF2(KK,JJ)=0.D0
      SBF3(KK,JJ)=0.D0
      SBF4(KK,JJ)=0.D0
      SCF2(KK,JJ)=0.D0
      SCF3(KK,JJ)=0.D0
      SCF4(KK,JJ)=0.D0
      ENDDO
      ENDDO
      DO KK=1,3
      DO JJ=1,3
      SBF2(KK,KK)=1.D0
      SBF3(KK,KK)=1.D0
      SBF4(KK,KK)=1.D0
      SCF2(KK,KK)=1.D0
      SCF3(KK,KK)=1.D0
      SCF4(KK,KK)=1.D0
      ENDDO
      ENDDO

!  INITIALIZE TIMEBCHEB
      TIMBCHEB=-99.D0


!     INITIALIZE THE LIMAGE FLAGS
      LIMCALL=.FALSE.
      LIMAT  =.FALSE.
      LIMCAM =.FALSE.
      INDSP=1
      INDTSP=1
      INDTNO=1
      INDTEA=1
      L12=.FALSE.
      NINNER=NINNER+1
      IF(NINNER.GE.MAXINR.AND..NOT.LOBS) LSTNRO=.TRUE.
      LITER1=NINNER.EQ.1.AND.NGLOBL.EQ.1

!  MININUM NUMBER OF OBS PER AMBIGUITY BIAS
      MPOBS=4
!  MINIMUM NUMBER OF OBS PER TROP PASS
      MTOBS=4
!
! FIND STARTING LOCATION AND NUMBER OF TROP BIASES
      MTPARM=0
      IF(NPVAL(IXBISA).LE.0) GO TO 2
      IQP1=IPVAL(IXBISA)
      IQP2=IQP1-1+NPVAL(IXBISA)
      L1=.TRUE.
      DO 1 IQP=IQP1,IQP2
      CARD=PNAME(1,IQP)
!      IF(CARDT(1:4).NE.'B500') GO TO 1
      IF(CARDT(1:2).NE.'B5') GO TO 1
      IF(L1) MTPRM1=IQP
      L1=.FALSE.
      MTPARM=1+IQP-MTPRM1
    1 END DO
      MTPRM1=IPTRUA(MTPRM1)
    2 CONTINUE
!  INITIALIZE THE ARRAYS THAT TRACK THE HEALTH OF AMBIGUITY
!  AND TROP BIASES
      DO I=1,28000
        ITPARM(4,I)=0
        IT2PRM(1,I)=0
        IF(LITER1) IT2PRM(2,I)=1
        IF(LITER1) ITPARM(5,I)=1
      ENDDO
!
! SET THE YARKOVSKY MODEL LOGICALS
      LYARK=.FALSE.
      LMOD1=.FALSE.
      LMOD2=.FALSE.
      LTYP1=.FALSE.
      LTYP2=.FALSE.
      LYSHAD=.FALSE.
      LYE1  =.TRUE.
      LSUN  =.FALSE.

      IF(YARTYP.EQ.0.D0) GO TO 4
      LYARK=.TRUE.
      IF(YARTYP.EQ.1.D0)THEN
      LTYP1=.TRUE.
      ELSE
      LTYP2=.TRUE.
      ENDIF

      IF(YARMOD.EQ.1.D0) THEN
      LMOD1=.TRUE.
      ELSE
      LMOD2=.TRUE.
      ENDIF

    4 CONTINUE

! INITIALIZE  THE DXMDN DXBDN ARRAYS (12 PARAMETER CASE)
      DO 6 IJ=1,2
       DO 5 KK=1,3
       DXMDN(KK,KK,IJ)=1.D0
       DXBDN(KK,KK,IJ)=1.D0
    5 END DO
    6 END DO

! ZERO OUT ARRAY THAT HOLDS CURRENT VALUE OF PHASE WINDUP FOR EACH PASS
      IF(NAMBB.GT.0) THEN
        NUP=4*NAMBB
        DO IQP=1,NUP
          AA(KPYSQH-1+IQP)=0.D0
        ENDDO
      ENDIF
!
!
      XOK0=0.D0
      XNOK0=0.D0
      NTCR=0
      NWCR=0
      IF(NPVAL0(IXRSEP).GT.1) THEN
         WRITE(6,78912)
         WRITE(6,78913)
         WRITE(6,78914)
         WRITE(6,78915)
         STOP
      ENDIF
      IF(NPVAL0(IXRSEP).EQ.1) THEN
        IP0=IPVAL0(IXRSEP)
        IP=IPVAL(IXRSEP)
        PARMV(IP)=AA(KPRMV0-1+IP0)
        PARMVC(IP0)=AA(KPRMV0-1+IP0)
        AA(KPRMVP-1+IP0)=AA(KPRMV0-1+IP0)
      ENDIF
      IF(NINNER.EQ.1) RMSWCR=10000.D0
      RMSPCR=RMSWCR
      RMSTCR=0.D0
      RMSWCR=0.D0
      RMSRCR=0.D0
      NGOBS=0
      KZROBS=0
       NNAQM=0
       KINDXC=0
!      write(6,*) 'initi: IXPMGM, NPVAL(IXPMGM) ',
!     1                   IXPMGM, NPVAL(IXPMGM)
      DO 10 I=1,NPVAL(IXPMGM)
      RMNMIN(I)=1.0D+50
   10 END DO
!
      FSCFR1=-90.0D0
      FSCFR2=-90.0D0
      FSCMS1=-90.0D0
      FSCMS2=-90.0D0
!>>>
!***** BEGIN DEBUG *****
!c      PRINT 98000
!c98000 FORMAT(1X,'ENTERING INITI' )
!c      PRINT 98001,LSIMDT,LOBS,LORB,LNOADJ,LNADJL
!c98001 FORMAT(' ** INITI **  LSIMDT,LOBS,LORB,LNOADJ,LNADJL=',5(1X,L1))
!***** END DEBUG *****
!<<<
      NCUTOF=0
      IF(LITER1) ELPPGT=0.0D0
      IF(.NOT.LITER1) EBLEVL=EDLEVL
      ITEST=0
      IF(.NOT.LITER1) ITEST=1
      JTEST=EDITSW
      LNEDIT=ITEST.GE.JTEST
! SET THE FREEZE FLAGS
      LFREEZ=.FALSE.
      LSAVEF=.FALSE.
      LHALT=.FALSE.
      IF((NINNER.EQ.INT(FREEZI+0.8)).AND.(NGLOBL.GE.INT(FREEZG+0.8)))   &
     & LSAVEF=.TRUE.
      IF((NINNER.GT.INT(FREEZI+0.8)).AND.(NGLOBL.GE.INT(FREEZG+0.8)))   &
     & LFREEZ=.TRUE.
      IF(NINNER.LT.INT(FREEZA+0.8)) LHALT=.TRUE.
! THE FOLLOWING STATEMENTS APPEAR IN INITA
!     IF(NGLOBL.GT.1) MAXINR=MAXLST
!     IF(NGLOBL.GT.1) MININR=1
! UPON CONVERGENCE ENDITR REDUCES MAXINR TO BE:
!     MIN0(MAX0(MININR,NINNER+1),MAXINR)
      LSTINR=LSTINR.OR.NINNER.GE.MAXINR.OR.LSDATA.OR.LSTNRO
      LRESPG=LSTINR.AND.(NPVAL0(IXGPC).GT.0.OR.NPVAL0(IXGPS).GT.0)
      LRESPT=LSTINR.AND.(NPVAL0(IXTGPC).GT.0.OR.NPVAL0(IXTGPS).GT.0)
      LRESPD=LSTINR.AND.(NCDTA.GT.0.OR.NSDTA.GT.0)
      LRESPP=LSTINR.AND.(NCPDA.GT.0.OR.NSPDA.GT.0)
      LSTITR=LSTINR.AND.LSTGLB
      LORITR=LORALL.OR.(LORFST.AND.LITER1).OR.(LORLST.AND.LSTITR)
       IF(LORITR) THEN
       DO N=1,NSATA
       LL(KLNDTT-1+N)=.FALSE.
       II(KMJSTC-1+N)=II(KMJSTB-1+N)
       AA(KFSCTC-1+N)=AA(KFSCTB-1+N)
       ENDDO
       ENDIF
      LOBORB=LOBS.AND.LORITR.AND.LORBOB
      LRESID=LOBS.AND.(LOBALL.OR.(LOBFST.AND.LITER1)                    &
     &                       .OR.(LOBLST.AND.LSTITR))
      LVMTF=VMATRT.GT.ZERO.AND.LSTITR
      LVMTFO=VMATRT.GT.-ONE.AND.VMATRT.LE.ZERO.AND.LSTITR
! SET THE GEOLOCATION OUTPUT FLAGS
      LFILOT=.FALSE.
      IF(LFIRIT) THEN
      LFILOT=LITER1.AND.LATCOR
      ELSE
      LFILOT=LSTINR.AND.LATCOR
      ENDIF
      LG1BOT=.FALSE.
      IF(LONEG1) THEN
      LG1BOT=LITER1.AND.LG1B
      ELSE
      LG1BOT=LSTINR.AND.LG1B
      ENDIF
! CLEAR ARC PORTION OF ESTIMATION SUMMATION ARRAYS
! IF LAST INNER ITER. AND E-MATRIX CLEAR FULL NORMAL MATRIX
      NPCLR=MPVAL0(IXARC)
      IF(LSTINR .AND. EMTNUM.GT.ZERO) NPCLR=MAPARM
      IF(LZNRM.AND.NPCLR.GT.0) CALL CLEARA(AA(KSUM2),NPCLR)
      IF(LSTINR .AND. EMTNUM.GT.ZERO .AND. LPART) THEN
       NSUM1=MAXWRK
      ELSE
       NSUM1=INDXNO(NPCLR)+MAPARM
      ENDIF
       NSUM1=MAXWRK
      IF(LZNRM.AND.NSUM1.GT.0) CALL CLEARA(AA(KSUM1),NSUM1)
      LOLAJ=NTOLAJ.GT.0.AND.LSTINR
! SET NUMBER OF ADJUSTED PARAMETERS FOR THIS ITERATION
      NADJST=NPVAL0(IXARC)
      NGLBAL=NPVAL0(IXGLBL)
      IF(LSTINR.AND.NGLBAL.GT.0) NADJST=MAPARM
      LPARTI=.FALSE.
      IF(.NOT.LOBS) GO TO 100
      IF(.NOT.LSTINR) GO TO 100
      IF(.NOT.LPART) GO TO 100
! PARTITIONED FORMATION OF NORMAL EQUATIONS HAS BEEN REQUESTED.
      LFIRST=.TRUE.
      CALL EPART(MAPARM,LFIRST,LAST)
      NDM=MAPARM-NP1+1
      CALL GETPPC(NDM,NP2)
      LPARTI=.NOT.LAST
  100 CONTINUE
      IF(LSTINR.AND..NOT.LPART) CALL GETPPC(MAPARM,MAPARM)
! INITIALIZE ATTPRT IN COMMON ATTCBD (ATTITUDE PARTIALS NUM EVALUATION)
      ATTPRT=0.001D0
!  INITIALIZE LCLOCK
!  ASSUME DEFAULT CLOCK POLYNOMIALS
      LCLOCK=.TRUE.
!  INITIALIZE CROSSOVER KOUNT
      KXKNT=0
      KXBST=1
      KXBUP=1
      KXBPA=1
      KXOBL=0
!  INITIALIZE IMAGE KOUNT
      KIMBST=1
      KIMBUP=1
      KIMBPA=1
!  INITIALIZE ALTIMETRY CONSTRAINTS KOUNT
      KCNBST0=1
      KCNBST1=1
      KBUP110=1
      KBUP111=1
      KBPA110=1
      KBPA111=1

           IF(LX1ALT) THEN
! INITIALIZE THE XPMPA ARRAY
! THE RESIDUAL ARRAY THE SIGMA AND EDTSIG ARRAYS
      NTOT=NRXTOT*MAPARM
      KXP=KXPMPA-1
      DO 101 I=1,NTOT
      AA(KXP+I)=0.D0
  101 END DO
      IIXL=KXL-1
      IIXS=KXSIG-1
      IIXES=KXEDTS-1
      IIXA1=KXALO1-1
      IIXA2=KXALO2-1
      DO 102 I=1,NRXTOT
      AA(IIXL+I)=0.D0
      AA(IIXS+I)=0.D0
      AA(IIXES+I)=0.D0
      AA(IIXA1+I)=0.D0
      AA(IIXA2+I)=0.D0
  102 END DO
            ENDIF
      IIXKE=KXKEY-1
      DO I=1,NRXTOT
      II(IIXKE+I)=0
      ENDDO
! INITIALIZE ALBEDO DYNAMIC ARRAYS
      IF(ISPOTS.EQ.0)GOTO 107
      ISF=KSFLUX-1
      ISVEC=KSVECT-1
      DO 103 I=1,ISPOTS
      AA(ISF+I)=0.D0
  103 END DO
      ISPOT3=ISPOTS*3
      DO 104 I=1,ISPOT3
      AA(ISVEC+I)=0.D0
  104 END DO
      IKAD=KADIST-1
      IGEO=KGEOAN-1
      DO 105 I=1,ISPOTS+1
      AA(IKAD+I)=0.D0
  105 END DO
      DO 106 I=1,IRINGS+2
      AA(IGEO+I)=0.D0
  106 END DO
  107 CONTINUE
! INITIALIZE PARTIAL DERIVATIVE FILE SWITCHES
      LPARFI=LOBS.AND.LSTINR.AND.NGLOBL.EQ.1.AND.PFSW.GE.ZERO
      LPFEOF=LPARFI.AND.PFSW.GT.ZERO
      LARCNU=LPARFI.AND.PFSW.EQ.ONE
! WRITE PARTIAL DERIVATIVE FILE HEADER RECORDS
      IF(LPARFI) CALL PDFHDR(AA,II,LL,AA(KPRML0),AA(KPRMV0),AA(KPRMVC), &
     &                                II(KMJDSB),AA(KFSECB),AA(KA1UT ))
! SET NORMAL POINT GENERATION SWITCH
      LNORM =LOBS.AND.LSTITR.AND.MWIDTH.GT.0
! SET SIMULATED DATA GENERATION SWITCH
      LSIMTI=LSIMDT.AND.LSTITR
! SET POLE ADJUSTMENT SWITCH
      LPOLAD=LSTINR.AND.NPOLEA.GT.0
      LNUTAD=LSTINR.AND.NNUTAA.GT.0
!***** DEBUG PRINT *****
!     PRINT 12345,NPVAL0(IXARC),NPVAL0(IXGLBL),NADJST,NGLBAL,MAPARM
!2345 FORMAT(' ** INITI **  NPVAL0(IXARC),NPVAL0(IXGLBL),NADJST,NGLBAL',
!    1   ',MAPARM='/1X,5I12)
!***** END DEBUG *****
! CLEAR ARC STATISTICAL SUMMATION ARRAYS
      IF(NPCLR.GT.0) CALL SUMCLR(AA,II,LL,.TRUE.)
! CLEAR E-BIAS SUMMATION ARRAYS
      IF(NEBIAS.GT.0) CALL EBINIT(AA(KBTWB ),AA(KTBTWA),AA(KBTWD ),     &
     &   AA(KPMPE ),AA(KEBSTT),II(KNEBOB))
!  SET LOGICAL ADJUST COMMON BLOCK FOR GLOBAL PARAMETERS
      LSAGP=(NADJC.GT.0.OR.NADJS.GT.0).AND.LSTINR
      LSATID=(NSTADJ.GT.0.OR.NETADJ.GT.0.OR.NOTADJ.GT.0).AND.LSTINR
! WRITE OUT ORBINF FILE HEADERS ON LAST ITERATION IF FILE REQUESTED
      LORBNF=MAXINF.GT.0.AND.LSTITR
      IF(LORBNF) CALL ORBHDR(AA(KSTNAM),AA(KSXYZ),AA(KXLOCV),           &
     &           AA(KSTAIN), AA, II, LL,AA(KXUTDT))
!
! Reset current C and S geopotential values back to the initial values
! when either the dynamic polar motion option or the time
! time dependent gravity option is used.
!
      IF(.NOT.LGVTPM) GO TO 190
      IF(.NOT.LDPM) GO TO 150
! Reset the C(2,1) and S(2,1) values for dynamic polar motion
      C(6)=DPMC21
      S(6)=DPMS21
  150 CONTINUE
      IF(.NOT.LGVTM) GO TO 190
! Reset values used for time dependent gravity option
      IF(NCDT+NCPD .LE.0) GO TO 180
      DO 175 I=1,NCDT+NCPD
         IPTT=IPTC(I)
         C(IPTT)=CSAVE(I)
  175 END DO
  180 IF(NSDT+NSPD .LE.0) GO TO 190
      DO 185 I=1,NSDT+NSPD
         IPTT=IPTS(I)
         S(IPTT)=SSAVE(I)
  185 END DO
  190 CONTINUE
!
! LOAD ARC PARAMETER VALUES INTO FORCE MODEL ARRAYS
!
      NPARC=NPVAL(IXARC)
      IF(NPARC .LE. 0) GO TO 350
!
!     ....thermal drag spin axis direction  - DDR 11/92
      IF(NPVAL0(IXTHDR).GT.0) THEN
        SPAXT=PARMV(IPVAL(IXTHDR))
        SPAXL=PARMV(IPVAL(IXTHDR)+1)
      ENDIF
      ISTRT=1
!???? IF(NINNER.NE.1) ISTRT=MSATA*6+1
      DO 200 I=ISTRT,NPARC
      AA(KXEPOC+I-1)=PARMV(I)
  200 END DO
! FIND HERE IF THERE ARE PAIRS WITH COMBINATION 12 STATE PARAMETERS

      DO IJ=1,10
      IF(IDSATS(IJ,1).GT.0.AND.IDSATS(IJ,2).GT.0) THEN
      IFND=IJ
      ENDIF
      ENDDO

      DO 210 I=1,NSATA
      IPOFF=(I-1)*6+1
!     IXOFF=KXEPOC+IPOFF-1
      ISATID=II(KISATN-1+I)
      IF(ISATID.EQ.IDSATS(IFND,1)) IP1=IPOFF
      IF(ISATID.EQ.IDSATS(IFND,2)) IP2=IPOFF
  210  CONTINUE

      IF(IP1.GT.0.AND.IP2.GT.0) THEN
      L12=.TRUE.
      CALL GETBCR(.FALSE.,P1,PARMV(IP1),P2,PARMV(IP2),DXMDN,DXBDN)
      CALL TWELVE(Q1,Q2,P1,P2,.FALSE.)
      ENDIF

! SATELLITE ELEMENTS IN AA(KXEPOC) MUST BE IN CARTESIAN COORDINATES
! REGARDLESS OF SYSTEM OF ADJUSTMENT
      DO 220 I=1,NSATA
      GMX=GM
      IF(I.EQ.1.AND.LASTSN) GMX=BDSTAT(7,8)
      IPOFF=(I-1)*6+1
      IXOFF=KXEPOC+IPOFF-1
      IF(IELMTP(I).EQ.2) CALL POSVEL(AA(IXOFF),PARMV(IPOFF),1,GMX)
      IF(IELMTP(I).EQ.3) CALL PVNSK(AA(IXOFF),PARMV(IPOFF),1,GMX)
      IF(IELMTP(I).EQ.1.AND.IPOFF.EQ.IP1) THEN
        DO KK=1,6
        AA(IXOFF-1+KK)=Q1(KK)
        ENDDO
      ENDIF
      IF(IELMTP(I).EQ.1.AND.IPOFF.EQ.IP2) THEN
        DO KK=1,6
        AA(IXOFF-1+KK)=Q2(KK)
        ENDDO
      ENDIF
! ON THE FIRST ITERATION LOAD KEPLER AND N.S. KEPLER ( FOR OTHER
! ITERATIONS THESE VALUES ARE LOADED IN ADJELM
      IF(NINNER.GT.1) GO TO 220
! LOAD KEPLERIAN ELEMENTS INTO CKEPLR
      IKOFF =KCKEP +IPOFF -1
      IPXOFF=KPXPK+IPOFF-1
      CALL ELEM(AA(IXOFF),AA(IXOFF+1),AA(IXOFF+2),AA(IXOFF+3),          &
     &   AA(IXOFF+4),AA(IXOFF+5),AA(IKOFF),3,AA(IPXOFF),GMX)
! PKPX INVERTED IS PXPK
      CALL DNVERT(6,AA(IPXOFF),6,PK)
! LOAD NON SINGULAR  KEPLERIAN ELEMENTS INTO CKEPNS
      IKOFF =KCKEPN+IPOFF-1
      CALL ELEM(AA(IXOFF),AA(IXOFF+1),AA(IXOFF+2),AA(IXOFF+3),          &
     &   AA(IXOFF+4),AA(IXOFF+5),AA(IKOFF),8,PK,GMX)
  220 END DO
! LOAD ARC GEOPOTENTIAL COEFFICIENTS INTO FORCE MODEL ARRAYS
! OVERRIDING GLOBAL VALUES
      IF(NPVAL(IXGPCA).LE.0) GO TO 250
      INDXGP=IPVAL(IXGPCA)-1
      NGP=NPVAL(IXGPCA)
      DO 230 I=1,NGP
      N=IGPCA(1,I)
      M=IGPCA(2,I)
! DENORMALIZE COEFFICIENT
!     GP=PARMV(INDXGP+I)*DENORM(N,M)
      GP=PARMV(INDXGP+I)
      IF(IPTRUA(INDXGP+I).GT.0) GP=PARMVC(IPTRUA(INDXGP+I))
! LOAD INTO ARC FORCE MODEL LOCATION
      AA(KACN+I-1)=GP
! COMPUTE OFFSET WITHIN GLOBAL ARRAY OF C COEFFICIENTS FOR THIS COEF.
      IOFF=(N-1)*N/2+3*(N-1)+M
      AA(KCN +IOFF)=GP
  230 END DO
  250 IF(NPVAL(IXGPSA).LE.0) GO TO 300
      INDXGP=IPVAL(IXGPSA)-1
      NGP=NPVAL(IXGPSA)
      DO 280 I=1,NGP
      N=IGPSA(1,I)
      M=IGPSA(2,I)
! DENORMALIZE COEFFICIENT
!     GP=PARMV(INDXGP+I)*DENORM(N,M)
      GP=PARMV(INDXGP+I)
      IF(IPTRUA(INDXGP+I).GT.0) GP=PARMVC(IPTRUA(INDXGP+I))
! LOAD INTO ARC FORCE MODEL LOCATION
      AA(KASN+I-1)=GP
! COMPUTE OFFSET WITHIN GLOBAL ARRAY OF C COEFFICIENTS FOR THIS COEF.
      IOFF=(N-1)*N/2+3*(N-1)+M
      AA(KSN +IOFF)=GP
  280 END DO
  300 CONTINUE
!***** BEGIN DEBUG *****
!     JB=KXEPOC
!     JE=JB+NPARC-1
!     PRINT 98730,NPARC,JB,(AA(J),J=JB,JE)
!8730 FORMAT(1X,'INITI-NPARC,JB,AA(KXEPOC)',2I5/(1X,5G15.8))
!***** END DEBUG *****
!
! IF ADJUSTMENT OF ARC PARAMETERS REQUESTED LOAD CURRENT VALUES
! (PARMVC ARRAY) FROM PARAMETER VALUES ARRAY (PARMV) USING POINTERS
! FROM IPTRUA ARRAY
!
      IF(NADJST.LE.0) GO TO 350
!***** BEGIN DEBUG *****
!     PRINT 98720,NPARC,(PARMV(J),IPTRUA(J),J=1,NPARC)
!98720 FORMAT(1X,'INITI-NO OF ARC PARAMETERS, PARMV AND IPTRUA ARRAYS', &
!       I4/ (1X,G15.8,I4,2X,G15.8,I4,2X,G15.8,I4) )
!***** END DEBUG *****
      DO 330 I=1,NPARC
      IF(IPTRUA(I) .LE.0) GO TO 330
      PARMVC(IPTRUA(I))=PARMV(I)
  330 END DO
!***** BEGIN DEBUG *****
!     PRINT 98725,NADJST,(PARMVC(J),J=1,NADJST)
!98725 FORMAT(1X,'INITI-NADJST,PARMVC ',I4,4G15.8/(1X,5G15.8))
!!***** END DEBUG *****
  350 CONTINUE
!
!  LOOP THROUGH ALL SATELLITES IN ALL SETS;FILL DRAG &SOLAR RADIATION
!  ARRAYS WHICH DEPEND UPON CD,CDDOT&CR
!
!  KB0DRG - points to array containing .5*area/mass and is dimensioned
!           by the number of satellites
!  KBDRAG - points to array containing  Cd*.5*area/mass and is dimen.
!           by the number of drag parameters
!  KAPLM  - points to array containing     area/mass*rpress*au**2
!           and is dimensioned by the number satellites
!  KAPGM  - points to array containing  Cr*area/mass*rpress*au**2
!           and is dimensioned by the number of sol rad parameters
! DRAG,SOLAR RADIATION AND GENERAL ACCELERATION POINTERS KCD,KCR,KGENAC
! MUST BE COMPUTED FROM THE START OF THE DRAG VALUES. THE POINTERS IN CO
! CORA01 ARE INCORRECT DUE TO THE MULTIPLE SET AND SAT OPTIONS. THE
! ORDER SHOWN BELOW IS REPEATED FOR EACH SET OF SATELLITES:
!  Cd (order 1,2,3)             - for all satellites in the set
!  Cd with times (highest order) -for all satellites in the set
!  Cr (order 1,2,3)             - for all satellites in the set
!  Cr with times (highest order) -for all satellites in the set
!  Ga (order 1,2,3)             - for all satellites in the set
!  Ga with times (highest order) -for all satellites in the set
      JB0DRG=KB0DRG
      JBDRAG=KBDRAG
      JAPLM=KAPLM
      JAPGM=KAPGM
      JCDCR=KCD
      DO 500 I=1,NSETA
      NSATS=II(KNSAT-1+I)
      IDRG=II(KIORFR+3*(I-1))
      IF(IDRG.LE.0) GO TO 435
      DO 430 J=1,NSATS
      DO 420 JJ=1,IDRG
      AA(JBDRAG)=AA(JB0DRG)*AA(JCDCR)
      JBDRAG=JBDRAG+1
      JCDCR=JCDCR+1
  420 END DO
      IDRGPD=II(KIPDFR+3*(I-1))
      IF(IDRGPD.LE.0) GO TO 429
      DO 425 JJ=1,IDRGPD
      AA(JBDRAG)=AA(JB0DRG)*AA(JCDCR)
      JBDRAG=JBDRAG+1
      JCDCR=JCDCR+1
  425 END DO
  429 CONTINUE
      JB0DRG=JB0DRG+1
  430 END DO
  435 ISRD=II(KIORFR+3*(I-1)+1)
      IF(ISRD.LE.0) GO TO 465
      DO 460 J=1,NSATS
      DO 450 JJ=1,ISRD
      AA(JAPGM)=AA(JAPLM)*AA(JCDCR)
      JAPGM=JAPGM+1
      JCDCR=JCDCR+1
  450 END DO
      ISRDPD=II(KIPDFR+3*(I-1)+1)
      IF(ISRDPD.LE.0) GO TO 459
      DO 455 JJ=1,ISRDPD
      AA(JAPGM)=AA(JAPLM)*AA(JCDCR)
      JAPGM=JAPGM+1
      JCDCR=JCDCR+1
  455 END DO
  459 CONTINUE
      JAPLM=JAPLM+1
  460 END DO
! GENERAL ACCELERATION MUST BE ACCOUNTED FOR IN JCDCR POINTER FOR NXT SE
  465 IGA=II(KIORFR+3*(I-1)+2)
      JCDCR=JCDCR+IGA
      IGAPD=II(KIPDFR+3*(I-1)+2)
      JCDCR=JCDCR+IGAPD
  500 END DO
! INTIALIZE THERMAL IMBALANCE MODEL VARIABLES
      SHADOW(1) = ZERO
      SHADOW(2) = ZERO
      SUNPCT    = ZERO
! INITIALIZE MAXIMUM OCCULTATION BETAPRIME (56 DEG FOR TOPEX)
      BETAMX = 56.0D0*DEGRAD
! SET LOGICAL FLAGS FOR TOPEX ATTITUDE CONTROL
!  INITIALIZED VALUES ASSUMES SPACECRAFT IS IN SINUSOIDAL YAW.
!  THIS MAY NOT BE THE CASE.  HOWEVER, THE CODE SHOULD CORRECT ITSELF
!  AFTER 1 INTEGRATION STEP.  IF ARC BEGINS IN RAMP OF FIXED YAW REGION,
!  VERIFY IMPACT OF THIS INITIALIZATION.
         LTOPX1=.TRUE.
         LRAMP =.FALSE.
         LFIX0 =.FALSE.
         LSIN  =.TRUE.
         LFIX90=.FALSE.
         LRUP  =.FALSE.
         LRDOWN=.FALSE.
! SET THE LOGICAL SWITCHES FOR ADJUSTING GM AND GEOMETRIC LOVE NUMERS
      LSAGM=NPVAL0(IXGM).GT.0.AND.LSTINR
      LSAPGM=NPVAL0(IXPMGM).GT.0.AND.LSTINR
      LADLOV=NPVAL0(IXH2LV).GT.0.AND.LSTINR.OR.NPVAL0(IXL2LV).GT.0      &
     &       .AND.LSTINR
! SET SWITCH FOR DYNAMIC POLAR MOTION ADJUSTMENT OF X & Y
      LSADNX=(NPVAL0(IXPOLX).GT.0).OR.(NPVAL0(IXPOLY).GT.0)
      LSADNX=LSADNX.AND.(DPMOPT.EQ.ONE)
      LSADNX=LSADNX.AND.LSTINR
! SET SWITCH FOR DYNAMIC POLAR MOTION ADJUSTMENT OF KF
      LSAKF=NPVAL0(IXKF).GT.0
      LSAKF=LSAKF.AND.(DPMOPT.EQ.ONE)
      LSAKF=LSAKF.AND.LSTINR
! SET SWITCH FOR DYNAMIC POLAR MOTION CONTRIBUTION TO C20
      IPC2=IPVAL(IXGPC)+4
      LSADJ2=IPTRUA(IPC2).GT.0
      LSADJ2=LSADJ2.AND.(DPMOPT.EQ.ONE)
      LSADJ2=LSADJ2.AND.LSTINR
! SET SWITCH TO SEE IF ANY PARTIALS WILL BE AFFECTED BY DYNAMIC
! POLAR MOTION
      LSADPM=LSADNX.OR.LSAKF.OR.LSADJ2
! SET NEQN AND NEQN3 FOR THE PROPER ITERATION
! ON ALL ITERATIONS EXCEPT LAST USE #2 SET OF INFO (ARC)
! ON LAST ITER USE #1 SET (GLOBAL)
!
      IF (NINNER == 1) THEN
          ! ON THE FIRST INNER ITERATION, SWAP THE FIRST AND SECOND
          ! HALVES OF THE II(KNEQN) ARRAY TO PUT THE NEQN VALUES
          ! EXCLUDING GLOBALS IN THE FIRST HALF.
          DO I = 1, NSETA ! DO 600
              I1 = KNEQN + I - 1
              I11 = I1 + MSETA
              IHLD = II(I1)
              II(I1) = II(I11)
              II(I11) = IHLD
          END DO
      END IF
      IF (LSTINR) THEN
          ! ON THE LAST INNER ITERATION, SWAP THE FIRST AND SECOND
          ! HALVES OF THE II(KNEQN) ARRAY TO PUT THE NEQN VALUES
          ! INCLUDING GLOBALS IN THE FIRST HALF.
          DO I = 1, NSETA ! DO 650
              I1 = KNEQN + I - 1
              I11 = I1 + MSETA
              IHLD = II(I1)
              II(I1) = II(I11)
              II(I11) = IHLD
          END DO
      END IF

      DO I = 1, NSETA ! DO 700
          I1 = I - 1
          II(KNEQN3+I1) = II(KNEQN+I1) * 3
      END DO

      ! DETERMINE NFMG(ISAT) FOR EVERY SATELLITE IN ARC
      NSATC = 0
      DO I = 1, NSETA ! DO 750
          ! DETERMINE NEQN FOR EACH SET THIS ITERATION
          MAX = II(KNEQN+I-1)
          IF (MAX <= 0) THEN
              CYCLE
          END IF

          ! DETERMINE MAX NUMBER OF FORCE MODEL GROUPS FOR THIS SET ON
          ! LAST INNER.  GET THIS FROM FIRST SATELLITE IN SET
          MFMGTS = II(KMFMG+NSATC)

          ! DETERMINE MAX NUMBER OF FORCE MODEL GROUPS FOR THIS SET ON
          ! THIS INNER.  GET THIS FROM FIRST SATELLITE IN SET
          JCOUNT = 0
          LFOUND = .FALSE.
          DO NFMGTS = 1, MFMGTS ! DO 710
              IPT = KILNFM + NSATC*MAXFMG + NFMGTS - 1
              JCOUNT = JCOUNT + II(IPT)
              IF (JCOUNT == MAX) THEN
                  LFOUND = .TRUE.
                  EXIT
              END IF
          END DO
          IF (.NOT. LFOUND) THEN
              GO TO 5000 ! PRINT OUT ERROR MESSAGE
          END IF

          ! PUT NFMGTS INTO NFMG(ISAT) FOR EVERY SATELLITE IN SET
          ! DETERMINE NSAT FOR EACH SET
          IIIUP = II(KNSAT+I-1)
          DO III = 1, IIIUP ! DO 720
              II(KNFMG+NSATC+III-1) = NFMGTS
          END DO
          NSATC = NSATC + IIIUP
      END DO
!
! TAKE CARE OF TRAJECTORY FILE
      LTRAJ=LSTITR.AND.NTRAJC.GT.0
      IF(.NOT.LSTNRO) LTRAJ=.FALSE.
      IF(.NOT.LTRAJ) GO TO 800
      CALL TRAJIN(AA,II,LL,II(KISATR),II(KTRTMB),II(KTRTMC),II(KMSTRC), &
     &            II(KMSTRE),II(KISCTR),AA(KFSTRC),AA(KFSTRE),          &
     &            AA(KDSCTR),AA(KTRBF),II(KITRUN),LL(KLNDTR),LL(KLWSTR))
  800 CONTINUE
! TAKE CARE OF BINARY RESIDUAL FILE
      LBINRI=.FALSE.
      LLOCRI=.FALSE.
      LODRI=.FALSE.
      LBNCRI=.FALSE.
      IF(.NOT.LBINR) GO TO 900
      IF(LSTNRO) LBINRI=.TRUE.
      IF(LSTNRO) GO TO 900
      IF(.NOT.LSTITR) GO TO 900
      LBINRI=.TRUE.
      LLOCRI=LLOCR
      LODRI=LODR
      LBNCRI=LBNCR
      CALL ARCBHD
  900 CONTINUE
! TAKE CARE OF VMAT FILE
      IF(LVMTF.OR.LVMTFO) CALL VMATHD(AA,II(KMJDSB),AA(KFSECB),         &
     &  II(KISATN),II(KNSAT),AA(KH),II(KIORDR),AA(KHV),II(KIORDV),      &
     &  II(KMJDND),AA(KFSCND),II(KJSAFR),AA(KPRML0),AA(KPXPFM),         &
     &  II(KMJDVS),AA(KFSCVS),II(KNTMVM),LL(KLEVMF),II)
!
      CALL LDELXS(PARMV,AA(KDELXS),II(KXSTAT),II(KNSAT),NSETA)
!
! INITIALIZE THE INTEGRATOR
!
!***** BEGIN DEBUG *****
!     PRINT 98100,NSATS,NSETA,NSATA,NSATA3
!8100 FORMAT(' INITI-NSATS,NSETA,NSATA,NSATA3 PRIOR TO COWLIN',4I5)
!***** END DEBUG *****
      CALL INTDMP(AA,II,LL)
      LNADJ=LNOADJ.OR.(LNADJL.AND.LSTITR)
      IF(LSDATA) LNADJ=LSDATA
!***** TEMPORARY FIX *****
      NSATA3=NSATA*3
!***** END FIX *****
      IF(NTRAJC.GT.0.AND.LSTITR.AND..NOT.LSTNRO) THEN
         LSTINR=.FALSE.
         LSTITR=.FALSE.
         LSTNRO=.TRUE.
      ENDIF
!
! LOKIT WILL ONLY BE TRUE ON THE LAST ITERATION FOR WHICH DATA IS BEING
! REDUCED. IN RUNS WITH TRAJECORY FILES, LSTNRO WILL BE TRUE ON THE
! LAST ITERATION FOR WHICH DATA IS BEING PROCESSED AND LSTINR WILL BE
! FALSE. FOR RUNS WITHOUT TRAJECTORY FILES LSTRNO WILL ALWAYS BE FALSE
! AND DATA WILL BE PROCESSED ON LSTINR
!
      LOKIT=.FALSE.
      IF(LSTINR.AND..NOT.LSTNRO) LOKIT=.TRUE.
      IF(.NOT.LSTINR.AND.LSTNRO) LOKIT=.TRUE.
      L9OUT=.TRUE.
      IF(L9LAST) L9OUT=LOKIT
! DEP RAPID INTEGRATION
! WE HAVE ALLOCATED SPACE FOR UP TO 3 SATELLITES.
! IF WE HAVE TWO SATELLITES SPLIT THE AVAILABLE AA(KSMXOS)
! IN 2 AND IF WE HAVE 3 OR MORE IN 3.
!     IF(NINNER.EQ.1) NQHOLD=NINTOT
!     IF(NINNER.EQ.1) NINTOT=0
!     IF(NINNER.GT.1) NINTOT=NQHOLD



      LBUFOP=.FALSE.
      IF(NINTOT.GT.0) THEN

      write(6,*)' SUBROUTINE INITI RAPID INTEGRATION REQUESTED FOR  ',  &
     & NINTOT, ' SATELLITES'
      DO I=1,NINTOT
      write(6,*)' SATELLITE ID ',II(KSATIN-1+I)
! ASSUME FOR NOW THAT WE HAVE EQUAL MEMORY FOR ALL SATELLITES
      write(6,*)' MEMORY ',II(KMEMST-1+I)
      write(6,*)' F.M. EQ ',II(KNEQNI-1+I)

! NOW FIGURE OUT HOW MANY STEPS ARE DEDICATED FOR EACH SATELLITE
! IN THE AVAILABLE BUFFER

      II(KSTEPS-1+I) = (II(KMEMST-1+I)-6-(II(KNEQNI-1+I)*2))/           &
     &                 (3+(II(KNEQNI-1+I)*3))-1
      write(6,*)' STEPS AVAILABLE WITHIN A BUFFER  FOR THIS SATELLITE' &
     & ,II(KSTEPS-1+I)

      ENDDO

! NOW KNOWING THE NUMBER OF STEPS FOR EACH SATELLITE COMPUTE THE MAPPING
! ARRAY TO ACCESS VARIOUS "OS" ARRAYS

      IF(NINTOT.LE.2) THEN
      IR=2
      ELSE
      IR=3
      ENDIF

      CALL FILMAP(II(KNEQNI),II(KSTEPS),NINTOT,IR,II(KMEMST))

      ENDIF ! IF(NINTOT.GE.0)

! DEP DEBUG FOR INTEGRATION

       CALL COWLIN(LL(KLORBT),LL(KLORBV),LL(KLNDRG),LL(KLAFRC),         &
     & LL(KLBAKW),                                                      &
     & NSATA3,NSETA,II(KIBACK),II(KIBAKV),II(KIORDR),                   &
     & II(KIORDV),II(KNOSTP),II(KNOCOR),II(KNSAT ),II(KN3   ),          &
     & II(KNEQN ),II(KNEQN3),II(KNH   ),II(KNHV  ),II(KNSTPS),          &
     & II(KNSTPV),II(KICPP ),II(KICPV ),II(KICCP ),II(KICCV ),          &
     & II(KICCPV),II(KICCVV),II(KISUMX),II(KIXDDT),II(KISMPX),          &
     & II(KIPXDD),II(KMJDSC),II(KMJDSV),II(KMJDS0),II(KMJDSB),          &
     & II(KNMAX ),II(KNTOLD),II(KNTOLO),II(KJSAFR),II(KIORFR),          &
     & II(KIPDFR),II(KJSPFR),AA(KFSEC),AA(KFSECV),                      &
     & AA(KFSEC0),AA(KFSECB),AA(KH),AA(KHV),AA(KXEPOC),II(KIXTMC),      &
     & II(KPLPTR),II(KPANEL),II(KNMOVE),II(KITPAT),II(KILTPX),          &
     & II(KIBCKN),II(KNRAT ),II(KIXDDN),II(KISMXN),II(KDXDDN),          &
     & II(KDSMXN),II(KICPPN),LL(KFHIRT),LL(KLSURF),II(KIPXDA),          &
     & II(KNEQNH),II(KPTFBS),II(KPTFSB),LL(KSETDN),II(KXSTAT),          &
     & AA(KTXSTA),AA(KDELXS),II(KPXST), II(KSALST),L12       ,          &
     & AA(KHLDV) ,II(KNSSVA),AA(KHLDA1),AA(KHLDA4),AA(KHLDA7),          &
     & AA,II,LL)
!>>>
! WRITE OUT ORBINF FILE HEADERS ON LAST ITERATION IF FILE REQUESTED
      LORBNF=MAXINF.GT.0.AND.LSTITR
!     write(6,*) 'initi: call orbhdr lorbnf = ', lorbnf
!     write(6,*) 'initi: kstain ,aa(kstain) ', kstain, aa(kstain)
      IF(LORBNF) CALL ORBHDR(AA(KSTNAM),AA(KSXYZ),AA(KXLOCV),           &
     &           AA(KSTAIN), AA, II, LL,AA(KXUTDT))
!<<<
      IF(NPVAL0(IXXTRO).GT.0) THEN
! FORM MATRIX R3(-w)
!
      R3THG(1)=COSSTG
      R3THG(2)=-SINSTG
      R3THG(3)=ZERO
      R3THG(4)=SINSTG
      R3THG(5)=COSSTG
      R3THG(6)=ZERO
      R3THG(7)=ZERO
      R3THG(8)=ZERO
      R3THG(9)=ONE
!
      DR3TDW(1)= R3THG(2)
      DR3TDW(2)= R3THG(1)
      DR3TDW(3)= ZERO
      DR3TDW(4)=-R3THG(5)
      DR3TDW(5)=-R3THG(4)
      DR3TDW(6)= ZERO
      DR3TDW(7)= ZERO
      DR3TDW(8)= ZERO
      DR3TDW(9)= ZERO
!
      ENDIF
!
      RETURN
 5000 CONTINUE
      WRITE(IOUT6,50000)
      STOP 99
50000 FORMAT(' TERMINATION IN INITI:ILFMG DOES NOT MATCH NEQN')
78912 FORMAT(' EXECUTION TERMINATING. NUMBER OF GEOMETRIC FANTOM')
78913 FORMAT(' PARAMETERS IS GREATER THAN 1. THIS VERSION USES AT')
78914 FORMAT(' MOST 1 GEOMETRIC FANTOM PARAMETER (FOR RADIAL ')
78915 FORMAT(' SEPARATION ZERO PROTECTION FOR CROSSOVERS)')
      END
