      SUBROUTINE IP1WAY(AA,II,LL,ISAT,NM,NP,OBSC,PMPA,LNPNM,NDIM1,      &
     &                  NDIM2,PRMLBL,MJDSBL,T2S,T2E,DTIME,RELCOR,       &
     &                  LAVOID)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!
      COMMON/RAMPA/SF1,SF2,FREQO,RBIAS
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/COBBUF/IOBSBF,IBUF1 ,IBUF2 ,IWORD1,NHEADR,NWORDM
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION OBSC(NM),PMPA(NDIM1,NDIM2),PRMLBL(3,1)
      DIMENSION T2S(NM),T2E(NM),DTIME(NM),RELCOR(NM)
!
      DIMENSION TCPOTC(500),TCP(500),TCP2(500),T2M1(500),T2M2(500)
      DIMENSION FACT(500)
      DIMENSION LAVOID(1)
!
      DATA TWELTH/.8333333333333333D-1/
      DATA SIXTH/.1666666666666667D0/
!
! PULL OUT SOME INFORMATION ABOUT FREQUENCY AND FREQUENCY BIASES
      SF1=11.D0/3.D0
      FREQO=BLKDAT(3,1)
      IP0=KLKSAT(1,2)
      IP1=KLKSAT(2,2)
      IP2=KLKSAT(3,2)
      T01=0.D0
      T02=0.D0
      IF(IP1.GT.0) T01=PRMLBL(2,IP1)-DBLE(MJDSBL)
      IF(IP2.GT.0) T02=PRMLBL(2,IP2)-DBLE(MJDSBL)
      C2=SF1
      FT0=C2*FREQO
      DFT0=C2*CLKSAT(1,2)
      FT1=C2*CLKSAT(2,2)
      FT2=C2*CLKSAT(3,2)
      C2FT0=FT0
      FT2STH=FT2*SIXTH
!
!
      DO 100 I=1,NM
!  AT THIS POINT, COMPUTED OBSERVATION IS IN M/S.
!  CONVERT IT TO A UNIT SCALE FACTOR
      OBSC(I)=OBSC(I)/VLIGHT
!  USE THE SCALE FACTOR TO COMPUTE THE COUNTING INTERVAL AT SAT
!  AND THE RATIO OF SAT/GROUND COUNTING INTERVAL
      TCPOTC(I)=1.D0-OBSC(I)
      TCP2(I)=TCPOTC(I)*DTIME(I)
      TCP2(I)=TCP2(I)*TCP2(I)
!
      T2M1(I)=.5D0*(T2S(I)+T2E(I))
      T2M2(I)=T2M1(I)-T02
      T2M2(I)=T2M2(I)*T2M2(I)
      T2M1(I)=T2M1(I)-T01
      FACT(I)=DFT0+FT1*T2M1(I)+FT2*(T2M2(I)+TWELTH*TCP2(I))
      OBSC(I)=OBSC(I)*C2FT0
!     OBSC(I)=OBSC(I)-C2*FACT(I)*TCPOTC(I)
!     FACT(I)=FACT(I)+FT0+FT2STH*TCP2(I)
      FACT(I)=(FACT(I)+FT0+FT2STH*TCP2(I))
      FACT(I)=FACT(I)/VLIGHT
!     FACT(I)=FACT(I)*C2
  100 END DO
!
!  AT THIS POINT:
!    (1) OBSC IS IN UNITS OF FREQ AND IS COMPLETE
!    (2) BIAS PARTIALS HAVE NOT BEEN FILLED
!    (3) ALL OTHER PARTIALS ARE IN M/S AND NEED TO BE MULTIPLIED
!        BY FACT
!    (4) CORRECTIONS ARE IN M/S AND NEED TO BE MULTIPLIED BY FACT
!    (5) BEFORE (4) IS DONE THE RELATIVITY NEEDS TO BE CORRECTED
!        IN UNITS OF M/SEC. MOYER'S DELTA SHOULD BE DIVIDED BY
!        THE COUNTING INTERVAL AND SUMMED INTO RELCOR
!
!
      IF(.NOT.LITER1) GO TO 200
!
!
      DO 110 I=1,NM
      TCP(I)=SQRT(TCP2(I))
  110 END DO
!
!
! GET SATELLITE ID
      ISATID=II(KISATN+ISAT-1)

      IF(ICBDGM.EQ.4) THEN
      CALL IWRELM(MJDSBL,NM,ISAT,DTIME,TCP,T2S,T2E,RELCOR,              &
     &            AA(KXSM),AA(KVSM),ISATID,AA,II,LL)
      ELSE
      CALL I1WREL(MJDSBL,NM,ISAT,DTIME,TCP,T2S,T2E,RELCOR,              &
     &            AA(KXSM),AA(KVSM),ISATID,AA,II,LL)
      ENDIF
!
!
! SCALE MEASUREMENT CORRECTIONS BY FACT
!
      DO 190 IHEADR=2,NHEADR
      JHEADR=IHEADR-1
      DO 180 IWORD =2,8
      IF(LPRE  (IWORD ,JHEADR)) GO TO 180
      IF(.NOT.LSWTCH(IWORD ,IHEADR)) GO TO 180
      JOBCOR=KOBCOR(IWORD ,JHEADR)
      DO 170 M=1,NM
      AA(JOBCOR)=AA(JOBCOR)*FACT(M)
      JOBCOR=JOBCOR+1
  170 END DO
  180 END DO
  190 END DO
!
  200 CONTINUE
!
! ZERO OUT ALL BIAS PARTIALS (JUST IN CASE)
! MULTIPLY PMPA BY FACT
! RESET BIAS PARTIALS
!
      IBS=IPVAL0(IXBISA)
      IBE=IBS-1+NPVAL0(IXBISA)
!
      IF(LNPNM) GO TO 500
!
      IF(NPVAL0(IXBISA).GT.0) THEN
         DO 300 I=IBS,IBE
         DO 290 J=1,NM
         PMPA(J,I)=0.D0
  290    CONTINUE
  300    CONTINUE
      ENDIF
!
      DO 400 I=1,NP
      DO 390 J=1,NM
      PMPA(J,I)=FACT(J)*PMPA(J,I)
  390 END DO
  400 END DO
!
!   BIAS PARTIALS
      IF(IP0.GT.0) THEN
         LAVOID(IP0)=.FALSE.
         DO 410 J=1,NM
         PMPA(J,IP0)=-C2*TCPOTC(J)
  410    CONTINUE
      ENDIF
      IF(IP1.GT.0) THEN
         LAVOID(IP1)=.FALSE.
         DO 420 J=1,NM
         PMPA(J,IP1)=-C2*TCPOTC(J)*T2M1(J)
  420    CONTINUE
      ENDIF
      IF(IP2.GT.0) THEN
         LAVOID(IP2)=.FALSE.
         DO 430 J=1,NM
         PMPA(J,IP2)=-C2*TCPOTC(J)*(T2M2(J)+TWELTH*TCP2(J))
  430    CONTINUE
      ENDIF
      GO TO 1000
!
!
  500 CONTINUE
      IF(NPVAL0(IXBISA).GT.0) THEN
         DO 800 J=1,NM
         DO 790 I=IBS,IBE
         PMPA(I,J)=0.D0
  790    CONTINUE
  800    CONTINUE
      ENDIF
!
      DO 900 J=1,NM
      DO 890 I=1,NP
      PMPA(I,J)=FACT(J)*PMPA(I,J)
  890 END DO
  900 END DO
!
!   BIAS PARTIALS
      IF(IP0.GT.0) THEN
         LAVOID(IP0)=.FALSE.
         DO 910 J=1,NM
          PMPA(IP0,J)=-C2*TCPOTC(J)
  910    CONTINUE
      ENDIF
      IF(IP1.GT.0) THEN
         LAVOID(IP1)=.FALSE.
         DO 920 J=1,NM
         PMPA(IP1,J)=-C2*TCPOTC(J)*T2M1(J)
  920    CONTINUE
      ENDIF
      IF(IP2.GT.0) THEN
         LAVOID(IP2)=.FALSE.
         DO 930 J=1,NM
         PMPA(IP2,J)=-C2*TCPOTC(J)*(T2M2(J)+TWELTH*TCP2(J))
  930    CONTINUE
      ENDIF
 1000 CONTINUE
      RETURN
      END
