      SUBROUTINE IWRELM(MJDSBL,NM,ISAT,TC,TCP,T2S,T2E,REL,XSM,VSM,      &
     &                  ISATID,  AA,II,LL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!
      COMMON/CBARYC/CBODY(6),TBODY(6),SUNRF(6)
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CREFMT/REFMT(9)
      COMMON/CENACC/DGCEN,TCEN,BMACEN,CCHEBV(50),EPCEN(50,3),           &
     &              DGEAR,TEAR,BMAEAR,ECHEBV(50),EPEAR(50,3),           &
     &              DGMON,TMON,BMAMON,SCHEBV(50),EPMON(50,3)
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
!
      DIMENSION XSM(MINTIM,3,2),VSM(MINTIM,3,2)
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION TC(NM),TCP(NM),T2S(NM),T2E(NM),REL(NM)
      DIMENSION BODY(3,2,5),U(2),UDOT(2),V2(2),V2DOT(2)
      DIMENSION IREST(3),IREST2(3),ICBOD(5)
      DIMENSION CCHEBA(50),CBODYA(3),CBODYX(3)
      DIMENSION ECHEBA(50),EBODYA(3),EBODYX(3)
      DIMENSION SCHEBA(50),SBODYA(3),SBODYX(3)
      DIMENSION GMX(5)
      DIMENSION SATVC(3,3),SP(3),SV(3)
      DIMENSION XI(2),XIDOT(2)
      DATA SQFV/2.236067977499D0/
      DATA IREST/2,4,3/
      DATA IREST2/5,6,7/
      DATA ICBOD/11,3,5,6,7/
      DATA YL/1.481D-8/
!
      IRET=0
      IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
      ENDIF

!
!
      VL2=VLIGHT*VLIGHT
!     XL=1.D0+YL
      XL=YL
      IDEGE=(DGEAR+.001D0)
      IDEGM=(DGMON+.001D0)
      GMX(1)=BDSTAT(7,8)
      GMX(2)=BDSTAT(7,9)
      GMX(3)=BDSTAT(7,2)
      GMX(4)=BDSTAT(7,4)
      GMX(5)=BDSTAT(7,3)
!
      C20=AA(KCN+4)
      OBLFCT=SQFV*AE*AE*GM*C20
!
!   GET SATELITE PLANET CENTERED TRUE OF REF POSITION AND VELOCITIES
!   ACROSS WHOLE MEASUREMENT BLOCK START AND END OF COUNT INTERVAL
!
      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),ISAT,                 &
     &   KNSTEPS,NEQNI,II(KSGMNT-1+IRET),                               &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),IRET,MJDSBL,T2S(1),T2S(NM),&
     &   NM,AA,II)
      CALL ORBIT(MJDSBL,T2S,AA(KS),NM,II(KINDH),II(KNMH),II(KMJDSC),    &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM(1,1,1),AA(KPXPFM),       &
     &   .TRUE.,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),               &
     &   AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)

      CALL ORBIT(MJDSBL,T2E,AA(KS),NM,II(KINDH),II(KNMH),II(KMJDSC),    &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM(1,1,2),AA(KPXPFM),       &
     &   .TRUE.,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),               &
     &   AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)

!
!
      DO 1000 I=1,NM
!
      DO 900  IT=1,2
      U(IT)=0.D0
      UDOT(IT)=0.D0
      V2(IT)=0.D0
      V2DOT(IT)=0.D0
      FSEC=T2S(I)
      IF(IT.EQ.2) FSEC=T2E(I)
      CALL PLANPO(MJDSBL,FSEC,.TRUE.,.TRUE.,AA,II)
      DO 50 J=1,6
      BODY(J,1,1)=SUNRF(J)
      BODY(J,1,2)=TBODY(J)
   50 END DO
      DO 60 J=1,3
      IF(ICBDGM.EQ.IREST2(J)) GO TO 60
      BODY(1,1,J+2)=REFMT(1)*BDSTAT(1,IREST(J))                         &
     &             +REFMT(2)*BDSTAT(2,IREST(J))                         &
     &             +REFMT(3)*BDSTAT(3,IREST(J))
      BODY(2,1,J+2)=REFMT(4)*BDSTAT(1,IREST(J))                         &
     &             +REFMT(5)*BDSTAT(2,IREST(J))                         &
     &             +REFMT(6)*BDSTAT(3,IREST(J))
      BODY(3,1,J+2)=REFMT(7)*BDSTAT(1,IREST(J))                         &
     &             +REFMT(8)*BDSTAT(2,IREST(J))                         &
     &             +REFMT(9)*BDSTAT(3,IREST(J))
      BODY(1,2,J+2)=REFMT(1)*BDSTAT(4,IREST(J))                         &
     &             +REFMT(2)*BDSTAT(5,IREST(J))                         &
     &             +REFMT(3)*BDSTAT(6,IREST(J))
      BODY(2,2,J+2)=REFMT(4)*BDSTAT(4,IREST(J))                         &
     &             +REFMT(5)*BDSTAT(5,IREST(J))                         &
     &             +REFMT(6)*BDSTAT(6,IREST(J))
      BODY(3,2,J+2)=REFMT(7)*BDSTAT(4,IREST(J))                         &
     &             +REFMT(8)*BDSTAT(5,IREST(J))                         &
     &             +REFMT(9)*BDSTAT(6,IREST(J))
   60 END DO
!
!  GET 2ND DERIV OF CHEB POLYNOMIALS FOR CENTRAL BODY
      ECHEBA(1)=0.D0
      ECHEBA(2)=0.D0
      SCHEBA(1)=0.D0
      SCHEBA(2)=0.D0
      TWOT=2.D0*TEAR
      DO 70 IDEG=3,IDEGE
      ECHEBA(IDEG)=4.D0*ECHEBV(IDEG-1)+TWOT*ECHEBA(IDEG-1)              &
     &            -ECHEBA(IDEG-2)
   70 END DO
      TWOT=2.D0*TMON
      DO 71 IDEG=3,IDEGM
      SCHEBA(IDEG)=4.D0*SCHEBV(IDEG-1)+TWOT*SCHEBA(IDEG-1)              &
     &            -SCHEBA(IDEG-2)
   71 END DO
! ***********  EARTH  ***********
      DO 90 IX=1,3
      EBODYX(IX)=0.D0
      NDEG=IDEGE-2
      DO 80 IDEG=1,NDEG
      EBODYX(IX)=EBODYX(IX)+EPEAR(IDEGE+1-IDEG,IX)*ECHEBA(IDEGE+1-IDEG)
   80 END DO
      EBODYX(IX)=EBODYX(IX)*BMAEAR*BMAEAR
   90 END DO
! ***********  MOON  ***********
      DO 91 IX=1,3
      SBODYX(IX)=0.D0
      NDEG=IDEGM-2
      DO 81 IDEG=1,NDEG
      SBODYX(IX)=SBODYX(IX)+EPMON(IDEGM+1-IDEG,IX)*SCHEBA(IDEGM+1-IDEG)
   81 END DO
      SBODYX(IX)=SBODYX(IX)*BMAMON*BMAMON
   91 END DO

      DO 100 IM=1,3
      CBODYX(IM)=-EMFACT*EBODYX(IM)+SBODYX(IM)
!     CBODYX(IM)=-EMFACT*BDSTAT(IM,11)+BDSTAT(IM,9)

  100 END DO


      CBODYA(1)=REFMT(1)*CBODYX(1)+REFMT(2)*CBODYX(2)+REFMT(3)*CBODYX(3)
      CBODYA(2)=REFMT(4)*CBODYX(1)+REFMT(5)*CBODYX(2)+REFMT(6)*CBODYX(3)
      CBODYA(3)=REFMT(7)*CBODYX(1)+REFMT(8)*CBODYX(2)+REFMT(9)*CBODYX(3)
!
      RS2=XSM(I,1,IT)*XSM(I,1,IT)+XSM(I,2,IT)*XSM(I,2,IT)               &
     &   +XSM(I,3,IT)*XSM(I,3,IT)
      RS=SQRT(RS2)
      RS3=RS2*RS
!
!
      OBLF=OBLFCT/RS3
      SINF=XSM(I,3,IT)/RS
      RSD=(XSM(I,1,IT)*VSM(I,1,IT)+XSM(I,2,IT)*VSM(I,2,IT)              &
     &    +XSM(I,3,IT)*VSM(I,3,IT))/RS
      SINFD=VSM(I,3,IT)/RS-(XSM(I,3,IT)*RSD)/RS2
      P1=1.5D0*SINF*SINF-.5D0
      UOBL=OBLF*P1
      UOBLD=-3.D0*OBLF*((RSD*P1)/RS-SINF*SINFD)
!
      U(IT)=UOBL+GM/RS
      UDOT(IT)=UOBLD-GM*(XSM(I,1,IT)*VSM(I,1,IT)                        &
     &             +XSM(I,2,IT)*VSM(I,2,IT)+XSM(I,3,IT)*VSM(I,3,IT))/RS3
!
      SATVC(1,1)=XSM(I,1,IT)+CBODY(1)
      SATVC(2,1)=XSM(I,2,IT)+CBODY(2)
      SATVC(3,1)=XSM(I,3,IT)+CBODY(3)
      SATVC(1,2)=VSM(I,1,IT)+CBODY(4)
      SATVC(2,2)=VSM(I,2,IT)+CBODY(5)
      SATVC(3,2)=VSM(I,3,IT)+CBODY(6)
      SATVC(1,3)=CBODYA(1)-GM*XSM(I,1,IT)/RS3
      SATVC(2,3)=CBODYA(2)-GM*XSM(I,2,IT)/RS3
      SATVC(3,3)=CBODYA(3)-GM*XSM(I,3,IT)/RS3
      V2(IT)=SATVC(1,2)*SATVC(1,2)+SATVC(2,2)*SATVC(2,2)                &
     &      +SATVC(3,2)*SATVC(3,2)
      V2DOT(IT)=2.D0*(SATVC(1,2)*SATVC(1,3)+SATVC(2,2)*SATVC(2,3)       &
     &               +SATVC(3,2)*SATVC(3,3))
!
      DO 200 IB=1,5
      IF(ICBDGM.EQ.ICBOD(IB)) GO TO 200
      SP(1)=SATVC(1,1)-BODY(1,1,IB)
      SP(2)=SATVC(2,1)-BODY(2,1,IB)
      SP(3)=SATVC(3,1)-BODY(3,1,IB)
      SV(1)=SATVC(1,2)-BODY(1,2,IB)
      SV(2)=SATVC(2,2)-BODY(2,2,IB)
      SV(3)=SATVC(3,2)-BODY(3,2,IB)
      RKP2=SP(1)*SP(1)+SP(2)*SP(2)+SP(3)*SP(3)
      RKP=SQRT(RKP2)
      RKP3=RKP*RKP2
      U(IT)=U(IT)+GMX(IB)/RKP
      UDOT(IT)=UDOT(IT)-GMX(IB)*(SP(1)*SV(1)+SP(2)*SV(2)                &
     &                          +SP(3)*SV(3))/RKP3
  200 END DO
!
!
      XI(IT)=(U(IT)+.5D0*V2(IT))/VL2-XL
      XIDOT(IT)=(UDOT(IT)+.5D0*V2DOT(IT))/VL2
  900 END DO
      RELT=.5D0*(XI(2)+XI(1))*TCP(I)                                    &
     &         -((XIDOT(2)-XIDOT(1))*TCP(I)*TCP(I))/12.D0

!
!  RELT IS A CORRECTION IN TIME. CONVERT IT
!  TO A CORRECTION IN M/S
      REL(I)=REL(I)+VLIGHT*RELT/TC(I)
 1000 END DO
      RETURN
      END
