!$LATLON
      SUBROUTINE LATLON(LLORB,AA,II,LL,MJDSBL,NM,FSECN,XSN,VSN,SSTS,    &
     &     OCDRYT,OCWETT,ETCOR,OTIDES,UTDT,ISATID)
!********1*********2*********3*********4*********5*********6*********7**
!     LATLON       9903                          PGMR - P. DAHIROC
!
!
!     FUNCTION: CODE TO OUTPUT SATELLITE LOCATION
!
!     I/O PARAMETERS:
!
!     NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!     ------  ---  ---   -----------------------------------------------
!     LLORB     I         .TRUE. - CALLS ORBIT
!                        .FALSE. - DOES NOT CALL ORBIT
!     AA      I/O   A
!     II      I/O   A
!     LL      I/O   A
!     MJDSBL   I         MODIFIED JULIAN DAY SECONDS OF THE FINAL
!                        RECEIVED TIME OF THE FIRST OBSERVATION IN
!                        THE BLOCK
!     NM       I         NUMBER OF MEASUREMENTS
!     FSECN    I    A    ELAPSED SECONDS FROM MJDSBL OF THE TIMES
!                        ASSOCIATED WITH OBSERVATION
!     XSN      I    A    XYZ S/C INERTIAL POSITIONS
!     VSN      I    A
!     SSTS     I    A    SEA SURFACE TOPOGRAPHY
!     OCDRYT   I    A    DRY TROPOSPHERIC CORRECTION
!     OCWETT   I    A    WET TROPOSPHERIC CORRECTION
!     ETCOR    I    A    EARTH TIDE  CORRECTION
!     OTIDES   I    A    OCEAN TIDE  CORRECTION
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL (L)
      SAVE
!
      COMMON/CALTOP/LADYNO,LAGEOO,LRGEOT,LRETDT,LROTDT,LRSSTT,LCOTRM,   &
     &              LFILOT,LATCOR,LFIRIT,LX1ALT,LX2ALT,LMSSWG,LATMOD,   &
     &              LG1BOT,LG1B,LONEG1,LXATTD,LXBEAM,NXALTO
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
!
      INTEGER :: I,J
      DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: CPXSN,CPVSN
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: FRSEC,STLAT,STLON,STH
      DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: XYSQ,OTPT1,OTPT2,THETA
      DIMENSION AA(1),II(1),LL(1),FSECN(NM),XSN(MINTIM,3),VSN(MINTIM,3)
      DIMENSION SSTS(NM),OCDRYT(NM),OCWETT(NM),ETCOR(NM),OTIDES(NM)
      DIMENSION UTDT(NM,4)
      DIMENSION DUM(3),DUM1(3,2,1)
!
!**********************************************************************
!* START OF EXECUPABLE CODE *******************************************
!**********************************************************************
!
      IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
      ENDIF

!
      ALLOCATE (FRSEC(NM),STLAT(NM),STLON(NM),STH(NM))
      ALLOCATE (XYSQ(NM),THETA(NM),OTPT1(NM),OTPT2(NM))
      ALLOCATE (CPXSN(MINTIM,3),CPVSN(MINTIM,3))

!     GET TRUE OF REF POSITION OF SATELLITE AT ALTIM RECEIVE IF NEEDED
      IF(LLORB) THEN
         CALL ORBIT(MJDSBL,FSECN,AA(KS),NM,II(KINDH),II(KNMH),          &
     &        II(KMJDSC),AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),    &
     &        II(KIPXPF),II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSN,         &
     &        AA(KPXPFM),.TRUE.,.FALSE.,II(KPLPTR),II(KPANEL),          &
     &        II(KNMOVE),AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),       &
     &        LL(KSETDN),                                               &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)

      END IF

      DO I = 1,MINTIM
         DO J = 1,3
            CPXSN(I,J) = XSN(I,J)
            CPVSN(I,J) = VSN(I,J)
         END DO
      END DO

!     %%%%%% pd: CONVERT TRUE OF REF -> TRUE OF DATE
      CALL SATUPD(MJDSBL,FSECN,XSN,XSN,AA,NM,MINTIM,.TRUE.,             &
     &     .FALSE.,II,0,1)
      CALL SATUPD(MJDSBL,FSECN,VSN,VSN,AA,NM,MINTIM,.FALSE.,            &
     &     .FALSE.,II,0,1)

!     %%%%%% pd: CALLS TO CALCULATE THETAG
      IF(ICBDGM.EQ.3) THEN
!     %%%%%% pd: FOR EARTH
         CALL GRHRAN(MJDSBL,FSECN,.TRUE.,.TRUE. ,AA(KEQN),AA(KSRTCH),   &
     &        THETA,OTPT1,OTPT2,NM,AA,II,UTDT(1,1),.FALSE.,DUM,DUM1)
      ELSE
!     %%%%%% pd: FOR OTHER PLANETS - SHOULD WE CALL ROTMTR FOR MARS?
         CALL ROTXTR(MJDSBL,FSECN,.TRUE.,AA(KEQN),AA(KSRTCH),           &
     &        THETA,OTPT1,OTPT2,NM,AA,AA(KACOSW),AA(KBSINW),AA(KANGWT), &
     &        AA(KWT),AA(KACOFW),AA(KBCOFW),II,1)
      ENDIF
!
      CALL SUBTRK(XSN,THETA,XYSQ,OTPT1,OTPT2,STLAT,STLON,STH,NM)
      MJDUTC = MJDSBL
      CALL UTCET(.FALSE.,NM,MJDUTC,FSECN,FRSEC,AA(KA1UT))
      DO I = 1,NM
         ISATLA = INT(STLAT(I)*1.0D6)
         IF(STLON(I).LT.0) THEN
            STLON(I) = STLON(I) + 360
         END IF
         ISATLO = INT(STLON(I)*1.0D6)
         TIME = MJDUTC + FRSEC(I)
         ISSTS = INT(SSTS(I)*1.0D3)
         IOCDRY = INT(OCDRYT(I)*1.0D3)
         IOCWET = INT(OCWETT(I)*1.0D3)
         IETCOR = INT(ETCOR(I)*1.0D3)
         IOTIDE = INT(OTIDES(I)*1.0D3)
         WRITE(UNIT=17,FMT=17) TIME,ISATLA,ISATLO,ISSTS,IOCDRY,         &
     &        IOCWET,IETCOR,IOTIDE
      END DO

      DO I = 1,MINTIM
         DO J = 1,3
            XSN(I,J) = CPXSN(I,J)
            VSN(I,J) = CPVSN(I,J)
         END DO
      END DO

   17 FORMAT(F20.8,I15,I15,I7,I7,I7,I7,I7)
      DEALLOCATE(FRSEC,STLAT,STLON,STH,XYSQ)
      DEALLOCATE(THETA,OTPT1,OTPT2,CPXSN,CPVSN)
      RETURN
      END
