      SUBROUTINE LDELXS(PARMV,DELXST,NXSTAT,NSATS,NSETS)
!********1*********2*********3*********4*********5*********6*********7**
! LDELXS                                         PGMR - D. ROWLANDS
!
!
! FUNCTION:  LOAD DELTA STATE VALUES INTO WORKING ARRAY
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PARMV    I    A    PARAMETER VALUE ARRAY
!   DELXST   O    A    WORKING ARRAY OF DELTA STATE VALUES
!   NXSTAT   I    A    NUMBER OF DELTA STATE EPOCHS FOR EACH SATELLITE
!                      SET
!   NSATS    I    A    NUMBER OF SATELLITE INE EACH SET
!   NSETS    I    S    NUMBER OF SATELLITE SETS IN ARC
!
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/IDELTX/MXSTAT,NEVENTS,NDSTAT,IDSYST,NDELTX
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
!
      DIMENSION PARMV(1)
      DIMENSION DELXST(6,MXSTAT,MSATG,NSETS)
      DIMENSION NXSTAT(NSETS),NSATS(NSETS)
!
      IPOINT=IPVAL(IXDXYZ)
!
      DO 1000 ISET=1,NSETS
      NUMPD=NXSTAT(ISET)
      IF(NUMPD.LE.0) GO TO 1000
      NSAT=NSATS(ISET)
      DO 900 ISAT=1,NSAT
      DO 600 IPD=1,NUMPD
      DO 500 IC=1,6
      DELXST(IC,IPD,ISAT,ISET)=PARMV(IPOINT)
      IPOINT=IPOINT+1
  500 END DO
  600 END DO
  900 END DO
 1000 END DO
      RETURN
      END
