      SUBROUTINE LDPMPP(NDIM,NDIM1,NDIM2,SCRTCH,WT,PMPP,NOBS)
!********1*********2*********3*********4*********5*********6*********7**
! LDPMPP                                         PGMR - D. ROWLANDS
!
!
! FUNCTION:  LOAD PARTIAL DERIVATIVES INTO PMPP ARRAY FROM SCRATCH FILE
!            DURING MATRIX PARTITIONING (ALSO OBSERVATION WEIGHTS)
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   NDIM     I    S    NUMBER OF WORDS THAT WERE WRITTEN
!                      TO SCRATCH FILE FOR EACH OBSERVATION
!   NDIM1    I    S    NUMBER OF PARTIAL DERIVATIVES THAT WILL BE LOADED
!                      TO PMPP ARRAY FOR EACH OBSERVATION
!   NDIM2    I    S    MAXIMUM NUMBER OF OBSERVATIONS THAT CAN BE LOADED
!                      IN THIS CALL
!   SCRTCH   I    A    SCRATCH ARRAY
!   WT       O    A    WEIGHTS ASSIGNED TO OBSERVATIONS
!                      BE ADDED TO COMPUTED OR SUBTRACTED FROM OBSERVED
!   PMPP     O    A    PARTIAL DERIVATIVES
!   NOBS     O    S    NUMBER OF OBSERVATIONS LOADED IN THIS CALLL
!
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION SCRTCH(NDIM),WT(NDIM2),PMPP(NDIM1,NDIM2)
!
      NOBS=0
      JPT=NDIM-NDIM1
!
      DO 100 I=1,NDIM2
      CALL PARTRD(SCRTCH,LEOF)
      IF(LEOF) GO TO 200
      NOBS=NOBS+1
      WT(NOBS)=SCRTCH(1)
      IF(WT(NOBS).LT.0.D0) THEN
        WRITE(6,6000)
        WRITE(6,6001)
        WRITE(6,6002)
        WRITE(6,6003)
        WRITE(6,6004)
        STOP
      ENDIF
      DO 50 J=1,NDIM1
      PMPP(J,NOBS)=SCRTCH(JPT+J)
   50 END DO
  100 END DO
  200 CONTINUE
 6000 FORMAT(' EXECUTION TERMINATING IN LDPMPP')
 6001 FORMAT(' NEGATIVE WT ENCOUNTERD WHILE READING')
 6002 FORMAT(' PARTIAL DERIVATIVE FILE. THIS WAY OF')
 6003 FORMAT(' NORMAL MATRIX PARTITIONING (SMPRT2) ')
 6004 FORMAT(' NOT INTENDED TO WORK WITH EBIASES ')
      RETURN
      END
