!$LITE2P
      SUBROUTINE LITE2P(X4,X1,X2,X3,R,WORK,WORK2,WORK3,WORK4,MJDS1,     &
     &         FSEC1,FSEC2,SIGNL,DELCET,RSS,GRLLT,CBSTAT,NM,            &
     &         SCRTM,TPMEAS,LTPMES,COSTHG,SINTHG,AA,II,LL)
!********1*********2*********3*********4*********5*********6*********7**
! LITE2P           95/11/20                      PGMR - DESPINA PAVLIS
!
! FUNCTION:  ITERATIVELY COMPUTE THE LIGHT TIME BETWEEN POINTS
!            #1 AND #2 ASSUMING THAT THE EPOCH OF POINT #1 IS
!            KNOWN AND THAT POINT #2 IS A SPACECRAFT
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   X1       I    A    INERTIAL TRUE OF REF POSITION VECTORS FOR
!                      POINT #1
!   X2       O    A    INERTIAL TRUE OF REF POSITION VECTORS FOR
!                      POINT #2
!   X3       I    A    E.C.F TARGET COORDINATES
!   R        O    A    SLANT RANGE FROM POINT #1 TO POINT #2
!   WORK          A    USED FOR PREVIOUS VALUES OF FSEC2 AND
!                      FOR ITERATIVE DIFFERENCES OF FSEC2
!   WORK2         A
!   WORK3         A
!   WORK4         A
!   MJDS1    I    S    MODIFIED JULIAN DATE SECONDS OF THE FIRST
!                      TIME POINT
!   FSEC1    I    A    ELAPSED SECONDS SINCE MJDS1 FOR POINTS #1
!   FSEC2   I/O   A    ELAPSED SECONDS SINCE MJDS1 FOR POINTS #2 AS
!                      OUTPUT
!                      FIRST ESTIMATE OF ELAPSED SECONDS SINCE
!                      MJDS1 FOR POINTS #2 AS INPUT
!   SIGNL    I    S    SIGN OF THE LIGHT TIME (+1. OR -1.)
!   DELCET   O    A    DIFFERENCE BETWEEN AVERAGE EPHENERIS TIME
!                      CORRECTION AND ACTUAL.
!   RSS      O    A    RANGE FROM SATELLITE TO SUN AT SAT TIME
!   GRLLT    O    A    GEN REL LIGHT TIME CORRECTION
!   CBSTAT   O    A    CEENTER OF INTEGRATION STATE
!   NM       I    S    NUMBER OF LIGHT TIMES TO BE COMPUTED
!   SCRTM
!   TPMEAS   O    A    TOPEX ATT VALUES FOR USE IN MEAS. MODEL
!   LTPMES   O    A    TOPEX ATT VALUES FOR USE IN MEAS. MODEL
!   COSTHG   I    A    COS(THETAG)
!   SINTHG   I    A    SIN(THETAG)
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBARYC/CBODY(6),TBODY(6),SUNRF(6)
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CHCOEF/ COEFM(3,15),COEFJ(3,15),COEFSA(3,15),COEFS(3,15),  &
     &               COEFEM(3,15),COEFMO(3,15),COEF(3,15)
      COMMON/CHCOFX/ COEFX(3,25),COEFXX(3,25,988),RLVAL(988)
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CRELAT/AER(11),GRLFC2(11),GRLFC3(11),SECCOR
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/LEPHM2/LXEPHM
      COMMON/NLIGHT/KNTLIM,NXNLIT
      COMMON/XLITSD/DELULT,DDLULT,UNVLTU(3),DELDLT,DDLDLT,UNVLTD(3),    &
     &              GRELLT,TOLLTX,GRLFCT,FCTJUP,FCTSAT
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! THE S/C ARRAY BEING DIMENSIONED BY (MINTIM,3,6,2) ALLOWS YOU TO
! TEMPORARILY ACCESS ARRAY SPACE SET ASIDE FOR OTHER S/C AND STATION
! POSITION AND VELOCITY ARRAYS DIMENSIONED IN MTSTST.
!
      DIMENSION X2(MINTIM,3,6,2),X1(MINTIM,3),R(NM),WORK(NM),WORK2(NM), &
     &   FSEC1(NM),FSEC2(NM),WORK3(NM),WORK4(NM),DELCET(NM),RSS(NM),    &
     &   GRLLT(NM),CBSTAT(NM,6),AA(1),II(1),LL(1),                      &
     &   SCRTM(NM,90),TPMEAS(MINTIM,2),LTPMES(MINTIM,3)
      DIMENSION X3(3),X4(MINTIM,3),COSTHG(NM),SINTHG(NM)
      DATA ZERO/0.0D0/,ONE/1.D0/
! GRLFC3 IS 2*GM/(C**3) ; BHN IS A SCALE FACTOR BETWEEN CLOCKS ON GEOID
! VS CLOCKS AT EARTH'S CENTER
!      DATA GRLFC3/.29587322D-10/  NOW IN CB CRELAT
      DATA BHN/6.9693D-10/
      CINVRS=SIGNL/VLIGHT
      KOUNT=0
      LCOUNT=.FALSE.
      IF(ITBDGM.EQ.ICBDGM) THEN
      WRITE(6,*)'  EXECUTION TERMINATING IN LITE2P, THIS MUST BE AN '
      WRITE(6,*)'  INTERPLANETARY CASE '
      STOP
      ENDIF
!
! CASE WHEN TRACKING BODY IS NOT SAME AS CENTER OF INTEGRATION
      CINVR=SIGNL*CINVRS
!
! IF NECESSARY, CORRECT FSEC1 TO GET COORDINATE TIME. THIS REQUIRES
! EVALUTAION OF THE EPHEMERIS WITH THE APPROX COORDINATE TIME AT THE
! TRACKING STATION POSITIONS. UNTIL A FIXUP IS TAKEN, THE EPHEMERIS
! WILL HAVE TO BE RE EVALUATED WITH THE CORRECT COORDINATE TIME AT
! THE STATIONS IN ORDER TO GET THE RANGE. IT COULD BE ARRANGED THAT
! SUBROUTINE LITPRX WOULD EVALUATE THE LARGEST TERM (TERM1) IN THE
! CORRECTION EXPRESSION. THE EPHEMERIS COULD BE EVALUATED TAKING INTO AC
! THAT TERM. THE REST OF THE COORECTION IS PROBABLY SMALL ENOUGH SO THAT
! THE EPHEMERIS COULD BE CORRECTED BY VELOCITIES. ANOTHER APPROACH WOULD
! BE TO GET THE CORRECTION AT ENDPOINT TIMES AND INTERPOLATE.
!
!
      CALL BUFXTR(MJDS1,FSEC1(1),MJDS1,FSEC1(NM),1,MJDR,FSECR,LRECAL,AA)
!
      IF(LXEPHM) THEN
      DO IJ=1,ICBODY
!     write(6,*)' dbg LITE2P calls BUFSUP '
      CALL BUFSUP(AA,MJDS1,FSEC1(1),MJDS1,FSEC1(1),II(KISUPE),          &
     &            AA(KEPHMS),IJ,1)
      ENDDO
      ENDIF
!
!     DO 10050 N=1,NM
      CALL COORDT(MJDS1,FSEC1,IORJ,IORSA,IOREM,IORMO,IORSUN,IORM,       &
     &            COEFJ,COEFSA,COEFEM,COEFMO,COEFS,COEFM,               &
     &            NM,X1,DELCET,SCRTM(1,56),SCRTM(1,62),SCRTM(1,44),     &
     &            SCRTM(1,1),SCRTM(1,1),SCRTM(1,1),                     &
     &            SCRTM(1,2),SCRTM(1,17),SCRTM(1,2),SCRTM(1,17),        &
     &            SCRTM(1,2),SCRTM(1,17),SCRTM(1,32),SCRTM(1,38),       &
     &            SCRTM(1,44),SCRTM(1,50),SCRTM(1,2),SCRTM(1,8),        &
     &            SCRTM(1,11),WORK)
!10050 CONTINUE
!
!
! USE THE LIGHT TIME AND THE DERIVITIVE OF LIGHT TIME WRT TIME
! CALCULATED IN EXEC2E AS A FIRST GUESS
      FACT1=SIGNL*DELULT
      FACT2=ONE+SIGNL*DDLULT
!     PRINT*,' FACT ',FACT1,FACT2
      DO 10100 N=1,NM
      WORK(N)=FACT1+FACT2*(FSEC1(N)+DELCET(N))
10100 END DO
!
! ADJUST THE LIGHT TIME FOR TRACKING BODY STATION POSITIONS
      FACT1=CINVRS*UNVLTU(1)
      FACT2=CINVRS*UNVLTU(2)
      FACT3=CINVRS*UNVLTU(3)
      DO 10200 N=1,NM
      FSEC2(N)=WORK(N)+FACT1*X1(N,1)+FACT2*X1(N,2)+FACT3*X1(N,3)
10200 END DO
!******8DEBUG****************
!     PRINT*,' FSEC@1 ',FSEC1(1)
!     PRINT*,' FSEC@2 ',FSEC2(1)
!     PRINT*,' WORK ',WORK(1)
!     PRINT*,' FACT ',FACT1,FACT2,FACT3
!     PRINT*,' X1   ',X1(1,1),X1(1,2),X1(1,3)
!***************************
!
! GET MARS COSTHG AND SINTHG
      CALL ROTXTR(MJDS1,FSEC2,.FALSE.,AA(KEQN),AA(KSRTCH),             &
     &         AA(KTHETG),COSTHG,SINTHG,NM,AA,AA(KACOSW),              &
     &         AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),AA(KBCOFW),II,1)
!
! GET TRUE OF DATE INERTIAL COORDINATES OF TARGET
      CALL INERPL(X3,COSTHG,SINTHG,X2(1,1,1,1),NM,MINTIM)
!
! OBTAIN THE POSTION OF THE TARGET IN THE TRUE OF REFERENCE INERTIAL
! SYSTEM CENTERED AT THE AT THE PLANET
!
      CALL SATUPD(MJDS1,FSEC2,X2(1,1,1,1),X2(1,1,3,1),AA,NM,MINTIM,     &
     &            .TRUE.,.TRUE.,II,0,1)
!
      DO 10300 N=1,NM
      FSEC2(N)=FSEC2(N)-FACT1*X2(N,1,3,1)-FACT2*X2(N,2,3,1)             &
     &        -FACT3*X2(N,3,3,1)
!
10300 END DO
!******8DEBUG****************
!     PRINT*,' FSEC@2 ',FSEC2(1)
!     PRINT*,' FACT ',FACT1,FACT2,FACT3
!     PRINT*,' X2   ',X2(1,1,3,1),X2(1,2,3,1),X2(1,3,3,1)
!***************************
! ASSUME THAT THE TRACKING BODY (EARTH) COMES FROM THE JPL EPHEMERIS
! LATER WORK ON EARTH COMING FROM THE SUPPLEMENTARY EPHEMERIS.
! SO THE FIRST CALL TO BARYC WILL REMAIN THE SAME. WE NEED TO CHANGE THE
! SECOND CALL TO BARYC TO CALL THE ALTERNATE BARYCX
!***************************
!
! BEFORE BEGIN ITERATIVE LOOP TO RIGOROUSLY GET AND CHECK LIGHT TIME
! NEED TO GET BARYCENTRIC TRACKING BODY POSITION AT FSEC1
      DO 10600 N=1,NM
      WORK3(N)=FSEC1(N)+DELCET(N)
10600 END DO
      CALL BARYC(MJDS1,WORK3,X1,X1,MINTIM,IGRP,IORTB,IORMO,IORSUN,IOREM,&
     &           COEFEM,COEFMO,COEFS,COEFEM,NM,NDIM1,NDIM2,             &
     &           .FALSE.,.TRUE.,.TRUE.,AA(KPRCBD),AA(KPRTBD),           &
     &           SCRTM(1,1),SCRTM(1,74),SCRTM(1,68),                    &
     &           SCRTM(1,10),SCRTM(1,25),SCRTM(1,10),SCRTM(1,25),       &
     &           SCRTM(1,10),SCRTM(1,25),                               &
     &           SCRTM(1,64),SCRTM(1,65),SCRTM(1,66),AA,II)
!    5           SCRTM(1,40),SCRTM(1,52),
      DO 10700 N=1,NM
      WORK2(N)=SCRTM(N,74)*SCRTM(N,74)+SCRTM(N,75)*SCRTM(N,75)+         &
     &         SCRTM(N,76)*SCRTM(N,76)
      GRLLT(N)=SQRT(WORK2(N))
10700 END DO
!
! BEGIN ITERATIVE LOOP TO GET FSEC2
11000 CONTINUE
      KOUNT=KOUNT+1
!
      CALL ROTXTR(MJDS1,FSEC2,.FALSE.,AA(KEQN),AA(KSRTCH),              &
     &            AA(KTHETG),COSTHG,SINTHG,NM,AA,AA(KACOSW),            &
     &            AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),AA(KBCOFW),  &
     &            II,1)
!
!
      CALL INERPL(X3,COSTHG,SINTHG,X2(1,1,1,1),NM,MINTIM)
!
      CALL SATUPD(MJDS1,FSEC2,X2(1,1,1,1),X4,AA,NM,MINTIM,              &
     &            .TRUE.,.TRUE.,II,0,1)
!
      DO 11105 N=1,NM
! TEMPORARILY LOAD TOR INTO THE FIRST SLOT
      X2(N,1,1,1)=X4(N,1)
      X2(N,2,1,1)=X4(N,2)
      X2(N,3,1,1)=X4(N,3)
11105 END DO
!
!     PRINT*,' FSEC@2 AFTER INERPL 2   ',FSEC2(1)
!
      IF(LXEPHM.AND.ICBDGM.GT.11) GO TO 11106
      CALL BARYC(MJDS1,FSEC2,X2,X2(1,1,1,2),MINTIM,IGRP,                &
     &           IORCB,IORMO,                                           &
     &           IORSUN,IOREM,COEF,COEFMO,COEFS,COEFEM,                 &
     &           NM,NDIM1,NDIM2,.FALSE.,.FALSE.,.TRUE.,AA(KPRCBD),      &
     &           AA(KPRTBD),SCRTM(1,1),SCRTM(1,7),SCRTM(1,10),          &
     &           SCRTM(1,16),SCRTM(1,31),SCRTM(1,16),SCRTM(1,31),       &
     &           SCRTM(1,16),SCRTM(1,31),                               &
     &           SCRTM(1,46),SCRTM(1,47),SCRTM(1,48),AA,II)
      GOTO 11107
11106  CONTINUE
      CALL BARYCX(MJDS1,FSEC2,X2,X2(1,1,1,2),MINTIM,IGRP,               &
     &           IORCB,IORMO,                                           &
     &           IORSUN,IOREM,COEFX,COEFMO,COEFS,COEFEM,                &
     &           NM,NDIM1,NDIM2,.FALSE.,.FALSE.,.TRUE.,AA(KPRCBD),      &
     &           AA(KPRTBD),SCRTM(1,1),SCRTM(1,7),SCRTM(1,10),          &
     &           SCRTM(1,16),SCRTM(1,31),SCRTM(1,16),SCRTM(1,31),       &
     &           SCRTM(1,16),SCRTM(1,31),                               &
     &           SCRTM(1,46),SCRTM(1,47),SCRTM(1,48),AA,II)
11107  CONTINUE
!
      IF(KOUNT.GT.1) GO TO 11110
!  SOME QUANTITIES NECESSARY FOR GENERAL REL LIGHT TIME
      DO 11100 N=1,NM
      RSS(N)=SQRT(SCRTM(N,7)*SCRTM(N,7)+SCRTM(N,8)*SCRTM(N,8)          &
     &            +SCRTM(N,9)*SCRTM(N,9))
      GRLLT(N)=GRLLT(N)+ RSS(N)
11100 END DO
11110 CONTINUE
!   GET RANGE
      DO 11115 N=1,NM
      WORK(N) =X2(N,1,1,1)-X1(N,1)
      WORK2(N)=X2(N,2,1,1)-X1(N,2)
      WORK3(N)=X2(N,3,1,1)-X1(N,3)
      WORK4(N)=WORK(N)*WORK(N)+WORK2(N)*WORK2(N)                        &
     &        +WORK3(N)*WORK3(N)
      R(N)=SQRT(WORK4(N))
!   GET DERIV OF RANGE USED IN LIGHT TIME SOLUTION. DIVIDE BY VLIGHT
! DEP
! Assume that the target velocity is zero
!
      X2(N,1,1,2)=0.D0
      X2(N,2,1,2)=0.D0
      X2(N,3,1,2)=0.D0
! DEP
      WORK4(N)= (WORK(N)*X2(N,1,1,2)                                    &
     &          +WORK2(N)*X2(N,2,1,2)                                   &
     &          +WORK3(N)*X2(N,3,1,2))*CINVR
      WORK4(N)=WORK4(N)/R(N)
11115 END DO
      IF(KOUNT.GT.1) GO TO 11120
! FINISH CALCULATING THE GEN REL LIGHT TIME
!
! .... CALCULATE JUPITER AND SATURN CONTRIBUTION TO LIGHT TIME DELAY
! .... AND STORE IT IN SCRTM(1-NM,1) AND SCRTM(1-NM,2)
      CALL LITDEL(MJDS1,FSEC2,X1,X2,MINTIM,R,SCRTM(1,1),SCRTM(1,2),     &
     &            SCRTM(1,3),SCRTM(1,4),SCRTM(1,5),SCRTM(1,8),          &
     &            SCRTM(1,11),SCRTM(1,26),NM,SCRTM(1,41),SCRTM(1,42))
!
      DO 11118 N=1,NM
      WORK(N)=(GRLLT(N)+R(N))/(GRLLT(N)-R(N))
      WORK2(N)=LOG(WORK(N))
      GRLLT(N)=(WORK2(N)*GRLFCT) + SCRTM(N,1) + SCRTM(N,2)
11118 END DO
11120 CONTINUE
!   USE DERIV/VLIGHT TO GET A BETTER ESTIMATE OF RANGE & LIGHT TIME
      ERRMAX=ZERO
      DO 11130 N=1,NM
      WORK(N)=WORK4(N)*WORK4(N)-WORK4(N)
      WORK3(N)=SIGNL*(FSEC2(N)-FSEC1(N)-DELCET(N))
      WORK2(N)=R(N)*CINVR-WORK3(N)+GRLLT(N)
      WORK2(N)=WORK(N)*WORK2(N)+GRLLT(N)
      WORK(N)=R(N)*CINVR+WORK2(N)
! WORK CONTAINS NEW LIGHT TIME & WORK3 CONTAINS THE PREVIOUS
      WORK2(N)=WORK(N)-WORK3(N)
      WORK4(N)=ABS(WORK2(N))
      ERRMAX=MAX(WORK4(N),ERRMAX)
      FSEC2(N)=SIGNL*WORK(N)+FSEC1(N)+DELCET(N)
11130 END DO
!******8DEBUG****************
!     PRINT*,' FSEC@3 ',FSEC2(1)
!     PRINT*,' WORK ',WORK(1)
!     PRINT*,' SIGNL ',SIGNL
!     PRINT*,' DELCET ',DELCET(1)
!***************************
      LAST=ERRMAX.LT.TOLLTX
      IF(KOUNT.LT.4) GOTO 11000
      IF(KOUNT.LT.KNTLIM.AND..NOT.LAST) GO TO 11000
      RETURN
      END
