      SUBROUTINE LOADAX(AX,AX2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION AX(3,3),AX2(3,3)
      COMMON/VAXINT/XAXIS(3,3,3)
      DO I=1,9
        XAXIS(I,1,1)=AX(I,1)
        XAXIS(I,1,2)=AX2(I,1)
      ENDDO
      RETURN
      END
