!$LPLNOP
      SUBROUTINE LPLNOP(PARMV,PARMVC,PARMV0,MJDSEC,LFLAG,ACOEFW,BCOEFW, &
     &                  ANGWT,PLANDX,PLANC,PPER,LAX )
!********1*********2*********3*********4*********5*********6*********7**
! LPLNOP          00/00/00            0000.0    PGMR -  DAVE ROWLANDS
!
!
! FUNCTION: INITIALIZE PLANET ORIENTATION PARAMETERS ONCE PER RUN
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PARMV    O    A    PARAMETER VALUES ARRAY STARTING AT PLANET
!                      ORIENTATION
!   PARMVC   O    A    CURRENT VALUES FOR ALL ADJUSTED PARAMETERS
!   PARMV0   O    A    INITIAL VALUES FOR ALL ADJUSTED PARAMETERS
!                      STARTING AT PLANET ORIENTATION
!   LFLAG    I    S    =.FALSE. THIS IS THE FIRST GLOBAL, JUST LOAD
!                      THE PARAMETER VALUES
!                      =.TRUE. THIS IS NOT THE FIRST GLOBAL, UPDATE
!                      THE PARAMETER VALUES IN PNCXN/NPNCXN
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/DNUTAT/RAPXTR(1),DCPXTR(1),DNUTXR(8),SMDNUT(30)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/PRXCON/PRXCON(2,2,2)
      COMMON/THXTGC/THXTGC(3,2)
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
!
      DIMENSION PARMV(*),PARMVC(*),PARMV0(*)
      DIMENSION ACOEFW(1),BCOEFW(1),ANGWT(1)
      DIMENSION PLANDX(*),PLANC(*),PPER(1)
! %%%%%%% ALL (*) USED TO BE (1)
!
      DATA FIVE/5.D0/,DAY/86400.D0/
      DATA ZERO/0.D0/
!
       IDIM1=7+2*NXALLC
!
      DO 10 I=1,NXALLC
      ANGWT(I)=TWOPI/PPER(I)
   10 END DO
!
      HOLD=FSDINP(1)
      FSDINP(1)=T0XTRO
      IF(NEPHEM.GE.200) THEN
       IF(ICBDGM.LE.11) THEN
         CALL NPNCXN(1,LFLAG,.TRUE.,IDIM1)
       ELSE
         ICB=ICBDGM-11
         CALL NPNCXX(1,LFLAG,.TRUE.,IDIM1,ICB)
       ENDIF
      ELSE
         CALL PNCXN(1,LFLAG,.TRUE.,PLANC,IDIM1)
      ENDIF
!
!
        IF(NXALLC.GT.0) THEN
      DO 40 I=1,NXALLC
      ACOEFW(I)=PARMV(7+I)
      BCOEFW(I)=PARMV(7+NXALLC+I)
   40 END DO
        ENDIF


!
      FSDINP(1)=HOLD
      RETURN
      END
