!$OBSIO
      SUBROUTINE OBSIO(AA,OBSBF1,OBSBF2,JDIM,MAXREC)
!********1*********2*********3*********4*********5*********6*********7**
! OBSIO            00/00/00            0000.0    PGMR - BILL EDDY
!
! FUNCTION:  READ SEQUENTIAL BINARY OBSERVATION FILE AND OUTPUT
!            AS A DIRECT ACCESS FILE
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   OBSBF1   I    A    BUFFER USED FOR READING OBSERVATIONS
!   OBSBF2   I    A    BUFFER USED FOR OBSERVATIONS AFTER THEY
!                      HAVE BEEN CONVERTED FROM IBM TO CYBER
!                      FLOATING POINT(USED ONLY WHEN RUNNING IIE
!                      ON THE CYBER)
!   JDIM     I    S    SIZE OF THE PHYSICAL BLOCK USED BY IIS FOR
!                      OBSERVATIONS
!   MAXREC        S
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CLASCI/LASCII,LIFCYB,LARECL,NXLASC
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
!
      DIMENSION AA(1)
      DIMENSION OBSBF1(JDIM),OBSBF2(JDIM)
!
      DATA IREC/0/
!
!**********************************************************************
! START OF EXECUTABLE CODE
!**********************************************************************
!
!     PRINT 90100,JDIM
!90100 FORMAT(1X,'OBSIO -JDIM',I5)
! READ SEQUENTIAL OBSERVATION FILE CREATED BY IIS
  100 CONTINUE
      IF(LASCII) THEN
       IF(LARECL) THEN
       READ(IUNT12,17000,END=1000) OBSBF1
       ELSE
       READ(IUNT12,18000,END=1000) OBSBF1
       ENDIF
      ELSE
       READ(IUNT12,END=1000  ) OBSBF1
      ENDIF
      IREC=IREC+1
!
! WRITE DIRECT ACCESS FILE
!
! CONVERT FLOATING POINT NUMBERS FROM 32-BIT TO 64-BIT
      CALL Q9ICLA(OBSBF1,OBSBF2,JDIM,ISTAT)
      IF(ISTAT.NE.0) GO TO 60100
      CALL DWRITE(IUNT13,IREC,OBSBF2)
      GO TO 100
! NORMAL EXIT
 1000 REWIND IUNT12
!     PRINT 90120,IREC
!90120 FORMAT(1X,'EXITING OBSIO LAST PHYSICAL DATA RECORD STORED = ',I6)
      RETURN
17000 FORMAT(BZ,3D24.16)
18000 FORMAT(BZ,5D24.16)
60100 WRITE(IOUT6,80100) ISTAT,IREC
      STOP
80100 FORMAT(1X,'SUBROUTINE Q9ICLA RETURNED STATUS CODE ',I4,           &
     &  'FOR DATA RECORD NUMBER ',I6,'IN SUBROUTINE OBSIO' )
      END
