!$OBSRD
      SUBROUTINE OBSRD (AA,II,LL,OBSBUF,PARMVC,LPBIAS, &
     &   INDSTA,INDSAT,INDSET,INPSTA,INPSAT,LELEVS,LEOF,FSCSDM,QUAINF,  &
     &   IPTRAU,IPTRUA,PNAME ,ILCORR,                                   &
     &   ITMRA1,ITMRA2,FRSTRT,FRRATE,LAVOID,PARML0,NDIR,IDWPT)
!********1*********2*********3*********4*********5*********6*********7**
! OBSRD            00/00/00            0000.0    PGMR - T. MARTIN
!
! FUNCTION: CONTROLS THE READING AND REWRITING OF OBSERVATION DATA
!           AND THE COMPUTATION OF MEMORY POINTERS NECESSARY FOR
!           DATA PROCESSING
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!  isdwrd   I     S    length of observation buffer (VAX)
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   OBSBUF  I/O   A    OBSERVATION BUFFER CONSISTING OF THE LOGICAL
!                      OBSERVATION RECORDS THAT MAKE UP ONE BLOCK
!                      OF DATA
!   PARMVC   I    A    CONTAINS CURRENT VALUES FOR ADJUSTED PARAMETERS
!   LPBIAS   I    A    LOGICAL ARRAY USE TO INDICATE PASS BY PASS BIASES
!   INDSTA   O    A    FOR A GIVEN INTERNAL STA NO (1,2,3) INDSTA
!                      GIVES THE ACTUAL LOCATION IN THE STATION
!                      RELATED ARRAYS FOR THIS STATION.
!                      (EG.   STA NO=ISTANO(INDSTA(1,2,OR 3))
!   INDSAT   O    A    FOR A GIVEN INTERNAL SAT NO (1,2,3) INDSAT
!                      GIVES THE ACTUAL LOCATION IN THE SATELLITE
!                      RELATED ARRAYS FOR THIS SATELLITE.
!                      (EG.   SAT ID=ISATNO(INDSAT(1,2,OR 3))
!   INDSET   O    A    FOR A GIVEN INTERNAL SATELLITE NUMBER INDSET TELL
!                      WHICH SAT SET THAT THE GIVEN SAT BELONGS TO.
!   INPSTA   O    A    POINTER ARRAY THAT RELATES THE INTERNAL STATION
!                      NUMBER (1,2,3) TO THE STATIONS DEFINED IN THE
!                      DATA HEADER RECORDS (N=1,2,3). (EG.
!                      ISTAP=INPSTA(1) WOULD TELL WHICH OF THE THREE
!                      POSSIBLE STATIONS DEFINED IN THE DATA HEADER
!                      RECORDS PERTAINED TO INTERNAL STATION NO. 1)
!   INPSAT   O    A    POINTER ARRAY THAT RELATES THE INTERNAL SATELLITE
!                      NUMBER (1,2,3) TO THE SATELLITES DEFINED IN THE
!                      DATA HEADER RECORDS (N=1,2,3). (EG.
!                      ISATP=INPSAT(1) WOULD TELL WHICH OF THE THREE
!                      POSSIBLE SATELLITES DEFINED IN THE DATA HEADER
!                      RECORDS PERTAINED TO INTERNAL SATELLITE NO. 1)
!   LELEVS  I/O   A    INDICATES WHICH ELEVATION ANGLES NEED TO BE
!                      COMPUTED FOR THE THREE POSSIBLE STATION SATELLITE
!                      CONFIGURATIONS DEFINED IN THE BLOCK HEADER
!                      RECORDS
!   LEOF    I/O   S    LOGICAL FLAG SET TO .TRUE. WHEN ALL THE
!                      OBSERVATION DIRECTORY RECORDS HAVE BEEN READ
!   FSCSDM  I/O   A    FRACTIONAL RECORDS OF MEASUREMENT TIMES FOR
!                      SIMULATED DATA GENERATION
!   ITMRA1   O    A    START TIMES FROM THE RAMP TABLES
!   ITMRA2   O    A    STOP TIMES FROM THE RAMP TABLES
!   FRSTRT   O    A    FREQUENCIES FROM THE RAMP TABLES
!   FRRATE   O    A    FREQUENCY RATES FROM THE RAMP TABLES
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      PARAMETER ( METRIX = 37 )
      PARAMETER ( ZERO   = 0.0D0 )
      PARAMETER ( HALF   = 0.5D0 )
      PARAMETER ( ONE    = 1.0D0 )
      PARAMETER ( TWO    = 2.0D0 )
      PARAMETER ( TEN12  = 1.0D12 )
!
      COMMON/LDATOR/LDQAT,LDVCT
      COMMON/LIMAGE/LIMG,LIMCALL,LIMAT,LIMCAM
      COMMON/BIAOR/NAMBB,NCYCB,NAMBBH
      COMMON/CALTOP/LADYNO,LAGEOO,LRGEOT,LRETDT,LROTDT,LRSSTT,LCOTRM,   &
     &              LFILOT,LATCOR,LFIRIT,LX1ALT,LX2ALT,LMSSWG,LATMOD,   &
     &              LG1BOT,LG1B,LONEG1,LXATTD,LXBEAM,NXALTO
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CBIASL/LEBIAS(4),LMBIAS(2),LBSCAL(1)  ,LTBIAS(1),          &
     &              LBTROP(3),LBIONO(3),LCLSTA(4,2),LCLSAT(4,2),        &
     &              LKLSTS(2,2),LTRPZE(2,2),LTRPGR(2,4),LBSBIA(1),      &
     &              LNBIAS
      COMMON/CBINRI/NSATB,NSTAB,INMSAT(3),INMSTA(3)
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CBLOKV/QUANO(3),EHAT(3),DEDA(3),DEDD(3),EFLG
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CLSSOT/LSSTMO,LOTMOD,LPRDES,NXLSST
      COMMON/CLPRNR/LPR9NR(24),LPRNRM(24,3)
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/COBBUF/IOBSBF,IBUF1 ,IBUF2 ,IWORD1,NHEADR,NWORDM
      COMMON/COBDIR/DWORD(100),CDIREC,TDIREC
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/COBREL/KDELCT(6,8)
      COMMON/CON2E/KCNBST0,KCNBST1,KBUP110,KBUP111,KBPA110,KBPA111,KDIST&
     &            ,KDSIG
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/CTIDES/NTIDE,NSTADJ,NET,NETADJ,NETUN,NOT,NOTADJ,           &
     &   NOTUN ,NETUNU,NETADU,NOTUNU,NOTADU,NBSTEP,KTIDA(3),            &
     &   ILLMAX,NUNPLY,NNMPLY,NDOODN,MXTMRT,NRESP ,NXCTID
      COMMON/CYCSLP/LCYCTB
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/GPSBLK/LGPS,LNOARC,LSPL85,NXGPS
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IMAG2E/KXIMG,KIMBST,KIMOBL,KIMBUP,KIMBPA
      COMMON/IRAMPS/INDRAM,KKRAMP
      COMMON/IOBTYP/NDXST(2,35),NDXSAT(2,35),                           &
     &      NDRSTA(50),NDRSAT(50),NDRST2(50),NDRSA2(50),                &
     &      ITMBIT(999),IOETR(999),MTYPED(11),NTYPES,                   &
     &      NM0112(4),NM1314(4),NM1522(4),NM2330(4),                    &
     &      NM3138(4),NM3997(4),NM4098(4),NM9900(4),NMT199(4),NMT203(4),&
     &      NS0112(4),NS1314(4),NS1522(4),NS2330(4),                    &
     &      NS3138(4),NS3997(4),NS4098(4),NS9900(4),NST199(4),NST203(4),&
     &      ITYPD(12,2),ITYPDD(7,2),ILINKF(5),ISTAFN(5,3),              &
     &      ISATFN(5,3),ILINKT(5),ISTATN(5,3),ISATTN(5,3),              &
     &      MGOTO(12),MENTER(12),MEXIT(12),                             &
     &      NDST60(3,24),NDST82(6,12),NDST92(12,7),NTDRSS,              &
     &      NDSA60(3,24),NDSA82(6,12),NDSA92(12,7),                     &
     &      MTDRSS(7),KTDRSS(7),ITDRSS(4,7),JTDRSS(4,7),                &
     &      NLLC60(5,24),NLLC82(10,12),NLLC98(20,7),NNBIA,              &
     &      NXMTYP
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/KINETEX/ORBIAS
      COMMON/KPRE/IKPRE9,IKPRE(3)
      COMMON/LANTID/LANTBD,LASALT
      COMMON/LBTYPE/LCLOCK
      COMMON/LMARIN/ LRADEC, LMARIN, LPASCU, NXLMAR
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/NUDITY/INUDP,INUDT,INUDF
      COMMON/OCLRA /LOCLRA, LOCLRS, LOCLRC(3), LRAM51

!           *LOCLRA* INFORMATION ON OFFSET, CGMASS AND LRARC OPTIONS
!
!            LOCLRA - .true. if valid OFFSET, CGMASS, and LRARC on
!            LOCLRS - .true. if LOCLRA is .true. and sum of corr.
!                     contains an input offset correction
!            LOCLRC - .true. if LOCLRA is .true. and header #N contains
!                     contains an input offset correction
!            LRAM51 - .true. if mtype is 51 and loclra is true

      COMMON/PYUA  /XGPSTB,WVL3,VHIGH(3,3,4),VLOW(3,3,4),PYUSQ(5),      &
     &              VISATH(4),VISATL(4),XANTSL(4),XCUTSL(4),XANTSH(4)
      COMMON/RAMPRL/LRAMPR
      COMMON/RAMPA/SF1,SF2,FREQO,RBIAS
      COMMON/RAMPI/MJDRMP,NRAMPS
      COMMON/RAMPS/TRINT(1000,2,2),FRINT(1000,2,2),TRAMP(1000,2),       &
     &             FRAMP(1000),FDRAMP(1000),RSCALX(1000),SCALX(1000),   &
     &             XINTS(1000),XINTB(1000),XINTS2(1000),RSCALY(1000)
      COMMON/REFDRV/DREFDA(9),DREFDB(9),DR3TDW(9),RDATR(9),RDBTR(9),    &
     &              DDA(9,2,50),DDB(9,2,50),DDR(9,50)
      COMMON/RESBIG/AMBIGR(1000)
      COMMON/RIMAGE/VIMAGE(6),QUCAM(4),QURSYS,TLBOD2
      COMMON/RRAMPS/RINDM1,RINDM2,RINDD,RININD,AVFREQ
      COMMON/ROBTYP/CONVRT(999),OBSCAL(999),RESCAL(999),                &
     &              XMTYP
      COMMON/SIMLM/OBSINT,VINT,ELCUTO,XSMLM
      COMMON/STATN /NSTA,NSTAE,NMSTA,NCSTA,NSTAV,NSTLV,NSTEL2,          &
     &              NSTEH2,                                             &
     &              NPH2L2,                                             &
     &              NSTNUM, NSTIME, NALLST,KCONAD, NXSTAT
      COMMON/TPARM/MTPARM,MTPRM1,IPS51,IPS52,MTOBS,IT2PRM(2,28000)
      COMMON/VLBI/NQUA,NADJQ,NADJQV,NQUAB,IYMDV,NVOPT,NXVLBI
      COMMON/XOVER /KXKNT,KXBST,KXOBL,KXBUP,KXBPA,IAPLSC,IAPLL
      COMMON/XPARMB/MPARMB,NPARMB,MPOBS,JPAMB,ISKIPE,                   &
     &             ITPARM(5,28000),ISTABP(3,28000),                     &
     &             ISATBP(3,28000),IPRMBF(28000)
      COMMON/ZPARMB/MPARMZ,ITPRMZ(1000),ISTABZ(3,1000),                 &
     &             ISATBZ(3,1000),IPRMPY(1000),IPRMZ(1000),IUSECY(1000)
!
!c      DIMENSION AA(*),II(*),LL(*),OBSBUF(MOBBUF),PARMVC(*),LPBIAS(*),
        DIMENSION OBSBUF(MOBBUF)
      DIMENSION IDWPT(NDIR)
      DIMENSION AA(*),II(*),LL(*),PARMVC(*),LPBIAS(*),                  &
     &   INDSTA(3,4),INDSAT(3,4),INDSET(3,4),LELEVS(3,4),               &
     &   INPSTA(3,4),INPSAT(3,4),ILCORR(5,4)
      DIMENSION ISTA(3),ISAT(3),LSW(80),JOBCOR(9,8),                    &
     &   LFSECS(6,4),LOTHER(10)
      DIMENSION AMODEL(3)
      DIMENSION FSCSDM(MINTIM),QUAINF(12,*),IQUA(3)
!      CHARACTER*8      PNAME
      DIMENSION PNAME(2,*),IPTRAU(*),IPTRUA(*)
      CHARACTER*8      BTYP4, BTYP7
      DIMENSION BTYP4(8),BTYP7(8)
!
      DIMENSION ITMRA1(1),ITMRA2(1),FRSTRT(1),FRRATE(1)
      DIMENSION LAVOID(1)
!
      DIMENSION FSECIN(1)
      DIMENSION IYMD(1),IHM(1),SEC(1)
      DIMENSION PARML0(3,1)
!
      EQUIVALENCE (JOBCOR(1,1),KOBS)
      EQUIVALENCE (LSWTCH(1,1),LSW(1)),(LFSECS(1,1),LFS(1)),            &
     &            (LOTHER(  1),LFS(31))
!
      CHARACTER*8      AMODEL
      DATA AMODEL/' GEOID  ',' E-TIDE ',' O-TIDE '/
!
      DATA NOPRE /16777215/
      DATA NOTHER/10/,NBITS/40/
      DATA BTYP4/'B4000000','B4010000','B4020000','B4030000',           &
     &                    4*'        '/
      DATA BTYP7/'B7000000','B7010000','B7020000','B7030000',           &
     &                    4*'        '/
      DATA RIS,RIX,RIDS,RIDX,RISS,RISX,RIXS,RIXX/96.D0,32.D0,0.D0,      &
     &6.5D09,1.085972851D0,3.981900452D0,.320427236D0,1.174899866D0/
      DATA LKINET/.FALSE./
! ERWAN FIX
!     DATA LKINET/.TRUE./

      CHARACTER*8      TMP_CHAR
      EQUIVALENCE (TMP_CHAR, TMP_DP )
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      LDQAT=.FALSE.
      LDVCT=.FALSE.
      IF(ICBDGM.NE.3) THEN
      DO IQP=1,1000
      AMBIGR(IQP)=0.D0
      ENDDO
      ENDIF

! INITIALIZE THE VLBI RELATED MEASUREMENT FLAGS
      LVLBI=.FALSE.
      LDDOR=.FALSE.
! INITIALIZE THE MTYPE= IMAGE FLAG
      LIMG=.FALSE.
! INITIALIZE THE MTYPE= LANDMK FLAG
      LLNDMK=.FALSE.
      LCYCTB=.FALSE.
! INITIALIZE LX2ALT
      LX2ALT=.FALSE.
! INITIALIZE LASALT
      LASALT=.FALSE.
! INITIALIZE THE AUXILIARY ARRAYS FOR PLANOR PARTIALS
      DO 20 J=1,50
      DO 20 I=1,9
      DDA(I,1,J)=ZERO
      DDA(I,2,J)=ZERO
      DDB(I,1,J)=ZERO
      DDB(I,2,J)=ZERO
      DDR(I,J)=ZERO
   20 CONTINUE
      IEND=NPVAL0(IXARC)
      IF(LSTINR) IEND=NPVAL0(IXTOTL)
      DO 110 I=1,IEND
      LAVOID(I)=.TRUE.
  110 END DO
!
!CCCCCCDIRS NOVECTOR
!
!
!     INDRAM=0
!
! CLEAR COMPUTED ELEVATION ARRAY
      LAPP=.FALSE.
      NCLEAR=MINTIM*12
      CALL CLEARA(AA(KELEVS),NCLEAR)
      IF(.NOT.LITER1) GO TO 1000
! OUTPUT MODIFIED OBSERVATION BLOCK ON FIRST ITERATION
      IF(LPSBL) GOTO 1000
      IF(LOBSIN) THEN
         CALL OBSOUT(AA,OBSBUF,IOBSBF,IBUF1,IBUF2)
      ENDIF
 1000 CONTINUE
      LOBSIN=.FALSE.
! READ OBSERVATION DIRECTORY RECORD
      IF (LPSBL) GOTO 1001
      CALL OBSDR2(AA,II,LL,NDIR,IDWPT,LEOF)
! EXIT IF DIRECTORY EMPTIED
      IF(LEOF) RETURN
 1001 CONTINUE
! OBTAIN OBSERVATION BLOCK START DATE AND TIME
!orig       MJDSBL=INT(DWORD(1))

!      write(6,*) 'obsrd: LPSBL  ', LPSBL
!      write(6,*) 'obsrd: REPDIF ', REPDIF
      if( LPSBL )then
          MJDSBL=INT(DWORD(1) - REPDIF )
      else
          MJDSBL=INT(DWORD(1) )
      endif

      FSECBL=DWORD(2)

! OBTAIN OBSERVATION BLOCK POINTERS
      IBUF1 =INT(DWORD(3))
      IBUF2 =INT(DWORD(4))
      IWORD1=INT(DWORD(5))
! NUMBER OF OBS. HEADER RECORDS
      NRAMP=0
      NH=INT(DWORD(6)+0.1)
      NHEADR=NH/10
      NRAMP=NH-(NHEADR*10)
!     IF(LPSBL) NHEADR=NH
!     NHEADR=INT(DWORD(6))
! NUMBER OF OBS. IN BLOCK
      NM    =INT(DWORD(7))
      NWORDM=INT(DWORD(8))
! TRACKING CONFIGURATION INDEX INTO STATISTICS ARRAYS
      JSTATS=INT(DWORD(13))
      ITSYS =INT(DWORD(14)+HALF)
      ITSYS =MOD(ITSYS,1000000)
!      write(6,12348 )MJDSBL,FSECBL,IBUF1,IBUF2,IWORD1,NHEADR,NM,NWORDM
!12348 FORMAT(' ** OBSRD **  MJDSBL,FSECBL=',I12,D24.16/ &
!         ' IBUF1,IBUF2,IWORD1,NHEADR,NM,NWORDM=',6I8/)

      IF(LPSBL) GOTO 1002
! READ OBSERVATION BLOCK
      CALL OBSIN (AA,OBSBUF,IOBSBF,IBUF1,IBUF2)
!DEBUG >>>
!       write(6,*) 'obsrd: iobsbf ', iobsbf
!     DO 9901 KKP = 1,200
!     write(6,*) kkp, ' obsrd: entire obsbuf ', &
!    &        (obsbuf(kkq+(kkp-1)*10),kkq=1,10)
9901  continue
!DEBUG <<<
      LOBSIN=.TRUE.
 1002 CONTINUE
      JDTSYS=IWORD1+4
!c      write(6,88880 ) JSTATS,ITSYS,OBSBUF(JDTSYS)
!c88880 FORMAT(' ** OBSRD **  JSTATS,ITSYS,DTSYS =',2I12,G24.16)
!
! VERIFY THAT OBSERVATION BLOCK START TIME AGREES WITH DIRECTORY
!
      MJDSOB=INT(OBSBUF(IWORD1))
      IF(MJDSOB.NE.MJDSBL) GO TO 9000
!
! BLOCK END TIME IN ELAPSED SECONDS FROM MJDSBL
      SECEND=OBSBUF(IWORD1+2)
!c      write(6,*) 'obsrd: SECEND ', SECEND
! DEFINE SPEED OF LIGHT CORRECTION RATIO
      VLITEB=OBSBUF(IWORD1+3)
      VLITEC=ONE-VLIGHT/VLITEB
      NHEADB=NHEADR-1
! SET MEASUREMENT TYPE INDICATOR
      LTARG=.FALSE.
      MTYPE =INT(OBSBUF(IWORD1+4))
      IF(MTYPE.EQ.33) LIMG=.TRUE.
      IF(MTYPE.EQ.34) LLNDMK=.TRUE.
      IF(MTYPE.EQ.101)LX2ALT=.TRUE.
      LTARG=MTYPE.EQ.37.OR.MTYPE.EQ.38.OR.MTYPE.EQ.47.OR.MTYPE.EQ.48
      INB=1
      IF( NNBIA .GT. 0 .AND. MTYPE .EQ. 56 ) THEN
         DO 6890 N=1,NNBIA
            IF(II(KLLBIA-INB+N).EQ.MTYPE) LAPP=.TRUE.
 6890    CONTINUE
      ENDIF
!      print *,'obsrd before: mtype,loclra,lram51: ',
!     .         mtype,loclra,lram51
      LRAM51 = MTYPE.EQ.51.AND.LOCLRA
!      print *,'obsrd after: mtype,loclra,lram51: ',
!     .         mtype,loclra,lram51
! IF PREPRO WORDS ARE 16777215, AND THIS IS NOT WHAT YOU EXPECT,
! BE SURE YOU HAVE A PREPRO CARD IN YOUR 2S SETUP.
! DECOMPOSE PREPROCESSING INDICATORS AND STORE AWAY HEADER DATA
      INDEXX0=IWORD1+9
      INDEXX=15
!...DECOMPOSE MASTER HEADER PREPRO WORD
      KPRE9 =INT(DWORD(INDEXX))
      IKPRE9=KPRE9
!       WRITE(6,*) 'OBSRD: KPRE9 ',N,KPRE9
      CALL DECOMP(KPRE9,LPR9NR   ,24)
!       write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPR9NR =', LPR9NR
!       write(6,*) 'obsrd: loclra ', loclra
!
      if(lram51.and.LITER1) lpr9nr(2)=.false.
!
!       write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPR9NR =', LPR9NR
      IF(.NOT.LITER1) KPRE9=NOPRE
!       IF(.NOT.LITER1) WRITE(6,*) 'OBSRD: KPRE9=NOPRE ',KPRE9
      CALL DECOMP(KPRE9,LPRE9    ,24)
!         write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRE9 =', LPRE9
!
      INDRAM=0
      IF(LITER1) THEN
        IF(.NOT.LPRE9(19)) THEN
           INDRAM=1
           LRAMPR=.TRUE.
        ENDIF
      ELSE
        IF(LRAMPR.AND.(MTYPE.EQ.53.OR.MTYPE.EQ.54)) INDRAM=1
      ENDIF
      if(lram51.and.LITER1) lpre9(2)=.false.
!
!              write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRE9 =', LPRE9
      DO 1100 N=1,3
      DO 1100 I=1,6
      BLKDAT(I,N)=ZERO
 1100 CONTINUE
      DO 1500 N=1,NHEADB
      INDEXX=INDEXX+1
!...DECOMPOSE HEADER #N PREPRO WORD
      KPRE  =INT(DWORD(INDEXX))
!       WRITE(6,*) 'OBSRD: NHEAD, KPRE ',N,KPRE
      CALL DECOMP(KPRE ,LPRNRM(1,N),24)
!              write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRNRM =', &
!    &                              (LPRNRM(iij,n),iij=1,24)
! IF SIMDAT CARDS ARE INCLUDED AND THE IONOSPHERIC OPTION IS SELECTED
! THEN SET FLAGS TO OUTPUT CORRECTIONS AND SUM OF CORRECTIONS FOR THE
! IONOSPHERIC OPTION ON UNIT 20. SAVE PREPRO WORD FOR HEADER #N FOR
! OUTPUT ON UNIT 20.
      IF(LIONC.AND.LSIMDT)THEN
        LPRNRM(6,N)=.TRUE.
        LPRNRM(7,N)=.TRUE.
        IKPRE(N)=KPRE
      ENDIF
!
      loclrs = .false.
      if(lram51.and.LITER1) then
         loclrs = lprnrm(2,N)
!                 write(6,*) 'obsrd: loclrs ', loclrs
         lprnrm(2,N) = .false.
      endif
!       write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRNRM =',
!             1                              (LPRNRM(iij,n),iij=1,24)
!
      IF(.NOT.LITER1) KPRE =NOPRE
!       IF(.NOT.LITER1) WRITE(6,*) 'OBSRD: NHEAD,KPRE=NOPRE ',N,KPRE
      CALL DECOMP(KPRE ,LPRE(1,N),24)
!
!              write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRE =',
!      1                              (LPRE(iij,n),iij=1,24)
      loclrc(N) = .false.
      if(lram51.and.LITER1) then
         loclrc(N) = lpre(2,N)
!                 write(6,*) 'obsrd:  N, loclrc(N) ', N, loclrc(N)
         lpre(2,N) = .false.
      endif
!              write(6,fmt='(1x,a,24(1x,l1))') 'OBSRD: LPRE =',
!             1                              (LPRE(iij,n),iij=1,24)
!
!...STORE HEADER #N PARTITIONS 1-6 INTO COMMON/CBLOKA/
      DO 1200 I=1,6
      BLKDAT(I,N)=OBSBUF(INDEXX0+I)
 1200 END DO
! CAMERA TO PLANET FIXED QUATERNIONS FOR CAMERA (IF SUPPLIED)
      IF(MTYPE.EQ.33.OR.MTYPE.EQ.34) THEN
        QUCAM(1)=OBSBUF(INDEXX0+11)
        QUCAM(2)=OBSBUF(INDEXX0+12)
        QUCAM(3)=OBSBUF(INDEXX0+13)
        QUCAM(4)=OBSBUF(INDEXX0+14)
        TLBOD2=OBSBUF(INDEXX0+15)
      ENDIF
!      write(6,*) 'obsrd:1200 blkdat(,n) ', (blkdat(iij,N),iij=1,6)
      INDEXX0=INDEXX0+10
 1500 END DO
      IF(MTYPE.EQ.33.OR.MTYPE.EQ.34) INDEXX0=INDEXX0+10
!C      PRINT 88888,((LPRE(iij,N),iij=1,24),N=1,NHEADB)
!C88888 FORMAT(' ** OBSRD **  LPRE ='/(24(1X,L1)/))
!C      write(6, 77777) BLKDAT
!C77777 FORMAT(' ** OBSRD **  BLKDAT ='/(1X,6D12.4/))
! SET LASER SWITCH TRUE IF FREQUENCY IS GREATER THAN 10**12 HZ.
      LASER =(MTYPE.LT.99.AND.BLKDAT(3,1).GT.TEN12).OR.LATMOD
      LASALT=LATMOD.AND.MTYPE.GE.99.AND.BLKDAT(4,1).GT.0.D0
! HERE check for NALTW  and replace frequency if wavelength was provided
!      on the ALTWVL card
! SET VLBI LOGICAL FLAG
      LVLBI=MTYPE.EQ.31.OR.MTYPE.EQ.32
      LDDOR=MTYPE.EQ.36
! SET RANGE OR RANGE RATE (DOPPLER) SWITCH
      LRORR =MTYPE.GE.METRIX.AND.MTYPE.LT.99
! SET RANGE RATE (DOPPLER) SWITCH
      LRRATE=LRORR.AND.MOD(MTYPE,2).EQ.0
! BIT 22 OF THE MASTER HEADER RECORD PREPRO WORD IS .FALSE. FOR
!     INSTANTANEOUS DOPPLER
! SET AVERAGE RANGE RATE (INTEGRATED DOPPLER) SWITCH
      !LAVGRR=LRRATE.AND.LPRE9(22)
      LAVGRR=LRRATE.AND.LPR9NR(22)  ! jjm 20150303
! SET SWITCH TO INDICATE RANGE COMPUTATIONS NECESSARY
      LRANGE=LAVGRR.OR..NOT.LRRATE
      IF(MTYPE.GT.3.AND.MTYPE.LT.13) LRANGE=.FALSE.
      IF(MTYPE.GE.3.AND.MTYPE.LE.34) LRANGE=.FALSE.
!
!     ....SET SWITCHES FOR RA/DEC MEAS INVOLVING MARS
!     ....IF MEASUREMENT TYPE IS RA/DEC, THEN LRADEC IS TRUE
!     ....THEN THE CONTENTS OF BLKDAT(4,1) INDICATES WHICH TYPE
!     ....OF INTERPLANETARY MEASUREMENT IT IS
!
      LRADEC = MTYPE .EQ. 13 .OR. MTYPE .EQ. 14
      LPASCU = BLKDAT(4,1) .EQ. 1 .AND. LRADEC
      LMARIN = BLKDAT(4,1) .EQ. 2 .AND. LRADEC
!
!
! MEASUREMENT EVENT TIMES ITERATIVELY COMPUTED ON FIRST ITERATION ONLY
      LIGHT =.NOT.LITER1
      IF(ICBDGM.NE.ITBDGM) LIGHT=.FALSE.
      LGPART=.FALSE.
      LGEOID=.FALSE.
      LSUFRM=.FALSE.
      LGEOI2=.FALSE.
      LOTID2=.FALSE.
      LOTRM2=.FALSE.
      LSSTM2=.FALSE.
      LETIDE=.FALSE.
      LETID2=.FALSE.
      LOTIDE=.FALSE.
      LEOTRM=.FALSE.
      LSURFM=(LITER1.AND.LMSSWG)
      LGEOI2=NGPA.GT.0
      IF(MTYPE.NE.99.AND.MTYPE.NE.100.AND.MTYPE.NE.101.AND.MTYPE.NE.199)&
     &  GO TO 1600
      NGPA=NPVAL0(IXGPC)+NPVAL0(IXGPS)
      LGPART=LSTINR.AND.NGPA.GT.0.AND..NOT.LADYNO
      LGEOID=(NINNER.EQ.1.AND.NGPA.GT.0).OR.(LITER1.AND.LRGEOT)
      IF(NGLOBL.GT.1.AND.NGPA.GT.0) LGEOID=.TRUE.
      IF(.NOT.LITER1.AND.LADYNO) LGEOID=.FALSE.
      IF(.NOT.LSSTMO) THEN
      NSSTAJ=NPVAL0(IXSSTC)+NPVAL0(IXSSTS)
      ELSE
      NSSTAJ=NPVAL0(IXSSTF)
      ENDIF
      NSSTMD=NPVAL (IXSSTC)+NPVAL (IXSSTS)
      NSSTMF=NPVAL (IXSSTF)
      LSSTAJ=LSTINR.AND.NSSTAJ.GT.0
      LSSTMD=(NINNER.EQ.1.AND.NSSTAJ.GT.0)                              &
     &   .OR.(LITER1.AND..NOT.LPRE(14,1).AND.NSSTMD.GT.0)               &
     &   .OR.(LITER1.AND.LRSSTT)                                        &
     &   .OR.(LITER1.AND.NSSTMF.GT.0)
      LSSTM2=(.NOT.LPRE(14,1).AND.NSSTMD.GT.0).OR.(NSSTAJ.GT.0).OR.     &
     & (LRSSTT).OR.(NSSTMF.GT.0)
      IF(NGLOBL.GT.1.AND.NSSTAJ.GT.0) LSSTMD=.TRUE.
      NH2A=NPVAL0(IXH2LV)+NPVAL0(IXETDE)
      LETIDE=(NINNER.EQ.1.AND.NH2A.GT.0).OR.(LITER1.AND..NOT.LPRE(11,1))&
     &   .OR.(LITER1.AND.LRETDT)
!!!!  LETID2=NH2A.GT.0.OR..NOT.LPRE9(11).OR.LRETDT
      LETID2=NH2A.GT.0.OR.LRETDT
!
!-----------------------------------------------------------------------
!     ....changed lotide so it does not override the ALTIM card flags
!     ....if tides are being solved for   jjm  4/2/92
!
!C      LOTIDE=(LITER1.AND..NOT.LPRE(12,1)).OR.(LITER1.AND.LROTDT).OR.
!C     1       (NINNER.EQ.1.AND.NPVAL0(IXOTDE).GT.0)
      LOTIDE = ( LITER1 .AND. .NOT.LPRE(12,1) ) .OR.                    &
     &         (NINNER .EQ. 1 .AND. LROTDT)
      LOTID2 = (.NOT.LPRE(12,1)).OR.(LROTDT).OR.(NPVAL0(IXOTDE).GT.0)
      LEOTRM = (NINNER .EQ. 1 .AND. LCOTRM)
!!!!! LOTRM2 = (.NOT.LPRE9(12) .OR. LCOTRM)
      LOTRM2 = (LROTDT .OR. LCOTRM)
!      print *,'obsrd: lotrm2: ',lotrm2
!-----------------------------------------------------------------------
!
 1600 CONTINUE
!
! LOAD E-BIAS INDICES   INTO COMMON/CBIASI/,
!      E-BIAS  VALUES  INTO COMMON/CBIASA/,
!  AND E-BIAS SWITCHES INTO COMMON/CBIASL/
!
!     PRINT 22220,BIASE
!22220 FORMAT(' ** OBSRD **  BIASE =',4G20.12)
!     PRINT 22221,KEBVAL
!22221 FORMAT(' ** OBSRD **  KEBVAL =',I12)
      IBIAS0=KEBVAL-1
      INDEXX=20
      IF(MTYPE.EQ.33.OR.MTYPE.EQ.34) INDEXX=30
      DO 1700 I=1,4
      LEBIAS(I)=.FALSE.
      INDEXX=INDEXX+1
      INDEXXB   =INT(DWORD(INDEXX))
      IEBIAS(I)=INDEXXB
      INDEXXB=MOD(INDEXXB,10000)
      IF(INDEXXB.LE.0) GO TO 1700
!***** BEGIN TEMPORARY FIX *****
      IF(LITER1)  AA(IBIAS0+INDEXXB)=ZERO
!*****  END  TEMPORARY FIX *****
      BIASE (I)=AA(IBIAS0+INDEXXB)
 1700 END DO
!     PRINT 22220,BIASE
!
! LOAD BIAS INDICES   INTO COMMON/CBIASI/,
!      BIAS  VALUES  INTO COMMON/CBIASA/,
!  AND BIAS SWITCHES INTO COMMON/CBIASL/
!
      INUDF=99
      IPAMB=-99
      IP900=-99
      IP902=-99
      IP156=-99
      IPS51=-99
      IPS52=-99
      IPS61=-99
      IPS62=-99
      IPS720=-99
      IPS721=-99
      IPS722=-99
      IPS723=-99
      IBIAS0=IPVAL0(IXBISA)-1
      IBIASG=IPVAL0(IXBISG)
      INDEXX=24
      LNBIAS=.TRUE.
      LCYC=.FALSE.

! 43 is number of bias switches from LMBIAS --> LBSBIA
! LMBIAS(I) points to elements in common CBIASL from LMBIAS --> LBSBIA
!      COMMON/CBIASL/LEBIAS(4),LMBIAS(2),LBSCAL(1)  ,LTBIAS(1),          &
!                   LBTROP(3),LBIONO(3),LCLSTA(4,2),LCLSAT(4,2),        &
!                   LKLSTS(2,2),LTRPZE(2,2),LTRPGR(2,4),LBSBIA(1),      &
!                   LNBIAS

      DO 1800 I=1,43
      LMBIAS(I)=.TRUE.
      BIASM(I)=0.D0
      INDEXX=INDEXX+1
      INDEXXB   =INT(DWORD(INDEXX))
      IMBIAS(I)=INDEXXB
      IF(INDEXXB.LE.0) GO TO 1800
      LNBIAS=.FALSE.
      IQP=I
      IF(LGPS.AND.I.EQ.2) IQP=1
      BIASM (IQP)=PARMVC(INDEXXB)
      !write(6,*)'OBSRD: INDEXXB,PARMVC(indexxb) ', &
      !                  INDEXXB,PARMVC(indexxb)
      !write(6,*)&
      !'OBSRD: INDEXXB,I,BIASM(IQP),IQP,PARML0(2,INDEXXB),PARML0(3,INDEXX
      !        INDEXXB,I,BIASM(IQP),IQP,PARML0(2,INDEXXB),PARML0(3,INDEXX
      IF(I.EQ.1) IPAMB=INDEXXB
      IF(I.EQ.2) IP156=INDEXXB
      IF(I.EQ.3) IP902=INDEXXB
      IF(I.EQ.4) IP900=INDEXXB
      IF(I.EQ.5) IPS51=INDEXXB
      IF(I.EQ.6) IPS52=INDEXXB
      IF(I.EQ.8) IPS61=INDEXXB
      IF(I.EQ.9) IPS62=INDEXXB
      IF(I.EQ.23) IPS720=INDEXXB
      IF(I.EQ.24) IPS721=INDEXXB
      IF(I.EQ.25) IPS722=INDEXXB
      IF(I.EQ.26) IPS723=INDEXXB
      DO 1750 J=1,4
!C      IF(PNAME(1,IPTRAU(INDEXXB)).EQ.BTYP4(J))THEN
      TMP_DP = PNAME(1,IPTRAU(INDEXXB))
      IF(TMP_CHAR .EQ.BTYP4(J))THEN
      LCLOCK=.TRUE.
!C      ELSEIF(PNAME(1,IPTRAU(INDEXXB)).EQ.BTYP7(J))THEN
      ELSEIF(TMP_CHAR .EQ.BTYP7(J))THEN
      LCLOCK=.FALSE.
      ENDIF
 1750 END DO
!     write(6,41414)PNAME(1,IPTRAU(INDEXXB)),LCLOCK
      IF(INDEXXB.GE.IBIASG) GO TO 1800
      INDEXXB=INDEXXB-IBIAS0
      LMBIAS(I)=.NOT.LPBIAS(INDEXXB)
41414 format(1x,A8,L2)
 1800 END DO
      IF((MTYPE.EQ.85.OR.MTYPE.EQ.87).AND.IPAMB.LT.0) INUDF=-99

!ddr mods
      IF((MTYPE.EQ.65).AND.IPAMB.LT.0) INUDF=-99
      IF((MTYPE.EQ.40).AND.IPAMB.LT.0) INUDF=-99
!ddr mods

! SET TIME DERIVATIVE SWITCH
      LTDRIV=LBINRI
      LTDRIV=LTDRIV.OR.ITBIAS(1).GT.0.OR.IBSCAL(1).GT.0
!
! THIS QUANTITY(NOBS) MAY BE COMPARED WITH NM
      NOBS  =INT(OBSBUF(IWORD1+6))
      NAUX  =INT(OBSBUF(IWORD1+7))
!C      write(6,12349) NOBS,NAUX,MTYPE,ITSYS,LAVGRR
!C12349 FORMAT(' ** OBSRD **  NOBS,NAUX=',2I12,' MTYPE,ITSYS,LAVGRR=',
!C     1   I3,I7,1X,L1)
      DO 2000 I=1,3
      ISTA(I)=0
      JSTANO(I)=0
      ISAT(I)=0
      JSATNO(I)=0
      IQUA(I)=0
      QUANO(I)=0
      DO 2000 J=1,4
      INDSTA(I,J)=0
      INDSAT(I,J)=0
      INDSET(I,J)=0
      INPSTA(I,J)=0
      INPSAT(I,J)=0
      LELEVS(I,J)=.FALSE.
      KXMN  (I,J)=KSXYZ
!     WRITE(6,*) 'OBSRD: 2000 I,J, KXMN(I,J) ',
!    1                        I,J, KXMN(I,J)
      KENVN (I,J)=KXLOCV
      KSTINF(I,J)=KSTAIN
 2000 CONTINUE
      INDEXX =IWORD1+6
      I=0
      DO 2810 IHEADR=2,NHEADR
      I=I+1
      INDEXX =INDEXX +10
      IF(INDRAM.GT.0.D0) THEN
      AVFREQ=OBSBUF(INDEXX-4)
      ENDIF
      K=INT(OBSBUF(INDEXX    ))
      IF(K.LE.0) GO TO 2400

      IF (.NOT.LLNDMK) THEN

      JSTANO(I)=K
      N=KISTNO
      DO 2200 J=1,NSTA
      IF(K.NE.II(N)) GO TO 2200
      ISTA(I)=J
      GO TO 2400
 2200 N=N+1
      JLINE6=ILINE6+3
      IF(JLINE6.LE.MLINE6) GO TO 2300
      IPAGE6=IPAGE6+1
      JLINE6=4
      WRITE(IOUT6,10000) IPAGE6
 2300 CONTINUE
      WRITE(IOUT6,23000) K,IHEADR
      ILINE6=JLINE6
      STOP 16


      ELSE

!!!JTW FOR LANDMK DATA

      JSTANO(I)=K
      N=KISTNO
      ISTA(I)=1

      END IF

 2400 CONTINUE
      K=INT(OBSBUF(INDEXX+1))
      IF(K.LE.0) GO TO 2800
!  CHECK FOR VLBI, LOAD QUASAR ID INSTEAD OF SATELLITE ID
      IF(LTARG)ITARNO=K
      IF (.NOT.LTARG)  THEN
      IF (.NOT.LVLBI.AND..NOT.LDDOR)  THEN
      JSATNO(I)=K
      N=KISATN
      DO 2600 J=1,NSATA
      IF(K.NE.II(N)) GO TO 2600
      ISAT(I)=J
      GO TO 2800
 2600 N=N+1
      JLINE6=ILINE6+3
      IF(JLINE6.LE.MLINE6) GO TO 2700
      IPAGE6=IPAGE6+1
      JLINE6=4
      WRITE(IOUT6,10000) IPAGE6
 2700 CONTINUE
      WRITE(IOUT6,27000) K,IHEADR
      ILINE6=JLINE6
      STOP 16
      ELSE
         IF(LDDOR) GO TO  2630
! VLBI
      QUANO(I)=K
      DO 2620 J=1,NQUAB
      IDQUA=QUAINF(2,J)
!CC     WRITE(6,*) ' OBSRD --> J, IDQUA : ',J,IDQUA
      IF(K.NE.IDQUA) GO TO 2620
      IQUA(I)=J
      GO TO 2800
 2620 END DO

! DELTA DOR
 2630 CONTINUE

      IF(I.EQ.1) THEN
      JSATNO(1)=K
      N=KISATN
      DO 2650 J=1,NSATA
      IF(K.NE.II(N)) GO TO 2650
      ISAT(I)=J
      GO TO 2800
 2650 N=N+1
      ENDIF

      IF(I.EQ.2) THEN
      QUANO(1)=K
      DO 2640 J=1,NQUAB
      IDQUA=QUAINF(2,J)
!     WRITE(6,*) ' OBSRD --> J, IDQUA : ',J,IDQUA
      IF(K.NE.IDQUA) GO TO 2640
      IQUA(1)=J
      GO TO 2800
2640  ENDDO
      ENDIF

      JLINE6=ILINE6+3
      IF(JLINE6.LE.MLINE6) GO TO 2720
      IPAGE6=IPAGE6+1
      JLINE6=4
      WRITE(IOUT6,10000) IPAGE6
 2720 CONTINUE
      WRITE(IOUT6,27020) K,IHEADR
      ILINE6=JLINE6
      STOP 16
      ENDIF
      ENDIF
 2800 CONTINUE
 2810 END DO
      IF(LITER1) CALL CCOUNT(NSATA,II(KISATN))
! If ramped Doppler find out how many ramp records are there
!     write(6,*)' dbg INDRAM ',indram,INDEXX
      IF(INDRAM.EQ.0) GO TO 3000
      INDEXX=INDEXX+4
      IDNBND=INT(OBSBUF(INDEXX))
!     write(6,*)'dbg DOWNLINK RADIO BAND ',IDNBND,INDEXX
      INDEXX=INDEXX+1
      IUPBND=INT(OBSBUF(INDEXX))
!     write(6,*)'dbg UPLINK RADIO BAND ',IUPBND
      IF(IDNBND.EQ.1.AND.IUPBND.EQ.1) THEN
      RINDM2=RISS
      ELSEIF(IDNBND.EQ.1.AND.IUPBND.EQ.2) THEN
      RINDM2=RIXS
      ELSEIF(IDNBND.EQ.2.AND.IUPBND.EQ.1) THEN
      RINDM2=RISX
      ELSEIF(IDNBND.EQ.2.AND.IUPBND.EQ.2) THEN
      RINDM2=RIXX
      ENDIF
      INDEXX=INDEXX+1
      IRXRB=INT(OBSBUF(INDEXX))
!     write(6,*)'dbg RECEIVER EXCITER RADIO BAND ',IRXRB
      INDEXX=INDEXX+1
      RININD=OBSBUF(INDEXX)
!     write(6,*)'dbg RECEIVER EXCITER  INDEPENDENT INDICATOR',IRXIN
      IF(IRXRB.EQ.1) THEN
      RINDM1=RIS
      RINDD= RIDS
      ELSE
      RINDM1=RIX
      RINDD= RIDX
      ENDIF
      INDEXX=INDEXX+1
!     KKRAMP IS THE NUMBER OF RAMP PERIODS
      KKRAMP=INT(OBSBUF(INDEXX  ))
!     write(6,*)' dbg kkramp indram ',kkramp,indram
!
      NRAMPS=KKRAMP
      SF1=OBSBUF(INDEXX+1)
      SF2=OBSBUF(INDEXX+2)
      FREQO=OBSBUF(INDEXX+3)
      RBIAS=OBSBUF(INDEXX+4)
      ORBIAS=RBIAS
!!!!!!!!!!!!!!!KINETEX SIMULATION CODE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      IF(LKINET) THEN
      IF(NPVAL(IXFAGM).EQ.3) THEN
        IF(MTYPE.EQ.54) THEN
          SF2=PARMVC(IPVAL0(IXFAGM))
          RBIAS=ORBIAS*PARMVC(IPVAL0(IXFAGM)+1)
        ENDIF
        IF(MTYPE.EQ.53) THEN
          SF2=PARMVC(IPVAL0(IXFAGM)+2)
        ENDIF
      ENDIF
      ENDIF
!!!!!!!!!!!!!!!KINETEX SIMULATION CODE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      IF(MTYPE.NE.53.AND.MTYPE.NE.54) THEN
        WRITE(6,60000)
        WRITE(6,60001) MTYPE
        WRITE(6,60000)
      STOP
      ENDIF
      LPROBI=.TRUE.
      IF(LPRE9(6).AND.LPRE(6,1).AND.LPRE(6,2)) LPROBI=.FALSE.
      IF(.NOT.LPRE9(6).AND..NOT.LPRE(6,1).AND.                          &
     &   .NOT.LPRE(6,2)) LPROBI=.FALSE.
      IF(LPROBI) THEN
        WRITE(6,60000)
        WRITE(6,60002)
        WRITE(6,60003)
        WRITE(6,60004) MTYPE,MJDSBL
        WRITE(6,60000)
        STOP
      ENDIF
      IF(LPRE9(6).AND.LIONC) THEN
        WRITE(6,60000)
        WRITE(6,60002)
        WRITE(6,60005)
        WRITE(6,60006)
        WRITE(6,60004) MTYPE,MJDSBL
        WRITE(6,60000)
      STOP
      ENDIF
 3000 CONTINUE
! IDENTIFY BIASES FOR SAKE OF PUNCH
      IF(LITER1) THEN
         CALL BID(MTYPE,MJDSBL,FSECBL,SECEND,JSTANO,JSATNO,IPAMB,IP900, &
     &            IPS51,IPS52,IP902,IPS61,IPS62,                        &
     &            IPS720,IPS721,IPS722,IPS723,IP156)
      ENDIF
      IF(LGPS.AND.IP156.GT.0) THEN
         INUDF=99
         IF(IPAMB.GT.0) THEN
            FSECIN(1)=FSECBL
            CALL YMDHMS(MJDSBL,FSECIN,IYMD,IHM,SEC,1)
            IF(IYMD(1).GT.1000000)IYMD(1)=IYMD(1)-1000000
            WRITE(6,98000)
            WRITE(6,98001)
            WRITE(6,98002)
            WRITE(6,98003) IYMD(1),IHM(1),SEC(1)
            WRITE(6,98004) MTYPE
            WRITE(6,98005) JSATNO
            WRITE(6,98006) JSTANO
            STOP
         ENDIF
         IMBIAS(1)=IP156
         IMBIAS(2)=0
         LCYCTB=.TRUE.
      ENDIF
!
      XGPSTB=-1.D0
      LMTOK=.FALSE.
!      IF(MTYPE.GE.41.OR.MTYPE.LE.44) LMTOK=.TRUE.
!      IF(MTYPE.GE.61.OR.MTYPE.LE.68) LMTOK=.TRUE.
      IF(MTYPE.EQ.85.OR.MTYPE.EQ.87) LMTOK=.TRUE.
!ddr mods
      IF(MTYPE.EQ.65) LMTOK=.TRUE.
!ddr mods
      JPAMB=IPAMB-IPVAL0(IXBISA)+1
      IF(IPAMB.LE.0) JPAMB=-99
      IF(LMTOK.AND.IP156.GT.0.AND.IPAMB.LE.0) THEN
         CALL GETAMB(MTYPE,MJDSBL,FSECBL,JSTANO,JSATNO)
      ENDIF
!ddr mods
      ! for phase wind-up
      IF(LGPS.AND.LMTOK.AND.JPAMB.GT.0) XGPSTB=1.D0
!orig      IF(LGPS.AND.LMTOK.AND.JPAMB.GT.0) XGPSTB=1.D0
!!!!  IF(LGPS.AND.LMTOK.AND.JPAMB.GT.0) XGPSTB=1.D0
!ddr mods

      IF(XGPSTB.GT.0.D0) THEN
!        WVL3=.15541268D0
         WVL3=0.1069533781421467D+00
         IPX=JPAMB
         IQP=KPYSQH-1+(IPX-1)*4
         PYUSQ(1)=AA(IQP+1)
         PYUSQ(2)=AA(IQP+2)
         PYUSQ(3)=AA(IQP+3)
         PYUSQ(4)=AA(IQP+4)
         PYUSQ(5)=DBLE(IPX)+.05D0
      ENDIF
      LPROBQ=.FALSE.
      IF(LGPS.AND.LMTOK.AND.JPAMB.LE.0.AND.IP156.GT.0) THEN
            FSECIN(1)=FSECBL
            CALL YMDHMS(MJDSBL,FSECIN,IYMD,IHM,SEC,1)
            IF(IYMD(1).GT.1000000)IYMD(1)=IYMD(1)-1000000
            WRITE(6,98007)
            WRITE(6,98008)
            WRITE(6,98009)
            WRITE(6,98003) IYMD(1),IHM(1),SEC(1)
            WRITE(6,98004) MTYPE
            WRITE(6,98005) JSATNO
            WRITE(6,98006) JSTANO
            WRITE(6,98010)
            LPROBQ=.TRUE.
      ENDIF
      ISKIPE=1
!
! THE CURRENT BLOCK OF DATA MAY BE DELETED FOR SEVERAL REASONS:
!   (ISKIPE=-1 ==> DELETE WHOLE BLOCK)
!
!   (1) CYCLE SLIP BIAS CAN'T BE LINKED TO A MAIN PASS
!   (2) THE MAIN PASS IS ASSOCIATED WITH AN AMBIGUITY BIAS
!       THAT HAS BEEN DETERMINED TO HAVE PROBLEMS
!   (3) THE BLOCK OF DATA IS ASSOCIATED WITH A TROP BIAS
!       THAT HAS BEEN DETERMINED TO HAVE PROBLEMS
!
!
      IF(LGPS.AND.LMTOK) THEN
!  PROBLEM(1)
         IF(LPROBQ) THEN
            ISKIPE=-1
         ELSE
!  PROBLEM(2)
            IF(ITPARM(5,JPAMB).LT.0) ISKIPE=-1
         ENDIF
         IF(IP156.GT.0) THEN
!  PROBLEM(1) OR (2)
            KPAMB=IP156-IPVAL0(IXBISA)-NAMBBH+1
            IF(.NOT.LITER1.AND.IUSECY(KPAMB).LE.0) ISKIPE=-1
            !IF(ITPARM(5,JPAMB).LT.0) IUSECY(KAMB)=-1 !original
            ! jjm 20120531  jjm changed KAMB below to KPAMB
            IF(ITPARM(5,JPAMB).LT.0) IUSECY(KPAMB)=-1
         ENDIF
      ENDIF
!  PROBLEM(3)
      IF(IPS51.GT.0) THEN
        IPS51=IPS51-MTPRM1+1
        IF(IT2PRM(2,IPS51).LT.0) ISKIPE=-1
      ENDIF
      IF(IPS52.GT.0) THEN
        IPS52=IPS52-MTPRM1+1
        IF(IT2PRM(2,IPS52).LT.0) ISKIPE=-1
      ENDIF
!
!  GET ANTENNA INFORMATION IF AVAILABLE
      LANTBD=.FALSE.
      IF(MTYPE.LT.99) LANTBD=.NOT.LPR9NR(10)
      IF(LANTBD) CALL GETANT(MTYPE,JSTANO,JSATNO)
! SET UP COMMON BLOCK CBINRI
      NSATB=0
      NSTAB=0
      DO 3005 ISATB=1,3
      INMSAT(ISATB)=0
      IF(ISAT(ISATB).LE.0) GO TO 3005
      NSATB=NSATB+1
      INMSAT(NSATB)=ISAT(ISATB)
!
 3005 END DO
!
      DO 3010 ISTAB=1,3
      INMSTA(ISTAB)=0
      IF(ISTA(ISTAB).LE.0) GO TO 3010
      NSTAB=NSTAB+1
      INMSTA(NSTAB)=ISTA(ISTAB)
!
 3010 END DO
!
!     IND???=FUNCTION OF ISTA,ISAT & MTYPE
!
      IF(MTYPE.GT.12) GO TO 3020
! PCE DATA INVOLVES ONLY ONE SATELLITE AND NO STATION
      INPSAT(1,1)=1
      GO TO 3200
 3020 CONTINUE
      IF(MTYPE.EQ.36) GOTO  3060
      IF(MTYPE.GT.60) GO TO 3060
! NON-DIFFERENCED DATA INVOLVE AT MOST 3 STATIONS AND 3 SATELLITES
      JTYPE =(MTYPE -11)/2
      DO 3040 I=1,3
      INPSAT(I,1)=NDSA60(I,JTYPE)
      INPSTA(I,1)=NDST60(I,JTYPE)
 3040 continue
      DO 3041 I=1,5
      ILCORR(I,1)=NLLC60(I,JTYPE)
 3041 continue
!      write(6,*) 'obsrd: 3041 mtype, jtype ', mtype, jtype
!     write(6,*) 'obsrd: inpsat(1-3,1) ', (inpsat(kkq,1),kkq=1,3)
!     write(6,*) 'obsrd: inpsta(1-3,1) ', (inpsta(kkq,1),kkq=1,3)
!     write(6,*) 'obsrd: ILCORR(1-5,1) ', (ILCORR(kkq,1),kkq=1,5)
      GO TO 3200
 3060 CONTINUE
      IF(MTYPE.GT.84) GO TO 3100
! SINGLE DIFFERENCE DATA MAY INVOLVE 2 COMBINATIONS OF 3 STATIONS
!        AND 3 SATELLITES
      JTYPE =(MTYPE-59)/2
      IF(MTYPE.EQ.36) JTYPE=1
      DO 3080 I=1,6
      INPSAT(I,1)=NDSA82(I,JTYPE)
      INPSTA(I,1)=NDST82(I,JTYPE)
 3080 END DO
      DO 3081 I=1,10
      ILCORR(I,1)=NLLC82(I,JTYPE)
 3081 END DO
      GO TO 3200
 3100 CONTINUE
      IF(MTYPE.GT.98) GO TO 3140
! DOUBLE DIFFERENCE DATA MAY INVOLVE 4 COMBINATIONS OF 3 STATIONS
!        AND 3 SATELLITES
      JTYPE =(MTYPE-83)/2
      DO 3120 I=1,12
      INPSAT(I,1)=NDSA92(I,JTYPE)
      INPSTA(I,1)=NDST92(I,JTYPE)
!
 3120 END DO
!
      DO 3121 I=1,20
      ILCORR(I,1)=NLLC98(I,JTYPE)
!
 3121 END DO
!
      GO TO 3200
!
 3140 CONTINUE
!
! ALL OTHER DATA TYPES (INCLUDING ALTIMETRY) WILL DEFAULT TO 1 SATELLITE
!           AND NO STATIONS
      INPSAT(1,1)=1
!
 3200 CONTINUE
!
! RELATE STATION AND SATELLITE CONFIGURATION STRUCTURE TO ACTUAL
!        STATIONS AND SATELLITES THROUGH INTERNAL INDICES
      DO 3300 I=1,12
      J=INPSTA(I,1)
      IF(J.GT.0) INDSTA(I,1)=ISTA(J)
      J=INPSAT(I,1)
      IF(J.LE.0) GO TO 3300
      INDSAT(I,1)=ISAT(J)
      K=KISET+ISAT(J)-1
      INDSET(I,1)=II(K)
!
 3300 END DO
!
! **********************************************
! DETERMINE WHICH ELEVATION ANGLES TO COMPUTE
!  LT *** 09.09.91  *******  SET UP COUNTERS AND ARRAYS FOR MULTI LINK
!                   MEASUREMENTS ( NON-DIFF. AND DIFFERENCED DATA)
!  FOR DATA TYPES INVOLVING ONLY SAT THIS CODE DOES NOT APPLY !!!
!  THIS IS TIED TO THE ELCUTOFF CARD ( FURTHER CODE WILL BE NEEDED)
!
      NELEVS=0
      DO 3400 I=1,12
      INDELV(I,1)=0
      JSTA=INDSTA(I,1)
!     JSAT=INDSAT(I,1)
      IF(JSTA.LE.0) GO TO 3400
!     IF(JSTA.LE.0.OR.JSAT.LE.0) GO TO 3400
      IF(NELEVS.GE.12) GO TO 3400
      NELEVS=NELEVS+1
      ISTAEL(NELEVS)=JSTA
      LELEVS(I,1)=.TRUE.
      INDELV(I,1)=NELEVS
 3400 END DO
!DEBUG>>> ********************
!      do 3444 i=1,3
!     write(6,*) ' obsrd : indsta ',(indsta(i,j),j=1,4)
!     write(6,*) ' obsrd : inpsta ',(inpsta(i,j),j=1,4)
!     write(6,*) ' obsrd : indsat ',(indsat(i,j),j=1,4)
!     write(6,*) ' obsrd : inpsat ',(inpsat(i,j),j=1,4)
!     write(6,*) ' obsrd : lelevs ',(lelevs(i,j),j=1,4)
! 3444 continue
!     write(6,*) ' obsrd : istael ',(istael(iij),iij=1,12)
!     write(6,*) 'obsrd : nelevs ',nelevs
!     DO 3451 I=1,3
!     write(6,*) ' obsrd : indelv ',(indelv(i,j),j=1,4)
!3451 continue
!DEBUG<<< ********************
      DO 3500 J=1,4
      DO 3500 I=1,3
      INDST1=INDSTA(I,J)-1
      IF(INDST1.LT.0) GO TO 3500
      KXMN  (I,J)=KSXYZ +3*INDST1
      KENVN (I,J)=KXLOCV+9*INDST1
      KSTINF(I,J)=KSTAIN+NSTAIN*INDST1
 3500 CONTINUE
!     PRINT 34567,KXMN,KENVN,KSTINF
!4567 FORMAT(' ** OBSRD **  KXMN,KENVN,KSTINF='/(1X,12I8))
!
      KOBS=KOBBUF+IWORD1+(NHEADR+NRAMP)*10-1
      IF(MTYPE.EQ.33.OR.MTYPE.EQ.34) KOBS=KOBS+10
!     write(6,23456) KOBS,ISTA,ISAT
23456 FORMAT(' ** OBSRD **  KOBS=',I12,'  ISTA,ISAT='/(1X,3I12))
!
!
! Unload switches from the Tracking Data Directory that tell which of
! the buffer partitions for the observation and observation corrections
! records are present.   (LSW  is equivalenced to LSWTCH)
      BMASK =TWO
      WORD09=DWORD( 9)
      WORD10=DWORD(10)
!c             write(6,*) 'obsrd: word09, word10 ', word09, word10
      DO 4000 I=1,NBITS
      WORDX =MOD(WORD09,BMASK)
      WORD09=WORD09-WORDX
      LSW   (I      )=WORDX.GT.ZERO
      WORDX =MOD(WORD10,BMASK)
      WORD10=WORD10-WORDX
      LSW   (I+NBITS)=WORDX.GT.ZERO
      BMASK=BMASK*TWO
 4000 END DO
!c             write(6,*) 'obsrd: below 4000 lsw ',  lsw
!
! Set the pointers starting with KOBS in /COBLOK/ for this obs. block.
! These  pointers tell where the observation, sum of corrections, time
! corrections and individual corrections such as tropo and tracking
! point correction will be stored in memory.
! Warning some of these pointers may be changed later in this routine.
! See the LOTHER flags.
      JNEXT=KOBS
      NRC=0
      DO 5000 J=1,8
      DO 5000 I=1,9
      JOBCOR(I,J)=JNEXT
!      write(6,*) 'obsrd: i,j,lswtch(i,j) ', i,j,lswtch(i,j)
!      write(6,*) 'obsrd: i,j,jobcor(i,j) ', i,j,jobcor(i,j)
      IF(LSWTCH(I,J)) THEN
      IF(J.LT.7) NRC=NRC+1
      IF(LPSBL) THEN
      IADD=1
!     write(6,*) 'obsrd: zero jobcor(i,j) ', jobcor(i,j)
      DO 4010 JADD=1,NM
      AA(JOBCOR(I,J)-1+IADD)=ZERO
      IADD=IADD+1
 4010 END DO
      ENDIF
!     write(6,*)'obsrd:i,j,lswtch(i,j)',i,j,lswtch(i,j),jnext,aa(jnext)
      IF(J.EQ.7.AND.INDRAM.EQ.1) THEN
         IF(I.GT.4)THEN
         J1=1
         ELSE
         J1=0
         ENDIF
         kramp2=kkramp/2+0.01
         kr2=(kramp2)*2
         if(kr2.ne.kkramp)then
         kramp2=kramp2+1
         endif
         do 5121 k1=1,kramp2
         if(i.eq.1.or.i.eq.5) then
! start times fill up ITMRAM(K1,1)
           ITMRA1(k1+j1)=INT(aa(jnext-1+k1)+0.1)
           RSCALX(K1+J1)=AA(JNEXT-1+K1)-XJDRM0
!        write(6,*)' dbg ITMRA1(',k1+j1,'=',ITMRA1(k1+j1)
         j1=j1+1
         elseif(i.eq.2.or.i.eq.6) then
! stop  times fill up ITMRA2(K1)
           ITMRA2(k1+j1)=INT(aa(jnext-1+k1)+0.1)
           SCALX(K1+J1)=AA(JNEXT-1+K1)-XJDRM0
!        write(6,*)' dbg ITMRA2(',k1+j1,'=',ITMRA2(k1+j1)
         j1=j1+1
         elseif(i.eq.3.or.i.eq.7) then
! frequencies fill up FRSTRT(K1)
           FRSTRT(k1+j1)=aa(jnext-1+k1)
           FRAMP(K1+J1)=aa(jnext-1+k1)
!        write(6,*)' dbg FRSTRT(',k1+j1,')=',FRSTRT(k1+j1)
         j1=j1+1
         elseif(i.eq.4.or.i.eq.8) then
! frequenciy rate fill up FRRATE(K1)
           FRRATE(k1+j1)=aa(jnext-1+k1)
           FDRAMP(K1+J1)=aa(jnext-1+k1)
!        write(6,*)' dbg FRRATE(',k1+j1,')=',FRRATE(k1+j1)
         j1=j1+1
         endif
 5121 continue
           IF(I.EQ.9) THEN
           JNEXT=JNEXT+NM
           ELSE
           JNEXT=JNEXT+KRAMP2
           ENDIF
      ELSE
         JNEXT=JNEXT+NM
      ENDIF
      ENDIF
      IF (LVLBI.AND.I.EQ.1.AND.J.EQ.1) THEN
      EFLG=AA(JNEXT)
!     WRITE(6,*) '  OBSRD : EDT FLAG ',EFLG
      END IF
!     WRITE(6,*) '  OBSRD : lswtch  ',LSWTCH(I,J),JNEXT,AA(JNEXT)
 5000 CONTINUE
      IF(INDRAM.GT.0) THEN
!
      NRRX=NRAMPS/2
      IADDX=NRAMPS-2*NRRX
      NRR=NRAMPS/2+IADDX
      NRR=NRR*2
      NRC=NRC*NM
      CALL RMPLOD(NRAMPS,NRR,AA(KOBS+NRC),RSCALX,SCALX,FRAMP,FDRAMP)
!
      MJDRM0=RSCALX(1)
      MJDRMP=MJDRM0+1861444800
      XJDRM0=DBLE(MJDRM0)
      DO 5002 IRAMP=1,NRAMPS
      RSCALX(IRAMP)=RSCALX(IRAMP)-XJDRM0
      SCALX(IRAMP)=SCALX(IRAMP)-XJDRM0
 5002 END DO
!
      CALL UTCET(.TRUE.,NRAMPS,MJDRMP,RSCALX,TRAMP(1,1),AA(KA1UT))
      CALL UTCET(.TRUE.,NRAMPS,MJDRMP,SCALX,TRAMP(1,2),AA(KA1UT))
      JNEXT=KOBS+NRC+NRR*8
      ENDIF
      IF(LPSBL) THEN
      DO 5003 NN=1,NM
      AA(KSMCOR-1+NN)=ZERO
 5003 END DO
      ENDIF
!
! NOTE ON RAMPED DOPPLER INFORMATION
! AT AA(JOBCOR(1,7)+NM BEGINS THE INFORMATION FROM THE RAMPED RECORDS
! IF THIS IS A RAMPED DOPPLER BLOCK OF OBSERVATIONS: (INDRAM=1)
! THE POINTERS HERE ADVANCE BY KKRAMP/2
!
!c             WRITE(6,*) '  OBSRD, CHECK OUT COBLOC POINTERS '
!c             WRITE(6,*) '  OBSRD: KSMCOR  ',KSMCOR,AA(KSMCOR)
!c             WRITE(6,*)
!     DO 1111 I=1,9
!      WRITE(6,*) '  OBSRD: KOBCOR  ',(KOBCOR(I,J),J=1,7)
!      WRITE(6,*) '  OBSRD: KOBCOR  ',(AA(KOBCOR(I,J)),J=1,7),I
!1111 END DO
!
!***** NOTE FOR FUTURE REFERENCE:
!
!      IF OBSERVATION CORRECTIONS RECORD PARTITIONS ARE NOT CONVEYED
!      IN OBSERVATION FILE, THIS WILL BE SO INDICATED BY THE LSWTCH
!      ARRAY. UNDER THESE CIRCUMSTANCES JOBCOR(I,J) FOR PARTITIONS
!      NOT CONVEYED WILL HAVE TO POINT TO AN APPROPRIATELY SIZED
!      SCRATCH ARRAY NOT OTHERWISE USED AT TIME CORRECTIONS ARE
!      COMPUTED AND SUMMED.
!
!      AT PRESENT THE ENTIRE OBSERVATION CORRECTIONS RECORD IS CONVEYED.
!
!      JOBCOR(I,J) AND LSWTCH(I,J) REFER TO THE I TH PARTITION OF
!      RECORD TYPE (J-1)*1000000.
!
!***** END NOTE.
!
!c             write(6,12345) JOBCOR
!c       12345 FORMAT(' ** OBSRD **  JOBCOR='/(1X,9I8))
!c             write(6,12347) LSW
!c       12347 FORMAT(' ** OBSRD **  LSW='/(40(1X,L1)))
      BMASK =TWO
      WORD11=DWORD(11)
!      print *,''
!      print *,'obsrd: word11 ',word11
!      print *,''
      DO 6000 I=1,NBITS
      WORDX =MOD(WORD11,BMASK)
      WORD11=WORD11-WORDX
      LFS   (I   )=WORDX.GT.ZERO
!      print *,''
!      print *,'obsrd: i,lfs: ',i,lfs(i)
!      print *,''
      BMASK=BMASK*TWO
 6000 END DO
      J=KSMCOR
      K=J+NM-1
!c             PRINT 96000,(AA(iij),iij=J,K)
!c       96000 FORMAT(' ** OBSRD **  96000 SUMCOR ='/(1X,6D12.5))
!
!c             WRITE(6,*) ' OBSRD: before7000 NOTHER, JNEXT ', NOTHER,JN
      DO 7000 I=1,NOTHER
      KOBSUM(I)=JNEXT
      IF(LOTHER(I)) JNEXT=JNEXT+NM
 7000 END DO
!c             WRITE(6,*) ' OBSRD: after 7000 KOBSUM ',KOBSUM
!c             WRITE(6,*) ' OBSRD: AA(KOBSUM)  ',(AA(KOBSUM(iij)),iij=1,
!
! NOMINALLY SET ALL DOPPLER SCALING FACTORS TO UNITY
!
      LNTDRS=.TRUE.
      DO 7100 J=1,4
      DO 7100 I=1,5
      DOPSCL(I,J)=ONE
 7100 CONTINUE
!
! DETERMINE SCALING FACTORS FOR TDRSS DOPPLER SHORT PATH
!
      DO 7300 M=1,NTDRSS
      IF(MTYPE.NE.MTDRSS(M)) GO TO 7300
      LNTDRS=.FALSE.
      NK=KTDRSS(M)
      DO 7200 K=1,NK
      I=ITDRSS(K,M)
      J=JTDRSS(K,M)
      DOPSCL(1,K)=1.0D0+BLKDAT(I,J)
      DOPSCL(5,K)=      BLKDAT(I,J)
 7200 END DO
      GO TO 7400
 7300 END DO
 7400 CONTINUE
!c             write(6,*) 'obsrd: below 7400'
!
! CLEAR ARRAYS FOR COMPUTATION OF PREPROCESSING CORRECTIONS
!
!c             write(6,*) 'obsrd: ksmcor ', ksmcor
!c             write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,nm)
!________________________
!c         write(6,*) 'obsrd: lother(4) ', lother(4)
      IF(LOTHER( 4)) KSMCOR=KOBSUM( 4)
      IF(LOTHER( 5)) KSMCR2=KOBSUM( 5)
      IF(LOTHER( 6)) KTMCOR=KOBSUM( 6)
! IF SIMDAT CARDS ARE INCLUDED AND THE IONOSPHERIC OPTION IS SELECTED
! DO NOT OVERWRITE OBSERVATION SIGMAS.
      IF(.NOT.(LIONC.AND.LSIMDT))THEN
        IF(LOTHER( 7)) KOBSIG=KOBSUM( 7)
      ENDIF
! AT THIS POINT OBSSIG OF MTYPE 33 IS SET
      IF(LOTHER( 8)) KOBSG2=KOBSUM( 8)
!
      IF(LPSBL) THEN
      DO 7171 NN=1,NM
      AA(KSMCOR-1+NN)=ZERO
 7171 END DO
      ENDIF
!
!CCC  IF(LOTHER( 9)) KEDSIG=KOBSUM( 9)
!CCC  IF(LOTHER(10)) KEDSG2=KOBSUM(10)
!
!c             write(6,*) 'obsrd: ksmcor ', ksmcor
!c             write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,nm)
!c             WRITE(6,*) ' OBSRD: before 7500 KOBSUM ',KOBSUM
!c             WRITE(6,*) ' OBSRD: AA(KOBSUM)  ',(AA(KOBSUM(iij)),iij=1,
!c             write(6,*) 'obsrd: lother ', lother
!________________________
!
!c             write(6,*) 'obsrd: ksmcor ', ksmcor
!c             write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,nm)
      DO 7500 J=2,NHEADR
      JL1=J-1
      DO 7500 I=2,9
!c             write(6,*) 'obsrd: 7500 loop i, j , lpre(i,jl1) ',
!c            &                             i, j , lpre(i,jl1)
      IF(LPRE(I,JL1)) GO TO 7500
      INDCOR=I
!c             write(6,*) 'obsrd: 7500 loop i, j , lswtch(i,j) ',
!c            &                             i, j , lswtch(i,j)
      IF(.NOT.LSWTCH(I,J)) GO TO 9200
      N1=JOBCOR(I,J)
      N2=N1+NM-1
!c             write(6,*) 'obsrd: before 7450 in 7500 loop'
!c             PRINT 97000,I,J,(AA(N),N=N1,N2)
!
!     ....remove the offset correction from the sum of corrections
!     ....and later replace with input offset correction
!
      if( i .eq. 2 .and. loclrs ) then
!c                write(6,*) 'obsrd: before 7435 loop ksmcor ', ksmcor
!c                write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,n
         DO 7435 N=1,NM
!cc            write(6,*) 'obsrd: 7435 loop N, aa(N1+N), AA(ksmcor-1+N)
!cc     1                                   N, aa(N1+N), AA(ksmcor-1+N)
            AA(ksmcor-1+N)= AA(ksmcor-1+N) - aa(N1-1+N)
!cc            write(6,*) 'obsrd: 7435 loop N, aa(N1+N), AA(ksmcor-1+N)
!cc     1                                   N, aa(N1+N), AA(ksmcor-1+N)
 7435    CONTINUE
!c                write(6,*) 'obsrd: after 7435 loop ksmcor ', ksmcor
!c                write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,n
      endif
!
!
      IF((LATMOD.OR.MTYPE.EQ.101).AND.(I.EQ.3.OR.I.EQ.4)) GO TO 7500
!
      DO 7450 N=N1,N2
      AA(N)=ZERO
 7450 END DO
!c     write(6,*) 'obsrd: after 7450 in 7500 loop'
!c     print *,'obsrd: i,j ',i,j,jobcor(i,j)
!c     print *,'obsrd: N1,N2 ',N1,N2
!c             PRINT 97000,I,J,(AA(N),N=N1,N2)
 7500 CONTINUE
!c             write(6,*) 'obsrd: below 7500'
!c             write(6,*) 'obsrd: ksmcor ', ksmcor
!c             write(6,*) 'obsrd: sumcor ', (aa(ksmcor-1+iij),iij=1,nm)
!________

      IF(MTYPE.EQ.110) THEN
      DIST=AA(JOBCOR(7,8))*1000
      KDIST=AINT(DIST+0.00001)
      DSIGM=AA(JOBCOR(8,8))*1000.D0
      KDSIG=AINT(DSIGM+0.00001)
      N1=JOBCOR(6,8)
      N2=N1+NM-1
      JCKEY=KCN110+KCNBST0 -1
      DO 7508 N=N1,N2
      KEY=AA(N)+0.05D0
      II(JCKEY)=KEY
!     write(6,*)' dbg OBSRD CONSTR KEY 110 LOCATION',II(JCKEY),JCKEY,KEY
      JCKEY=JCKEY+1
 7508 END DO
      ENDIF

      IF(MTYPE.EQ.111) THEN
      DIST=AA(JOBCOR(7,8))*1000
      KDIST=AINT(DIST+0.00001)
      DSIGM=AA(JOBCOR(8,8))*1000.D0
      KDSIG=AINT(DSIGM+0.00001)
      N1=JOBCOR(6,8)
      N2=N1+NM-1
      JCKEY=KCN111+KCNBST1-1
      DO 7509 N=N1,N2
      KEY=AA(N)+0.05D0
      II(JCKEY)=KEY
!     write(6,*)' dbg OBSRD CONSTR KEY 111 LOCATION',II(JCKEY),JCKEY,KEY
      JCKEY=JCKEY+1
 7509 END DO
      ENDIF

      IF(MTYPE.NE.33) GO TO 1379
       IF(NINTOT.EQ.0) THEN
!   IMAGE KEY IDENTIFICATION
      N1=JOBCOR(6,8)
      N2=N1+NM-1
      JIMK=KIMKEY+KIMBST-1
      DO 7510 N=N1,N2
! CHECK IF CROSSOVER KEY IS ODD OR EVEN
! AND LOAD THE CROSSOVER ARRAY
! BEGIN COUNTING OBSERVATIONS
      IMG=AA(N)+0.05D0
      II(JIMK)=IMG
!     write(6,*)' dbg OBSRD IMAGE KEY AND LOCATION',II(JIMK),JIMK,IMG
      JIMK=JIMK+1
 7510 END DO

!   IMAGE VECTORS IDENTIFICATION
      N1=JOBCOR(7,8)
      N2=N1+NM-1
      N3=JOBCOR(8,8)
      N4=N3+NM-1
      N5=JOBCOR(9,8)
      N6=N5+NM-1
      DO 7511 N=N1,N2
      VIMAGE(1)=AA(N)
 7511 END DO
      DO 7512 N=N3,N4
      VIMAGE(2)=AA(N)
 7512 END DO
      DO 7513 N=N5,N6
      VIMAGE(3)=AA(N)
 7513 END DO
!     write(6,*)' dbg OBSRD VIMAGE ',VIMAGE
       ELSE
!   IMAGE VECTORS IDENTIFICATION FOR RAPID INTEGRATION
      N1=JOBCOR(4,8)
      N2=N1+NM-1
      N3=JOBCOR(5,8)
      N4=N3+NM-1
      N5=JOBCOR(6,8)
      N6=N5+NM-1
      N7=JOBCOR(7,8)
      N8=N7+NM-1
      N9=JOBCOR(8,8)
      N10=N9+NM-1
      N11=JOBCOR(9,8)
      N12=N11+NM-1
      DO  N=N1,N2
      VIMAGE(1)=AA(N)
      ENDDO
      DO  N=N3,N4
      VIMAGE(2)=AA(N)
      ENDDO
      DO  N=N5,N6
      VIMAGE(3)=AA(N)
      ENDDO
      DO  N=N7,N8
      VIMAGE(4)=AA(N)
      ENDDO
      DO  N=N9,N10
      VIMAGE(5)=AA(N)
      ENDDO
      DO  N=N11,N12
      VIMAGE(6)=AA(N)
      ENDDO
       ENDIF

1379  CONTINUE

!   LANDMARK
      IF(MTYPE.EQ.34) THEN
      QURSYS=AA(JOBCOR(3,8))
      N5=JOBCOR(6,8)
      N6=N5+NM-1
      DO  N=N5,N6
      VIMAGE(3)=AA(N)
      ENDDO
      ENDIF


      IF(MTYPE.NE.100) GO TO 1389
! CROSSOVER KEY IDENTIFICATION
! INITIALIZE CROSSOVER INDEXX ARRAY
      N1=JOBCOR(6,8)
      N2=N1+NM-1
      JXVK=KXVKEY+KXBST-1
      DO 7520 N=N1,N2
! CHECK IF CROSSOVER KEY IS ODD OR EVEN
! AND LOAD THE CROSSOVER ARRAY
! BEGIN COUNTING OBSERVATIONS
      IXOV=AA(N)+0.05D0
      II(JXVK)=IXOV
!     write(6,*)' dbg OBSRD KEY AND LOCATION',II(JXVK),JXVK
      JXVK=JXVK+1
 7520 END DO
! CROSSOVER KEY IDENTIFICATION
 1389 CONTINUE
      IF(MTYPE.NE.101) GO TO 1399
! CROSSOVER-2 KEY IDENTIFICATION
! INITIALIZE CROSSOVER INDEX ARRAY
      N1=JOBCOR(6,8)
!     N2=N1+NM-1
      JXVK=KXVKEY+KXBST-1
!     DO 7521 N=N1,N2
! CHECK IF CROSSOVER KEY IS ODD OR EVEN
! AND LOAD THE CROSSOVER ARRAY
! BEGIN COUNTING OBSERVATIONS
      IXOV=AA(N1)+0.05D0
      II(JXVK)=IXOV
!     JXVK=JXVK+1
!7521  CONTINUE
!     write(6,*)' dbg OBSRD IXOV KXBST ',IXOV,KXBST
! CROSSOVER-2 KEY IDENTIFICATION
 1399 CONTINUE
      INDCOR=74
      N=1
      IF(LGEOID.AND..NOT.LSWTCH(4,8)) GO TO 9150
      INDCOR=42
      N=2
      IF(LETIDE.AND..NOT.LSWTCH(2,5)) GO TO 9150
      INDCOR=43
      N=3
      IF(LOTIDE.AND..NOT.(LSWTCH(3,5).OR.LSWTCH(4,5))) GO TO 9150
97000 FORMAT(' ** OBSRD 97000**  I,J =',2I12,5X,'OBSCOR(N,I,J) ='/      &
     &   (1X,6D12.5))
!________
      J=KSMCOR
      K=J+NM-1
      M=1
      IF(LAVGRR) M=2
!     write(6,*) 'obsrd: lavgrr, m   ', lavgrr, m
      J=0
      DO 8000 N=1,M
      DO 8000 K=1,4
      J=J+1
      DO 8000 I=1,6
      KFSECS(I,J)=JNEXT
!      print *,'obsrd: jnext,i,j,kfsecs: ',jnext,i,j,kfsecs(i,j)
!      print *,'obsrd: i,k,lfsecs: ',i,k,lfsecs(i,k)
      IF(LFSECS(I,K)) then
      JNEXT=JNEXT+NM
      endif
 8000 CONTINUE
!c             write(6,*) 'obsrd: after 8000 sumcor ',
!c            &         (aa(ksmcor-1+iij),iij=1,nm)
!     IF(ICBDGM.EQ.ITBDGM.AND..NOT.LGRELE.AND..NOT.LVLBI) GO TO 8110
      J=0
      DO 8100 N=1,M
      DO 8100 K=1,4
      J=J+1
      DO 8100 I=1,6
      KDELCT(I,J)=JNEXT
      IF(LFSECS(I,K)) JNEXT=JNEXT+NM
 8100 CONTINUE
!c             write(6,*) 'obsrd: after 8100 sumcor ',
!c            &              (aa(ksmcor-1+iij),iij=1,nm)
      IF(.NOT.LITER1) GO TO 8110
      LRLCLK=.FALSE.
      LPRE(8,1)=.FALSE.
      LPRE(8,2)=.FALSE.
      LPRE(8,3)=.FALSE.
      LPRNRM(8,1)=.FALSE.
      LPRNRM(8,2)=.FALSE.
      LPRNRM(8,3)=.FALSE.
 8110 CONTINUE
      SIGNL=-ONE
! CLEAR COMPUTED OBSERVATION ARRAY
      I=KOBSC
      DO 8200 N=1,NM
      AA(I)=ZERO
      I=I+1
 8200 END DO
!c             write(6,*) 'obsrd: after 8200 sumcor ',
!c            &              (aa(ksmcor-1+iij),iij=1,nm)
! Initialize Ramped Doppler Arrays
!     IF(INDRAM.GT.0) THEN
      DO 8510 I=1,MINTIM*6
      AA(KPRL1-1+I)=0.D0
      AA(KPRL2-1+I)=0.D0
 8510 END DO
      DO 8511 I=1,MINTIM*2
      AA(KRL1-1+I)=0.D0
 8511 END DO
!     ENDIF
      IF(.NOT.LITER1) RETURN
! ADD FRACTIONAL SECONDS OF BLOCK START TO ELAPSED TIMES
! AND SUBTRACT SUM OF TIME CORRECTIONS FROM ELAPSED TIMES
      I=KOBTIM
      J=KTMCOR
      ISIG=KOBSIG
      KEDS=KEDSIG
      KED2=KEDSG2
      IF(.NOT.LPSBL)GOTO 8399
! CLEAR  AA(KTMCOR) ARRAY AND  AA(KOBTIM) ARRAY
      DO 8398 INDX=1,NM
      AA(I-1+INDX)=ZERO
      AA(J-1+INDX)=ZERO
      AA(ISIG-1+INDX)=ZERO
      AA(KEDS-1+INDX)=ZERO
      AA(KED2-1+INDX)=ZERO
 8398 continue
      GOTO 8410
 8399 CONTINUE
!c             write(6,*) 'obsrd: after 8399 sumcor ',
!c            &             (aa(ksmcor-1+iij),iij=1,nm)
      DO 8400 N=1,NM
      AA(I)=AA(I)-AA(J)+FSECBL
      J=J+1
      I=I+1
 8400 END DO
! LOAD EVENT TIMES ARRAY CORRECTING FOR ET-UTC
 8410 CONTINUE
      J=KFSECS(1,1)
      CALL UTCET(.TRUE.,NM,MJDSBL,AA(KOBTIM),AA(J),AA(KA1UT))
!            PRINT 11113,(AA(iij),iij=J,J-1+NM)
!11113 FORMAT(' ** OBSRD **  FSECM ='/(1X,5G24.16))

!
!     ....LPSBL is true if simulated data
!
      IF(.NOT.LPSBL)GOTO 8440
      JJK=KOBTIM
      JJNM=KOBTIM+NM-1
      KL=1
      DO 8425 I=JJK,JJNM
      AA(I)=FSCSDM(KL)
      KL=KL+1
 8425 END DO
      I1=KFSECS(1,1)
      CALL UTCET(.TRUE.,NM,MJDSBL,AA(KOBTIM),AA(I1),AA(KA1UT))
!
! ZERO OUT AA(KOBS) THE PART OF THE DYNAMIC ARRAY WHERE THE
! OBSERVATIONS ARE AND AA(KSMCOR) WHERE THE SUM OF THE OBSERVATION
! CORRECTIONS ARE.
!
      JK=KOBS
      JEND=KOBS+NM-1
      DO 8430 I=JK,JEND
      AA(I)=ZERO
 8430 END DO
      JK=KNOISE
      JEND=KNOISE+NM-1
      DO 8435 I=JK,JEND
      AA(I)=ZERO
 8435 END DO
!c             write(6,*) 'obsrd: 8440 sumcor ', (aa(iij),iij=jk,jend)
 8440 CONTINUE
! INITIALIZE LOGICAL ARRAY FOR SST EDITING
      DO 8436 I=1,NM
      LL(KLSDAT+I-1)=.TRUE.
 8436 END DO
!c             write(6,*) 'obsrd: after 8440 sumcor ',
!c            &          (aa(ksmcor-1+iij),iij=1,nm)
!
!
      IF(MTYPE.EQ.13) GO TO 8800
      IF(MTYPE.EQ.36) GO TO 8888
      IF(MTYPE.LT.61.OR.MTYPE.GT.98) GO TO 8500
8888  CONTINUE
!
! DIFFERENCE MEASUREMENTS!
!
! Difference observations may involve clocks at two receivers.
! The nominal differences in epochs are accounted for by adding those
! differences to the observation times of the primary receiver (+ side
! of difference) to obtain the observation times of the secondary
! receiver (- side of difference). This is the function of ADDTIM.
!
! Measurement types 61-84 are single difference measurements.
! Measurement types 85-98 are double difference measurements.
      M=2
      IF(MTYPE.GT.84) M=3
      I=KFSECS(1,M)
      J=KFSECS(1,1)
      K=KIAUNO
      SIGNA= ONE
      CALL ADDTIM(AA(I),AA(J),AA(K),SIGNA,NM)
      IF(MTYPE.LT.85) GO TO 8500
! Double difference observations are formed by differencing four
! independent observations. Generally two receivers are involved
! (although sometimes only one). GEODYN assumes two receivers even
! though they may be identical. To accomplish this, reception times
! must be defined for all four observations. EQUATE is called to
! define the two times not presently defined at this point.
      DO 8450 M=2,4,2
      I=KFSECS(1,M)
      J=KFSECS(1,M-1)
      CALL EQUATE(AA(I),AA(J),NM)
 8450 END DO
 8500 CONTINUE
!c             write(6,*) 'obsrd: at return sumcor ',
!c            &          (aa(ksmcor-1+iij),iij=1,nm)
      IF(.NOT.LAVGRR) RETURN
! Average range rates are modeled by GEODYN as differences between
! ranges computed at the beginning of the Doppler counting interval and
! the end of the Doppler counting interval. The time tag provided with
! the observations corresponds to the end of the counting interval.
! The counting interval must be subtracted from this time to obtain
! the time of the beginning of the counting interval. ADDTIM is called
! to perform this function.
      I=KFSECS(1,5)
      J=KFSECS(1,1)
      K=KDTIME
!     write(6,*) 'obsrd: i,j,kdtime ', i, j, kdtime
!
!     ....FOR SIMULATED DATA GENERATION OF DOPPLER DATA, LOAD
!     ....OBSERVATION INTERVAL
!
      IF(LPSBL) THEN
         DO 8600 I1=1,NM
            AA(K-1+I1)=OBSINT
 8600    CONTINUE
      ENDIF
      SIGNA=-ONE
      CALL ADDTIM(AA(I),AA(J),AA(K),SIGNA,NM)
      IF(MTYPE.EQ.36) GOTO 7777
      IF(MTYPE.LT.61.OR.MTYPE.GT.98) RETURN
! ADDTIM is called here to account for differences in observing epochs
! at the beginning of the counting interval.
7777  CONTINUE
      M=6
      IF(MTYPE.GT.84) M=7
      I=KFSECS(1,M)
      J=KFSECS(1,5)
      K=KIAUNO
      SIGNA= ONE
      CALL ADDTIM(AA(I),AA(J),AA(K),SIGNA,NM)
!     WRITE(6,*)' dbg 2  KOBCOR OBSRD ',KOBCOR(8,2),AA(KOBCOR(8,2))
      IF(MTYPE.LT.85) RETURN
! EQUATE is called here to define reception times for remaining two
! legs of double difference measurements at beginning of counting
! interval.
      DO 8550 M=6,8,2
      I=KFSECS(1,M)
      J=KFSECS(1,M-1)
      CALL EQUATE(AA(I),AA(J),NM)
 8550 END DO
      IF(.NOT.LPSBL) GOTO 8620
      IO=0
      DO 8610 IJ=1,NM
      AA(K+IO)=OBSINT
      IO=IO+1
 8610 END DO
 8620 CONTINUE
      RETURN
! If SATCLC or SATCL2 have been used by GEODYN D.F. then the time
! tag will be satellite time. Let received time (AA(KFSECS(1,1)) equal
! tagged time and skip light time corrections. This will introduce a
! small positioning error for the station. Call EQUATE to load
! satellite time (AA(KFSECS(2,1)) from received time.
 8800 CONTINUE
!     write(6,*) 'obsrd: below 8800 '
      K=MOD(ITSYS,10000)/100
!     write(6,*) 'obsrd: itsys, k   ', itsys, k
      IF(K.NE.1) RETURN
      I=KFSECS(2,1)
      J=KFSECS(1,1)
!     write(6,*) 'obsrd: i, j   ', i, j
      CALL EQUATE(AA(I),AA(J),NM)
      LIGHT=.TRUE.
      RETURN
!
!     ....ERROR RETURNS
!
 9000 CONTINUE
      JLINE6=ILINE6+3
      IF(JLINE6.LE.MLINE6) GO TO 9100
      IPAGE6=IPAGE6+1
      JLINE6=4
      WRITE(IOUT6,10000) IPAGE6
 9100 CONTINUE
      WRITE(IOUT6,91000) MJDSOB,MJDSBL
      ILINE6=JLINE6
      STOP 16
!
 9150 CONTINUE
      WRITE(IOUT6,91500) INDCOR,AMODEL(N)
      GO TO 9225
 9200 CONTINUE
! LSWTCH,LPRE
      WRITE(IOUT6,92000) INDCOR,JL1
 9225 CONTINUE
      WRITE(IOUT6,92100) (LPRE9(iij),iij=1,24)
      WRITE(IOUT6,92200) (LSWTCH(iij,1),iij=1,9)
      DO 9250 J=1,NHEADB
      JP1=J+1
      WRITE(IOUT6,92300) J,(LPRE(iij,J),iij=1,24)
      WRITE(IOUT6,92400) (LSWTCH(iij,JP1),iij=1,9)
 9250 END DO
      STOP 16
10000 FORMAT('1',109X,'UNIT  6 PAGE NO.',I6)
23000 FORMAT('0OBSRD  ** STATION NUMBER(',I10,') IN OBSERVATION',       &
     &   ' HEADER(',I10,') NOT FOUND IN STATION NUMBER LIST'/1X )
27000 FORMAT('0OBSRD  ** SATELLITE NUMBER(',I10,') IN OBSERVATION',     &
     &   ' HEADER(',I10,') NOT FOUND IN SATELLITE NUMBER LIST'/1X )
27020 FORMAT('0OBSRD  ** QUASAR ID NUMBER(',I10,') IN OBSERVATION',     &
     &   ' HEADER(',I10,') NOT FOUND IN QUASAR ID NUMBER LIST'/1X )
60000 FORMAT(' ')
60001 FORMAT(' EXECUTION TERMINATING IN OBSRD RAMPED DATA WITH MT ',I10)
60002 FORMAT(' EXECUTION TERMINATING IN OBSRD. IONOSPHERIC REFACTION')
60003 FORMAT(' FLAGS INCONSISTENT ON A BLOCK OF RAMPED DATA')
60004 FORMAT(' MTYPE=',I4,' MJDSBL=',I10)
60005 FORMAT(' COMPUTATION REQUESTED, BUT THE DATA ARE ALREADY')
60006 FORMAT(' CORRECTED')
91000 FORMAT('0OBSRD  ** MODIFIED JULIAN DATE SECONDS IN OBSERVATION',  &
     &   ' HEADER(',I10,') DISAGREES WITH DIRECTORY(',I10,')'/1X )
91500 FORMAT('0OBSRD  ** PARTITION ',I2,' NOT PROVIDED FOR ',           &
     &   'ALTIMETER ',A8,' MODEL'/1X )
92000 FORMAT('0OBSRD  ** PARTITION ',I1,' NOT PROVIDED FOR ',           &
     &   'PREPRO CORR. REQUESTED BY HEADER #',I1/1X )
92100 FORMAT(' MASTER HEADER PREPRO WORD =',24(1X,L1))
92200 FORMAT(' DATA PARTITIONS PRESENT   =', 9(1X,L1))
92300 FORMAT(' HEADER RECORD #',I1,' PREPRO WORD =',24(1X,L1))
92400 FORMAT(' OBSCOR PARTITIONS PRESENT    =',      9(1X,L1))
98000 FORMAT(' EXECUTION TERMINAPING IN OBSRD. BIAS POINTER PROBLEM')
98001 FORMAT(' IN A GPS RUN (GPSMOD OPTION) A BLOCK OF DATA USED')
98002 FORMAT(' SIMPLE MEASURMENT BIASES AND SCALE BIASES.')
98003 FORMAT(' BLOCK START : ',I8,I6,1X,F10.3)
98004 FORMAT(' BLOCK MEASUREMENT TYPE : ',I8)
98005 FORMAT(' BLOCK MEASUREMENT SATELLITES ',3I12)
98006 FORMAT(' BLOCK MEASUREMENT STATIONS   ',3I12)
98007 FORMAT(' WARNING; PHASE WIND UP CAN NOT BE APPLIED')
98008 FORMAT(' FOR A BLOCK OF DATA FOLLOWING A CYCLE SLIP ')
98009 FORMAT(' THE PRECEEDING BLOCK COULD NOT BE FOUND ')
98010 FORMAT(' THE DATA FROM THIS BLOCK WILL BE DELETED')
      END
