      SUBROUTINE OCCUSS(XSAT1,XSAT2,LOCCLT,NM,NDIM)
!
!  CHECK IF A SAT - SAT LINK IS OCCULTED BY THE ORBITED BODY
!  GIVEN THE PLANET CENTERED COORDINATES OF THE TWO SATELLITES
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      DIMENSION XSAT1(NDIM,3),XSAT2(NDIM,3)
      DIMENSION LOCCLT(NM)
!
      DO 100 I=1,NM
!
!
      TERM1=(XSAT1(I,1)-XSAT2(I,1))
      TERM2=(XSAT1(I,2)-XSAT2(I,2))
      TERM3=(XSAT1(I,3)-XSAT2(I,3))
      RHS=-XSAT2(I,1)*TERM1                                             &
     &    -XSAT2(I,2)*TERM2                                             &
     &    -XSAT2(I,3)*TERM3
      XMULT=TERM1*TERM1+TERM2*TERM2+TERM3*TERM3
      TT=RHS/XMULT
!  TT IS THE % DISTANCE ALONG THE SS LINK WHERE THE
!  PERPENDICULAZE FROM THE PLANET CENTER HITS (THE
!  CLOSEST PT ON THE SS LINK TO PLANET CENTER)
      IF(TT.GT.1.D0.OR.TT.LT.0.D0) GO TO 100
      XX=XSAT2(I,1)+TT*TERM1
      YY=XSAT2(I,2)+TT*TERM2
      ZZ=XSAT2(I,3)+TT*TERM3
      RCHECK=SQRT(XX*XX+YY*YY+ZZ*ZZ)
      IF(RCHECK.GT.AE) GO TO 100
      LOCCLT(I)=.TRUE.
 100  CONTINUE
      RETURN
      END
