      SUBROUTINE ODRSR2(AA,II,LL,NDIR,IDWPT,DWTM,OBSBUF)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  ODRSR2
!
!  PURPOSE: SORT TRACKING DATA DIRECTORY RECORDS SO THEY WILL BE
!           IN TIME ORDER. FOR PLANETARY RUNS TAKE INTO ACCOUNT
!           LIGHT TIMES SO THAT THE DIRECTORY WILL BE IN ORDER
!           OF SATELLITE EVENT TIMES.
!
!     AA    GEODYN's DYNAMIC  ARRAY FOR FLOATING POINTS
!     II    GEODYN's DYNAMIC  ARRAY FOR INTEGERS
!     LL    GEODYN's DYNAMIC  ARRAY FOR LOGICALS
!     NDIR  NUMBER OF TRACKING DATA DIRECTORY RECORDS (OUTPUT)
!     IDWPT POINTER ARRAY THAT POINTS TO DIRECTORY
!           IN TIME ORDER (OUTPUT)
!     DWTM  SCRATCH ARRAY USED TO HOLD DIRECTORY RECORD TIMES
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/COBBUF/IOBSBF,IBUF1 ,IBUF2 ,IWORD1,NHEADR,NWORDM
      COMMON/COBDIR/DWORD(100),CDIREC,TDIREC
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION IDWPT(NDIR),DWTM(NDIR)
      DIMENSION OBSBUF(MOBBUF)
!
      DO 10 I=1,NDIR
      CALL OBSDIR(AA,II,LL,LEOF)
      IDWPT(I)=I
      DWTM(I)=DWORD(1)+DWORD(2)
      IBUF1 =INT(DWORD(3))
      IBUF2 =INT(DWORD(4))
      IWORD1=INT(DWORD(5))
      CALL OBSIN (AA,OBSBUF,IOBSBF,IBUF1,IBUF2)
      MTYPE =INT(OBSBUF(IWORD1+4))
      IF(ICBDGM.NE.ITBDGM) THEN
      IF(MTYPE.GT.40.AND.MTYPE.LT.90) THEN
        IJD=INT(DWORD(1))
        FSC=DWORD(2)
        CALL LITPRX(IJD,FSC,MJDSST,FSECST,AA,II)
        DWTM(I)=DBLE(MJDSST)+FSECST
      ENDIF
      ENDIF
  10  CONTINUE
      IF(.NOT.LEOF) CALL OBSDIR(AA,II,LL,LEOF)
!
!
      NDIR1=NDIR-1
      DO 200 I=1,NDIR1
      J1=I+1
      DO 100 J=J1,NDIR
      IF(DWTM(I).LE.DWTM(J)) GO TO 100
      H=DWTM(I)
      IH=IDWPT(I)
      DWTM(I)=DWTM(J)
      IDWPT(I)=IDWPT(J)
      DWTM(J)=H
      IDWPT(J)=IH
 100  CONTINUE
 200  CONTINUE
!
      RETURN
      END
