!$OLDEOP
      SUBROUTINE OLDEOP(MJDSEC,FSEC,NM,ABCOF,ANGFAC,SPEED,XLOCV,        &
     &                 XYZC,TRIGOL,SCR2,LADJOL,PXSPAB,NEAJ,NNAJ,        &
     &                 NVAJ,IPAJE,IPAJN,IPAJV ,ABCCM ,PXSPA1,NXCJ,NYCJ, &
     &                 NZCJ,IPAXC,IPAYC,IPAZC ,ABCEO ,PXSPA2,NXPJ,NYPJ, &
     &                 NUPJ,IPAXP,IPAYP,IPAUP ,LOLD,LXYC,LEOP,XM)
!********1*********2*********3*********4*********5*********6*********7**
! OLOAD            00/00/00            8604.0    PGMR - ?
!
! FUNCTION:  COMPUTES OCEAN LOADING DISPLACEMENT
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    START BLOCK SATELLITE INTEGER TIME
!   FSEC     I    A    FRACTIONAL SECONDS OF BLOCK MEASUREMENT TIMES
!   NM       I    S    NUMBER OF OBSERVATIONS IN THE BLOCK
!   ABCOF    O    S    FREQUENCIES FOR OCEAN LOADING
!   ANGFAC   I    A    FACTORS TO MULTIPLY EACH OF THE 5 ARGUMENTS BY
!                      PLUS A -/+ PHASE FOR CERTAIN DOODSON NUMBERS
!   SPEED    I    A    RATE OF ANGULAR ARGUMENT FOR EACH FREQUENCY
!   XLOCV    I    A    OCEAN LOADING PARAMETERS COVARIANCE MATRIX
!   XYZC     O    A    X,Y,Z FOR OCEAN LOADING
!   TRIGOL   I    A    COSINES AND SINES OF OCEAN LOADING FREQURNCIES
!                      AT BLOCK START TIME (IN SOME CASES MODIFIED
!                      FOR SIDE BANDS). ALSO DERIVATIVES WRT OF
!                      THE COSINE AND SINES. DERIVATIVES IN FIRST
!                      TWO SLOTS. COSINES AND SINES IN SLOTS 3&4
!   SCR2    I/O   A    SCRATCH ARRAY FOR INTERMEDIATE CALCULATION
!   LADJOL   I    S    .TRUE. IF OCEAN LOADING IS TO BE ADJUSTED
!   PXSPAB   O    A    THE PART OF PMPA FOR OCEAN LOADING
!   NEAJ     I    S    POINTER TO OCEAN LOADING EAST INFO FROM
!                      COMMON/OLDADJ/
!   NNAJ     I    S    POINTER TO OCEAN LOADING NORTH INFO FROM
!                      COMMON/OLDADJ/
!   NVAJ     I    S    POINTER TO OCEAN LOADING VERTICAL INFO FROM
!                      COMMON/OLDADJ/
!   IPAJE    I    A    POINTER TO EAST INFO OF IOLDPA ARRAY
!   IPAJN    I    A    POINTER TO NORTH INFO OF IOLDPA ARRAY
!   IPAJV    I    A    POINTER TO VERTICAL INFO OF IOLDLPA ARRAY
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      DIMENSION ANGFAC(NTOLFR,6),SPEED(NTOLFR),XLOCV(3,3)
      DIMENSION TRIGOL(NTOLFR,4),ABCOF(NTOLFR,2,3)
      DIMENSION ABCCM(NTOLFR,2,3)
      DIMENSION ABCEO(NTOLFR,2,3)
      DIMENSION IPAJE(1),IPAJN(1),IPAJV(1)
      DIMENSION IPAXC(1),IPAYC(1),IPAZC(1)
      DIMENSION IPAXP(1),IPAYP(1),IPAUP(1)
      DIMENSION SCR2(NM),XYZC(NM,3),FSEC(NM),PXSPAB(NM,3,1)
      DIMENSION PXSPA1(NM,3,1)
      DIMENSION PXSPA2(NM,3,1)
      DIMENSION XM(3)
      COMMON/CTHDOT/THDOT
      COMMON/LOLOAD/LOLMD,LOLAJ,L2FOLT,LAPLOD
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      COMMON/TIDEOP/EOPTID(2,3)
      DATA ZERO/0.D0/
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!
      I0OFF=ABS(FSEC(1))
      IF(FSEC(1).LT.0.D0) I0OFF=-I0OFF
      FSCO=-I0OFF

!
! FIGURE DELTX,DELTY,DELTZ AT START OF BLOCK
      DELTX0=ZERO
      DELTY0=ZERO
      DELTZ0=ZERO
      DO 135 N=1,NTOLF2
      DELTX0=DELTX0+ABCEO(N,1,1)*TRIGOL(N,3)
      DELTY0=DELTY0+ABCEO(N,1,2)*TRIGOL(N,3)
      DELTZ0=DELTZ0+ABCEO(N,1,3)*TRIGOL(N,3)
  135 END DO
      DXDT=ZERO
      DYDT=ZERO
      DZDT=ZERO
      DO 155 N=1,NTOLF2
      DXDT=DXDT+ABCEO(N,1,1)*TRIGOL(N,1)
      DYDT=DYDT+ABCEO(N,1,2)*TRIGOL(N,1)
      DZDT=DZDT+ABCEO(N,1,3)*TRIGOL(N,1)
  155 END DO
      EOPTID(1,1)=DELTX0+DXDT*(FSEC(1)+FSCO)
      EOPTID(2,1)=DELTX0+DXDT*(FSEC(NM)+FSCO)
      EOPTID(1,2)=DELTY0+DYDT*(FSEC(1)+FSCO)
      EOPTID(2,2)=DELTY0+DYDT*(FSEC(NM)+FSCO)
      EOPTID(1,3)=DELTZ0+DZDT*(FSEC(1)+FSCO)
      EOPTID(2,3)=DELTZ0+DZDT*(FSEC(NM)+FSCO)
!
!
      IF(.NOT.LADJOL) RETURN
!
! FORM THE PARTIALS FOR EAST
      IF(NXPJ.LE.0) GO TO 1550
      JCT=0
      DO 1500 I=1,NXPJ
      JCT=JCT+1
      JFREQ=IPAXP(I)
      DO 1410 N=1,NM
      FSCN=FSEC(N)+FSCO
      PXSPA2(N,1,JCT)= XM(3)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
!     PXSPA2(N,2,JCT)=ZERO
      PXSPA2(N,2,JCT)= XM(3)*(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
!     PXSPA2(N,3,JCT)= XM(1)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
      PXSPA2(N,3,JCT)=-XM(1)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)     &
     &                -XM(2)*(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
      PXSPA2(N,1,JCT+NXPJ)=-XM(3)                                       &
     &                    *(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
!     PXSPA2(N,2,JCT+NXPJ)=ZERO
      PXSPA2(N,2,JCT+NXPJ)= XM(3)                                       &
     &                    *(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
!     PXSPA2(N,3,JCT+NXPJ)= XM(1)
!    1                    *(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
      PXSPA2(N,3,JCT+NXPJ)= XM(1)                                       &
     &                    *(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)       &
     &              -XM(2)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
 1410 END DO
 1500 END DO
 1550 CONTINUE
! FORM THE PARTIALS FOR NORTH
      IF(NYPJ.LE.0) GO TO 1650
      JCT=2*NXPJ
      DO 1600 I=1,NYPJ
      JCT=JCT+1
      JFREQ=IPAYP(I)
      DO 1560 N=1,NM
      FSCN=FSEC(N)+FSCO
      PXSPA2(N,1,JCT)=ZERO
      PXSPA2(N,2,JCT)=ZERO
      PXSPA2(N,3,JCT)=ZERO
!     PXSPA2(N,2,JCT)= XM(3)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
!     PXSPA2(N,3,JCT)=-XM(2)*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
      PXSPA2(N,1,JCT+NYPJ)=ZERO
      PXSPA2(N,2,JCT+NYPJ)=ZERO
      PXSPA2(N,3,JCT+NYPJ)=ZERO
!     PXSPA2(N,2,JCT+NYPJ)= XM(3)
!    1                    *(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
!     PXSPA2(N,3,JCT+NYPJ)=-XM(2)
!    1                    *(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
 1560 END DO
 1600 END DO
 1650 CONTINUE
! FORM THER PARTTIALS FOR VERT
      IF(NUPJ.LE.0) RETURN
      JCT=2*(NXPJ+NYPJ)
      DX=-XM(2)*THDOT
      DY= XM(1)*THDOT
      DO 1700 I=1,NUPJ
      JCT=JCT+1
      JFREQ=IPAUP(I)
      DO 1660 N=1,NM
      FSCN=FSEC(N)+FSCO
      PXSPA2(N,1,JCT)=DX*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
      PXSPA2(N,2,JCT)=DY*(TRIGOL(JFREQ,3)+TRIGOL(JFREQ,1)*FSCN)
      PXSPA2(N,3,JCT)=ZERO
      PXSPA2(N,1,JCT+NUPJ)=DX*(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
      PXSPA2(N,2,JCT+NUPJ)=DY*(TRIGOL(JFREQ,4)+TRIGOL(JFREQ,2)*FSCN)
      PXSPA2(N,3,JCT+NUPJ)=ZERO
 1660 END DO
 1700 END DO
      RETURN
      END
