!$ORBSET
      SUBROUTINE ORBSET(NSAT,IVSAT,LSETS,ISAT,                         &
     & KNSTEPS,NEQNI,ISEGM,T1SEG,                                      &
     & T2SEG,IRET,MJDS,T1,T2,NM,AA,II)
!********1*********2*********3*********4*********5*********6*********7**
! ORBSET           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:  DETERMINES WHICH SPACECRAFT PARAMETERS ARE REQUIRED TO BE
!            INTERPOLATED
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   NSAT     I    A    ID OF SATELLITE TO BE CHECKED FOR INTERPOLATION
!   IVSAT    O    A    ARRAY FILLED WITH SATELLITES TO BE INTERPOLATED
!   LSETS    O    A    LOGICAL FLAGS FOR THE SATELLITES TO BE
!                      INTERPOLATED
!   ISAT     I    S    INTERNAL SATELLITE INDEX
!   ISEGM    I    S    HOW MANY SEGMENTS TO BE READ FOR THIS SATELLITE
!                      IN THE GET MODE OF RAPID INTEGRATION.
!   KNSTEPS  I    S    HOW MANY STEPS ARE ALLOWED IN A BUFFER FOR THIS SATELLITE
!   IRET     I    S    THE S/C SEQUENCE NUMBER IN II(KISATN)
!   NEQNI    I    A    FORCE MODEL EQUATIONS FOR EACH SATELLITE PARTICIPATING
!                      IN RAPID INTEGRATION.
!   T1SEG    I    A    START TIME OF SEGMENT FOR EACH SATELLITE
!   T2SEG    I    A    END TIME OF SEGMENT FOR EACH SATELLITE
!   MJDS     I    S    BLOCK START SECONDS
!   T1       I    S    TIME OF FIRST OBSERVATION
!   T2       I    S    TIME OF LAST OBSERVATION
!   NM       I    S    NUMBER OF OBSERVATIONS.
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      CHARACTER*33 FILNAM
      SAVE
      COMMON/NSEGSC/NSEGM(80)
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/RAPIDI/LINTF,LBUFOP
      COMMON/SNAPXL/LXRSET
      COMMON/LSNAPX/LSNAP
      DIMENSION NSAT(NSETA),IVSAT(NSATA),LSETS(NSETA)
      DIMENSION JSTOS(3)
      DIMENSION HOS(1)
      DIMENSION T1SEG(10),T2SEG(10)
      DIMENSION AA(1),II(1)
      EQUIVALENCE (JSTOS(1),ISTOS1)
      DATA NSEGM/80*0/
      DATA kentry/0/
      DATA IUNT/64/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      ISATID=II(KISATN+ISAT-1)
! FOR "GET MODE" CHECK TIMES



      IF(NINTOT.EQ.0) GO TO 1200

      IF(LINTF) THEN
      IF(kentry.eq.0.OR.nsegm(iret).eq.0) then
      NG=1
      else
      NG=NSEGM(IRET)
      endif
      kentry=kentry+1
      TFIRST=DBLE(MJDS)+T1
      TLAST =DBLE(MJDS)+T2
      LREND=.FALSE.
      IF(TFIRST.GT.T2SEG(NG).OR.TLAST.GT.T2SEG(NG)) THEN
!     IF(TFIRST.GT.T2SEG(NG)) WRITE(6,*)' FIRST OBS BEYOND ',TFIRST,    &
!    & T2SEG(NG),NG,IRET
      LREND=.TRUE.
!     IF(TLAST.GT.T2SEG(NG)) WRITE(6,*)' SECOND  OBS BEYOND ',TLAST,    &
!    & T2SEG(NG),NG,IRET
!     WRITE(6,*)' dbg HERE NEED TO GO TO THE NEXT BUFFER '
      ENDIF
      ENDIF
!
      IF(LREND) GO TO 1200

! HERE FOR CROSSOVERS
      IF(LINTF.AND.LSNAP.AND.NSEGM(IRET).GT.1) THEN
      IF(TFIRST.LT.T2SEG(NG-1).AND.TLAST.LT.T2SEG(NG-1)) THEN
      NSEGM(IRET)=NSEGM(IRET)-2

      LREND=.TRUE.
      ENDIF

      ENDIF

1200  CONTINUE

      ISATID=II(KISATN+ISAT-1)
      IVSAT(1)=ISAT
      JSAT=0
      DO 1000 ISET=1,NSETA
      JSAT0=JSAT
      JSAT=JSAT+NSAT(ISET)
      LSETS(ISET)=(ISAT.GT.JSAT0).AND.(ISAT.LE.JSAT)
 1000 END DO
      IF(NINTOT.GT.0.AND..NOT.LINTF) RETURN
      IF(NINTOT.EQ.0) RETURN
!
      IF(LREND) THEN
      WRITE(6,*) 'dbg HERE WE NEED TO READ THE NEXT SEGMENT ',ISATID
      ENDIF
      IF(LREND) GO TO 2000
      IF(ISAT.EQ.ISTOS1) THEN
        INTOSP=1
        RETURN
      ENDIF
      IF(ISAT.EQ.ISTOS2) THEN
        INTOSP=2
        RETURN
      ENDIF
      IF(ISAT.EQ.ISTOS3) THEN
        INTOSP=3
        RETURN
      ENDIF
!
      IF(ISTLST.EQ.0) THEN
        INTOSP=1

        GO TO 2000
      ENDIF
      IF(ISTLST.EQ.1) THEN
        INTOSP=2
        GO TO 2000
      ENDIF
      IF(ISTLST.EQ.2) THEN
        INTOSP=3
        GO TO 2000
      ENDIF
      IF(ISTLST.EQ.3) THEN
        INTOSP=1
        GO TO 2000
      ENDIF

2000  CONTINUE
      NSEGM(IRET)=NSEGM(IRET)+1
      IF(LXRSET)NSEGM(IRET)=1
!CDEPDEP
      IF(ISEGM.EQ.1)NSEGM(IRET)=1
!CDEPDEP
      ISTLST=INTOSP
      JSTOS(INTOSP)=ISAT


! START READING.
      WRITE(FILNAM,FMT='(A13,I7,A4,I2,A7)')'RAPID_INT_SAT',ISATID,      &
     & '_SEG',NSEGM(IRET),'.COWELL'
      OPEN(IUNT,FILE=FILNAM,STATUS='OLD',FORM='UNFORMATTED')

! KNSTEPS here is the number of steps for this satellite in a buffer
      IF(NSEGM(IRET).EQ.ISEGM) THEN
      KNST=ILSTSG(IRET)
      ELSE
      KNST=KNSTEPS
      ENDIF

      NN=NEQNI*3
      NN2=NEQNI*6

      CALL READOS(IUNT,INTOSP,AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),   &
     &            AA(KTMOSP-1+INTOSP),          &
     &            AA(KSMXOS-1+MAPSAT(INTOSP,1)),                        &
     &            AA(KSMXOS-1+MAPSAT(INTOSP,2)),                        &
     &            AA(KSMXOS-1+MAPSAT(INTOSP,3)),                        &
     &            AA(KSMXOS-1+MAPSAT(INTOSP,4)),NEQNI,KNSTEPS,KNST,     &
     &            NN,NN2,HOS,ISAT)

      INTSUB(INTOSP)=KNST
      JNTSUB(INTOSP)=KNST
      LREND=.FALSE.
      CLOSE(64)

      RETURN
      END
