      SUBROUTINE PARTIT(MWORD,NPART,NSECT,NROWS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION NROWS(2,50)
!
!
      INDXNO(I)=I+NPART*(I-1)-(I*(I-1))/2
!
!
      NSECT=0
!
!
   10 CONTINUE
      NSECT=NSECT+1
      IF(NSECT.EQ.1) THEN
         NROWS(1,NSECT)=1
      ELSE
         NROWS(1,NSECT)=NROWS(2,NSECT-1)+1
      ENDIF
      IROW1=NROWS(1,NSECT)
      ISTRT=INDXNO(IROW1)-1
      DO 20 I=IROW1,NPART
      NWD=INDXNO(I)+(NPART-(I-1))-ISTRT
      IF(NWD.LT.MWORD) GO TO 20
      GO TO 30
   20 END DO
      NROWS(2,NSECT)=NPART
      RETURN
   30 CONTINUE
      NROWS(2,NSECT)=(I-1)
      GO TO 10
      END
