      SUBROUTINE PAS2S1(NM,NEQN,PXPF,PAPF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      DIMENSION PXPF(NEQN,3,NM),PAPF(NEQN,3,NM)
      DO 200 I=1,NM
      DO 100 J=1,NEQN
      PXPF(J,1,I)=PAPF(J,1,I)
      PXPF(J,2,I)=PAPF(J,2,I)
      PXPF(J,3,I)=PAPF(J,3,I)
 100  CONTINUE
 200  CONTINUE
      RETURN
      END
