!$
      SUBROUTINE PCORMP(AA,MTYPE,NM,FREQO,FRINT,NDIMFR,SF2,VLIGHT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      DIMENSION AA(1),FRINT(NDIMFR,2,2)
!
      IF(.NOT.LPRE9(6)) RETURN
!
      DO 200 IREC=1,2
      PLUSMC=SF2/VLIGHT
      IF(IREC.EQ.1.AND.MTYPE.EQ.54) PLUSMC=-PLUSMC
      JIONC=KOBCOR(6,IREC)-1
      IPTFR=1
      IF(IREC.EQ.2.AND.MTYPE.EQ.54) IPTFR=2
      DO 100 I=1,NM
      AA(KSMCOR-1+I)=AA(KSMCOR-1+I)                                     &
     &              +AA(JIONC+I)*PLUSMC*(FREQO+FRINT(I,1,IPTFR))
  100 END DO
  200 END DO
      RETURN
      END
