!$PDFEND
      SUBROUTINE PDFEND(PMPA)
!********1*********2*********3*********4*********5*********6*********7**
! PDFEND           86/03/28            8603.0    PGMR - TOM MARTIN
!
! FUNCTION:  OUTPUT SENTINEL RECORD TO PARTIAL DERIVATIVE FILE.
!            ENDFILE AND INCREMENT UNIT NUMBER AS NECESSARY.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PMPA          A    MEASUREMENT PARTIALS WITH RESPECT TO RECOVERED
!                      PARAMETERS
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CPARFI/IUNPF1,IUNPF2,IUNPFI,ISZPFI,NBLKPF,NWRDPF,MTCALL(4)
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      DIMENSION PMPA(NADJST),WORD50(50)
      DATA WORD50/50*-999999.0D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! NOTIFY USER OF SENTINEL RECORD OUTPUT
      WRITE(IOUT6,30000) IUNPFI
      NWRDPF=NWRDPF+NADJST+50
      NBLOCK=NWRDPF/512
      NWRDPF=NWRDPF-NBLOCK*512
      NBLKPF=NBLKPF+NBLOCK
      IF(NBLKPF.LE.ISZPFI) GO TO 1000
! WARN USER OF POSSIBLE FILE OVERFLOW
      WRITE(IOUT6,40000)
 1000 CONTINUE
! WRITE SENTINEL RECORD
      WRITE(IUNPFI) WORD50,PMPA
! OPTIONALLY ENDFILE OUTPUT UNIT
      IF(LPFEOF) END FILE IUNPFI
      IF(.NOT.LARCNU) GO TO 3000
! OPTIONALLY CLOSE OUTPUT FILE AT END OF ARC...
      REWIND IUNPFI
      WRITE(IOUT6,10000) IUNPFI,NBLKPF
      IF(LSTARC) GO TO 3000
!...AND OPEN NEW FILE.
      IUNPFI=IUNPFI+1
      IF(IUNPFI.GT.IUNPF2) GO TO 9000
! NOTIFY USER OF NEWLY OPENED FILE.
      WRITE(IOUT6,20000) IUNPFI
      NWRDPF=0
      NBLKPF=0
 3000 CONTINUE
      RETURN
 9000 CONTINUE
! FILE(S) OVERFLOW. NOTIFY USER.
      WRITE(IOUT6,90000) IUNPFI,IUNPF1,IUNPF2
      STOP 16
10000 FORMAT('0','UNIT =',I3,' CLOSED FOR PARTIAL DERIVATIVE FILE ',    &
     &   'OUTPUT WITH ',I10,' BLOCKS OF LENGTH 512 WORDS WRITTEN.')
20000 FORMAT('0','UNIT =',I3,' OPENED FOR PARTIAL DERIVATIVE FILE ',    &
     &   'OUTPUT.')
30000 FORMAT('0','WRITING PARTIAL DERIVATIVE FILE SENTINEL RECORD ON ', &
     &   'UNIT =',I3)
40000 FORMAT(' ** PDFEND **  WARNING!  OUTPUT OF PARTIAL DERIVATIVE ',  &
     &   'FILE SENTINEL WILL EXCEED SPECIFIED FILE SIZE.')
90000 FORMAT(' ** PDFEND **  PARTIAL DERIVATIVE FILE UNIT NUMBER ',     &
     &   'OUT OF RANGE.'/'0',14X,'UNIT NUMBER =',I12/                   &
     &   1X ,14X,'UNIT RANGE  =',I3,' TO ',I3)
      END
