!$PDFHDR
      SUBROUTINE PDFHDR(AA,II,LL,PARML0,PARMV0,PARMVC,MJDSB,FSECB,ETUTC)
!********1*********2*********3*********4*********5*********6*********7**
! PDFHDR           86/03/27            8603.0    PGMR - WFE/TVM
!
! FUNCTION:   OUTPUT PARTIAL FILE HEADER AND INFORMATION RECORDS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL    DATA
!   II      I/O   A    DYNAMIC ARRAY FOR INTEGER DATA
!   LL      I/O   A    DYNAMIC ARRAY FOR LOGICAL DATA
!   PARML0   I    A    PARAMETER LABELS
!   PARMV0   I    A    PARAMETER A PRIORI VALUES
!   PARMVC   I    A    PARAMETER CURRENT VALUES
!   MJDSB    I    A    INTEGER SECONDS OF EPOCH TIME SINCE GEODYN REF.TI
!   FSECB    I    A    FRACTIONAL SECONDS OF EPOCH TIME REMAINING
!   ETUTC    I    A    ET-UTC TIME DIFFERENCES
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/ARCPR /FSECRF,XARCPR
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CPARFI/IUNPF1,IUNPF2,IUNPFI,ISZPFI,NBLKPF,NWRDPF,MTCALL(4)
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/G2SINF/G2SVER,G2SDAT,G2SRTM,G2SCOM,TDFVER,TDFRTM,SETCDS,   &
     &              GPCKSM,GPDEG ,GPORD ,XG2SIN
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PARFIL/PFSW  ,PFUNT1,PFUNT2,PFNUMB,SEGSIZ,XPARFI
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION ETUTC(1),FSEC(1),FSECB(1),MJDSB(1)
      DIMENSION PARML0(3,1),PARMV0(1),PARMVC(1)
      DIMENSION RSCRAT(120)
!
      DATA MSCR/60/
      DATA C1/1.0D0/,C0/0.0D0/,C1D6/1.0D6/
!
!***********************************************************************
! START OF EXECUTABLA CODE *********************************************
!***********************************************************************
!
!
! COMPUTE START AND END LOCATIONS FOR ARC AND GLOBAL INFORMATION
!
      IARCB =IPVAL0(IXARC)
      IARCE =IARCB +NPVAL0(IXARC)-1
      IGLBB =IPVAL0(IXGLBL)
      IGLBE =IGLBB+NPVAL0(IXGLBL)-1
      NWORDS=NPVAL0(IXARC)+NPVAL0(IXGLBL)
      WRITE(IOUT6,80200) PFNUMB
!
! OUTPUT DATE AND TIME INFORMATION
!
! TDF DATE/TIME
      ITDFDT=TDFRTM/C1D6
      ITDFTM=MOD(TDFRTM,C1D6)
! IIS DATE/TIME
      IISDT =G2SRTM/C1D6
      IISTM =MOD(G2SRTM,C1D6)
! ARC REFERENCE - CONVERT TIME FROM MJDS IN E.T. TO YMD IN UTC
      CALL UTCET(.FALSE.,1,MJDSRF,FSECRF,FSEC(1),ETUTC)
      CALL YMDHMS(MJDSRF,FSEC(1),IREFDT,IREFTM,REFSEC,1)
      WRITE(IOUT6,80210) ITDFDT,ITDFTM,IISDT,IISTM,IREFDT,IREFTM,REFSEC
      DO 200 ISATNO=1,NSATA
! CONVERT EPOCH TIME FROM MJDS IN E.T. TO YMD IN UTC
      CALL UTCET(.FALSE.,1,MJDSB(ISATNO),FSECB(ISATNO),FSEC(1),ETUTC)
      CALL YMDHMS(MJDSB(ISATNO),FSEC(1),IEPYMD,IEPHM,EPSEC,1)
      WRITE(IOUT6,80212) ISATNO,IEPYMD,IEPHM,EPSEC
  200 END DO
      WRITE(IOUT6,80215)
!
! OUTPUT E-MATRIX HEADER RECORD
!
      NLEN=30
      CALL PDFCHK(NLEN)
      CALL EMTHDR(IUNPFI,RSCRAT,.TRUE.,0.D0)
!
! OUTPUT E-MATRIX PARAMETER GROUP IDENTIFIER RECORDS
!
      MSCR2=2*MSCR
      CALL PDFCHK(MSCR2)
      CALL EMTGRP(IUNPFI,RSCRAT,RSCRAT(MSCR+1),MSCR)
!
! OUTPUT E-MATRIX LABELS
!
      NLBLS =NWORDS*3
      XNLBLS=DBLE(NLBLS)
      CALL PDFCHK(NLBLS)
      WRITE(IUNPFI) XNLBLS,                                             &
     &(PARML0(1,J1),J1=IARCB,IARCE),(PARML0(1,K1),K1=IGLBB,IGLBE),      &
     &(PARML0(2,J2),J2=IARCB,IARCE),(PARML0(2,K2),K2=IGLBB,IGLBE),      &
     &(PARML0(3,J3),J3=IARCB,IARCE),(PARML0(3,K3),K3=IGLBB,IGLBE)
!
! OUTPUT CURRENT VALUES FOR PARAMETERS
!
      WORDS =DBLE(NWORDS)
      CALL PDFCHK(NWORDS)
      WRITE(IUNPFI) WORDS,                                              &
     &     (PARMVC(J1),J1=IARCB,IARCE),(PARMVC(K1),K1=IGLBB,IGLBE)
!
! OUTPUT A PRIORI VALUES
!
      CALL PDFCHK(NWORDS)
      WRITE(IUNPFI) WORDS,                                              &
     &(PARMV0(J1),J1=IARCB,IARCE),(PARMV0(K1),K1=IGLBB,IGLBE)
      RETURN
80200 FORMAT('0',4X,33('*')/5X,'PARTIAL FILE NO.',F16.0/5X,33('*')/1X )
80210 FORMAT(29X,       'YYYYMMDD HHMMSS.SSSSSSS'/                      &
     &  5X, 'TDF RUN DATE/TIME ',6X,I8,1X,I6/                           &
     &  5X, 'IIS RUN DATE/TIME ',6X,I8,1X,I6/                           &
     &  5X, 'ARC REFERENCE DATE',6X,I8,1X,I6,1x,F10.7/1X )
80212 FORMAT(5X, 'SAT',I2,' EPOCH DATE/TIME   ',I8,1X,I6,1x,F10.7)
80215 FORMAT('0'/1X )
      END
