!$PDXSM
      SUBROUTINE PDXSM( MJDSN, FSECN, FSECM, XTN, XSM, VTN, VSM,        &
     &   RNM, RRNM, URNM, PRRPNM, MINTPL, S, RELV, COSTHG, SINTHG,      &
     &   INDSAT, SIGNL, NM, LIGHT, LRANGE, LSKIP1, IEXIT, LTDRSS,       &
     &   GRELT1, DELCTN, PSTAT, RSUNST, SCRTM, XSTR, ISATID,            &
     &   AA, II, LL)
!********1*********2*********3*********4*********5*********6*********7**
! PDXSM            89/06/12            0000.0    PGMR - JJM
!
! FUNCTION: COMPUTE THE SATELLITE POSITION FOR THE TRACKED
!           SATELLITES FOR THE MARINER AND VIKING DATA. THIS
!           SUBROUTINE IS A CUT-DOWN VERSION OF THE MTSTST
!           SUBROUTINE. THE MAJOR MODIFICATION WAS TO REMOVE
!           CHANGES TO THE TRACKER POSITIONS, XTN, WHICH ARE
!           PROVIDED IN INERTIAL COORDINATES ON A DATA FILE.
!
!           COMPUTE RANGES AND/OR RANGE RATES WHICH FOLLOW
!           THE PATTERN:
!
!           Ti-->Sj
!
!           COMPUTATIONS START AT THE FINAL RECEIVED TIME
!           MJDSn+FSECn AND PROCEED BACKWARDS UNTIL THE MODEL
!           IS COMPLETE. IF THE "LIGHT" SWITCH IS .FALSE.
!           ITERATIVE SOLUTIONS FOR THE LIGHT TIME ARE
!           PERFORMED. OTHERWISE, THE MEASUREMENT EVENT TIMES
!           ARE CONSIDERED TO BE KNOWN.
!           THE SET OF RANGES AND RANGE RATES WHICH FALL INTO
!           THIS PATTERN INCLUDE TYPES AS FOLLOWS:
!
!           TYPES  PATTERN
!           _____  ______________________
!
!           41/42                 S1-->T1
!
!           THE IEXIT ARGUMENT IS USED TO DISCRIMINATE
!           BETWEEN SUB-PATTERNS
!
!           THE LRANGE SWITCH IS USED TO DISCRIMINATE
!           BETWEEN RANGES AND RANGE RATES
!
!
!  I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSN    I    S    MODIFIED JULIAN DAY SECONDS OF THE FINAL
!                      RECEIVED TIME OF THE FIRST OBSERVATION IN THE
!                      BLOCK
!   FSECN    I    A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH TRACKING STATION Tn
!   FSECM   I/O   A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH SATELLITE Sm
!   XTN      O    A    TRUE OF DATE INERT. COORD. OF TRACKING STA. Tn
!   XSM      O    A    TRUE OF DATE INERT. COORD. OF SATELLITE Sm
!   VTN      O    A    TRUE OF DATE INERT. VEL. OF TRACKING STA. Tn
!   VSM      O    A    TRUE OF DATE INERT. VEL. OF SATELLITE Sm
!   RNM      O    A    SLANT RANGE FROM Tn TO Sm
!   RRNM     O    A    RANGE RATE BETWEEN Tn AND Sm
!   URNM     O    A    UNIT VECTOR FROM Tn TO Sm
!   PRRPNM   O    A    PARTL. OF RNG. RATE W.R.T. Tn-->Sm VECTOR
!   MINTPL   I    S    MAXIMUM NUMBER OF INTERPOLATION INTERVALS
!   S        I    A    INTERPOLATION FRACTIONS
!   RELV     O    A    VELOCITY OF SATELLITE W.R.T. TRACKING STATION
!   COSTHG   O    A    COSINES OF RIGHT ASCENSION OF GREENWICH
!   SINTHG   O    A    SINES  OF RIGHT ASCENSION OF GREENWICH
!   INDSAT   I    A
!   SIGNL    I    S    SIGN OF THE LIGHT TIME (+1. OR -1.)
!   NM       I    S    NUMBER OF MEASUREMENTS IN THE CURRENT DATA BLOCK
!   LIGHT    I    S    .TRUE. IF LIGHT TIMES HAVE BEEN DETERMINED
!   LRANGE   I    S    .FALSE. WHEN RANGE RATES TO BE COMPUTED
!   LSKIP1   I    S
!   IEXIT    I    S    NUMBER OF LINKS IN MEASUREMENT
!   LTDRSS   I    S
!   GRELT1   O    A    GENERAL REL LIGHT TIME CORRECTION FOR  THE LINK
!   DELCTN   O    A    DELTA COORDINATE TIME- ET
!   PSTAT    O    A    SPACE TO HOLD PLANET POSITIONS
!   RSUNST   O    A    DISTANCE BETWEEN SATELLITE AND SUN
!   SCRTM   I/O   A    SCRATCH SPACE
!   XSTR     I    A    RECEIVING STATION OFFSET W.R.T. EARTH CENTER
!                      IN THE TRUE OF REFERENCE BARYCENTRIC FRAME
!   XSTT     I    A    TRANSMITTING STATION OFFSET W.R.T. EARTH CENTER
!                      IN THE TRUE OF REFERENCE BARYCENTRIC FRAME
!   AA      I/O   A    FLOATING POINT LABEL
!   II      I/O   A    INTEGER LABEL
!   LL      I/O   A    LOGICAL LABEL
!
! COMMENTS:      1) ONLY USED FOR MARINER/VIKING R.A.  AND DEC MEAS
!
! REFERENCES:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CHCOEF/ COEFM(3,15),COEFJ(3,15),COEFSA(3,15),COEFS(3,15),  &
     &               COEFEM(3,15),COEFMO(3,15),COEF(3,15)
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LOLOAD/LOLMD,LOLAJ,L2FOLT,LAPLOD
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/OCCLTL/LOCCLT(200),LMSHD(200)
      COMMON/OLDADJ/NPV0OL(3,3),JPV0OL(3,3),NYZ0OL(3,3),JYZ0OL(3,3),    &
     &              NEO0OL(3,3),JEO0OL(3,3)
      COMMON/POLESW/LDNPOL,NXPOLS
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      COMMON/VMATFL/LVMTF,LVMTFO
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
!
      DIMENSION FSECN(NM), FSECM(NM), XTN(MINTIM,3), XSM(MINTIM,3),     &
     &   VTN(MINTIM,3), VSM(MINTIM,3), RNM(NM), RRNM(NM),               &
     &   URNM(NM,3,2), PRRPNM(NM,3),                                    &
     &   S(NM), RELV(NM,3), COSTHG(NM,4), SINTHG(NM,4), INDSAT(3),      &
     &   GRELT1(NM), DELCTN(NM), PSTAT(NM,6), RSUNST(NM),               &
     &   AA(1), II(1), LL(1),                                           &
     &   SCRTM(NM,68), XSTR(MINTIM,3)
!
!
      DATA J1,J2P,J3,J4/1,2,3,4/
      DATA TWO/2.0D0/
!
!********1*********2*********3*********4*********5*********6*********7**
! START OF EXECUTABLE CODE
!********1*********2*********3*********4*********5*********6*********7**
!
      LSIMX=LSIMDT
      IF(ICBDGM.EQ.ITBDGM) LSIMX=.FALSE.
      KTRJX=KVTKP+3*MINTIM
      KTRJV=KTRJX+3*MINTIM
      IF(LTDRSS) GO TO 2900
      IF(LSKIP1) GO TO 2000
!
!
!***********************************************************************
!     ....INPUT XTN IN T.O.R. MARS EQUATOR AND  EQUINOX
!***********************************************************************
!
!
!***** INERTIAL TRACKING STATION #n POSITIONS NOW COMPUTED *************
!
! IF TRANSIT TIME CORRECTIONS ARE NOT REQUIRED SKIP TO 2000
!
      IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
      ENDIF

      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),INDSAT(J1) ,          &
     &   KNSTEPS,NEQNI,II(KSGMNT-1+IRET),                               &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),IRET,MJDSN,FSECM(1),       &
     &   FSECM(NM),NM,AA,II)
!
! SAVE STATION OFFSETS(IN PLANET CENTERED COORDINATES)
      MIN3 = MINTIM*3
      IF (ITBDGM .NE. ICBDGM) THEN
         DO 1050 I=1,3
            DO 1050 J=1,MINTIM
               XSTR(J,I)=XTN(J,I)
 1050    CONTINUE
      ENDIF
!
      IF(LIGHT) GO TO 2000
!
!***** START HERE TO COMPUTE LINK #1 TRANSIT TIMES TO SATELLITE ********
!
! INITIALIZE SATELLITE Sm TIMES TO EQUAL STATION Tn TIMES
      DO 1000 N=1,NM
      FSECM(N)=FSECN(N)
 1000 END DO
!
! ITERATIVELY COMPUTE SATELLITE TIMES
      CALL LITEUP(XTN,XSM,AA(KXSMPC),                                   &
     &                    RNM,URNM,URNM(1,2,1),URNM(1,3,1),S,MJDSN,     &
     &         FSECN,FSECM,SIGNL,DELCTN,RSUNST,GRELT1,PSTAT,NM,         &
     &         SCRTM,AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),           &
     &         ISATID,AA,II,LL,.FALSE.)
!
!***** TRANSIT TIMES FOR LINK #1 COMPUTED ******************************
!
 2000 CONTINUE
!
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF

!
! OBTAIN SATELLITE POSITIONS AT CORRECT SATELLITE TIMES
!
      CALL ORBIT(MJDSN,FSECM,AA(KS),NM,II(KINDH),II(KNMH),II(KMJDSC),   &
     &   AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),II(KIPXPF),         &
     &   II(KIVSAT),1,II(KNMAX),II(KNTOLD),XSM,AA(KPXPFM),              &
     &   LNADJ,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),                &
     &   AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),LL(KSETDN),            &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)

      KPXPFJ=KPXPFM+II(KIPXPF+1)-II(KIPXPF)
!
      IF( (LOBORB.OR.(LPARFI.AND..NOT.LRORR)) ) THEN
!
! GET POS & VEL IN TRUE OF DATE SYSTEM
         CALL SATUPD(MJDSN,FSECM,XSM,AA(KTRJX),AA,NM,MINTIM,.TRUE.,     &
     &              .FALSE.,II,0,1)
         CALL SATUPD(MJDSN,FSECM,VSM,AA(KTRJV),AA,NM,MINTIM,.FALSE.,    &
     &              .FALSE.,II,0,1)
! COMPUTE RIGHT ASCENSION OF GREENWICH ACROSS ENTIRE BLOCK OF DATA
         CALL ROTXTR(MJDSN,FSECM,.FALSE.,AA(KEQN),AA(KSRTCH),           &
     &      AA(KTHETG),COSTHG(1,J2P),SINTHG(1,J2P),NM,AA,AA(KACOSW),    &
     &      AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),AA(KBCOFW),II,1)
! COMPUTE S/C HEIGHT ABOVE ELLIPSOID AND SUB-SATELLITE LAT & LON
         CALL SUBTRK(AA(KTRJX),AA(KTHETG),AA(KXY2),AA(KZT),AA(KRT),     &
     &      AA(KSATLT),AA(KSATLN),AA(KSATH),NM)
         IF( LOBORB ) THEN
! PRINT TRAJECTORY
            CALL TRAJCT(AA(KA1UT),MJDSN,FSECM,AA(KTRJX),AA(KTRJV),      &
     &        AA(KSATLT),AA(KSATLN),AA(KSATH),II(KINDH),II(KNMH),AA(KS),&
     &   AA(KCIP  ),NM,INDSAT(J1),AA,AA(KCOSTH),AA(KSINTH),AA(KDPSR),   &
     &   AA(KXPUT),AA(KYPUT),II)
         ENDIF
      ENDIF
!
      IF(LVMTFO) CALL VMATO(AA(KA1UT),MJDSN,FSECM,XSM,VSM,AA(KPXPFM),   &
     &   II(KINDH),II(KNMH),AA(KS),AA(KCIP  ),NM,INDSAT(J1),II)
!
!
!
      IF(LSKIP1) GO TO 2750
!
!***** START HERE TO COMPUTE LINK #1 MEASUREMENT ***********************
!
! COMPUTE RANGES AND UNIT VECTORS FROM STATION TO SATELLITE
!
      CALL RANGE(XSM,XTN,URNM(1,1,2),RNM,S,NM,.TRUE.)
      IF(LSIMX) CALL OCCULT(MJDSN,FSECM,NM,AA(KAESHD),XSJ,XSM,          &
     &                       URNM(1,1,2),RSUNST,LOCCLT,LMSHD,.TRUE.,    &
     &                       PSTAT,AA,II)
!
! GET TOD UNIT VECTOR AT STATION TIME
!
      CALL TDORTR(MJDSN,FSECN,URNM(1,1,2),URNM(1,1,1),AA,NM,NM,.TRUE.,  &
     &            .FALSE.,II)
!
! IF RANGE RATES NOT REQUIRED, SKIP TO 2500
      IF(LRANGE) GO TO 2500
! COMPUTES RANGE RATES AND PARTIALS OF RANGE RATES W.R.T. SAT. POSITIONS
      CALL RNGRAT(VSM,VTN,URNM,RNM,RRNM,RELV,PRRPNM,NM,.TRUE.)
 2500 CONTINUE
!
!***** LINK #1 MEASUREMENT COMPUTED ************************************
!
! IF ONE-WAY SATELLITE TO STATION MEAS., COMPUTATIONS ARE COMPLETE.
!    PATTERN: S1-->T1
      IF(IEXIT.EQ.1.AND..NOT.LLOCRI) RETURN
!
 2750 CONTINUE
 2900 CONTINUE
      RETURN
      END
