!$PFTPR3
      SUBROUTINE PFTPR3(MAXD,ND2AC,ND1,NU,TIME,XX,YY,ZZ,ACOEF,ANGV,     &
     &                  RLAND,ACOEF3,SLOPE)
!********1*********2*********3*********4*********5*********6*********7**
! PFTPR             00/00/00            0000.0    PGMR -DAVE ROWLANDS
!
!
! FUNCTION: PROCESS DYNAMIC CROSSOVERS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!
!********1*********2*********3*********4*********5*********6*********7**
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      PARAMETER(MAXND1=21)
      DIMENSION TIME(NU),XX(NU),YY(NU),ZZ(NU)
      DIMENSION ANGV(NU),RLAND(NU),SLOPE(NU)
      DIMENSION ACOEF(MAXD,ND2AC,3)
      DIMENSION ACOEF3(MAXD,4)
      DIMENSION XPOS(3)
!
!  231=21*22/2=MAXND1*(MAXND1+1)/2
!
      DIMENSION ATA(231),SQMAT(MAXND1,MAXND1)
      DIMENSION ATL(MAXND1,7),SCR(MAXND1)
      DIMENSION SCR2(MAXND1),SCR3(MAXND1),SCR4(MAXND1)
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      NU1=NU+1
      IF(ND1.GT.MAXND1) THEN
         NDP=ND1-1
         MDP=MAXND1-1
         WRITE(6,6000)
         WRITE(6,6000)
         WRITE(6,6001)
         WRITE(6,6002) NDP
         WRITE(6,6003) MDP
         WRITE(6,6000)
         STOP
      ENDIF
!
      NZ=(ND1*(ND1+1))/2
      CALL CLEARA(ATA,NZ)
      NZ=ND1
      CALL CLEARA(ATL,NZ)
      CALL CLEARA(ATL(1,2),NZ)
      CALL CLEARA(ATL(1,3),NZ)
      CALL CLEARA(ATL(1,4),NZ)
      CALL CLEARA(ATL(1,5),NZ)
      CALL CLEARA(ATL(1,6),NZ)
      CALL CLEARA(ATL(1,7),NZ)
      NZ=4*MAXD
      CALL CLEARA(ACOEF3,NZ)
      NZ=3*MAXD*ND2AC
      CALL CLEARA(ACOEF,NZ)
      SCR(1)=1.D0
!
      DL=TIME(NU)-TIME(1)
!
      DO 300 ITM=1,NU
!
!  SLOPE COMPUTATIONS
      IPT3=ITM+1
      IF(IPT3.GT.NU) IPT3=NU
      IPT1=ITM-1
      IF(IPT1.LT.1) IPT1=1
      PR1=SQRT(XX(IPT1)*XX(IPT1)+YY(IPT1)*YY(IPT1)+ZZ(IPT1)*ZZ(IPT1))
      PR3=SQRT(XX(IPT3)*XX(IPT3)+YY(IPT3)*YY(IPT3)+ZZ(IPT3)*ZZ(IPT3))
      DSX=XX(IPT3)-XX(IPT1)
      DSY=YY(IPT3)-YY(IPT1)
      DSZ=ZZ(IPT3)-ZZ(IPT1)
      DSQ=SQRT(DSX*DSX+DSY*DSY+DSZ*DSZ)
      SLOPE(ITM)=ABS(PR3-PR1)/DSQ
!
      DT=-1.D0+2.D0*(TIME(ITM)-TIME(1))/DL
      SCR(1)=1.D0
      CALL CHEBPL(SCR,SCR,DT,ND1,.FALSE.)
!
      DO 50 I=1,ND1
      ATL(I,1)=ATL(I,1)+XX(ITM)*SCR(I)
      ATL(I,2)=ATL(I,2)+YY(ITM)*SCR(I)
      ATL(I,3)=ATL(I,3)+ZZ(ITM)*SCR(I)
   50 END DO
      IN=0
      NL=ND1
      DO 200 I=1,ND1
      IIN=IN-(I-1)
      DO 100 J=I,ND1
      ATA(IIN+J)=ATA(IIN+J)+SCR(I)*SCR(J)
  100 END DO
      IN=IN+NL
      NL=NL-1
  200 END DO
  300 END DO
      CALL DSINV(ATA,ND1,ND1,SCR)
      IN=0
      NL=ND1
      DO 500 I=1,ND1
      IIN=IN-(I-1)
      DO 400 J=I,ND1
      SQMAT(I,J)=ATA(IIN+J)
      SQMAT(J,I)=SQMAT(I,J)
  400 END DO
      IN=IN+NL
      NL=NL-1
  500 END DO
      DO 800 K=1,NU1
      IF(K.EQ.1) THEN
        FACT=0.D0
        DO IQ=1,ND1
          SCR4(IQ)=0.D0
        ENDDO
      ELSE
        FACT=1.D0
        SCR4(1)=1.D0
        DT=-1.D0+2.D0*(TIME(K-1)-TIME(1))/DL
        CALL CHEBPL(SCR4,SCR4,DT,ND1,.FALSE.)
      ENDIF
      DO 550 I=1,ND1
      SCR(I)=ATL(I,1)+FACT*SCR4(I)
      SCR2(I)=ATL(I,2)+FACT*SCR4(I)
      SCR3(I)=ATL(I,3)+FACT*SCR4(I)
  550 END DO
      DO 700 I=1,ND1
      DO 600 J=1,ND1
      ACOEF(I,K,1)=ACOEF(I,K,1)+SQMAT(I,J)*SCR(J)
      ACOEF(I,K,2)=ACOEF(I,K,2)+SQMAT(I,J)*SCR2(J)
      ACOEF(I,K,3)=ACOEF(I,K,3)+SQMAT(I,J)*SCR3(J)
  600 END DO
  700 END DO
  800 END DO
      DO 900 K=2,NU1
      DO 850 I=1,ND1
      ACOEF(I,K,1)=(ACOEF(I,K,1)-ACOEF(I,1,1))/1.D0
      ACOEF(I,K,2)=(ACOEF(I,K,2)-ACOEF(I,1,2))/1.D0
      ACOEF(I,K,3)=(ACOEF(I,K,3)-ACOEF(I,1,3))/1.D0
  850 END DO
  900 END DO
!
      DO 1300 ITM=1,NU
!
      IPT3=ITM+1
      IF(IPT3.GT.NU) IPT3=NU
      IPT1=ITM-1
      IF(IPT1.LT.1) IPT1=1
      RMS=0.D0
      NPT=0
!
      DO 1020 IPT=IPT1,IPT3
      DT=-1.D0+2.D0*(TIME(IPT)-TIME(1))/DL
      SCR(1)=1.D0
      CALL CHEBPL(SCR,SCR,DT,ND1,.FALSE.)
!
      XF=XX(IPT)
      YF=YY(IPT)
      ZF=ZZ(IPT)
      DO 1010 I=1,ND1
      XF=XF-SCR(I)*ACOEF(I,1,1)
      YF=YF-SCR(I)*ACOEF(I,1,2)
      ZF=ZF-SCR(I)*ACOEF(I,1,3)
 1010 CONTINUE
!
      RMS=RMS+XF*XF+YF*YF+ZF*ZF
      NPT=NPT+1
 1020 CONTINUE
      RMS=SQRT(RMS/DBLE(NPT))
!
      DT=-1.D0+2.D0*(TIME(ITM)-TIME(1))/DL
      SCR(1)=1.D0
      CALL CHEBPL(SCR,SCR,DT,ND1,.FALSE.)
!
      DO 1050 I=1,ND1
      ATL(I,4)=ATL(I,4)+ANGV(ITM)*SCR(I)
      ATL(I,5)=ATL(I,5)+RMS*SCR(I)
      ATL(I,6)=ATL(I,6)+RLAND(ITM)*SCR(I)
      ATL(I,7)=ATL(I,7)+SLOPE(ITM)*SCR(I)
 1050 CONTINUE
!
!
 1300 CONTINUE
      DO 1600 I=1,ND1
      DO 1500 J=1,ND1
      ACOEF3(I,1)=ACOEF3(I,1)+SQMAT(I,J)*ATL(J,4)
      ACOEF3(I,2)=ACOEF3(I,2)+SQMAT(I,J)*ATL(J,5)
      ACOEF3(I,3)=ACOEF3(I,3)+SQMAT(I,J)*ATL(J,6)
      ACOEF3(I,4)=ACOEF3(I,4)+SQMAT(I,J)*ATL(J,7)
 1500 CONTINUE
 1600 CONTINUE
!
      RETURN
!
 6000 FORMAT(' ')
 6001 FORMAT(' EXECUTION TERMINATING IN SUBROUTINE PFTPAR')
 6002 FORMAT(' DEGREE OF POLYNIMIAL FIT REQUESTED:',I3)
 6003 FORMAT(' LARGER THAN MAX ALLOWABLE:',I3)
      END
