!$PLANPT
      SUBROUTINE PLANPT(MJDSEC,FSEC,LVELP,LBARYC,CBODY,TBODY)
!********1*********2*********3*********4*********5*********6*********7**
! PLANPT           92/07/17            9203.0    LUCIA TSAOUSSI
!
! *** MODIFIED COPY OF PLANPO               PGMR - D. ROWLANDS
!
! FUNCTION:  CALCULATE MEAN OF EPHEM. EPOCH PLANET STATE AT TIME
!            MJDSEC,FSEC AND TRUE OF REFERENCE
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    EPHEMERIS SECONDS SINCE GEODYN REFERENCE TIME
!   FSEC     I    S    FRACTIONAL REMAINING SECONDS FROM MJDSEC
!   LVELP    I    S    .TRUE. IF VELOCITIES ARE REQUESTED
!   LBARYC   I    S    .TRUE. IF OUTPUT DESIRED IN SS BARYCENTRIC.
!                      IF SO, THE EARTH -MOON BARYCENTER WILL BE
!                      OUTPUT IN SLOT 11 OF BDSTAT
!                      .FALSE. IF OUTPUT DESIRED IN CENTER OF INTEGRATIO
!                      IF SO, THE EARTH'S MOON  WILL BE OUTPUT IN SLOT 1
!                      OF BDSTAT
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CREFMT/REFMT(9)
      COMMON/CEPHEP/FSCEPC(1),EPHBFC(1016),                             &
     &              FSCEPT(1),EPHBFT(1016),                             &
     &              SEPBFC(75),SEPBFT(75),XEPHEP
      COMMON/EPHMPT/NTOT,NTOTS,NNPDPR,NUTORD,IBODDG(8),IGRPDG(4),       &
     &              NENPD,INRCD(2),KPLAN(11),NINEP,NEPHMR,NEPHEM,       &
     &              IBHINT,NINTBH,NXEPHP
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      DIMENSION FNSEC(4),IGRPPT(4),DT(4),CHB(15),CHBV(15)
      DIMENSION BMA(4),ITEST(4),CB(6),TB(6)
      DIMENSION CBODY(6),TBODY(6),SUNRF(6),BDSTAT(7,11)
      DIMENSION IMAP(11)
      DATA ZERO/0.D0/,ONE/1.D0/,TWO/2.D0/
      DATA FNSEC/2764800.D0,1382400.D0,691200.D0,345600.D0/
      DATA CHB(1)/1.D0/,CHBV(1)/0.D0/,CHBV(2)/1.D0/
      DATA ITEST/1,2,4,8/
      DATA IMAP/2,4,5,6,7,8,9,11,3,1,10/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      TTEST=MJDSEC+FSEC-FSCEPT(1)
      ITOT=0
      IF(TTEST.LE.FNSEC(1)) GO TO 10
      ITOT=NTOT
      TTEST=TTEST-FNSEC(1)
   10 CONTINUE
!   MAP MJDSEC,FSEC INTO INTERVAL  -1,1  FOR EACH PERIOD GROUP
!   FIGURE POINTER WHITHIN 32 DAY RECORD FOR EACH PERIOD GROUP
      DO 100 I=1,4
      IGRPPT(I)=TTEST/FNSEC(I)
      IF(IGRPPT(I).GE.ITEST(I)) IGRPPT(I)=ITEST(I)-1
      FSECC=FSCEPT(1+ITOT)+IGRPPT(I)*FNSEC(I)
      DT(I)=((MJDSEC-FSECC)+FSEC)/FNSEC(I)
      DT(I)=DT(I)*TWO-ONE
      BMA(I)=TWO/FNSEC(I)
  100 END DO
      DO 250 IGROUP=1,4
      CALL CHEBPL(CHB,CHBV,DT(IGROUP),15,LVELP)
      DO 200 I=1,11
      IF(ICHBOG(2,IMAP(I)).NE.IGROUP) GO TO 200
      IB=ICHBOG(1,IMAP(I))
      IBPT=KPLAN(I)+3*IGRPPT(IGROUP)*IB+ITOT
      BDSTAT(1,I)=ZERO
      BDSTAT(2,I)=ZERO
      BDSTAT(3,I)=ZERO
      DO 120 K=1,IB
      IBK2=IB+1-K
      IBK11=IBPT+IBK2-1
      IBK12=(IBPT+IB)+IBK2-1
      IBK13=(IBPT+2*IB)+IBK2-1
      BDSTAT(1,I)=BDSTAT(1,I)+EPHBFT(IBK11)*CHB(IBK2)
      BDSTAT(2,I)=BDSTAT(2,I)+EPHBFT(IBK12)*CHB(IBK2)
      BDSTAT(3,I)=BDSTAT(3,I)+EPHBFT(IBK13)*CHB(IBK2)
  120 END DO
      IF(.NOT.LVELP) GO TO 200
      IBM1=IB-1
      BDSTAT(4,I)=ZERO
      BDSTAT(5,I)=ZERO
      BDSTAT(6,I)=ZERO
      DO 140 K=1,IBM1
      IBK2=IB+1-K
      IBK11=IBPT+IBK2-1
      IBK12=(IBPT+IB)+IBK2-1
      IBK13=(IBPT+2*IB)+IBK2-1
      BDSTAT(4,I)=BDSTAT(4,I)+EPHBFT(IBK11)*CHBV(IBK2)
      BDSTAT(5,I)=BDSTAT(5,I)+EPHBFT(IBK12)*CHBV(IBK2)
      BDSTAT(6,I)=BDSTAT(6,I)+EPHBFT(IBK13)*CHBV(IBK2)
  140 END DO
      BDSTAT(4,I)=BDSTAT(4,I)*BMA(IGROUP)
      BDSTAT(5,I)=BDSTAT(5,I)*BMA(IGROUP)
      BDSTAT(6,I)=BDSTAT(6,I)*BMA(IGROUP)
  200 END DO
  250 END DO
!
      NUL=3
      IF(LVELP) NUL=6
!
!   NOW GET EARTH & EARTH'S MOON & EARTH-MOON BARYCENTER
      DO 600 I=1,NUL
      CB(I)=-EMFACT*BDSTAT(I,11)+BDSTAT(I,9)
  600 END DO
      DO 610 I=1,NUL
      TB(I)=BDSTAT(I,11)+CB(I)
      BDSTAT(I,11)=BDSTAT(I,9)
      BDSTAT(I,9)=CB(I)
  610 END DO
      IF(.NOT.LBARYC) GO TO 900
! TRACKING BODY AND CENTER OF INTEGRATION TRUE OF REF COORDINATES
! DESIRED THROUGH COMMON LBARYC IN ADDITION TO MEAN OF 50 (2000)
! COORDINATES THROUGH CBDSTA
      IXPCI=IPLNIN(ICBDGM)
      IXPTK=IPLNIN(ITBDGM)
      IF(LMOON) THEN
      DO 615 I=1,NUL
      CB(I)=TB(I)
  615 END DO
      ELSE
      DO 620 I=1,NUL
      CB(I)=BDSTAT(I,IXPCI)
  620 END DO
      ENDIF
      IF(ITBDGM.EQ.4) GOTO 700
      DO 670 I=1,NUL
      TB(I)=BDSTAT(I,IXPTK)
  670 END DO
  700 CONTINUE
!     ROTATE TRACKING BODY CENTER OF INTEGRATION AND SUN INTO TRUE OF RE
      DO 800 I=1,3
      IPT1=3*I-2
      IPT2=IPT1+1
      IPT3=IPT2+1
      CBODY(I)=REFMT(IPT1)*CB(1)+REFMT(IPT2)*CB(2)+REFMT(IPT3)*CB(3)
      TBODY(I)=REFMT(IPT1)*TB(1)+REFMT(IPT2)*TB(2)+REFMT(IPT3)*TB(3)
      SUNRF(I)=REFMT(IPT1)*BDSTAT(1,8)+REFMT(IPT2)*BDSTAT(2,8)          &
     &        +REFMT(IPT3)*BDSTAT(3,8)
      IF(NUL.LE.3) GO TO 800
      CBODY(I+3)=REFMT(IPT1)*CB(4)+REFMT(IPT2)*CB(5)+REFMT(IPT3)*CB(6)
      TBODY(I+3)=REFMT(IPT1)*TB(4)+REFMT(IPT2)*TB(5)+REFMT(IPT3)*TB(6)
      SUNRF(I+3)=REFMT(IPT1)*BDSTAT(4,8)+REFMT(IPT2)*BDSTAT(5,8)        &
     &        +REFMT(IPT3)*BDSTAT(6,8)
  800 END DO
!     WRITE(6,*) 'PLANP2: CBODY  ', CBODY
!     WRITE(6,*) 'PLANP2: CENT BD: CBDSTA ', (BDSTAT(IP,2),IP=1,6)
!     WRITE(6,*) 'PLANP2: TBODY  ', TBODY
!     WRITE(6,*) 'PLANP2: TRACK BD: CBDSTA ', (BDSTAT(IP,9),IP=1,6)
      RETURN
  900 CONTINUE
!
!     GET EVERYTHING IN TERMS OF CENTER OF INTEGRATION
! FIRST GET MOON NOT EARTH MOON INTO PROPER LOCATION
      DO 925 I=1,NUL
      BDSTAT(I,11)=TB(I)
  925 END DO
      IXPCI=IPLNIN(ICBDGM)
      DO 950 I=1,NUL
      CB(I)=BDSTAT(I,IXPCI)
  950 END DO
!
      DO 1000 I=1,11
      DO 1000 J=1,NUL
      BDSTAT(J,I)=BDSTAT(J,I)-CB(J)
 1000 CONTINUE
!     WRITE(6,*) 'PLANP2: CBODY  ', CBODY
!     WRITE(6,*) 'PLANP2: CENT BD: CBDSTA ', (BDSTAT(IP,2),IP=1,6)
!     WRITE(6,*) 'PLANP2: TBODY  ', TBODY
!     WRITE(6,*) 'PLANP2: TRACK BD: CBDSTA ', (BDSTAT(IP,9),IP=1,6)
      RETURN
      END
