!$PLANPX
      SUBROUTINE PLANPX(MJDSEC,FSEC,BDSTAT,ISUPE,BUFFER,LVELP,AA,II)
!********1*********2*********3*********4*********5*********6*********7**
! PLANPX          99/07/26                      PGMR - D. PAVLIS
!
! FUNCTION:  COMPUTE BDSTAT FOR CELESTIAL BODIES IN THE SUPPLEMENTARY
!            PLANETARY EPHEMERIS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   BDSTAT   I/O  A    PLANET STATE VECTORS
!   ISUPE    I    A    SCHEDULING ARRAY FOR CELESTIAL BODIES
!   BUFFER   I    A    SUPPLEMENTARY EPHEMERIS BUFFER
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBDACC/BD_ACCEL(10,999)
      COMMON/CENACC/DGCEN,TCEN,BMACEN,CCHEBV(50),EPCEN(50,3),           &
     &              DGEAR,TEAR,BMAEAR,ECHEBV(50),EPEAR(50,3),           &
     &              DGMON,TMON,BMAMON,SCHEBV(50),EPMON(50,3)
      COMMON/CHCOFX/ COEFX(3,25),COEFXX(3,25,988),RLVAL(988)
      COMMON/CHCFFX/COEFFX1(3,25,11),COEFFXX(3,25,988),TIMBCHEB
      COMMON/EPHMX/FSECSE(10,2)
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/LDUAL/LASTSN,LSTSNX,LSTSNY
      COMMON/PLNETI/IPLNET(999),IPLNIN(999),MPLNGD(999),MPLNGO(999),   &
     &              IPLNZ(999),NXPLNI
      DIMENSION ISUPE(ICBODY,5),BUFFER(ICBODY,MAXDEG,2)
      DIMENSION CHB(25),CHBV(25),CHBA(25)
      DIMENSION BDSTAT(7,988)
      DIMENSION BUFQ(3,25,988)
      DIMENSION AA(1),II(1)
      EQUIVALENCE(BUFQ(1,1,1),COEFFXX(1,1,1))
      DATA CHB(1)/1.D0/,CHBV(1)/0.D0/,CHBV(2)/1.D0/
      DATA DAYSEC/86400.D0/
      DATA TWO/2.D0/,ONE/1.D0/
      DATA ZERO/0.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
      IKK=11
      IF(LASTSN) IKK=12

      CALL COFFFX(MJDSEC,FSEC,AA,II,ISUPE)
      FSECS1=TIMBCHEB
      TTEST=DBLE(MJDSEC)+FSEC-FSECS1
!
! FOR ALL CELESTIAL BODIES DO
      DO I=1,ICBODY
      IWHOLE=I+11
!
! FIND LENGTH OF VALIDITY
      ILOV=ISUPE(I,3)
!     RLOV=(ILOV/100)*DAYSEC
      RLOV=( DBLE(ILOV)/100.D0)*DAYSEC
      RLVAL(I)=RLOV
! FIND NUMBER OF GROUPS FOR THIS BODY
      IGRP=ISUPE(I,1)
! FSECSE MIGHT BE WRONG FOR THIS OBS
!!!     J=1
!!!      FSECS1=FSECSE(I,1)
!!!      TTEST=DBLE(MJDSEC)+FSEC-FSECSE(I,1)
!!!      IF(TTEST.GT.RLVAL(I)) THEN
!!!     WRITE(6,*)' CROSSING A BLOCK ',TTEST,MJDSEC,FSEC,FSECSE(I,1)
!!!      TTEST=DBLE(MJDSEC)+FSEC-FSECSE(I,2)
!!!      FSECS1=FSECSE(I,2)
!!!      J=2
!!!      ENDIF
! FIGURE OUT IN WHICH GROUP IS THE TIME MJDSEC FSEC
!   MAP MJDSEC,FSEC INTO INTERVAL  -1,1
      IGRPT=TTEST/RLOV

      IF(IGRPT.GE.ISUPE(I,1)) THEN
      WRITE(6,*)' ERROR IN PLANPX ',IGRPT
      STOP 16
      ENDIF
      FSECC=FSECS1+IGRPT*RLOV
      DT=((MJDSEC-FSECC)+FSEC)/RLOV
      DT=DT*TWO-ONE
      BMA=TWO/RLOV
!
      IF (LVELP) THEN
          ! ALSO GET ACCELERATIONS IF VELOCITIES ARE REQUESTED
          CALL CHEBPL2(CHB, CHBV, CHBA, DT, 25)
      ELSE
          CALL CHEBPL(CHB,CHBV,DT,25,LVELP)
      END IF
      BDSTAT(1,I)=ZERO
      BDSTAT(2,I)=ZERO
      BDSTAT(3,I)=ZERO
      IB=ISUPE(I,2)/3
      DO 120 K=1,IB
      IBK2=IB+1-K
      IBK11=1+IBK2-1
      IBK12=(1+IB)+IBK2-1
      IBK13=(1+2*IB)+IBK2-1
!      BDSTAT(1,I)=BDSTAT(1,I)+BUFFER(I,IBK11,J)*CHB(IBK2)
!      BDSTAT(2,I)=BDSTAT(2,I)+BUFFER(I,IBK12,J)*CHB(IBK2)
!      BDSTAT(3,I)=BDSTAT(3,I)+BUFFER(I,IBK13,J)*CHB(IBK2)
      BDSTAT(1,I)=BDSTAT(1,I)+BUFQ(1,IBK2,I)*CHB(IBK2)
      BDSTAT(2,I)=BDSTAT(2,I)+BUFQ(2,IBK2,I)*CHB(IBK2)
      BDSTAT(3,I)=BDSTAT(3,I)+BUFQ(3,IBK2,I)*CHB(IBK2)
  120 END DO
!DEP
!     BD_ACCEL(1:3,I+12) = BDSTAT(1:3,I)
      BD_ACCEL(1:3,I+IKK) = BDSTAT(1:3,I)
!!!!!!!!PRINT OUT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!DEP
!      WRITE(6,87652) I+12,BD_ACCEL(1:3,I+12)
!      WRITE(6,87652) I+IKK,BD_ACCEL(1:3,I+11)
87652    FORMAT("PLANPX1",I2,3D25.11)

      IF(LVELP.AND.IPLNIN(ICBDGM).EQ.IWHOLE) THEN
         TCEN=DT
         DGCEN=DBLE(IB)
         BMACEN=BMA
         DO 130 K=1,IB
         CCHEBV(K)=CHBV(K)
!         EPCEN(K,1)=BUFFER(I,IBK11-1+K,J)
!         EPCEN(K,2)=BUFFER(I,IBK12-1+K,J)
!         EPCEN(K,3)=BUFFER(I,IBK13-1+K,J)
         EPCEN(K,1)=BUFQ(1,K,I)
         EPCEN(K,2)=BUFQ(2,K,I)
         EPCEN(K,3)=BUFQ(3,K,I)
  130    CONTINUE
      ENDIF
      IF(.NOT.LVELP) GO TO 200
      IBM1=IB-1
      BDSTAT(4,I)=ZERO
      BDSTAT(5,I)=ZERO
      BDSTAT(6,I)=ZERO
!DEP
!     BD_ACCEL(7:9,I+12) = ZERO
      BD_ACCEL(7:9,I+IKK) = ZERO
      DO 140 K=1,IBM1
      IBK2=IB+1-K
      IBK11=1+IBK2-1
      IBK12=(1+IB)+IBK2-1
      IBK13=(1+2*IB)+IBK2-1
!      BDSTAT(4,I)=BDSTAT(4,I)+BUFFER(I,IBK11,J)*CHBV(IBK2)
!      BDSTAT(5,I)=BDSTAT(5,I)+BUFFER(I,IBK12,J)*CHBV(IBK2)
!      BDSTAT(6,I)=BDSTAT(6,I)+BUFFER(I,IBK13,J)*CHBV(IBK2)
      BDSTAT(4,I)=BDSTAT(4,I)+BUFQ(1,IBK2,I)*CHBV(IBK2)
      BDSTAT(5,I)=BDSTAT(5,I)+BUFQ(2,IBK2,I)*CHBV(IBK2)
      BDSTAT(6,I)=BDSTAT(6,I)+BUFQ(3,IBK2,I)*CHBV(IBK2)
!DEP
!     BD_ACCEL(7,I+12) = BD_ACCEL(7,I+12) + BUFQ(1,IBK2,I)*CHBA(IBK2)
!     BD_ACCEL(8,I+12) = BD_ACCEL(8,I+12) + BUFQ(2,IBK2,I)*CHBA(IBK2)
!     BD_ACCEL(9,I+12) = BD_ACCEL(9,I+12) + BUFQ(3,IBK2,I)*CHBA(IBK2)
      BD_ACCEL(7,I+IKK) = BD_ACCEL(7,I+IKK) + BUFQ(1,IBK2,I)*CHBA(IBK2)
      BD_ACCEL(8,I+IKK) = BD_ACCEL(8,I+IKK) + BUFQ(2,IBK2,I)*CHBA(IBK2)
      BD_ACCEL(9,I+IKK) = BD_ACCEL(9,I+IKK) + BUFQ(3,IBK2,I)*CHBA(IBK2)
  140 END DO
      BDSTAT(4,I)=BDSTAT(4,I)*BMA
      BDSTAT(5,I)=BDSTAT(5,I)*BMA
      BDSTAT(6,I)=BDSTAT(6,I)*BMA
!DEP
!     BD_ACCEL(4:6,I+12) = BDSTAT(4:6,I)
!     BD_ACCEL(7:9,I+12) = BD_ACCEL(7:9,I+12) * BMA**2
      BD_ACCEL(4:6,I+IKK) = BDSTAT(4:6,I)
      BD_ACCEL(7:9,I+IKK) = BD_ACCEL(7:9,I+IKK) * BMA**2
      ENDDO
  200 CONTINUE
!
      RETURN
      END
