!$PNCXN
      SUBROUTINE PNCXN(MINEP,LFLAG,LINIT,IDIM)
!********1*********2*********3*********4*********5*********6*********7**
! PNCXN            86/12/24            8701.0    PGMR - D. ROWLANDS
!
!  FUNCTION:  DETERMINE ELEMENTS OF PRECESION SINCE 1950.0
!             FOR A PLANET OTHER THAN EARTH (AT PRESENT ONLY MARS)
!             THIS IS DONE ONLY AT 12 HR INTERPOLATION ENDPOINT
!             TIMES. AT PRESENT THIS 12HR INFORMATION IS NOT USED -
!             BUT IT MAY BE USED LATER. IN ADDITION, DETERMINE THE
!             COEFFICIENTS OF THE LINEAR POLYNOMIALS NEEDED TO
!             CALCULATE THE ABOVE QUANTITIES AT OTHER TIMES. ALSO
!             FIGURES THE COEFFCIENTS OF THE LINEAR POLYNOMIAL USED
!             TO DESCRIBE THE ROTATION OF THE PLANET.THE TIME IN THIS
!             FORMULATION WILL BE REFERENCED TO THE FIRST 12HR INTERP
!             TIME.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MINEP    I    S    THE NUMBER OF 12HR TIMES NEEDED TO BE FILLED IN
!                      COMMON BLOCK DNUTAT
!   LFLAG    I    S    .FALSE. THE SUBROUTINE WILL OPERATE THE ORIGINAL
!                      .TRUE.  PLANOR PARAMETERS NEED TO BE SUBSTITUTED
!   LINIT    I    S    .TRUE. INITIALIZE PLANETARY CONSTANTS
!
!
! COMMENTS:  OUTPUT BY MEANS OF COMMON BLOCK DNUTAT
!
! INPUT-OUTPUT   THE ONLY INPUT ARGUMENT IS MINEP
!                THE OUTPUT IS THROUGH THE COMMON BLOCKS.
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/DNUTAT/RAPXTR(1),DCPXTR(1),DNUTXR(8),SMDNUT(30)
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/PRXCON/PRXCON(2,2,2)
      COMMON/ROTEL5/ALF050,ALFR50,DEC050,DECR50,W050,WR50,X1005,       &
     &               XA1005,THXTGC22S(3),XROTL5
      COMMON/THXTGC/THXTGC(3,2)
      DATA ONE/1.D0/,TWO/2.D0/,THREE/3.D0/,D100/8640000.D0/
      DATA NSDNUT/10/
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
         IF(.NOT.LFLAG) THEN
         IF(LINIT) THEN
! FIRST TIME
         THXTGC(1,1)=THXTGC22S(1)
         THXTGC(1,1)=MOD(THXTGC(1,1)+TWOPI,TWOPI)
         THXTGC(2,1)=THXTGC22S(2)
         THXTGC(3,1)=THXTGC22S(3)
         GO TO 50
       ENDIF
       ENDIF

!
      XTIME=MOD(FSDINP(1),D100)
      XTM100=FSDINP(1)-XTIME+ONE
      ITM100=XTM100/D100
      XTM100=DBLE(ITM100)
      XA100=XTM100*X1005
      XA100=MOD(XA100,TWOPI)
      XAREST=XTIME*WR50
      XAREST=MOD(XAREST,TWOPI)
      THXTGC(1,1)=XA100+XAREST+W050
      THXTGC(1,1)=MOD(THXTGC(1,1),TWOPI)
      THXTGC(2,1)=WR50
!
      DO 100 I=1,MINEP
      IPT=1+(I-1)*NSDNUT
      RAPXTR(IPT)=ALF050+FSDINP(I)*ALFR50
      DCPXTR(IPT)=DEC050+FSDINP(I)*DECR50
  100 END DO

   50 CONTINUE
!
      PRXCON(1,1,1)=ALF050
      PRXCON(2,1,1)=ALFR50
      PRXCON(1,2,1)=DEC050
      PRXCON(2,2,1)=DECR50
      RETURN
      END
