      SUBROUTINE PORPAL(AA,MJDSEC,FSEC,XEF,PXEPA,NU,NDIM1,NDIM2,IX,     &
     &                  LNPNM,II,LAVOID)
!********1*********2*********3*********4*********5*********6*********7**
! PORPAL             00/00/00            0000.0    PGMR -DAVE ROWLANDS
!
!
! FUNCTION: PROCESS PLANOR PARTIALS FOR DYNAMIC CROSSOVERS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!
!********1*********2*********3*********4*********5*********6*********7**
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
      DIMENSION AA(1),II(1),THETAG(1),COSTHG(1),SINTHG(1)
      DIMENSION EF(1),ZF(1),TF(1)
      DIMENSION FSEC(NU),PXEPA(NDIM1,NDIM2),XEF(MINTIM,3)
      DIMENSION XTD(3),X50(3)
      DIMENSION ATD(3),BTD(3)
      DIMENSION AEF(3),BEF(3),WEF(3)
      DIMENSION LAVOID(1)
!
      IF(.NOT.LSTINR) RETURN
      IF(NPVAL0(IXXTRO).LE.0) RETURN
      IPT5=IPVAL0(IXXTRO)+4
      IPT6=IPVAL0(IXXTRO)+5
      IPT7=IPVAL0(IXXTRO)+6
!
      DO 1000 IOBS=1,NU
      CALL ROTXTR(MJDSEC,FSEC(IOBS),.TRUE.,AA(KEQN),AA(KSRTCH),         &
     &   THETAG,COSTHG,SINTHG,1,AA,AA(KACOSW),AA(KBSINW),AA(KANGWT),    &
     &   AA(KWT),AA(KACOFW),AA(KBCOFW),II,1)
      XTD(1)=COSTHG(1)*XEF(IOBS,1)-SINTHG(1)*XEF(IOBS,2)
      XTD(2)=SINTHG(1)*XEF(IOBS,1)+COSTHG(1)*XEF(IOBS,2)
      XTD(3)=XEF(IOBS,3)
!
!
! W0 PERTURBED (RA & DEC ARE ONLY FORCE MODEL PARAMTERS)
      COSXX=COS(.00001D0)
      SINXX=SIN(.00001D0)
      COSX=COSTHG(1)*COSXX-SINTHG(1)*SINXX
      SINX=COSTHG(1)*SINXX+SINTHG(1)*COSXX
      WEF(1)= XTD(1)*COSX+XTD(2)*SINX
      WEF(2)=-XTD(1)*SINX+XTD(2)*COSX
      WEF(3)= XTD(3)
      DOBDW=100000.D0*(WEF(IX)-XEF(IOBS,IX))
!
      SCALT=DBLE(MJDSEC)+FSEC(IOBS)-T0XTRO
      SCALSQ=SCALT*SCALT
!
      IF(LNPNM) THEN
         LAVOID(IPT5)=.FALSE.
         LAVOID(IPT6)=.FALSE.
         LAVOID(IPT7)=.FALSE.
         PXEPA(IPT5,IOBS)=PXEPA(IPT5,IOBS)+DOBDW
         PXEPA(IPT6,IOBS)=PXEPA(IPT6,IOBS)+DOBDW*SCALT
         PXEPA(IPT7,IOBS)=PXEPA(IPT7,IOBS)+DOBDW*SCALSQ
!        NXALLC IS THE NUMBER OF PAIRS FOR PERIODIC TERMS
!        FOR THE SIMPLE MODEL WITH ONE FREQUENCY NXALLC=1
         IF(NXALLC.GT.0) THEN
           IPT=IPT7+1
           DO 500 IQ=1,NXALLC
           ANGWT=TWOPI/AA(KPPER-1+IQ)
           WT=ANGWT*SCALT
           WT=MOD(WT,TWOPI)
           F1=COS(WT)
           F2=SIN(WT)
           LAVOID(IPT)=.FALSE.
           PXEPA(IPT,IOBS)=PXEPA(IPT,IOBS)+DOBDW*F1
           IPT=IPT+1
           LAVOID(IPT)=.FALSE.
           PXEPA(IPT,IOBS)=PXEPA(IPT,IOBS)+DOBDW*F2
           IPT=IPT+1
  500      CONTINUE
         ENDIF
      ELSE
         LAVOID(IPT5)=.FALSE.
         LAVOID(IPT6)=.FALSE.
         LAVOID(IPT7)=.FALSE.
         PXEPA(IOBS,IPT5)=PXEPA(IOBS,IPT5)+DOBDW
         PXEPA(IOBS,IPT6)=PXEPA(IOBS,IPT6)+DOBDW*SCALT
         PXEPA(IOBS,IPT7)=PXEPA(IOBS,IPT7)+DOBDW*SCALSQ
!        NXALLC IS THE NUMBER OF PAIRS FOR PERIODIC TERMS
!        FOR THE SIMPLE MODEL WITH ONE FREQUENCY NXALLC=1
         IF(NXALLC.GT.0) THEN
           IPT=IPT7+1
           DO 600 IQ=1,NXALLC
           ANGWT=TWOPI/AA(KPPER-1+IQ)
           WT=ANGWT*SCALT
           WT=MOD(WT,TWOPI)
           F1=COS(WT)
           F2=SIN(WT)
           LAVOID(IPT)=.FALSE.
           PXEPA(IOBS,IPT)=PXEPA(IOBS,IPT)+DOBDW*F1
           IPT=IPT+1
           LAVOID(IPT)=.FALSE.
           PXEPA(IOBS,IPT)=PXEPA(IOBS,IPT)+DOBDW*F2
           IPT=IPT+1
  600      CONTINUE
         ENDIF
      ENDIF
 1000 END DO
      RETURN
      END
