      SUBROUTINE PREFCR(NCCALL,SFRAC,LHIGH,AA,COSTG,SINTG,ROTI)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/AXIS/LINTAX
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CRDDIM/NDCRD2,NDCRD3,NDCRD4,NDCRD5,NDCRD6,NDCRD7,          &
     &              NDCRD8,NDCRD9,NXCRDM
      DIMENSION AA(1)
      DIMENSION ROTI(9)
      DIMENSION Q1(4),Q2(4),QI(4)
      DIMENSION RA(1),DEC(1),FSEC(1),SCRTCH(4)
!
      NCARG=NCCALL-1
!
      IF(.NOT.LHIGH) THEN
         IF(LINTAX) THEN
            CALL GETOR(COSTG,SINTG,RA(1),DEC(1),1)
            CALL DXQN(MJDSC,FSEC,RA,DEC,ROTI(1),ROTI(2),ROTI(3),        &
     &                ROTI(4),ROTI(5),ROTI(6),ROTI(7),ROTI(8),          &
     &                ROTI(9),SCRTCH,1)

            RETURN
         ENDIF
         COSTG=AA(KCOSTG+NCARG)
         SINTG=AA(KSINTG+NCARG)
         ROTI(1)=AA(KROTMT+NCARG)
         ROTI(2)=AA(KROTMT+NCARG+NDCRD2)
         ROTI(3)=AA(KROTMT+NCARG+NDCRD3)
         ROTI(4)=AA(KROTMT+NCARG+NDCRD4)
         ROTI(5)=AA(KROTMT+NCARG+NDCRD5)
         ROTI(6)=AA(KROTMT+NCARG+NDCRD6)
         ROTI(7)=AA(KROTMT+NCARG+NDCRD7)
         ROTI(8)=AA(KROTMT+NCARG+NDCRD8)
         ROTI(9)=AA(KROTMT+NCARG+NDCRD9)
         RETURN
      ENDIF
      IF(LINTAX) THEN
        WRITE(6,6000)
        WRITE(6,6001)
        STOP
      ENDIF
! COWELL HAS BEEN SET UP SO THAT IN HIGH RATE INTEGRATION
! THERE IS ALWAYS ONE PREVIOUS STEP AVAILABLE FOR COORDINATE
! SYSTEM INFORMATIION
      COSTG=AA(KCOSTG+NCARG-1)                                          &
     &     +SFRAC*(AA(KCOSTG+NCARG)-AA(KCOSTG+NCARG-1))
      SINTG=AA(KSINTG+NCARG-1)                                          &
     &     +SFRAC*(AA(KSINTG+NCARG)-AA(KSINTG+NCARG-1))
      XN=SQRT(COSTG*COSTG+SINTG*SINTG)
      COSTG=COSTG/XN
      SINTG=SINTG/XN
!
!  CONVERT THE TRUE OF DATE / TRUE OF REFERENCE MATRIX
!  TO QUATERNIONS FOR INTERPOLATION. THE INTERPOLATED
!  QUATERNIONS CAN BE NORMALIZED MORE EASILY THAN
!  INTERPOLATED MATRICIES.
      ROTI(1)=AA(KROTMT+NCARG-1)
      ROTI(2)=AA(KROTMT+NCARG-1+NDCRD2)
      ROTI(3)=AA(KROTMT+NCARG-1+NDCRD3)
      ROTI(4)=AA(KROTMT+NCARG-1+NDCRD4)
      ROTI(5)=AA(KROTMT+NCARG-1+NDCRD5)
      ROTI(6)=AA(KROTMT+NCARG-1+NDCRD6)
      ROTI(7)=AA(KROTMT+NCARG-1+NDCRD7)
      ROTI(8)=AA(KROTMT+NCARG-1+NDCRD8)
      ROTI(9)=AA(KROTMT+NCARG-1+NDCRD9)
      CALL ROTQAT(ROTI,Q1)
      ROTI(1)=AA(KROTMT+NCARG)
      ROTI(2)=AA(KROTMT+NCARG+NDCRD2)
      ROTI(3)=AA(KROTMT+NCARG+NDCRD3)
      ROTI(4)=AA(KROTMT+NCARG+NDCRD4)
      ROTI(5)=AA(KROTMT+NCARG+NDCRD5)
      ROTI(6)=AA(KROTMT+NCARG+NDCRD6)
      ROTI(7)=AA(KROTMT+NCARG+NDCRD7)
      ROTI(8)=AA(KROTMT+NCARG+NDCRD8)
      ROTI(9)=AA(KROTMT+NCARG+NDCRD9)
      CALL ROTQAT(ROTI,Q2)
      QI(1)=Q1(1)+SFRAC*(Q2(1)-Q1(1))
      QI(2)=Q1(2)+SFRAC*(Q2(2)-Q1(2))
      QI(3)=Q1(3)+SFRAC*(Q2(3)-Q1(3))
      QI(4)=Q1(4)+SFRAC*(Q2(4)-Q1(4))
      QR=SQRT(QI(1)*QI(1)+QI(2)*QI(2)+QI(3)*QI(3)+QI(4)*QI(4))
      QI(1)=QI(1)/QR
      QI(2)=QI(2)/QR
      QI(3)=QI(3)/QR
      QI(4)=QI(4)/QR
      CALL QATROT(QI,ROTI)
      RETURN
 6000 FORMAT(' EXECUTION TERMINATING IN PREFCR')
 6001 FORMAT(' LINTAX AND LHIGH BOTH .TRUE.')
      END
