!$PREOL
      SUBROUTINE PREOL(ANGFAC,SPEEDO,IDOODN,IPTOLS)
!********1*********2*********3*********4*********5*********6*********7**
! PREOL            00/00/00            8604.0    PGMR - ?
!
! FUNCTION:  COMPUTES OCEAN LOADING SIDE BAND POINTER INFORMATION
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   ANGFAC   I    A    FACTORS TO MULTIPLY EACH OF THE 5 ARGUMENTS BY
!                      SIDEBANDS OR NOT FOR SAT TIDES
!   IPTOLS   O    A    POINTER FROM OCEAN LOADING FREQUENCIES TO
!                      SATELLITE TIDE SIDE BAND INFORMATION
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CTIDES/NTIDE,NSTADJ,NET,NETADJ,NETUN,NOT,NOTADJ,           &
     &   NOTUN ,NETUNU,NETADU,NOTUNU,NOTADU,NBSTEP,KTIDA(3),            &
     &   ILLMAX,NUNPLY,NNMPLY,NDOODN,MXTMRT,NRESP ,NXCTID
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      DIMENSION ANGFAC(NTOLFR,6)
      DIMENSION SPEEDO(NTOLFR)
      DIMENSION IDOODN(NDOODN,3)
      DIMENSION IPTOLS(NTOLFR)
      DIMENSION ANGST2(6)
      DIMENSION SPEEDA(5)
      DATA SPEEDA/.1991063804D-6,.2661707251D-5,.2250425926D-7, &
     & .1069699416D-7,.9507237213D-11/
      DATA SPEEDE/.7272205217D-4/
!
      DO 500 I=1,NTOLFR
      LRETRO=.FALSE.
      IF(SPEEDO(I).LT.0.D0) LRETRO=.TRUE.
      IPTOLS(I)=0
      DO 300 J=1,NDOODN
      JFRQOL=IDOODN(J,1)*10
! BREAK THE FREQUENCY NUMBER DOWN INTO SIX ARGUMENTS
      JARGT=JFRQOL/1000000
      IARGT=JARGT
      ISN=1
      IF(LRETRO) ISN=-1
      IF(JARGT.GE.6) THEN
        IARGT=(JARGT-6)
      ENDIF
      JARGH=MOD(JFRQOL,100000)/10000-5
      JARGS=MOD(JFRQOL,1000000)/100000-5
      IARGP=MOD(JFRQOL,10000)/1000-5
      IARGN=MOD(JFRQOL,1000)/100-5
      IARGPS=MOD(JFRQOL,100)/10-5
! FOLD THE ARGT INTO ARGH&S
      IARGH=JARGH+IARGT
      IARGS=JARGS-IARGT
! LOAD ANGFAC WITH FACTORS
      ANGST2(1)=DBLE(ISN*IARGH)
      ANGST2(2)=DBLE(ISN*IARGS)
      ANGST2(3)=DBLE(ISN*IARGP)
      ANGST2(4)=DBLE(ISN*IARGN)
      ANGST2(5)=DBLE(ISN*IARGPS)
      ANGFCT=DBLE(IARGT*ISN)
! FIGURE DERIVATIVE WRT TIME OF ANGULAR ARG
      SPEED=ANGST2(1)*SPEEDA(1)+ANGST2(2)*SPEEDA(2) &
     & +ANGST2(3)*SPEEDA(3)+ANGST2(4)*SPEEDA(4) &
     & +ANGST2(5)*SPEEDA(5)+ANGFCT*SPEEDE
      DO 100 K=1,5
      TEST=ABS(ANGFAC(I,K)-ANGST2(K))
      IF(TEST.GT..1D0) GO TO 300
  100 END DO
      TESTN=ABS(SPEEDO(I)-SPEED)
      TESTD=ABS(SPEEDO(I)+SPEED)
      TEST=TESTN/TESTD
      IF(TEST.GT..1D0) GO TO 300
      IPTOLS(I)=J
!!!
! ALL OCEAN LOADING HAS TYPE 1 (SIDEBANDS)
      IDOODN(J,2)=1
!!!
      GO TO 500
  300 END DO
  500 END DO
      RETURN
      END
