!$RDPRD1
      SUBROUTINE RDPRD1(LSST,LTID,LALL,NTPNTO,NTPNTS,RLATB,RLONB,       &
     & XLTMNO,XLTMXO,XLNMNO,XLNMXO,XLTMNS,XLTMXS,XLNMNS,XLNMXS,         &
     & IUPRDO,IUPRDS)
!********1*********2*********3*********4*********5*********6*********7**
! RDRDD1               03/99            9910.0        PGMR - S.LUO
!
! FUNCTION         FIRST READ PROUDMAN FUNCTION FILE(GRID file)
!                  FOR SEA SURFACE TOPOGRAPHY MODEL AND OCEAN TIDE
!                  MODEL IN ORDER TO GET THE NUMBERS WHICH ARE
!                  NEEDED FOR ALLOCATE SPACE
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!  LSST      I    S    .TRUE. IF SEA SURFACE TOPOGRAPHY HAS BEEN SELECTE
!  LTID      I    S    .TRUE. IF OCEAN TIDE MODEL HAS BEEN SELECTED
!  LALL      I    S    .TRUE. IF THE WHOLE FILE IS TO BE READ
!  RLATB     I    A    LATITUDE OF SATELLITE FOR THIS BLOCK
!  RLONB     I    A    LONGITUDE OF SATELLITE FOR THIS BLOCK
!  NNPNTO    O    S    NUMBER OF GRID POINT OF OCEAN TIDE PRODMAN FUNCTI
!                      COVERED BY SATELLITE IN THE BLOCK
!  NNPNTS    O    S    NUMBER OF GRID POINT OF SST PRODMAN FUNCTION
!                      COVERED BY SATELLITE IN THE BLOCK
!  XLTMNO    O    S
!  XLTMXO    O    S
!  XLNMNO    O    S
!  XLNMXO    O    S
!  XLTMNS    O    S
!  XLTMXS    O    S
!  XLNMNS    O    S
!  XLNMXS    O    S
!
! COMMENTS
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL(L)
      SAVE
!
      COMMON/CIOTMD/NOTPT,NOTPRF,NODEG,NXCIOT
      COMMON/CISSTM/NSSTPT,NSSTF,NSDEG,NXCISS
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      DIMENSION RLATB(NM),RLONB(NM)
      REAL SSTPT,SSIZE
      DATA XLTMIN,XLTMAX/90.D0,-90.D0/
      DATA XLNMIN,XLNMAX/360.D0,0.D0/
      DATA LINIT/.TRUE./
!
!**********************************************************************
!* START OF EXECUTABLE CODE *******************************************
!**********************************************************************
!
!
      XLTMNO=XLTMIN
      XLTMXO=XLTMAX
      XLNMNO=XLNMIN
      XLNMXO=XLNMAX
      DO 18 I=1,NM
      XLTMNO=MIN(XLTMNO,RLATB(I))
      XLTMXO=MAX(XLTMXO,RLATB(I))
      XLNMNO=MIN(XLNMNO,RLONB(I))
      XLNMXO=MAX(XLNMXO,RLONB(I))
   18 END DO
      XLTMNS=XLTMNO
      XLTMXS=XLTMXO
      XLNMNS=XLNMNO
      XLNMXS=XLNMXO
      IF(LSST) THEN
       IF(LINIT)THEN
      OPEN(UNIT=IUPRDS,FILE='ftn28',STATUS='OLD',             &
     &   FORM='UNFORMATTED')
      READ(IUPRDS,ERR=300)SSTPT,SSIZE
      NSSTPT=INT(SSTPT+0.01)
      NSDEG = INT(SSIZE+0.01)
        ENDIF
      XLTMNS=XLTMNS-NSDEG*5.0
      XLTMXS=XLTMXS+NSDEG*5.0
      XLNMXS=XLNMXS+NSDEG*5.0
      XLNMNS=XLNMNS-NSDEG*5.0
      IF(XLTMNS.LT.-90.0)XLTMNS=-90.0
      IF(XLTMXS.GT.+90.0)XLTMXS=+90.0
      IF(XLNMNS.LT.0.0)XLNMNS=0.0
      IF(XLNMXS.GT.+360.0)XLNMXS=360.0
!
      DXLAT=XLTMXS-XLTMNS
      DXLON=XLNMXS-XLNMNS
      NSLTS=INT(DXLAT+0.1)/NSDEG+2
      NSLNS=INT(DXLON+0.1)/NSDEG+2
      NTPNTS= NSLTS*NSLNS
      IF(.NOT.LALL) GOTO 301
      ENDIF
      IF(LTID) THEN
       IF(LINIT)THEN
      OPEN(UNIT=IUPRDO,FILE='ftn27',STATUS='OLD',             &
     &   FORM='UNFORMATTED')
      READ(IUPRDO,ERR=310)RNOTPT,TSIZE
      NOTPT=INT(RNOTPT+0.01D0)
      NODEG=INT(TSIZE + 0.01)
        ENDIF
      XLTMNO=XLTMNO-NODEG*2.0
      XLTMXO=XLTMXO+NODEG*2.0
      XLNMXO=XLNMXO+NODEG*2.0
      XLNMNO=XLNMNO-NODEG*2.0
      IF(XLTMNO.LT.-90.0)XLTMNO=-90.0
      IF(XLTMXO.GT.+90.0)XLTMXO=+90.0
      IF(XLNMNO.LT.0.0)XLNMNO=0.0
      IF(XLNMXO.GT.+360.0)XLNMXO=360.0
      DXLAT=XLTMXO-XLTMNO
      DXLON=XLNMXO-XLNMNO
      NOLTS=INT(DXLAT)/NODEG+2
      NOLNS=INT(DXLON)/NODEG+2
      NTPNTO= NOLTS*NOLNS
      GO TO 301
      ENDIF
  300 WRITE(6,*)' CAN NOT READ UNIT 28  '
      GOTO 301
  310 WRITE(6,*)' CAN NOT READ UNIT 27  '
  301 CONTINUE
!     PRINT *,'*RDPRD1*NSSTF,NSSTPT,NTPNTS=',NSSTF,NSSTPT,NTPNTS
!     PRINT *,'*RDPRD1*NOTPRF,NOTPT,NTPNTO=',NOTPRF,NOTPT,NTPNTO
      LINIT=.FALSE.
 9999 RETURN
      END
