!$REFGS
      SUBROUTINE REFGS(NM,COSLAT,SINLAT,COSLON,SINLON,C,S,ICPNT,        &
     &                 ISPNT,P,COSLAM,SINLAM,EXPART,GEOIDS,PMPA,LNPNM,  &
     &                 NDIM1,NDIM2,LGEOID,LGPART,WORK,AA)
!********1*********2*********3*********4*********5*********6*********7**
! REFGS            00/00/00            0000.0    PGMR - ?
!
! FUNCTION:   THIS SUBROUTINE IS PARALLEL TO SUBROUTINE GEOID FOR
!             OTHER THAN THE EARTH PLANETS.
!             THE WORDS GEOID AND GEOCENTRIC HERE REFER TO THE PLANET
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   NM       I         NUMBER OF POINTS FOR WHICH CALCULATION DESIRED
!                      REQUIRED
!   COSLAT   I         COSINE OF GEOCENTRIC LATITUDES
!   SINLAT   I         SINE   OF GEOCENTRIC LATITUDES
!   COSLON   I         COSINE OF LONGITUDES
!   SINLON   I         SINE OF LONGITUDES
!   C        I         GRAVITY C COEFFCIENTS
!   S        I         GRAVITY S COEFFCIENTS
!   ICPNT    I         POINTER IN C ARRAY TO ADJUSTED COEFFCIENTS
!   ISPNT    I         POINTER IN S ARRAY TO ADJUSTED COEFFCIENTS
!   P             A    SPACE FOR LGENDRE POLYNOMIALS
!   COSLAM        A    SPACE FOR COS(M*SATLON)
!   SINLAM        A    SPACE FOR SIN(M*SATLON)
!   EXPART        A    SPACE FOR C & S PARTIALS (FULL SET)
!   GEOIDS   O         GEOID HT
!   PMPA     O         PARTIALS OF ALTIMETRY MEAS WRT C&S COEFFCIENTS
!   LNPNM    I         .TRUE. IF NP IS THE FIRST DIMENSION IN THE PMPA
!                      ARRAY (AS OPPOSED TO NM)
!   NDIM1    I         FIRST DIMENSION OF PMPA ARRAY
!   NDIM2    I         SECOND DIMENSION OF PMPA ARRAY
!   LGEOID   I         .TRUE.,IF CALCULATION OF GEOID HT REQUIRED
!   LGPART   I         .TRUE.,IF CALCULATION OF GRAVITY COEFFCIENTS
!   WORK          A    SPACE FOR ADJUSTED C&S
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CEBODY/APL(11),APLSQ,FINVPL(11),FGP,EGSQP,EGSQPP,C1P,C2P,  &
     &              FOURCP,TWOC2P,WREFP(11),RPMEAN,RFPC20,              &
     &              RFPC40,RFPC60,BEGP,CBLTCP,                          &
     &              WAE2P,GAMMAP,FSTARP,F4P
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/GEODEG/NMAX,NMAXP1,NP,NTOLD,NTOLO,NADJC,NADJS,NADJCS,      &
     &              NPMAX,NXGDEG
      COMMON/GEOMCS/MDEGEO,MORGEO,NPGEOM,NXGEOM
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/VRBLOK/SINPSI,COSPSI,XLAMDA,GMR,AOR
      DIMENSION SINLAT(NM),COSLAT(NM),COSLON(NM),SINLON(NM),C(1),S(1),  &
     &          ICPNT(1),ISPNT(1),P(1),COSLAM(37),SINLAM(37),           &
     &          EXPART(NP,*),                                           &
     &          GEOIDS(NM),PMPA(NDIM1,NDIM2),WORK(NADJCS),AA(1)
! %%%%%%%% EXPART(NP,1) -> EXPART(NP,*)
      DATA ZERO/0.D0/,ONE/1.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      NMAXL1=NMAX-1
!
      DO 500 I=1,NM
!
! CALCULATE COSLAM & SINLAM ARRAYS
      COSLAM(1)=ONE
      SINLAM(1)=ZERO
      SINLAM(2)=SINLON(I)
      COSLAM(2)=COSLON(I)
      CL2=COSLAM(2)+COSLAM(2)
      SINLAM(3)=CL2*SINLAM(2)
      COSLAM(3)=CL2*COSLAM(2)-ONE
      DO 20 N=2,NMAXL1
      N1=N+1
      N2=N+2
      SINLAM(N2)=CL2*SINLAM(N1)-SINLAM(N)
      COSLAM(N2)=CL2*COSLAM(N1)-COSLAM(N)
   20 END DO
      COSPSI=COSLAT(I)
      SINPSI=SINLAT(I)
      SINP2=SINPSI*SINPSI
      COSP2=COSPSI*COSPSI
      GAMMA=GAMMAP*(ONE+FSTARP*SINP2-F4P*SINP2*COSP2)
      R=BEGP/SQRT(ONE-EGSQP*COSP2)
!     AOR=APL(ICBDGM)/R
      AOR=AE/R
      GMR=GM/R
      AORN1=AOR*GMR/GAMMA
!
      CALL LGENDR(.TRUE.,AA(KXNRMZ),AA(KXNRMC),AA(KVRARY),P,            &
     &            AA(KAORN),SINLAM,COSLAM,AA(KTANPS),NMAX)
!  (1)CALCULATE ALL PARTIALS UP TO DEGREE NMAX (VECTORIZED)
!  (2)IF GEOID REQUIRED,DOT PRODUCT THIS WITH C &S COEFFCIENTS
!  (3)IF PARTIALS REQUIRED,THEN SQUEEZE PARTIALS OUT OF FULL ARRAY
!
      KRA=0
      KNL=2
      DO 110 N=1,NMAX
      DO 105 KR=1,KNL
      KRAA=KR+KRA
      EXPART(KRAA,1)=P(KRAA)*AORN1
      EXPART(KRAA,2)=SINLAM(KR)*EXPART(KRAA,1)
      EXPART(KRAA,1)=COSLAM(KR)*EXPART(KRAA,1)
      AORN1=AORN1*AOR
  105 END DO
      KRA=KRA+N+3
      KNL=KNL+1
  110 END DO
!
      IF(.NOT.LGEOID) GO TO 140
!
!
      POT=ZERO
      DO 130 N=1,NP
      NPT=NP+1-N
      POT=POT+EXPART(NPT,1)*C(NPT)+EXPART(NPT,2)*S(NPT)
  130 END DO
!
!     SUBTRACT OFF CONTRIBUTION FROM REFERENCE ELLIPSOID POTENTIAL
      GEOIDS(I)=POT-(RFPC20*EXPART(5,1)+RFPC40*EXPART(16,1)             &
     &         +RFPC60*EXPART(31,1))
      GEOIDS(I)=GEOIDS(I)
      IF (.NOT.LGPART) GO TO 500
  140 CONTINUE
!
!   PUT PARTALS WRT C INTO PARTIAL ARRAY
      ISTRTC=IPVAL0(IXGPC)
      ISTRTS=IPVAL0(IXGPS)
      IF(.NOT.LNPNM) GO TO 300
! NUMBER OF PARAMETRS IS THE FIRST DIMENSION
      IF(NADJC.LE.0) GO TO 150
      DO 125 II=1,NADJC
      PMPA(II+ISTRTC-1,I)=-EXPART(ICPNT(II),1)
  125 END DO
!
  150 CONTINUE
!   PUT PARTIALS WRT S INTO PARTIAL ARRAY
      IF(NADJS.LE.0) GO TO 200
      DO 175 II=1,NADJS
      PMPA(II+ISTRTS-1,I)=-EXPART(ISPNT(II),2)
  175 END DO
  200 CONTINUE
      GO TO 500
  300 CONTINUE
! NUMBER OF PARAMETRS IS THE SECOND DIMENSION
      IF(NADJC.LE.0) GO TO 400
!   PUT PARTIALS WRT C INTO PARTIAL ARRAY
      DO 325 II=1,NADJC
      PMPA(I,II+ISTRTC-1)=-EXPART(ICPNT(II),1)
  325 END DO
!
  400 CONTINUE
      IF(NADJS.LE.0) GO TO 500
!   PUT PARTIALS WRT S INTO PARTIAL ARRAY
      DO 425 II=1,NADJS
      PMPA(I,II+ISTRTS-1)=-EXPART(ICPNT(II),2)
  425 END DO
  500 END DO
!     IF(.NOT.LGEOID) RETURN
!      DO 600 I=1,NM
!      GEOIDS(I)=GEOIDS(I)*RPMEAN
! 600  CONTINUE
      RETURN
      END
