!$ROTMTR
      SUBROUTINE ROTMTR(MJDSEC,FSEC,LEQC,EQN,SCRTCH,THETAG,COSTHG,      &
     &                  SINTHG,NM,AA,II)
!********1*********2*********3*********4*********5*********6*********7**
! ROTMTR           93/03/31               PGMR - S.LUO
!
! FUNCTION:  COMPUTE THE ANGLE BETWEEN THE IAU VECTOR OR EQUINOX
!            AND THE PRIME MERIDIAN FOR MARS AT
!            A VECTOR OF TIMES OF LENGTH "NM"
!            ALSO COMPUTE THE COSINES AND SINES OF THIS
!            ANGLE. THIS SUBROUTINE PARALLELS GRHRAN. IT
!            THEREFORE HAS DUMMY ARGUMENTS.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    MODIFIED JULIAN DAY SECONDS OF THE VECTOR
!                      OF TIMES OF INTEREST (EPHEMERIS TIME)
!   FSEC     I    A    THE FRACTION OF SECONDS OF THE VECTOR OF
!                      TIMES OF INTEREST (EPHEMERIS TIME)
!   LEQC     I    S    .TRUE. IF IT IS NECCESSARY TO CALCULATE EQN
!                      OF THE EQUINOX IN ROUTINE
!   EQN     I/O   A    EQUATION OF THE EQUINOX (INPUT IF LEQC=.FALSE.)
!                      EQN OF THE EQUINOX (OUTPUT IF LEQC=.TRUE.)
!   SCRTCH  I/O    A   5*NM
!   THETAG   O     A   VECTOR OF VALUES OF RIGHT ASCENSION OF
!                      PRIME MERIDIAN OF MARS
!   COSTHG   O     A   COSINES OF THETAG
!   SINTHG   O     A   SINES OF THETAG
!   NM       I     S   NUMBER OF TIMES OF INTEREST
!   AA      I/O    A   DYNAMIC REAL SPACE
!   II      I/O    A   DYNAMIC INTEGER SPACE
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
!
      DIMENSION FSEC(NM),THETAG(NM),COSTHG(NM),SINTHG(NM),EQN(NM),      &
     &          SCRTCH(NM,5),AA(1),II(1)
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/EPHSET/EMFACT,DTENPD,DTINPD,FSC1EN,FSCENP(2),FSCINP(4),    &
     &   FSDINP(4),XEPHST
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/LEPHM2/LXEPHM
      DIMENSION THMTGC(2,2)
!
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!     DD0 = JD2000 - GEODYN REF. TIME
      DD0  = 2451545.D0 - TMGDN1
!
!     THMTGC(1,1)=319.0779911D0
      THMTGC(1,1)=319.2169911D0
      THMTGC(2,1)=350.8919857D0
      THMTGC(1,2)=176.868D0
      THMTGC(2,2)=350.8919830D0
!
! GET EQN OF EQUINOX IF NECESSARY
!CC   CALL NUVMCT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),
!CC  .            NM,SCRTCH)
!
      IF(.NOT.LEQC) GO TO 500
      CALL BUFXTR(MJDSEC,FSEC(1),MJDSEC,FSEC(NM),1,MJDDUM,FSCDM,LDUM,   &
     &            AA)
!
      IF(LXEPHM) THEN
      DO IJ=1,ICBODY
      CALL BUFSUP(AA,MJDSEC,FSEC(1),MJDSEC,FSEC(NM),                    &
     &           II(KISUPE),AA(KEPHMS),IJ,1)
      ENDDO
      ENDIF
!
  500 CONTINUE
!
!     XJDSC0=FLOAT(MJDSEC)-FSDINP(1)
      XJDSC0=DBLE(MJDSEC)
      X0=THMTGC(1,1)
      DO 1000 I=1,NM
!     SCRTCH(I,1)=XJDSC0+FSEC(I)
      SCRTCH(I,1)=(XJDSC0+FSEC(I))/86400.D0 - DD0
      THETAG(I)=X0+SCRTCH(I,1)*THMTGC(2,1)
      IF(LEQC) THEN
      THETAG(I)=(THETAG(I))*DEGRAD+EQN(I)
      ELSE
      THETAG(I)=THETAG(I)*DEGRAD
      ENDIF
      THETAG(I)=MOD(THETAG(I),TWOPI)
 1000 END DO
! EVALUATE COSINES OF THETAG
      DO 4000 N=1,NM
      COSTHG(N)=COS(THETAG(N))
 4000 END DO
! EVALUATE SINES OF THETAG
      DO 5000 N=1,NM
      SINTHG(N)=SIN(THETAG(N))
 5000 END DO
      RETURN
      END
