!$RPY
      SUBROUTINE RPY(AA,II,PARMV,PARMV0,                                &
     &MAXBOD,TDIF,IRET,INDX,IADD,NOBS,ROT,                              &
     &ITERP,IMOD,INDS,PER,ROLL,PITCH,YAW,SINWT,COSWT)
!********1*********2*********3*********4*********5*********6*********7**
! RPY                                            PGMR - D.PAVLIS
!
! FUNCTION: MODEL ROLL PITCH YAW AND FORM THE PARTIALS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC REAL ARRAY
!   II      I/O   A    DYNAMIC INTGER ARRAY
!   PARMV   I     A    PARAMETER VALUE ARRAY
!   PARMV0  I     A    ADJUSTED PARAMETER VALUE ARRAY
!   MAXBOD  I     S    NUMBER OF LASERS + 1( S/C)
!   IMOD    I     S    1 or 2 ; 1 FOR SC BODY ; 2 FOR LASER OR CAMERA PT
!   IRET    I     S    SAT # IF IMOD=1 OR LASER # IF IMOD=2
!   INDX    I     S    ATITUDE PERIOD #
!   IADD    I     S    STARTING ATITUDE PARAMETER FOR THIS SAT
!   INDS    I     S    A NUMBER FROM 1 TO 6 INDICATING THE ORDER OF
!                      ROTATIONS :123,132,213,231,312,321
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z), LOGICAL (L)

      SAVE
!
      COMMON/ATTCB /KPAT,MAXAT,MAXLAS,IBLAS,                            &
     &              NASAT,IATCNT,NXATT
      COMMON/ATTCBD/BATPER,ATTPRT
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
!
      DIMENSION AA(1),II(1)
      DIMENSION PARMV(1),PARMV0(1)
      DIMENSION PMPA(NM,MAPARM)
      DIMENSION ROT(3,3)
!
!**********************************************************************
!* START OF EXECUTABLE CODE *******************************************
!**********************************************************************

      R100=0.D0
      P100=0.D0
      Y100=0.D0

      IF(IMOD.EQ.1) THEN
       K=0
       IF(ITERP.EQ.4.OR.ITERP.EQ.7) R100=ATTPRT
       IF(ITERP.EQ.5.OR.ITERP.EQ.8) P100=ATTPRT
       IF(ITERP.EQ.6.OR.ITERP.EQ.9) Y100=ATTPRT
      ELSE
       K=IRET
       IF(ITERP.EQ.4.OR.ITERP.EQ.7) R100=ATTPRT
       IF(ITERP.EQ.5.OR.ITERP.EQ.8) P100=ATTPRT
       IF(ITERP.EQ.6.OR.ITERP.EQ.9) Y100=ATTPRT
      ENDIF

!     write(6,*)' dbg RPY ',ITERP,R100,P100,Y100
! PARAMETER ADDRESS FOR S/C
! PARAMETER ADDRESS FOR LASER

      RLC= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+0 +IADD )
      RLL= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+1 +IADD )
      RLQ= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+2 +IADD )
      RLSWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+3 +IADD )
      RLCWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+4 +IADD )
      PLC= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+5 +IADD )
      PLL= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+6 +IADD )
      PLQ= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+7 +IADD )
      PLSWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+8 +IADD )
      PLCWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+9 +IADD )
      YLC= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+10 +IADD )
      YLL= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+11 +IADD )
      YLQ= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+12 +IADD )
      YLSWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+13 +IADD )
      YLCWT= PARMV(IPVAL(IXATUD)+(15*MAXBOD)*(INDX-1)+15*K+14 +IADD )

      IF(PER.GT.0.D0) THEN
       WT=(TWOPI/PER)*TDIF
       SINWT=SIN(WT)
       COSWT=COS(WT)
      ELSE
       SINWT=0.D0
       COSWT=0.D0
      ENDIF

      ROLL  = RLC+ RLL*TDIF + RLQ*(TDIF**2.D0) +                        &
     &RLSWT*SINWT+ RLCWT*COSWT +  R100

      PITCH = PLC+ PLL*TDIF + PLQ*(TDIF**2.D0) +                        &
     &PLSWT*SINWT+ PLCWT*COSWT +  P100

      YAW   = YLC+ YLL*TDIF + YLQ*(TDIF**2.D0) +                        &
     &YLSWT*SINWT+ YLCWT*COSWT +  Y100

!      print *,'rpy: inds,per,imod,k: ',inds,per,imod,k
!      print *,'rpy: roll,pitch,yaw in degrees: ',roll,pitch,yaw

      ROLL = MOD(ROLL,360.D0) *DEGRAD
      PITCH= MOD(PITCH,360.D0)*DEGRAD
      YAW  = MOD(YAW,360.D0)  *DEGRAD



!
      CALL GETROT(INDS, ROT,ROLL,PITCH,YAW)
!

      RETURN
      END
