!$SATUP2
      SUBROUTINE SATUP2(MJDSEC,FSEC,X1,X2,AA,NM,NDIM,LMATC,LTDTR,II)
!********1*.*******2*********3*********4*********5*********6*********7**
! SATUPD           87/09/30            8710.0    PGMR - D. ROWLANDS
!
! FUNCTION:  TRANFORM TRUE OF DATE EARTH EQUATOR & EQUINOX
!            (TDEEES) SYSTEM TO TRUE OF REF SATELLTE SYSTEM
!            (TRSS). THE TRSS MAY BE THE IAU SYSTEM IF THE
!            CENTER OF INTEGRATION IS NOT THE EARTH). THE
!            ROUTINE CAN GO IN THE OTHER DIRECTION ALSO.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    INTEGER NUMBER OF SECONDS SINCE GEODYN REF.TIME
!                      FOR THE BLOCK TO BE TRANSFORMED.
!   FSEC     I    A    ELAPSED SECONDS SINCE MJDSEC FOR EACH DATA
!                      POINT
!   X1       I    A    TDEEES COORDINATES OR TRSS COORDINATES
!   X2       O    A    TRSS COORDINATES OR TDEEES COORDINATES
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   NM       I    S    NUMBER OF LIGHT TIMES TO BE COMPUTED
!   NDIM     I    S    FIRST DIMENSION OF X1 & X2
!   LMATC    I    S    .TRUE. IF MATRIX CALCULATION IS NECESSARY.
!   LTDTR    I    S    .TRUE. IF GOING FROM TDEEES TO TRSS
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
!      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!      SAVE
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/DPLNOR/DXGEO1,DXGEO2,DXFRC1,DXFRC2,XPLNOR
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CRDDIM/NDCRD2,NDCRD3,NDCRD4,NDCRD5,NDCRD6,NDCRD7,          &
     &              NDCRD8,NDCRD9,NXCRDM
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/LEPHM2/LXEPHM
      DIMENSION AA(1),II(1),X1(1),X2(1),FSEC(NM),DUM(3),DUm2(3,2,1)
      DATA ZERO/0.0D0/,ONE/1.0D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      IF(.NOT.LMATC) GO TO 100
! CALCULATE THE MATRIX THAT WILL BE NECESSARY
!
      JREFSY=0
           IF(JREFSY.EQ.0) THEN
      IF(ICBDGM.EQ.3) THEN
      CALL BUFEAR(MJDSEC,FSEC(1),MJDSEC,FSEC(NM),1,MJDR,FSECR,LRECAL,   &
     &            AA,II)
      CALL PRECSS(MJDSEC,FSEC,AA(KETA),AA(KZTA),AA(KTHTA),              &
     &            AA(KSRTCH),NM)
      CALL NUVECT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            NM,AA(KSRTCH))
      CALL NPVECT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NM,AA(KSRTCH),            &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.,                   &
     &            AA(KPDPSI),AA(KPEPST),AA(KNUTIN),AA(KNUTMD),.FALSE.,  &
     &            AA(KDXDNU),AA(KDPSIE),AA(KEPSTE),DUM,DUM2)
      ELSE
      CALL BUFXTR(MJDSEC,FSEC(1),MJDSEC,FSEC(NM),1,MJDR,FSECR,LRECAL,   &
     &            AA)
!
      IF(LXEPHM) THEN
      DO IJ=1,ICBODY
      CALL BUFSUP(AA,MJDSEC,FSEC(1),MJDSEC,FSEC(NM),                    &
     &II(KISUPE), AA(KEPHMS),IJ,1)
      ENDDO
      ENDIF
!
! NEW SUBROUTINE FOR NUTATION CALCULATION ONLY FOR MARS
         IF(LMARS.AND.IMRNUT.EQ.1) THEN
      CALL PRMCSS(MJDSEC,FSEC,AA(KETA),AA(KZTA),AA(KTHTA),              &
     &            AA(KSRTCH),NM)
      CALL NUVMCT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            NM,AA(KSRTCH))
      CALL NPVMCT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NM,AA(KSRTCH),            &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.)
      CALL MM2EJ2(MJDSEC,FSEC,AA(KROTMT),NDCRD2,AA(KSRTCH),             &
     & .FALSE.)
!
         ELSE
      CALL PRXCSS(MJDSEC,FSEC,AA(KETA),AA(KZTA),AA(KTHTA),              &
     &            AA(KSRTCH),NM,AA(KDPSI),AA(KEPST),AA(KEPSM),AA,1)
      DO I=1,NM
       AA(KZTA-1+I)=AA(KZTA-1+I)+DEGRAD*DXGEO1
      ENDDO
      CALL NUVXCT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            NM,AA(KSRTCH))
      CALL NPVXCT(MJDSEC,FSEC,AA(KDPSI),AA(KEPST),AA(KEPSM),            &
     &            AA(KETA),AA(KTHTA),AA(KZTA),NM,AA(KSRTCH),            &
     &            AA(KROTMT),AA(KEQN),NDCRD2,.FALSE.)
      ENDIF
      ENDIF
           ELSE
         DO JJ=1,NM
             AA(KROTMT-1+JJ)=ONE
             AA(KROTMT+NDCRD2-1+JJ)=ZERO
             AA(KROTMT+NDCRD3-1+JJ)=ZERO
             AA(KROTMT+NDCRD4-1+JJ)=ZERO
             AA(KROTMT+NDCRD5-1+JJ)=ONE
             AA(KROTMT+NDCRD6-1+JJ)=ZERO
             AA(KROTMT+NDCRD7-1+JJ)=ZERO
             AA(KROTMT+NDCRD8-1+JJ)=ZERO
             AA(KROTMT+NDCRD9-1+JJ)=ONE
        ENDDO

       ENDIF
  100   CONTINUE
      CALL TDTR(AA(KROTMT),AA(KROTMT+NDCRD2),AA(KROTMT+NDCRD3),         &
     &    AA(KROTMT+NDCRD4),AA(KROTMT+NDCRD5),AA(KROTMT+NDCRD6),        &
     &    AA(KROTMT+NDCRD7),AA(KROTMT+NDCRD8),AA(KROTMT+NDCRD9),        &
     &   X1,X2,AA(KSRTCH),NM,NDIM,LTDTR)
      RETURN
      END
