!$SIMDAT
      SUBROUTINE SIMDAT(AA,II,LL,OBS,RESID,SUMCOR,MTYPE,NM,NMWTD,LEDIT)
!********1*********2*********3*********4*********5*********6*********7**
! SIMDAT           87/04/07            8704.0    PGMR - TOM MARTIN
!
!
! FUNCTION:  CONTROL THE WRITING OF SIMULATED DATA RECORDS
!            FOR ONE BLOCK OF OBSERVATIONS.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY.
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   OBS      I    A    OBSERVATION VALUES.
!   RESID    I    A    RESIDUAL VALUES.
!   SUMCOR   I    A    SUM OF OBSERVATION CORRECTIONS ARRAY
!   MTYPE    I    S    MEASUREMENT TYPE
!   NM       I    S    NUMBER OF OBSERVATIONS IN THE BLOCK.
!   NMWTD    I    S    NUMBER OF WEIGHTED OBSERVATIONS
!   LEDIT    I    A    LOGICAL FLAG FOR EDITING OBSERVATIONS
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBIASA/BIASE (4),BIASM (2),BSCALE(1)  ,TBIAS (1),          &
     &              BSTROP(3),BSIONO(3),CLKSTA(4,2),CLKSAT(4,2),        &
     &              CLKSTS(2,2),TROPZE(2,2),TROPGR(2,4),BSLBIA(1)
      COMMON/CBIASI/IEBIAS(4),IMBIAS(2),IBSCAL(1)  ,ITBIAS(1),          &
     &              IBTROP(3),IBIONO(3),KLKSTA(4,2),KLKSAT(4,2),        &
     &              KLKSTS(2,2),ITRPZE(2,2),ITRPGR(2,4),IBSBIA(1)
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/COBGLO/MABIAS,MCBIAS,MPVECT,MINTPL,MPARAM,MSTA,MOBBUF,     &
     &       MNPITR,MWIDTH,MSIZE ,MPART ,MBUF  ,NXCOBG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/COPARM/LOP1
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/ION2EL/LIONC,LFRQOP,LFRQOF,NXIONL
      COMMON/OCCLTL/LOCCLT(200),LMSHD(200)
      COMMON/TROPX/LOUTRP
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION OBS(NM),RESID(NM),SUMCOR(NM),LEDIT(NM)
      DIMENSION TROPP(3)
      DATA ZERO/0.0D0/,ONE/1.0D0/,METRIX/37/,MOPT/12/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      TROPP(1)=0.D0
      TROPP(2)=0.D0
      TROPP(3)=0.D0
!
!     FURTHER EDIT BASED ON OCCULTATION
      NNMWTD=NMWTD
      DO 100 I=1,NM
      IF(LEDIT(I)) GO TO 100
      IF(LOCCLT(I)) NNMWTD=NNMWTD-1
  100 END DO
      IF(LACC) GOTO 999
      IF(NNMWTD.LE.0) RETURN
  999 CONTINUE
      LOP=(MTYPE.GT.MOPT).AND.(MTYPE.LT.METRIX).AND.(MTYPE.NE.31)
! INITIALIZE NORMAL POINT OUTPUT FILE BUFFER
      DO 1000 I=1,NM
      IF(LOUTRP) THEN
        TROPP(1)=0.D0
        TROPP(2)=0.D0
        TROPP(3)=0.D0
      IF(IBTROP(1).GT.0) TROPP(1)=BSTROP(1)
      IF(IBTROP(2).GT.0) TROPP(2)=BSTROP(2)
      IF(IBTROP(3).GT.0) TROPP(3)=BSTROP(3)
      ENDIF
      CALL PRESUB(MTYPE,SUMCOR(I),AA,I,TROPP)
 1000 END DO
      IF(LOP) GO TO 9000
! METRIC SECTION
      IF(LACC)NNMWTD=NM
      CALL BLKHDR(AA(KOBOUT),II(KNDBUF),AA(KOBBUF),NNMWTD)
      FACT=ONE/(ONE-VLITEC)
      IF(MTYPE.LT.METRIX) FACT=ONE
!...LOOP OVER THE MEASUREMENTS (METRIC)
      DO 8000 I=1,NM
      IF(LACC)GOTO 7900
      IF(LEDIT(I).OR.LOCCLT(I)) GO TO 8000
! USE A RESIDUAL WHICH HAS A SPEED OF LIGHT CONSISTENT WITH OBS
 7900 CONTINUE
      RES=RESID(I)*FACT
      OBSSIM=OBS(I)-RES
      IF(LCUTOT)OBSSIM=OBS(I)
      IF(LIONC) OBSSIM=OBS(I)
      CALL BLKOUT(AA(KOBBUF),AA(KOBOUT),II(KNDBUF),                     &
     &   OBSSIM,OBSSIM,OBSSIM,ONE,ONE,1  ,I)
 8000 END DO
      RETURN
 9000 CONTINUE
! OPTICAL SECTION
      IF(.NOT.LOP1) GO TO 9200
      JHOLD=KXTI
!...LOOP OVER THE MEASUREMENTS (1ST IN PAIR)
      DO 9100 I=1,NM
      AA(JHOLD+I)=OBS(I)-RESID(I)
      IF(LCUTOT) AA(JHOLD+I)=OBS(I)
 9100 END DO
      RETURN
 9200 CONTINUE
      IF(LACC)NNMWTD=NM
      CALL BLKHDR(AA(KOBOUT),II(KNDBUF),AA(KOBBUF),NNMWTD)
!...LOOP OVER THE MEASUREMENTS
      JHOLD=KXTI
      DO 9300 I=1,NM
      IF(LACC)GOTO 9250
      IF(LEDIT(I).OR.LOCCLT(I)) GO TO 9300
 9250 CONTINUE
      JIHOLD=JHOLD+I
      OBSSIM=OBS(I)-RESID(I)
      IF(LCUTOT) OBSSIM=OBS(I)
      CALL BLKOUT(AA(KOBBUF),AA(KOBOUT),II(KNDBUF),                     &
     &   AA(JIHOLD),OBSSIM,SUMCOR(I),ONE,ONE,1  ,I)
 9300 END DO
      RETURN
      END
