!$SMPLBL
      SUBROUTINE SMPLBL(PARML0)
!********1*********2*********3*********4*********5*********6*********7**
! SMPLBL           90/04/16            0000.0    PGMR - SBL
!
! FUNCTION: OUTPUTS E-MATRIX LABELS TO UNIT6 AND UNIT9 FOR PARTITIONED
!           E-MATRIX RUNS.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PARML0  I/O   A    E-MATRIX LABELS
!
! COMMENTS: IF PARTITIONING OF THE NORMAL MATRIX IS NOT REQUESTED OR
!           NEEDED THIS WILL BE DONE IN SUMMRY. THIS CODE IS A SUBSET
!           OF THE CODE IN SUMMRY.
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      DIMENSION PARML0(3,1)
      CHARACTER(8)      :: ARC, GLOBAL
      DATA ARC/'   ARC  '/,GLOBAL/' GLOBAL '/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!
! OUTPUT E-MATRIX LABELS TO UNIT6
      K1=1
      NARCPR=NPVAL0(IXARC)
      IF(NARCPR.LE.0) GO TO 8500
! ARC PARAMETER LABELS
      I1=IPVAL0(IXARC)
      I2=I1+NARCPR-1
      NLINE6=ILINE6+6
      IF(NLINE6.LE.MLINE6) GO TO 8100
      IPAGE6=IPAGE6+1
      NLINE6=8
      WRITE(IOUT6,20000) NARC,NGLOBL,IPAGE6
 8100 CONTINUE
      ILINE6=NLINE6-1
      WRITE(IOUT6,19000) ARC   ,EMTNUM
      DO 8300 J1=I1,I2,7
      J2=MIN(J1+6,I2)
      ILINE6=ILINE6+1
      IF(ILINE6.LE.MLINE6) GO TO 8200
      IPAGE6=IPAGE6+1
      ILINE6=8
      WRITE(IOUT6,20000) NARC,NGLOBL,IPAGE6
      WRITE(IOUT6,19100) ARC
 8200 CONTINUE
      WRITE(IOUT6,19200) K1,(PARML0(1,J),J=J1,J2)
      K1=K1+7
 8300 END DO
      K1=NARCPR+1
 8500 CONTINUE
      NGLBPR=NPVAL0(IXGLBL)
      IF(NGLBPR.LE.0) GO TO 8900
! GLOBAL PARAMETER LABELS
      I1=IPVAL0(IXGLBL)
      I2=I1+NGLBPR-1
      NLINE6=ILINE6+6
      IF(NLINE6.LE.MLINE6) GO TO 8600
      IPAGE6=IPAGE6+1
      NLINE6=8
      WRITE(IOUT6,20000) NARC,NGLOBL,IPAGE6
 8600 CONTINUE
      ILINE6=NLINE6-1
      WRITE(IOUT6,19000) GLOBAL,EMTNUM
      DO 8800 J1=I1,I2,7
      J2=MIN(J1+6,I2)
      ILINE6=ILINE6+1
      IF(ILINE6.LE.MLINE6) GO TO 8700
      IPAGE6=IPAGE6+1
      ILINE6=8
      WRITE(IOUT6,20000) NARC,NGLOBL,IPAGE6
      WRITE(IOUT6,19100) GLOBAL
 8700 CONTINUE
      WRITE(IOUT6,19200) K1,(PARML0(1,J),J=J1,J2)
      K1=K1+7
 8800 END DO
 8900 CONTINUE
!
      IF(.NOT.L9SUMP) GO TO 9900
!
! OUTPUT E-MATRIX LABELS TO UNIT9
      K1=1
      IF(NARCPR.LE.0) GO TO 9500
! ARC PARAMETER LABELS
      I1=IPVAL0(IXARC)
      I2=I1+NARCPR-1
      NLINE9=ILINE9+6
      IF(NLINE9.LE.MLINE9) GO TO 9100
      IPAGE9=IPAGE9+1
      NLINE9=8
      WRITE(IOUT9,20009) NARC,NGLOBL,IPAGE9
 9100 CONTINUE
      ILINE9=NLINE9-1
      WRITE(IOUT9,19009) ARC   ,EMTNUM
      DO 9300 J1=I1,I2,4
      J2=MIN(J1+3,I2)
      ILINE9=ILINE9+1
      IF(ILINE9.LE.MLINE9) GO TO 9200
      IPAGE9=IPAGE9+1
      ILINE9=8
      WRITE(IOUT9,20009) NARC,NGLOBL,IPAGE9
      WRITE(IOUT9,19109) ARC
 9200 CONTINUE
      WRITE(IOUT9,19209) K1,(PARML0(1,J),J=J1,J2)
      K1=K1+4
 9300 END DO
      K1=NARCPR+1
 9500 CONTINUE
      IF(NGLBPR.LE.0) GO TO 9900
! GLOBAL PARAMETER LABELS
      I1=IPVAL0(IXGLBL)
      I2=I1+NGLBPR-1
      NLINE9=ILINE9+6
      IF(NLINE9.LE.MLINE9) GO TO 9600
      IPAGE9=IPAGE9+1
      NLINE9=8
      WRITE(IOUT9,20009) NARC,NGLOBL,IPAGE9
 9600 CONTINUE
      ILINE9=NLINE9-1
      WRITE(IOUT9,19009) GLOBAL,EMTNUM
      DO 9800 J1=I1,I2,4
      J2=MIN(J1+3,I2)
      ILINE9=ILINE9+1
      IF(ILINE9.LE.MLINE9) GO TO 9700
      IPAGE9=IPAGE9+1
      ILINE9=8
      WRITE(IOUT9,20009) NARC,NGLOBL,IPAGE9
      WRITE(IOUT9,19109) GLOBAL
 9700 CONTINUE
      WRITE(IOUT9,19209) K1,(PARML0(1,J),J=J1,J2)
      K1=K1+4
 9800 END DO
 9900 CONTINUE
! SET PAGE LENGTH TO MAXIMUM SO THAT NEXT LINE WILL CAUSE PAGE FAULT
      ILINE6=MLINE6
      IF(.NOT.L9SUMP) RETURN
! SET PAGE LENGTH TO MAXIMUM SO THAT NEXT LINE WILL CAUSE PAGE FAULT
      ILINE9=MLINE9
      RETURN
19000 FORMAT(1X/' E-MATRIX',A8,'PARAMETER LABELS FOR E-MATRIX NO.',     &
     &   F18.1/1X /' SEQ. NO. ',7(' PARAMETER LABEL ')/1X )
19009 FORMAT(1X/' E-MATRIX',A8,'PARAMETER LABELS FOR E-MATRIX NO.',     &
     &   F18.1/1X /' SEQ. NO. ',4(' PARAMETER LABEL ')/1X )
19100 FORMAT(1X/' E-MATRIX',A8,'PARAMETER LABELS CONTINUED'/1X /        &
     & ' SEQ. NO. ',7(' PARAMETER LABEL ')/1X )
19109 FORMAT(1X/' E-MATRIX',A8,'PARAMETER LABELS CONTINUED'/1X /        &
     & ' SEQ. NO. ',4(' PARAMETER LABEL ')/1X )
19200 FORMAT(1X,I8,1X,7(F16.0,1X))
19209 FORMAT(1X,I8,1X,4(F16.0,1X))
20000 FORMAT('1ARC',I3,' SUMMARY CONTINUATION  FOR  GLOBAL ITERATION ', &
     &   I2,56X,'UNIT  6 PAGE NO.',I6)
20009 FORMAT('1ARC',I3,' SUMMARY CONTINUATION  FOR  GLOBAL ITERATION ', &
     &   I2, 4X,'UNIT  9 PAGE NO.',I4)
      END
