!$SMPRT2
      SUBROUTINE SMPRT2(AA,PMPP,NRMTOT,ATPA,SCRTCH,TBTWA,LPRTD,NRECS,   &
     & IUNTMT)
!********1*********2*********3*********4*********5*********6*********7**
! SMPART           85/10/08            0000.0    PGMR - TOM MARTIN
!                  84/02/27            0000.0    PGMR - D. ROWLANDS
!                  90/04/10                      PGMR - SBL
!
! FUNCTION:  CONTROLS THE ACCUMULATION OF PARTIAL DERIVATIVES THAT HAVE
!            BEEN WRITTEN TO DISK (BECAUSE OF MATRIX PARTITIONING) INTO
!            THE PARTITIONED NORMAL MATRIX. THIS ROUTINE EXPLOITS
!            MULTI-PROCESSING. EACH MATRIX PARTITION IS DIVIDED INTO
!            A NUMBER OF SUB PARTITIONS WHICH IS EQUAL TO THE NUMBER
!            OF PROCESSORS REQUESTED,
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    DYNAMIC ARRAY FOR REAL DATA
!   PMPP     I    A    ARRAY TO HOLD PARTIALS OFF OF DISK
!                      NECCESSARY) FOR EACH MEASUREMENT.
!   NRMTOT   I    S    MAXIMUM DIMENSION OF FULL NORMAL MATRIX
!   ATPA     O    A    NORMAL MATRIX ARRAY
!   SCRTCH   I    A    SCRATCH ARRAY
!   TBTWA    I    A    NOT USED (KEPT IN ARGUMENT LIST SO THAT ARGUMENT
!                      LIST WILL BE THE SAME AS SMPART
!   LPRTD    I    S    TRUE WHEN EMAT PRINTED ON UNIT 6
!   NRECS   I/O   S    NUMBER OF RECORDS CURRENTLY WRITTEN TO EMAT FILE
!   IUNTMT   I    S    EMAT UNIT NUMBER
!
! COMMENTS:  THIS ROUTINE IS BASED ON SMPART. IT IS CALLED WHEN
!            NPROCS>1 AND THERE ARE NO EBIASES. THIS ROUTINE SHOULD
!            EXPLOIT MULTIPLE PROCESSORS BETTER THAN SMPART.
!            THIS ROUTINE WILL NOT WORK WITH EBIASES
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
! THE SIZE OF MEPARX MUST BE CONSISTENT WITH THE BTWB & DELTA ARRAYS
      PARAMETER ( MEPARX = 4 )
      PARAMETER ( ZERO   = 0.0D0 )
!
      COMMON/CEBGLB/MEPARM,MEDIM ,MEBIAS,MBIASE,NEBGRP,IEBGRP(4),NXCEBG
      COMMON/CLVIEW/LNPRNT(18),NXCLVI
      COMMON/CPARTI/MAXLP ,KORSIZ,MAXWRK,                               &
     &              IUNTP1,IUNTP2,IUNTPF,ISIZPF,IRECPF,NRECPF,          &
     &              NPDONE,NP1   ,NP2   ,NRECND,NPDIM ,NXPARI
      COMMON/CPARTL/LPART ,LPARTI,NXPARL
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      DIMENSION AA(1),PMPP(NRMTOT),ATPA(1),SCRTCH(NRMTOT)
! BTWB AND DELTA ARE LOCAL ARRAYS IN THIS ROUTINE
! DIMENSION     BTWB(MEDIM),DELTA(MEPARM),TBTWA(NRMTOT,MEPARM)
      DIMENSION BTWB(10)   ,DELTA(4)     ,TBTWA(NRMTOT,MEPARM)
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
      NRECSV=NRECPF
      IF(IUNTPF.EQ.IUNTP1) NRECSV=IRECPF
      NRECND=IRECPF
      IUNTP2=IUNTPF
      NPAR0=NP2
      LFIRST=.FALSE.
      LAST=NPDONE.GE.NRMTOT
      ENDFILE IUNTPF
      REWIND IUNTPF
 1000 CONTINUE
! A MEMORY PARTITION IS COMPLETE - OUTPUT THIS PARTITION TO THE EMATRX
! FILE THIS WILL BE ROWS NP1 TO NP2
      CALL EMTPDT(ATPA(1),AA(KSUM2),LPRTD,AA(KPRML0),NRECS,IUNTMT)
! CLEAR MEMORY USED FOR ATWA MATRIX
      CALL CLEARA(ATPA(1),MAXWRK)
      IF(LAST) GO TO 9100
      NRECPF=NRECSV
      CALL EPART(NRMTOT,LFIRST,LAST)
      ISP0=NP1-1
      IL0=NRMTOT-ISP0
      NDM=NRMTOT-NP1+1
      ILAST=NP2-NP1+1
      CALL GETPPC(NDM,ILAST)
      CALL SMPRT3(PMPP,ATPA,SCRTCH)
      GO TO 1000
 9100 CONTINUE
! WRITE OUT E-MATRIX LABELS IF REQUESTED ON PRNTVU CARD
      IF(.NOT.LNPRNT(12)) CALL SMPLBL(AA(KPRML0))
!     ....f90 on Sun did not like IUNTPF as loop index
!     ....and also in common block         ! jjm 9/98
                                     ! jjm 9/98
      DO 9200 IUNTPFX=IUNTP1,IUNTP2
                        ! jjm 9/98
      CLOSE(IUNTPFX)
 9200 CONTINUE
! END AND REWIND EMAT FILE
      ENDFILE IUNTMT
      REWIND IUNTMT
      WRITE(IOUT6,80100) NRECS,IUNTMT,EMTNUM
      RETURN
!
 9800 CONTINUE
      WRITE(IOUT6,98000) MEPARM,MEPARX
      STOP 16
!
 9900 CONTINUE
      WRITE(IOUT6,99000)
      STOP 16
!
80100 FORMAT('0',9X,I5,' RECORDS OUTPUT ON UNIT ',I2,                   &
     &   ' FOR E-MATRIX NUMBER  ',F16.0)
98000 FORMAT(' **SMPART**  MEPARM(',I11,') FROM E-BIAS CORRECTIONS ',   &
     &   'RECORD IS INCONSISTENT WITH LOCAL DIMENSION(',I2,')')
99000 FORMAT(' **SMPART**  UNEXPECTED E.O.F. ENCOUNTERED WHILE READING',&
     &   ' E-BIAS PARTIALS IN PARTRD.')
      END
