!$SMSTAT
      SUBROUTINE SMSTAT(TMEAN ,TRMS  ,WTMEAN,WTRMS ,WTRND ,PRVRAT,      &
     &    TYMEAN,TYPRMS,WTMTYP,WTYRMS,NOBST ,NOBSWT,NOBSTY,NOBWTY,      &
     &    LOGPRV,RESID ,NM    ,RATIOW,RATIOE,NMWTD ,MTYPE ,ISTATS)
!********1*********2*********3*********4*********5*********6*********7**
! SMSTAT           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:  SUMS THE OBSERVATION RESIDUAL STATISTICS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   TMEAN   I/O   A    RESIDUAL MEANS GROUPED BY STATIONS
!   TRMS    I/O   A    RESIDUAL RMS GROUPED BY STATIONS
!   WTMEAN  I/O   A    RESIDUAL WEIGHTED MEANS GROUPED BY STATION
!   WTRMS   I/O   A    RESIDUAL WEIGHTED RMS GROUPED BY STATION
!   WTRND   I/O   A    RESIDUAL WEIGHTED RANDOM NORMAL DEVIATION ARRAYS
!   PRVRAT  I/O   A    ARRAY FOR SAVING PREVIOUSLY COMPUTED RATIO
!   TYMEAN  I/O   A    RESIDUAL MEANS GROUPED BY MEASUREMENT TYPES
!   TYPRMS  I/O   A    RESIDUAL RMS GROUPED BY MEASUREMENT TYPES
!   WTMTYP  I/O   A    RESIDUAL WEIGHTED MEANS GROUPED BY MEASUREMENT
!                      TYPES
!   WTYRMS  I/O   A    RESIDUAL WEIGHTED RMS GROUPED BY MEASUREMENT
!                      TYPES
!   NOBST
!   NOBSWT
!   NOBSTY
!   NOBWTY
!   LOGPRV
!   RESID    I    A    RESIDUAL ARRAY
!   NM       I    S    NUMBER OF MEASUREMENTS IN THIS LOGICAL BLOCK
!   RATIOW
!   RATIOE
!   NMWTD
!   MTYPE    I    S    MEASUREMENT TYPE
!   ISTATS   I    S    NUMBER OF UNIQUE TRACKING/MTYPE CONFIGURATION
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CSTATA/RMSTOT,RMSEDT,RMSGLB
      COMMON/CSTATS/MSTATS,MTYPES,NXCSTT
      DIMENSION TMEAN (MSTATS),TRMS  (MSTATS)
      DIMENSION WTMEAN(MSTATS),WTRMS (MSTATS)
      DIMENSION WTRND (MSTATS),PRVRAT(MSTATS)
      DIMENSION NOBST (MSTATS),NOBSWT(MSTATS)
      DIMENSION LOGPRV(MSTATS)
      DIMENSION TYMEAN(MTYPES),TYPRMS(MTYPES)
      DIMENSION WTMTYP(MTYPES),WTYRMS(MTYPES)
      DIMENSION NOBSTY(MTYPES),NOBWTY(MTYPES)
      DIMENSION RESID (NM    ),RATIOW(    1 ),RATIOE(    1 )
      DATA ZERO/0.0D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!***** DEBUG *****
!     PRINT 12345,NM,NMWTD,MTYPE,ISTATS,MTYPES,MSTATS
!2345 FORMAT(' ** SMSTAT **  NM    ,NMWTD =',2I12/
!    1                  15X,'MTYPE ,ISTATS=',2I12/
!    2                  15X,'MTYPES,MSTATS=',2I12)
!     PRINT 12346,RESID
!2346 FORMAT(' ** SMSTAT **  RESID ='/(1X,10G13.5))
!     PRINT 12347,RATIOW
!2347 FORMAT(' ** SMSTAT **  RATIOW='/(1X,10G13.5))
!     PRINT 12348,RATIOE
!2348 FORMAT(' ** SMSTAT **  RATIOE='/(1X,10G13.5))
!***** END DEBUG *****
      SUM   =ZERO
      SUMSQ =ZERO
      DO 1000 N=1,NM
      SUM   =SUM   + RESID (N)
      SUMSQ =SUMSQ + RESID (N)*RESID (N)
 1000 END DO
      TMEAN (ISTATS)=TMEAN (ISTATS)+SUM
      TRMS  (ISTATS)=TRMS  (ISTATS)+SUMSQ
      NOBST (ISTATS)=NOBST (ISTATS)+NM
      TYMEAN(MTYPE )=TYMEAN(MTYPE )+SUM
      TYPRMS(MTYPE )=TYPRMS(MTYPE )+SUMSQ
      NOBSTY(MTYPE )=NOBSTY(MTYPE )+NM
!***** DEBUG *****
!     PRINT 22345,TMEAN
!2345 FORMAT(' ** SMSTAT **  TMEAN ='/(1X,10G13.5))
!     PRINT 22346,TRMS
!2346 FORMAT(' ** SMSTAT **  TRMS  ='/(1X,10G13.5))
!     PRINT 22347,NOBST
!2347 FORMAT(' ** SMSTAT **  NOBST ='/(1X,10G13.5))
!     PRINT 32345,TYMEAN
!2345 FORMAT(' ** SMSTAT **  TYMEAN='/(1X,10G13.5))
!     PRINT 32346,TYPRMS
!2346 FORMAT(' ** SMSTAT **  TYPRMS='/(1X,10G13.5))
!     PRINT 32347,NOBSTY
!2347 FORMAT(' ** SMSTAT **  NOBSTY='/(1X,10G13.5))
!***** END DEBUG *****
      IF(NMWTD.LE.0) RETURN
      SUMEDT=ZERO
      SUM   =ZERO
      SUMSQ =ZERO
      SUMRND=ZERO
      PREV  =PRVRAT(ISTATS)
      IF(.NOT.LOGPRV(ISTATS)) PREV  =RATIOW(1)
      DO 2000 N=1,NMWTD
      SUMEDT=SUMEDT+RATIOE(N)**2
      RATIO =RATIOW(N)
      SUM   =SUM   + RATIO
      SUMSQ =SUMSQ + RATIO *RATIO
      SUMRND=SUMRND+(RATIO -PREV  )**2
      PREV  =RATIO
 2000 END DO
      PRVRAT(ISTATS)=RATIOW(NMWTD )
      LOGPRV(ISTATS)=.TRUE.
      RMSEDT=RMSEDT+SUMEDT
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
!            write ( 6, * ) 'SMSTAT: WTYRMS(MTYPE)=', WTYRMS(MTYPE), &
!    &                              ' SUMSQ=',SUMSQ
! %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      WTMEAN(ISTATS)=WTMEAN(ISTATS)+SUM
      WTRMS (ISTATS)=WTRMS (ISTATS)+SUMSQ
      WTRND (ISTATS)=WTRND (ISTATS)+SUMRND
      NOBSWT(ISTATS)=NOBSWT(ISTATS)+NMWTD
      WTMTYP(MTYPE )=WTMTYP(MTYPE )+SUM
      WTYRMS(MTYPE )=WTYRMS(MTYPE )+SUMSQ
      NOBWTY(MTYPE )=NOBWTY(MTYPE )+NMWTD
!***** DEBUG *****
!     PRINT 42345,WTMEAN
!2345 FORMAT(' ** SMSTAT **  WTMEAN='/(1X,10G13.5))
!     PRINT 42346,WTRMS
!2346 FORMAT(' ** SMSTAT **  WTRMS ='/(1X,10G13.5))
!     PRINT 42347,NOBSWT
!2347 FORMAT(' ** SMSTAT **  NOBSWT='/(1X,10G13.5))
!     PRINT 52345,WTMTYP
!2345 FORMAT(' ** SMSTAT **  WTMTYP='/(1X,10G13.5))
!     PRINT 52346,WTYRMS
!2346 FORMAT(' ** SMSTAT **  WTYRMS='/(1X,10G13.5))
!     PRINT 52347,NOBWTY
!2347 FORMAT(' ** SMSTAT **  NOBWTY='/(1X,10G13.5))
!***** END DEBUG *****
      RETURN
      END
