!$SNAPGN
      SUBROUTINE SNAPGN(AA,II,LL,INDSTA,INDSAT,INDSET,INPSTA,INPSAT,    &
     &   LELEVS,ILCORR,LSNAP1,NSNAPB,NSNAPX,ID1,ID2,NB1,NB2,NBT,        &
     &   NBC,NM1,NM2,INDX0,KEY1,KEY2,XLAT,XLON,XS,XN,XW,XE,LGRN,        &
     &   MAXD,PPARM,                                                    &
     &   PXEPXI,PXEPA,PXEPA2,ACOEF,ACOEF2,ACOEF3,BCOEF,BCOEF2,          &
     &   AUX1,TIME1,DDDA,DIST,DIST0,IDLAS,IOBSC,TMSE,MAXNM,MADJST,      &
     &   MAXLAS,NPDEG,IAVP,NAVP,DCDP,KEY,MJDLAS,ACOF4)
!********1*********2*********3*********4*********5*********6*********7**
! SNAPGN           00/00/00            0000.0    PGMR - ?
!
! FUNCTION:  CONTROL SNAPSHOT CROSSOVER PROCESSING
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   INDSTA   O    A    FOR A GIVEN INTERNAL STA NO (1,2,3) INDSTA
!                      GIVES THE ACTUAL LOCATION IN THE STATION
!                      RELATED ARRAYS FOR THIS STATION.
!                      (EG.   STA NO=ISTANO(INDSTA(1,2,OR 3))
!   INDSAT   O    A    FOR A GIVEN INTERNAL SAT NO (1,2,3) INDSAT
!                      GIVES THE ACTUAL LOCATION IN THE SATELLITE
!                      RELATED ARRAYS FOR THIS SATELLITE.
!                      (EG.   SAT ID=ISATNO(INDSAT(1,2,OR 3))
!   INDSET   O    A    FOR A GIVEN INTERNAL SATELLITE NUMBER INDSET TELL
!                      WHICH SAT SET THAT THE GIVEN SAT BELONGS TO.
!   INPSTA   O    A    POINTER ARRAY THAT RELATES THE INTERNAL STATION
!                      NUMBER (1,2,3) TO THE STATIONS DEFINED IN THE
!                      DATA HEADER RECORDS (N=1,2,3). (EG.
!                      ISTAP=INPSTA(1) WOULD TELL WHICH OF THE THREE
!                      POSSIBLE STATIONS DEFINED IN THE DATA HEADER
!                      RECORDS PERTAINED TO INTERNAL STATION NO. 1)
!   INPSAT   O    A    POINTER ARRAY THAT RELATES THE INTERNAL SATELLITE
!                      NUMBER (1,2,3) TO THE SATELLITES DEFINED IN THE
!                      DATA HEADER RECORDS (N=1,2,3). (EG.
!                      ISATP=INPSAT(1) WOULD TELL WHICH OF THE THREE
!                      POSSIBLE SATELLITES DEFINED IN THE DATA HEADER
!                      RECORDS PERTAINED TO INTERNAL SATELLITE NO. 1)
!   LELEVS  I/O   A    INDICATES WHICH ELEVATION ANGLES NEED TO BE
!                      COMPUTED FOR THE THREE POSSIBLE STATION SATELLITE
!                      CONFIGURATIONS DEFINED IN THE BLOCK HEADER
!                      RECORDS
!
! COMMENTS: THE CONTOL OF THE SNAPSHOT CROSSOVERS IS ACCOMPLISHED MAINLY
!           THROUGH THE USE OF AN EXTERAL FILE. EVENTIALLY, THE INFORMATION
!           ON THAT FILE WILL BE RELOCATED TO THE INTERFACE FILE AND
!           LOADED INTO ARRAYS.
!
!           INFORMATION ON THE EXTERAL FILE:
!
!                   (1) NUMBER OF SATELLITES
!                   (2) ID OF EACH SATELLITE AND ASSOCIATED ENDTIME
!                   (3) NUMBER OF SNAPSHOT CROSSOVERS
!                    (4) FOR EACH SNAPSHOT CROSSOVER:
!                         THE TWO KEYS
!                         THE CENTER CROSSOVER PT
!                         THE RECTANGLE BOUNDRY
!                          SATELLITE #1 ID AND # LASER BLOCKS
!                          SATELLITE #2 ID AND # LASER BLOCKS
!
!           THIS FIRST VERSION WITH THE EXTERNAL FILE CAN NOT ADJUST
!           PARAMETERS
!
!
! NOTE!!!! NEED TO ADD PROTECTION FOR ARRAYS WITH DIMENSIONS:
!
!                 MAXH,MAXR,MAXD,MXPARH
!
!
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/NSEGSC/NSEGM(80)
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
!
!                    INDICES TO SATELLITES IN A BLOCK WITH SAVED
!                    INTEGRATION INFORMATION.
!              ISTOS1 - INDEX TO THE FIRST SATELLLITE
!              ISTOS2 - INDEX TO THE SECOND SATELLLITE
!              ISTOS3 - INDEX TO THE THIRD SATELLLITE

      COMMON/HOLDQ/SUMXO(3,2,200,3),SUMXX(8000,3,2,200,3),QINTQ
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CBLOKA/FSECBL,SIGNL ,VLITEC,SECEND,BLKDAT(6,4),DOPSCL(5,4)
      COMMON/CBLOKI/MJDSBL,MTYPE ,NM    ,JSTATS,NPSEG ,JSATNO(3),ITSYS ,&
     &       NHEADB,NELEVS,ISTAEL(12),INDELV(3,4),JSTANO(3),ITARNO,     &
     &       KTARNO
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CESTML/LNPNM ,NXCSTL
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CINTI/IBACK ,IBACKV,IORDER,IORDRV,NOSTEP,NOCORR,           &
     &      NSAT  ,N3    ,NEQN  ,NEQN3 ,NH    ,NHV   ,NSTEPS,           &
     &      NSTEPV,ICPP  ,ICPV  ,ICCP  ,ICCV  ,ICCPV ,ICCVV ,           &
     &      ISUMX ,IXDDOT,ISUMPX,IPXDDT
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/COFFST/JXYZOF(2),JSADLY(2),JSTDLY(2),JXYZCG(2,2),          &
     &              MJDFCG(2,2),JXYOF2(2),JEXTOF(2),JXYOF3(2)
      COMMON/COFSTL/LOFEXT(2)
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/CPMPA /KTMPAR(3)    ,KMBPAR(2)    ,KRFPAR(2)    ,          &
     &              KAEPAR,KFEPAR,KFPPAR,KVLPAR,KETPAR(2,2)  ,          &
     &              KPMPAR,KUTPAR,KSTPAR(3,4)  ,NADJST       ,          &
     &              NDIM1 ,NDIM2 ,NXDIM1,NXDIM2
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      COMMON/CLPRNR/LPR9NR(24),LPRNRM(24,3)
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
      COMMON/DELOFF/NOFFST,NSATDL,NSTADL,NCGMAS,NXDELO
      COMMON/ELRTNX/NELVS,NELVC,IELSTA(6),IELSAT(6),IELSA2(6),          &
     &       INDXEL(5,4)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/OCCLTL/LOCCLT(200),LMSHD(200)
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/RAPIDI/LINTF,LBUFOP
      COMMON/XOVERS/NRXTOT,NXBLK,NUSIDE,NDEGX2,NDEGXX,NUCON,ITERNU,     &
     &              IPEDIT,IDEDIT,NXXOVR
      COMMON/SNAPXL/LXRSET
!
      DIMENSION AA(1),II(1),LL(1),INDSTA(3,4),INDSAT(3,4),INDSET(3,4),  &
     &   LELEVS(3,4),INPSTA(3,4),INPSAT(3,4),ILCORR(5,4)
      DIMENSION FSC(1),RINDEX(1)
!
!
! FOR SNAPSHOT CROSSOVERS   TYPE 2
!
!
      DIMENSION PXEPXI(1)
      DIMENSION PXEPA(NADJST,MAXNM,3,MAXLAS,2),PXEPA2(NADJST,MAXNM,3,2)
      DIMENSION ACOEF(MAXD,MAXNM,3,MAXLAS,2),ACOEF2(3,3,MAXLAS,2)
      DIMENSION ACOEF3(MAXD,4,MAXLAS,2)
      DIMENSION BCOEF(MAXD,MAXNM,3,2),BCOEF2(3,3,2)
      DIMENSION AUX1(MAXNM,5,MAXLAS,2),TIME1(1)
      DIMENSION DDDA(1)
      DIMENSION DIST(MAXLAS,MAXLAS),DIST0(MAXLAS,MAXLAS)
      DIMENSION IDLAS(MAXLAS,2),KSAT(2),IDSAT(2)
      DIMENSION IOBSC(MAXLAS,2)
      DIMENSION TMSE(MAXNM,MAXLAS,2)
      DIMENSION IAVP(MADJST,MAXLAS,2),NAVP(MAXLAS,2)
      DIMENSION DCDP(MAXD,MADJST,3,MAXLAS,2)
      DIMENSION FSQ(11)
      DIMENSION MJDLAS(MAXLAS,2)
      DIMENSION ACOF4(1)
!
      DATA XMPP/75.D0/
      DATA RBODY/6378000.D0/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      DATA NMF/5/
      DATA NPDEGF/3/
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      data kentry/0/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
!!!   IF(NINNER.EQ.1) RETURN
      kentry=kentry+1
      if(kentry.eq.1) then
      DO JJ=1,20
      NSEGM(JJ)=1
      ENDDO
      endif
!
!
      LTYPE1=.FALSE.
      LTYPE2=.TRUE.
      ITERNU=0
      MAXD2=MAXD*MAXD
      IF(NSNAPB.EQ.1) THEN
! RESET SATELITE INDICES
        ISTOS1=0
        ISTOS2=0
        ISTOS3=0
        ISTLST=0
!
        READ(51) NSATSN
        DO I=1,NSATSN
          READ(51) ID,ENDTIM
          READ(51) ID
          DO K=1,NSATA
             ISAT=K
             IF(II(KISATN-1+K).EQ.ID) GO TO 10
          ENDDO
          WRITE(6,6000)
          WRITE(6,6001) ID
          STOP
 10       CONTINUE
           WRITE(6,78911) ENDTIM,ID
78911     FORMAT(' INTEGRATION ENDTIME: ',F15.3,' SATID ',I10)

! This might be necessary if ONLY crossover measurements are in the run.

! INTEGRATE OUT TO END TIME SO FAST INTEGRATION CAN TAKE PLACE
!          MJDS=ENDTIM
!          FSC(1)=ENDTIM-DBLE(MJDS)
!          CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),ISAT)
!          CALL ORBIT(MJDS,FSC,AA(KS),1,II(KINDH),II(KNMH),          &
!     &               II(KMJDSC),AA(KFSEC),II(KMJDSV),AA(KFSECV),    &
!     &               LL(KLSETS),II(KIPXPF),II(KIVSAT),1,II(KNMAX),  &
!     &               II(KNTOLD),AA(KXSM),AA(KPXPFM),.TRUE.,.FALSE., &
!     &               II(KPLPTR),II(KPANEL),II(KNMOVE),              &
!     &               AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),       &
!     &               LL(KSETDN),AA,II,LL)
        ENDDO
!
! AT THIS POINT REGULAR INTEGRATION IS COMPLETE SWITCH OVER TO RAPID
! INTERPOLATION
!
!       LINTF=.TRUE.
        READ(51) NSNAPX
        WRITE(6,78912)
78912   FORMAT(' SNAPGN INTEGRATION COMPLETE ')
        WRITE(6,78913) NSNAPX
78913   FORMAT(' ',I20,' SNAPSHOTS WILL BE PROCEESED')
        WRITE(63,70000) NSNAPX
      ENDIF
!
!
! ON THE FIRST BLOCK OF A SNAPSHOT CROSSOVER
!
!
      IF(LSNAP1) THEN
! This might not be right for always but try
        INTOSP=0
        LXRSET=.TRUE.
        PPARM=-10.D0
        IF(NPVAL0(IXRSEP).GE.1) THEN
          IP=IPVAL(IXRSEP)
          PPARM=AA(KPRMV-1+IP)
        ENDIF
        READ(51) KEY1,KEY2
        READ(51) KEY1,NB1
        READ(51) KEY2,NB2
        READ(51) IDIF1,IDIF2
!
        WRITE(6,78915) KEY1,KEY2,NB1,NB2
78915   FORMAT(' NEW SNAPSHOT ; KEY1 &2 ; NB1 & NB2 ',4I12)
!
        WRITE(63,70000) KEY1,KEY2,NB1,NB2
!
!
        NZQ=MAXD*MADJST*3*MAXLAS*2
        DO IQP=1,NZQ
          DCDP(IQP,1,1,1,1)=0.D0
        ENDDO
        NBC=1
        NBT=NB1+NB2
        INDX0=0
!
!
!
!
      ELSE
        NBC=NBC+1
      ENDIF
!
      IF(KEY.NE.KEY1.AND.KEY.NE.KEY2) THEN
        WRITE(6,88912) KEY,KEY1,KEY2
88912   FORMAT(' EXECUTION TERMINATING MISMATCH ;KEY ON DAT KEYS ',3I12)
        STOP
      ENDIF
!
!!!!! WRITE(6,78923) NBC,NBT,NM
78923 FORMAT(' PROCESSING BLOCK # ',I5,' OF ',I5,' IN CROSSOVER; NM',I4)
!     if(NBC.EQ.7) stop
!
!
! ENDIF FOR  THE FIRST BLOCK OF A SNAPSHOT CROSSOVER
!
!
      LSNAP1=.FALSE.
      ISAT12=1
      IF(NBC.GT.NB1) ISAT12=2
      ITQ=NBC-NB1
      IF(ITQ.EQ.1) QINTQ=1.D0
      IF(NBC.EQ.1) QINTQ=1.D0
      KSAT(ISAT12)=INDSAT(1,1)
      IDSAT(ISAT12)=II(KISATN+INDSAT(1,1)-1)
!     IF(KEY1.GT.10000) GO TO 999
      IF(ISAT12.EQ.1) MJDSBL=MJDSBL-IDIF1
      IF(ISAT12.EQ.2) MJDSBL=MJDSBL-IDIF2
      ITEST=NBC-NB1
      IF(ITEST.EQ.1) THEN
         NM1=INDX0
         INDX0=0
      ENDIF
      NBQ=NBC
      IF(NBQ.GT.NB1) NBQ=NBQ-NB1
      IF(NBC.EQ.NBT) NM2=INDX0+NM
      IF(NM.GE.MAXNM) THEN
         WRITE(6,6050) NBC
         WRITE(6,6051)
         WRITE(6,6052) NM,MAXNM
         STOP
      ENDIF
!
!
!
!
!
!
! IN CASE OF SIMULATION OF INTERPLANETRY,INITIALIZE LOCCLT TO FALSE
      NELVS=0
      LSIMX=LSIMDT
      IF(ICBDGM.EQ.ITBDGM) LSIMX=.FALSE.
      IF(LSIMX) THEN
      DO 40 I=1,NM
      LOCCLT(I)=.FALSE.
      LMSHD(I)=.FALSE.
   40 END DO
      ENDIF
!
! SET DIMENSIONS OF PXPF
      NEQN=II(KNEQN-1+INDSET(1,1))
      NDIM1=NEQN
      NDM1=NADJST
      NDIM2=3
      NDIM3=NM
      NDM2=MAXNM
      IF(LNPNM) GO TO 100
      NDIM1=NM
      NDM1=MAXNM
      NDIM2=NEQN
      NDM2=NADJST
      NDIM3=3
  100 CONTINUE
! WRITE OUT BINARY LENGTHS RECORD
      IF(LBINRI) CALL BINLEN(AA,II)
!
!
!
! CHECK FOR APPLICABLE ALTIMETER ANTENNA OFFSETS
         JXYZOF(1)=KFRQOF
         JXYOF2(1)=KFRQOF
         JXYOF3(1)=KFRQOF
         JSADLY(1)=KFRQSA
         JSTDLY(1)=KFRQST
         JXYZCG(1,1)=KFRQOF
         JXYZCG(2,1)=KFRQOF
         MJDFCG(1,1)=0
         MJDFCG(2,1)=0
         LOFEXT(1)=.FALSE.
! GET SATELLITE ID BY USING INTERNAL SAT INDEX
         ISATID=II(KISATN+INDSAT(1,1)-1)
         IF(NOFFST.GT.0) THEN
          CALL IDANT(ISATID,0,.FALSE.,IANT)
                       CALL OFFDEL(ISATID,0,BLKDAT(3,1),                &
     &      II(KISATO),II(KISATD),II(KISATC),II(KISTAD),                &
     &      AA(KFRQOF),AA(KFRQSA),AA(KFRQST),II(KMJDCG),JICOOR,         &
     &      JXYZOF(1),JSADLY(1),JSTDLY(1),JXYZCG(1,1),MJDFCG(1,1),      &
     &      IANT,ii(KANTOF),JXYOF2(1),LL(KNSCID),II(KIANTO),LL(KEXTOF), &
     &      LOFEXT(1),.TRUE.,II,FRQLNK,1,AA,JXYOF3(1))
         ENDIF
         IDLAS(NBQ,ISAT12)=INT(BLKDAT(4,1))
         IDLAS(NBQ,ISAT12)=MOD(IDLAS(NBQ,ISAT12),10)
      CALL ATPARP(AA,II,LL,99,INDSAT(1,1),NM,MJDSBL,AA(KFSECS(1,1)),    &
     &            II(KATSAT),II(KKVLAS),AA(KATIME))
! EVENT TIMES
         JFSECN=KFSECS(1,1)
         JFSECM=KFSECS(2,1)
         JFSECK=KFSECS(3,1)
         JFSECO=KFSECS(4,1)
! OBSERVATION CORRECTIONS RECORD
         JOBMET=KOBCOR(1,1)
         JOCTPC=KOBCOR(2,1)
         JOCDRY=KOBCOR(3,1)
         JOCWET=KOBCOR(4,1)
         IF(LPRNRM(5,1)) JOCWET=KOBCOR(5,1)
         JOCION=KOBCOR(6,1)
! OCEAN DYNAMICS RECORD
         JETIDE=KOBCOR(2,4)
         JOTIDE=KOBCOR(3,4)
         IF(LPRNRM(13,1)) JOTIDE=KOBCOR(4,4)
         JSST=KOBCOR(5,4)
! LOCATIONS DATA RECORD
         JGEOID=KOBCOR(4,7)
         JUNQIN=KOBCOR(7,7)
         JRLAND=KOBCOR(8,7)
!
!
      NUCONH=NUCON
      NUCON=NM
      LXGOUT=.FALSE.
      LDIOUT=.FALSE.
!
!
      LPROC=.FALSE.
!      IF(KEY1.GT.300) GO TO 2000
      IF(NM.LT.NPDEG) GO TO 2000
      LPROC=.TRUE.
!      IF(NINNER.LT.4) THEN
!        LPROC=.FALSE.
!     GO TO 2000
!      ENDIF
!
!
!
        IF(QINTQ.GT.0.D0) THEN
          MJDS=MJDSBL
          FSQ(1)=AA(JFSECN)-5.D0
          ENDQ=AA(JFSECN-1+NM)+5.D0
        DO IQP=2,11
           NMQ=IQP
         FSQ(IQP)=FSQ(1)+DBLE(IQP-1)*5.D0
         IF(FSQ(IQP).GE.ENDQ) GO TO 7777
          ENDDO
 7777     CONTINUE
!
      IF(INTOSP.EQ.0) INTOSP=1
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
!
      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),KSAT(ISAT12),         &
     &   KNSTEPS,NEQNI,II(KSGMNT-1+IRET),                               &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),IRET,MJDS,FSQ(1),         &
     &   FSQ(11),11,AA,II)

        LXRSET=.FALSE.

      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      ENDIF
          CALL ORBIT(MJDS,FSQ,AA(KS),NMQ,II(KINDH),II(KNMH),        &
     &               II(KMJDSC),AA(KFSEC),II(KMJDSV),AA(KFSECV),    &
     &               LL(KLSETS),II(KIPXPF),II(KIVSAT),1,II(KNMAX),  &
     &               II(KNTOLD),AA(KXSM),AA(KPXPFM),.FALSE.,.FALSE.,&
     &               II(KPLPTR),II(KPANEL),II(KNMOVE),              &
     &               AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),       &
     &               LL(KSETDN),                                    &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)
        ENDIF
      QINTQ=-1.D0
!
!
!
      WRITE(63,70000) ISAT12,IDLAS(NBQ,ISAT12),MJDSBL,NM
      MJDLAS(NBQ,ISAT12)=MJDSBL
      WRITE(6,18912) ISAT12,NBQ,IDLAS(NBQ,ISAT12),MJDSBL,NM
18912 FORMAT(' SNAPGN; ISAT12,NBQ,IDLAS(NBQ,ISAT12),MJDSBL,NM ',5I14)
      CALL SNAPF2(AA,II,LL,LNADJ,MJDSBL,AA(JFSECN),AA(JFSECM),         &
     &           AA(JFSECK),NM,INDSAT(1,1),INDSET(1,1),AA(KOBS),       &
     &           AA(KXTN),AA(KXSM),AA(KXTK),AA(KVTN),AA(KVTK),AA(KXSJ),&
     &           AA(KTHETG),AA(KCOSTH),AA(KSINTH),AA(JOBMET),          &
     &           AA(JOCDRY),AA(JOCWET),AA(JOCION),AA(JOTIDE),          &
     &           AA(KX2SCR),LNPNM,LDIOUT,LXGOUT,AA(KPMATT),AA(KXHOLD), &
     &           AA(JSST),RINDEX,AA(KSATLT),AA(KSATLN),AA(KSATH),      &
     &           AA(KXY2),AA(KZT),AA(KRT),AA(KRA),AA(KEXTRA),          &
     &           AA(KATROT),AA(KXUTDT),AA(JUNQIN),AA(JETIDE),          &
     &           AA(JRLAND),MAXD,NPDEG,MADJST,MAXNM,IOBSC(NBQ,ISAT12), &
     &           TMSE(1,NBQ,ISAT12),PXEPXI,PXEPA(1,1,1,NBQ,ISAT12),    &
     &           ACOEF(1,1,1,NBQ,ISAT12),ACOEF2(1,1,NBQ,ISAT12),       &
!!!! &           ACOEF3(1,1,NBQ,ISAT12),                               &
!!!! &           AUX1,TIME1,NADJST,NDIM1,NDIM2,NDIM3,                  &
     &           ACOEF3(1,1,NBQ,ISAT12),AUX1(1,1,NBQ,ISAT12),          &
     &           TIME1,NADJST,NDIM1,NDIM2,NDIM3,                       &
     &           IAVP(1,NBQ,ISAT12),NAVP(NBQ,ISAT12),                  &
     &           DCDP(1,1,1,NBQ,ISAT12),ISATID,MTYPE)
!
      NUCON=NUCONH
      INDX0=INDX0+NM
 2000 CONTINUE
      IF(NBC.EQ.NBT) THEN
          IF(LPROC) THEN
          CALL EXDYN3(AA,II,LL,NPDEG,AA(KPMPA),PXEPA,PXEPA2,ACOEF,      &
     &                ACOEF2,ACOEF3,BCOEF,BCOEF2,DDDA,NDM1,NDM2,IOBSC,  &
     &                TMSE,DIST,DIST0,MAXLAS,MAXD,MAXNM,NB1,NB2,        &
     &                NADJST,LNPNM,KSAT,IDSAT,IDLAS,KEY1,KEY2,          &
     &                MADJST,IAVP,NAVP,DCDP,AUX1,MJDLAS,ACOF4,NMF,      &
     &                NPDEGF,TIME1)
          ENDIF
          LSNAP1=.TRUE.
        QINTQ=1.D0
          RETURN
      ENDIF
 6000 FORMAT(' EXECUTION TERMINATING IN SNAPGN')
 6001 FORMAT(' ID ',I10,' EXISTS ON SNAPSHOT FILE BUT NOT IN ARC')
 6007 FORMAT(' MAX DEGREE FOR POLYNOMIALS EXCEEDED')
 6008 FORMAT(' KEYS ',2I12)
 6009 FORMAT(' CROSSOVER LOC ',2F15.6)
 6010 FORMAT(' BOUNDARIES   ',4F15.6)
 6011 FORMAT(' METERS PER PARAMETER   ',F10.2)
 6012 FORMAT(' NPLAT,NPLON,MAXD ',3I10)
 6020 FORMAT('DIMENSION OF PARH ARRAY ',I10,' EXCEEDED')
 6021 FORMAT(' NXPARH,NADJST,NRLAT,NRLON ',4I12)
 6027 FORMAT(' MAX SUB REGIONS FOR PARTIALS  EXCEEDED')
 6028 FORMAT(' NRLAT,NRLON,MAXR ',3I10)
 6037 FORMAT(' MAX NUMBER OF POINTS IN A SNAPSHOT EXCEEDED')
 6038 FORMAT(' MAXH IS CURRENTLY SET AT ',I10)
 6039 FORMAT(' THIS BLOCK IS BEING DELETED DUE TO INSUFFICIENT OBS')
 6040 FORMAT(' NB1  NB2 ',2I12)
 6050 FORMAT(' EXECUTION TERMINATING ON BLOCK # ',I3)
 6051 FORMAT(' OF CURRENT SNAP SHOT CROSSOVER')
 6052 FORMAT(' # OBS IN BLOCK ',I5,' MAXNM ',I5)
70000 FORMAT(4I12)
      END
