      SUBROUTINE SNAPF2(AA,II,LL,LNADJ,MJDSBL,FSECN,FSECM,FSECK,NM,    &
! NUCON SET TO NM BY CALLING  ROUTINE
! FOR PMATT TO BE ALLOCATED  CORRECTLY NUCON MUST NE SET TO THE
! MAX NM FOR ANT STREAM
!
     &                 ISAT,ISET,OBS,XSN,XBM,XSK,VSN,VSK,OFF,THETAG,    &
     &                 COSTHG,SINTHG,OBSMET,OCDRYT,OCWETT,OCIONO,       &
     &                 OTIDES,XSCR,LNPNM,LDIOUT,LXGOUT,PMATT,HOLD,      &
     &                 SSTS,RINDEX,SATLAT,SATLON,SATH,XY2,ZT,RT,RA,     &
     &                 XTRA,ATROT,UTDT,UNQNDX,ETIDES,RLAND,             &
     &                 MAXD,NPDEG,MADJST,MAXNM,IOBSC,                   &
     &                 TMSE,PXEPXI,PXEPA,ACOEF,ACOEF2,ACOEF3,AUX1,TIME1,&
     &                 NADJST,NDIM1,NDIM2,NDIM3,IAVP,NAVP,DCDP,ISATID,  &
     &                 MTYPE)
!
!
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!
! THE FOLLOWING TWO COMMON BLOCKS ARE NEEDED FOR DIMENSIONS OF
! ARRAYS PASSES TO LTALTO
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL04/KLEDIT,KLBEDT,KLEDT1,KLEDT2,KNSCID,KEXTOF,KLSDAT,   &
     &              KLRDED,KLAVOI,KLFEDT,KLANTC,NXCL04
      COMMON/XOVER /KXKNT,KXBST,KXOBL,KXBUP,KXBPA,IAPLSC,IAPLL
      COMMON/XOVERR/XBTIME
      COMMON/XOVERS/NRXTOT,NXBLK,NUSIDE,NDEGX2,NDEGXX,NUCON,ITERNU,     &
     &              IPEDIT,IDEDIT,NXXOVR
!
      COMMON/CALTOP/LADYNO,LAGEOO,LRGEOT,LRETDT,LROTDT,LRSSTT,LCOTRM,   &
     &              LFILOT,LATCOR,LFIRIT,LX1ALT,LX2ALT,LMSSWG,LATMOD,   &
     &              LG1BOT,LG1B,LONEG1,LXATTD,LXBEAM,NXALTO
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
!
!
      DIMENSION TMSE(MAXNM),PXEPXI(1),PXEPA(1)
      DIMENSION ACOEF(MAXD,MAXNM,3),ACOEF2(1),AUX1(MAXNM,5),TIME1(1)
      DIMENSION ACOEF3(MAXD,4)
      DIMENSION DCDP(MAXD,MADJST,3)
      DIMENSION FSECUT(1)
!
!
! START ARRAYS PASSES TO LTALTO
      DIMENSION AA(1),II(1),LL(1),FSECN(NM),FSECM(NM),FSECK(NM),OBS(NM)
      DIMENSION COSTHG(NM),SINTHG(NM),THETAG(NM)
      DIMENSION XSN(MINTIM,3),XBM(MINTIM,3),XSK(MINTIM,3)
! VSN,VBM,VSK,VSJ,VSI,VSKP ARE USED AS SCRATCH LUMPED INTO VSN
! pd %%%%%% note: major changes to VSN array for
! VSKP HAS 2 EXTRA MINTIMS AT THE END OF IT (SEE KORC02 & KORP02)
      DIMENSION VSN(MINTIM,20)
      DIMENSION VSK(MINTIM,3)
! XTRA SPACE ; *,29 is FSECNN; *,30 is FSECKK
!              *,23 is COROBS; *,24 is XPTH; *,25 is ELPSEC
!              *,31 is ROLL; *,32 is PITCH; *,33 is YAW
      DIMENSION XTRA(MINTIM,33)
! OFF IS XSJ
      DIMENSION OFF(MINTIM,3)
      DIMENSION OBSMET(NM),OCDRYT(NM),OCWETT(NM),OCIONO(NM)
      DIMENSION OTIDES(NM),ETIDES(NM)
! PMATT IS USED FOR PARTIALS OF THE BOUNCE POINT  WRT TO VARIOUS PARAMET
! (UP TO 20) THE FIRST 3 ARE USED FOR ATTITUDE ANGLES (ROLL PITCH AND YA
      DIMENSION PMATT(NUCON,3,20)
      DIMENSION RINDEX(NXBLK,3)
      DIMENSION XSCR(3,MINTIM)
      DIMENSION HOLD(MINTIM,30)
      DIMENSION SSTS(NM)
      DIMENSION RA(NM,3)
      DIMENSION SATLAT(NM),SATLON(NM),SATH(NM),XY2(NM),ZT(NM),RT(NM)
      DIMENSION ATROT(3,3,MINTIM)
      DIMENSION UTDT(NM,4)
      DIMENSION UNQNDX(NM),RLAND(NM)
      DIMENSION IAVP(NADJST)
! END ARRAYS PASSED TO LTALTO
!
      DO I=1,NADJST
       LL(KLAVOI-1+I)=.TRUE.
      ENDDO
!
      LX2H=LX2ALT
      LX2ALT=.TRUE.
      CALL LTALTO(AA,II,LL,LNADJ,MJDSBL,FSECN,FSECM,FSECK,NM,MTYPE,&
     &             ISAT,ISET,OBS,XSN,XBM,XSK,VSN,VSK,OFF,THETAG,   &
     &             COSTHG,SINTHG,OBSMET,OCDRYT,OCWETT,OCIONO,      &
     &             OTIDES,XSCR,LNPNM,LDIOUT,LXGOUT,PMATT,HOLD,     &
     &             SSTS,RINDEX,SATLAT,SATLON,SATH,XY2,ZT,RT,RA,    &
     &             XTRA,ATROT,UTDT,UNQNDX,ETIDES,ISATID,RLAND)
!        print*,'mjds:',mjdsbl,fsecn(1)
!        print*,xtra(1,10),xtra(1,11),xtra(1,12)
!        print*,(aa(kpxpfm+k),k=0,8)
!        print*,(aa(kpxpfm+k),k=9,17)
!        print*,(aa(kpxpfm+k),k=18,26)
!        print*, '---------------------'
!        do i=1,20
!          print*,pmatt(1,1,i),pmatt(1,2,i),pmatt(1,3,i)
!        enddo
!        print*, '---------------------'

      LX2ALT=LX2H
!
!
      NDM1=MAXNM
      NDM2=NADJST
      IF(LNPNM) THEN
        NDM1=NADJST
        NDM2=MAXNM
      ENDIF
      DO I=1,NM
        AUX1(I,1)=XTRA(I,10)
        AUX1(I,2)=XTRA(I,11)
        AUX1(I,3)=XTRA(I,12)
        AUX1(I,4)=PMATT(I,1,20)
        AUX1(I,5)=PMATT(I,3,20)
        TMSE(I)=FSECN(I)
        CALL UTCET(.FALSE.,1,MJDSBL,FSECN(I),FSECUT(1),AA(KA1UT))
        WRITE(63,70000) FSECUT(1),AUX1(I,1),AUX1(I,2),AUX1(I,3)
70000   FORMAT(F15.6,3F20.4)
      ENDDO
      IOBSC=NM
!
!
      CALL EXDYN1(MAXD,NPDEG,ISAT,ISET,AA,II,LL,                        &
     &            AA(KXTN),AA(KXSM),AA(KXTK),PXEPXI,                    &
     &            II(KNEQN),II(KN3),II(KIPTFM),II(KILNFM),              &
     &            II(KNFMG),PXEPA,ACOEF,ACOEF2,ACOEF3,MJDSBL,           &
     &            FSECN,AUX1,                                           &
     &            TIME1,NDM1,NDM2,XBTIME,                               &
     &            IAPLSC,IAPLL,                                         &
     &            AA(KPXPFM),NDIM1,NDIM2,NDIM3,PMATT,                   &
     &            AA(KATPER),NM,MAXNM,.FALSE.,0,MAXNM)
!
!
!
       NAVP=0
       DO I=1,NADJST
         LPUT=.FALSE.
         IF(.NOT.LL(KLAVOI-1+I).AND.AA(KPRSG0-1+I).GT.1.D-10) THEN
            LPUT=.TRUE.
         ENDIF
         IF(.NOT.LL(KLAVOI-1+I).AND.I.LT.NPVAL0(IXSATP)) THEN
            LPUT=.TRUE.
         ENDIF
         IF(LPUT) THEN
            NAVP=NAVP+1
            IAVP(NAVP)=I
         ENDIF
       ENDDO
       CALL CHAINC(DCDP,PXEPA,ACOEF,NDM1,NDM2,NPDEG,MAXNM,NADJST,NM, &
     &             MAXD,MADJST,IAVP,NAVP)
!
!
      RETURN
      END
