!$SOLRD
      SUBROUTINE SOLRD(MJDSEC,FSEC,ELEM,S,R,RSQ,THETG,APLM,APGM,        &
     &                 LORBITL,NEQN,DXDD,VMATRX,GRPAR,STACC,LSTSUN,     &
     &                 NTRANS,NDARKS,LAJSP,AA,II,ISATID,ALAPGM,         &
     &                 RATIO)
!********1*********2*********3*********4*********5*********6*********7**
! SOLRD            83/08/21            8308.0    PGMR - ANITA C. BRENNER
!                                                PGMR - D. ROWLANDS
!
! FUNCTION:  CALCULATE ACCELERATION AND PARTIALS DUE TO SOLAR
!             RADIATION PRESSURE
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    INTEGER EPHEMERIS SECONDS SINCE GEODYN REF. TIME
!   FSEC     I    A    FRACTIONAL REMAINING SECONDS
!   ELEM     I    A    TRUE OF INTEGRATION ELEMENTS
!   S        I    A    TRUE OF REFERENCE ELEMENTS
!   R        I    A    DISTANCE OF SATELLITE FROM CENTER OF INTEGRATION
!   RSQ      I    A    R*R
!   THETG    I    S    GREENWHICH HOUR ANGLE
!   APLM     I    A
!   APGM     I    A
!   LORBITL  I         .TRUE. IF ORBGEN RUN
!   NEQN     I    S    NUMBER OF FORCE MODEL PARAMETERS
!   DXDD     O    A    TRUE OF INTEGRATION ACCELERATION DUE TO SOLAR RAD
!   VMATRX   O    A    TRUE OF INTEGRATION CONTRIBUTION TO VMAT FROM
!                      SOLAR RADIATION
!   GRPAR    O    A    TRUE OF REFERENCE PARTIAL OF ACCELERATION
!                      WRT SOLAR COEFFCIENT
!   STACC    I    A    START TIMES FOR SOLAR RADIATION PERIODS
!   LSTSUN  I/O   S    .TRUE. WHEN SATELLITE WAS IN SUN LAST CALL AS
!                      INPUT
!                      .TRUE. WHEN SATELLITE WAS IN SUN THIS CALL AS
!                      OUTPUT
!   NTRANS  I/O   S    NUMBER OF LIGHT TO DARK TRANSITIONS BEFORE
!                      THIS CALL AS INPUT
!                      NUMBER OF LIGHT TO DARK TRANSITIONS AFTER
!                      (INCLUDING) THIS CALL AS OUTPUT
!   NDARKS  I/O   S    NUMBER OF STEPS THAT HAVE BEEN IN DARKNESS
!                      BEFORE THIS CALL AS INPUT
!                      NUMBER OF STEPS THAT HAVE BEEN IN DARKNESS
!                      AFTER (INCLUDING) THIS CALL AS OUTPUT
!   LAJSP    I    S    LOGICAL TELLING WHETHER A PARTICULAR PERIOD HAS
!                      BEEN ADJUSTED
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INGEGER DYNAMIC ARRAY
!   NSTART   I    S    STARTING LOCATION FOR SOLAR COFFCIENT IN
!                      GRPAR ARRAY (0=>NOADJ)
!   ISATID   I    A    SAT ID ARRAY
!   ALAPGM   O    S    CORRECT CR*APLM SAVED FOR ALBEDO
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      PARAMETER ( ZERO   = 0.D0 )
      PARAMETER ( ONE    = 1.D0 )
      PARAMETER ( TWO    = 2.D0 )
      PARAMETER ( THREE  = 3.D0 )
!
!     LOGICAL SOLSW,DRGSW,BAXISW
      LOGICAL LORBITL
      LOGICAL LAJSP(1)
      LOGICAL LSTSUN,LCRSUN
!     REAL ASTAR,CRT
!
      INCLUDE 'COMMON_DECL.inc'
      COMMON/BWREAL/SHADOW(2),SUNPCT,SCAREA,SCMASS,BWMEAN
      COMMON/BWINTG/JBFNRM,JTDNRM,JBWARE,JBWSPC,JBWDIF,JBWEMS,JBWTPA,   &
     &              JBWTPC,JBWTMD,JBWTMF,JBWTHX,JARADJ,JSPADJ,JDFADJ,   &
     &              JEMADJ,JTAADJ,JTCADJ,JTDADJ,JTFADJ,JTXADJ,JARUA ,   &
     &              JSPUA ,JDFUA ,JEMUA ,JTAUA ,JTCUA ,JTDUA ,JTFUA ,   &
     &              JTXUA ,NFACE ,NMOVE,NTFACE,JBFNR2,JBFNR3,JTDNR2,    &
     &              JTDNR3
      COMMON/BWLOGC/LVAREA,LTOPEX,LSPOT2,LGPSVA,LERS1,LMO,LMOC,LTDRSA,  &
     &              LMAGNA,LGFO,LTRMM,LEUVE,LVCL,LENVS,LCRYO,LGRAIL,    &
     &              LHY2A,LSARAL
!      COMMON/CAXIS/
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
!      COMMON/CPENUM/
      COMMON/CBDTRU/BDTRUE(7,999)
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CLVIEW/LNPRNT(18),NXCLVI
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CRMI/RMI(9)
!     ....ADD IBODPT TO GET ICBDGM
      COMMON/DELOFF/NOFFST,NSATDL,NSTADL,NCGMAS,NXDELO
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/LSFSHD/LSLFSH, NXSLFS
      COMMON/LSTRT/LSTART
      COMMON/SLFSHD/NSHSAT,IDSASH(200),NSPANL(200),IFLGSH(200),         &
     &              IATYSH(200),NSHRCD(200),MNSHPL,NXSFSD
      COMMON/SETADJ/LSADRG(4),LSASRD(4),LSAGA(4),LSAGP,LSATID,LSAGM,    &
     &              LSADPM,LSAKF,LSADNX,LSADJ2,LSAPGM
      COMMON/SETAPT/                                                    &
     &       JSADRG(1),JSASRD(1),JSAGA(1),JFAADJ,JTHDRG,JACBIA,JATITD,  &
     &       JDSTAT,JDTUM ,                                             &
     &       JSACS, JSATID,JSALG,JSAGM,JSAKF,JSAXYP,JSADJ2,JSAPGM,      &
     &       JFGADJ,JLTPMU,JLTPAL,JL2CCO,JL2SCO,JL2GM,JLRELT,           &
     &       JLJ2SN,JLGMSN,JLPLFM,JL2AE,JSAXTO,JSABRN
      COMMON/SETIOR/IORDRG,IORSRD,IORGA,IPDDRG,IPDSRD,IPDGA
      COMMON/STARTT/ESSTRT,FSSTRT
      COMMON/TOPEXL/LTOPX1,LRAMP,LRDOWN,LRUP,LFIX0,LFIX90,LSIN,LTXPRT
!      COMMON/VAPCM/
      COMMON/VRBLOK/SINPSI,COSPSI,XLAMDA,GMR,AOR
      COMMON/SLRATI/ISLRNS,ISLRID(10),ISLRNO(10),ISLRMO,NXSLRI
      COMMON/SLRATL/LRATIO,NXSLRL

!jtw add Common Blocks
!
!     DIMENSION ASTAR(1)
      DIMENSION GRPAR(NEQN,3),APGM(1),S(6),DXDD(3),FACT(3),FACTR(3)
      DIMENSION STACC(1),TM(3)
!      DIMENSION PSDYPX(3),A(3),B(3),PASTPA(3),PASTPD(3),PSDPPX(3),
!     .XSQ(3),XSS(3),PSDXPX(3),PDPX(3),XDD(3),PAPX(3)
      DIMENSION XHELIO(3),PART(3)
      DIMENSION ELEM(6),VMATRX(3,3)
      DIMENSION AA(1),II(1)
      DIMENSION ISATID(1)

!
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
      RATIO2=1.D0
      ITEST=MJDSEC+FSEC
      IF(NCGMAS.GT.0) THEN
        DO I=1,NCGMAS
           IF(ISATID(1).EQ.II(KISATC-1+I).AND.                          &
     &      ITEST.GE.II(KMJDCG-1+I)) RATIO2=1.D0/AA(KSCMRA-1+I)
        ENDDO
      ENDIF
!
!     BAXISW=.FALSE.
      LCRSUN=.TRUE.
      TTEST=MJDSEC+FSEC
      TM(1)=ONE
      IF(IORSRD.GT.1) TM(2)=FSSTRT
      IF(IORSRD.GT.2) TM(3)=TM(2)*TM(2)
      APGMR=ZERO
      IPD=0
      IUP=IORSRD-1
      IF(IUP.LE.0) GO TO 110
      DO 100 I=1,IUP
  100 APGMR=APGMR+TM(I)*APGM(I)
  110 IF(IPDSRD.GT.0) GO TO 112
      APGMR=APGMR+TM(IORSRD)*APGM(IORSRD)
      GO TO 150
  112 CONTINUE
!   FIGURE WHICH PERIOD APPLIES
      DO 115 I=1,IPDSRD
      IF(TTEST.LT.STACC(I)) GO TO 116
  115 END DO
      IPSN=IPDSRD
      IPD=0
      GO TO 120
  116 CONTINUE
      IPSN=I-1
      IPD=I
  120 CONTINUE
      T0=ESSTRT
      IF(IPSN.EQ.0) GO TO 140
      DO 130 I=1,IPSN
      TD=STACC(I)-T0
      CALL POWER(IORSRD,TD,TDN,.FALSE.)
      APGMR=APGMR+APGM(I+IORSRD)*TDN
      T0=STACC(I)
  130 END DO
  140 CONTINUE
      TD=TTEST-T0
      CALL POWER(IORSRD,TD,TDN,.TRUE.)
      APGMR=APGMR+APGM(IORSRD+IPD)*TDN
  150 CONTINUE
! SAVE VALUE OF APGMR WITH CORRECT CR FOR ALBEDO
      ALAPGM=APGMR
      IF(APGMR.EQ.ZERO) GO TO 650
      RATIO=ONE
      XHELIO(1)=ELEM(1)-BDTRUE(1,8)
      XHELIO(2)=ELEM(2)-BDTRUE(2,8)
      XHELIO(3)=ELEM(3)-BDTRUE(3,8)
      RSSQ=XHELIO(1)**2+XHELIO(2)**2+XHELIO(3)**2
      RS=SQRT(RSSQ)

!!!!!!jtw add if statements to determine call for SOLRIN
!!!!!!ICBDGM tells which body satellite is orbiting


      IF( ICBDGM .EQ. 11 ) THEN
         RATIO = ONE

      ELSE IF (LRATIO) THEN

      TDUM=MJDSEC+FSEC
      DO kk=1,ISLRNS
         IF (ISATID(1)==ISLRID(kk))THEN

!jtw add so that time step will be calculated
            DO jj=1,25
               TDIFF=0.0D0
               IF (jj==1) THEN
                  DUMTS=AA(KTRAT+ISLRMO*(kk-1))
                  DUMRS=AA(KSRAT+ISLRMO*(kk-1))
               ELSE
                  DUMTS=DUMTF
                  DUMRS=DUMRF
               END IF

               DUMTF=AA(KTRAT+ISLRMO*(kk-1)+jj)
               DUMRF=AA(KSRAT+ISLRMO*(kk-1)+jj)

               IF (jj==1) TDIFFMIN=DUMTF-DUMTS

               TDIFF=DUMTF-DUMTS

               IF (TDIFF.LT.TDIFFMIN) THEN
                  TDIFFMIN=TDIFF
               END IF

            END DO

            DO jj=1,ISLRMO

               IF (jj==1) THEN
                  DUMTS=AA(KTRAT+ISLRMO*(kk-1))
                  DUMRS=AA(KSRAT+ISLRMO*(kk-1))
               ELSE
                  DUMTS=DUMTF
                  DUMRS=DUMRF
               END IF

               DUMTF=AA(KTRAT+ISLRMO*(kk-1)+jj)
               DUMRF=AA(KSRAT+ISLRMO*(kk-1)+jj)

               IF (TDUM.GE.DUMTS.AND.TDUM.LE.DUMTF) THEN
                  TDIFF=0.0D0
                  TDIFF=DUMTF-DUMTS
                  RATIO=0.0D0
                  IF (TDIFF.LE.(1.5D0*TDIFFMIN)) THEN
                  RATIO=DUMRS+(DUMRF-DUMRS)*((TDUM-DUMTS)/(DUMTF-DUMTS))
                  ELSE IF(DUMRS==DUMRF) THEN
                        RATIO=DUMRS
!                  ELSE
!                        RATIO=7.777
                  END IF
               END IF
            END DO
         END IF
      END DO

      ELSE

         CALL SOLRAT(AA(KAESHD),II(KISHDP),FE,RS,RSSQ,R,RSQ,ELEM,RATIO)

      END IF

!jtw optional output to check ratios
!      IF (.NOT.LSTART) THEN
!
!      IF (ISATID(1).EQ.2012001) THEN
!         WRITE(4001,8000)MJDSEC,RATIO,ISATID
!      ELSE IF (ISATID(1).EQ.2012002) THEN
!         WRITE(4002,8000)MJDSEC,RATIO,ISATID
!      END IF
!
!      END IF
!
! OUTPUT TOPEX TELEM FILE INFORMATION
      IF(LTXPRT .AND. .NOT. LSTART) THEN
!....SUN OCCULTATION INFORMATION
         WRITE(97) RATIO*100.0
!        WRITE(97,6000) RATIO*100.0
      ENDIF
!
      IF(RATIO.LE.ZERO) GO TO 650
      RATIO2=RATIO2*RATIO
!      RS3=RSSQ*RS
!      RS5=RSSQ*RS3
!!!!! APGMR=APGMR*RATIO
!! SCALE BY % SUNLIGHT AND CURRENT RATIO OF RECIP MASS
      APGMR=APGMR*RATIO2
! COMPUTE TRUE OF DATE SOLAR RADIATION ACCELERATION FOR A VARIABLE AREA
! THIS WILL ALTER  APLM, APGMR TO REFLECT THE ACTUAL PROJECTED AREA.
! THEREFORE, TEMPORARILY STORE VALUES IN TAPLM AND TAPGMR.
! BOX-WING PARTIALS ARE STORED IN TRUE OF REFERENCE.
      TAPLM = APLM
      TAPGMR = APGMR
      IF(LVAREA) THEN
! ISHFLG=0 THE DEFAULT MODEL WITHOUT SELF SHADOWING
         ISHFLG=0
         IF(LSLFSH) THEN
           CALL FNDNUM(ISATID,IDSASH,NSHSAT,IRET)
! ISHFLG=1 FOR SELF SHADOWING WITH CROSS-SECTION
! ISHFLG=2 FOR SELF SHADOWING WITH RATIO
! IATYSH(IRET)=0 FOR RATIO
! ITAYSH(IRET)=1 FOR CROSS-SECTION
           IF(IFLGSH(IRET).EQ.10.OR.IFLGSH(IRET).EQ.11) ISHFLG=1
           IF(ISHFLG.EQ.1 .AND. IATYSH(IRET).EQ.0)      ISHFLG=2
         ENDIF
! AA(KSDINS) IS THE ARRAY OF THE INTERPOLATED PLANE AREA WHICH IS
! CALCULATED IN EXTATT
         CALL BWSOLR(AA(JTDNRM),AA(JTDNR2),AA(JTDNR3),                  &
     &               AA(KCSTHT),AA(JBWARE),                             &
     &               AA(JBWSPC),AA(JBWDIF),DXDD,GRPAR,JARADJ,JSPADJ,    &
     &               JDFADJ,II(JARUA),II(JSPUA),II(JDFUA),NFACE,        &
     &         XHELIO,TAPGMR,TAPLM,RS,RSSQ,FACT,VMATRX,NEQN,ISATID,     &
     &         ISHFLG,AA(KSDINS))
      ELSE
!     IF(SOLSW(ISAT))GO TO 900
      DO 600 I=1,3
  600 FACT(I)=XHELIO(I)/RS
!     GO TO 604
!900  CALL SOLINT(IRECSR(ISAT),ASTAR,FACT,NAS(ISAT),NDS(ISAT),
!    .   ISAT,PASTPD,PASTPA,DAY)
!     RDOT= SQRT(ELEM(4)**2+ELEM(5)**2+ELEM(6)**2)
!     RSQ4RD=RSQ*RSQ*RDOT
!     FACT2=ONE/RSQ4RD
!     FACT1=R*FACT2
!     DO 810 I=1,3
!     XSQ(I)=ELEM(I)*ELEM(I)
!     XXD(I)=ELEM(I)*ELEM(I+3)
!     XSS(I)=-XHELIO(I)
!10   PSDPPX(I)=-BAXISZ(I)-ELEM(I)*XSUN(3)/RSQ+XSS(I)/R
!     A(1)=ELEM(4)*(-XSQ(2)-XSQ(3))+ELEM(1)*(XXD(3)+XXD(2))
!     A(2)=ELEM(5)*(-XSQ(3)-XSQ(1))+ELEM(2)*(XXD(3)+XXD(1))
!     A(3)=ELEM(6)*(-XSQ(2)-XSQ(1))+ELEM(3)*(XXD(2)+XXD(1))
!     XYD=ELEM(1)*ELEM(5)
!     XZD=ELEM(1)*ELEM(6)
!     YXD=ELEM(2)*ELEM(4)
!     YZD=ELEM(2)*ELEM(6)
!     ZXD=ELEM(3)*ELEM(4)
!     ZYD=ELEM(3)*ELEM(5)
!     B(1)=2.E0*ELEM(1)*A(1)+RSQ*(-XXD(2)-XXD(3))
!     B(2)=2.E0*ELEM(1)*A(2)+RSQ*(2.E0*XYD-YXD)
!     B(3)=2.E0*ELEM(1)*A(3)+RSQ*(2.E0*XZD-ZXD)
!     PSDXPX(1)=-BAXISX(1)+DOTPRD(XSS,B)*FACT2
!     B(1)=2.E0*ELEM(2)*A(1)+RSQ*(2.E0*YXD-XYD)
!     B(2)=2.E0*ELEM(2)*A(2)+RSQ*(-XXD(3)-XXD(1))
!     B(3)=2.E0*ELEM(2)*A(3)+RSQ*(2.E0*YZD-ZYD)
!     PSDXPX(2)=-BAXISX(2)+DOTPRD(XSS,B)*FACT2
!     B(1)=2.E0*ELEM(3)*A(1)+RSQ*(2.E0*ZXD-XZD)
!     B(2)=2.E0*ELEM(3)*A(2)+RSQ*(2.E0*ZYD-YZD)
!     B(3)=2.E0*ELEM(3)*A(3)+RSQ*(-XXD(1)-XXD(2))
!     PSDXPX(3)=-BAXISX(3)+DOTPRD(XSS,B)*FACT2
!     A(1)=ZYD-YZD
!     A(2)=XZD-ZXD
!     A(3)=YXD-XYD
!     B(1)=ELEM(1)*A(1)
!     B(2)=ELEM(1)*A(2)-RSQ*ELEM(6)
!     B(3)=ELEM(1)*A(3)+RSQ*ELEM(5)
!     PSDYPX(1)=-BAXISY(1)+DOTPRD(XSS,B)*FACT1
!     B(1)=ELEM(2)*A(1)+RSQ*ELEM(6)
!     B(2)=ELEM(2)*A(2)
!     B(3)=ELEM(2)*A(3)-RSQ*ELEM(4)
!     PSDYPX(2)=-BAXISY(2)+DOTPRD(XSS,B)*FACT1
!     B(1)=ELEM(3)*A(1)-RSQ*ELEM(5)
!     B(2)=ELEM(3)*A(2)+RSQ*ELEM(4)
!     B(3)=ELEM(3)*A(3)
!     PSDYPX(3)=- BAXISY(3)+DOTPRD(XSS,B)*FACT1
!     XZSSQ=XSUN(1)**2+XSUN(3)**2
!     XZS= SQRT(XZSSQ)
!     XYZSSQ=XZSSQ+XSUN(2)**2
!     DO 820 I=1,3
!     PDPX(I)=(XZS*PSDYPX(I)-XSUN(2)*(XSUN(1)*PSDXPX(I)+XSUN(3)*
!    .   PSDPPX(I))/XZS)/XYZSSQ
!820  PAPX(I)=(XSUN(3)*PSDXPX(I)-XSUN(1)*PSDPPX(I))/XZSSQ
!     DO 830 I=1,3
!     DO 830 J=1,3
!830  VMATRX(J,I)=RATIO*TAPGMR*
!    1            (PASTPA(J)*PAPX(I)+PASTPD(J)*PDPX(I))/RSSQ
! SCALE DOWN THE ACC BY THE DIST of THE SAT TO THE SUN **2 TO
! ACCOUNT FOR THE CONSTANT COMPUTED IN INIT A HAVING BEEN  SCALED
!UO BY AU**
      DO 608 I=1,3
      DXDD(I)=TAPGMR*FACT(I)/RSSQ
  608 END DO
      ENDIF
      IF(LORBITL) GO TO 700
      DO 620 I=1,3
!      PAR=-THREE*TAPGMR*XHELIO(I)/RS5
      PAR=-THREE*((TAPGMR/RS)/RS)*(( XHELIO(I)/RS)/RS)/RS
      DO 610 J=1,3
  610 VMATRX(J,I)=VMATRX(J,I)+PAR*XHELIO(J)
! 620  VMATRX(I,I)=VMATRX(I,I)+TAPGMR/RS3
  620 VMATRX(I,I)=VMATRX(I,I)+((TAPGMR/RS)/RS)/RS
!
! APPLY CONVENTIONAL SOLAR RADIATION WHEN NOT IN SHADOW
!
! COMPUTE SOLAR RADIATION PARTIALS TRUE OF STEP
! PUT PARTIALS INTO TRUE OF REFERENCE
      CRINV=TAPLM*RATIO2/TAPGMR
      FACTR(1)=CRINV*DXDD(1)
      FACTR(2)=CRINV*DXDD(2)
      FACTR(3)=CRINV*DXDD(3)
      PART(1)=RMI(1)*FACTR(1)+RMI(2)*FACTR(2)+RMI(3)*FACTR(3)
      PART(2)=RMI(4)*FACTR(1)+RMI(5)*FACTR(2)+RMI(6)*FACTR(3)
      PART(3)=RMI(7)*FACTR(1)+RMI(8)*FACTR(2)+RMI(9)*FACTR(3)
      KPART=JSASRD(1)
      DO 635 J=1,IORSRD
      IF(.NOT.LSASRD(J)) GO TO 635
      GRPAR(KPART,1)=TM(J)*PART(1)
      GRPAR(KPART,2)=TM(J)*PART(2)
      GRPAR(KPART,3)=TM(J)*PART(3)
      KPART=KPART+1
  635 END DO
      IF(.NOT.LSASRD(4)) GO TO 700
      IF(.NOT.LSASRD(IORSRD)) GO TO 637
      GRPAR(KPART-1,1)=ZERO
      GRPAR(KPART-1,2)=ZERO
      GRPAR(KPART-1,3)=ZERO
  637 CONTINUE
      KPARTS=KPART
      DO 640 I=1,IPDSRD
      IF(.NOT.LAJSP(I)) GO TO 640
      GRPAR(KPART,1)=ZERO
      GRPAR(KPART,2)=ZERO
      GRPAR(KPART,3)=ZERO
      KPART=KPART+1
  640 END DO
      KPART=KPARTS
      T0=ESSTRT
      IF(IPSN.EQ.0) GO TO 647
      DO 645 I=1,IPSN
      IF(.NOT.LAJSP(I)) GO TO 643
      TD=STACC(I)-T0
      CALL POWER(IORSRD,TD,TDN,.FALSE.)
      GRPAR(KPART,1)=PART(1)*TDN
      GRPAR(KPART,2)=PART(2)*TDN
      GRPAR(KPART,3)=PART(3)*TDN
      KPART=KPART+1
  643 CONTINUE
      T0=STACC(I)
  645 END DO
  647 CONTINUE
      IF(IPD.GT.0) GO TO 648
      IF(.NOT.LSASRD(IORSRD)) GO TO 700
      KPART=KPARTS-1
      GO TO 649
  648 CONTINUE
      IF(.NOT.LAJSP(IPD)) GO TO 700
  649 CONTINUE
      TD=TTEST-T0
      CALL POWER(IORSRD,TD,TDN,.TRUE.)
      GRPAR(KPART,1)=PART(1)*TDN
      GRPAR(KPART,2)=PART(2)*TDN
      GRPAR(KPART,3)=PART(3)*TDN
      GO TO 700
  650 CONTINUE
! SATELLITE NOT IN SUN OR NOT AFFECTED BY SOLAR RADIATION
      LCRSUN=.FALSE.
      NDARKS=NDARKS+1
      DO 655 I=1,3
  655 DXDD(I)=ZERO
      IF(LORBITL) GO TO 700
      KPART=JSASRD(1)
      DO 670 J=1,IORSRD
      IF(.NOT.LSASRD(J)) GO TO 670
      GRPAR(KPART,1)=ZERO
      GRPAR(KPART,2)=ZERO
      GRPAR(KPART,3)=ZERO
      KPART=KPART+1
  670 END DO
      IF(.NOT.LSASRD(4)) GO TO 700
      DO 680 I=1,IPDSRD
      IF(.NOT.LAJSP(I)) GO TO 680
      GRPAR(KPART,1)=ZERO
      GRPAR(KPART,2)=ZERO
      GRPAR(KPART,3)=ZERO
      KPART=KPART+1
  680 END DO
  700 CONTINUE
!
! INCREMENT SUN-SHADOW TRANSITION COUNT IF REQUESTED ON
!  PRNTVU CARD (IIS)
!  CALL ROUTINE TO PRINT SHADOW CROSSING INFO
!
      IF(LCRSUN.NEQV.LSTSUN)THEN
         NTRANS=NTRANS+1
         LSTSUN=LCRSUN
         IF(LNPRNT(15))GO TO 720
         IF(.NOT.LSTART)THEN
           IF(LSTITR)THEN
             CALL PRTSHD(MJDSEC,FSEC,ISATID,LCRSUN,LSTSUN,AA)
           ENDIF
         ENDIF
      ENDIF
      RETURN
  720 CONTINUE
!700  IF(.NOT.PENUMB) GO TO 780
!     IF(RATIO.EQ.RATIOP(ISAT)) GO TO 780
!     CALL DATES(DAY2,IYMD,IHM,SEC)
!     DLAT= ATAN(SINPSI/COSPSI)/DRAD
!     DLON= ATAN2(S(2),S(1))-THETG+TWOPI
!     DLON=AMOD(DLON,TWOPI)/DRAD
!     WRITE(KUNIT,5000) IYMD,IHM,SEC,S,DLAT,DLON,RATIOP(ISAT),RATIO
!     RATIOP(ISAT)=RATIO
!780  RETURN
!5000 FORMAT(1X,I6,I5,F8.4,6G15.8,2F10.5/' PENUMBRA ENCOUNTERED. ',
!    .   'FRACTION OF SUNLIGHT BEFORE ENCOUNTER =',F6.3,' FRACTION OF ',
!    .   'SUNLIGHT AT ABOVE LOCATION AND TIME =',F6.3)
 6000 FORMAT(F5.1)
 8000 FORMAT(I10,1X,F6.4,1X,I7)
      END
