!$SSORT
      SUBROUTINE SSORT(PNAME,IPTRUA,ISATID,STSRD,LREDSL,NREDSR,RTGSLR,  &
     &                 IRESLR,ISTRTS,WTASLR,CTMSLR,IDIM3,IDIM4,IDIMT,KI)
!********1*********2*********3*********4*********5*********6*********7**
! ASORT
!
!
! FUNCTION:
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PNAME   I     A    PARAMETER NAME ARRAY
!   IPTRUA  I     A    POINTERS FROM UNADJUSTED TO ADJUSTED PARAMETERS
!   ISATID  I     A    SATELLITE ID
!   STSRD   I     A    SOLAR RADIATION TIME PERIODS
!   LREDSL  I     A    FLAGS FOR CONSTRAINTS APPLICATION (ISAT)
!   NREDSR  I     A    NUMBER OF CONTINUOUS TIME PERIODS (ISET,ISAT)
!   RTGSLR  O     A    ARRAY OF TIMES
!   IRESLR  0     A    ARRAY OF POINTERS TO ADJUSTED PARAMETERS
!   ISTRTS  I     A    STARTING LOCATION OF CONTINUOUS PERIODS
!   WTASLR  I     A    ARRAY OF WEIGHTS FOR SOLAR RADIATION  CONSTRAINTS
!   CTMSLR  I     A    ARRAY OF CORRELATION TIMES FOR SOL. RAD  CONSTRAI
!   IDIM3   I     S    FIRST DIMENSION OF NRESRD
!   IDIM4   I     S    FOURTH  DIMENSION OF NREDSR
!   IDIMT   I     S    FIRST DIMENSION OF RTDRGG
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION  (A-H,O-Z),LOGICAL(L)
      SAVE
      CHARACTER*8 SOLR,HOLD8
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/KNTSTS/KNTACC(9,40),MKNTAC,KNTDRG,KNTSLR,MAXNGA,MAXNDR,    &
     &              MAXNSR,NXKNTS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/SETIOR/IORDRG,IORSRD,IORGA,IPDDRG,IPDSRD,IPDGA
      COMMON/STARTT/ESSTRT,FSSTRT
      COMMON/STARTV/SSTRTC(200)

      CHARACTER(8)    :: PNAME
      DIMENSION PNAME(2,1),IPTRUA(1),ISATID(1),STSRD(1)
      DIMENSION FSEC(1),IYMD(1),IHM(1),SEC(1)
      DIMENSION LREDSL(1)
      DIMENSION NREDSR(IDIM3,IDIM4)
      DIMENSION ISTRTS(IDIM3,IDIM4)
      DIMENSION RTGSLR(IDIMT,IDIM3,IDIM4)
      DIMENSION IRESLR(IDIMT,IDIM3,IDIM4)
      DIMENSION WTASLR(IDIM3,IDIM4)
      DIMENSION CTMSLR(IDIM3,IDIM4)
! ILOCSC IS LOCAL IT HOLDS THE STARTING LOCATION FOR SOLRAD IPTRUA FOR E
! S/C MAY NEED TO INCREASE IT OR MAKE IT DYNAMIC IN THE FUTURE
      DIMENSION ILOCSC(9999)
      DATA SOLR/'CR      '/
      DATA FSEC/0.D0/
      CHARACTER(8)      :: BLANK
      CHARACTER(8)      :: WRD2
      DATA BLANK/'        '/
      EQUIVALENCE (HOLD8,HOLDR)
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!     do 5511 I=1,20
!     write(6,*)' dbg esstrt ',SSTRTC(I),I
!5511  continue
! INITIALIZE ILOCSC TO ZERO
!
      DO 10 I=1,9999
      ILOCSC(I)=0
   10 END DO
!
! DEBUG
!
!     write(6,*)' dbg nsata',nsata
!     do 100 i=1,3
!     do 100 j=1,3
!     do 100 k=1,nsata
!     write(6,*)' ISATID ',ISATID(k)
!     IF(LREDSL(K)) THEN
!     write(6,*)' dbg LREDSL',LREDSL(k),k
!     do 200 ij=1,mkntac
!     if(nredsr(ij,k).gt.0) then
!     write(6,*)' dbg NREDSR',NREDSR(IJ,k),ij,k
!     write(6,*)' dbg ISTRTS',ISTRTS(IJ,k),ij,k
!     write(6,*)' dbg WTASLR',wtaslr(IJ,k),ij,k
!     write(6,*)' dbg CTMSLR',CTMSLR(IJ,k),ij,k
!     endif
!200   continue
!     ENDIF
!100   CONTINUE
!
! DEBUG
!
! FIND THE STARTING LOCATION FOR EACH SATELLITE IN IPTRUA
! LOAD IN LOCAL ARRAY ILOCSC
      J=1
      IEC=IPVAL(IXBISA)
      DO 1001 I=1,IEC
      IF(J.GT.NSATA) GOTO 1001
!      HOLDR=PNAME(1,I)
      HOLD8=PNAME(1,I)
      IF(HOLD8(1:5).NE.SOLR(1:5)) GO TO 1001
!      HOLDR=PNAME(2,I)
      HOLD8=PNAME(2,I)
      IF(IPTRUA(I).LE.0) GO TO 1001
      WRD2=BLANK
      CALL NUMASC(ISATID(J),WRD2,28,.TRUE.)
!!      ....INDX is UNDEFINED                           ! jjm 9/98
!      WRITE(6,34567) J,INDX,I,PNAME(1,I),PNAME(2,I),IPTRUA(I)
      IF(PNAME(2,I).EQ.WRD2) THEN
!     WRITE(6,34567) J,INDX,I,PNAME(1,I),PNAME(2,I),IPTRUA(I)
      ILOCSC(J)=I
      J=J+1
      ENDIF
 1001 END DO
!
      WRITE(6,6000)
! LOOP 1000 FOR SATELLITE
!     DO 1000 KI=1,NSATA
      TT1=SSTRTC(KI)
      INDXS=ILOCSC(KI)
      IF(LREDSL(KI)) THEN
      IK0=1
      IK=IK0
      DO 300 JJ=1,IDIM3
      IF(NREDSR(JJ,KI).GT.0) THEN
      NALL=NREDSR(JJ,KI)
      INDXB=ISTRTS(JJ,KI)
      INDXT=INDXB
!     IL=ILOCSC(KI)+INDXB
      IL=ILOCSC(KI)+INDXB-1
      WRITE(6,34569)
      WRITE(6,34570)
      DO 350 IJ=1,NALL
      IF(INDXT.EQ.1) THEN
      T0=TT1
      ELSE
      T0=STSRD(INDXT-1)
      ENDIF
      T1=STSRD(INDXT)
      TREDDR=(T0/2.D0)+(T1/2.D0)
      IRESLR(IJ,IK,KI)=IPTRUA(IL)
!     write(6,*)' dbg iptrua(il)',iptrua(il),IL
      RTGSLR(IJ,IK,KI)=TREDDR
      WRITE(6,*)' dbg IRESLR ',ireslr(ij,ik,ki),ij,ik,ki,il
!     write(6,*)' dbg times ',t0,t1
      WRITE(6,*)' dbg RTGSLR ',rtgslr(ij,ik,ki),ij,ik,ki,il
      ITAG=RTGSLR(IJ,IK,KI)
      CALL YMDHMS(ITAG,FSEC,IYMD,IHM,SEC,1)
      ITAG=SEC(1)
      IHMS=IHM(1)*100+ITAG
      !orig WRITE(6,*)' FOR SATELLITE ',KI,'AND SOLAR RADIATION PARAMETER
      WRITE(6,'(A,1x,I8,1x,A)')&
            'FOR SATELLITE ',KI,' AND SOLAR RADIATION PARAMETERS'
      WRITE(6,34571) IRESLR(IJ,IK,KI),IYMD(1),IHMS
      WRITE(6,6000)
      IL=IL+1
      INDXT=INDXT+1
  350 END DO
      IK=IK+1
      ENDIF
  300 END DO
      ENDIF
!1000  CONTINUE
!
! DEBUG
!
! DEBUG
!
      WRITE(6,6000)
      WRITE(6,6000)
      WRITE(6,6000)
      RETURN
 6000 FORMAT(' ')
34567 FORMAT('  ',3I5,3X,A8,3X,A8,I10)
34569 FORMAT('  THE FOLLOWING ADJUSTED PARAMETER NUMBERS WITH ')
34570 FORMAT('  TIME TAGS WILL BE CONSTRAINED TOGETHER:')
34571 FORMAT('  ADJUSTED PARM NUM:',I8,' TIME TAG ',I8,3X,I6)
      END
