!$SST
      SUBROUTINE SST(NM,COSLAT,SINLAT,COSLON,SINLON,C,S,                &
     &               P,COSLAM,SINLAM,EXPART,SSTS,PMPA,LNPNM,            &
     &               NDIM1,NDIM2,WORK,IPTRUA,IPTRAU,AA,II,MJDSBL,FSEC,  &
     &               ISSTNA,CCOSWT,CSINWT,SCOSWT,SSINWT,SSS,LOAD,       &
     &               LAVOID,LRADAR)
!********1*********2*********3*********4*********5*********6*********7**
! SST              00/00/00            0000.0    PGMR - ?
!
! FUNCTION:   CALCULATE SST HTS (AS IMPLIED BY A SET OF SPHERICAL
!             HARMONICS) AT A SERIES OF POINTS ON THE ELLIPSOID AND/OR
!             CALCULATE THE PARTIALS OF AN ALTIMETRY MEASUREMENT TO THE
!             GEOID WRT C & S COEFFCIENTS
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   NM       I    S    NUMBER OF POINTS FOR WHICH CALCULATION DESIRED
!                      REQUIRED
!   COSLAT   I    A    COSINE OF GEOCENTRIC LATITUDES
!   SINLAT   I    A    SINE OF GEOCENTRIC LATITUDES
!   COSLON   I    A    COSINE OF LONGITUDES
!   SINLON   I    A    SINE OF LONGITUDES
!   C        I    A    GRAVITY C COEFFCIENTS
!   S        I    A    GRAVITY S COEFFCIENTS
!   P       I/O   A    SCRATCH SPACE FOR LGENDRE POLYNOMIALS
!   COSLAM  I/O   A    SPACE FOR COS(M*SATLON)
!   SINLAM  I/O   A    SPACE FOR SIN(M*SATLON)
!   EXPART  I/O   A    SPACE FOR C & S PARTIALS (FULL SET)
!   SSTS     O    A    SST HTS
!   PMPA     O    A    PARTIALS OF ALTIMETRY MEAS WRT C&S COEFFCIENTS
!   LNPNM    I    S    .TRUE. IF NP IS THE FIRST DIMENSION IN THE PMPA
!                      ARRAY (AS OPPOSED TO NM)
!   NDIM1    I    S    FIRST DIMENSION OF PMPA ARRAY
!   NDIM2    I    S    SECOND DIMENSION OF PMPA ARRAY
!   WORK          A    SPACE FOR ADJUSTED C&S
!   IPTRUA   I    A    INDICES FROM UNADJUSTED PARAMETERS TO ADJUSTED
!                      PARAMETERS ARRAY
!   IPTRAU   I    A    INDICES FROM ADJUSTED PARAMETERS TO UNADJUSTED
!                      PARAMETERS ARRAY
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II
!   MJDSBL
!   FSEC     I         OBS. TIME IN SECS SINCE BLOCK START AT MJDSBL
!   ISSTNA   I         NOFFSETS FOR ADJ C&S SST COEFFICIENTS
!   CCOSWT             COS(SSTFRQ*TDIFF) FOR C COEFFICIENT (SEE SSTCS2)
!   CSINWT             SIN(SSTFRQ*TDIFF) FOR C COEFFICIENT (SEE SSTCS2)
!   SCOSWT             COS(SSTFRQ*TDIFF) FOR S COEFFICIENT (SEE SSTCS2)
!   SSINWT             SIN(SSTFRQ*TDIFF) FOR S COEFFICIENT (SEE SSTCS2)
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION(A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/GEODEG/NMAX,NMAXP1,NP,NTOLD,NTOLO,NADJC,NADJS,NADJCS,      &
     &              NPMAX,NXGDEG
      COMMON/GEOMCS/MDEGEO,MORGEO,NPGEOM,NXGEOM
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/SSTCOM/NCBAR, NSBAR ,NCDOT ,NSDOT ,NCAPRD,NCBPRD,NSAPRD,   &
     &              NSBPRD,NCBARA,NSBARA,NCDOTA,NSDOTA,NCAPDA,NCBPDA,   &
     &              NSAPDA,NSBPDA,ISSTEP,NXSST
      COMMON/SSTPTR/KCBAR, KSBAR ,KCDOT ,KSDOT ,KCAPRD,KCBPRD,KSAPRD,   &
     &              KSBPRD,KCBARA,KSBARA,KCDOTA,KSDOTA,KCAPDA,KCBPDA,   &
     &              KSAPDA,KSBPDA,NSSTOT,NSSTDP
      COMMON/VRBLOK/SINPSI,COSPSI,XLAMDA,GMR,AOR
!
      DIMENSION SINLAT(NM),COSLAT(NM),COSLON(NM),SINLON(NM),C(1),S(1),  &
     &          P(1),COSLAM(*),SINLAM(*),                               &
     &          EXPART(NPGEOM,2),SSTS(NM),PMPA(NDIM1,NDIM2),WORK(1),    &
     &          IPTRUA(1),IPTRAU(1),AA(1),II(1),FSEC(NM),ISSTNA(1)
      DIMENSION CCOSWT(1),CSINWT(1),SCOSWT(1),SSINWT(1),SSS(NM)
      DIMENSION SINEL(500)
      DIMENSION LAVOID(1)
! NOTE IN THE POINT ZERO VERSION ALLOW IN IIS (KORP04) THE KEXTRA TO
! ALLOCATE FOR MINTIM ANYWAY AND HERE REMOVE THE SSS ARRAY AND LEAVE THE
!
      DATA ZERO/0.D0/,ONE/1.D0/
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
      IF(LRADAR) THEN
      DO I=1,NM
      SINEL(I)=ONE
      ENDDO
      ELSE
      DO I=1,NM
      SINEL(I)=SSS(I)
      ENDDO
      ENDIF
! INITIALIZE POINTERS
      NMAXL1=MDEGEO-1
! NUMBER OF ADJ C&S TERMS
      NAJSSC=NPVAL0(IXSSTC)
      NAJSSS=NPVAL0(IXSSTS)
! POINTER TO START OF ADJ C&S  IN PAMV0 ARRAY
      IBEGC =IPVAL0(IXSSTC)
      IBEGS =IPVAL0(IXSSTS)
! POINTER TO START OF PERIODIC TERMS IN PARMV AARAY
      ICAPTR=IPVAL(IXSSTC)+KCAPRD-1
      ICBPTR=IPVAL(IXSSTC)+KCBPRD-1
      ISAPTR=IPVAL(IXSSTC)+KSAPRD-1
      ISBPTR=IPVAL(IXSSTC)+KSBPRD-1
!
! IF C(0,0) TERM (C(1)) IS ADJUSTED, SET LOGICAL FLAG TO TRUE
      IF(NAJSSC.GT.0)THEN
      LASST0=ISSTNA(1).LT.0
      ENDIF
! IF CDOT(0,0) TERM (C(1)) IS ADJUSTED, SET LOGICAL FLAG TO TRUE
      IF(NAJSSC.GT.0)THEN
      LSSTD0=ISSTNA(KCDOTA).LT.0
      ENDIF
!
      DO 500 I=1,NM
!
! INCORPORATE TIME DEPENDENT TERMS INTO C&S COEFFICIENTS
      IF(NSSTDP.GT.0) THEN
      CALL SSTCS2(MJDSBL,FSEC(I),II(KSSTNM),AA(KPRMV),                  &
     &            C,S,AA(KSSTFQ),TDIFF,CCOSWT,CSINWT,SCOSWT,SSINWT)
      ENDIF
!
! CALCULATE COSLAM&SINLAM ARRAYS
! THIS IS DONE EXTERNALLY TO LGENDR TO SAVE TANPSI CALCULATIONS
      SINLAM(2)=SINLON(I)
      COSLAM(2)=COSLON(I)
      CL2=COSLAM(2)+COSLAM(2)
      SINLAM(3)=CL2*SINLAM(2)
      COSLAM(3)=CL2*COSLAM(2)-ONE
      DO 20 N=2,NMAXL1
      N1=N+1
      N2=N+2
      SINLAM(N2)=CL2*SINLAM(N1)-SINLAM(N)
      COSLAM(N2)=CL2*COSLAM(N1)-COSLAM(N)
   20 END DO
      COSPSI=COSLAT(I)
      SINPSI=SINLAT(I)
!
! COMPUTE LGENDR POLYNOMIALS
      CALL LGENDR(.TRUE.,AA(KXNRMZ),AA(KXNRMC),AA(KVRARY),P,            &
     &            AA(KAORN),SINLAM,COSLAM,AA(KTANPS),MDEGEO)
!
!  (1)CALCULATE ALL PARTIALS UP TO DEGREE MDEGEO (VECTORIZED)
!  (2)IF SST REQUIRED,DOT PRODUCT THIS WITH C &S COEFFCIENTS
!  (3)IF PARTIALS REQUIRED,THEN SQUEEZE PARTIALS OUT OF FULL ARRAY
!
      KRA1=0
      KNL=2
      DO 110 N=1,MDEGEO
      DO 105 KR=1,KNL
      KRAA=KR+KRA1
      EXPART(KRAA,1)=COSLAM(KR)*P(KRAA)
      EXPART(KRAA,2)=SINLAM(KR)*P(KRAA)
  105 END DO
      KRA1=KRA1+N+3
      KNL=KNL+1
  110 END DO
!
! IF SEA SURFACE HEIGHTS NOT REQUIRED, SKIP TO STORING PARTIALS
       IF(.NOT.LSSTMD.AND.LRADAR) GO TO 140
!
! COMPUTE SEA SURFACE HEIGHTS
! C ARRAY STARTS AT 4 BECAUSE OF CONSTANT TERM STORED IN DEG=0,ORD=0
!
      HGHT=ZERO
      DO 130 N=1,NPGEOM
      NPT=NPGEOM+1-N
      HGHT=HGHT+EXPART(NPT,1)*C(NPT+3)+EXPART(NPT,2)*S(NPT)
  130 END DO
!
! ADD ON CONSTANT TERM AND STORE SEA SURFACE HEIGHT
      SSTS(I)=HGHT+C(1)
!
! IF PARTIALS NOT REQUIRED, PROCESS NEXT OBSERVATION
      IF (.NOT.LSSTAJ) GOTO 500
      IF (.NOT.LOAD) GOTO 500
  140 CONTINUE
!
! CHECK IF NUMBER OF PARAMETRS IS THE FIRST DIMENSION OF PMPA
      IF(.NOT.LNPNM) GO TO 300
!
! STORE PARTALS WRT C INTO PARTIAL ARRAY PMPA
      IF(NAJSSC.LE.0) GO TO 151
!
      IF(LASST0) GOTO 142
! CODE DOES NOT INCLUDE ADJUSTMENT OF C(0,0) TERM
!
! STORE CBAR PARTIALS
      DO 141 J=1,NCBARA
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)= -EXPART(ISSTNA(J),1)/SINEL(I)
  141 END DO
      GOTO 144
!
  142 CONTINUE
! CODE DOES INCLUDE ADJUSTMENT OF C(0,0) TERM
!
! STORE CBAR PARTIALS
      LAVOID(IBEGC)=.FALSE.
      PMPA(IBEGC,I)=-ONE/SINEL(I)
      DO 143 J=2,NCBARA
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)= -EXPART(ISSTNA(J),1)/SINEL(I)
  143 END DO
  144 CONTINUE
!
      IF(NSSTDP.LE.0) GOTO 151
! STORE CDOT PARTIALS
      IF(LSSTD0) THEN
      PMPA(IBEGC+KCDOTA-1,I)=-TDIFF/SINEL(I)
      LAVOID(IBEGC+KCDOTA-1)=.FALSE.
      DO 145 J=KCDOTA+1,KCAPDA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)= -EXPART(ISSTNA(J),1)*TDIFF/SINEL(I)
  145 END DO
      ELSE
      DO 146 J=KCDOTA,KCAPDA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)= -EXPART(ISSTNA(J),1)*TDIFF/SINEL(I)
  146 END DO
      ENDIF
!
! STORE CAPRD PARTIALS
! FIND APPROPRIATE COSWT POINTER (COSWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      DO 147 J=KCAPDA,KCBPDA-1
      IIIPTR=IPTRAU(IBEGC+J-1)-ICAPTR+1
      IF(ISSTNA(J).LT.0) THEN
         LAVOID(IBEGC+J-1)=.FALSE.
         PMPA(IBEGC+J-1,I)=-CCOSWT(IIIPTR)/SINEL(I)
      ELSE
         LAVOID(J+IBEGC-1)=.FALSE.
         PMPA(J+IBEGC-1,I)=-EXPART(ISSTNA(J),1)*CCOSWT(IIIPTR)/SINEL(I)
      ENDIF
  147 END DO
! STORE CBPRD PARTIALS
! FIND APPROPRIATE SINWT POINTER (SINWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      DO 149 J=KCBPDA,KSBARA-1
      IIIPTR=IPTRAU(IBEGC+J-1)-ICBPTR+1
      IF(ISSTNA(J).LT.0) THEN
       LAVOID(J+IBEGC-1)=.FALSE.
       PMPA(J+IBEGC-1,I)=-CSINWT(IIIPTR)/SINEL(I)
      ELSE
       LAVOID(J+IBEGC-1)=.FALSE.
       PMPA(J+IBEGC-1,I)=-EXPART(ISSTNA(J),1)*CSINWT(IIIPTR)/SINEL(I)
      ENDIF
  149 END DO
!
  151 CONTINUE
!
! STORE PARTIALS WRT S INTO PARTIAL ARRAY PMPA
      IF(NAJSSS.LE.0) GO TO 200
! STORE SBAR PARTIALS
      DO 160 J=KSBARA,KSDOTA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)=-EXPART(ISSTNA(J),2)/SINEL(I)
  160 END DO
!
      IF(NSSTDP.LE.0) GOTO 200
! STORE SDOT PARTIALS
      DO 170 J=KSDOTA,KSAPDA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)= -EXPART(ISSTNA(J),2)*TDIFF/SINEL(I)
  170 END DO
! STORE SAPRD PARTIALS
      DO 180 J=KSAPDA,KSBPDA-1
! FIND APPROPRIATE SINWT POINTER (COSWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      IIIPTR=IPTRAU(IBEGC+J-1)-ISAPTR+1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)=-EXPART(ISSTNA(J),2)*SCOSWT(IIIPTR)/SINEL(I)
  180 END DO
! STORE SBPRD PARTIALS
      DO 190 J=KSBPDA,KSBPDA+NSBPDA-1
! FIND APPROPRIATE SINWT POINTER (SINWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      IIIPTR=IPTRAU(IBEGC+J-1)-ISBPTR+1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(J+IBEGC-1,I)=-EXPART(ISSTNA(J),2)*SSINWT(IIIPTR)/SINEL(I)
  190 END DO
!
  200 CONTINUE
      GO TO 500
!
! NUMBER OF PARAMETRS IS THE SECOND DIMENSION OF PMPA
  300 CONTINUE
!
! STORE PARTALS WRT C INTO PARTIAL ARRAY PMPA
      IF(NAJSSC.LE.0) GO TO 400
!
      IF(LASST0) GOTO 320
! CODE DOES NOT INCLUDE ADJUSTMENT OF C(0,0) TERM
! STORE CBAR PARTIALS
      DO 310 J=1,NCBARA
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)= -EXPART(ISSTNA(J),1)/SINEL(I)
  310 END DO
      GOTO 340
!
  320 CONTINUE
! CODE DOES INCLUDE ADJUSTMENT OF C(0,0) TERM
! STORE CBAR PARTIALS
      LAVOID(IBEGC)=.FALSE.
      PMPA(I,IBEGC)=-ONE/SINEL(I)
      DO 330 J=2,NCBARA
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)= -EXPART(ISSTNA(J),1)/SINEL(I)
  330 END DO
  340 CONTINUE
!
      IF(NSSTDP.LE.0) GOTO 400
! STORE CDOT PARTIALS
      IF(LSSTD0) THEN
       LAVOID(IBEGC+KCDOTA-1)=.FALSE.
       PMPA(I,IBEGC+KCDOTA-1)=-TDIFF/SINEL(I)
       DO 355 J=KCDOTA+1,KCAPDA-1
        LAVOID(J+IBEGC-1)=.FALSE.
        PMPA(I,J+IBEGC-1)= -EXPART(ISSTNA(J),1)*TDIFF/SINEL(I)
  355  CONTINUE
      ELSE
       DO 356 J=KCDOTA,KCAPDA-1
        LAVOID(J+IBEGC-1)=.FALSE.
        PMPA(I,J+IBEGC-1)= -EXPART(ISSTNA(J),1)*TDIFF/SINEL(I)
  356  CONTINUE
      ENDIF
!
! STORE CAPRD PARTIALS
! FIND APPROPRIATE COSWT POINTER (COSWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      DO 358 J=KCAPDA,KCBPDA-1
      IIIPTR=IPTRAU(IBEGC+J-1)-ICAPTR+1
      IF(ISSTNA(J).LT.0) THEN
         LAVOID(J+IBEGC-1)=.FALSE.
         PMPA(I,J+IBEGC-1)=-CCOSWT(IIIPTR)/SINEL(I)
      ELSE
        LAVOID(J+IBEGC-1)=.FALSE.
        PMPA(I,J+IBEGC-1)=-EXPART(ISSTNA(J),1)*CCOSWT(IIIPTR)/SINEL(I)
      ENDIF
  358 END DO
! STORE CBPRD PARTIALS
! FIND APPROPRIATE SINWT POINTER (SINWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      DO 365 J=KCBPDA,KSBARA-1
      IIIPTR=IPTRAU(IBEGC+J-1)-ICBPTR+1
      IF(ISSTNA(J).LT.0) THEN
         LAVOID(J+IBEGC-1)=.FALSE.
         PMPA(I,J+IBEGC-1)=-CSINWT(IIIPTR)/SINEL(I)
      ELSE
         LAVOID(J+IBEGC-1)=.FALSE.
         PMPA(I,J+IBEGC-1)=-EXPART(ISSTNA(J),1)*CSINWT(IIIPTR)/SINEL(I)
      ENDIF
  365 END DO
!
  400 CONTINUE
!
! STORE PARTIALS WRT S INTO PARTIAL ARRAY PMPA
      IF(NAJSSS.LE.0) GO TO 500
! STORE SBAR PARTIALS
      DO 410 J=KSBARA,KSDOTA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)=-EXPART(ISSTNA(J),2)/SINEL(I)
  410 END DO
!
      IF(NSSTDP.LE.0) GOTO 500
! STORE SDOT PARTIALS
      DO 420 J=KSDOTA,KSAPDA-1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)= -EXPART(ISSTNA(J),2)*TDIFF/SINEL(I)
  420 END DO
! STORE SAPRD PARTIALS
      DO 430 J=KSAPDA,KSBPDA-1
! FIND APPROPRIATE COSWT POINTER (COSWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      IIIPTR=IPTRAU(IBEGC+J-1)-ISAPTR+1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)=-EXPART(ISSTNA(J),2)*SCOSWT(IIIPTR)/SINEL(I)
  430 END DO
! STORE SBPRD PARTIALS
      DO 440 J=KSBPDA,KSBPDA+NSBPDA-1
! FIND APPROPRIATE SINWT POINTER (SINWT STORED IN PARMV UNADJ ORDER)
! THE IPTRAU(IBEGC+J-1) IS POINTER OF ADJ PARAM. IN PARMV ARRAY
      IIIPTR=IPTRAU(IBEGC+J-1)-ISBPTR+1
      LAVOID(J+IBEGC-1)=.FALSE.
      PMPA(I,J+IBEGC-1)=-EXPART(ISSTNA(J),2)*SSINWT(IIIPTR)/SINEL(I)
  440 END DO
!
  500 END DO
      RETURN
      END
