!$SSTCS1
      SUBROUTINE SSTCS1(ISSTNM,PARMV,C,S)
!*********1*********2*********3*********4*********5*********6*********7
! SSTCS1            08/09/89            0000.0    PGMR - A. MARSHALL
!
! FUNCTION: INITIALIZES POINTERS AND ARRAYS FOR TIME INDEPENDENT
!           SEA SURFACE TOPOGRAPHY C&S COEFFICIENTS.
!           CALLED ONCE FOR EACH GLOBAL ITERATION
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   ISSTNM   I         INDEX ARRAY FOR NOFFSETS OF SEA SURFACE
!                      TOPOGRAPHY
!   PARMV    I         PARAMETERS ARRAY PASSED FROM IIS
!   C        O         C SEA SURFACE TOPOGRAPHY COEFFICIENTS
!   S        O         S SEA SURFACE TOPOGRAPHY COEFFICIENTS
!
! COMMENTS: ISSTNM IS STORED IN THE FOLLOWING ORDER
!            CBAR,CDOT,CAPRD,CBPRD,SBAR,SDOT,SAPRD,SBPRD
!
!*********1*********2*********3*********4*********5*********6*********7
      IMPLICIT DOUBLE PRECISION(A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/GEOMCS/MDEGEO,MORGEO,NPGEOM,NXGEOM
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/SSTCOM/NCBAR, NSBAR ,NCDOT ,NSDOT ,NCAPRD,NCBPRD,NSAPRD,   &
     &              NSBPRD,NCBARA,NSBARA,NCDOTA,NSDOTA,NCAPDA,NCBPDA,   &
     &              NSAPDA,NSBPDA,ISSTEP,NXSST
      COMMON/SSTPTR/KCBAR, KSBAR ,KCDOT ,KSDOT ,KCAPRD,KCBPRD,KSAPRD,   &
     &              KSBPRD,KCBARA,KSBARA,KCDOTA,KSDOTA,KCAPDA,KCBPDA,   &
     &              KSAPDA,KSBPDA,NSSTOT,NSSTDP
!
      DIMENSION ISSTNM(1),PARMV(1),C(1),S(1)
!
      DATA ZERO/0.D0/
!
!**********************************************************************
! START OF EXECUTABLE CODE ********************************************
!**********************************************************************
!
! DETERMINE POINTER FOR START OF SST C&S COEFFICIENTS IN PARMV ARRAY
      ISTRTC=IPVAL(IXSSTC)
      ISTRTS=IPVAL(IXSSTS)
! INITIALIZE C & S ARRAYS
      DO 100 I=1,NPGEOM
      C(I+3)=ZERO
      S(I)=ZERO
  100 END DO
! INITALIZE DEGREE ZERO TERMS FOR C ARRAY
      DO 150 I=1,3
      C(I)=ZERO
  150 END DO
!
! STORE TIME INDEPENDENT (MEAN) C COEFFICIENTS
      DO 200 I=1,NCBAR
      C(ISSTNM(I)) = PARMV(ISTRTC+I-1)
  200 END DO
! STORE TIME INDEPENDENT (MEAN) S COEFFICIENTS
      DO 300 I=KSBAR,KSBAR+NSBAR-1
      S(ISSTNM(I)) = PARMV(ISTRTC+I-1)
  300 END DO
      RETURN
      END
