!$STARTD
      SUBROUTINE STARTD(LORBIT,LNDRAG,IORDER,H,                         &
     &   MJDSEC,FSEC,NSAT,N3,NEQN,NEQN3,IOL1,CIPV,                      &
     &   CIVV,XP,X,SUMX,XDDOT,PX,SUMPX,PXDDOT,XDDTMC,                   &
     &   DNLT,TOPXAT,LTPXAT,AA,II,LL,ISATID,UTDT,XDDTNC,PXDDTH,         &
     &   LFHIRT,LSURFF,XDDTAC,PXDDAC,NEQNAC,IPTFBS,NPRMAC,DYNTIM,       &
     &   NPERDY,EXACCT,EXACIN,EXACOB,LACCELS,ACCTIM,ACCPER,NPERAC,      &
     &   SUMRC,XDDRC,                                                   &
     &   TMOS0,TMOS,TMOSP,SUMXOS,SUMPOS,XDDTOS,PDDTOS,NSTEPS,NEQNI,HOS, &
     &   NEQNA,NEQNA3,SUMXA,XDDOTA,PXA,SUMPXA,PXDDTA,XA,XR,XRDOT,SUMXR, &
     &   XMNRT,ISQ,PXA0,LPXA0,XRP,XA2,SUMXA2,XDDTA2,PXA2,SMPXA2,        &
     &   PXDDA2,PXA20,XR2,XR2P,XRDOT2,SUMXR2,GM2,IDA1,IDA2)
!********1*********2*********3*********4*********5*********6*********7**
! START            82/08/27            8208.0    PGMR - TOMA MARTIN
!
! FUNCTION:  USE A MULTI-STEP PROCEDURE WITH TAYLOR SERIES
!            FIRST APPROXIMATION TO START THE NUMERICAL
!            INTEGRATION PROCESS AND PRODUCE SUFFICIENT
!            BACK VALUES FOR THE COWELL INTEGRATOR TO CONTINUE
!            THE INTEGRATION.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   LORBIT   I    S    LOGICAL SWITCH INDICATING ORBIT-ONLY
!                      INTEGRATION WHEN .TRUE.
!   LNDRAG   I    S    LOGICAL SWITCH INDICATING THAT THE
!                      FORCING FUNCTION IS VELOCITY INDEPENDENT
!                      WHEN .TRUE.
!   IORDER   I    S    ORDER OF COWELL INTEGRATION FOR ORBIT
!   H        I    S    INTEGRATION STEP SIZE IN SECONDS FOR ORBIT
!   MJDSEC   I    S    CURRENT DATE AND INTEGRAL SECONDS OF TIME O
!                      ORBIT INTEGRATION
!   FSEC     I    S    CURRENT FRACTIONAL SECONDS OF ORBIT TIME
!   NSAT     I    S    NUMBER OF SATELLITES OF LIKE CHARACTERISTICS
!                      TO BE SIMULATANEOUSLY INTEGRATED
!   N3       I    S    NSAT*3
!   NEQN     I    S    NUMBER OF FORCE MODEL VARIATIONAL EQUATIONS
!   NEQN3    I    S    NEQN*N3
!   IOL1     I    S    IORDER - 1
!   CIPV     I    A    COWELL COEFFICIENTS FOR INTERPOLATING
!                      POSITION
!   CIVV     I    A    COWELL COEFFICIENTS FOR INTERPOLATING
!                      VELOCITY
!   XP       I    A    PREDICTED S/C POS. AND VEL.
!   X        O    A    CORRECTED SC POS. AND VEL.
!   SUMX     O    A    INTEGRATION SUMS FOR ORBIT
!   XDDOT    O    A    ORBIT ACCELERATIONS
!   PX,PX3   O    A    CORRECTED VARIATIONAL EQUATIONS
!   SUMPX    O    A    INTEGRATION SUMS FOR VAR. EQ.
!   PXDDOT   O    A    VARIATIONAL ACCELERATIONS
!   XDDTMC   O    A    ORBIT ACCELERATIONS DUE TO POINT MASS
!   DNLT     O    A    CHANGE IN NODE DUE TO LENSE THIRRING
!                      INITIALIZED TO ZERO
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   TOPXAT   O    A    TOPEX ATT. BACK VALUES (BETAPRIME & ORBIT ANGLE)
!   LTPXAT   O    A    TOPEX ATT. BACK VALUES (RAMPING LOGICALS)
!   PXDDT3   O    A    VARIATIONAL ACCELERATIONS
!   ISATID   I         SAT ID ARRAY
!   XDDTNC   O         SMALL FORCE ACCELERATIONS (ACCELEROMETRY
!                      COMPUTED AND/OR SEPARATELY INTEGRATED)
!   PXDDTH   O         ARRAY TO HOLD THE EXPLICIT (NON INTEGRATED)
!                      FORCE MODEL PARTIALS
!   LFHIRT   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!   LSURFF   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!
!                      ACCELEROMETRY
!   PXDDAC   O    A    PARTIAL DERIVATIVES OF XDDTAC
!   NEQNAC   I    S    NUMBER OF ADJUSTING ACCELEROMTER PARTIALS
!   IPTFBS   I    A    MAPPING ARRAY ; EXPLICIT PARTIAL ARRAY TO
!                      COMPUTED ACCELERATION PARTIAL ARRAY
!   NPRMAC   I    A    NUMBER OF PARMETERS IN EACH FORCE MODEL
!                      GROUP CATEGORY YO BE MAPPED BY IPTFBS
!   DYNTIM   I    A    USER REQUESTED START AND STOP TIMES FOR
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
!   NPERDY   I    A    NUMBER OF USER REQUESTED
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      CHARACTER*18 CARD
      SAVE
      DIMENSION CIPV(IOL1,IORDER),CIVV(IOL1,IORDER),                    &
     &   XP(N3,2),X(N3,2),SUMX(N3,2,2),XDDOT(N3,IOL1,2),                &
     &   PX(NEQN3,2),  SUMPX(NEQN3,2,2),                                &
     &   PXDDOT(NEQN3,IOL1,2),XDDTMC(N3,1),DNLT(N3),                    &
     &   AA(1),II(1),LL(1),ISATID(1),XDDTNC(N3,IOL1,2),                 &
     &   SUMRC(NSAT,2),XDDRC(NSAT,IOL1)
!      DIMENSION XPA(3,2),XA(3,2),SUMXA(N3,2,2),XDDOTA(N3,IOL1,2),       &
!     &   PXA(NEQNA3,2),SUMPXA(NEQNA3,2,2),                              &
!     &   PXDDTA(NEQNA3,IOL1,2)
      DIMENSION XPA(3,2),XA(3,2),SUMXA(N3,2,2),                         &
     &   XDDOTA(N3,IOL1,2),PXA(NEQNA3,2),SUMPXA(NEQNA3,2,2),            &
     &   PXDDTA(NEQNA3,IOL1,2),PXA0(NEQNA3,2)
! THE SECOMDARY ASTEROID ARRAYS CAN NOT BE CONSOLODATED INTO THE
! PRIMARY ASTEROID ARRAYS BECAUSE THE FUKK SET OF BACK VALUES
! IS NOT BEING USED
      DIMENSION XPA2(3,2),XA2(3,2),SUMXA2(N3,2,2),                      &
     &   XDDTA2(N3,IOL1,2),PXA2(NEQNA3,2),SMPXA2(NEQNA3,2,2),           &
     &   PXDDA2(NEQNA3,IOL1,2),PXA20(NEQNA3,2)
      DIMENSION XDDP(3)
      DIMENSION TRQP(3),TRQS(3)
      DIMENSION VMATA(3,6)
      DIMENSION VMATA2(3,6)
      DIMENSION XDDCM2(3)
      DIMENSION S(20),B(20),FSECS(20),FSECSS(20)
      DIMENSION TOPXAT(2*NSAT,IOL1),LTPXAT(3*NSAT,IOL1)
      DIMENSION PXDDTH(NEQN3,IOL1)
      DIMENSION LFHIRT(NHRATE),LSURFF(NSURF),IPTFBS(MXFMG)
      DIMENSION NPRMAC(MXHRG)
      DIMENSION XDDTAC(3,NFSCAC,NSAT,IOL1),PXDDAC(NEQNAC,N3,IOL1)
      DIMENSION DYNTIM(MDYNPD,2,NSAT),NPERDY(NSAT)
      DIMENSION EXACCT(2,NSAT),EXACIN(NSAT),EXACOB(MACOBS,NSAT)
      DIMENSION ACCTIM(MBAPPD,2,NSAT),ACCPER(MBAPPD,NSAT),NPERAC(NSAT)
      DIMENSION UTDT(MINTIM,4)
      DIMENSION XRC(2)
      DIMENSION TMOS0(1),TMOS(1),TMOSP(1),OS(1)
      DIMENSION SUMXOS(3,2,1)
      DIMENSION SUMPOS(NEQNI,3,2,1)
      DIMENSION XDDTOS(3,NSTEPS,1)
      DIMENSION PDDTOS(NEQNI,3,NSTEPS,1)
      DIMENSION HOS(1)
      DIMENSION XDDSUN(3),XDDCMP(3)
      DIMENSION XMNRT(3)
!... Begin TJS...
!...  DIMENSION XR(12,2),XRP(12,2),XRDOT(12,IOL1,2),SUMXR(12,2,2)
      DIMENSION XR(NDPOR,2),XRP(NDPOR,2),XRDOT(NDPOR,IOL1,2)
      DIMENSION SUMXR(NDPOR,2,2)
! THE SECOMDARY ASTEROID ARRAYS CAN NOT BE CONSOLODATED INTO THE
! PRIMARY ASTEROID ARRAYS BECAUSE THE FUKK SET OF BACK VALUES
! IS NOT BEING USED
      DIMENSION XR2(NDPOR,2),XR2P(NDPOR,2),XRDOT2(NDPOR,IOL1,2)
      DIMENSION SUMXR2(NDPOR,2,2)
!... End TJS...
      DIMENSION PDUM(1)
      DIMENSION HOLDA(6,100),FSCUTC(1),IYMD(1),IHM(1),SEC(1)
      DIMENSION XDDBRN(3)
      COMMON/ASTLGT/CBODY1(7)
      COMMON/ASTSUN/BDAST(6),GMSAT,GEOPTS(3)
      COMMON/ACCLRM/MDYNPD,MBAPPD,MACOBS,IDYNSC(200),MDYNST,IACCSC(200),&
     &              MACCSC,NACPRM(200),NATPRM(200),NXCLRM
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/AXIS/LINTAX
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORA07/KELEVT,KSRFEL,KTINT,KFSCSD,KXTIM,KFSDM,             &
     & KSGM1,KSGM2,KNOISE,KEPHMS,NXCA07
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI07/KSMSA1,KSMSA2,KSMSA3,KSMST1,KSMST2,KSMST3,KSMTYP,   &
     &              KSMT1,KSMT2,KMSDM,KIOUT,KISUPE,NXCI07
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CRDDIM/NDCRD2,NDCRD3,NDCRD4,NDCRD5,NDCRD6,NDCRD7,          &
     &              NDCRD8,NDCRD9,NXCRDM
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IEPHM2/ISUPL,ICBODY,ISEQB(2),MAXDEG,ITOTSE,IREPL(988), &
     &              NXEPH2
      COMMON/INERTIA/WMNRT(6,2)
      COMMON/LASTER/LASTR(2),LBINAST,NXASTR
      COMMON/LCBODY/LEARTH,LMOON,LMARS
      COMMON/LDUAL/LASTSN,LSTSNX,LSTSNY
      COMMON/LEPHM2/LXEPHM
      COMMON/LSTRT/LSTART
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/RAMPI/MJDRMP,NRAMPS
      COMMON/RAMPA/SF1,SF2,FREQO,RBIAS
      COMMON/SETPPT/JSPDRG(3),JSPSRD(3),JSPGA(3),JCSAT
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
!... Begin TJS...
!
! NEW NAMED COMMON BLOCK "PORINF" (found also in EXPLOR and STARTD)
! introduce new named common block for planetary orientation information in
! order to get current omega and R states (PLOR(1:12)), current partials of
! omega and R with respect to omega_0 and R_0 (PLOR(13:156)), partials of
! omega and R with respect to six independent moments of inertia
! (PLOR(157:228)), and partials of omega_0 and R_0 with respect to RA_0,
! DEC_0, W_0, RA_t_0, DEC_t_0, and W_t_0 (DO0DA0)
      COMMON/PORINF/PLOR(228,2),DO0DA0(12,6,2)
!... End TJS...
!
      DATA ZERO/0.0D0/,ONE/1.0D0/
      DATA MAXMUM/20/
      DATA XRC/2*0.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      DIAG1=ONE
      DIAG2=ONE
      IF(LSTSNX) DIAG1=ZERO
      IF(LSTSNY) DIAG2=ZERO
      IF(LSTINR.AND.ISQ.EQ.1) THEN
        DO I=1,18
          CARD(I:I)=' '
        ENDDO
        CALL SYSTEM('rm CBTRAJ')
        OPEN(UNIT=77,FILE='CBTRAJ',FORM='FORMATTED',STATUS='NEW')
      ENDIF
!
      NRAT=1
      LHIRAT=.FALSE.
      LALLA=.TRUE.
!
      N=N3/3
      DO 15 I=1,N
      DNLT(I)=ZERO
   15 END DO
!      LSTART=.TRUE.
      N6=N3*2
      NEQN6=NEQN3*2
      NEQNA6=NEQNA3*2
      IOL2=IOL1-1
      IEVEN=MOD(IOL1,2)
      MF=IOL2/2-IEVEN
      MB=MF+1+IEVEN
      MID=MB+1
      MF1=MF+1
      ISH=H
      FSH=H-ISH
      H2=H**2
!   CALCULATE TIMES AT WHICH FORCE MODEL MUST BE EVALUATED
!   STORE EPOCH TIME
      FSECS(MID)=FSEC
!   COMPUTE TIMES OF BACK VALUES
      DO 40 I=1,MB
      J=MID-I
      FSEC=FSEC-H
   40 FSECS(J)=FSEC
!   COMPUTE TIMES OF FORWARD VALUES
      FSEC=FSECS(MID)
      DO 50 I=1,MF
      J=I+MID
      FSEC=FSEC+H
   50 FSECS(J)=FSEC
!   GET QUANTITIES NEEDED FOR COORDINATE SYSTEM EVALUATIONS
      ISN0=0
      ISN1=1
      IF(H.GT.ZERO) GO TO 55
      ISN0=IOL1+1
      ISN1=-1
   55 DO 57 I=1,IOL1
   57 FSECSS(I)=FSECS(I*ISN1+ISN0)
!
      IF(ICBDGM.EQ.3) THEN
      CALL BUFEAR(MJDSEC,FSECS(1),MJDSEC,FSECS(IOL1),ISN1,              &
     &   IDUM1,DUM2,LRECAL,AA,II)
      ELSE
      CALL BUFXTR(MJDSEC,FSECS(1),MJDSEC,FSECS(IOL1),ISN1,              &
     &   IDUM1,DUM2,LRECAL,AA)
!
      IF(LXEPHM) THEN
      DO IJ=1,ICBODY
      CALL BUFSUP(AA,MJDSEC,FSECS(1),MJDSEC,FSECS(IOL1),                &
     &II(KISUPE),AA(KEPHMS),IJ,1)
      ENDDO
      ENDIF
!
      ENDIF
!
      IF(.NOT.LRECAL) GO TO 60
      WRITE(6,999)
      STOP
   60 CONTINUE
!
      IF(ICBDGM.EQ.3) THEN
      CALL PRECSS(MJDSEC,FSECSS,AA(KETA),AA(KZTA),AA(KTHTA),            &
     &   AA(KSRTCH),IOL1)
      CALL NUVECT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),IOL1,     &
     &   AA(KSRTCH))
      CALL NPVECT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),AA(KETA), &
     &   AA(KTHTA),AA(KZTA),IOL1,AA(KSRTCH),AA(KROTMT),AA(KEQN),        &
     &   NDCRD2,.FALSE.)
      CALL GRHRAN(MJDSEC,FSECSS,.FALSE.,.FALSE.,AA(KEQN),AA(KSRTCH),    &
     &   AA(KTHG),AA(KCOSTG),AA(KSINTG),IOL1,AA,II,UTDT(1,1))
      ELSE
! NEW SUBROUTINE FOR MARS NUTATION CALCULATION
          IF(LMARS.AND.IMRNUT.EQ.1) THEN
      CALL PRMCSS(MJDSEC,FSECSS,AA(KETA),AA(KZTA),AA(KTHTA),            &
     &   AA(KSRTCH),IOL1)
      CALL NUVMCT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),IOL1,     &
     &   AA(KSRTCH))
      CALL NPVMCT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),AA(KETA), &
     &   AA(KTHTA),AA(KZTA),IOL1,AA(KSRTCH),AA(KROTMT),AA(KEQN),        &
     &   NDCRD2,.FALSE.)
      CALL MM2EJ2(MJDSEC,FSECSS,AA(KROTMT),NDCRD2,AA(KSRTCH),.TRUE.)
!
      CALL ROTMTR(MJDSEC,FSECSS,.FALSE.,AA(KEQN),AA(KSRTCH),            &
     &   AA(KTHG),AA(KCOSTG),AA(KSINTG),IOL1,AA,II)
          ELSE
      CALL PRXCSS(MJDSEC,FSECSS,AA(KETA),AA(KZTA),AA(KTHTA),            &
     &   AA(KSRTCH),IOL1,AA(KDPSI),AA(KEPST),AA(KEPSM),AA,1)
      CALL NUVXCT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),IOL1,     &
     &   AA(KSRTCH))
      CALL NPVXCT(MJDSEC,FSECSS,AA(KDPSI),AA(KEPST),AA(KEPSM),AA(KETA), &
     &   AA(KTHTA),AA(KZTA),IOL1,AA(KSRTCH),AA(KROTMT),AA(KEQN),        &
     &   NDCRD2,.FALSE.)
      CALL ROTXTR(MJDSEC,FSECSS,.FALSE.,AA(KEQN),AA(KSRTCH),            &
     &   AA(KTHG),AA(KCOSTG),AA(KSINTG),IOL1,AA,                        &
     &      AA(KACOSW),AA(KBSINW),AA(KANGWT),AA(KWT),AA(KACOFW),        &
     &      AA(KBCOFW),II,1)
      ENDIF
      ENDIF
!
!
!
!  START OF LINTAX INITIALIZATIONS
!
!
      IF(LINTAX) THEN
!... Begin TJS...
!...    DO I=1,12
        IF (ISQ == 1) THEN
          DO I=1,NDPOR
            XR(I,1)=0.D0
            XR(I,2)=0.D0
          ENDDO
          IF(LBINAST) THEN
            DO I=1,NDPOR
              XR2(I,1)=0.D0
              XR2(I,2)=0.D0
            ENDDO
          ENDIF
! Initialize d(omega)/d(omega_0) = I
          XR( 13,2)=1.D0
          XR( 26,2)=1.D0
          XR( 39,2)=1.D0
! Initialize d(axis)/d(axis_0) = I
          XR( 52,2)=1.D0
          XR( 65,2)=1.D0
          XR( 78,2)=1.D0
          XR( 91,2)=1.D0
          XR(104,2)=1.D0
          XR(117,2)=1.D0
          XR(130,2)=1.D0
          XR(143,2)=1.D0
          XR(156,2)=1.D0
          IF(LBINAST) THEN
! Initialize d(omega)/d(omega_0) = I
            XR2( 13,2)=1.D0
            XR2( 26,2)=1.D0
            XR2( 39,2)=1.D0
! Initialize d(axis)/d(axis_0) = I
            XR2( 52,2)=1.D0
            XR2( 65,2)=1.D0
            XR2( 78,2)=1.D0
            XR2( 91,2)=1.D0
            XR2(104,2)=1.D0
            XR2(117,2)=1.D0
            XR2(130,2)=1.D0
            XR2(143,2)=1.D0
            XR2(156,2)=1.D0
          ENDIF
        END IF
!... End TJS...
        RA=AA(KETA-1+MID)
        DEC=AA(KZTA-1+MID)
        W=AA(KTHG-1+MID)
        PIQ=ACOS(-1.D0)
        TPIQ=2.D0*ACOS(-1.D0)
        RA=MOD(RA,TPIQ)
        RA=RA+TPIQ
        RA=MOD(RA,TPIQ)
        DEC=MOD(DEC,TPIQ)
        DEC=DEC+TPIQ
        DEC=MOD(DEC,TPIQ)
        IF(DEC.GT.PIQ) DEC=DEC-TPIQ
        W=MOD(W,TPIQ)
        W=W+TPIQ
        W=MOD(W,TPIQ)
!...TJS DEBUG
        RAQ=RA*180.D0/ACOS(-1.D0)
        DECQ=DEC*180.D0/ACOS(-1.D0)
        WQ=W*180.D0/ACOS(-1.D0)
        RAQ=MOD(RAQ,360.D0)
        DECQ=MOD(DECQ,360.D0)
        WQ=MOD(WQ,360.D0)
        WRITE(6,78912) RAQ,DECQ,WQ
78912   FORMAT(' STARTD;  RA,DEC,W ',3F20.6)
!!!        RA=81.517346100D0*DACOS(-1.D0)/180.D0
!!!        DEC=-63.08844180D0*DACOS(-1.D0)/180.D0
!!!        W=13.318368072777039D0*DACOS(-1.D0)/180.D0
!...TJS DEBUG
!
        IF(ISQ.EQ.1) THEN
           RA      = MODULO(AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 1), TWOPI)
           RA_DOT  = AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 2)
           DEC     = MODULO(AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 3), TWOPI)
           DEC_DOT = AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 4)
           W       = MODULO(AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 5), TWOPI)
           W_DOT   = AA(KPRMVC-1 + IPVAL0(IXXTRO)-1 + 6)
           DO I=1,NDPOR
             XR(I,1)=0.D0
           ENDDO
           DO I=1,6
             WMNRT(I,1)=AA(KPRMV-1 + IPVAL(IXXTRO)-1 + NXTRAC-NMINRT+I)
           ENDDO
           CALL INITAX(RA,DEC,W,RA_DOT,DEC_DOT,W_DOT,XR(1,2),XR(4,2),AA)
           IF(LBINAST) THEN
             IOFF=IPVAL0(IXXTRO)-1+NPVAL0(IXXTRO)/2
             RA2     = MODULO(AA(KPRMVC-1 + IOFF + 1), TWOPI)
             RA_DT2  = AA(KPRMVC-1 + IOFF + 2)
             DEC2    = MODULO(AA(KPRMVC-1 + IOFF + 3), TWOPI)
             DEC_DT2 = AA(KPRMVC-1 + IOFF + 4)
             W2      = MODULO(AA(KPRMVC-1 + IOFF + 5), TWOPI)
             W_DT2   = AA(KPRMVC-1 + IOFF + 6)
             DO I=1,NDPOR
               XR2(I,1)=0.D0
             ENDDO
             DO I=1,6
               WMNRT(I,2)=AA(KPRMV-1+IPVAL(IXXTRO)+NPVAL(IXXTRO)-1-6+I)
             ENDDO
             CALL INITAX(RA2,DEC2,W2,RA_DT2,DEC_DT2,W_DT2,XR2(1,2),     &
     &                   XR2(4,2),AA)
           ENDIF
        ENDIF
!... Begin TJS...
        DO I=1,NDPOR
           PLOR(I,1)=XR(I,2)
           PLOR(I,2)=XR(I,2)
           IF(LBINAST) PLOR(I,2)=XR2(I,2)
        END DO
!... End TJS...
        IF(LBINAST) THEN
          CALL LOADAX(XR(4,2),XR2(4,2))
        ELSE
          CALL LOADAX(XR(4,2),XR(4,2))
        ENDIF
!... Begin TJS...
!
! compute partials of omega_0 and R_0 with respect to RA_0, DEC_0, W_0,
! RA_t_0, DEC_t_0, and W_t_0
         CALL GETDODA (XR(1,2),XR(4,2),DO0DA0)
         IF(LBINAST) CALL GETDODA (XR2(1,2),XR2(4,2),DO0DA0(1,1,2))
!... End TJS...
      ENDIF
!
!
!  END OF LINTAX INITIALIZATIONS
!
!  IN THE CASE OF BINARY ASTEROIDS AND .NOT.LINTAX, THE MOMENTS OF THE
!  SECONDARY ASTEROID ARE REQUIRED
      IF(.NOT.LINTAX.AND.LBINAST) THEN
        IPT1=KPRMV+IPVAL(IXXTRO)+NPVAL(IXXTRO)-7
        WMNRT(1,2)=AA(IPT1)
        WMNRT(2,2)=AA(IPT1+1)
        WMNRT(3,2)=AA(IPT1+2)
      ENDIF
!
      IF(LSTSNX) CALL GETAST(AA,IDA1,MJDSEC,FSECS(MID),XA)
      IF(LSTSNY) CALL GETAST(AA,IDA2,MJDSEC,FSECS(MID),XA2)
!
!
! EVALUATE FORCES AT EPOCH
      MIDD=MID*ISN1+ISN0

      BDAST(1)=XA(1,1)
      BDAST(2)=XA(2,1)
      BDAST(3)=XA(3,1)
      BDAST(4)=XA(1,2)
      BDAST(5)=XA(2,2)
      BDAST(6)=XA(3,2)
      IF(ISQ.EQ.1) THEN
        DO I=1,6
         CBODY1(I)=XA(I,1)
        ENDDO
        IF(LSTINR) THEN
         DO J=1,6
          HOLDA(J,MID)=BDAST(J)
         ENDDO
        ENDIF
      ENDIF
      CBODY1(7)=DBLE(ISQ)
!
! SECONARY ASTEROID
!
          XDDP(1)=0.D0
          XDDP(2)=0.D0
          XDDP(3)=0.D0
          IF(LBINAST) THEN
      CALL FASTIN(GM2,XA2,XDDP,                                         &
     &            XDDTA2(1,MID,1),TRQP,TRQS,VMATA2,0,                   &
     &            AA,II,MIDD,MJDSEC,FSECS(MID),PXDDTA(1,MID,1),         &
     &            PXDDA2(1,MID,1),NEQNA,NEQNA)
      CALL TRQMAT(GM2,XA2,TRQP,TRQS,AA,II,MIDD,MJDSEC,FSECS(MID))
          ENDIF
!
!
!
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),1,XDDP,XA2)
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),2,XDDP,XA2)
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),3,XDDP,XA2)
!
!
          IF(LBINAST) THEN
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),4,XDDP,XA2)
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),5,XDDP,XA2)
      CALL F123(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,&
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),6,XDDP,XA2)
          ENDIF
!
!
      HQ=H
      CALL F(MJDSEC,FSECS(MID),X,XDDOT(1,MID,1),PXDDOT(1,MID,1),NSAT,   &
     &   NEQN,MIDD,XDDTMC,TOPXAT(1,MID),LTPXAT(1,MID),AA,II,LL,ISATID,  &
     &   LFHIRT,LSURFF,XDDTNC(1,MID,1),XDDTAC(1,1,1,MID),               &
     &   PXDDAC(1,1,MID),                                               &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,MID),XDDP,XA2,LQ1,IPSBRN,LQ2,XDDBRN,HQ)
      IF(LQ1.OR.LQ2) THEN
        WRITE(6,60000)
        WRITE(6,60001)
        STOP
      ENDIF
      CALL FAST(MJDSEC,FSECS(MID),AA,II,LL,NEQNA,XA,VMATA,              &
     &          PXDDTA(1,MID,1),XDDOTA(1,MID,1),XDDSUN,XDDCMP,          &
     &          XDDOT(1,MID,1),X,XMNRT,XR(4,2),XR(1,2),                 &
     &          XRDOT(4,MID,1),XRDOT(1,MID,1),.FALSE.,XDDTMC,           &
     &          .FALSE.,MIDD,ONE,                                       &
!... Begin TJS...
! omega                           => XR(  1,2) => length   3 \
! axis                            => XR(  4,2) => length   9  \
!                                                              | Total
!                                                              | length = 228
! d(orientation)/d(orientation_0) => XR( 13,2) => length 144  /
! d(orientation)/d(inertia)       => XR(157,2) => length  72 /
     &          XR(13,2),XRDOT(13,MID,1),XR(157,2),XRDOT(157,MID,1),    &
     &          XDDP,1,TRQP,PXDDOT(1,MID,1),NEQN)
!... End TJS...
!
!
          IF(LBINAST) THEN
      CALL FAST2(XA2,XDDTA2(1,MID,1),XDDCM2,VMATA2)
      CALL FAST(MJDSEC,FSECS(MID),AA,II,LL,NEQNA,XA,VMATA,              &
     &          PXDDTA(1,MID,1),XDDOTA(1,MID,1),XDDSUN,XDDCMP,          &
     &          XDDOT(1,MID,1),X,XMNRT,XR2(4,2),XR2(1,2),               &
     &          XRDOT2(4,MID,1),XRDOT2(1,MID,1),.FALSE.,XDDTMC,         &
     &          .FALSE.,MIDD,ONE,                                       &
!... Begin TJS...
! omega                           => XR(  1,2) => length   3 \
! axis                            => XR(  4,2) => length   9  \
!                                                              | Total
!                                                              | length = 228
! d(orientation)/d(orientation_0) => XR( 13,2) => length 144  /
! d(orientation)/d(inertia)       => XR(157,2) => length  72 /
     &          XR2(13,2),XRDOT2(13,MID,1),XR2(157,2),XRDOT2(157,MID,1),&
     &          XDDP,2,TRQS,PXDDOT(1,MID,1),NEQN)
!... End TJS...
          ENDIF
!
!

!     IF(.NOT.LORBIT) THEN
!        DO IQP=1,NEQN3
!           PXDDTH(IQP,MID)=PXDDOT(IQP,MID,1)
!        ENDDO
!     ENDIF
! SAVE THE LOGICAL FLAG FOR SUMMARY INDICATING IF IN SUNLIGHT AT EPOCH
      DO 70 N=1,NSAT
      LL(KLSNLT+JCSAT+N-1)=LL(KLSTSN+JCSAT+N-1)
   70 END DO
!
      DO 100 N=1,N3
      XDDOT(N,MID,2)=XDDOT(N,MID,1)
      XDDTNC(N,MID,2)=XDDTNC(N,MID,1)
      XDDOTA(N,MID,2)=XDDOTA(N,MID,1)
      IF(LBINAST) XDDTA2(N,MID,2)=XDDTA2(N,MID,1)
  100 END DO
      IF(LINTAX) THEN
!... Begin TJS...
!...    DO N=1,12
        DO N=1,NDPOR
!... End TJS...
          XRDOT(N,MID,2)=XRDOT(N,MID,1)
          IF(LBINAST) XRDOT2(N,MID,2)=XRDOT2(N,MID,1)
        ENDDO
      ENDIF
      IF(LORBIT)GO TO 300
! EVALUATE FORCE MODEL PARTIAL DERIVATIVE ACCELERATIONS
!   INITIALIZE PARTIALS OF STATE VECTOR WRT FORCE PARAMETERS
      DO 132 NN=1,2
      DO 130 N=1,NEQN3
      PX(N,NN)=ZERO
  130 CONTINUE
      IF(.NOT.LPXA0) THEN
         DO 131 N=1,NEQNA3
         PXA(N,NN)=ZERO
         IF(LBINAST) PXA2(N,NN)=ZERO
  131    CONTINUE
      END IF
  132 CONTINUE
! INITIALIZE PARTIALS OF STATE VECTOR WRT TO INITIAL ELEMENTS
      NOFFST=NEQN*3
      DO 150 N=1,NEQN3,NOFFST
      PX(N,1)=ONE
      PX(N+NEQN+1,1)=ONE
      PX(N+2*NEQN+2,1)=ONE
      PX(N+3,2)=ONE
      PX(N+NEQN+4,2)=ONE
      PX(N+2*NEQN+5,2)=ONE
  150 END DO
      NOFFST=NEQNA*3
      IF(.NOT.LPXA0) THEN
         DO 151 N=1,NEQNA3,NOFFST
         PXA(N,1)=DIAG1
         PXA(N+NEQNA+1,1)=DIAG1
         PXA(N+2*NEQNA+2,1)=DIAG1
         PXA(N+3,2)=DIAG1
         PXA(N+NEQNA+4,2)=DIAG1
         PXA(N+2*NEQNA+5,2)=DIAG1
         IF(.NOT.LBINAST) GO TO 151
         PXA2(N,1)=DIAG2
         PXA2(N+NEQNA+1,1)=DIAG2
         PXA2(N+2*NEQNA+2,1)=DIAG2
         PXA2(N+3,2)=DIAG2
         PXA2(N+NEQNA+4,2)=DIAG2
         PXA2(N+2*NEQNA+5,2)=DIAG2
  151    END DO
      ELSE
         DO 152 N=1,NEQNA3
         PXA(N,1)=PXA0(N,1)
         PXA(N,2)=PXA0(N,2)
         IF(.NOT.LBINAST) GO TO 152
         PXA2(N,1)=PXA20(N,1)
         PXA2(N,2)=PXA20(N,2)
  152    END DO
      ENDIF
      CALL VEVAL(X,PX,PXDDOT(1,MID,1),AA,II,LL,NSAT,NEQN,.TRUE.,        &
     &   LNDRAG)
      CALL VEVALA(PXA,PXDDTA(1,MID,1),NEQNA,.TRUE.,VMATA,NEQN,          &
     &            PXDDOT(1,MID,1),.FALSE.,1)
         IF(LBINAST) THEN
      CALL VEVALA(PXA2,PXDDA2(1,MID,1),NEQNA,.TRUE.,VMATA2,NEQN,        &
     &            PXDDOT(1,MID,1),.FALSE.,2)
         ENDIF
!
      DO 200 N=1,NEQN3
      PXDDOT(N,MID,2)=PXDDOT(N,MID,1)
  200 END DO
      DO 201 N=1,NEQNA3
      PXDDTA(N,MID,2)=PXDDTA(N,MID,1)
      IF(LBINAST) PXDDA2(N,MID,2)=PXDDA2(N,MID,1)
  201 END DO
!
!
  300 CONTINUE
! PREDICT FORWARD USING TAYLOR SERIES
      CALL TAYLRA(LORBIT,H,1,MID,MF,IOL1,NSAT,                          &
     &   N3,N6,NEQN,NEQN3,NEQN6,MJDSEC,FSECS,                           &
     &   XP,X,XDDOT,PX,PXDDOT,ISN0,ISN1,LNDRAG,XDDTMC,TOPXAT,           &
     &   LTPXAT,AA,II,LL,ISATID,                                        &
     &   LFHIRT,LSURFF,XDDTNC,XDDTAC,PXDDAC,                            &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,DYNTIM,NPERDY,EXACCT,        &
     &   EXACIN,EXACOB,LACCELS,ACCTIM,ACCPER,NPERAC,XDDRC,              &
     &   NEQNA,NEQNA3,NEQNA6,XPA,XA,XDDOTA(1,1,1),PXA,                  &
     &   PXDDTA(1,1,1),XMNRT,XR(4,2),XRP(4,2),XR(1,2),XRP(1,2),         &
     &   XRDOT(1,1,1),                                                  &
!... Begin TJS...
     &   XR(13,2),XRP(13,2),XR(157,2),XRP(157,2),                       &
!... End TJS...
     &   XPA2,XA2,XDDTA2(1,1,1),PXA2,PXDDA2(1,1,1),                     &
     &   XR2(4,2),XR2P(4,2),XR2(1,2),XR2P(1,2),XRDOT2(1,1,1),           &
     &   XR2(13,2),XR2P(13,2),XR2(157,2),XR2P(157,2),GM2,IDA1,IDA2)
! PREDICT BACKWARD USING TAYLOR SERIES
      HMINUS=-H
      CALL TAYLRA(LORBIT,HMINUS,-1,MID,MB,IOL1,NSAT,                    &
     &   N3,N6,NEQN,NEQN3,NEQN6,MJDSEC,FSECS,                           &
     &   XP,X,XDDOT,PX,PXDDOT,ISN0,ISN1,LNDRAG,XDDTMC,TOPXAT,           &
     &   LTPXAT,AA,II,LL,ISATID,                                        &
     &   LFHIRT,LSURFF,XDDTNC,XDDTAC,PXDDAC,                            &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,DYNTIM,NPERDY,EXACCT,        &
     &   EXACIN,EXACOB,LACCELS,ACCTIM,ACCPER,NPERAC,XDDRC,              &
     &   NEQNA,NEQNA3,NEQNA6,XPA,XA,XDDOTA(1,1,1),PXA,                  &
     &   PXDDTA(1,1,1),XMNRT,XR(4,2),XRP(4,2),XR(1,2),XRP(1,2),         &
     &   XRDOT(1,1,1),                                                  &
!... Begin TJS...
     &   XR(13,2),XRP(13,2),XR(157,2),XRP(157,2),                       &
!... End TJS...
     &   XPA2,XA2,XDDTA2(1,1,1),PXA2,PXDDA2(1,1,1),                     &
     &   XR2(4,2),XR2P(4,2),XR2(1,2),XR2P(1,2),XRDOT2(1,1,1),           &
     &   XR2(13,2),XR2P(13,2),XR2(157,2),XR2P(157,2),GM2,IDA1,IDA2)
! COMPUTE INTERPOLATOR COEFFICIENTS FOR EACH TIME
      IS=-IOL1
      DO 600 I=1,IOL1
      IS=IS+1
      S(I)=IS
  600 END DO
      CALL COEFV(S,B,IOL1,IORDER,CIPV,CIVV)
! BEGIN ITERATIVE CONVERGENCE OF STARTING SUMS
      INDS=1
      INDSAV=2
      KOUNT=0
 1000 CONTINUE
      KOUNT=KOUNT+1
      LSUMER=.TRUE.
! INITIALIZE EPOCH STATE AND PARTIAL DERIVATIVE ARRAYS
      CALL START0(LORBIT,N3,N6,NEQN,NEQN6,NSAT,XP,X,PX,PX,ONE)
      CALL START0(LORBIT,N3,N6,NEQNA,NEQNA6,NSAT,XPA,XA,PXA,PXA,DIAG1)
           IF(LBINAST) THEN
      CALL START0(LORBIT,N3,N6,NEQNA,NEQNA6,NSAT,XPA2,XA2,PXA2,PXA2,    &
     &            DIAG2)
           ENDIF
      IF(LPXA0) THEN
         DO 1152 N=1,NEQNA3
         PXA(N,1)=PXA0(N,1)
         PXA(N,2)=PXA0(N,2)
         IF(.NOT.LBINAST) GO TO 1152
         PXA2(N,1)=PXA20(N,1)
         PXA2(N,2)=PXA20(N,2)
 1152    END DO
      ENDIF
!... Begin TJS
!...  IF(LINTAX) CALL START0(.TRUE.,12,24,1,1,1,XRP,XR,PDUM,PDUM)
      IF(LINTAX) CALL START0(.TRUE.,NDPOR,2*NDPOR,1,1,1,XRP,            &
     &    XR,PDUM,PDUM,ONE)
      IF(LINTAX.AND.LBINAST)  CALL START0(.TRUE.,NDPOR,2*NDPOR,1,1,1,   &
     &    XR2P,XR2,PDUM,PDUM,ONE)
!... End TJS

! COMPUTE POSITION AND VELOCITY SUMS
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,N3,MF1,MID,                     &
     &   XP,SUMX(1,1,INDS),CIPV,CIVV,XDDOT(1,1,INDS))
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,N3,MF1,MID,                     &
     &   XPA,SUMXA(1,1,INDS),CIPV,CIVV,XDDOTA(1,1,INDS))
!
         IF(LBINAST) THEN
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,N3,MF1,MID,                     &
     &   XPA2,SUMXA2(1,1,INDS),CIPV,CIVV,XDDTA2(1,1,INDS))
         ENDIF
!
!... Begin TJS...
!...  IF(LINTAX) CALL STARTS(IORDER,IOL1,IOL2,H,H2,12,MF1,MID,          &
!... &   XRP,SUMXR(1,1,INDS),CIPV,CIVV,XRDOT(1,1,INDS))
      IF(LINTAX) CALL STARTS(IORDER,IOL1,IOL2,H,H2,NDPOR,MF1,MID,       &
     &   XRP,SUMXR(1,1,INDS),CIPV,CIVV,XRDOT(1,1,INDS))
      IF(LINTAX.AND.LBINAST) CALL STARTS(IORDER,IOL1,IOL2,H,H2,NDPOR,   &
     &   MF1,MID,XR2P,SUMXR2(1,1,INDS),CIPV,CIVV,XRDOT2(1,1,INDS))
!... End TJS...
! COMPUTE RELATIVISTIC CLOCK SUMS
      IF(LXPCLK) THEN
        CALL STARTS(IORDER,IOL1,IOL2,H,H2,NSAT,MF1,MID,                 &
     &              XRC,SUMRC(1,1),CIPV,CIVV,XDDRC(1,1))
      ENDIF
      IF(LORBIT) GO TO 2000
! COMPUTE SUMS FOR POSITION AND VELOCITY PARTIALS
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,NEQN3,MF1,MID,                  &
     &   PX,SUMPX(1,1,INDS),CIPV,CIVV,PXDDOT(1,1,INDS))
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,NEQNA3,MF1,MID,                 &
     &   PXA,SUMPXA(1,1,INDS),CIPV,CIVV,PXDDTA(1,1,INDS))
!
         IF(LBINAST) THEN
      CALL STARTS(IORDER,IOL1,IOL2,H,H2,NEQNA3,MF1,MID,                 &
     &   PXA2,SMPXA2(1,1,INDS),CIPV,CIVV,PXDDA2(1,1,INDS))
         ENDIF
!
 2000 CONTINUE
! DETERMINE IF LOCAL ERROR IN STARTING SUMS HAS REACHED
!     DESIRED ACCURACY
      IF(KOUNT.GT.1) THEN
      LSUMER=.FALSE.

      CALL STARTE(LSUMER,SUMX,N6,KOUNT)
      CALL STARTE(LSUMER,SUMXA(1,1,1),N6,KOUNT)
      IF(LBINAST) CALL STARTE(LSUMER,SUMXA2(1,1,1),N6,KOUNT)

!... Begin TJS...
!...  IF(LINTAX) CALL STARTE(LSUMER,SUMXR(1,1,1),24,KOUNT)
      IF(LINTAX) CALL STARTE(LSUMER,SUMXR(1,1,1),2*NDPOR,KOUNT)
      IF(LINTAX.AND.LBINAST) CALL STARTE(LSUMER,SUMXR2(1,1,1),          &
     &                                   2*NDPOR,KOUNT)
      IF (LINTAX.AND.KOUNT.EQ.20) THEN
         DO J=1,NDPOR
            WRITE(6,8834) J,SUMXR(J,1,1),SUMXR(J,2,1)
 8834       FORMAT(1X,'J = ',I3,' SUMXR = ',2E12.5)
         END DO
      END IF
!... End TJS...
      IF(LORBIT) GO TO 3000
      CALL STARTE(LSUMER,SUMPX,NEQN6,KOUNT)
      CALL STARTE(LSUMER,SUMPXA(1,1,1),NEQNA6,KOUNT)
      IF(LBINAST) CALL STARTE(LSUMER,SMPXA2(1,1,1),NEQNA6,KOUNT)
 3000 CONTINUE
      ENDIF
      IF(.NOT.LSUMER) GO TO 7000
! LOOP OVER EACH TIME STEP
      DO 6000 IORD=1,IOL1
      IC=IORDER-IORD
      IF(IC.EQ.MID)GO TO 5000
! RECOMPUTE POSITION AND VELOCITY USING SUMS
      NK=-IORD
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,N3,NK,IC,                       &
     &   XP,SUMX(1,1,INDS),CIPV,CIVV,XDDOT(1,1,INDS))
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,N3,NK,IC,                       &
     &   XPA,SUMXA(1,1,INDS),CIPV,CIVV,XDDOTA(1,1,INDS))
!
           IF(LBINAST) THEN
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,N3,NK,IC,                       &
     &   XPA2,SUMXA2(1,1,INDS),CIPV,CIVV,XDDTA2(1,1,INDS))
           ENDIF
      IF(LSTSNX) CALL GETAST(AA,IDA1,MJDSEC,FSECS(IC),XPA)
      IF(LSTSNY) CALL GETAST(AA,IDA2,MJDSEC,FSECS(IC),XPA2)
!
!... Begin TJS...
!...  IF(LINTAX) CALL STARTC(IORDER,IOL1,IOL2,H,H2,12,NK,IC,            &
!... &   XRP,SUMXR(1,1,INDS),CIPV,CIVV,XRDOT(1,1,INDS))
      IF(LINTAX) CALL STARTC(IORDER,IOL1,IOL2,H,H2,NDPOR,NK,IC,         &
     &   XRP,SUMXR(1,1,INDS),CIPV,CIVV,XRDOT(1,1,INDS))
      IF(LINTAX.AND.LBINAST) CALL STARTC(IORDER,IOL1,IOL2,H,H2,NDPOR,NK,&
     &   IC,XR2P,SUMXR2(1,1,INDS),CIPV,CIVV,XRDOT2(1,1,INDS))
!... End TJS...

! RECOMPUTE ACCELERATION
      ICC=IC*ISN1+ISN0
      BDAST(1)=XPA(1,1)
      BDAST(2)=XPA(2,1)
      BDAST(3)=XPA(3,1)
      BDAST(4)=XPA(1,2)
      BDAST(5)=XPA(2,2)
      BDAST(6)=XPA(3,2)
      IF(LSTINR.AND.ISQ.EQ.1) THEN
       DO J=1,6
         HOLDA(J,IC)=BDAST(J)
       ENDDO
      ENDIF
!
! IF(LINTAX) PUT IN A ROUTINE TO REPLACE ORINNTATION INFORMATION
      IF(LINTAX) THEN
         IF(LBINAST) THEN
             CALL LOADAX(XRP(4,2),XR2P(4,2))
           ELSE
             CALL LOADAX(XRP(4,2),XRP(4,2))
         ENDIF
      ENDIF
!
! SECONARY ASTEROID
!
          XDDP(1)=0.D0
          XDDP(2)=0.D0
          XDDP(3)=0.D0
          IF(LBINAST) THEN
      CALL FASTIN(GM2,XPA2,XDDP,                                        &
     &            XDDTA2(1,IC,INDSAV),TRQP,TRQS,VMATA2,0,               &
     &            AA,II,ICC,MJDSEC,FSECS(IC),PXDDTA(1,IC,INDSAV),       &
     &            PXDDA2(1,IC,INDSAV),NEQNA,NEQNA)
      CALL TRQMAT(GM2,XPA2,TRQP,TRQS,AA,II,ICC,MJDSEC,FSECS(IC))
          ENDIF
!
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),1,XDDP,XPA2)
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),2,XDDO,XPA2)
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),3,XDDP,XPA2)
!
!
            IF(LBINAST) THEN
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),4,XDDP,XPA2)
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),5,XDDO,XPA2)
      CALL F123(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                 &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),6,XDDP,XPA2)

            ENDIF
!
!
!
      HQ=H
      CALL F(MJDSEC,FSECS(IC),XP,XDDOT(1,IC,INDSAV),                    &
     &   PXDDOT(1,IC,INDSAV),NSAT,NEQN,ICC,XDDTMC,                      &
     &   TOPXAT(1,IC),LTPXAT(1,IC),AA,II,LL,ISATID,LFHIRT,              &
     &   LSURFF,XDDTNC(1,IC,INDSAV),XDDTAC(1,1,1,IC),PXDDAC(1,1,IC),    &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,IC),XDDP,XPA2,LQ1,IPSBRN,LQ2,XDDBRN,HQ)
      IF(LQ1.OR.LQ2) THEN
        WRITE(6,60000)
        WRITE(6,60001)
        STOP
      ENDIF
      CALL FAST(MJDSEC,FSECS(IC),AA,II,LL,NEQNA,XPA,VMATA,              &
     &          PXDDTA(1,IC,INDSAV),XDDOTA(1,IC,INDSAV),XDDSUN,         &
     &          XDDCMP,XDDOT(1,IC,INDSAV),XP,XMNRT,XRP(4,2),XRP(1,2),   &
     &          XRDOT(4,IC,INDSAV),XRDOT(1,IC,INDSAV),.FALSE.,          &
     &          XDDTMC,.FALSE.,ICC,ONE,                                 &
!... Begin TJS...
     &       XRP(13,2),XRDOT(13,IC,INDSAV),XRP(157,2),                  &
     &       XRDOT(157,IC,INDSAV),XDDP,1,TRQP,PXDDOT(1,IC,INDSAV),NEQN)
!... End TJS...
!
!
          IF(LBINAST) THEN
      CALL FAST2(XPA2,XDDTA2(1,IC,INDSAV),XDDCM2,VMATA2)
      CALL FAST(MJDSEC,FSECS(IC),AA,II,LL,NEQNA,XPA,VMATA,              &
     &          PXDDTA(1,IC,INSAV),XDDOTA(1,IC,INDSAV),XDDSUN,XDDCMP,   &
     &          XDDOT(1,IC,INDSAV),XP,XMNRT,XR2(4,2),XR2(1,2),          &
     &          XRDOT2(4,IC,INDSAV),XRDOT2(1,IC,INDSAV),.FALSE.,XDDTMC, &
     &          .FALSE.,ICC,ONE,                                        &
!... Begin TJS...
! omega                           => XR(  1,2) => length   3 \
! axis                            => XR(  4,2) => length   9  \
!                                                              | Total
!                                                              | length = 228
! d(orientation)/d(orientation_0) => XR( 13,2) => length 144  /
! d(orientation)/d(inertia)       => XR(157,2) => length  72 /
     &       XR2P(13,2),XRDOT2(13,IC,INDSAV),XR2P(157,2),               &
     &       XRDOT2(157,IC,INDSAV),XDDP,2,TRQS,PXDDOT(1,IC,INDSAV),NEQN)
!... End TJS...
          ENDIF
!
!

      IF(LORBIT)GO TO 4000
!      DO IQP=1,NEQN3
!         PXDDTH(IQP,IC)=PXDDOT(IQP,IC,INDSAV)
!      ENDDO
! RECOMPUTE PARTIAL DERIVATIVES
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,NEQN3,NK,IC,                    &
     &   PX,SUMPX(1,1,INDS),CIPV,CIVV,PXDDOT(1,1,INDS))
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,NEQNA3,NK,IC,                   &
     &   PXA,SUMPXA(1,1,INDS),CIPV,CIVV,PXDDTA(1,1,INDS))
!
             IF(LBINAST) THEN
      CALL STARTC(IORDER,IOL1,IOL2,H,H2,NEQNA3,NK,IC,                   &
     &   PXA2,SMPXA2(1,1,INDS),CIPV,CIVV,PXDDA2(1,1,INDS))
             ENDIF
!
! RECOMPUTE PARTIAL DERIVATIVE ACCELERATIONS
      CALL VEVAL(XP,PX,PXDDOT(1,IC,INDSAV),AA,II,LL,NSAT,NEQN,.TRUE.,   &
     &   LNDRAG)
      CALL VEVALA(PXA,PXDDTA(1,IC,INDSAV),NEQNA,.TRUE.,VMATA,NEQN,      &
     &            PXDDOT(1,IC,INDSAV),.FALSE.,1)
!
             IF(LBINAST) THEN
      CALL VEVALA(PXA2,PXDDA2(1,IC,INDSAV),NEQNA,.TRUE.,VMATA2,NEQN,    &
     &            PXDDOT(1,IC,INDSAV),.FALSE.,2)
             ENDIF
!
 4000 CONTINUE
 5000 CONTINUE
 6000 END DO
      IND=INDS
      INDS=INDSAV
      INDSAV=IND
      IF(KOUNT.LT.MAXMUM)GO TO 1000
      WRITE(6,6666) KOUNT
 6666 FORMAT('-   START; KOUNT=',I6)
!     CALL ERROR
 7000 CONTINUE
!
      IF(LSTINR.AND.ISQ.EQ.1) THEN
         DO J=MID,IOL1
           CALL UTCET(.FALSE.,1,MJDSEC,FSECS(J),FSCUTC(1),AA(KA1UT))
           CALL YMDHMS(MJDSEC,FSCUTC(1),IYMD,IHM,SEC,1)
           IF(IYMD(1).GT.1000000)IYMD(1)=IYMD(1)-1000000
           TQ=DBLE(MJDSEC)+FSCUTC(1)
           WRITE(CARD,70000) IYMD,IHM,SEC
           DO JJ=1,6
             IF(CARD(JJ:JJ).EQ.' ') CARD(JJ:JJ)='0'
           ENDDO
           DO JJ=8,11
             IF(CARD(JJ:JJ).EQ.' ') CARD(JJ:JJ)='0'
           ENDDO
           IF(CARD(14:14).EQ.' ') CARD(14:14)='0'
           IF(CARD(15:15).EQ.' ') CARD(15:15)='0'
           WRITE(77,70001) TQ,CARD,(HOLDA(JJ,J),JJ=1,6)
         ENDDO
      ENDIF
!
      FSEC=FSECS(IOL1)
      ISEC=FSEC
      FSEC=FSEC-ISEC
      MJDSEC=MJDSEC+ISEC
      IF(INDS.EQ.1) THEN
!      LSTART=.FALSE.
       GO TO 7250
!      RETURN
      ENDIF
! SHIFT ACCELERATIONS AND SUMS
      DO 7100 N=1,N6
      SUMX(N,1,1)=SUMX(N,1,2)
      SUMXA(N,1,1)=SUMXA(N,1,2)
      IF(.NOT.LBINAST) GO TO 7100
      SUMXA2(N,1,1)=SUMXA2(N,1,2)
 7100 END DO
!
!
!
      IF(LINTAX) THEN
!... Begin TJS...
         DO N=1,NDPOR
!... End TJS...
          SUMXR(N,1,1)=SUMXR(N,1,2)
          SUMXR(N,2,1)=SUMXR(N,2,2)
          IF(LBINAST) THEN
            SUMXR2(N,1,1)=SUMXR2(N,1,2)
            SUMXR2(N,2,1)=SUMXR2(N,2,2)
          ENDIF
         ENDDO
!... Begin TJS...
!...     NQ=12*IOL1
         NQ=NDPOR*IOL1
!... End TJS...
         DO N=1,NQ
           XRDOT(N,1,1)=XRDOT(N,1,2)
           IF(LBINAST) XRDOT2(N,1,1)=XRDOT2(N,1,2)
         ENDDO
      ENDIF
!
!
!
      N3IOL1=N3*IOL1
      DO 7200 N=1,N3IOL1
      XDDOT(N,1,1)=XDDOT(N,1,2)
      XDDTNC(N,1,1)=XDDTNC(N,1,2)
      XDDOTA(N,1,1)=XDDOTA(N,1,2)
      IF(LBINAST) XDDTA2(N,1,1)=XDDTA2(N,1,2)
 7200 END DO
 7250 CONTINUE
!
!
       IF(NINTOT.GT.0) THEN
      TMOS0(1)=DBLE(MJDSEC)+FSEC
      TMOS(1)=DBLE(MJDSEC)+FSEC
!     write(6,*)' dbg START fill up TMOS0 TMOS ',TMOS0(1),TMOS(1)
!     HOS(1)=H
!     write(6,*)' dbg START fill up HOS ',HOS(1)
!
! THE NEXT TWO LOOPS ONLY WORK IF THERE IS ONE SAT PER SET
      DO  N=1,N6
         SUMXOS(N,1,1)=SUMX(N,1,1)
!     write(6,*)' compute SUMXOS start ',SUMXOS(N,1,1),N
      ENDDO
      N3IOL1=N3*IOL1
      DO N=1,N3IOL1
         XDDTOS(N,1,1)=XDDOT(N,1,1)
      ENDDO
       ENDIF
!
!
      IF(LORBIT)THEN
!      LSTART=.FALSE.
      RETURN
      ENDIF
      IF(INDS.EQ.1) GO TO 7450
      N3IOL1=NEQN3*IOL1
!
      DO 7300 N=1,N3IOL1
      PXDDOT(N,1,1)=PXDDOT(N,1,2)
!     PXDDOT(N,1,2)=PXDDTH(N,1)
 7300 END DO
      N3IOL1=NEQNA3*IOL1
      DO 7301 N=1,N3IOL1
      PXDDTA(N,1,1)=PXDDTA(N,1,2)
      IF(LBINAST) PXDDA2(N,1,1)=PXDDA2(N,1,2)
 7301 END DO
!
!
      DO 7400 N=1,NEQN6
      SUMPX(N,1,1)=SUMPX(N,1,2)
 7400 END DO
      DO 7401 N=1,NEQNA6
      SUMPXA(N,1,1)=SUMPXA(N,1,2)
      IF(LBINAST) SMPXA2(N,1,1)=SMPXA2(N,1,2)
 7401 END DO
 7450 CONTINUE
!
       IF(NINTOT.GT.0) THEN
      TMOSP(1)=DBLE(MJDSEC)+FSEC
!     XNEQN(1)=DFLOAT(NEQN)+.001D0
!
! THE NEXT TWO LOOPS ONLY WORK IF THERE IS ONE SAT PER SET
!
      DO N=1,IOL1
        KPT=0
        DO J=1,3
          DO K=1,NEQN
             PDDTOS(K,J,N,1)=PXDDOT(K+KPT,N,1)
          ENDDO
          KPT=KPT+NEQN
        ENDDO
      ENDDO
!
        JPT=0
      DO J=1,3
         DO N=1,NEQN
           SUMPOS(N,J,1,1)=SUMPX(N+JPT,1,1)
           SUMPOS(N,J,2,1)=SUMPX(N+JPT,2,1)
!        write(6,*)' dbg START SUMPOS ',SUMPOS(N,J,1,1),N
!        write(6,*)' dbg START SUMPOS ',SUMPOS(N,J,2,1),N
         ENDDO
         JPT=JPT+NEQN
      ENDDO
      ENDIF
!
  999 FORMAT('-TERMINATION IN START;STEPSIZE AND/OR ORDER TOO LARGE')
!      LSTART=.FALSE.
      RETURN
60000 FORMAT(' EXECUTION REMINATING IN STARTD ')
60001 FORMAT(' A FINTE BURN ENCOUNTERED DURING STARTING PROCEDURE ')
70000 FORMAT(I6,1X,I4,F7.2)
70001 FORMAT(F15.2,2X,A18,6D25.16)
      END
