!$SUBALT
      SUBROUTINE SUBALT(AA,NM)
!********1*********2*********3*********4*********5*********6*********7**
! SUBALT          00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A
!   NM
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
! /COBBUF/ OBSERVATION BLOCK POINTERS
      COMMON/COBBUF/IOBSBF,IBUF1 ,IBUF2 ,IWORD1,NHEADR,NWORDM
! /COBLOC/ OBSERVATION BLOCK DYNAMIC ARRAY POINTERS
!          STATION INFORMATION POINTERS TO COORDINATE SYSTEM ARRAYS
      COMMON/COBLOC/KXMN  (3,4)  ,KENVN (3,4)  ,KSTINF(3,4)  ,          &
     &       KOBS  ,KDTIME,KSMCOR,KSMCR2,KTMCOR,KOBTIM,KOBSIG,KOBSG2,   &
     &       KIAUNO,KOBCOR(9,7)  ,KFSECS(6,8)  ,KOBSUM(8)    ,          &
     &       KEDSIG,KEDSG2
      COMMON/CPRESW/LPRE9 (24),LPRE  (24,3),LSWTCH(10,8),LOBSIN,LPREPW, &
     &              LFS   (40)
      DIMENSION AA(1)
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      N1=KSMCOR
      N2=N1+NM-1
      M1=KSMCR2
      M2=M1+NM-1
      IHEADR=2
      JHEADR=IHEADR-1
      KHEADR=IHEADR+2
      MHEADR=IHEADR+3
! SUBTRACT COMPUTED OCEAN PARAMETERS
      DO 8000 IWORD =11,14
      IF(IWORD.EQ.11.AND..NOT.LETIDE) GO TO 8000
      IF(IWORD.EQ.12.AND..NOT.LOTIDE) GO TO 8000
      IF(IWORD.EQ.14.AND..NOT.LSSTMD) GO TO 8000
      IF(.NOT.LPRE  (IWORD ,JHEADR)) GO TO 8000
      IF(IWORD.EQ.13) GO TO 8000
      JWORD=IWORD-9
      IF(IWORD.EQ.12.AND.LPRE(IWORD+1,JHEADR)) JWORD=JWORD+1
! ASK TVM
      IF(.NOT.LSWTCH(JWORD ,MHEADR)) GO TO 8000
! ASK TVM
      JOBCOR=KOBCOR(JWORD ,KHEADR)
!     J2=JOBCOR+NM-1
!     PRINT 22222,IWORD,IHEADR,(AA(J),J=JOBCOR,J2)
      DO 7000 M=M1,M2
      AA(M     )   =AA(M     )   -AA(JOBCOR)
      JOBCOR=JOBCOR+1
 7000 END DO
 8000 END DO
!     PRINT 11111,(AA(N),N=N1,N2)
!     PRINT 33333,(AA(M),M=M1,M2)
      RETURN
!11111 FORMAT(' ** SUBALT **  SUMCOR ='/(1X,6D12.5))
!22222 FORMAT(' ** SUBALT **  IWORD,IHEADR =',2I12,5X,'OBSCOR(N,I,J) ='/
!    1   (1X,6D12.5))
!33333 FORMAT(' ** SUBALT **  SUMCR2 ='/(1X,6D12.5))
      END
