      SUBROUTINE SWTCPT(ISET,LFRMCM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/HETADJ/LHETAD(20,3)
      COMMON/HETAPT/IHETAP(19,3)
      COMMON/HETIOR/IHETIO(6,3)
      COMMON/HETAGP/IHETAG(6,3)
      COMMON/HETOPT/LHETOP(6,3)
      COMMON/HETPPT/IHETPP(10,3)
!!!!!!!
      COMMON/SETADJ/LSADRG(4),LSASRD(4),LSAGA(4),LSAGP,LSATID,LSAGM,    &
     &              LSADPM,LSAKF,LSADNX,LSADJ2,LSAPGM
      COMMON/SETAGP/NAJCA,NAJSA,NAJCG,NAJSG,NAJCT,NAJST
      COMMON/SETAPT/                                                    &
     &       JSADRG(1),JSASRD(1),JSAGA(1),JFAADJ,JTHDRG,JACBIA,JATITD,  &
     &       JDSTAT,JDTUM ,                                             &
     &       JSACS, JSATID,JSALG,JSAGM,JSAKF,JSAXYP,JSADJ2,JSAPGM,      &
     &       JFGADJ,JLTPMU,JLTPAL,JL2CCO,JL2SCO,JL2GM,JLRELT,           &
     &       JLJ2SN,JLGMSN,JLPLFM,JL2AE,JSAXTO,JSABRN
      COMMON/SETIOR/IORDRG,IORSRD,IORGA,IPDDRG,IPDSRD,IPDGA
      COMMON/SETOPT/LSDRG,LSSRD,LSGA,LSORB,LTHDRG,LROCK4
      COMMON/SETPPT/JSPDRG(3),JSPSRD(3),JSPGA(3),JCSAT
!!!!!!!
      DIMENSION L1(20),L2(6)
      DIMENSION I1(19),I2(6),I3(10),I4(6)
      EQUIVALENCE(L1(1),LSADRG(1))
      EQUIVALENCE(L2(1),LSDRG)
      EQUIVALENCE(I1(1),JSADRG(1))
      EQUIVALENCE(I2(1),IORDRG)
      EQUIVALENCE(I3(1),JSPDRG(1))
      EQUIVALENCE(I4(1),NAJCA)
!!!!!!!
      IF(.NOT.LFRMCM) GO TO 500
      DO I=1,20
        LHETAD(I,ISET)=L1(I)
      ENDDO
      DO I=1,19
        IHETAP(I,ISET)=I1(I)
      ENDDO
      DO I=1,6
        IHETIO(I,ISET)=I2(I)
      ENDDO
      DO I=1,6
        LHETOP(I,ISET)=L2(I)
      ENDDO
      DO I=1,10
        IHETPP(I,ISET)=I3(I)
      ENDDO
      DO I=1,6
        IHETAG(I,ISET)=I4(I)
      ENDDO
      RETURN
 500  CONTINUE
      DO I=1,20
        L1(I)=LHETAD(I,ISET)
      ENDDO
      DO I=1,19
        I1(I)=IHETAP(I,ISET)
      ENDDO
      DO I=1,6
        I2(I)=IHETIO(I,ISET)
      ENDDO
      DO I=1,6
        L2(I)=LHETOP(I,ISET)
      ENDDO
      DO I=1,10
        I3(I)=IHETPP(I,ISET)
      ENDDO
      DO I=1,6
        I4(I)=IHETAG(I,ISET)
      ENDDO
      RETURN
      END
