!$TAYLRA
      SUBROUTINE TAYLRA(LORBIT,H,MSIGN,MID,MI,IOL1,                     &
     &   NSAT,N3,N6,NEQN,NEQN3,NEQN6,MJDS,FSECS,                        &
     &   XP,X,XDDOT,PX,PXDDOT,ISN0,ISN1,LNDRAG,XDDTMC,                  &
     &   TOPXAT,LTPXAT,AA,II,LL,ISATID,                                 &
     &   LFHIRT,LSURFF,XDDTNC,XDDTAC,PXDDAC,                            &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,DYNTIM,NPERDY,EXACCT,        &
     &   EXACIN,EXACOB,LACCELS,ACCTIM,ACCPER,NPERAC,XDDRC,              &
     &   NEQNA,NEQNA3,NEQNA6,XPA,XA,XDDOTA,PXA,PXDDTA,                  &
     &   XMNRT,XAXS,XAXSP,OMEG,OMEGP,XRDOT,DORIED0,DORIEP0,DORIEDI,     &
     &   DORIEPI,                                                       &
     &   XPA2,XA2,XDDTA2,PXA2,PXDDA2,                                   &
     &   XAXS2,XAXSP2,OMEG2,OMEGP2,XRDOT2,D2RIED0,D2RIEP0,D2RIEDI,      &
     &   D2RIEPI,GM2,IDA1,IDA2)
!********1*********2*********3*********4*********5*********6*********7**
! TAYLOR           82/08/27            8208.0    PGMR - TOM MARTIN
!
! FUNCTION:  PREDICT THE ORBIT AND PARTIAL DERIVATIVES AT
!            EACH TIME STEP USING TAYLOR SERIES
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   LORBIT   I         LOGICAL SWITCH INDICATING ORBIT ONLY
!                      INTEGRATION WHEN .TRUE.
!   H        I         INTEGRATION STEPSIZE
!   MSIGN    I         SIGNED INTEGER INDICATING TIME DIRECTION
!                      OF TAYLOR EXPANSION
!   MID      I         INDICATOR OF WHICH TIME STEP IS INITIAL EPOCH
!   MI       I         NUMBER OF TIME STEPS TO BE EXPANDED IN TAYLOR
!   IOL1     I         IORDER-1
!   NSAT     I         NUMBER OF SATELLITES IN THE SET
!   N3       I         NSAT*3
!   N6       I         NSAT*6
!   NEQN     I         NUMBER OF FORCE MODEL PARAMETERS INTEGRATED
!   NEQN3    I         NEQN*3
!   NEQN6    I         NEQN*6
!   MJDS     I         DATE & INTEGRAL SECONDS OF EACH TIME STEP
!   FSECS    I         FRACTIONAL SECONDS OF EPOCH OF EACH TIME STE
!   XP            A    PREDICTED SATELLITE STATE
!   X        I         INITIAL EPOCH ELEMENTS
!   XDDOT    O         ACCELERATION BACK VALUE ARRAY
!   PX       O         PREDICTED SATELLITE PARTIALS
!   PXDDOT   O         ACCELERATION PARTIAL BACK VALUE ARRAY
!   ISN0     I         POINTER TO COORDINATE ROTATION MATRX
!   ISN1     I         POINTER TO COORDINATE ROTATION MATRX
!   LNDRAG   I         FALSE IF FORCE MODEL IS DRAG DEPENDENT
!   XDDTMC   O         P.MASS ACCELERATION BACK VALUE ARRAY
!   TOPXAT   O    A    TOPEX ATT. BACK VALUES (BETAPRIME & ORBIT ANGLE)
!   LTPXAT   O    A    TOPEX ATT. BACK VALUES (RAMPING LOGICALS)
!   AA      I/O   A
!   II      I/O   A
!   LL      I/O   A
!   ISATID          SAT ID ARRAY
!   XDDTNC   O         SMALL FORCE ACCELERATIONS (ACCELEROMETRY
!                      COMPUTED AND/OR SEPARATELY INTEGRATED)
!   LFHIRT   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!   LSURFF   I    A    ARRAY OF LOGICAL FLAGS. EACH ELEMENT
!                      CORRESPONDS TO A FORCE MODEL COMPONENT.
!                      THE ARRAY DESCRIBES WHICH COMPONENTS ARE
!                      INTEGRATED AT A HIGH RATE.
!   XDDTAC   O    A    COMPUTED ACCELERATIONS CORRESPONDING TO
!                      ACCELEROMETRY
!   PXDDAC   O    A    PARTIAL DERIVATIVES OF XDDTAC
!   NEQNAC   I    S    NUMBER OF ADJUSTING ACCELEROMTER PARTIALS
!   IPTFBS   I    A    MAPPING ARRAY ; EXPLICIT PARTIAL ARRAY TO
!                      COMPUTED ACCELERATION PARTIAL ARRAY
!   NPRMAC   I    A    NUMBER OF PARMETERS IN EACH FORCE MODEL
!                      GROUP CATEGORY YO BE MAPPED BY IPTFBS
!   LHIRAT   I    S    TRUE IF MULTI RATE INTEGRATION IS ON FOR
!                      THIS CALL
!   LALLA    I    S    TRUE IF SUBROUTINE F RETURNS FULL ACCELERATION
!                      (NOT JUST LOW RATE ACCEL)
!   DYNTIM   I    A    USER REQUESTED START AND STOP TIMES FOR
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
!   NPERDY   I    A    NUMBER OF USER REQUESTED
!                      DYNAMIC ACCELERATION ACCELEROMETER PERIODS
! DORIED0  = d(orientation)/d(orientation_0) CORRECTED
! DORIEP0  = d(orientation)/d(orientation_0) PREDICTED
! DORIEDI  = d(orientation)/d(inertia) CORRECTED
! DORIEPI  = d(orientation)/d(inertia) PREDICTED
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/ACCLRM/MDYNPD,MBAPPD,MACOBS,IDYNSC(200),MDYNST,IACCSC(200),&
     &              MACCSC,NACPRM(200),NATPRM(200),NXCLRM
      COMMON/ASTSUN/BDAST(6),GMSAT,GEOPTS(3)
      COMMON/AXIS/LINTAX
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/LASTER/LASTR(2),LBINAST,NXASTR
      COMMON/LDUAL/LASTSN,LSTSNX,LSTSNY
      COMMON/NFORCE/NHRATE,NSURF,MPXHDT,MXHRG,MXFMG,NFSCAC,NXFORC
      COMMON/XPCNT /NXTRAC,NXFLAG,NXALLC,NCPPER,NMINRT,NDPOR,NXXTRA
      DIMENSION FSECS(IOL1),XP(N3,2),                                   &
     &   X(N3,2),XDDOT(N3,IOL1),PX(NEQN3,2),                            &
     &   PXDDOT(NEQN3,IOL1),AA(1),II(1),LL(1),                          &
     &   XDDTMC(N3,1),TOPXAT(2*NSAT,IOL1),LTPXAT(3*NSAT,IOL1),          &
     &   XDDRC(NSAT,IOL1)
      DIMENSION XPA(N3,2),XA(N3,2),XDDOTA(N3,IOL1),PXA(NEQNA3,2),       &
     &   PXDDTA(NEQNA3,IOL1)
! SECONDARY ASTEROID STUFF
      DIMENSION XPA2(N3,2),XA2(N3,2),PXA2(NEQNA3,2)
      DIMENSION XDDTA2(N3,IOL1),PXDDA2(NEQNA3,IOL1)
!
      DIMENSION ISATID(NSAT)
      DIMENSION XDDTNC(N3,IOL1)
      DIMENSION LFHIRT(NHRATE),LSURFF(NSURF),IPTFBS(MXFMG)
      DIMENSION NPRMAC(MXHRG)
      DIMENSION XDDTAC(3,NFSCAC,NSAT,IOL1),PXDDAC(NEQNAC,N3,IOL1)
      DIMENSION DYNTIM(MDYNPD,2,NSAT),NPERDY(NSAT)
      DIMENSION EXACCT(2,NSAT),EXACIN(NSAT),EXACOB(MACOBS,NSAT)
      DIMENSION ACCTIM(MBAPPD,2,NSAT),ACCPER(MBAPPD,NSAT),NPERAC(NSAT)
      DIMENSION VMATA(3,6),XDDSUN(3),XDDCMP(3)
      DIMENSION XMNRT(3),OMEG(3),OMEGP(3),XAXS(3,3),XAXSP(3,3)
!!!   DIMENSION XRDOT(3,4,IOL1)
      DIMENSION XRDOT(NDPOR,IOL1)
      DIMENSION DORIED0(12,12),DORIEP0(12,12)
      DIMENSION DORIEDI(12,6),DORIEPI(12,6)
! SECONDARY ASTEROID STUFF
      DIMENSION OMEG2(3),OMEGP2(3),XAXS2(3,3),XAXSP2(3,3)
      DIMENSION D2RIED0(12,12),D2RIEP0(12,12)
      DIMENSION D2RIEDI(12,6),D2RIEPI(12,6)
      DIMENSION XRDOT2(NDPOR,IOL1)
      DIMENSION XDDP(3),TRQP(3),TRQS(3),VMATA2(3,6),XDDCM2(3)
      DIMENSION XDDBRN(3)
!
      DATA ONE/1.D0/,THREE/3.0D0/,HALF/0.5D0/,ZERO/0.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      DIAG1=ONE
      DIAG2=ONE
      IF(LSTSNX) DIAG1=ZERO
      IF(LSTSNY) DIAG2=ZERO
      GMS=BDSTAT(7,8)
      IF(LBINAST) GMC=GM2+GM
      NRAT=1
      HALFH=HALF*H
! INITIALIZE EPOCH STATE AND PARTIAL DERIVATIVE ARRAYS
      CALL START0(LORBIT,N3,N6,NEQN,NEQN6,NSAT,XP,X,PX,PX,ONE)
      CALL START0(LORBIT,N3,N6,NEQNA,NEQNA6,NSAT,XPA,XA,PXA,PXA,DIAG1)
      IF(LBINAST) THEN
        CALL START0(LORBIT,N3,N6,NEQNA,NEQNA6,NSAT,XPA2,XA2,PXA2,PXA2,  &
       &            DIAG2)
      ENDIF
      IF(LINTAX) THEN
        DO I=1,3
          OMEGP(I)=OMEG(I)
          XAXSP(1,I)=XAXS(1,I)
          XAXSP(2,I)=XAXS(2,I)
          XAXSP(3,I)=XAXS(3,I)
          IF(LBINAST) THEN
            OMEGP2(I)=OMEG(I)
            XAXSP2(1,I)=XAXS2(1,I)
            XAXSP2(2,I)=XAXS2(2,I)
            XAXSP2(3,I)=XAXS2(3,I)
          ENDIF
        ENDDO
        DO I=1,144
          DORIEP0(I,1)=DORIED0(I,1)
          IF(LBINAST) D2RIEP0(I,1)=D2RIED0(I,1)
        ENDDO
        DO I=1,72
          DORIEPI(I,1)=DORIEDI(I,1)
          IF(LBINAST) D2RIEPI(I,1)=D2RIEDI(I,1)
        ENDDO
      ENDIF
! PREDICT ORBIT USING TAYLOR SERIES
      DO 900 I=1,MI
      M=MID+I*MSIGN
      M1=M-MSIGN
      DO 700 ISAT=1,NSAT
      N0=(ISAT-1)*3
      N0P1=N0+1
      N0P2=N0+2
      N0P3=N0+3
      RSQ=XP(N0P1,1)**2+XP(N0P2,1)**2+XP(N0P3,1)**2
      RCUBED=RSQ* SQRT(RSQ)
      RDOTV3=(XP(N0P1,1)*XP(N0P1,2)+XP(N0P2,1)*XP(N0P2,2)               &
     &      +XP(N0P3,1)*XP(N0P3,2))*THREE
      DO 600 K=1,3
      NK=N0+K
      GERK=-GM*(XP(NK,2)-RDOTV3*XP(NK,1)/RSQ)/RCUBED
      XP(NK,1)=XP(NK,1)+H*(XP(NK,2)                                     &
     &        +HALFH*(XDDOT(NK,M1)+H*GERK/THREE))
      XP(NK,2)=XP(NK,2)+H*(XDDOT(NK,M1)+HALFH*GERK)
  600 END DO
      RSQ=XPA(N0P1,1)**2+XPA(N0P2,1)**2+XPA(N0P3,1)**2
      RCUBED=RSQ* SQRT(RSQ)
      RDOTV3=(XPA(N0P1,1)*XPA(N0P1,2)+XPA(N0P2,1)*XPA(N0P2,2)           &
     &      +XPA(N0P3,1)*XPA(N0P3,2))*THREE
      DO 601 K=1,3
      NK=N0+K
      GERK=-GMS*(XPA(NK,2)-RDOTV3*XPA(NK,1)/RSQ)/RCUBED
      XPA(NK,1)=XPA(NK,1)+H*(XPA(NK,2)                                  &
     &        +HALFH*(XDDOTA(NK,M1)+H*GERK/THREE))
      XPA(NK,2)=XPA(NK,2)+H*(XDDOTA(NK,M1)+HALFH*GERK)
  601 END DO
      IF(LSTSNX) CALL GETAST(AA,IDA1,MJDS,FSECS(M),XPA)
      IF(.NOT.LBINAST) GO TO 700
      RSQ=XPA2(N0P1,1)**2+XPA2(N0P2,1)**2+XPA2(N0P3,1)**2
      RCUBED=RSQ* SQRT(RSQ)
      RDOTV3=(XPA2(N0P1,1)*XPA2(N0P1,2)+XPA2(N0P2,1)*XPA2(N0P2,2)       &
     &       +XPA2(N0P3,1)*XPA2(N0P3,2))*THREE
      DO 602 K=1,3
      NK=N0+K
      GERK=-GMC*(XPA2(NK,2)-RDOTV3*XPA2(NK,1)/RSQ)/RCUBED
      XPA2(NK,1)=XPA2(NK,1)+H*(XPA2(NK,2)                               &
     &          +HALFH*(XDDTA2(NK,M1)+H*GERK/THREE))
      XPA2(NK,2)=XPA2(NK,2)+H*(XDDTA2(NK,M1)+HALFH*GERK)
  602 END DO
      IF(LSTSNY) CALL GETAST(AA,IDA2,MJDS,FSECS(M),XPA2)
  700 END DO
      IF(LINTAX) THEN
        DO IQ=1,3
          OMEGP(IQ)=OMEGP(IQ)+H*XRDOT(IQ,M1)
          XAXSP(IQ,1)=XAXSP(IQ,1)+H*XRDOT(IQ+3,M1)
          XAXSP(IQ,2)=XAXSP(IQ,2)+H*XRDOT(IQ+6,M1)
          XAXSP(IQ,3)=XAXSP(IQ,3)+H*XRDOT(IQ+9,M1)
          IF(LBINAST) THEN
            OMEGP2(IQ)=OMEGP2(IQ)+H*XRDOT2(IQ,M1)
            XAXSP2(IQ,1)=XAXSP2(IQ,1)+H*XRDOT2(IQ+3,M1)
            XAXSP2(IQ,2)=XAXSP2(IQ,2)+H*XRDOT2(IQ+6,M1)
            XAXSP2(IQ,3)=XAXSP2(IQ,3)+H*XRDOT2(IQ+9,M1)
          ENDIF
        ENDDO
        DO IQ=1,144
          DORIEP0(I,1)=DORIEP0(I,1)+H*XRDOT(IQ+12,M1)
          IF(LBINAST) D2RIEP0(I,1)=D2RIEP0(I,1)+H*XRDOT2(IQ+12,M1)
        ENDDO
        DO IQ=1,72
          DORIEPI(I,1)=DORIEPI(I,1)+H*XRDOT(IQ+156,M1)
          IF(LBINAST) D2RIEPI(I,1)=D2RIEPI(I,1)+H*XRDOT2(IQ+156,M1)
        ENDDO
      ENDIF
! EVALUATE FORCES
      MM=ISN1*M+ISN0
      BDAST(1)=XPA(1,1)
      BDAST(2)=XPA(2,1)
      BDAST(3)=XPA(3,1)
      BDAST(4)=XPA(1,2)
      BDAST(5)=XPA(2,2)
      BDAST(6)=XPA(3,2)
!
      IF(LINTAX) THEN
        IF(LBINAST) THEN
          CALL LOADAX(XAXSP,XAXSP2)
        ELSE
          CALL LOADAX(XAXSP,XAXSP)
        ENDIF
      ENDIF

! SECONARY ASTEROID
!
          XDDP(1)=0.D0
          XDDP(2)=0.D0
          XDDP(3)=0.D0
          IF(LBINAST) THEN
      CALL FASTIN(GM2,XPA2,XDDP,                                        &
     &            XDDTA2(1,M),TRQP,TRQS,VMATA2,0,                       &
     &            AA,II,MM,MJDS,FSECS(M),PXDDTA(1,M),PXDDA2(1,M),       &
     &            NEQNA,NEQNA)
      CALL TRQMAT(GM2,XPA2,TRQP,TRQS,AA,II,MM,MJDS,FSECS(M))
          ENDIF
!
!
!
!
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),1,XDDP,XPA2)
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),2,XDDP,XPA2)
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),3,XDDP,XPA2)
!
          IF(LBINAST) THEN
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),4,XDDP,XPA2)
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),5,XDDP,XPA2)
      CALL F123(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,           &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),6,XDDP,XPA2)
          ENDIF
!
      HQ=ABS(H)
      CALL F(MJDS,FSECS(M),XP,XDDOT(1,M),PXDDOT(1,M),NSAT,              &
     &   NEQN,MM,XDDTMC,TOPXAT(1,M),LTPXAT(1,M),AA,II,LL,ISATID,        &
     &   LFHIRT,LSURFF,XDDTNC(1,M),XDDTAC(1,1,1,M),PXDDAC(1,1,M),       &
     &   NEQNAC,IPTFBS,NPRMAC,LHIRAT,LALLA,ONE,DYNTIM,NPERDY,LACCELS,   &
     &   EXACCT,EXACIN,EXACOB,ACCTIM,ACCPER,NPERAC,II(KIACCP),          &
     &   AA(KPACCL),NRAT,XDDRC(1,M),XDDP,XPA2,LQ1,IPSBRN,LQ2,XDDBRN,HQ)
      IF(LQ1.OR.LQ2) THEN
        WRITE(6,60000)
        WRITE(6,60001)
        STOP
      ENDIF
      CALL FAST(MJDS,FSECS(M),AA,II,LL,NEQNA,XPA,VMATA,                 &
     &          PXDDTA(1,M),XDDOTA(1,M),XDDSUN,XDDCMP,                  &
     &          XDDOT(1,M),XP,XMNRT,XAXSP,OMEGP,XRDOT(4,M),             &
     &          XRDOT(1,M),.FALSE.,XDDTMC,.FALSE.,MM,ONE,               &
     &          DORIEP0,XRDOT(13,M),DORIEPI,XRDOT(157,M),XDDP,1,TRQP,   &
     &          PXDDOT(1,M),NEQN)
!
          IF(LBINAST) THEN
      CALL FAST2(XPA2,XDDTA2(1,M),XDDCM2,VMATA2)
      CALL FAST(MJDS,FSECS(M),AA,II,LL,NEQNA,XPA,VMATA,                 &
     &          PXDDTA(1,M),XDDOTA(1,M),XDDSUN,XDDCMP,                  &
     &          XDDOT(1,M),XP,XMNRT,XAXSP2,OMEGP2,XRDOT2(4,M),          &
     &          XRDOT2(1,M),.FALSE.,XDDTMC,.FALSE.,MM,ONE,              &
     &          D2RIEP0,XRDOT2(13,M),D2RIEPI,XRDOT2(157,M),XDDP,2,TRQS, &
     &          PXDDOT(1,M),NEQN)
          ENDIF
!
      IF(LORBIT)GO TO 900
! PREDICT FORCE MODEL PARTIAL DERIVATIVES
!
      DO 800 N=1,NEQN3
      PX(N,1)=PX(N,1)+H*(PX(N,2)+HALFH*PXDDOT(N,M1))
      PX(N,2)=PX(N,2)+H*PXDDOT(N,M1)
  800 END DO
      DO 801 N=1,NEQNA3
      PXA(N,1)=PXA(N,1)+H*(PXA(N,2)+HALFH*PXDDTA(N,M1))
      PXA(N,2)=PXA(N,2)+H*PXDDTA(N,M1)
      IF(.NOT.LBINAST) GO TO 801
      PXA2(N,1)=PXA2(N,1)+H*(PXA2(N,2)+HALFH*PXDDA2(N,M1))
      PXA2(N,2)=PXA2(N,2)+H*PXDDA2(N,M1)
  801 END DO
!
!
! EVALUATE FORCE MODEL PARTIAL DERIVATIVE ACCELERATIONS
      CALL VEVAL(XP,PX,PXDDOT(1,M),AA,II,LL,NSAT,NEQN,.TRUE.,LNDRAG)
      CALL VEVALA(PXA,PXDDTA(1,M),NEQNA,.TRUE.,VMATA,NEQN,              &
     &            PXDDOT(1,M),.FALSE.,1)
      IF(.NOT.LBINAST) GO TO 900
      CALL VEVALA(PXA2,PXDDA2(1,M),NEQNA,.TRUE.,VMATA2,NEQN,            &
     &            PXDDOT(1,M),.FALSE.,2)
  900 END DO
      RETURN
60000 FORMAT(' EXECUTION REMINATING IN TAYLRA ')
60001 FORMAT(' A FINTE BURN ENCOUNTERED DURING STARTING PROCEDURE ')
      END
