      SUBROUTINE TR2S20(LTR2SN,VCT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
! SUMAT GOES FROM TRUE OF REF TO SUN 2000
      COMMON/SUNMT/SUNMAT(9)
      DIMENSION VCT(3)
      DIMENSION SCR(3)
!
      SCR(1)=VCT(1)
      SCR(2)=VCT(2)
      SCR(3)=VCT(3)
!  ROTATE FROM SUN 2000 TO TR
      IF(LTR2SN) GO TO 100
      VCT(1)=SUNMAT(1)*SCR(1)+SUNMAT(2)*SCR(2)+SUNMAT(3)*SCR(3)
      VCT(2)=SUNMAT(4)*SCR(1)+SUNMAT(5)*SCR(2)+SUNMAT(6)*SCR(3)
      VCT(3)=SUNMAT(7)*SCR(1)+SUNMAT(8)*SCR(2)+SUNMAT(9)*SCR(3)
      RETURN
!
!  ROTATE DROM TR TO SUN 2000
 100  CONTINUE
      VCT(1)=SUNMAT(1)*SCR(1)+SUNMAT(4)*SCR(2)+SUNMAT(7)*SCR(3)
      VCT(2)=SUNMAT(2)*SCR(1)+SUNMAT(5)*SCR(2)+SUNMAT(8)*SCR(3)
      VCT(3)=SUNMAT(3)*SCR(1)+SUNMAT(6)*SCR(2)+SUNMAT(9)*SCR(3)
      RETURN
      END
