!$TRAJCT
      SUBROUTINE TRAJCT(ETUTC,MJDSTC,FSECTI,XS,VS,SATLAT,SATLON,SATH,   &
     &   IYMD,IHM,SEC,WORK,NPTS,ISAT,AA,COSTHG,SINTHG,DPSR,XPUT,YPUT,   &
     &   II)
!********1*********2*********3*********4*********5*********6*********7**
! TRAJCT           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   ETUTC
!   MJDSTC
!   FSECTI
!   XS
!   VS
!   SATLAT
!   SATLON
!   SATH
!   IYMD
!   IHM
!   SEC
!   WORK
!   NPTS
!   ISAT                INDEX TO THE SAT ARRAY
!   AA                  DYNAMIC REAL ARRAY
!   COSTHG
!   SINTHG
!   DPSR
!   XPUT
!   YPUT
!   II                  DYNAMIC INTEGER ARRAY
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/ARCPAR/MAXSEL,NSEL,MAXDEL,NDEL,MAXMET,NMETDT,NSATID,       &
     &              IATDEN,ISATEQ,ITRMAX,ITRMIN,ITRMX2,                 &
     &              MJDSRF,MREFSY,NTDDR,NBTOTL,IDRAGM,IMRNUT,           &
     &              NXARCP
      COMMON/CBDSTA/BDSTAT(7,999),XBDSTA
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORBVU/ISATL
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/G2EINF/G2EVER,G2EDAT,G2ERTM
      COMMON/G2SINF/G2SVER,G2SDAT,G2SRTM,G2SCOM,TDFVER,TDFRTM,SETCDS,   &
     &              GPCKSM,GPDEG ,GPORD ,XG2SIN
      COMMON/G2SINC/GRVDES(9),XG2SIC
      COMMON/CREFMT/REFMT(9)
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/LDUAL/LASTSN,LSTSNX,LSTSNY
      COMMON/LICASE/LINT(2),LCASE(18),NXLCAS
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/TITLEC/TITLEG(10,3),TITLEA(10,10),XTITLE
      COMMON/TRJREF/NORBTV,NORBFL,NCOFM,NXTREF
      DIMENSION XSTOR(3),VSTOR(3),X1(3),V1(3)
      DIMENSION AEI(6),PKPX(6,6)
      DIMENSION AEI2(6)
      DIMENSION ETUTC(1),WORK(NPTS)
      DIMENSION FSECTI(NPTS),XS(MINTIM,3),VS(MINTIM,3),SATLAT(NPTS),    &
     &   SATLON(NPTS),SATH(NPTS),SEC(NPTS),IHM(NPTS),IYMD(NPTS),        &
     &   COSTHG(NPTS),SINTHG(NPTS)
      DIMENSION DPSR(1),XPUT(1),YPUT(1),BIHMAT(3,3)
      DIMENSION XE(100,5), VE(100,5), XEP(100,3), VEP(100,3)
      DIMENSION AA(1),II(1)
      DATA NTIME/0/,IOUT59/15/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
      GMS=BDSTAT(7,8)
      LTOP=.FALSE.
      DO 5 I=1,18
      IF(LINT(1).AND.LCASE(I)) THEN
      LTOP=.TRUE.
      ENDIF
    5 END DO
      IF(.NOT.LTOP)GOTO 10
      NTIME=NTIME+1
      IF(NTIME.GT.1) GOTO 10
      WRITE(IOUT59,15000) (TITLEG(I,2),I=1,5),G2SVER,G2SRTM,            &
     &                     G2EVER,G2ERTM
!15000 FORMAT(1X,5A8,' IIS VERSION&TIME ',F9.2,1X,F18.2,
!    1           ' IIE VERSION&TIME ',F9.2,1X,F18.2)
15000 FORMAT(5A8,' IIS VERSION&TIME ',F9.2,1X,F18.2,                    &
     &           ' IIE VERSION&TIME ',F9.2,1X,F18.2)
   10   CONTINUE
!     CALL TDORTR(MJDSTC,FSECTI,XS,XS,AA,NPTS,MINTIM,.TRUE.,.FALSE.,II)
!     CALL TDORTR(MJDSTC,FSECTI,VS,VS,AA,NPTS,MINTIM,.FALSE.,.FALSE.,II)
      CALL UTCET(.FALSE.,NPTS,MJDSTC,FSECTI,WORK,ETUTC)
      CALL YMDHMS(MJDSTC,WORK,IYMD,IHM,SEC,NPTS)
!
! DETERMINE THE SATELLITE ID
!
      ISATID=II(KISATN+ISAT-1)
!
      IF(.NOT.LORBVX) GO TO 2000
      NLINE8=ILINE8+10
      IF(NLINE8.LE.MLINE8) GO TO 1000
      IPAGE8=IPAGE8+1
      ILINE8=3
      WRITE(IOUT8,10000) ISATID,NARC,NINNER,NGLOBL,IPAGE8
      WRITE(IOUT8,10200)
      GO TO 2000
 1000 CONTINUE
      IF(ISAT.EQ.ISATL) GO TO 2000
      ILINE8=ILINE8+4
      WRITE(IOUT8,10100) ISATID,NARC,NINNER,NGLOBL
 2000 CONTINUE
      IF(.NOT.LORBVK) GO TO 4000
      NLIN10=ILIN10+10
      IF(NLIN10.LE.MLIN10) GO TO 3000
      IPAG10=IPAG10+1
      ILIN10=3
      WRITE(IOUT10,20000) ISATID,NARC,NINNER,NGLOBL,IPAG10
      WRITE(IOUT10,20200)
      GO TO 4000
 3000 CONTINUE
      IF(ISAT.EQ.ISATL) GO TO 4000
      ILIN10=ILIN10+4
      WRITE(IOUT10,10100) ISATID,NARC,NINNER,NGLOBL
 4000 CONTINUE
      ISATL=ISAT
      DO 9000 K=1,NPTS,6
      IF(.NOT.LORBVX) GO TO 6000
      NLINE8=ILINE8+7
      IF(NLINE8.LE.MLINE8) GO TO 5500
      IPAGE8=IPAGE8+1
      ILINE8=3
      WRITE(IOUT8,10000) ISATID,NARC,NINNER,NGLOBL,IPAGE8
      WRITE(IOUT8,10200)
 5500 CONTINUE
      IF(.NOT.LTOP)GOTO 6000
      ILINE8=ILINE8+1
      WRITE(IOUT8,10300)
 6000 CONTINUE
      IF(.NOT.LORBVK) GO TO 7000
      NLIN10=ILIN10+7
      IF(NLIN10.LE.MLIN10) GO TO 6500
      IPAG10=IPAG10+1
      ILIN10=3
      WRITE(IOUT10,20000) ISATID,NARC,NINNER,NGLOBL,IPAG10
      WRITE(IOUT10,20200)
 6500 CONTINUE
      IF(.NOT.LTOP)GOTO 7000
      ILIN10=ILIN10+1
      WRITE(IOUT10,10300)
 7000 CONTINUE
      KP5=K+5
      KP5=MIN(KP5,NPTS)
      DO 8000 I=K,KP5
      IF(.NOT.LORBVX) GO TO 7500
      IF(.NOT.LTOP)GOTO 7400
      CALL DIFF(780601,0,IYMD(I),0,IDAY,ISECXX)
      XJD=IDAY+2443660.0D0
      IH=IHM(I)/100
      IM=IHM(I)-IH*100
      XSEC=(IH*60.0D0+IM)*60.0D0+SEC(I)
      XFRAC=XSEC/8.64D4+0.5D0
      IF(XFRAC.LE.1.0D0) GOTO 7100
         XFRAC=XFRAC-1.0D0
         XJD=XJD+1.0D0
 7100 CONTINUE
      RAS=ATAN2(XS(I,2),XS(I,1))/DEGRAD
      GHA=RAS-SATLON(I)
      GHA=MOD(GHA+720.0D0,360.0D0)
      IF(.NOT.LCASE(3).AND..NOT.LCASE(4).AND..NOT.LCASE(5)) GOTO 7350
      CALL ECFIXP(XS,COSTHG,SINTHG,XE,MINTIM,100,NPTS)
      CALL ECFIXV(VS,COSTHG,SINTHG,XE,VE,MINTIM,100,NPTS)
      IF(LCASE(3)) GOTO 7345
      CALL INPOLE(ETUTC,DPSR,XPUT,YPUT,.FALSE.,.FALSE.,.FALSE.,MJDSTC,  &
     &      FSECTI(I),1,DUM1,NDUM0,NDUM1,NDUM2,NDUM3,DUM2,BIHMAT,DUM3,  &
     &      AA(KXDPOL),AA(KXDOTP))
      XEP(I,1)=BIHMAT(1,1)*XE(I,1)+BIHMAT(2,1)*XE(I,2)+                 &
     &         BIHMAT(3,1)*XE(I,3)
      XEP(I,2)=BIHMAT(1,2)*XE(I,1)+BIHMAT(2,2)*XE(I,2)+                 &
     &         BIHMAT(3,2)*XE(I,3)
      XEP(I,3)=BIHMAT(1,3)*XE(I,1)+BIHMAT(2,3)*XE(I,2)+                 &
     &         BIHMAT(3,3)*XE(I,3)
      VEP(I,1)=BIHMAT(1,1)*VE(I,1)+BIHMAT(2,1)*VE(I,2)+                 &
     &         BIHMAT(3,1)*VE(I,3)
      VEP(I,2)=BIHMAT(1,2)*VE(I,1)+BIHMAT(2,2)*VE(I,2)+                 &
     &         BIHMAT(3,2)*VE(I,3)
      VEP(I,3)=BIHMAT(1,3)*VE(I,1)+BIHMAT(2,3)*VE(I,2)+                 &
     &         BIHMAT(3,3)*VE(I,3)
 7340 CONTINUE
      WRITE(IOUT59,17200) XJD,XFRAC,GHA,(XEP(I,J),J=1,3)
      WRITE(IOUT59,17300) (VEP(I,J),J=1,3),SATLAT(I),SATLON(I),SATH(I)
      GOTO 7360
 7345 CONTINUE
      WRITE(IOUT59,17200) XJD,XFRAC,GHA,(XE(I,J),J=1,3)
      WRITE(IOUT59,17300) (VE(I,J),J=1,3),SATLAT(I),SATLON(I),SATH(I)
      GOTO 7360
 7350 CONTINUE
!C
!C OTHER THAN TOD OUTPUT COORDINATE SYSTEM
         IF(NORBTV.NE.0)  THEN
! TOR
         DO IJ=1,3
         XSTOR(IJ)=XS(I,IJ)
         VSTOR(IJ)=VS(I,IJ)
           ENDDO
!        CALL TDORTR(MJDSTC,FSECTI(I),XSTOR,XSTOR,AA,1,1,.TRUE.,        &
!    &           .TRUE.,II)
!        CALL TDORTR(MJDSTC,FSECTI(I),VSTOR,VSTOR,AA,1,1,.FALSE.,       &
!    &           .TRUE.,II)
         CALL SATUPD(MJDSTC,FSECTI(I),XSTOR,XSTOR,AA,1,1,.TRUE.,        &
     &           .TRUE.,II,0,1)
         CALL SATUPD(MJDSTC,FSECTI(I),VSTOR,VSTOR,AA,1,1,.FALSE.,       &
     &           .TRUE.,II,0,1)
         IF(NORBTV.EQ.2) THEN
! MEAN OF J2000
         X1(1)=XSTOR(1)*REFMT(1)+XSTOR(2)*REFMT(4)+XSTOR(3)*REFMT(7)
         X1(2)=XSTOR(1)*REFMT(2)+XSTOR(2)*REFMT(5)+XSTOR(3)*REFMT(8)
         X1(3)=XSTOR(1)*REFMT(3)+XSTOR(2)*REFMT(6)+XSTOR(3)*REFMT(9)
         V1(1)=VSTOR(1)*REFMT(1)+VSTOR(2)*REFMT(4)+VSTOR(3)*REFMT(7)
         V1(2)=VSTOR(1)*REFMT(2)+VSTOR(2)*REFMT(5)+VSTOR(3)*REFMT(8)
         V1(3)=VSTOR(1)*REFMT(3)+VSTOR(2)*REFMT(6)+VSTOR(3)*REFMT(9)
         ENDIF
         WRITE(IOUT59,17200) XJD,XFRAC,GHA,(X1(J),J=1,3)
         WRITE(IOUT59,17300) (V1(J),J=1,3),SATLAT(I),SATLON(I),SATH(I)
!C OTHER THAN TOD OUTPUT COORDINATE SYSTEM END BELOW IT IS TOD
         ELSE
      WRITE(IOUT59,17200) XJD,XFRAC,GHA,(XS(I,J),J=1,3)
      WRITE(IOUT59,17300) (VS(I,J),J=1,3),SATLAT(I),SATLON(I),SATH(I)
         ENDIF
!C
17200 FORMAT(2D22.15,4D22.15)
17300 FORMAT(6D22.15)
 7360 CONTINUE
      IF ((IHM(I).NE.0).OR.(SEC(I).NE.0.0D0)) GOTO 7500
 7400 CONTINUE
      ILINE8=ILINE8+1
      IYMDP=IYMD(I)
      IF(IYMD(I).GT.991231) IYMDP=IYMD(I)-1000000
!C
!C OTHER THAN TOD OUTPUT COORDINATE SYSTEM
       IF(NORBTV.NE.0)  THEN
! TOR
         DO IJ=1,3
         XSTOR(IJ)=XS(I,IJ)
         VSTOR(IJ)=VS(I,IJ)
         ENDDO
!        CALL TDORTR(MJDSTC,FSECTI(I),XSTOR,XSTOR,AA,1,1,.TRUE.,        &
!    &           .TRUE.,II)
!        CALL TDORTR(MJDSTC,FSECTI(I),VSTOR,VSTOR,AA,1,1,.FALSE.,       &
!    &           .TRUE.,II)
         CALL SATUPD(MJDSTC,FSECTI(I),XSTOR,XSTOR,AA,1,1,.TRUE.,        &
     &           .TRUE.,II,0,1)
         CALL SATUPD(MJDSTC,FSECTI(I),VSTOR,VSTOR,AA,1,1,.FALSE.,       &
     &           .TRUE.,II,0,1)
         DO IJ=1,3
         X1(IJ)=XSTOR(IJ)
         V1(IJ)=VSTOR(IJ)
         ENDDO
           IF(NORBTV.EQ.2) THEN
! MEAN OF J2000
         X1(1)=XSTOR(1)*REFMT(1)+XSTOR(2)*REFMT(4)+XSTOR(3)*REFMT(7)
         X1(2)=XSTOR(1)*REFMT(2)+XSTOR(2)*REFMT(5)+XSTOR(3)*REFMT(8)
         X1(3)=XSTOR(1)*REFMT(3)+XSTOR(2)*REFMT(6)+XSTOR(3)*REFMT(9)
         V1(1)=VSTOR(1)*REFMT(1)+VSTOR(2)*REFMT(4)+VSTOR(3)*REFMT(7)
         V1(2)=VSTOR(1)*REFMT(2)+VSTOR(2)*REFMT(5)+VSTOR(3)*REFMT(8)
         V1(3)=VSTOR(1)*REFMT(3)+VSTOR(2)*REFMT(6)+VSTOR(3)*REFMT(9)
         DO IJ=1,3
         ENDDO
           ENDIF
      IF( ICBDGM .NE. 11 ) THEN
         WRITE(IOUT8,10400) IYMDP,IHM(I),SEC(I),                        &
     &                      (X1(J),J=1,3),(V1(J),J=1,3),                &
     &                      SATLAT(I),SATLON(I),SATH(I)
      ELSE
         WRITE(IOUT8,10401) IYMDP,IHM(I),SEC(I),                        &
     &                      (X1(J),J=1,3),(V1(J),J=1,3),                &
     &                      SATLAT(I),SATLON(I),SATH(I)
      ENDIF
      IF(LASTSN) THEN
         WRITE(IOUT8,10401) IYMDP,IHM(I),SEC(I),                        &
     &   AA(KASTO-1+I),AA(KASTO+MINTIM-1+I),AA(KASTO+2*MINTIM-1+I),     &
     &   AA(KASTO+3*MINTIM-1+I),AA(KASTO+4*MINTIM-1+I),                 &
     &   AA(KASTO+5*MINTIM-1+I)
      ENDIF
!C OTHER THAN TOD OUTPUT COORDINATE SYSTEM END BELOW IS TOD
         ELSE
!
      DO IJ=1,3
        X1(IJ) = XS(I,IJ)
        V1(IJ) = VS(I,IJ)
      ENDDO
! X1 AND V1 ARE ALWAYS TOD NO MATTER WHAT THE INTEGRATION FRAME IS
! NO NEED TO DO ANY TRANSFORMATION
!     IF(MREFSY .EQ. 1) THEN
!     INTEGRATED IN MEAN OF J2000, WE NEED TO DO THE TRANSFORMATION
!       CALL J2000_2_TOD(MJDSTC,FSECTI(I),AA,1,1,II,X1,V1)
!     ENDIF

      IF( ICBDGM .NE. 11 ) THEN
         WRITE(IOUT8,10400) IYMDP,IHM(I),SEC(I),                        &
     &                      (X1(J),J=1,3),(V1(J),J=1,3),            &
     &                      SATLAT(I),SATLON(I),SATH(I)
      ELSE
         WRITE(IOUT8,10401) IYMDP,IHM(I),SEC(I),                        &
     &                      (X1(J),J=1,3),(V1(J),J=1,3),            &
     &                      SATLAT(I),SATLON(I),SATH(I)
      ENDIF
      IF(LASTSN) THEN
         WRITE(IOUT8,10401) IYMDP,IHM(I),SEC(I),                        &
     &   AA(KASTO-1+I),AA(KASTO+MINTIM-1+I),AA(KASTO+2*MINTIM-1+I),     &
     &   AA(KASTO+3*MINTIM-1+I),AA(KASTO+4*MINTIM-1+I),                 &
     &   AA(KASTO+5*MINTIM-1+I)
      ENDIF
         ENDIF
!C
 7500 CONTINUE
      IF(.NOT.LORBVK) GO TO 8000
      ILIN10=ILIN10+1
      KGMP=KPRMV+IPVAL(IXGM)+IBDGM(ICBDGM)-2
      GMP =AA(KGMP)
      CALL ELEM(XS(I,1),XS(I,2),XS(I,3),VS(I,1),VS(I,2),VS(I,3),        &
     &         AEI,0,PKPX,GMP)
      IF(LASTSN) THEN
      CALL ELEM(AA(KASTO-1+I),AA(KASTO+MINTIM-1+I),                     &
     &          AA(KASTO+2*MINTIM-1+I),AA(KASTO+3*MINTIM-1+I),          &
     &          AA(KASTO+4*MINTIM-1+I),AA(KASTO+5*MINTIM-1+I),          &
     &          AEI2,0,PKPX,GMS)
      ENDIF
      IF(.NOT.LTOP)GOTO 7900
      IF ((IHM(I).NE.0).OR.(SEC(I).NE.0.0D0)) GOTO 8000
      ILIN10=ILIN10+1
 7900 CONTINUE
      IYMDP=IYMD(I)
      IF(IYMD(I).GT.991231) IYMDP=IYMD(I)-1000000
      IF( ICBDGM .NE. 11 ) THEN
         WRITE(IOUT10,20400)IYMDP,IHM(I),SEC(I),AEI
      ELSE
         WRITE(IOUT10,20401)IYMDP,IHM(I),SEC(I),AEI
      ENDIF
      IF(LASTSN) THEN
         WRITE(IOUT10,20401)IYMDP,IHM(I),SEC(I),AEI2
      ENDIF
 8000 END DO
 9000 END DO
      RETURN
10000 FORMAT('1',10X,'SPACECRAFT EPHEMERIS FOR SATELLITE',I8,' OF ARC', &
     &   I3,' FOR INNER ITERATION',I3,' OF GLOBAL ITERATION',I2,2X,     &
     &   'UNIT  8 PAGE NO.',I6)
10100 FORMAT('0',10X,'SPACECRAFT EPHEMERIS FOR SATELLITE',I8,' OF ARC', &
     &   I3,' FOR INNER ITERATION',I3,' OF GLOBAL ITERATION',I2)
10200 FORMAT(2X,'DATE  GREENWICH TIME',5X,'INERTIAL CARTESIAN ',        &
     &   'COORDINATES',9X,'INERTIAL CARTESIAN VELOCITY',6X,             &
     &   'GEODETIC',4X,'EAST',7X,'SPHEROID'/                            &
     &   1X,'YYMMDD HHMM  SECONDS',4X,'X(METERS)',4X,'Y(METERS)',4X,    &
     &   'Z(METERS)',3X,'XDOT(M/S)',3X,'YDOT(M/S)',3X,'ZDOT(M/S)',3X,   &
     &   'LAT(DEG)',2X,'LONG(DEG)',4X,'HEIGHT(M)')
10300 FORMAT(1X)
10400 FORMAT(1X,I6,I5,F10.6,3F13.2,3F12.5,2F11.6,F13.2)
10401 FORMAT(1X,I6,I5,F10.6,3G13.6,3G12.5,2F11.6,G13.6)
20000 FORMAT('1',10X,'SPACECRAFT EPHEMERIS FOR SATELLITE',I8,' OF ARC', &
     &   I3,' FOR INNER ITERATION',I3,' OF GLOBAL ITERATION',I2,2X,     &
     &   'UNIT 10 PAGE NO.',I6)
20200 FORMAT(2X,'DATE  GREENWICH TIME',9X,'A',14X,'E',15X,'I',          &
     &   11X,'RA ASC NODE',6X,'ARC PERIGEE',6X,'MEAN ANOMALY'/          &
     &   1X,'YYMMDD HHMM  SECONDS',7X,'(METERS)',14X,4(8X,'(DEGREES)'))
20400 FORMAT(1X,I6,I5,F10.6,F16.3,F15.11,F16.9,3F17.9)
20401 FORMAT(1X,I6,I5,F10.6,1X,F16.3,F15.11,F16.9,3F17.9)
      END
