!$UPDATE
      SUBROUTINE UPDATE(AA,II,LL,PARMV,PARMVC,IPTRUA,IPTRAU,            &
     &                  PARMSG,PARMV0,PDELTA,PNAME,SUM2,PARMVP,PRMSG0,  &
     &                  LOKIT)
!********1*********2*********3*********4*********5*********6*********7**
! UPDATE           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A
!   II      I/O   A
!   LL      I/O   A
!   PARMV
!   PARMVC
!   IPTRUA
!   IPTRAU
!   PARMSG
!   PARMV0
!   PDELTA
!   PNAME
!   SUM2
!   PARMVP
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION  (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CESTIM/MPARM,MAPARM,MAXDIM,MAXFMG,ICLINK,IPROCS,NXCEST
      COMMON/CITER /NINNER,NARC,NGLOBL
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CITERM/MAXINR,MININR,MAXLST,IHYPSW,NXITER
      COMMON/CITERG/MARC,MGLOBL,MGLOBM,                                 &
     &              MGLOCV,NXITRG
      COMMON/CLVIEW/LNPRNT(18),NXCLVI
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA06/KPRMV ,KPNAME,KPRMV0,KPRMVC,KPRMVP,KPRMSG,KPARVR,   &
     &              KPRML0,KPDLTA,KSATCV,KSTACV,KPOLCV,KTIDCV,KSUM1 ,   &
     &              KSUM2 ,KGPNRA,KGPNRM,KPRSG0,KCONDN,KVELCV,          &
     &              KSL2CV,KSH2CV,KTIEOU,KPRMDF,NXCA06
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORI06/KPTRAU,KPTRUA,KNFMG ,KIPTFM,KILNFM,KIGPC ,          &
     &              KIGPS ,KIGPCA,KIGPSA,KIELMT,KMFMG ,KTPGPC,          &
     &              KTPGPS,KTPUC ,KTPUS,                                &
     &              KLINK,KPTFAU,KPTFUA,NXCI06
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CUNIT9/L9SET ,L9RES ,L9RSST,L9RSTY,L9EBS ,L9APAR,L9SUMP,   &
     &              L9GPAR,L9UPDT,L9LAST,L9OUT ,NXUNT9
      COMMON/CVIEW /IOUT6 ,ILINE6,IPAGE6,MLINE6,                        &
     &              IOUT8 ,ILINE8,IPAGE8,MLINE8,                        &
     &              IOUT9 ,ILINE9,IPAGE9,MLINE9,                        &
     &              IOUT10,ILIN10,IPAG10,MLIN10,                        &
     &              IOUT15,ILIN15,IPAG15,MLIN15,                        &
     &              IOUT16,ILIN16,IPAG16,MLIN16,                        &
     &              IOUT7 ,NXCVUE
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/PUNCH /LPNCH ,LPNALL,LPNADJ,LPNITR,NXPUNC
!
      DIMENSION AA(1),II(1),LL(1)
      DIMENSION IPTRUA(1),IPTRAU(1)
      DIMENSION PARMV(1),PARMVC(1)
      DIMENSION PARMSG(1),PARMV0(1),PDELTA(1),PNAME(2,1),SUM2(1),       &
     &          PARMVP(1),PRMSG0(1)
!
      INDXNO(I)=MAPARM*(I-1)-(I*(I-1))/2
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
!**********************************
      NGLBAL=NPVAL0(IXGLBL)
      NSTART=MAPARM-NGLBAL
      ISUM1 =KSUM1 +NSTART
      JJJ=NSTART
      IF(ICLINK.GT.0) JJJ=NSTART+ICLINK
      IPDLTA=KPDLTA+JJJ
      JSUM2 =KSUM2 +NSTART
      NSTART=NSTART+1
      ISTART=INDXNO(NSTART)+NSTART
      JSUM1 =KSUM1 +ISTART-1
!
!  LOOP TO UPDATE ARC PARAMETERS DUE TO GLOBAL SOLUTION
!
! DEBUG SUM1
!     write(6,*)' dbg DEBUG SUM1 ',maparm
!     kk=maparm
!     iend=maparm
!     jj=1
!     ij=1
!2221 continue
!     if(kk.eq.0) goto 42223
!     write(6,22222)((AA(KSUM1+I-1)),i=jj,iend)
!     jj=iend+1
!     iend=iend+maparm-ij
!     kk=kk-1
!     ij=ij+1
!     goto 42221
!2223 continue
!2222 format(12D10.4)
! DEBUG SUM1

      DO 9500 NARC=1,MARC
! LOAD ARC INFORMATION FROM EXTENDED VIRT. MEMORY TO DYNAMIC LOCATIONS
      CALL ARCLOD(AA,II,LL,NARC,.TRUE.,.TRUE.,.TRUE.)

! LOAD CURRENT ARC PARAMETER VALUES (PARMVC) FROM PARMV ARRAY
      NPARC=NPVAL(IXARC)
      DO 200 J=1,NPARC
      IF(IPTRUA(J).LE.0) GO TO 200
      PARMVC(IPTRUA(J))=PARMV(J)
  200 END DO
      IAPARM=NPVAL0(IXARC )
      IF(ICLINK.GT.0) IAPARM=IAPARM-ICLINK
      CALL GPMODA(AA(KSUM1 ),AA(ISUM1 ),AA(IPDLTA),AA(KPDLTA),          &
     &            AA(KPDLTA),IAPARM,NGLBAL,MAPARM)
!
!    USE AA(KSUM2) TO UPDATE THE ARC PARAMETERS
!
      CALL GPMDAE(AA(KSUM1 ),AA(ISUM1 ),AA(JSUM1),                      &
     &            AA(KSUM2),IAPARM,NGLBAL,MAPARM)
!
! RE-MAKE DELTA IF LINKS ARE PRESENT
      IF(ICLINK.GT.0) CALL REDELT(PDELTA,MAPARM,II(KLINK),ICLINK)

      JJJ=IAPARM
!    PRINT OUT NEW ARC SIGMAS
! COMPUTE STANDARD DEVIATION OF ADJUSTED PARAMETERS
      INCR=MAPARM
      J=KSUM1
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      DO 5000 I=1,JJJ
      PDELTA(I)=-PDELTA(I)
      PARMVP(I)=PARMVC(I)
      PARMVC(I)=PARMVC(I)+PDELTA(I)
      SUM2(I)=PARMVC(I)-PARMV0(I)
      PARMSG(I)=SQRT(AA(J))
      J=J+INCR
      INCR=INCR-1
 5000 END DO
! PRINT PARAMETER ADJUSTMENT SUMMARY
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      ILINE6=MLINE6
      DO 7000 I=1,JJJ
      N=IPTRAU(I)
      JLINE6=ILINE6+4
      IF(JLINE6.LE.MLINE6) GO TO 6000
      IPAGE6=IPAGE6+1
      JLINE6=5
      WRITE(IOUT6,10001) NARC,NGLOBL,IPAGE6
      WRITE(IOUT6,20001)
 6000 CONTINUE
      ILINE6=JLINE6
      WRITE(IOUT6,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),SUM2  (I),PRMSG0(I),PARMVC(I),PDELTA(I),             &
     &   PARMSG(I)
 7000 END DO
      IF(.NOT.L9UPDT) GO TO 9000
! SEND PARAMETER ADJUSTMENT SUMMARY TO TERMINAL
      IF(ICLINK.GT.0) JJJ=IAPARM+ICLINK
      ILINE9=MLINE9
      DO 8000 I=1,JJJ
      N=IPTRAU(I)
      JLINE9=ILINE9+4
      IF(JLINE9.LE.MLINE9) GO TO 7500
      IPAGE9=IPAGE9+1
      JLINE9=5
      WRITE(IOUT9,10009) NARC,IPAGE9,NGLOBL
      WRITE(IOUT9,20001)
 7500 CONTINUE
      ILINE9=JLINE9
      WRITE(IOUT9,30000) (PNAME(J,N),J=1,2),PARMV0(I),                  &
     &   PARMVP(I),SUM2  (I),PRMSG0(I),PARMVC(I),PDELTA(I),             &
     &   PARMSG(I)
 8000 END DO
 9000 CONTINUE
!
! PRINT OUT MODIFIED ARC CORRELLATIONS
      IF(.NOT.LNPRNT(14)) CALL CRAAGG(AA(KSUM1),IAPARM,MAPARM,NINNER)
! INVERT CROSS (ARCXGLOBAL) PART OF MATRIX
      CALL CRSVRT(AA(KSUM1),AA(JSUM1),AA(JSUM2),MAPARM,IAPARM,NGLBAL,   &
     &            NSTART)
! PRINT OUT ARCXGLOBAL CORRELATIONS

      IF(.NOT.LNPRNT(14))                                               &
     &  CALL CRAGAG(AA(KSUM1),MAPARM,NSTART,IAPARM,NARC)
!
! PUNCH UPDATED ARC SET INFORMATION
!>>>>>
      WRITE(6,*) 'UPDATE**** LPNITR,LSTINR',LPNITR,LSTINR,NARC
      IF(LPNCH .AND. (LPNITR .OR. LOKIT))                               &
     & CALL CRDPUN(AA    ,II    ,LL    ,NARC  ,NGLOBL,     0,           &
     &          AA(KPRMVC),AA(KPRSG0),LL(KLAFRC),II(KIPDFR),II(KIORFR), &
     &          II(KITACC),II(KISATN),II(KNSAT ),AA(KSTDRG),AA(KSTSRD), &
     &          AA(KSTACC),AA(KA1UT ),II(KPTRUA),II(KINDPI),II(KIPOLC), &
     &          AA(KPUTBH),II(KIELMT),II(KISTNO),II(KICRD ),AA(KPRML0), &
     &          II(KITACX),II(KMBSAT),II(KMBSTA),II(KICNL2),II(KICNH2), &
     &          II(KICNV),AA(KSAVST))
! LOAD PARAMETER VALUES (PARMV) FROM UPDATED PARMVC ARRAY
      DO 9200 J=1,IAPARM
      IF(IPTRAU(J).LE.0) GO TO 9200
      PARMV(IPTRAU(J))=PARMVC(J)
 9200 END DO
! UNLOAD ARC INFORMATION FROM DYNAMIC LOCATIONS TO EXTENDED V. MEMORY
      CALL ARCLOD(AA,II,LL,NARC,.FALSE.,.FALSE.,.TRUE.)
 9500 END DO
!
! PRINT OUT MODIFIED GLOBAL CORRELLATIONS
      CALL CRAAGG(AA(JSUM1),NGLBAL,NGLBAL,NINNER)
      RETURN
10001 FORMAT('1',   'ARC',I3,' PARAMETER ADJUSTMENT SUMMARY FOR ',      &
     &   'UPDATE DUE TO GLOBAL ITERATION',I2,29X,                       &
     &   'UNIT  6 PAGE NO.',I6)
10009 FORMAT('1ARC',I3,' PARAMETER ADJUSTMENT SUMMARY UPDATE',16X,      &
     &   'UNIT 9 PAGE NO.',I4/                                          &
     &   ' FOR GLOBAL ITERATION',I2)
20001 FORMAT('0 ','PARAMETER NAME',                                     &
     &    7X,'APRIORI  VALUE'/                                          &
     &   23X,'PREVIOUS VALUE', 9X,'TOTAL   DELTA', 5X,'APRIORI SIGMA'/, &
     &   23X,'CURRENT  VALUE', 9X,'CURRENT DELTA', 5X,'CURRENT SIGMA')
30000 FORMAT('0',2A8,G24.16/17X,G24.16,G20.12,G16.8/                    &
     &     17X,G24.16,G20.12,G16.8/)
      END
