      SUBROUTINE USETDP(PARMV,PRMFSD)
!********1*********2*********3*********4*********5*********6*********7**
! USETDP
!
! FUNCTION:  UPDATE WORKING ARRAY(S) AND COMMON BLOCK(S) ASSOCIATED
!            WITH SOLID EARTH TIDE DISPLACEMENT MODEL
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   PARMV    I    A    ARRAY OF CURRENT VALUES OF ALL PARAMETERS
!   PRMFSD   O    A    ARRAY CONTAINING FREQUENCY DEPENDENT
!                      SOLID EARTH TIDE DISPLACEMENT PARAMETRS
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
!
      COMMON/NPCOM /NPNAME,NPVAL(92),NPVAL0(92),IPVAL(92),IPVAL0(92),   &
     &              MPVAL(28),MPVAL0(28),NXNPCM
      COMMON/NPCOMX/IXARC ,IXSATP,IXDRAG,IXSLRD,IXACCL,IXGPCA,IXGPSA,   &
     &              IXAREA,IXSPRF,IXDFRF,IXEMIS,IXTMPA,IXTMPC,IXTIMD,   &
     &              IXTIMF,IXTHTX,IXTHDR,IXOFFS,IXBISA,IXFAGM,IXFAFM,   &
     &              IXATUD,IXRSEP,IXACCB,IXDXYZ,IXGPSBW,IXCAME,IXBURN,  &
     &              IXGLBL,IXGPC ,IXGPS, IXTGPC,IXTGPS,IXGPCT,IXGPST,   &
     &              IXTIDE,IXETDE,IXOTDE,IXOTPC,IXOTPS,IXLOCG,IXKF  ,   &
     &              IXGM  ,IXSMA ,IXFLTP,IXFLTE,IXPLTP,IXPLTV,IXPMGM,   &
     &              IXPMJ2,IXVLIT,IXEPHC,IXEPHT,IXH2LV,IXL2LV,IXOLOD,   &
     &              IXPOLX,IXPOLY,IXUT1 ,IXPXDT,IXPYDT,IXUTDT,IXVLBI,   &
     &              IXVLBV,IXXTRO,IXBISG,IXSSTF,IXFGGM,IXFGFM,IXLNTM,   &
     &              IXLNTA,IX2CCO,IX2SCO,IX2GM ,IX2BDA,IXRELP,IXJ2SN,   &
     &              IXGMSN,IXPLNF,IXPSRF,IXANTD,IXTARG,                 &
     &              IXSTAP,IXSSTC,IXSSTS,IXSTAV,IXSTL2,                 &
     &              IXSTH2,IXDPSI,IXEPST,IXCOFF,IXTOTL,NXNPCX
      COMMON/SETDI /NSETDP,NFRSED,NFRSDI,NFRSLN,NXSETI
      COMMON/SETDR /H20,XL20,DH2DP,DL2DP,H3,XL3,DHID,DLID,DHIS,DLIS,    &
     &              XLID,XLISD
!
      DIMENSION PARMV(1),PRMFSD(4,NFRSED)
      DIMENSION HOLD(11)
!
      EQUIVALENCE(XL20,HOLD(1))
!
      H20=PARMV(IPVAL(IXH2LV))
      NNFRL=NSETDP-1-4*NFRSED
      DO I=1,NNFRL
       HOLD(I)=PARMV(IPVAL(IXL2LV)-1+I)
      ENDDO
!
      IPTP=IPVAL(IXL2LV)+NNFRL
!
      DO I=1,NFRSED
         DO J=1,4
           PRMFSD(J,I)=PARMV(IPTP)
           IPTP=IPTP+1
         ENDDO
      ENDDO
!
      RETURN
      END
