!$VMTGEN
      SUBROUTINE VMTGEN(AA,II,LL,MJDVMS,FSCVMS,FSECTI,FSECOT,NTIME,     &
     &                  LEVMF,XI)
!********1*********2*********3*********4*********5*********6*********7**
! VMTGEN           00/00/00            0000.0    PGMR - ?
!
!
! FUNCTION:
!            SENSE OF MJDVMS,MJDVMA,FSCVMS,FSCVMA IS THE NEXT OUTPUT
!            TIME
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   AA      I/O   A
!   II      I/O   A
!   LL      I/O   A
!   MJDVMS
!   FSCVMS
!   FSECTI
!   FSECOT
!   NTIME
!   LEVMF
!   XI
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      COMMON/IOS/ISTOS1,ISTOS2,ISTOS3,ISTLST,INTSUB(3),JNTSUB(3),      &
     &        ILSTSG(80),INTOSP,MAPSAT(3,4)
      COMMON/CBLOKL/LIGHT ,LNRATE,LNREFR,LPOLAD,LTDRIV,LNANT ,LNTRAK,   &
     &       LASER ,LGPART,LGEOID,LETIDE,LOTIDE,LNTIME,LAVGRR,LRANGE,   &
     &       LSSTMD,LSSTAJ,LNTDRS,LPSBL,LACC,LAPP,LTARG,LTIEOU,LEOTRM,  &
     &       LSURFM,LGEOI2,LSSTM2,LOTID2,LOTRM2,LETID2,LNUTAD
      COMMON/CNIARC/NSATA,NSATG,NSETA,NEQNG,NMORDR,NMORDV,NSORDR,       &
     &              NSORDV,NSUMX,NXDDOT,NSUMPX,NPXDDT,NXBACK,NXI,       &
     &              NXILIM,NPXPF,NINTIM,NSATOB,NXBCKP,NXTIMB,           &
     &              NOBSBK,NXTPMS,NXCNIA
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/EMAT  /EMTNUM,EMTPRT,EMTCNT,VMATRT,VMATS,VMATFR,FSCVMA,    &
     &              XEMAT
      COMMON/DTMGDN/TGTYMD,TMGDN1,TMGDN2,REPDIF,XTMGN
      COMMON/NEQINT/NINTOT,MEMTOT,NEQNIM,NXNEQS
      COMMON/VMATFI/MJDVMA
      COMMON/VMATFL/LVMTF,LVMTFO
      DIMENSION AA(1),II(1),LL(1),MJDVMS(1),FSCVMS(1),FSECTI(1),        &
     &          FSECOT(1),NTIME(1),LEVMF(1)
      DIMENSION XI(MINTIM,3,6,2)
      DIMENSION IYMD(1),IHM(1),SEC(1),WORD(12)
      DATA ZERO/0.D0/,EPS/.0000001D0/,X1PE6/1000000.D0/
      DATA WORDE/-999999.D0/
!
!***********************************************************************
! START OF EXECUTABLE CODE *********************************************
!***********************************************************************
!
! TO GET VELOCITY PARTIALS FROM ORBIT NEED TO SET LRANGE=FALSE
      LHR=LRANGE
      LRANGE=.FALSE.
!
!
      ISATA=-1
      DO 4000 ISET=1,NSETA
      IF(ISET.GT.1) ISATA=ISATA+II(KNSAT-2+ISET)
      IF(LEVMF(ISET)) GO TO 4000
! SKIP OVER SET IF NEXT VMAT OUTPUT FOR SET IS LATER THAN FOR SOME SET
      DIFSEC=DBLE(MJDVMS(ISET)-MJDVMA)+(FSCVMS(ISET)-FSCVMA)
      IF(DIFSEC.GT.EPS) GO TO 4000
!  NTIMES TAKES INTO ACCOUNT THE MAX NUM OF OUTPUT TIMES THAT
!  CAN BE INTERPOLATED FROM ONE CALL TO ORBIT
      NPTS=NTIME(ISET)
!  CAN ONLY OUTPUT MULTILE TIMES PER ORBIT CALL WHEN THERE IS ONE SET
!  AND A TOTAL OF NO MORE THAN THREE SATELLITES
      IF(NSETA.GT.1.OR.NSATA.GT.3) NPTS=1
      FSECTN=FSCVMS(ISET)+(NPTS-1)*VMATRT
      ISECTN=INT(FSECTN)
      FSECTN=FSECTN-DBLE(ISECTN)
      MJDSTN=MJDVMS(ISET)+ISECTN
      DIFSEC=VMATS-DBLE(MJDSTN)+(VMATFR-FSECTN)
      IF(DIFSEC.GE.ZERO) GO TO 1000
      LEVMF(ISET)=.TRUE.
      DIFSCS=VMATS-DBLE(MJDVMS(ISET))                                 &
     &            +(VMATFR-FSCVMS(ISET))
      NPTS=INT(DIFSCS/VMATRT)
      NPTS=NPTS+1
 1000 CONTINUE
      DO 2000 N=1,NPTS
      N1=N-1
      FSECTI(N)=FSCVMS(ISET)+DBLE(N1)*VMATRT
 2000 END DO
      DO  2005 JSET=1,NSETA
      LL(KLSETS-1+JSET)=.FALSE.
 2005 END DO
      JSATE=1
      DO  2010 JSET=1,ISET
      JSATB=JSATE
      JSATE=JSATB+II(KNSAT+JSET-1)-1
 2010 END DO
      LL(KLSETS+ISET-1)=.TRUE.
!    CAN ONLY DO 3 SATELLITES AT A TIME
      NTRIES=(JSATE-JSATB)/3+1
      NTRY=0
      ISATB=JSATB-3
      ISATE=MIN(JSATB,JSATE-3)
!
!   LOOP TO 3003 GET UP TO 3 SATELLITES AT A TIME TILL SET IS FINISHED
 2020 CONTINUE
      ISATB=ISATB+3
      ISATE=ISATE+3
      ISATE=MIN(ISATE,JSATE)
      NNNSAT=ISATE-ISATB+1
      NTRY=NTRY+1
      LNRCOT=.FALSE.
      IF(NTRY.GT.1) LNRCOT=.TRUE.
      IK=0
      DO 2030 ISAT=ISATB,ISATE
      II(KIVSAT+IK)=ISAT+ISATA+1
      IK=IK+1
 2030 END DO

      ISATID=II(KISATN-1+ISET)
       IF(NINTOT.GT.0) THEN
      CALL FNDNUM(ISATID,II(KSATIN),NINTOT,IRET)
      IF(IRET.GT.0) THEN
      KSUMXOS=MAPSAT(INTOSP,1)
      KSUMPOS=MAPSAT(INTOSP,2)
      KXDDTOS=MAPSAT(INTOSP,3)
      KPDDTOS=MAPSAT(INTOSP,4)
      KNSTEPS=II(KSTEPS-1+IRET)
      NEQNI=II(KNEQNI-1+IRET)
      ENDIF
      ENDIF

      CALL ORBIT(MJDVMS(ISET),FSECTI,AA(KS),NPTS,II(KINDH),             &
     &   II(KNMH),II(KMJDSC),AA(KFSEC),II(KMJDSV),AA(KFSECV),LL(KLSETS),&
     &   II(KIPXPF),II(KIVSAT),1,II(KNMAX),II(KNTOLD),XI,               &
     &   AA(KPXPFM),.FALSE.,.FALSE.,II(KPLPTR),II(KPANEL),II(KNMOVE),   &
     &   AA(KTPMES),LL(KLTPMS),LL(KSETDN),                              &
     &   AA(KTMOS0-1+INTOSP),AA(KTMOS-1+INTOSP),AA(KTMOSP-1+INTOSP),    &
     &   AA(KSMXOS-1+KSUMXOS),AA(KSMXOS-1+KSUMPOS),AA(KSMXOS-1+KXDDTOS),&
     &   AA(KSMXOS-1+KPDDTOS),KNSTEPS,NEQNI,II(KSGMNT-1+IRET),          &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),AA,II,LL)

      IF(LNRCOT) GO TO 2600
      CALL UTCET(.FALSE.,NPTS,MJDVMS(ISET),FSECTI,FSECOT,AA(KA1UT))
 2600 CONTINUE
!   WRITE  OUT NPTS DATA POINTS
      DO 3000 JPT=1,NPTS
      CALL YMDHMS(MJDVMS(ISET),FSECOT(JPT),IYMD,IHM,SEC,1)
      ISEC=SEC(1)
      SEC(1)=SEC(1)-ISEC
      WORD(1)=DBLE(ISEC+100*IHM(1))+X1PE6*DBLE(IYMD(1))
      WORD(2)=SEC(1)
      WORD(3)=DBLE(MJDVMS(ISET)) + REPDIF
      WORD(4)=FSECTI(JPT)
      DO 2900 ISAT=ISATB,ISATE
      ISATPP=ISAT-ISATB+1
      WORD(5)=XI(JPT,1,ISATPP,1)
      WORD(6)=XI(JPT,2,ISATPP,1)
      WORD(7)=XI(JPT,3,ISATPP,1)
      WORD(8)=XI(JPT,1,ISATPP,2)
      WORD(9)=XI(JPT,2,ISATPP,2)
      WORD(10)=XI(JPT,3,ISATPP,2)
      WORD(11)=II(KISATN+ISATA+ISATPP)
      NFME=II(KNEQN-1+ISET)
      WORD(12)=DBLE(6*NFME)
      JPXPFM=KPXPFM+(ISATPP-1)*NPTS*NFME*6
      IPXPFM=JPXPFM+(JPT-1)*NFME*3
      IPVPFM=IPXPFM+NPTS*NFME*3
      CALL VMTPWR(WORD,NFME,AA(JPXPFM),AA(IPXPFM),AA(IPVPFM),NPTS,JPT)
 2900 END DO
 3000 END DO
      IF(NTRY.LT.NTRIES) GO TO 2020
!  FINISHED WITH THIS SET
!  GET THE NEXT OUTPUT TIME FOR THIS SET
      FSCVMS(ISET)=FSECTI(NPTS)+VMATRT
      ISECVM=INT(FSCVMS(ISET))
      FSCVMS(ISET)=FSCVMS(ISET)-DBLE(ISECVM)
      MJDVMS(ISET)=MJDVMS(ISET)+ISECVM
      XTEST=DBLE(MJDVMS(ISET))-EPS
      IF(XTEST.GT.VMATS) LEVMF(ISET)=.TRUE.
 4000 END DO
!
      LVMTF=.NOT.LEVMF(1)
      MJDVMA=MJDVMS(1)
      FSCVMA=FSCVMS(1)
      IF(NSETA.LT.2) GO TO 6000
      DO 5000 ISET=2,NSETA
      LVMTF=LVMTF.OR..NOT.LEVMF(ISET)
      DIFSEC=DBLE(MJDVMS(ISET)-MJDVMA)+(FSCVMS(ISET)-FSCVMA)
      IF(DIFSEC.GE.EPS) GO TO 5000
      MJDVMA=MJDVMS(ISET)
      FSCVMA=FSCVMS(ISET)
 5000 END DO
 6000 CONTINUE
! RESET LRANGE UPON EXIT
      LRANGE=LHR
! IF DONE WITH VMAT FILE WRITE SENTINEL RECORD
      IF(LVMTF) RETURN
      DO 7000 N=1,12
      WORD(N)=WORDE
 7000 END DO
      CALL VMTPWR(WORD,NFME,AA(KPXPFM),AA(KPXPFM),AA(KPXPFM),1,1)
      RETURN
      END
