!$VTSTST
      SUBROUTINE VTSTST(MJDSN,FSECN,FSECM,FSECK,FSECJ,FSECI, &
     &   XTN,XSM,XTK,XSJ,XTI,VTN,VSM,VTK,VSJ,VTI,XMN,XMK,XMI, &
     &   RNM,RKM,RKJ,RIJ,RRNM,RRKM,RRKJ,RRIJ,URNM,URKM,URKJ,URIJ, &
     &   PRRPNM,PRRPKM,PRRPKJ,PRRPIJ,NMP,INDSTA,INDP,RPOLE,PXPOLE, &
     &   NINTPL,MINTPL,S,S1,XTP,RELV,PXSPXP,PXSPLV,COSTHG,SINTHG, &
     &   INDSAT,SIGNL,NM,LPOLAD,LIGHT,LRANGE,LSKIP1,IEXIT,LTDRSS, &
     &   GRELT1,GRELT2,GRELT3,GRELT4,DELCTN,DELCTK,DELCTI,PSTAT, &
     &   RSUNST,CHEMR,CHMOR,EPOSR,CHEMT,CHMOT,EPOST,CHCBS,CPOSS,SCRTM, &
     &   XSTT,XSTR,XSS,MTYPE,INDSET,BRTS,BRTSV,AA,II,LL, &
     &   LYARA,ISNUMB, LADD, XDPOLE,PXSPXD,UTDT,LVLBI,JJ1,RROT,UEN, &
     &   REN,PSI,TIMVEL,LNUTAD)
!********1*********2*********3*********4*********5*********6*********7**
! MTSTST           83/04/07            8304.0    PGMR - TOM MARTIN
!                  88/09/26                      PGMR - A. MARSHALL
!                  89/09/20            8906.0    PGMR - J. MCCARTHY
!
! FUNCTION:  COMPUTE RANGES AND/OR RANGE RATES WHICH FOLLOW
!            THE PATTERN:
!
!                 Ti-->Sj-->Tk-->Sm-->Tn
!
!                 COMPUTATIONS START AT THE FINAL RECEIVED TIME
!                 MJDSn+FSECn AND PROCEED BACKWARDS UNTIL THE MODEL
!                 IS COMPLETE. IF THE "LIGHT" SWITCH IS .FALSE.
!                 ITERATIVE SOLUTIONS FOR THE LIGHT TIME ARE
!                 PERFORMED. OTHERWISE, THE MEASUREMENT EVENT TIMES
!                 ARE CONSIDERED TO BE KNOWN.
!                 THE SET OF RANGES AND RANGE RATES WHICH FALL INTO
!                 THIS PATTERN INCLUDE TYPES AS FOLLOWS:
!
!                 TYPES  PATTERN
!                 _____  ______________________
!
!                 59/60  T1-->S1-->T3-->S2-->T2
!                 53/54            T2-->S1-->T1
!                 51/52            T1-->S1-->T1
!                 41/42                 S1-->T1
!
!                 THE IEXIT ARGUMENT IS USED TO DESCRIMINATE
!                 BETWEEN SUB-PATTERNS
!
!                 THE LRANGE SWITCH IS USED TO DISCRIMINATE
!                 BETWEEN RANGES AND RANGE RATES
!                 NOTE: LRANGE is true for ranges and average
!                       range rates.  LRANGE is LNRATE in ROBS
!                       which is set if time derivatives are
!                       required.
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSN    I    S    MODIFIED JULIAN DAY SECONDS OF THE FINAL
!                      RECEIVED TIME OF THE FIRST OBSERVATION IN
!                      THE BLOCK
!   FSECN    I    A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH TRACKING STATION Tn
!   FSECM   I/O   A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH SATELLITE Sm
!   FSECK   I/O   A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH TRACKING STATION Tk
!   FSECJ   I/O   A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH SATELLITE Sj
!   FSECI   I/O   A    ELAPSED SECONDS FROM MJDSN OF THE EVENT
!                      TIMES ASSOCIATED WITH TRACKING STATION Ti
!   XTN      O    A    TRUE OF REFERENCE INERT. COORD. OF TRACKING STA. Tn
!   XSM      O    A    TRUE OF REFERENCE INERT. COORD. OF SATELLITE Sm
!   XTK      O    A    TRUE OF REFERENCE INERT. COORD. OF TRACKING STA. Tk
!   XSJ      O    A    TRUE OF REFERENCE INERT. COORD. OF SATELLITE Sj
!   XTI      O    A    TRUE OF REFERENCE INERT. COORD. OF TRACKING STA. Ti
!   VTN      O    A    TRUE OF REFERENCE INERT. VEL. OF TRACKING STA. Tn
!   VSM      O    A    TRUE OF REFERENCE INERT. VEL. OF SATELLITE Sm
!   VTK      O    A    TRUE OF REFERENCE INERT. VEL. OF TRACKING STA. Tk
!   VSJ      O    A    TRUE OF REFERENCE INERT. VEL. OF SATELLITE Sj
!   VTI      O    A    TRUE OF REFERENCE INERT. VEL. OF TRACKING STA. Ti
!   XMN      I    A    MEAN POLE COORDINATES OF TRACKING STATION Tn
!   XMK      I    A    MEAN POLE COORDINATES OF TRACKING STATION Tk
!   XMI      I    A    MEAN POLE COORDINATES OF TRACKING STATION Ti
!   RNM      O    A    SLANT RANGE FROM Tn TO Sm
!   RKM      O    A    SLANT RANGE FROM Tk TO Sm
!   RKJ      O    A    SLANT RANGE FROM Tk TO Sj
!   RIJ      O    A    SLANT RANGE FROM Ti TO Sj
!   RRNM     O    A    RANGE RATE BETWEEN Tn AND Sm
!   RRKM     O    A    RANGE RATE BETWEEN Tk AND Sm
!   RRKJ     O    A    RANGE RATE BETWEEN Tk AND Sj
!   RRIJ     O    A    RANGE RATE BETWEEN Ti AND Sj
!   URNM     O    A    UNIT VECTOR FROM Tn TO Sm
!   URKM     O    A    UNIT VECTOR FROM Tk TO Sm
!   URKJ     O    A    UNIT VECTOR FROM Tk TO Sj
!   URIJ     O    A    UNIT VECTOR FROM Ti TO Sj
!   PRRPNM   O    A    PARTL. OF RNG. RATE W.R.T. Tn-->Sm VECTOR
!   PRRPKM   O    A    PARTL. OF RNG. RATE W.R.T. Tk-->Sm VECTOR
!   PRRPKJ   O    A    PARTL. OF RNG. RATE W.R.T. Tk-->Sj VECTOR
!   PRRPIJ   O    A    PARTL. OF RNG. RATE W.R.T. Ti-->Sj VECTOR
!   NMP      O    A    INDEX OF THE LAST MEASUREMENT ASSOCIATED WITH
!                      EACH INTERPOLATION INTERVAL
!   INDSTA   O    A    POINTER TO INTERNAL STATION NUMBER
!   INDP     O    A    POINTER TO ADJUSTED POLAR MOTION VALUES
!                      ASSOCIATED WITH EACH INTERPOLATION INTERVAL
!   RPOLE    O    A    POLAR MOTION ROTATION MATRICES AT EACH END
!                      OF EACH INTERPOLATION INTERVAL
!   PXPOLE   O    A    PARTIALS OF THE TRUE POLE STATION LOCATION
!                      W.R.T. THE POLAR MOTION X & Y PARAMETERS AT
!                      EACH END OF EACH INTERPOLATION INTERVAL
!   XDPOLE   O    A    PARTIALS OF THE TRUE POLE STATION RATE
!                      W.R.T. THE POLAR MOTION X & Y PARAMETERS AT
!                      EACH END OF EACH INTERPOLATION INTERVAL
!   NINTPL   I    S
!   MINTPL   I    S    MAXIMUM NUMBER OF INTERPOLATION INTERVALS
!   S        O    A    INTERPOLATION FRACTIONS
!   S1       O    A    1.0-S
!   XTP      O    A    TRUE POLE COORDINATES OF A TRACKING STATION
!   RELV     O    A    VELOCITY OF SATELLITE W.R.T. TRACKING STATION
!   PXSPXP   O    A    PARTIALS OF TRUE POLE STATION COORDINATES
!                      W.R.T. POLAR MOTION FOR EACH OF "NM"
!                      MEASUREMENT TIMES
!   PXSPLV   O    A
!   COSTHG   O    A    COSINES OF RIGHT ASCENSION OF GREENWICH
!   SINTHG   O    A    SINES  OF RIGHT ASCENSION OF GREENWICH
!   INDSAT   I    A
!   SIGNL    I    S    SIGN OF THE LIGHT TIME (+1. OR -1.)
!   NM       I    S    NUMBER OF MEASUREMENTS
!   LPOLAD   I    S    SWITCH INDICATING IF POLAR MOTION ADJUST.
!                      PARTIALS ARE REQUIRED FOR EACH INTERP.
!                      INTERVAL
!   LIGHT    I    S    .TRUE. IF LIGHT TIMES HAVE BEEN DETERMINED
!   LRANGE   I    S    .FALSE. WHEN RANGE RATES TO BE COMPUTED
!   LSKIP1   I    S    .TRUE. WHEN 1ST LINE IS TO BE SKIPPED
!   IEXIT    I    S    NUMBER OF LINKS IN MEASUREMENT
!   LTDRSS   I    S    LOGICAL FLAG FOR TDRSS MEASUREMENTS
!   GRELT1-4 O    A    GENERAL REL LIGHT TIME CORRECTION FOR
!                      EACH LINK
!   DELCTN   O    A    DELTA COORDINATE TIME- ET
!   DELCTK   O    A    DELTA COORDINATE TIME- ET
!   DELCTI   O    A    DELTA COORDINATE TIME- ET
!   PSTAT    O    A    SPACE TO HOLD PLANET POSITIONS
!   RSUNST   O    A    DISTANCE BETWEEN SATELLITE AND SUN
!   CHEMR    O    A    EARTH-MOON CHEBYSHEV POLY. FOR RECEIVING
!                      STATION
!   CHMOR    O    A    MOON CHEBYSHEV POLY. FOR RECEIVING
!                      STATION
!   EPOSR    O    A    EARTH POSITION FOR RECEIVING STATION
!   CHEMT    O    A    EARTH-MOON CHEBYSHEV POLY. FOR TRANSMITTING
!                      STATION
!   CHMOT    O    A    MOON CHEBYSHEV POLY. FOR TRANSMITTING
!                      STATION
!   EPOST    O    A    EARTH POSITION FOR TRANSMITTING STATION
!   CHCBS    O    A    CENTRAL BODY CHEBYSHEV POLY. FOR
!                      SATELLITE
!   CPOSS    O    A    CENTRAL BODY POSITION FOR SATELLITE
!   SCRTM    O    A    SCRATCH SPACE
!   XSTT     I    A    TRANSMITTING STATION OFFSET W.R.T. EARTH CENTER
!                      IN THE TRUE OF REFERENCE BARYCENTRIC FRAME
!   XSTR     I    A    RECEIVING STATION OFFSET W.R.T. EARTH CENTER
!                      IN THE TRUE OF REFERENCE BARYCENTRIC FRAME
!   XSS      I    A    SATELLITE OFFSET W.R.T. MARS CENTER IN THE TRUE
!                      OF REFERENCE BARYCENTRIC FRAME
!   BRTS     W    A    BINARY RESIDUAL FILE STATION COOR.
!   BRTSV    W    A    BINARY RESIDUAL FILE STATION VELOCITIES
!   AA      I/O   A    REAL DYNAMIC ARRAY
!   II      I/O   A    INTEGER DYNAMIC ARRAY
!   LL      I/O   A    LOGICAL DYNAMIC ARRAY
!   MTYPE              MEASUREMENT TYPE
!   INDSET             FOR A GIVEN INTERNAL SAT. NUMBER THIS TELLS
!                      WHICH SET THE SAT. BELONGS TO.
!
! COMMENTS:
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
!
      COMMON/CBINRL/LBINR,LLOCR,LODR,LBNCR,LBINRI,LLOCRI,LODRI,LBNCRI,  &
     &              NXCBIN
      COMMON/CEARTH/AEG,AEGSQ,FGINV,FG,EGSQ,EGSQP1,C1,C2,FOURC1,TWOC2,  &
     &              XH2,XL2,WREF,RMEAN,REFC20,REFC40,REFC60,BEG,CBLTC,  &
     &              WAE2,GAMMAA,FSTAR,F4
      COMMON/CEGREL/LGRELE,LRLCLK,LGRELR,LXPCLK,LBPCLK,NXEGRL
      COMMON/CHCOEF/ COEFM(3,15),COEFJ(3,15),COEFSA(3,15),COEFS(3,15),  &
     &               COEFEM(3,15),COEFMO(3,15),COEF(3,15)
      COMMON/CHCOFX/ COEFX(3,25),COEFXX(3,25,988),RLVAL(988)
      COMMON/CIMDST/IDRLTM(200),ITRLTM(200),IRELON,IRLONA,NRLTMC,       &
     & IDRCK4(200),IRKONA,NROCK4,IRKRAD,NXIRTM
      COMMON/CITERL/LSTGLB,LSTARC,LSTINR,LNADJ ,LITER1,LSTITR,          &
     &              LOBORB,LRESID,LFREEZ,LSAVEF,LHALT,LADJPI,LADJCI
      COMMON/CLIGHT/VLIGHT,ERRLIM,XCLITE
      COMMON/CNIGLO/MINTIM,MSATG3,MEQNG ,MEQNG3,MSATG ,MSATOB,MSATA ,   &
     &              MSATA3,MSETA ,MINTVL,MSORDR,MSORDV,NMXORD,          &
     &       MCIPV ,MXBACK,MXI   ,MPXPF ,MAXAB ,MSETDG,MXSATD,          &
     &       MXDEGS,MXDRP ,MXDRPA,MXSRP ,MXSRPA,MXGAP ,MSATDR,          &
     &       MSATSR,MSATGA,MXDRPD,MXSRPD,MXGAPD,MXBCKP,MXTPMS,          &
     &       NSTAIN,NXCNIG
      COMMON/CONTRL/LSIMDT,LOBS  ,LORB  ,LNOADJ,LNADJL,LORFST,LORLST,   &
     &              LORALL,LORBOB,LOBFST,LOBLST,LOBALL,LPREPO,LORBVX,   &
     &              LORBVK,LACC3D,LSDATA,LCUTOT,LACCEL,LDYNAC,LFRCAT,   &
     &              LNIAU, NXCONT
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORA02/KFSCTB,KFSCTC,KFSCTE,KDSECT,                        &
     &              KFSECT,KS    ,KCIP  ,KCIV  ,                        &
     &       KXTN  ,KXSM  ,KXTK  ,KXSJ  ,KXTI  ,KXTKP ,                 &
     &       KVTN  ,KVSM  ,KVTK  ,KVSJ  ,KVTI  ,KVTKP ,                 &
     &       KSATLT,KSATLN,KSATH ,KCOSTH,KSINTH,                        &
     &       KPXPFM,KPXPFK,KPXPFJ,KTRBF ,KFSTRC,                        &
     &       KFSTRE,KDSCTR,KFSCVS,KXSMBF,KXSKBF,KXSJBF,                 &
     &       KRSSV1,KRSSV2,KRSSV3,KTPMES,KACOEF,KACTIM,                 &
     &       KXTNPC,KXSMPC,KXTKPC,KXSJPC,KXTIPC,KXTKPP,                 &
     &       KRLRNG,KASTO,KASTP,NXCA02
      COMMON/CORA03/KRFMT ,KROTMT,KSRTCH,KCFSC ,KTHG  ,KCOSTG,KSINTG,   &
     &              KDPSI ,KEPST ,KEPSM ,KETA  ,KZTA  ,KTHTA ,KEQN  ,   &
     &              KDPSR ,KSL   ,KH2   ,KL2   ,KXPUT ,KYPUT ,KUT   ,   &
     &              KSPCRD,KSPSIG,KSTAIN,KSXYZ ,KSPWT ,KDXSDP,KDPSDP,   &
     &              KXLOCV,KSTNAM,KA1UT ,KPLTIN,KPLTVL,KPLTDV,KPUTBH,   &
     &              KABCOF,KSPEED,KANGFC,KSCROL,KSTVEL,KSTVDV,KTIMVL,   &
     &              KSTEL2,KSTEH2,KSL2DV,KSH2DV,                        &
     &              KAPRES, KASCAL, KASOFF,KXDOTP,KSAVST,               &
     &              KANGT , KSPDT , KCONAM,KGRDAN,KUANG ,KFAMP ,        &
     &              KOFACT, KOTSGN,KWRKRS,KANFSD,KSPDSD,KPRMFS,KSCRFR,  &
     &              KCOSAS,KSINAS,KDXTID,KALCOF,KSTANF,KNUTIN,KNUTMD,   &
     &              KPDPSI,KPEPST,KDXDNU,KDPSIE,KEPSTE,NXCA03
      COMMON/CORA04/KABIAS,KABSTR,KABSTP,KCBIAS,KCBSTR,KCBSTP,          &
     &       KRNM  ,KRKM  ,KRKJ  ,KRIJ  ,KRKPM ,                        &
     &       KRRNM ,KRRKM ,KRRKJ ,KRRIJ ,KRRKPM,                        &
     &       KURNM ,KURKM ,KURKJ ,KURIJ ,KURKPM,                        &
     &       KPRRNM,KPRRKM,KPRRKJ,KPRRIJ,KPRRKP,                        &
     &       KPMPXI,KPMPXE,KRA   ,KRELV ,KUHAT ,KWORK ,KTMPCR,KU    ,   &
     &       KS0   ,KS1   ,KXTP  ,KPXSXP,KPXDXP,KXUTDT,KRPOLE,KPXPOL,   &
     &       KXDPOL,KOBBUF,KOBSC ,KRESID,KSIGMA,KRATIO,KELEVS,          &
     &       KPMPA ,KPXSLV,KTPRTL,                                      &
     &       KFRQOF,KXYZOF,KFRQST,KFRQSA,KSTDLY,KSADLY,KXYZCG,KSCMRA,   &
     &       KEBVAL,KEBSIG,KEBNAM,KBTWB ,KTBTWA,KBTWD ,KPMPE ,          &
     &       KFSEB1,KFSEB2,KSTAMT,KPXSPA,KDIAGN,KOBOUT,KGRLT1,KGRLT2,   &
     &       KGRLT3,KGRLT4,KGRLT5,KPSTAT,KRSUNS,KCHEMR,KCHMOR,KEPOSR,   &
     &       KCHEMT,KCHMOT,KEPOST,KCHCBS,KCPOSS,KSCRTM,KXSTT ,KXSTR ,   &
     &       KXSS  ,KRANGT,KRANGR,KCHB1 ,KCHB2 ,KCHBV1,KCHBV2,KCHEB ,   &
     &       KSSTFQ,KSSTCC,KSSTSS,KSSTWT,KRLCOR,KWVLBI,KQUINF,KBRTS ,   &
     &       KBRTSV,KLRARC,KXEPBF,KXEPBR,KPRCBD,KPRTBD,KXPMPA,KXL,      &
     &       KXSIG ,KXEDTS,KXALO1,KXALO2,KXYOF2,KDLATF,KDLATS,KDLONF,   &
     &       KDLONS,KPF   ,KPS   ,                                      &
     &       KXOBSV,KXOBSW,KXEDSW,                                      &
     &       KXSIGW,KPSF  ,KDNUM ,KCNUM ,KFCOR ,KCOSAR,KSINAR,KSABIA,   &
     &       KSBTM1,KSBTM2,KYAWBS,KVLOUV,KACMAG,KOBSTR,                 &
     &       KPRL1 ,KPRL2, KRL1  ,KT1SE ,KTCP  ,                        &
     &       KRATDR,KFQT1S,KFQT1E,KT1STR,KFTTSE,KFRSTR,KFRRAT,KSV1  ,   &
     &       KSV2  ,KTSLOV,                                             &
     &       KGLGR1,KGLGR2,KGLFR1,KGLFR2,                               &
     &       KARGR1,KARGR2,KARFR1,KARFR2,                               &
     &       KRDS1L,KFT1AV,KDFQP ,KFREQ1,KFREQ3,KSAVD1,KSAVD2,          &
     &       KANTOU,KFM3CF,KF2CF,KTMG,KLTMG,KX2TIM,KX2OBS,KXRNDX,KX2SCR,&
     &       KALTWV,KXXBM ,KX2PAR,KATIME,KPMPAT,KPMATT,KX2PAT,          &
     &       KPXEXI,KPXEPA,KPV,KPXEP2,KX2COF,KACOF2,KACOF3,KBCOF,KBCOF2,&
     &       KDDDA ,KX2AUX,KX2VPR,KX2VPA,KEXTRA,KVARAY,KATROT,KATPER,   &
     &       KLTAR ,KXHOLD,KANTBL,KPHC  ,KOFDRV,KGNAME,KGRSIZ,KGRCNT,   &
     &       KGRDAT,KACCDT,KCTBTI,KCTBWE,KCTCTM,KANTUV,KANTOR,KW1PU ,   &
     &       KPYSQH,KSIGSP,KXYOF3,KXVTM1,KXDIST,KXDST0,KTMSE ,KDSDP ,   &
     &       KEXCST,KEXCDT,KEXCGX,KEXCGY,KEXCGZ,KIMNDX,KIMOBS,KIMTIM,   &
     &       KIMSAT,KM2VPA,KDCDD ,KDWNWT,KDPOR ,KC2PAR,KBOUNC,KBPART,   &
     &       NXCA04
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/CORI02/KNTIME,KMJSTB,KMJSTC,KMJSTE,KISECT,                 &
     &              KINDH ,KNMH  ,KIVSAT,KIPXPF,KNTRTM,KMSTRC,          &
     &              KMSTRE,KISCTR,KISATR,KITRUN,KTRTMB,KTRTMC,          &
     &              KMJDVS,KNTMVM,NXCI02
      COMMON/CORI03/KICRD ,KICON ,KISTNO,KINDPI,KMJDPL,KIPOLC,          &
     &              KNDOLA,KIOLPA,KKIOLA,KIP0OL,KNDOLM,KIOLPM,          &
     &              KKIOLM,KIPVOL,KICNL2,KICNH2,                        &
     &              KSTMJD, KNUMST, KITAST, KSTNRD, KICNV,              &
     &              KTIDES,KFODEG,KFOORD,KRDEGR,KRORDR,                 &
     &              KPHINC,KDOODS,KOTFLG,KJDN  ,KPTDN ,                 &
     &              KATIND,KPRESP,KMP2RS,KSITE,KPTOLS,NXCI03
      COMMON/CORI04/KNMP  ,KINDP ,KNDPAR,KNPVCT,KISATN,KISET ,KIANTO,   &
     &              KISATO,KIANTD,KISATD,KISTAD,KISATC,KMJDCG,KISTAT,   &
     &              KMJDEB,KMJDBN,KNDBIN,KNWTDB,KIXPAR,KNDBUF,KSSTNM,   &
     &              KSSTNA,KMBSAT,KMBSTA,KXKEY ,KXVKEY,KXFLAG,KIPNTF,   &
     &              KIPNTS,KNCON ,KKF   ,KIDATB,KNSTLV,KSLVID,KLLBIA,   &
     &              KTMRA1,KTMRA2,KIND1 ,KTARID,KATARD,KYAWID,KXOBLK,   &
     &              KDSCWV,KATRSQ,KATSAT,KKVLAS,KPARTP,KLTMSC,KLTASC,   &
     &              KCTBST,KSTBST,KANCUT,KANGPS,KANTYP,                 &
     &              KANTOF,                                             &
     &              KYSAT, KMBDEG,                                      &
     &              KMBNOD,KMBSST,KBSPLN,KSSPLN,KXIOBS,KIDLAS,KIAVP ,   &
     &              KXNAVP,KNEXCG,KIDEXC,KNREXC,KTELEO,KIKEY ,KIMKEY,   &
     &              KIMBLK,KIMPRT,KCN110,KCN111,KC110,KC111,KTDSAT,     &
     &              KTDANT,NXCI04
      COMMON/CORL01/KLORBT,KLORBV,KLNDRG,KLBAKW,KLSETS,KLAFRC,KLSTSN,   &
     &              KLSNLT,KLAJDP,KLAJSP,KLAJGP,KLTPAT,KEALQT,KLRDGA,   &
     &              KLRDDR,KLRDSR,KFHIRT,KLSURF,KHRFON,KLTPXH,KSETDN,   &
     &              KTALTA,NXCL01
      COMMON/CORL02/KLNDTT,KLWSTR,KLNDTR,KLEVMF,KLTPMS,NXCL02
      COMMON/CPARFL/LPARFI,LPFEOF,LARCNU,LRORR
      COMMON/CSBSAT/KR,KRT,KZT,KXY2,KUZ,KUZSQ,KTEMP,KC3,KTHETG
! /CSTA  / STATION GEODETIC INFORMATION USED IN MEASUREMENT CORRECTIONS
      COMMON/CSTA/RLAT,COSLAT,SINLAT,RLON,COSLON,SINLON,HEIGHT,         &
     &   TMOUNT,DISP,WAVREC,WAVXMT,ELCUT,PLATNO,SITNOL,SDTLRA,ANTTNO
      COMMON/IBODPT/IBDCF(999),IBDSF(999),IBDGM(999),IBDAE(999),    &
     &              IBDPF(999),                                     &
     &              ICBDCF,ICBDSF,ICBDGM,ICBDAE,ICBDPF,             &
     &              ITBDCF,ITBDSF,ITBDGM,ITBDAE,ITBDPF,NXBDPT
      COMMON/IORCHB/ IORM,IORJ,IORSA,IORSUN,IOREM,IORMO,IORCB,IORTB,    &
     &               IGRP,ICHBOG(2,14),IORSCB(988),NXORCH
      COMMON/LEPHM2/LXEPHM
      COMMON/LOLOAD/LOLMD,LOLAJ,L2FOLT,LAPLOD
      COMMON/OCCLTL/LOCCLT(200),LMSHD(200)
      COMMON/OLDADJ/NPV0OL(3,3),JPV0OL(3,3),NYZ0OL(3,3),JYZ0OL(3,3),    &
     &              NEO0OL(3,3),JEO0OL(3,3)
      COMMON/OLDMOD/NTOLFR,NTOLF2,NTOLMD,NSTAOL,NSITOL,NTOLAJ,MXOLSA,   &
     &              NPOLSH,                                             &
     &              NXOLMD
      COMMON/OLOADA/LXYZCO,LEOPTO
      COMMON/POLESW/LDNPOL,NXPOLS
      COMMON/SETDI /NSETDP,NFRSED,NFRSDI,NFRSLN,NXSETI
      COMMON/UNITS/IUNT11,IUNT12,IUNT13,IUNT19,IUNT30,IUNT71,IUNT72,    &
     &             IUNT73,IUNT05,IUNT14,IUNT65,IUNT88,IUNT21,IUNT22,    &
     &             IUNT23,IUNT24,IUNT25,IUNT26
      COMMON/VMATFL/LVMTF,LVMTFO
      COMMON/TIDEOP/EOPTID(2,3)
      COMMON/XTRAOR/T0XTRO,T0XTRO2,CVENUS,CLIBMN,CMARS,CMERC,XXTRAO
!
      DIMENSION DUM(4,1),RROT(3,3),STANFO(25)
      DIMENSION DUM4(3),DUM5(3,2,1)
      DIMENSION FSECN(NM),FSECM(NM),FSECK(NM),FSECJ(NM),FSECI(NM), &
     &   XTN(MINTIM,3),XSM(MINTIM,3),XTK(MINTIM,3),XSJ(MINTIM,3), &
     &   XTI(MINTIM,3),VTN(MINTIM,3),VSM(MINTIM,3),VTK(MINTIM,3), &
     &   VSJ(MINTIM,3),VTI(MINTIM,3), &
     &   XMN(3),XMK(3),XMI(3),RNM(NM),RKM(NM),RKJ(NM),RIJ(NM), &
     &   RRNM(NM),RRKM(NM),RRKJ(NM),RRIJ(NM), &
     &   URNM(NM,3,2),URKM(NM,3,2),URKJ(NM,3,2),URIJ(NM,3,2), &
     &   NMP(MINTPL,4), &
     &   PRRPNM(NM,3),PRRPKM(NM,3),PRRPKJ(NM,3),PRRPIJ(NM,3),NINTPL(4), &
     &   INDSTA(3),INDP(MINTPL,4),RPOLE(3,3,MINTPL),PXPOLE(3,2,MINTPL), &
     &   S(NM),S1(NM),XTP(NM,3),RELV(NM,3),PXSPXP(NM,3,2,4), &
     &   PXSPLV(NM,3,NSETDP,4),COSTHG(NM,4),SINTHG(NM,4),INDSAT(3), &
     &   GRELT1(NM),GRELT2(NM),GRELT3(NM),GRELT4(NM),DELCTN(NM), &
     &   DELCTK(NM),DELCTI(NM),PSTAT(NM,6),RSUNST(NM),BRTS(MINTIM,3), &
     &   BRTSV(MINTIM,3),AA(1),II(1),LL(1), &
     &   CHEMR(NM,15),CHMOR(NM,12),EPOSR(NM,3),CHEMT(NM,15), &
     &   CHMOT(NM,15),EPOST(NM,3),CHCBS(NM,1),CPOSS(NM,3), &
     &   SCRTM(NM,90),XSTT(MINTIM,3),XSTR(MINTIM,3),XSS(MINTIM,3), &
     &   INDSET(3),XDPOLE(3,2,MINTPL),PXSPXD(NM,3,2,4),UTDT(NM,4)
!
! THE ORDER OF THE FOLLOWING SAT AND STATION ARRAYS MUST BE MAINTAINED
! IN THE ARGUMENT LIST OF THIS ROUTINE.  INDEXING IN LITEUP AND LITEDN
! FOR THE S/C ARRAY DEPENDS ON THIS ORDER.
!
      DIMENSION XENV(3,3),UEN(3,3),REN(3,3)
      EQUIVALENCE (STANFO(1),RLAT)
!
!
      DATA J1,J2P,J3,J4/1,2,3,4/
      DATA TWO/2.0D0/,ZERO/0.D0/
!
!********1*********2*********3*********4*********5*********6*********7**
! START OF EXECUTABLE CODE
!********1*********2*********3*********4*********5*********6*********7**

      DO I=1,6
       EOPTID(I,1)=0.D0
      ENDDO
!
!
!     ....set switch to indicate range rate measurement
!
      J1N=J1
      IF(LVLBI) J1N=JJ1
       LTDR1W=MTYPE.EQ.56
      LRRATE = MOD( MTYPE,2 ) .EQ. 0
      LSIMX=LSIMDT
      IF(ICBDGM.EQ.ITBDGM) LSIMX=.FALSE.
      KTRJX=KVTKP+3*MINTIM
      KTRJV=KTRJX+3*MINTIM
!
!
!
!
!
!
      IF(LOLMD) THEN
        CALL OLDSET(J1N,INDSTA(J1N),NM,AA(KSTAIN),II(KIP0OL),II(KNDOLA),&
     &              II(KKIOLA),LOLAJ,LOLMDS, &
     &              JABCOF,JPXSPA,JOLPAE,JOLPAN,JOLPAV,JXLOCV, &
     &              JABCCM,JPXSP1,JOLPXC,JOLPYC,JOLPZC, &
     &              JABCEO,JPXSP2,JOLPXP,JOLPYP,JOLPUP,LALOAD,ISITA, &
     &              XENV)
      ENDIF
      IF(LEOPTO.OR.LOLMDS.OR.LXYZCO) THEN
         CALL OLTIME(MJDSN,FSECN,NM,AA(KANGFC),AA(KSPEED),AA(KSCROL), &
     &               AA(KSCROL+4*NTOLFR),II(KPTOLS),AA(KANGT), &
     &               AA(KCONAM),AA(KTWRK1),AA(KGRDAN),AA(KUANG), &
     &               AA(KFAMP),II(KJDN))
      ENDIF
      IF(LEOPTO) THEN
         CALL OLDEOP(MJDSN,FSECN,NM,AA(JABCOF),AA(KANGFC),AA(KSPEED), &
     &           AA(JXLOCV),XTP,AA(KSCROL),AA(KROTMT),LOLAJ, &
     &           AA(JPXSPA),NPV0OL(1,J1N),NPV0OL(2,J1N),NPV0OL(3,J1N), &
     &           II(JOLPAE),II(JOLPAN),II(JOLPAV),AA(JABCCM), &
     &           AA(JPXSP1),NYZ0OL(1,J1N),NYZ0OL(2,J1N),NYZ0OL(3,J1N), &
     &           II(JOLPXC),II(JOLPYC),II(JOLPZC),AA(JABCEO), &
     &           AA(JPXSP2),NEO0OL(1,J1N),NEO0OL(2,J1N),NEO0OL(3,J1N), &
     &           II(JOLPXP),II(JOLPYP),II(JOLPUP),LOLMDS,LXYZCO, &
     &           LEOPTO,XMN)
      ENDIF


! OBTAIN POLAR MOTION ROTATION MATRICES AND PARTIAL DERIVATIVE MATRICES
!        FROM WHICH TO INTERPOLATE ACROSS THE ENTIRE BLOCK OF DATA

      NINTP2=NINTPL(J1N)*2

      CALL STATPVP(AA,II,LL,LDNPOL,LPOLAD,MJDSN,FSECN,NM,XMN,           &
     &   NINTPL(J1N),                                                   &
     &   NMP(1,J1N),INDP(1,J1N),PXPOLE,RPOLE,S,XDPOLE,XTP,              &
     &   PXSPXP(1,1,1,J1N)                                              &
     &   ,PXSPLV(1,1,1,J1N),NINTP2,.TRUE.,INDSTA(J1N),.TRUE.,           &
     &   LYARA,ISNUMB,PXSPXD(1,1,1,J1N),COSTHG(1:NM,J1N),               &
     &   SINTHG(1:NM,J1N), AA(KSRTCH),UTDT(1,J1N),S1,FSECN,AA(KDXDNU),  &
     &   LNUTAD)


      CALL GRHRAP(MJDSN,FSECN,.TRUE.,.TRUE. ,AA(KEQN),AA(KSRTCH), &
     &   AA(KTHETG),COSTHG(1,J1N),SINTHG(1,J1N),NM,AA,II,UTDT(1,J1N),   &
     &   .FALSE.,XMN,DUM5)

      TIMVEL=AA(KTIMVL-1+INDSTA(J1N))
      IF(.NOT.LOLMDS.AND..NOT.LXYZCO) GO TO 500
      CALL OLOAD(MJDSN,FSECN,NM,AA(JABCOF),AA(KANGFC),AA(KSPEED), &
     &           AA(JXLOCV),XTP,AA(KSCROL),AA(KROTMT),LOLAJ, &
     &           AA(JPXSPA),NPV0OL(1,J1N),NPV0OL(2,J1N),NPV0OL(3,J1N), &
     &           II(JOLPAE),II(JOLPAN),II(JOLPAV),AA(JABCCM), &
     &           AA(JPXSP1),NYZ0OL(1,J1N),NYZ0OL(2,J1N),NYZ0OL(3,J1N), &
     &           II(JOLPXC),II(JOLPYC),II(JOLPZC),AA(JABCEO), &
     &           AA(JPXSP2),NEO0OL(1,J1N),NEO0OL(2,J1N),NEO0OL(3,J1N), &
     &           II(JOLPXP),II(JOLPYP),II(JOLPUP),LOLMDS,LXYZCO,LEOPTO, &
     &           isnumb,.FALSE.,NM,LALOAD,AA(KALCOF),II(KSITE),ISITA, &
     &           XENV)
 500  CONTINUE
! ROTATE TRUE POLE STATION COORDINATES TO TRUE OF DATE ACROSS ENTIRE
!        BLOCK OF DATA
!     PRINT 12349
!2349 FORMAT(' ** MTSTST **  CALL INERTP')
      CALL INERTP(XTP,COSTHG(1,J1N),SINTHG(1,J1N),XTN,NM,MINTIM,NM)
! STORE OFF TOD TRACKING STATION COORDINATES FOR BINRES FILE
            DO 510 IS=1,3
            DO 510 NN=1,NM
            BRTS(NN,IS)=XTN(NN,IS)
 510        CONTINUE
! COMPUTE INERTIAL STATION VELOCITIES IF NECESSARY
      IF(.NOT.LRANGE) &
     &CALL INRTSV(COSTHG(1,J1N),SINTHG(1,J1N),XTN,VTN,NM,MINTIM)
      CALL TDORTR(MJDSN,FSECN,XTN,XTN,AA,NM,MINTIM,.TRUE.,.TRUE.,II)
      IF(.NOT.LRANGE) &
     &CALL TDORTR(MJDSN,FSECN,VTN,VTN,AA,NM,MINTIM,.FALSE.,.TRUE.,II)
!     write(6,*)' dbg inertial velocity vectors for geodyn '
! get the complete matrix from trs to crs
      CALL ICRSITRF(AA(KROTMT),AA(KDPSR),AA(KXPUT),AA(KYPUT), &
     &              AA(KA1UT),II(KINDPI),MJDSN,FSECN(1), &
     &              AA(KCOSTH),AA(KSINTH),1,MINTIM,DUM,2, &
     &              AA(KXDPOL),AA(KXDOTP),RROT,.TRUE.)
! FORM THE UEN (Up East North matrix in the same sequence as VLBI vtd
      JSTA=INDSTA(JJ1)
      JXLOC=KXLOCV+9*(JSTA-1)
      UEN(1,2)=AA(JXLOC)
      UEN(2,2)=AA(JXLOC+1)
      UEN(3,2)=AA(JXLOC+2)
      UEN(1,3)=AA(JXLOC+3)
      UEN(2,3)=AA(JXLOC+4)
      UEN(3,3)=AA(JXLOC+5)
      UEN(1,1)=AA(JXLOC+6)
      UEN(2,1)=AA(JXLOC+7)
      UEN(3,1)=AA(JXLOC+8)
!
! Compute the REN Radial-Easr-North matrix - For this we need the
! geocentric latitude
      JSTAIN=KSTAIN+NSTAIN*(JSTA-1)
      STANFO(9)=AA(JSTAIN+8)
      STANFO(8)=AA(JSTAIN+7)
      STANFO(1)=AA(JSTAIN)
      STANFO(4)=AA(JSTAIN+3)
      STANFO(7)=AA(JSTAIN+6)
! cosine of geodetic latitude
      STANFO(2)=AA(JSTAIN+1)
! sine of geodetic latitude
      STANFO(3)=AA(JSTAIN+2)
! compute tanphi
      tanphi=STANFO(3)/STANFO(2)
      STANFO(5)=AA(JSTAIN+4)
      STANFO(6)=AA(JSTAIN+5)
      fact=(1.D0-fg)**2.D0
      tanpsi=fact*tanphi
      psi=ATAN(tanpsi)
      cospsi=COS(psi)
      sinpsi=SQRT(1.D0-cospsi**2.D0)
!   CALCULATE LOCAL VERTICLE FIRST
      REN(1,1)=cospsi*STANFO(5)
      REN(2,1)=cospsi*STANFO(6)
      REN(3,1)=sinpsi
!   CALCULATE LOCAL NORTH
      REN(1,3)=-sinpsi*STANFO(5)
      REN(2,3)=-sinpsi*STANFO(6)
      REN(3,3)=cospsi
!   CALCULATE LOCAL EAST
      REN(1,2)=-STANFO(6)
      REN(2,2)=STANFO(5)
      REN(3,2)=ZERO
      IF(LVLBI) GO TO 1010
!
!***** INERTIAL TRACKING STATION #n POSITIONS NOW COMPUTED *************
!
!2351 FORMAT(' ** MTSTST **  CALL ORBSET')

      CALL ORBSET(II(KNSAT),II(KIVSAT),LL(KLSETS),INDSAT(J1N) ,         &
     &   KNSTEPS,NEQNI,II(KSGMNT-1+IRET),                               &
     &   AA(KSGTM1-1+IRET),AA(KSGTM2-1+IRET),IRET,MJDSN,FSECM(1),       &
     &   FSECM(NM),NM,AA,II)
!
! SAVE STATION OFFSETS(IN PLANET CENTERED COORDINATES)
      MIN3 = MINTIM*3
      IF (ITBDGM .EQ. ICBDGM) GOTO 1100
      DO 1050 I=1,3
      DO 1050 J=1,MINTIM
      XSTR(J,I)=XTN(J,I)
 1050 CONTINUE
 1100 CONTINUE
!
!
!***** START HERE TO COMPUTE LINK #1 TRANSIT TIMES TO SATELLITE ********
!
! INITIALIZE SATELLITE Sm TIMES TO EQUAL STATION Tn TIMES
      DO 1000 N=1,NM
      FSECM(N)=FSECN(N)
 1000 CONTINUE
 1010 CONTINUE
! ITERATIVELY COMPUTE SATELLITE TIMES
      CALL LITEVP(XTN,XSM,RNM,URNM,URNM(1,2,1),URNM(1,3,1),S,MJDSN, &
     &         FSECN,FSECM,SIGNL,DELCTN,RSUNST,GRELT1,PSTAT,NM, &
     &         SCRTM,AA(KTPMES+4*MINTIM),LL(KLTPMS+6*MINTIM),AA,II,LL, &
     &         LVLBI)
!     write(6,*)' dbg DELCTN after LITEVP ',DELCTN
      DO 1009 I=1,3
      DO 1009 J=1,MINTIM
      XSTR(J,I)=XTN(J,I)
 1009 CONTINUE
! GET COORDINATE EPHEMERIS TIME AT TRACKING STATION TIME
      DO 1011 N=1,NM
      RNM(N)=FSECN(N)+DELCTN(N)
 1011 CONTINUE
      RETURN
      END
