!$YRKVSK
      SUBROUTINE YRKVSK(MJDSEC,FSEC,XSAT,VSAT,ACC,SUNXYZ,ISATID,AA,II)
!********1*********2*********3*********4*********5*********6*********7**
! YRKVSK                                         PGMR - D. E. PAVLIS
!
! FUNCTION: (1) CALCULATE THE YARKOVSKY-SCHACH EFFECT ACCELERATION
!               FOR LAGEOS AND LAGEOS II
!           (2) CALCULATE THE ASSYMETRIC REFLECTIVITY EFFECT ACCELERATIO
!
!
! I/O PARAMETERS:
!
!   NAME    I/O  A/S   DESCRIPTION OF PARAMETERS
!   ------  ---  ---   ------------------------------------------------
!   MJDSEC   I    S    MEASUREMENT BLOCK START TIME IN MJD SECONDS
!   FSEC     I    S    FRACTIONAL SECONDS
!   XSAT     I    A    POSITION VECTOR OF SATELLITE
!   VSAT     I    A    VELOCITY VECTOR OF SATELLITE
!   ACC      O    A    OUTPUT ACCELERATIONS
!   SUNXYZ   I    A    SUN POSITION IN THE TOD SYSTEM
!   ISATID   I    S    S/C ID
!   AA       I    A    REAL DYNAMIC ARRAY
!   II       I    A    INTEGER DYNAMIC ARRAY
!
!
! COMMENTS:
!
!
!********1*********2*********3*********4*********5*********6*********7**
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      SAVE
      DOUBLE PRECISION N
      CHARACTER*6 FILNAM
!     COMMON BLOCKS
      COMMON/CBDTRU/BDTRUE(7,999)
      COMMON/CELEMX/TRUE,ECC
      COMMON/CGRAV/GM,AE,AESQ,FE,FFSQ32,FSQ32,XK2,XK3,XLAM,SIGXK2,      &
     &      SIGXK3,SIGLAM,RATIOM(2),AU,RPRESS
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      COMMON/CORA01/KFSEC0,KFSECB,KFSEC ,KFSECV,KH    ,KHV   ,KCTOL ,   &
     &              KRSQ  ,KVMATX,KCPP  ,KCPV  ,KCCP  ,KCCV  ,KCCPV ,   &
     &              KCCVV ,KXPPPP,KX    ,KPX   ,KSUMX ,KXDDOT,KSUMPX,   &
     &              KPXDDT,KAB   ,KPN   ,KAORN ,KSINLM,KCOSLM,KTANPS,   &
     &              KCRPAR,KVRARY,KXM   ,KXNP1 ,KXPRFL,KXM2  ,KXNNP1,   &
     &              KWRK  ,KFI   ,KGE   ,KB0DRG,KBDRAG,KAPGM ,KAPLM ,   &
     &              KCN   ,KSN   ,KSTID ,KTIDE ,KSTDRG,KSTSRD,KSTACC,   &
     &              KLGRAV,KGM   ,KAE   ,KFPL  ,KFEQ  ,KPLNPO,KPLNVL,   &
     &              KXEPOC,KCD   ,KCDDOT,KCR   ,KGENAC,KACN  ,KASN  ,   &
     &              KTHDRG,KCKEP ,KCKEPN,KXNRMZ,KXNRMC,KFSCEP,KFSCND,   &
     &              KAREA ,KXMASS,KRMSPO,KTCOEF,KTXQQ ,KTIEXP,KTXMM ,   &
     &              KTXLL1,KTXSN1,KTS2QQ,KT2M2H,KT2MHJ,KTXKK ,KTSCRH,   &
     &              KPXPK ,KAESHD,KCSAVE,KSSAVE,KCGRVT,KSGRVT,KXDTMC,   &
     &              KDNLT ,KTXSN2,KTNORM,KTWRK1,KTWRK2,KUNORM,KAERLG,   &
     &              KSINCO,KPARLG,KCONST,KBFNRM,KTDNRM,KCSTHT,KTPSTR,   &
     &              KTPSTP,KTPFYW,KPLMGM,KTPXAT,KEAQAT,KEAFSS,KEAINS,   &
     &              KACS  ,KECS  ,KSOLNA,KSOLNE,KSVECT,KSFLUX,KFACTX,   &
     &              KFACTY,KADIST,KGEOAN,KPALB ,KALBCO,KEMMCO,KCNAUX,   &
     &              KSNAUX,KPPER ,KACOSW,KBSINW,KACOFW,KBCOFW,KANGWT,   &
     &              KWT   ,KPLNDX,KPLANC,KTGACC,KTGDRG,KTGSLR,KWTACC,   &
     &              KWTDRG,KWTSLR,KTMACC,KTMDRG,KTMSLR,KATTUD,KDYACT,   &
     &              KACCBT,KACPER,KXDDNC,KXDDAO,KXNC  ,KXPPNC,KSMXNC,   &
     &              KXDDTH,KPDDTH,KXSSBS,KCPPNC,KEXACT,KXACIN,KXACOB,   &
     &              KPXHDT,KTPXTH,KPACCL,KTXSTA,KDELXS,KSMRNC,KPRX  ,   &
     &              KSMRNP,KDSROT,KXUGRD,KYUGRD,KZUGRD,KSUMRC,KXDDRC,   &
     &              KTMOS0,KTMOS, KTMOSP,KSMXOS,KSGTM1,KSGTM2,KSMPNS,   &
     &              KXGGRD,KYGGRD,KZGGRD,KXEGRD,KYEGRD,KZEGRD,KSSDST,   &
     &              KSDINS,KSDIND,KSSDSR,KSSDDG,KTATHM,KTAINS,KTAFSS,   &
     &              KSRAT ,KTRAT ,KHLDV ,KHLDA1,KHLDA4,KHLDA7,KQAST1,   &
     &              KQAST2,KQAST3,KQAST4,KQAST5,KQAST6,NXCA01
      COMMON/CORI01/KMJDS0,KMJDSB,KMJDSC,KMJDSV,KIBACK,KIBAKV,KIORDR,   &
     &              KIORDV,KNOSTP,KNOCOR,KNSAT ,KN3   ,KNEQN ,KNEQN3,   &
     &              KNH   ,KNHV  ,KNSTPS,KNSTPV,KICPP ,KICPV ,KICCP ,   &
     &              KICCV ,KICCPV,KICCVV,KISUMX,KIXDDT,KISMPX,KIPXDD,   &
     &              KNMAX ,KNTOLD,KNTOLO,KICNT ,KISNT ,KMM   ,KKK   ,   &
     &              KJJ   ,KHH   ,KIBDY ,KSIGN1,KSIGN2,KLL   ,KQQ   ,   &
     &              KIORFR,KIPDFR,KITACC,KJSAFR,KJSPFR,KMJDEP,KMJDND,   &
     &              KNVSTP,KNSTRN,KNDARK,KTIPPT,KTJBDY,                 &
     &              KICNTA,KISNTA,KISHDP,KIPTC ,KIPTS ,KIGTSR,KIXTMC,   &
     &              KTIPTT,KTNOSD,KTQNDX,KTLL1 ,KTJJBD,KTITDE,KTCNTR,   &
     &              KTNN  ,KITACX,KNMOVE,KPANEL,KPLPTR,KNADAR,KNADSP,   &
     &              KNADDF,KNADEM,KNADTA,KNADTC,KNADTD,KNADTF,KNADTX,   &
     &              KITPMD,KSCATT,KITPAT,KILTPX,KEASBJ,KEANMP,KEANAN,   &
     &              KEAPMP,KEAPAN,KEAMJS,KEAPPP,KEAAAA,KICNTT,KISNTT,   &
     &              KTPGRC,KTPGRS,KTPC  ,KTPS  ,KALCAP,KEMCAP,KNSEG ,   &
     &              KICNTP,KISNTP,KNRDGA,KNRDDR,KNRDSR,KIRDGA,KIRDRG,   &
     &              KIRSLR,KSTRTA,KSTRTD,KSTRTS,KDYNPE,KACCPE,KIBCKN,   &
     &              KNRAT ,KIXDDN,KISMXN,KDXDDN,KDSMXN,KICPPN,KACSID,   &
     &              KNEQNH,KHRFRC,KPTFBS,KPTFSB,KIPXDA,KIACCP,KXSTAT,   &
     &              KPXST ,KSALST,KMAPLG,KNMBUF,KSTEPS,KSGMNT,KSATIN,   &
     &              KMEMST,KNEQNI,KBUFIN,KWEMGA,KWEMDR,KTPATS,KTANMP,   &
     &              KTAPPP,KTAMJS,KTASID,KGPSID,KNSSVA,KPNALB,KBRAX1,   &
     &              KBRAX2,KBRAX3,NXCI01
      COMMON/LYARKO/LYARK,LTYP1,LTYP2,LMOD1,LMOD2,LYSHAD,LYE1,LSUN
      COMMON/THERMD/DRGSAT,DTHSC,ZETA,SPAXT,SPAXL,THRMFL,XTHERM
      COMMON/YARSCH/YARTYP,YARMOD,AYAR,TAU,RISYEN,FSEYEN,RISYEX,FSEYEX, &
     &              SMEANM,XYARMD
!     DIMENSIONS
      DIMENSION AA(1),II(1)
      DIMENSION ACC(3),S(3),AEI(6)
      DIMENSION SUNXYZ(3)
      DIMENSION XHELIO(3),XSAT(3),VSAT(3),USUN(3)
      DIMENSION IDYSAT(2),SATDAT(4,2)
      DATA IDYSAT/7603901,9207002/
      DATA SATDAT/0.890055D0,0.307455D0,1976.33972602739732D0,13524D0,  &
     &            0.727332D0,0.461128D0,1992.80821917808225D0,13344D0/
      DATA ONE/1.D0/
!
!**********************************************************************
!* START OF EXECUTABLE CODE *******************************************
!**********************************************************************
!
! DEBUG
!     WRITE(6,*)' dbg Y ENTRY ',ISATID
!     write(6,*)' SATDAT '
!     write(6,*)SATDAT(1,1),SATDAT(2,1),SATDAT(3,1),SATDAT(4,1)
!     write(6,*)SATDAT(1,2),SATDAT(2,2),SATDAT(3,2),SATDAT(4,2)
! DEBUG
      IF(ISATID.NE.IDYSAT(1).AND.ISATID.NE.IDYSAT(2)) THEN
      WRITE(6,*)' THE YARKOVSKY MODEL IS AVAILABLE ONLY FOR LAGEOS I '
      WRITE(6,*)' AND LAGEOS II  -- EXECUTION TERMINATES IN  YRKVSK '
      STOP 16
      ENDIF
      KK=1
      IF(ISATID.EQ.IDYSAT(2)) KK=2


! THE COMPUTATIONS BELOW ARE NECESSARY REGARDLESS OF THE TYPE OF THE RUN
!
! COMPUTE THE COMPONENTS OF THE VECTOR S (Satellite Spin Unit Vector)
      RADT=SPAXT*DEGRAD
      RADL=SPAXL*DEGRAD
      SRADT=SIN(RADT)
      S(1)=SRADT*COS(RADL)
      S(2)=SRADT*SIN(RADL)
      S(3)=COS(RADT)
!     DEBUG
!     WRITE(6,*)' dbg RADT ',RADT
!     WRITE(6,*)' dbg RADTL',RADL
!     WRITE(6,*)' dbg RSADT',SRADT
!     WRITE(6,*)' dbg S ',S
!     DEBUG
!
!     Z1 THE SATELLITE LONGITUDE AT THE ECLIPSE ENTRANCE
!     Z2 THE SATELLITE LONGITUDE AT THE ECLIPSE EXIT
!     DZ = Z2-Z1
!     DZ IS NEEDED IN ORDER TO COMPUTE THE CONSTANTS C0 AND C1 GOOD
!        FOR THE ENTIRE EVENT OF SHADOW CROSSING. THEREFORE DZ NEEDS
!        TO BE AVAILABLE IMMEDIATELY WHEN THE SATELLITE ENTERS THE
!        SHADOW. IN A "FIRST" GEODYN RUN WHICH WILL BECOME AN ORBGEN
!        THE ANGLES Z1 AND Z2 WILL BE COMPUTED AND SAVED IN A BINARY
!        FILE. THIS FILE WILL BE READ in a "SECOND" DATA REDUCTION TYPE
!        GEODYN RUN  WHERE THE YARKOVSY ACCELERATIONS WILL BE COMPUTED.
!
      ZMAG = SQRT(XSAT(1)**2+XSAT(2)**2+XSAT(3)**2)
      R=ZMAG
      RSQ=ZMAG*ZMAG
      RATIO=ONE
      XHELIO(1)=XSAT(1)-BDTRUE(1,8)
      XHELIO(2)=XSAT(2)-BDTRUE(2,8)
      XHELIO(3)=XSAT(3)-BDTRUE(3,8)
      RSSQ=XHELIO(1)**2+XHELIO(2)**2+XHELIO(3)**2
      RS=SQRT(RSSQ)
      USUN(1)=XHELIO(1)/RS
      USUN(2)=XHELIO(2)/RS
      USUN(3)=XHELIO(3)/RS

! DEBUG
!     WRITE(6,*)' dbg ZMAG ',ZMAG
!     WRITE(6,*)' dbg RSQ ',RSQ
!     WRITE(6,*)' dbg XHELIO ',XHELIO
!     WRITE(6,*)' dbg RSSQ ',RSSQ
!     WRITE(6,*)' dbg RS ',RS
!     WRITE(6,*)' dbg USUN ',USUN
! DEBUG

      CALL SOLRAT(AA(KAESHD),II(KISHDP),FE,RS,RSSQ,R,RSQ,XSAT,RATIO)

! RATIO=0.D0 IF THE SATELLITE IS IN THE UMBRA.
!
! DEBUG
!     WRITE(6,*)' dbg  RATIO ',RATIO
! DEBUG

! COMPUTE ARGUMENT OF PERIGEE AND TRUE ANOMALY FOR THIS STEP:
      CALL ELEM(XSAT(1),XSAT(2),XSAT(3),VSAT(1),VSAT(2),VSAT(3),        &
     &          AEI,1,PKPX,GM)
!     AEI(5) IS THE ARGUMENT OF PERIGEE
! TURE OF COMMON/CELEMX/ IS THE TRUE ANOMALY
      Z=AEI(5)+TRUE

! DEBUG
!     WRITE(6,*)' dbg Z ,AEI(5),TRUE',Z,AEI(5),TRUE
!     WRITE(6,*)' dbg  LTYP1 LTYP2  LYE1',LTYP1,LTYP2,LYE1
! DEBUG

!  **********  FORM THE YARFIL FILE  BEGIN **********************


      IF(LTYP1) THEN

!  __________ FIRST ENTRY BEGIN ___________________________________

! FOR FIRST ENTRY DO
        IF(LYE1) THEN
              IF(RATIO.EQ.0.D0) THEN
! CASE FIRST ENTRY AND THE SATELLITE IS IN THE UMBRA SAVE TIMES
! AT FIRST ENTRY .. NO NEED TO COMPUTE THE Z1,Z2 AND Z ANGLES

! DEBUG
!     WRITE(6,*)' dbg first obs case the s/c is in the umbra '
! DEBUG
             RISYEN=DBLE(MJDSEC)
             FSEYEN=FSEC
             LYSHAD=.TRUE.

             ELSE
! CASE FIRST ENTRY AND THE SATELLITE IS IN THE SUNLIGHT
! DEBUG
!     WRITE(6,*)' dbg first obs case the s/c is in the sunlight'
! DEBUG
             LYSHAD=.FALSE.
                     ! IF(RATIO.EQ.0.D0
             ENDIF
! DEBUG
!     WRITE(6,*)' dbg report on LYSHAD ',LYSHAD
! DEBUG

        LYE1=.FALSE.
        RETURN
        ENDIF
!  __________ FIRST ENTRY  END ____________________________________
!  __________ OTHER ENTRY  BEGIN __________________________________

! CASE OTHER ENTRY AND THE SATELLITE IS IN THE SUNLIGHT
      IF(RATIO.EQ.1.D0) THEN
! DEBUG
!     WRITE(6,*)' dbg case the s/c is in the sunlight'
! DEBUG

           IF(LYSHAD) THEN
! THE SATELLITE JUST WENT FROM SHADOW TO SUNLIGHT SAVE EXIT TIME
! HERE COMPUTE THE Z2 ANGLE
      WRITE(6,*)' THE SATELLITE EXITED SHADOW NOW '
           Z2=AEI(5)+TRUE
           RISYEX=DBLE(MJDSEC)
           FSEYEX=FSEC
! HERE OUTPUT TIMES
           DZ=Z2-Z1
! DEBUG
!     WRITE(6,*)' dbg Z2 RISYEX FXEYEX  DZ',Z2,RISYEX,FSEYEX,DZ
      WRITE(6,*)' dbg writing on 67 SUNLIGHT '
! DEBUG
             WRITE(67)RISYEN,FSEYEN,RISYEX,FSEYEX,Z1,Z2,DZ
!            WRITE(6,*)RISYEN,FSEYEN,RISYEX,FSEYEX,Z1,Z2,DZ
           LYSHAD=.FALSE.
           ELSE
! THE SATELLITE WAS IN THE SYNLIGHT BEFORE
           LYSHAD=.FALSE.
           ENDIF
      ELSE

! CASE OTHER ENTRY AND THE SATELLITE IS IN THE UMBRA
!     WRITE(6,*)' dbg case the s/c is in the umbra'
           IF(.NOT.LYSHAD) THEN
! THE SATELLITE JUST WENT FROM SUNLIGHT TO SHADOW SAVE ENTRY TIMES
! HERE COMPUTE THE Z1 ANGLE
      WRITE(6,*)' THE SATELLITE ENTERED SHADOW NOW '
           Z1=AEI(5)+TRUE
           RISYEN=DBLE(MJDSEC)
           FSEYEN=FSEC
           LYSHAD=.TRUE.
! DEBUG
!     WRITE(6,*)' dbg Z1 RISYEN FSEYEN LYSHAD ',RISYEN,FSEYEN,LYSHAD
! DEBUG
           ELSE
! THE SATELLITE IS STILL IN  THE SHADOW
           LYSHAD=.TRUE.
           ENDIF

              ! IF(RATIO.EQ.1.D0)
      ENDIF
      RETURN
!  __________ OTHER ENTRY  END __________________________________

!  **********  FORM THE YARFIL FILE  END **********************

                 ! IF(LTYP1)
      ELSE
!     WRITE(6,*)' CASE LTYP2=.TRUE.'

! THIS IS THE SECOND GEODYN RUN - DATA REDUCTION
! COMPUTE THE YARKOVSKY/SCHACH ACCELERATION.

!  *********  COMPUTE ACCELLERATIONS **************************

!    CURRENT TIME
      TIME=DBLE(MJDSEC)+FSEC



! OPEN FILE AND READ FIRST REORD AT FIRST ENTRY
      IF(LYE1) THEN
      INQUIRE(FILE='YARFIL',EXIST=LEXIST)

      IF(LEXIST) THEN
!     WRITE(6,*)' dbg OPEN UNIT 67 '
      OPEN(UNIT=67,FILE='YARFIL',STATUS='OLD',FORM='UNFORMATTED')
  200 CONTINUE
      READ(67,END=600)T1,F1,T2,F2,Z11,Z21,DZ1
      TIME1=T1+F1
      TIME2=T2+F2
      IF(TIME.GT.TIME1.AND.TIME.GT.TIME2) GO TO 200
! DEBUG
!     WRITE(6,*)' dbg T1 F1 T2 F2 Z11 Z21 DZ1 ',T1,F1,T2,F2,Z11,Z21,DZ1
! DEBUG
      ENDIF

! DEBUG
!     WRITE(6,*)' dbg TIMES ',TIME1,TIME, TIME2
! DEBUG

              ! IF(LYE1)
      ENDIF

      LYE1=.FALSE.

                 ! IF(LTYP1)
      ENDIF

! DEBUG
!     WRITE(6,*)' dbg end of common LTYP1 and LTYP2 operations '
! DEBUG

      GO TO 700

! THIS IS THE CASE WHERE YARFIL IS EMPTY -- APPLY THE SUNLIGHT MODEL ONL
  600 CONTINUE
      LSUN=.TRUE.
!     WRITE(6,*)' dbg LSUN ',LSUN

  700 CONTINUE
! COMPUTE COSINE OF ANGLE KSI
! SCALAR PRODUCT
      COSKSI=0.D0
      DO 10 I=1,3
   10 COSKSI = COSKSI + S(I)*USUN(I)
! COMPUTE SINKSI
      SINKSI=SQRT(1.D0-COSKSI*COSKSI)
! DEBUG
!     WRITE(6,*)' dbg COSKSI ',COSKSI
!     WRITE(6,*)' dbg USUN ',USUN
!     WRITE(6,*)' dbg S ',S
!     WRITE(6,*)' dbg SINKSI ',SINKSI
! DEBUG
!
   20 CONTINUE
      LCON=.FALSE.

      IF(TIME.GE.TIME1.AND.TIME.LE.TIME2.AND..NOT.LSUN) THEN
! SHADOW
      WRITE(6,*)' DBG DATA REDUCTION WE ARE IN SHADOW '


!     COMPUTE C0 AND C1
!     COMPUTE ZT AT THIS TIME
      ZT=Z-Z11
      IF(Z11.LE.Z) D1=Z11-Z
      IF(Z11.GT.Z) D1=Z11-Z-TWOPI
      IF(Z21.GT.Z) D2=Z21-Z-TWOPI
      IF(Z21.LE.Z) D2=Z21-Z
      DELTA=SMEANM*TAU
      ET=EXP(-2*TAU/DELTA)
      C0=(1.D0-EXP(-(TWOPI-Z11)/DELTA))/(1.D0-EXP(-TWOPI/DELTA))
      C1=(1.D0-EXP(-DZ1/DELTA))/(1.D0-EXP(-(TWOPI-DZ1)/DELTA))
      GAMMAZ=C0*EXP(-ZT/DELTA)
! N MUST BE DEFINED USING A TIMING TABLE
      CALL FYEAR(MJDSEC,FSEC,YEAR)
      TORT=SATDAT(1,KK)*(EXP(SATDAT(2,KK)*(YEAR-SATDAT(3,KK))))
      N=SATDAT(4,KK)/TORT
      DN1=N*D1
      DN2=N*D2
      GAMMAX=RATIO+(1.D0-ET)**1.D-01 *(  EXP(D1/DELTA)* (COS(DN1)+      &
     &       N*DELTA*SIN(DN1))-       EXP(D2/DELTA) * (COS(DN2) +       &
     &       N*DELTA*SIN(DN2)))
      GAMMAY= N * RATIO * DELTA + (1.D0-ET)**1.D-01 * (  EXP(D2/DELTA) *&
     &        (COS(DN2) - N*DELTA*COS(DN2))-            EXP(D1/DELTA) * &
     &        (SIN(DN1) - N*DELTA*COS(DN2)))
       IF(LMOD1) THEN
      ACC(1)=AYAR*GAMMAZ*COSKSI*S(1)
      ACC(2)=AYAR*GAMMAZ*COSKSI*S(2)
      ACC(3)=AYAR*GAMMAZ*COSKSI*S(3)
!     WRITE (6,*)' dbg ACC RAPID SPIN IN SHADOW  ',ACC
       ELSE
      ACC(3)=AYAR *   COSKSI* GAMMAZ
      ACC(1)=AYAR * ( SINKSI/(1+(N*DELTA)**2.D0 ))*GAMMAX
      ACC(2)=AYAR * ( SINKSI/(1+(N*DELTA)**2.D0 ))*GAMMAY
!     WRITE (6,*)' dbg ACC SLOW ROTATING IN SHADOW  ',ACC
       ENDIF

!  SUNLIGHT
!     ELSEIF(TIME.GT.TIME2.AND.TIME.LE.TIME3.OR.LSUN) THEN
      ELSEIF(TIME.LT.TIME1.OR.LSUN) THEN
      WRITE(6,*)' DBG DATA REDUCTION WE ARE IN SUNLIGHT '
!     WRITE(6,*)' dbg CHECK LSUN -- MUST BE TRUE ',LSUN
!     COMPUTE C0 AND C1
!     COMPUTE Z AT THIS TIME
      ZT=Z-Z11
      IF(Z11.LE.Z) D1=Z11-Z
      IF(Z11.GT.Z) D1=Z11-Z-TWOPI
      IF(Z21.GT.Z) D2=Z21-Z-TWOPI
      IF(Z21.LE.Z) D2=Z21-Z
! DEBUG
!     WRITE(6,*)' dbg Z ',Z
!     WRITE(6,*)' dbg D1 D2 ',D1,D2
! DEBUG
      DELTA=SMEANM*TAU
      ET=EXP(-2*TAU/DELTA)
      C0=(1.D0-EXP(-(TWOPI-DZ1)/DELTA))/(1.D0-EXP(-TWOPI/DELTA))
      C1=(1.D0-EXP(-DZ1/DELTA))/(1.D0-EXP(-(TWOPI-DZ1)/DELTA))
      GAMMAZ=C0*C1*(1.D0-EXP(-(ZT-DZ1)/DELTA))+C0*EXP(-DZ1/DELTA)
! DEBUG
!     WRITE(6,*)' dbg DELTA  SMEANM TAU',DELTA,SMEANM,TAU
!     ET=EXP(-2*TAU/DELTA)
!     WRITE(6,*)' dbg C0 C1 GAMMAZ ',C0,C1,GAMMAZ
! DEBUG

! N MUST BE DEFINED USING A TIMING TABLE
      CALL FYEAR(MJDSEC,FSEC,YEAR)
      TORT=SATDAT(1,KK)*(EXP(SATDAT(2,KK)*(YEAR-SATDAT(3,KK))))
      N=SATDAT(4,KK)/TORT
      DN1=N*D1
      DN2=N*D2
      GAMMAX=RATIO+(1.D0-ET)**1.D-01 *(  EXP(D1/DELTA)* (COS(DN1)+      &
     &       N*DELTA*SIN(DN1))-       EXP(D2/DELTA) * (COS(DN2) +       &
     &       N*DELTA*SIN(DN2)))
      GAMMAY= N * RATIO * DELTA + (1.D0-ET)**1.D-01 * (  EXP(D2/DELTA) *&
     &        (COS(DN2) - N*DELTA*COS(DN2))-            EXP(D1/DELTA) * &
     &        (SIN(DN1) - N*DELTA*COS(DN2)))
       IF(LMOD1) THEN
!     WRITE(6,*)' dbg LMOD1 MUST BE TRUE COMPUTE ACC ',LMOD1
!     WRITE(6,*)' dbg AYAR ',AYAR
      ACC(1)=AYAR*GAMMAZ*COSKSI*S(1)
      ACC(2)=AYAR*GAMMAZ*COSKSI*S(2)
      ACC(3)=AYAR*GAMMAZ*COSKSI*S(3)
!     WRITE (6,*)' dbg ACC RAPID SPIN IN SUNLIGHT  ',ACC
       ELSE
      ACC(3)=AYAR *   COSKSI* GAMMAZ
      ACC(1)=AYAR * ( SINKSI/(1+(N*DELTA)**2.D0 ))*GAMMAX
      ACC(2)=AYAR * ( SINKSI/(1+(N*DELTA)**2.D0 ))*GAMMAY
!     WRITE (6,*)' dbg ACC SLOW ROTATING SPIN IN SUNLIGHT  ',ACC
       ENDIF


      ELSEIF(TIME.GT.TIME2) THEN
!     WRITE(6,*)' dbg MUST RESET TIMES NOW '
!     RE-SET TIMES
      READ(67,END=1000)T1,F1,T2,F2,Z11,Z21,DZ1
      TIME1=T1+F1
      TIME2=T2+F2
      LCON=.TRUE.

      ENDIF
      IF(LCON) GOTO 20
      RETURN

 1000 CONTINUE

      IF(LCON) GOTO 20
!
      RETURN
      END
