      SUBROUTINE YRVSBA(BIAS,YAWRM,BETM)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z),LOGICAL(L)
      COMMON/CONSTR/PI,TWOPI,DEGRAD,SECRAD,SECDAY
      CHARACTER*1 SHAD
      DIMENSION SUNV(3),EART(3),EARTP(3),VEL(3),XA(3)
      ERA=13.89*DEGRAD
      YB=BIAS*DEGRAD
!
      DO 1000 III=1,100
      BETAD=10.D0-DBLE(III-1)*.1D0
      BETA=BETAD*DEGRAD
      TBETA=TAN(BETA)
!
      SUNV(1)=-1.D0
      SUNV(2)=0.D0
      SUNV(3)=TAN(BETA)
      R=SQRT(SUNV(1)*SUNV(1)+SUNV(3)*SUNV(3))
      SUNV(1)=SUNV(1)/R
      SUNV(3)=SUNV(3)/R
!
      YAWMX=0.D0
!
      DO 100 I=1,43373
      IF(MOD(I,1).NE.0) GO TO 100
!
      ORBAD=DBLE(I)*.0083D0
      ORBA=ORBAD*DEGRAD
!
      EART(1)=-COS(ORBA)
      EART(2)=-SIN(ORBA)
      EART(3)=0.D0
      DOT=EART(1)*SUNV(1)
      SUNA=ACOS(DOT)
      SHAD=' '
      IF(SUNA.LT.ERA) SHAD='S'
!
      YAW=ATAN2(-TBETA,SIN(ORBA))
      E=ACOS(COS(BETA)*COS(ORBA))
      LSING=.FALSE.
      IF(ABS(SIN(E)).LE.0.00001D0) LSING=.TRUE.
      IF(.NOT.LSING) RAT=YB/SIN(E)
      IF(RAT.GT.1.D0) LSING=.TRUE.
      IF(.NOT.LSING) THEN
         B=ASIN(RAT)/DEGRAD
      ELSE
         B=0.D0
      ENDIF
      YAWD=B+YAW/DEGRAD
      ORBAP=(ORBAD-.0083D0)*DEGRAD
      YAWP=ATAN2(-TBETA,SIN(ORBAP))
      E=ACOS(COS(BETA)*COS(ORBAP))
      LSING=.FALSE.
      IF(ABS(SIN(E)).LE.0.00001D0) LSING=.TRUE.
      IF(.NOT.LSING) RAT=YB/SIN(E)
      IF(RAT.GT.1.D0) LSING=.TRUE.
      IF(.NOT.LSING) THEN
         B=ASIN(RAT)/DEGRAD
      ELSE
         B=0.D0
      ENDIF
      YAWPD=B+YAWP/DEGRAD
      YAWRAT=YAWD-YAWPD
      IF(ABS(YAWRAT).GT.YAWMX) YAWMX=ABS(YAWRAT)
!
      EARTP(1)=-COS(ORBAP)
      EARTP(2)=-SIN(ORBAP)
      EARTP(3)=0.D0
      VEL(1)=EART(1)-EARTP(1)
      VEL(2)=EART(2)-EARTP(2)
      VEL(3)=EART(3)-EARTP(3)
      V=SQRT(VEL(1)*VEL(1)+VEL(2)*VEL(2)+VEL(3)*VEL(3))
      VEL(1)=-VEL(1)/V
      VEL(2)=-VEL(2)/V
      VEL(3)=-VEL(3)/V
      XA(1)=COS(YAW)*VEL(1)+SIN(YAW)*VEL(2)
      XA(2)=-SIN(YAW)*VEL(1)+COS(YAW)*VEL(2)
      XA(3)=0.D0
      DOT=XA(1)*SUNV(1)
      SA=ACOS(DOT)/DEGRAD
!
!     WRITE(6,6000) BETAD,ORBAD,SA,SHAD,YAWD,YAWRAT
  100 END DO
!     WRITE(20,7000) BETAD,YAWMX
      IF(YAWMX.GT.YAWRM) THEN
         BETM=BETAD+.1D0
         RETURN
      ENDIF
 1000 END DO
 6000 FORMAT(' BETA, ORBA, YAW, YAWRAT ',3F10.2,3X,A1,F10.2,F10.6)
 7000 FORMAT(F10.2,2XF10.6)
      END
